### ISSUE TITLE
Latest windows binaries including InterfacePhotoScan

### ISSUE THREAD

**Issue by e-vlad** [cdcseacave/openMVS#101]
Sorry for disturbing with such request.
But is it possible build latest OpenMVS windows binaries including new tool InterfacePhotoScan.

I was try build binaries by myself, but looks like Visual Studio that going with Unity3D not enough for successful result. So It's not so easy resolve all system conflict for non coders like me.

But i really want test export from Photoscan with OpenMVS power.

Thank you.

**Comment by cdcseacave** [comment]
Unfortunately I didn't find a good way of extracting from Photoscan the data needed by OpenMVS. Therefor the interface is not enabled, and so not built.

**Comment by e-vlad** [comment]
Oh, i see.
Probably the only way is use Photoscan PRO python API (std do not support python) for export all required data.
Well will play with VisualSFM

**Comment by e-vlad** [comment]
Sorry, can i also ask about some settings explanation here or better open another "issue", or there are another way for such questions on github?

**Comment by cdcseacave** [comment]
Here might be OK, but since you asked use the forum: https://groups.google.com/forum/#!forum/openmvs

**Comment by e-vlad** [comment]
Ah, ok, thank you!
 I'll better wright expanded question about quality and memory settings on forum.
