### ISSUE TITLE
Issue with two view features

### ISSUE THREAD

**Issue by marinmarcillat** [cdcseacave/openMVS#1015]
**Describe the bug**
I have an underwater image transect with little overlap (so lots of two view features). After sparse reconstruction in Colmap (with ignore_two_view_geometry set to 0), I imported it into openMVS using InterfaceColmap, and all was going well. But at the densify step, two-view fetures seams to beexcluded, leaving blank stripes in the dense point cloud. I've tried to change several parameters (--number-views-fuse set to 2), but it didn't change anything. A clue of which parameter to change to include two views ? Any help would be highly appreciated !

Thanks a lot OpenMVS, it's a great tool !

**To Reproduce**
The image dataset: https://filesender.renater.fr/?s=download&token=0e9488f5-ec7e-4f9b-b62e-be44f3c21923
The mvs file in input of DensifyPointCloud: https://filesender.renater.fr/?s=download&token=00a25ff8-7b86-49bc-a9e6-e458291d1155

**Expected behavior**
A complete model of the transect, and not only "stripes"

**Screenshots**
Here is what I get with colmap (sparse reconstruction)
![image](https://github.com/cdcseacave/openMVS/assets/58145636/a02c9ff6-ad24-4878-94c6-fae8b6cd996d)
What I get after Interface colmap:
![image](https://github.com/cdcseacave/openMVS/assets/58145636/88328097-dd98-44b1-aef1-40641168ac28)
And what I get after DensifyPointCloud
![image](https://github.com/cdcseacave/openMVS/assets/58145636/2887450d-87db-471e-9776-abd92f2c2e13)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Build date: Nov 28 2022, 13:08:56
 - Camera Nikon D5500, ROV Victor 6000

**Additional context**
For context, this is research project to investigate deep-sea fauna on sea-mounts in south-west pacific.

**Comment by cdcseacave** [comment]
setting `--number-views-fuse 2` should do the trick, make sure you set it and start from scratch

**Comment by marinmarcillat** [comment]
Thanks for your quick answer ! Unfortunately, I tried again several time without success. I isolated the bug:

- Image + mvs file: https://filesender.renater.fr/?s=download&token=f4f4bb8e-2673-43ae-8469-e7319a7e3101
- command: DensifyPointCloud --number-views-fuse 2 -i model.mvs
- log: 

```
16:27:48 [App     ] Build date: Nov 28 2022, 13:08:56
16:27:48 [App     ] CPU: Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz (16 cores)
16:27:48 [App     ] RAM: 63.93GB Physical Memory 128.00TB Virtual Memory
16:27:48 [App     ] OS: Windows 8 x64
16:27:48 [App     ] Disk: 164.52GB (476.39GB) space
16:27:48 [App     ] SSE & AVX compatible CPU & OS detected
16:27:48 [App     ] Command line: DensifyPointCloud --number-views-fuse 2 -i model.mvs
16:27:48 [App     ] CUDA device 0 initialized: NVIDIA GeForce RTX 2080 Ti (compute capability 7.5; memory 11.00GB)
16:27:48 [App     ] Camera model loaded: platform 0; camera  0; f 1.220x1.214; poses 35
16:27:48 [App     ] Scene loaded from interface format (39ms):
        35 images (35 calibrated) with a total of 729.85 MPixels (20.85 MPixels/image)
        96689 points, 0 vertices, 0 faces
16:27:48 [App     ] The camera directions mean is unbalanced; the scene will be considered unbounded (no ROI)
16:27:48 [App     ] Point-cloud composed of 96689 points with:
 - visibility info (215383 views - 2.23 views/point):
                0 points with 1- views (0.00)
            74839 points with 2  views (77.40)
            21697 points with 3  views (22.44)
              153 points with 4+ views (0.16)
        2 min / 2.22759 mean (0.423129 std) / 5 max
16:27:49 [App     ] Preparing images for dense reconstruction completed: 35 images (1s125ms)
16:27:49 [App     ] Selecting images for dense reconstruction completed: 35 images (4ms)
Estimated depth-maps 35 (100%, 13s894ms)
Geometric-consistent estimated depth-maps 35 (100%, 12s204ms)
Geometric-consistent estimated depth-maps 35 (100%, 13s356ms)
Filtered depth-maps 35 (100%, 10s780ms)
Fused depth-maps 35 (100%, 11s800ms)
16:28:53 [App     ] Depth-maps fused and filtered: 35 depth-maps, 68145729 depths, 22999441 points (34%) (13s134ms)
16:28:54 [App     ] Densifying point-cloud completed: 22999441 points (1m6s173ms)
16:29:13 [App     ] Scene saved (18s668ms):
        35 images (35 calibrated)
        22999441 points, 0 vertices, 0 faces
16:29:16 [App     ] Point-cloud saved: 22999441 points (2s781ms)
16:29:17 [App     ] MEMORYINFO: {
16:29:17 [App     ]     PageFaultCount 13946555
16:29:17 [App     ]     PeakWorkingSetSize 8.72GB
16:29:17 [App     ]     WorkingSetSize 3.92GB
16:29:17 [App     ]     QuotaPeakPagedPoolUsage 347.58KB
16:29:17 [App     ]     QuotaPagedPoolUsage 340.48KB
16:29:17 [App     ]     QuotaPeakNonPagedPoolUsage 77.55KB
16:29:17 [App     ]     QuotaNonPagedPoolUsage 51.92KB
16:29:17 [App     ]     PagefileUsage 5.00GB
16:29:17 [App     ]     PeakPagefileUsage 10.36GB
16:29:17 [App     ] } ENDINFO
```

**Comment by marinmarcillat** [comment]
Update: I tried changing some other parameters, and the `--postprocess-dmaps 3` gave this result:
![image](https://github.com/cdcseacave/openMVS/assets/58145636/e8ca1879-1d3a-45d5-9109-18e57382494e)
It seems that the adjust-filter removes two views. 
Is this an expected behavior ? If yes, I will close this Issue

**Comment by cdcseacave** [comment]
yes, you are right, it affects this, i forgot about it, but it is also expected; you do not have to disable it but set `Min Views Filter = 1` in `Densify.ini` file and call `DensifyPointCloud.exe scene.mvs --dense-config-file Densify.ini --number-views-fuse 2`

![image](https://github.com/cdcseacave/openMVS/assets/2802670/36f05ebc-fc3b-4b86-a88e-02f4f98eb606)

**Comment by marinmarcillat** [comment]
It worked ! Thanks for your help !
