### ISSUE TITLE
Suppress/redirect logging for specific commands

### ISSUE THREAD

**Issue by xiaoxiae** [cdcseacave/openMVS#1033]
**Is your feature request related to a problem? Please describe.**
Running commands like `InterfaceCOLMAP` (and others) creates a log file, which is oftentimes undesired.

**Describe the solution you'd like**
A flag to suppress creating log files / setting their destination.

**Additional context**
I've browsed through the issues/pull requests and looked at the help for the command but could not find a way to do this.

**Comment by cdcseacave** [comment]
currently there is no param to disable the log file, but there is a compile time define for disabling the entire log: `#define TD_VERBOSE 0`

It should be easy to add a param for that, but most often if you find the log file problematic is because you probably are not using the binaries as intended: they can be called from anywhere, together with setting the working folder using `-w <folder>` param, and all other params, including inputs / outputs and logs are relative to that folder

I am open to receive a scenario in which the log files disturb if used as described above

**Comment by xiaoxiae** [comment]
Thanks for the quick response!

I use OpenMVS as a part of a photogrammetry pipeline and it's being called from a Python script in the following way.:

```python3
subprocess.Popen(
    [
        "InterfaceCOLMAP",
        "-i", self.mvs_path,
        "-o", self.mvs_path / "scene.mvs",
        "--image-folder", self.mvs_path / "images"
    ],
).communicate()
```

It feels strange that I have to be careful of where my cwd is (since that's where the log file will be written), since the command takes input/output parameters and so doesn't depend on cwd at all (besides writing to a log file).

It even creates a file when called with no parameters (or `--help`) so even when I just want to read the documentation, I have to delete a log file right after from wherever I called the command.

The solution here would be to set cwd before/after, which I'll do for now, but I think that either having an option to suppress the output or writing to the destination folder would be cleaner.

**Comment by cdcseacave** [comment]
No matter how you use the binary, everything (not only the logs) depends on
the cwd if relative paths are used, as in the example above. If you do not
set the working directory, it will be set by default to cwd

Like I said, i see many have trouble understanding this setup, and I am not
sure why, i find it so intuitive and useful, i wish all apps have this

**Comment by xiaoxiae** [comment]
Fair enough, this makes sense and I will adjust the program accordingly.

I do still think that creating log files when calling the commands with no parameters (or just `--help`) is almost always undesirable, but that might be a separate issue.

**Comment by 4CJ7T** [comment]
If you want the log in the mvs directory.
```python
subprocess.Popen(
    [
        "InterfaceCOLMAP",
        "-i", self.mvs_path,
        "-o", "scene.mvs",
        "--image-folder", "images",
        "-w", self.mvs_path
    ],
).communicate()
```
If you want the log created somewhere else or nowhere.
```python
subprocess.Popen(
    [
        "InterfaceCOLMAP",
        "-i", self.mvs_path,
        "-o", self.mvs_path / "scene.mvs",
        "--image-folder", self.mvs_path / "images",
        "-w", <a_path> or 'not_a_path'
    ],
).communicate()
```

**Comment by 4CJ7T** [comment]
Another way to write that is.
```python
subprocess.Popen(
    [
        "InterfaceCOLMAP",
        "-i", self.mvs_path,
        "-o", "scene.mvs",
        "--image-folder", "images",
        "-w", self.mvs_path
    ],
).communicate()
```

**Comment by xiaoxiae** [comment]
I was worried that this would not work since it would want to start logging first, but if it does then it's definitely much cleaner. We can probably close the issue then?

**Comment by xiaoxiae** [comment]
Closing since this seems to be resolved, feel free to open.
