### ISSUE TITLE
How to do mesh texturing with known point cloud and known camera poses only?

### ISSUE THREAD

**Issue by flolu** [cdcseacave/openMVS#1035]
How to do the mesh reconstruction and mesh texturing when **only** having access to:

- a known dense point cloud (colored, without normals),
- known camera intrinsics and extrinsics
- and the images?

I think the workflow would be as follows:

1. Import dense point cloud, cameras and images with a custom script by using [libs/MVS/Interface.h](https://github.com/cdcseacave/openMVS/blob/master/libs/MVS/Interface.h)
2. Reconstruct the mesh with `ReconstructMesh`
3. Project textures onto mesh with `TextureMesh`

But I'm worried that I would also need depth maps and for each point, a list of image IDs seeing it. Do I need those? Am I missing something?

**Comment by cdcseacave** [comment]
you need only the a list of image IDs seeing each point

**Comment by flolu** [comment]
Allright thank you! Then I will try to make that work
