### ISSUE TITLE
Empty-color stripes on textured model using COLMAP+OpenMVS

### ISSUE THREAD

**Issue by Kripner** [cdcseacave/openMVS#1036]
I used the standard COLMAP+OpenMVS pipeline as described in [colmap.github.io/cli.html](https://colmap.github.io/cli.html) and  [github.com/cdcseacave/openMVS/wiki/Usage](https://github.com/cdcseacave/openMVS/wiki/Usage) to get a textured mesh. The resulting point cloud, mesh and texture are fine, but the textured mesh is covered with orange stripes, as shown below.

![362893506_319992170358860_2486222439918074737_n](https://github.com/cdcseacave/openMVS/assets/9218121/961c442d-c239-49fe-9eeb-3d6e942e149c)

**To Reproduce**
I used the following pipeline:
```shell
colmap feature_extractor \
   --database_path ./database.db \
   --image_path ./images
colmap exhaustive_matcher \
   --database_path ./database.db
mkdir sparse
colmap mapper \
    --database_path ./database.db \
    --image_path ./images \
    --output_path ./sparse
mkdir dense
colmap image_undistorter \
    --image_path ./images \
    --input_path ./sparse/0 \
    --output_path ./dense \
    --output_type COLMAP 
    
InterfaceCOLMAP -i dense -o scene.mvs --image-folder dense/images
DensifyPointCloud scene.mvs
ReconstructMesh scene_dense.mvs
TextureMesh scene_dense_mesh.mvs
```

**Expected behavior**
There should be no orange stripes.

**Environment:**
 - Ubuntu 22.04
 - COLMAP 3.9 (Commit 567d29ea with CUDA)
 - OpenMVS x64 v2.2.0

**Additional context**
 I know from the [wiki](https://github.com/cdcseacave/openMVS/wiki/Usage) that faces that don't appear in the input images are colored orange and I made sure that all parts of the object are captured in multiple images.

**Comment by MikeCernea** [comment]
Hello Kripner, we will have a look on a random dataset, but if you could share at least a part of the images you used that might get us closer to reproducing the issue.

**Comment by Kripner** [comment]
> Hello Kripner, we will have a look on a random dataset, but if you could share at least a part of the images you used that might get us closer to reproducing the issue.

Thank you for your response! I uploaded the input photos and all the output files to OneDrive:

Photos: [https://1drv.ms/u/s!AqywjFac8We_g4kmdiDo_GjudPZq5A?e=RPn3ZV](https://1drv.ms/u/s!AqywjFac8We_g4kmdiDo_GjudPZq5A?e=RPn3ZV)
Full pipeline output: [https://1drv.ms/u/s!AqywjFac8We_g4knmQOBbxQgDmmRUQ?e=tSOdmN](https://1drv.ms/u/s!AqywjFac8We_g4knmQOBbxQgDmmRUQ?e=tSOdmN)

**Comment by MikeCernea** [comment]
Hello Kripner, after couple of tests I was not able to reproduce so I downloaded your output just to find that your textured mesh is fine as well.
Here is your mesh visualised with MeshLab:
<img width="682" alt="image" src="https://github.com/cdcseacave/openMVS/assets/75977936/510e8bea-f1bb-4594-a450-96d92df0dfa1">
Please check the Open3D options for displaying texture border, because what you shown as orange seems to correspond to texture border, seen here in MeshLab:
<img width="660" alt="image" src="https://github.com/cdcseacave/openMVS/assets/75977936/0ac4d947-2297-4547-ae3d-f89a7c56dd03">

**Comment by 4CJ7T** [comment]
Open3D viewer renders correctly if its an obj.
![image](https://github.com/cdcseacave/openMVS/assets/108303308/7b3ccda5-acea-4578-83e3-b9b468168f31)

**Comment by Kripner** [comment]
Thank you for your assistance. I have verified that the model looks fine in MeshLab, so it's probably just an issue with Open3D (although a weird one). I apologize for taking your time with this.
