### ISSUE TITLE
Using a different pointcloud for ReconstructMesh from CLI

### ISSUE THREAD

**Issue by xiaoxiae** [cdcseacave/openMVS#1045]
**Is your feature request related to a problem? Please describe.**
Running `ReconstructMesh` takes data from the `.mvs` file, even when the dense pointcloud is adjusted.

**Describe the solution you'd like**
A similar flag to `TextureMesh`'s `--mesh-file`, which overrides the `.mvs` data and uses the provided mesh instead.

**Describe alternatives you've considered**
Adjusting the contents using `Interface.h` is a possibility, but would be quite painful since I'm interacting with OpenMVS only via the command line (through Python). Other than that, I went trough the CLI options of the relevant commands and haven't been able to find a way to achieve this.

**Comment by cdcseacave** [comment]
the lastest commit on develop is saving the point cloud outside MVS file, so you can edit it and/or replace it entirely, only make sure to keep the views ID list for each point

**Comment by xiaoxiae** [comment]
Completely missed that. Thanks!
