### ISSUE TITLE
what is central or non-central camera means？

### ISSUE THREAD

**Issue by Yes-Jumby** [cdcseacave/openMVS#1057]
I am confused in central or non-central camera described in wiki interface:

_The array of platforms contains one element for each camera (central or non-central) used in the project. A Platform is represented by two arrays of Camera and Pose structures. The array of cameras contains only one camera in the case of a central camera, or multiple cameras for representing a non-central camera. For the non-central case, each camera should contain along with the camera matrix also the pose relative to the platform._

what i get is :central camera means one camera in the platform,non-central camera means multiple camera in the platform.
(i get it confirm in:https://github.com/cdcseacave/openMVS/issues/132)

but i seach central or non-central camera,it shows that they  differ in whether the external light from the world to the img plane  intersect at a point. 

I need your help:(

**Comment by cdcseacave** [comment]
here it means exactly what you deduced: one or multiple cameras on one platform,
at the end of the day it does not matter during the MVS stage, at least for now all openmvs cares is receiving one pinhole camera per input image; during SfM though it is very important to have them grouped like that, as you can estimate one pose for all the cameras on the platform
