### ISSUE TITLE
ReconstructMesh only produce .ply , no .mvs output

### ISSUE THREAD

**Issue by atdrdeterminant** [cdcseacave/openMVS#1058]
**Describe the bug**
I ran the commands following the doc. 

I get a `scene_dense.mvs` file and the corresponding `.ply` file. 
However when I run `ReconstructMesh scene_dense.mvs` I only get a `scene_dense_mesh.ply` file.  but no `mvs` file whish is needed for the refinement and to apply the texture using OpenMVS. 

Here is a screen shot of `scene_dense_mesh.ply` :

![image](https://github.com/cdcseacave/openMVS/assets/136814547/d9f39670-ff79-4f8b-b5c2-d35a4a97b202)

The output of the ReconstructMesh command is : 

10:16:37 [App     ] OpenMVS x64 v2.2.0
10:16:38 [App     ] Build date: Sep 14 2023, 11:23:02
10:16:38 [App     ] CPU: Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz (8 cores)
10:16:38 [App     ] RAM: 43.05GB Physical Memory 0B Virtual Memory
10:16:38 [App     ] OS: Linux 5.15.0-82-generic (x86_64)
10:16:38 [App     ] Disk: 87.72GB (290.57GB) space
10:16:38 [App     ] SSE & AVX compatible CPU & OS detected
10:16:38 [App     ] Command line: ReconstructMesh scene_dense.mvs
10:16:38 [App     ] Camera model loaded: platform 0; camera  0; f 0.499x0.499; poses 239
10:16:38 [App     ] Scene loaded from interface format (62ms):
        239 images (239 calibrated) with a total of 118.16 MPixels (0.49 MPixels/image)
        76776 points, 0 vertices, 0 faces
10:16:44 [App     ] Point-cloud 'scene_dense.ply' loaded: 13765120 points (6s909ms)
Points inserted 13765120 (100%, 1m9s242ms)           
10:18:05 [App     ] Delaunay tetrahedralization completed: 13765120 points -> 6562147 vertices, 40780432 (+204) cells, 81560966 (+306) faces (1m17s999ms)
Points weighted 6562147 (100%, 1m57s386ms)           
10:20:39 [App     ] Delaunay tetrahedras weighting completed: 40780636 cells, 81561272 faces (2m32s50ms)
10:22:49 [App     ] Delaunay tetrahedras graph-cut completed (5.76145e+06 flow): 4649482 vertices, 9307830 faces (2m9s964ms)
10:23:58 [App     ] Mesh reconstruction completed: 4653873 vertices, 9295384 faces (7m13s624ms)
10:25:43 [App     ] Cleaned mesh: 4636659 vertices, 9269628 faces (1m45s250ms)
10:26:23 [App     ] Cleaned mesh: 4636677 vertices, 9269670 faces (39s856ms)
10:26:43 [App     ] Cleaned mesh: 4636677 vertices, 9269670 faces (19s643ms)
10:26:44 [App     ] Mesh saved: 4636677 vertices, 9269670 faces (985ms)
10:26:44 [App     ] MEMORYINFO: {
10:26:44 [App     ]     VmPeak: 14965252 kB
10:26:44 [App     ]     VmSize:  3641572 kB
10:26:44 [App     ] } ENDINFO

**Comment by cdcseacave** [comment]
on develop the MVS file only keeps the camera info, all geometry is in external PLY;
if the MVS file does not generate, means the last one you used is unchanged and there is no reson to resave it, you can use the same one;
also, you do not have to do RefineMesh, only if you want, you can texture it directly

**Comment by cdcseacave** [comment]
so in order to select the correct PLY file you need to specify it manually, the command should look something like this:
```
TextureMesh scene.mvs -m scene_mesh.ply
```

**Comment by atdrdeterminant** [comment]
Thank you !

**Comment by cgmatter** [comment]
found myself here for the same reason - thank fucking god! you guys dope
