### ISSUE TITLE
How to solve Monocular scaling problem in single rgbd camera?

### ISSUE THREAD

**Issue by Yes-Jumby** [cdcseacave/openMVS#1062]
I had one rgbd camera,and I use colmap by rgb to get the pose,but there is a  scaling problem between pose from colmap and the depth.so how could I handle scaling problem?I need your help,thanks:)

**Comment by cdcseacave** [comment]
most probably the rgbd stores depths in meters, and so you need to scale the scene to meters as well; you can do this manually by measuring something you know and apply the scale on the reconstructed scene, or add GPS to each image, and use them in colmap to scale the scene
