### ISSUE TITLE
No scene_dense.mvs created after successful run of Densifypointcloud 

### ISSUE THREAD

**Issue by anttad** [cdcseacave/openMVS#1064]
**Describe the bug**
I am trying to get a 3D reconstruction from a video from which I extract a set of frames.
I use openMVG to get the point cloud and the scene.mvs file. 
When I try to get the scene_dense.mvs file with `DensifyPointCloud` everything seems to run fine but I get no file at the end. 

**To Reproduce**
1. `ffmpeg -i [video path] -vf "select=not(mod(n\,[frame step])),scale=1920:-1" -vsync vfr [image_folder]/%04d.png` 
2.  `python SfM_SequentialPipeline.py [image_folder] [resulting directory]` from openMVG
3. `openMVG_main_openMVG2openMVS -i sfm_data.bin -o scene.mvs -d scene_undistorted_images` from openMVG
4.  run the docker for openMVS: ` docker run -it --rm --volume [parent dir of image and resulting directory]:/dataset openmvs-ubuntu`
5. run `DensifyPointCloud scene.mvs`

The output log is : 

12:43:45 [App     ] OpenMVS x64 v2.2.0
12:43:45 [App     ] Build date: Sep 14 2023, 11:23:02
12:43:45 [App     ] CPU: Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz (8 cores)
12:43:45 [App     ] RAM: 43.05GB Physical Memory 0B Virtual Memory
12:43:45 [App     ] OS: Linux 5.15.0-82-generic (x86_64)
12:43:45 [App     ] Disk: 44.91GB (290.57GB) space
12:43:45 [App     ] SSE & AVX compatible CPU & OS detected
12:43:45 [App     ] Command line: DensifyPointCloud scene.mvs
12:43:45 [App     ] Camera model loaded: platform 0; camera  0; f 0.499x0.499; poses 510
12:43:45 [App     ] Scene loaded from interface format (102ms):
        510 images (510 calibrated) with a total of 1008.54 MPixels (1.98 MPixels/image)
        171549 points, 0 vertices, 0 faces
12:43:45 [App     ] Found a camera not pointing towards the scene center; the scene will be considered unbounded (no ROI)
12:43:45 [App     ] Point-cloud composed of 171549 points with:
 - visibility info (606957 views - 3.54 views/point):
                0 points with 1- views (0.00%)
            80557 points with 2  views (46.96%)
            35244 points with 3  views (20.54%)
            55748 points with 4+ views (32.50%)
        2 min / 3.5381 mean (2.43852 std) / 42 max
12:43:51 [App     ] Preparing images for dense reconstruction completed: 510 images (5s332ms)
12:43:51 [App     ] Selecting images for dense reconstruction completed: 510 images (352ms)
Estimated depth-maps 510 (100%, 40m14s374ms) 

**Expected behavior**
have a `scene_dense.mvs` and `scene_dense.ply` files

**Comment by anttad** [comment]
I think it should not stop after: 
 Estimated depth-maps 239 (100%, 18m40s804ms)

**Comment by anttad** [comment]
I had a permission problem on the docker with the mounted volume. It's fixed now ! thank you

**Comment by 853142898** [comment]
I encountered the same problem as you, could you tell me how you solved it?

**Comment by SaraZiWang** [comment]
> I encountered the same problem as you, could you tell me how you solved it?

Hi, I had a similar issue, and I managed solving the issue by changing file path and rerun.

**Comment by 853142898** [comment]
> > I encountered the same problem as you, could you tell me how you solved it?
> 
> Hi, I had a similar issue, and I managed solving the issue by changing file path and rerun.

Thanks! I finally solved my problem. It was caused by insufficient memory.
