### ISSUE TITLE
Does openMVS support running under arm64?

### ISSUE THREAD

**Issue by BaiDXia** [cdcseacave/openMVS#1066]
I want to run openMVG on rk3588, but I get a segmentation fault when RefineMesh
Mistake.

root@ok3588:/home/forlinx/MVS/openMVS_build/bin# ./RefineMesh /home/forlinx/MVS/openMVG_build/software/SfM/dataset/eglise/result/reconstruction_dir/scene_dense_mesh.mvs
19:09:48 [App     ] OpenMVS x32 v2.2.0
19:09:48 [App     ] Build date: Oct 11 2023, 16:29:30
19:09:48 [App     ] CPU:  (8 cores)
19:09:48 [App     ] RAM: 7.43GB Physical Memory 0B Virtual Memory
19:09:48 [App     ] OS: Linux 5.10.66 (aarch64)
19:09:48 [App     ] Disk: 5.40GB (13.73GB) space
19:09:48 [App     ] warning: no SSE compatible CPU or OS detected
19:09:48 [App     ] Command line: RefineMesh /home/forlinx/MVS/openMVG_build/software/SfM/dataset/eglise/result/reconstruction_dir/scene_dense_mesh.mvs
19:09:48 [App     ] Scene loaded (297ms):
        85 images (85 calibrated) with a total of 203.39 MPixels (2.39 MPixels/image)
        0 points, 300001 vertices, 599401 faces
Decimated faces 374626 (100%, 6s722ms)
19:10:00 [App     ] Cleaned mesh: 112686 vertices, 224755 faces (8s600ms)
19:10:01 [App     ] Cleaned mesh: 112676 vertices, 224755 faces (902ms)
19:10:43 [App     ] Cleaned mesh: 99335 vertices, 197420 faces (796ms)
19:10:44 [App     ] Mesh subdivided: 112676/224755 -> 99335/197420 vertices/faces
Processed iterations 24 (53.33%, 6m1s, ETA 5m)... Segmentation fault

Once ran to this：
root@ok3588:/home/forlinx/MVS/openMVS_build/bin# ./RefineMesh /home/forlinx/MVS/openMVG_build/software/SfM/dataset/eglise/result/reconstruction_dir/scene_dense_mesh.mvs
18:36:55 [App     ] OpenMVS x32 v2.2.0
18:36:55 [App     ] Build date: Oct 11 2023, 16:29:30
18:36:55 [App     ] CPU:  (8 cores)
18:36:55 [App     ] RAM: 7.43GB Physical Memory 0B Virtual Memory
18:36:55 [App     ] OS: Linux 5.10.66 (aarch64)
18:36:55 [App     ] Disk: 5.43GB (13.73GB) space
18:36:55 [App     ] warning: no SSE compatible CPU or OS detected
18:36:55 [App     ] Command line: RefineMesh /home/forlinx/MVS/openMVG_build/software/SfM/dataset/eglise/result/reconstruction_dir/scene_dense_mesh.mvs
18:36:55 [App     ] Scene loaded (288ms):
        85 images (85 calibrated) with a total of 203.39 MPixels (2.39 MPixels/image)
        0 points, 300001 vertices, 599401 faces
Decimated faces 374626 (100%, 6s732ms)
18:37:08 [App     ] Cleaned mesh: 112686 vertices, 224755 faces (8s624ms)
18:37:09 [App     ] Cleaned mesh: 112676 vertices, 224755 faces (915ms)
18:37:51 [App     ] Cleaned mesh: 99335 vertices, 197420 faces (786ms)
18:37:51 [App     ] Mesh subdivided: 112676/224755 -> 99335/197420 vertices/faces
Processed iterations 45 (100%, 10m56s171ms)
Killed

**Comment by cdcseacave** [comment]
this look like an OOM, for now refinemesh is not scalable, you can safely skip this stage if you do not have enough memory
