### ISSUE TITLE
Retrieving non-textured triangles

### ISSUE THREAD

**Issue by xiaoxiae** [cdcseacave/openMVS#1072]
**Is your feature request related to a problem? Please describe.**
Since the non-textured triangles don't look good, it would be great to obtain their indexes so they can be inpainted / removed / etc.

**Describe the solution you'd like**
A way to retrieve the triangles (besides parsing the texture, which is slow and error-prone). It would perhaps be possible to determine the non-textured triangles by their UV coordinates, which could be set to some constant value? Alternatively, an argument to export a list of non-textured triangles to a file.  

**Describe alternatives you've considered**
Parsing the texture, which is slow and error-prone.

This is related (but more general) to #576.

**Comment by cdcseacave** [comment]
yes, that list is available during texturing, but not exported
you should be able to select those triangles if you check that the `uv` coordinates are equal for all 3 vertices of that face
pls confirm this is working

**Comment by xiaoxiae** [comment]
Yes, this seems to work perfectly, thank you! I think that you can close both issues.

However, this was not trivial to achieve since both Python libraries I tried to use (trimesh and open3d) don't support the PLY format that is exported by OpenMVS. What I had to do is take the raw data from trimesh's PLY loader and use, which wasn't too difficult but you should keep it in mind if you want to do the same.

Sample code:

```python3
import numpy as np
from trimesh.exchange.ply import _parse_header, _ply_ascii, _ply_binary

def get_untextured_triangles(path) -> list[int]:
    """Return the indexes of triangles that are not textured."""
    # has to be done this way because of OpenMVS' PLY format
    # (Trimesh doesn't recognize the uv textures)
    with open(path, "rb") as f:
        elements, is_ascii, image_name = _parse_header(f)

        if is_ascii:
            _ply_ascii(elements, f)
        else:
            _ply_binary(elements, f)

    untextured_triangles = []
    for i, face_data in enumerate(elements['face']['data']):
        uv1x, uv1y, uv2x, uv2y, uv3x, uv3y = face_data[-1][-1]

        if np.allclose(uv1x, [uv1x, uv2x, uv3x]) and np.allclose(uv1y, [uv1y, uv2y, uv3y]):
            untextured_triangles.append(i)

    return untextured_triangle
```

**Comment by xiaoxiae** [comment]
Closing this issue since it's resolved.
