### ISSUE TITLE
Build Error on VS 2015 R2

### ISSUE THREAD

**Issue by xialang2012** [cdcseacave/openMVS#108]
I built OpenMVS on VS2015, but it showed some errors, 

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2660	'jpeg_destroy_decompress': function does not take 1 arguments	IO	C:\Users\xialang2012\Documents\Visual Studio 2013\Projects\ODM-Win\OpenSfM\openMVS\libs\IO\ImageJPG.cpp	120	

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2660	'jpeg_destroy_decompress': function does not take 1 arguments	IO	

> C:\Users\xialang2012\Documents\Visual Studio 2013\Projects\ODM-Win\OpenSfM\openMVS\libs\IO\ImageJPG.cpp	120	
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	IO	C:\Users\xialang2012\Documents\Visual Studio 2013\Projects\ODM-Win\OpenSfM\openMVS\libs\IO\ImageTIFF.cpp	68	

The JPG and TIff libraries I used come from openCV 3.0.

**Comment by xialang2012** [comment]
No one is here?

**Comment by xialang2012** [comment]
> 5>------ Build started: Project: MVS, Configuration: Release x64 ------
> 5>  Generating CXX prefix header C:\Users\xialang2012\Documents\Visual Studio 2013\Projects\ODM-Win\OpenSfM\openMVS\libs\MVS\x64\Release\cotire\MVS_CXX_prefix.hxx
> 5>cl : Command line warning D9025: overriding '/Zm170' with '/Zm150'
> 5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE3'
> 5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE3'
> 5>  Common.cpp
> 5>  Unknown compiler version - please run the configure tests and report the results
> 5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(46): error C2061: syntax error: identifier '_General_ptr_iterator_tag'
> 5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(65): error C2061: syntax error: identifier '_Really_trivial_ptr_iterator_tag'
> 5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(68): error C2995: '_FwdIt std::_Uninitialized_copy_unchecked1(_InIt,_InIt,_FwdIt)': function template has already been defined
> 5>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(45): note: see declaration of 'std::_Uninitialized_copy_unchecked1'
> 5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(82): error C2061: syntax error: identifier 'input_iterator_tag'
> 5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(91): error C2061: syntax error: identifier 'random_access_iterator_tag'
> 5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(96): error C2995: '_FwdIt std::_Uninitialized_copy1(_InIt,_InIt,_FwdIt)': function template has already been defined
> 5>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(81): note: see declaration of 'std::_Uninitialized_copy1'

**Comment by xialang2012** [comment]
It is ready...

**Comment by MichaleWong** [comment]
hi， have you fix it？

**Comment by xialang2012** [comment]
OpenMVS was built well. The problem was the dis-corresponding JPEG TIFF libraries which required by OpenMVS.

**Comment by woshidashabizhende** [comment]
> > 5>------ Build started: Project: MVS, Configuration: Release x64 ------
> > 5>  Generating CXX prefix header C:\Users\xialang2012\Documents\Visual Studio 2013\Projects\ODM-Win\OpenSfM\openMVS\libs\MVS\x64\Release\cotire\MVS_CXX_prefix.hxx
> > 5>cl : Command line warning D9025: overriding '/Zm170' with '/Zm150'
> > 5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE3'
> > 5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE3'
> > 5>  Common.cpp
> > 5>  Unknown compiler version - please run the configure tests and report the results
> > 5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(46): error C2061: syntax error: identifier '_General_ptr_iterator_tag'
> > 5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(65): error C2061: syntax error: identifier '_Really_trivial_ptr_iterator_tag'
> > 5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(68): error C2995: '_FwdIt std::_Uninitialized_copy_unchecked1(_InIt,_InIt,_FwdIt)': function template has already been defined
> > 5>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(45): note: see declaration of 'std::_Uninitialized_copy_unchecked1'
> > 5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(82): error C2061: syntax error: identifier 'input_iterator_tag'
> > 5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(91): error C2061: syntax error: identifier 'random_access_iterator_tag'
> > 5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(96): error C2995: '_FwdIt std::_Uninitialized_copy1(_InIt,_InIt,_FwdIt)': function template has already been defined
> > 5>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory(81): note: see declaration of 'std::_Uninitialized_copy1'

have you fix it？

**Comment by cdcseacave** [comment]
pls use latest VS
