### ISSUE TITLE
Is PointProjectP division applied twice?

### ISSUE THREAD

**Issue by paulinus** [cdcseacave/openMVS#109]
This is more a question than an issue.

### Specifications like the version of the project, operating system, and hardware

Master branch on a mac. Both using clang and gcc.

### Steps to reproduce the problem

The camera method [`PointProjectP`](https://github.com/cdcseacave/openMVS/blob/79bacacff692ffd9b8631dcf729f6f8a6c76e8be/libs/MVS/Camera.h#L255-L259) returns a `TPoint2`. The point is build from a `TPoint3` and then divided by the last coordinate, z:
```
return ((const TPoint2<TYPE>&)q)*INVERT(q.z);
```

When debugging the code, i'm seeing that the [following constructor](https://github.com/cdcseacave/openMVS/blob/79bacacff692ffd9b8631dcf729f6f8a6c76e8be/libs/Common/Types.h#L1295) is called to build the `TPoint2`:
```
explicit inline TPoint2(const cv::Point3_<TYPE>& pt) : Base(pt.x/pt.z,pt.y/pt.z) {}
```
This constructor is also doing the division by the last coordinate of the `TPoint3`. So projections end up being divided by z twice.

The result on my tests is that the colors of the pointclouds totally misaligned. Curiously enough, the point cloud it self looks ok, so probably the functions building the pointcloud are not using this particular projection method.

I'm assuming it must be related to my compilation since openMVS work great for others.

Is anyone else observing this behavior?

**Comment by cdcseacave** [comment]
If TPoint2 is returned then the constructor you displayed is not called cause it expects a TPoint3.

**Comment by paulinus** [comment]
Thanks for the explanation. That makes sense. First there is a cast to TPoint2 and then the product between a TPoint2 and `INVERT(q.z)`.

Unfortunately, what i'm seeing on the debugger is that the casting expression
```
((const TPoint2<TYPE>&)q)
```
calls that constructor.

Again, i realize that this must not be happening for anyone else. But i fail to understand why.

**Comment by cdcseacave** [comment]
so try replace `return ((const TPoint2<TYPE>&)q)*INVERT(q.z);` with `return TPoint2<TYPE>(q);`

**Comment by paulinus** [comment]
yes, that is what I did (https://github.com/paulinus/openMVS/commit/f81512073764110e01527ed61f97de80d4b1a149) and it fixes the texturing problem on by side. But i really wonder why it does work for others without that change.

Also, even after that change things are not perfectly aligned so i'm still looking for something wrong on my setup.

**Comment by cdcseacave** [comment]
Is this happening for you only on mac?

**Comment by paulinus** [comment]
Only tested on mac for now. The change should not break anything on other platforms, but did not test it.

Just got the first reconstruction working. I get random segmentation faults which i don't manage to reproduce in debug mode. Some asserts fail on debug mode and it is hard to reach the segmentation fault before that.

**Comment by cdcseacave** [comment]
Sorry to hear you face so many problems on Mac. I do not have a Mac OS to test on, so you are probably the first person to compile and use it on Mac.
You can easily disable all ASSERTs in debug mode, by defining ASSERT to nothing in Config.h.

**Comment by paulinus** [comment]
Just found the other source of my problems. It seems that they were caused by me running Densify from the same folder all the time. Previously computed depthmap of other datasets were stored on the folder and not recomputed for new datasets. Does this make sense? Should i always run from the folder of each dataset?

**Comment by cdcseacave** [comment]
Thx! Is this fixing your problem?
Apart of this, did you face any problems when compiling on Mac?

**Comment by paulinus** [comment]
Problem fixed, yes.

Apart from that, there is also segfault on `Scene::ExportCamerasMLP` when using `_vsntprintf`. I've deactivated the whole function to make it pass.

**Comment by cdcseacave** [comment]
I know about `_vsntprintf`, it crashes in Ubuntu too, with no apparent reason, I have now idea how to fix it.

But regarding the building process, it was working ok on Mac the stept I posted on Wiki? Sorry for bothering you with this, but I do not have a Mac to test.

**Comment by paulinus** [comment]
I had to disable libTIFF for building. I've just commented the corresponding lines in the CMakeLists.

Apart from that, just following the instructions worked.
