### ISSUE TITLE
error of image center position or image scale

### ISSUE THREAD

**Issue by flashlau** [cdcseacave/openMVS#1091]
I have images, pointclouds and camera trajectory. Then I generate a mvs file by calling "interface.h". But all image center points (green) do not at the center of their rectangle region.
![Screenshot from 2024-01-11 13-42-21](https://github.com/cdcseacave/openMVS/assets/12620265/fd1847e5-b41d-47be-b6a2-9c1fdeffc8ef)

I only have one camera. So I set 
`camera.K = intrinsic_mat;`
`camera.R = Interface::Mat33d::eye();`
`camera.C = Interface::Pos3d(0, 0, 0);`
then I set N poses for N images as follows: 
`pose.R = R;`
`pose.C = -R.t()*t;`
where R and t are from transformation matrix (4x4, from World coordinate to Camera coordinate)
The camera trajectory and pointcloud in Viewer looks good, but the image center or image scale must be wrong.
I cannot find the bug. Did I make a mistake at any step or miss any parameter?"

**Comment by cdcseacave** [comment]
Do you set the image resolution in the one camera you initialized?

Are you sure you set the pose correctly? Inn the screenshot i see only the cameras and not the point cloud.

**Comment by flashlau** [comment]
yes, I hide the point-cloud in Viewer in order to see the green points clearly.
And I set 
`camera.width = img_w;`
`camera.height = img_h;`
`double fScale = (double)1 / double(max(img_w, img_h));`
then fx, fy, cx, cy in camera.K are all divided by fScale.
but width and height parameter are optional when K is normalized (mentioned in "Interface.h")
![Screenshot from 2024-01-12 09-24-07](https://github.com/cdcseacave/openMVS/assets/12620265/dba652dc-2f13-4dfd-ac5e-79380389ee00)

**Comment by cdcseacave** [comment]
no need to normalize if you set the width and h, pls try that

**Comment by flashlau** [comment]
I comment the normalization part and remain camera.width, camera.height and camera.K.
then  re-generate mvs file. 
in Viewer, (we hide point cloud)
![Screenshot from 2024-01-12 11-25-28](https://github.com/cdcseacave/openMVS/assets/12620265/b5bca0a9-3097-4013-9cbd-0af3ec53a5dc)
 the size of camera  becomes 0 ?

**Comment by cdcseacave** [comment]
Strange. You can put a break point where the MVS scene you generate is read, and check that you get the values you expect.

**Comment by flashlau** [comment]
> Strange. You can put a break point where the MVS scene you generate is read, and check that you get the values you expect.
in this line :         
[if (!scene.Load(fileName, true))](https://github.com/cdcseacave/openMVS/blob/ce03889e2055a3d6cbcae9dd5a93b5eeea94b909/apps/Viewer/Scene.cpp#L233)

I found the camera.K value in "scene.images._vector.camera.K.val" is NOT equal to that of  "scene.platforms._vector.cameras._vector.K.val", why?

**Comment by cdcseacave** [comment]
depends, is K in platforms normalized?
do you change the resolution?
simplest set K in platforms not normalized, set width and height too, and use the same resolution when u use it

**Comment by flashlau** [comment]
> no need to normalize if you set the width and h, pls try that

I found that it's caused by:
`    camera.K = cam_in;
    // camera.width = img_w;
    // camera.height = img_h;

    double fScale = (double)1 / double(max(img_w, img_h));
    camera.K(0, 0) *= fScale;
    camera.K(1, 1) *= fScale;
    camera.K(0, 2) *= fScale;
    camera.K(1, 2) *= fScale;
`
no need to normalize K.

**Comment by flashlau** [comment]
> no need to normalize if you set the width and h, pls try that

I found that it's caused by:
`
    camera.K = cam_in;
    double fScale = (double)1 / double(max(img_w, img_h));
    camera.K(0, 0) *= fScale;
    camera.K(1, 1) *= fScale;
    camera.K(0, 2) *= fScale;
    camera.K(1, 2) *= fScale;
`

no need to normalize K.

**Comment by flashlau** [comment]
> Strange. You can put a break point where the MVS scene you generate is read, and check that you get the values you expect.

This bug is caused by my fault. I called "ARCHIVE::SerializeSave" but set the "version" parameter to 0 which stop the serialization of camera size. Just remove it to use the default value.

**Comment by flashlau** [comment]
> depends, is K in platforms normalized? do you change the resolution? simplest set K in platforms not normalized, set width and height too, and use the same resolution when u use it

Many thanks for your help! @cdcseacave
