### ISSUE TITLE
ReconstructMesh | Dense point cloud file fails to load

### ISSUE THREAD

**Issue by 5VK8Y** [cdcseacave/openMVS#1093]
Dense point clouds stored as PLY seemingly fail to load when there is too many points. When stored as MVS it successfully loads.

**Comment by cdcseacave** [comment]
can u give more details? what means too many points? in what way it fails? a way to reproduce? etc

**Comment by 5VK8Y** [comment]
1280x | 87 images (87 calibrated) with a total of 90.59 MPixels (1.04 MPixels/image) loads 10,191,484 points
2560x | 87 images (87 calibrated) with a total of 362.57 MPixels (4.17 MPixels/image) does not load 38,788,012 points

Command line: `DensifyPointCloud -i scene.mvs --resolution-level 0 --max-resolution 2560 --number-views-fuse 4 --estimate-colors 0 --estimate-roi 0 --remove-dmaps 1 --tower-mode 0 -w C:\Users\5VK8Y\Workspace\project_00\mvs`

Command line: `ReconstructMesh -i scene_dense.mvs -p scene_dense.ply --constant-weight 0 --quality-factor 0 -w C:\Users\5VK8Y\Workspace\project_00\mvs` does not log `Point-cloud 'scene_dense.ply' loaded` and uses the existing point cloud in the archive instead.

Dataset: https://gofile.io/d/ZUGshL

**Comment by cdcseacave** [comment]
I think I solved the problem, can you pls try latest develop?

**Comment by 5VK8Y** [comment]
It is working. Danke schoen!
