### ISSUE TITLE
where is the origin of the camera pose and,what unit does the pointcloud used

### ISSUE THREAD

**Issue by GYH-skywalker** [cdcseacave/openMVS#1096]
i want to know where is the origin of the camera pose and pointcloud coordinates ,and how to kown the origin or pivot

**Comment by cdcseacave** [comment]
maybe I do not understand the question, but if you ask what is the position of a camera pose in word coordinates the answer is `C`, in camera space is of course `0,0,0`

the origin and rotation and scale of the world coordinates depends on the SfM solution, is there are only images at SfM time, all are arbitrarily, however if there is also GPS it is possible to have an absolute position, usually in ENU
