### ISSUE TITLE
Since the .mvs format does not store point clouds, --export-type obj cannot export obj.

### ISSUE THREAD

**Issue by SSground** [cdcseacave/openMVS#1098]
TextureMesh scene.mvs --mesh-file scene_dense_mesh.ply --export-type obj 
Error LOG;
Segmentation fault (core dumped)

 --mesh-file  and  --export-type  obj is not supported

**Comment by SSground** [comment]
> solved, pls try latest develop

The save and load obj in this step（TextureMesh ） have been solved.
But in this step(ReconstructMesh) save obj only saves the points(v * * *) and does not save the face(f */* */* */*) information.

**Comment by cdcseacave** [comment]
sry for that, pls try latest develop

**Comment by SSground** [comment]
![image](https://github.com/cdcseacave/openMVS/assets/27821863/bdae0767-40d9-4ce7-a94a-fb1ab2fe42d4)
There seems to be a problem with the generated obj. The latter step[TextureMesh] cannot be used, and there is an error when opening meshlab.

**Comment by SSground** [comment]
There seems to be a problem with the generated obj. The latter step[TextureMesh] cannot be used, and there is an error when opening meshlab.

**Comment by SSground** [comment]
> TextureMesh

I found out that it was a problem written by usemtl in obj.cpp, and mat.name is empty, causing the mtl file to not write the material.
It's solved now, thanks

**Comment by Yao-DY** [comment]
I encountered while using the latest release version (2.3.0). When will the fix be released for this issue? Should I now use the develop branch to compile it myself?

**Comment by cdcseacave** [comment]
There is no issue. All is working fine.
