### ISSUE TITLE
DensifyPointCloud error: failed loading image header

### ISSUE THREAD

**Issue by citystrawman** [cdcseacave/openMVS#1106]
**Describe the bug**
I am using DensifyPointCloud to generate a mvs file (I use colmap as my sfm processing software): 

```
DensifyPointCloud --input-file  E:\sfm_mvs_pipeline_test\mid_data\mvs\model_colmap.mvs
--working-folder E:\sfm_mvs_pipeline_test\mid_data\colmap_working_folder 
--output-file E:\sfm_mvs_pipeline_test\mid_data\mvs\model_dense.mvs 
--archive-type -1
```
the program could load camera model, image as well as scene, then there comes the error messages:
```
...load camera model and images, lines omitted... 
16:57:47 [App     ] Image loaded  31: 202211161443308.jpg
16:57:47 [App     ] Image loaded  32: 202211161443309.jpg
16:57:47 [App     ] Scene loaded from interface format (1s427ms):
        33 images (33 calibrated) with a total of 373.87 MPixels (11.33 MPixels/image)
        20713 points, 0 vertices, 0 faces
16:57:47 [App     ] The camera directions mean is unbalanced; the scene will be considered unbounded (no ROI)
16:57:47 [App     ] error: does not seem to be a tower: X(0.65), Y(26.43), Z(632.61)
16:57:47 [App     ] Point-cloud composed of 20713 points with:
 - visibility info (113717 views - 5.49 views/point):
                0 points with 1- views (0.00)
             3980 points with 2  views (19.21)
             5448 points with 3  views (26.30)
            11285 points with 4+ views (54.48)
        2 min / 5.49013 mean (4.50841 std) / 43 max
16:57:47 [App     ] error: failed loading image header
16:57:47 [App     ] error: failed loading image header
...  lines omitted
16:57:47 [App     ] error: failed reloading image 'E:/sfm_mvs_pipeline_test/mid_data/colmap_working_folder/images/2022111614433016.jpg'
16:57:47 [App     ] error: failed reloading image 'E:/sfm_mvs_pipeline_test/mid_data/colmap_working_folder/images/2022111614433014.jpg'
16:57:47 [App     ] error: failed reloading image 'E:/sfm_mvs_pipeline_test/mid_data/colmap_working_folder/images/20221116144330.jpg'
...  lines omitted
16:57:48 [App     ] error: preparing images for dense reconstruction failed (errors loading images)
16:57:48 [App     ] MEMORYINFO: {
16:57:48 [App     ]     PageFaultCount 31727
16:57:48 [App     ]     PeakWorkingSetSize 118.13MB
16:57:48 [App     ]     WorkingSetSize 111.14MB
16:57:48 [App     ]     QuotaPeakPagedPoolUsage 462.93KB
16:57:48 [App     ]     QuotaPagedPoolUsage 462.82KB
16:57:48 [App     ]     QuotaPeakNonPagedPoolUsage 24.95KB
16:57:48 [App     ]     QuotaNonPagedPoolUsage 24.83KB
16:57:48 [App     ]     PagefileUsage 187.98MB
16:57:48 [App     ]     PeakPagefileUsage 195.31MB
16:57:48 [App     ] } ENDINFO
```
 
I searched this error and there are several posts like #644  #521  #402  but there's no detailed solution on it.

I appreciate if anyone could help solve this issue. Thank you.

**Desktop (please complete the following information):**
 - OS: windows 10

**ScreenShot**
![image](https://github.com/cdcseacave/openMVS/assets/9004748/a81c9386-059f-4cdc-af08-fff7a3ca1d6c)

![image](https://github.com/cdcseacave/openMVS/assets/9004748/ce4c13e5-9a17-4da8-80c6-64d32db1f736)

**Comment by citystrawman** [comment]
I just found that this problem is because that DensifyCLoud requires the working folder as the colmap input folder(the folder that contains images, sparse and stereo), so I copied these into the working folder that I set, and now it could work. 
However, when the program runs "Estimated depth-maps", it pops out errors: 
![image](https://github.com/cdcseacave/openMVS/assets/9004748/a4ac78fb-5653-42a4-8c13-4e77e8839a37)
I will close this issue and try to solve the new problem.....

**Comment by zhangxingAI** [comment]
> I just found that this problem is because that DensifyCLoud requires the working folder as the colmap input folder(the folder that contains images, sparse and stereo), so I copied these into the working folder that I set, and now it could work. However, when the program runs "Estimated depth-maps", it pops out errors: ![image](https://private-user-images.githubusercontent.com/9004748/303204484-a4ac78fb-5653-42a4-8c13-4e77e8839a37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTQzNDAsIm5iZiI6MTcyNTYxNDA0MCwicGF0aCI6Ii85MDA0NzQ4LzMwMzIwNDQ4NC1hNGFjNzhmYi01NjUzLTQyYTQtOGMxMy00ZTc3ZTg4MzlhMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDkxNDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWVhN2QwMTYwODU5Yzc0MjdmMDc1NmVlMjVjODcwMThmMWZiZjBiOWFjZTBjZjVjNzJmMTM2ZThiY2EyNWNlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GmwQil-jASFRTyPAPH1C0uV0QCyEUiMBL50sYynJLmQ) I will close this issue and try to solve the new problem.....

Did you solve the problem?
