### ISSUE TITLE
problem of the textured mesh

### ISSUE THREAD

**Issue by xialang2012** [cdcseacave/openMVS#111]
I open the textured mesh in Meshlab, but it does not work well

> In mesh file scene_dense_mesh_texture.obj: Failure loading textures: scene_dense_mesh_texture_material_0_map_Kd.jpg.

The scene_dense_mesh_texture_material_0_map_Kd.jpg size is about 100 MB, and the scene_dense_mesh_texture.obj is about 700 MB.

Is it due to the material image size is too large?

**Comment by cdcseacave** [comment]
Yes. You can simply downscale the JPG image, or when you run the texture module, select resolution-level 2 or higher.

**Comment by xialang2012** [comment]
Yes I used 

> TextureMesh.exe --resolution-level 3  scene_dense_mesh.mvs

to get a small size of obj and material image files with 54 input images. But when the image number is larger than 150, the mesh lab still failed to load the textured obj file correctly. I wonder if we can produce material images one by one, and each material image with constant pixel number, e.g. 4096, just like other texture tools do.

**Comment by cdcseacave** [comment]
Currently it is not supported, but it is on todo list.

**Comment by xialang2012** [comment]
Just waiting

**Comment by liiiliq** [comment]
> Currently it is not supported, but it is on todo list.

Thanks for your answer, can you please tell me if this function is currently available?

**Comment by graduate0629** [comment]
> Currently it is not supported, but it is on todo list.

Hello! I have a problem using TextureMesh.exe and the texture mapping results are all orange. Is this because the number of images exceeds 150? I use openmvs v1.1.1 Has this problem been solved in the latest version? I would be very grateful if you could answer this question.
