### ISSUE TITLE
Preserve point cloud visibility information when calculating texture

### ISSUE THREAD

**Issue by CanCanZeng** [cdcseacave/openMVS#1112]
I tried the latest version of OpenMVS(v2.3.0) and found that the structure of the MVS file has been changed, removing point cloud visibility information. I need to use this information to perform outlier filtering in texturing stage. What should I do?

**Comment by cdcseacave** [comment]
nothing has been removed, the visibility info is either in the MVS file or the generated PLY (default) file, depending on what file format you used

**Comment by CanCanZeng** [comment]
Thank you for your quick reply!
So I can reload the point cloud, just like you did during mesh reconstruction. https://github.com/cdcseacave/openMVS/blob/ce03889e2055a3d6cbcae9dd5a93b5eeea94b909/apps/ReconstructMesh/ReconstructMesh.cpp#L354  Is that correct for my understanding?

**Comment by cdcseacave** [comment]
yes
