### ISSUE TITLE
 exception thrown: class version class SEACAVE::cList<class MVS::Platform,class MVS::Platform const & __ptr64,1,16,unsigned int>

### ISSUE THREAD

**Issue by xiaoxu1316** [cdcseacave/openMVS#1119]
After the compilation of openmvs is completed, the scene dense.mvs file generated when using the dense point cloud function is the same as scene.mvs, but the file that can generate scene dense.ply is viewed by meshlab and generates a dense point cloud. Later, when I used the official scene dense.mvs to generate the mesh reconstruction, an error occurred, and it stopped directly.
     The error displayed is " exception thrown: class version class SEACAVE::cList<class MVS::Platform,class MVS::Platform const & __ptr64,1,16,unsigned int>”
This is the full PowerShell error
16:59:44 [App     ] OpenMVS x64 v2.3.0
16:59:44 [App     ] Build date: Mar  7 2024, 11:45:55
16:59:44 [App     ] CPU: AMD Ryzen 7 7735H with Radeon Graphics (16 cores)
16:59:44 [App     ] RAM: 15.19GB Physical Memory 128.00TB Virtual Memory
16:59:44 [App     ] OS: Windows 8 x64
16:59:44 [App     ] Disk: 165.00GB (274.71GB) space
16:59:44 [App     ] SSE & AVX compatible CPU & OS detected
16:59:44 [App     ] Command line: ReconstructMesh scene_dense.mvs -w D:\MVS\openMVS-master\data
16:59:44 [App     ] MapSMtoCores for SM 8.9 is undefined; default to use 64 cores/SM
16:59:45 [App     ] CUDA device 0 initialized: NVIDIA GeForce RTX 4060 Laptop GPU (compute capability 8.9; memory 8.00GB)
16:59:45 [App     ] exception thrown: class version class SEACAVE::cList<class MVS::Platform,class MVS::Platform const & __ptr64,1,16,unsigned int>
 The compilation of openmvs is a success，So what can I do to fix this

**Comment by cdcseacave** [comment]
see the wiki or the python scripts on how to use the library

**Comment by xiaoxu1316** [comment]
I've found out how to use it from some articles, but I ran into this error when generating and don't know how to fix it. I would appreciate it if you could tell me

**Comment by xiaoxu1316** [comment]
> 请参阅 Wiki 或 Python 脚本，了解如何使用该库

I've found out how to use it from some articles, but I ran into this error when generating and don't know how to fix it. I would appreciate it if you could tell me

**Comment by DanielMeMyself** [comment]
I have met this problem too...have you fixed this?

**Comment by mgj321** [comment]
> I have met this problem too...have you fixed this?

 I have met this problem too...have you fixed this?

**Comment by mgj321** [comment]
> > 请参阅 Wiki 或 Python 脚本，了解如何使用该库
> 
> I've found out how to use it from some articles, but I ran into this error when generating and don't know how to fix it. I would appreciate it if you could tell me

 I have met this problem too...have you fixed this?
