### ISSUE TITLE
There is a problem with scene dense.mvs generated by Densepointclouds

### ISSUE THREAD

**Issue by xiaoxu1316** [cdcseacave/openMVS#1120]
The generated scene dense.mvs is about the same size as scene.mvs, and it is the same when viewed with software, without the effect of generating dense point clouds. However, a scene dense.ply file is generated in the form of a dense point cloud

**Desktop :windows10 - OS: [e.g. iOS]
 - Browser vs2022
 - Version openmvs2.3

<img width="566" alt="92924a6f6f50df371afbb65f280f196" src="https://github.com/cdcseacave/openMVS/assets/163831293/8d1bb1c6-55f8-44da-a729-e183f28e46fc">

Then when rebuilding with the official scene dense.mvs file, this error occurred
<img width="358" alt="051040fdd30d9a0aeb12d006837384e" src="https://github.com/cdcseacave/openMVS/assets/163831293/da3ee34d-1d0d-45b4-90d0-4d733e668c93">

**Comment by xiaoxu1316** [comment]
<img width="656" alt="1a9a8943986c3c5ddf95ab5234fef35" src="https://github.com/cdcseacave/openMVS/assets/163831293/a0649d12-f327-4dcf-bbcb-57201b8ae5bd">

about this

**Comment by xiaoxu1316** [comment]
The Debug bug has been fixed, but there is still this error exception thrown: class version class SEACAVE::cList<class MVS::P latform,class MVS::P latform const & __ptr64,1,16,unsigned int> translated into English

**Comment by uniHsia** [comment]
So am I!How did you solve it?

**Comment by ats05** [comment]
The mvs file created by Dense Point cloud process does not seem to contain densified point clouds data.

According to the log, According to the log, the number of points is different.
```
Point-cloud 'scene_dense.ply' saved: 2602692 points (2s531ms)
Scene saved to interface format (49ms):
        410 images (410 calibrated)
        18181 points, 0 vertices, 0 faces
...

**Comment by cdcseacave** [comment]
Pls read the wiki. Since V2.3 the geometry is not stored with the MVS file anymore, but as an external ply.

**Comment by ats05** [comment]
@cdcseacave 
The exported ply file contain view parameters, but its cannot handled by general ply editor software.
Is there a way to open the view parameters of densified pointcloud data?

**Comment by cdcseacave** [comment]
Sure it is, any ply library can read it.
