### ISSUE TITLE
Difference in .ply and .obj textured mesh file

### ISSUE THREAD

**Issue by kundu03** [cdcseacave/openMVS#1128]
Hi @cdcseacave,
Thanks for solving problem #1125
I am encountering one more error in mesh texturing. I am generating mesh and texturing it with TextureMesh and exporting it in both formats .ply and .obj, but there is difference in the two mesh.

This is .ply file -

![Screenshot from 2024-04-06 17-35-26](https://github.com/cdcseacave/openMVS/assets/104849951/7ec35054-dddd-4ccd-b162-3f3aa019b4a6)

 and this is .obj file - 

![Screenshot from 2024-04-06 17-36-21](https://github.com/cdcseacave/openMVS/assets/104849951/412a043f-0155-4207-a18c-7db9b567fbd8)

Is this issue in processing or because of different file format. Thanks

**Comment by cdcseacave** [comment]
I think it is only a difference of lighting, in the first the light is off, in the second is on

**Comment by kundu03** [comment]
Hi @cdcseacave ,
The basic difference among them is not of lighting. They are textured from the same mesh but exported in two formats.

**Comment by 5VK8Y** [comment]
The normal property for the PLY archive could not be read or does not exist, disabling shading.
The normal property for the OBJ archive was found, enabling shading.
To disable shading, select the mesh and press N on your keyboard.

**Comment by 5VK8Y** [comment]
Arguments available are file opening, -WIN X Y W H, -MAX, and -TOP.
Disabling shading is not in the list of available arguments.

**Comment by 5VK8Y** [comment]
Left click the mesh then go to `Options> Selected entity` and disable `Show Normals`.
Sorry for being harsh but the issue concerning OpenMVS has been solved, the rest is up to you to figure out.
