### ISSUE TITLE
2.3.0 is broken because the removed C++ feature std::shared_ptr::unique() used with C++20 where it was removed

### ISSUE THREAD

**Issue by yurivict** [cdcseacave/openMVS#1138]
**Describe the bug**
Build fails:
```
In file included from <built-in>:1:
In file included from /usr/ports/graphics/openmvs/work/.build/libs/MVS/CMakeFiles/MVS.dir/cmake_pch.hxx:5:
In file included from /usr/ports/graphics/openmvs/work/openMVS-2.3.0/libs/MVS/Common.h:42:
In file included from /usr/ports/graphics/openmvs/work/openMVS-2.3.0/libs/MVS/../Common/Common.h:176:
In file included from /usr/ports/graphics/openmvs/work/openMVS-2.3.0/libs/MVS/../Common/Types.h:76:
/usr/ports/graphics/openmvs/work/openMVS-2.3.0/libs/MVS/../Common/FastDelegateCPP11.h:155:61: error: no member named 'unique' in 'std::shared_ptr<void>'
  155 |         if ((sizeof(functor_type) > store_size_) || !store_.unique())
      |                                                      ~~~~~~ ^
1 error generated.
```

Please see the docs [here](https://en.cppreference.com/w/cpp/memory/shared_ptr) showing that the unique() function is removed.

There is a similar issue https://github.com/cdcseacave/openMVS/issues/1075, but you somehow still keep producing releases where removed features are used.

You probably use gcc which isn't 100% C++ compliant and doesn't check for removed features.

You need to build with Clang which does find removed features usage.

**Desktop (please complete the following information):**
 - OS: FreeBSD
 - Version 2.3.0

**Comment by StefanBruens** [comment]
> **Describe the bug** Build fails:

> You probably use gcc which isn't 100% C++ compliant and doesn't check for removed features.
> 
> You need to build with Clang which does find removed features usage.

GCC *does* check for removed features, at least when you use a recent GCC (an old GCC can not know which features are removed or deprecated in the future).

**Comment by StefanBruens** [comment]
Note, the usage of `std::shared_ptr<T>::unique()` is not thread safe in general, so this is a pattern best avoided.

It probably *is* safe here, as the shared_ptr<functor_type> is not visible from outside the delegate, and the delegate itself does not use any weak_ptr's.

I find the "optimization" done here slightly awkward. This special case is used whenever a delegate gets reassigned, and the earlier functor had sufficient size to store the the new one, in this case freeing and allocating memory is skipped. The destructor of the old functor and the constructor of the new one are run in any case. Iff allocation is actually a performance bottleneck, the first optimization which should be done is usage of `std::make_shared<functor_type>`.

**Comment by cdcseacave** [comment]
unique was replaced long time ago with use_count, pls use the latest develop, thanks

**Comment by StefanBruens** [comment]
`use_count` is as unsafe as `unique()`.

If you want people to use recent code, you should do a release, not expect people to pull a random commit from the repo hoping the errors are fixed.

**Comment by cdcseacave** [comment]
I expect nobody to pull random commits, however I expect everybody to pull latest commit of the default branch before rising issues. And if you have such deep knowledge of how things have to be done feel free to create a PR
