### ISSUE TITLE
Output format question

### ISSUE THREAD

**Issue by jpwhitney** [cdcseacave/openMVS#114]
Hi @cdcseacave,

I'd like to make a DEM with pointcloud output from the densify tool of openMVS.  What format are the point clouds output from openMVS?  Or do you know of a good tool to take openMVS output and create a DEM?

The software I'm hoping to use ([points2grid](https://github.com/CRREL/points2grid/)) can use as input point clouds in ASCII and LAS formats.

Thank you for your works!

**Comment by cdcseacave** [comment]
Hi! Not sure I understand the question. If you run OpenMVS you will see it generates the point-cloud in MVS and PLY format. The MVS format is explained in the Interface.h file and the PLY format is a common used format. Please use any of them, as you like.

**Comment by jpwhitney** [comment]
Is the PLY format the ASCII or binary version?

**Comment by pmoulon** [comment]
FYI, you can either use Meshlab or CloudCompare to change the format to ASCII to binary or inverse.

**Comment by jpwhitney** [comment]
Thanks!
