### ISSUE TITLE
My scene.mvs and images generated by openmvg go into openmvs densifyPointCloud with an error!

### ISSUE THREAD

**Issue by hepeixin123** [cdcseacave/openMVS#1141]
robot@robot:~/code/MVS/openMVS_build$ ./bin/DensifyPointCloud -w /home/robot/code/MVS/data2 -i scene.mvs -o test_dense.mvs
19:57:55 [App     ] Build date: May 26 2024, 22:31:03
19:57:55 [App     ] CPU: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 cores)
19:57:55 [App     ] RAM: 31.26GB Physical Memory 11.44GB Virtual Memory
19:57:55 [App     ] OS: Linux 5.4.0-84-generic (x86_64)
19:57:55 [App     ] SSE & AVX compatible CPU & OS detected
19:57:55 [App     ] Command line: -w /home/robot/code/MVS/data2 -i scene.mvs -o test_dense.mvs
19:57:55 [App     ] error: invalid project
how do solve it

**Comment by cdcseacave** [comment]
Scene.mvs is invalid. Fix it or use one of the interfaces app to import it

**Comment by hepeixin123** [comment]
robot@robot:~/code/MVS/openMVS_build$ ./bin/ReconstructMesh  -w /home/robot/code/MVS/xuexiao -i xuexiao_dense.mvs -o xuexiao_mesh.mvs -d 2.5
15:44:36 [App     ] Build date: May 29 2024, 20:41:51
15:44:36 [App     ] CPU: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 cores)
15:44:36 [App     ] RAM: 31.26GB Physical Memory 27.44GB Virtual Memory
15:44:36 [App     ] OS: Linux 5.4.0-150-generic (x86_64)
15:44:36 [App     ] SSE & AVX compatible CPU & OS detected
15:44:36 [App     ] Command line: -w /home/robot/code/MVS/xuexiao -i xuexiao_dense.mvs -o xuexiao_mesh.mvs -d 2.5
15:45:18 [App     ] Scene loaded (41s338ms):
	473 images (473 calibrated) with a total of 474.54 MPixels (1.00 MPixels/image)
	96740661 points, 0 vertices, 0 faces
Points inserted 96740661 (100%, 6m19s855ms)           
15:56:36 [App     ] Delaunay tetrahedralization completed: 96740661 points -> 39705681 vertices, 256970743 (+266) cells, 513941619 (+399) faces (11m2s603ms)
Points weighted 39705681 (100%, 11m58s196ms)           
16:26:24 [App     ] Delaunay tetrahedras weighting completed: 256971009 cells, 513942018 faces (17m46s489ms)
已杀死
could you tell me how do solve it ?

**Comment by Nicny** [comment]
> robot@robot:~/code/MVS/openMVS_build$ ./bin/ReconstructMesh -w /home/robot/code/MVS/xuexiao -i xuexiao_dense.mvs -o xuexiao_mesh.mvs -d 2.5 15:44:36 [App ] Build date: May 29 2024, 20:41:51 15:44:36 [App ] CPU: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 cores) 15:44:36 [App ] RAM: 31.26GB Physical Memory 27.44GB Virtual Memory 15:44:36 [App ] OS: Linux 5.4.0-150-generic (x86_64) 15:44:36 [App ] SSE & AVX compatible CPU & OS detected 15:44:36 [App ] Command line: -w /home/robot/code/MVS/xuexiao -i xuexiao_dense.mvs -o xuexiao_mesh.mvs -d 2.5 15:45:18 [App ] Scene loaded (41s338ms): 473 images (473 calibrated) with a total of 474.54 MPixels (1.00 MPixels/image) 96740661 points, 0 vertices, 0 faces Points inserted 96740661 (100%, 6m19s855ms) 15:56:36 [App ] Delaunay tetrahedralization completed: 96740661 points -> 39705681 vertices, 256970743 (+266) cells, 513941619 (+399) faces (11m2s603ms) Points weighted 39705681 (100%, 11m58s196ms) 16:26:24 [App ] Delaunay tetrahedras weighting completed: 256971009 cells, 513942018 faces (17m46s489ms) 已杀死 could you tell me how do solve it ?

I have the same problem, do you solve it?

**Comment by Nicny** [comment]
抱歉我问题描述错了，出现的问题和您刚开始提出的问题一样，在DensifyPointCloud 上面。

I create a docker container in ubuntu, which build the openmvg and openmvs

In the container, i run SfM_GlobalPipline.py to generate the sfm_data.bin and run openMVG_main_openMVG2openMVS to translate the sfm_data.bin to scene.mvs.

After that ,when I run DensifyPointCloud scene.mvs in the container, something wrong happened as below:

14:14:58 [App ] Build date: June 19 2024, 22:01:15
14:14:58 [App ] CPU: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 cores)
14:14:58 [App ] RAM: 7.59GB Physical Memory 2.00GB Virtual Memory
14:14:58 [App ] OS: Linux 5.15.0-101-generic (x86_64)
14:14:58 [App ] SSE & AVX compatible CPU & OS detected
14:14:58 [App ] Command line: scene.mvs
14:14:58 [App ] error: invalid project

However, when I copy the scene.mvs to Windows platform, it can work.

请问这个问题您怎么解决的
