### ISSUE TITLE
how to get camera pose and point cloud from .mvs file

### ISSUE THREAD

**Issue by JV-X** [cdcseacave/openMVS#1143]
by use` InterfaceCOLMAP`,`DensifyPointCloud`,`ReconstructMesh`,`RefineMesh`,`TextureMesh`,I get some `.mvs` file which named `scene.mvs`,`test_dense.mvs`,`mesh.mvs`,`refinemesh.mvs` and `texture.mvs`.

after that， I want extract camera pose and point cloud from these `.mvs` files, but I hava no idea what should i do.
in openMVG, I can use `openMVG_main_ConvertSfM_DataFormat binary -i yoursfm_data.bin -o sfm-data.json -V -I -E` to get camera pose data, but in openMVS, I couldn't find any relevant information about how to extract camera pose and point cloud data.  Is there an easy way to get them?

really thanks for your help.
and thanks for your time.

**Comment by cdcseacave** [comment]
check the Wiki, in short the camera poses and the point cloud is stored in the MVS file as described in the Interface.h file
additionally there is a python script that reads this too

**Comment by JV-X** [comment]
thanks for your reply, I'll have a try

**Comment by tsrobcvai** [comment]
> additionally there is a python script that reads this too

Sorry, I didn't find this script, could you give more guidance?

**Comment by tsrobcvai** [comment]
> > check the Wiki, in short the camera poses and the point cloud is stored in the MVS file as described in the Interface.h file additionally there is a python script that reads this too
> 
> thanks for your reply, I'll have a try

Hi, Have you found the solution? Appreciate any comments
