### ISSUE TITLE
[Enhancement]  OpenMVG + OpenMVS python pipeline

### ISSUE THREAD

**Issue by FlachyJoe** [cdcseacave/openMVS#115]
Hi,
I'm happy to share a Python pipeline to proceed a reconstruction with OpenMVG and OpenMVS.
You can basically call `python MvgMvs_Pipeline.py input_dir ouput_dir` or set arguments for each step from the command line (no script editing needed).
This script has been tested under linux and you may adjust binary paths at lines 50+.

[MvgMvs_Pipeline.py.txt](https://github.com/cdcseacave/openMVS/files/439342/MvgMvs_Pipeline.py.txt)

**Comment by cdcseacave** [comment]
Looks great, thanks! I'd like to add it to my usage instructions, however in my opinion it needs few teaks. Why didn't you add the full OpenMVS pipeline, like texturing? And could you change the hard coded paths to get them from some ENV variables for example and if not set to warn the user?

**Comment by cdcseacave** [comment]
With some small changes, I added the script to the sample repository and instruction on how to use it on the Usage wiki page. Thanks again, @FlachyJoe!

**Comment by FlachyJoe** [comment]
You're welcome.

**Comment by jpwhitney** [comment]
I noticed this uses openMVG_main_IncrementalSfM.  Is it possible to have a version that uses openMVG_main_GlobalSfM or even better, uses a command line switch to specify?
