### ISSUE TITLE
How to perform “ReconstructMesh” after editing the “scene_dense.ply” file

### ISSUE THREAD

**Issue by StevenssW** [cdcseacave/openMVS#1158]
Hello, I want to seek some help in the community. 
I calculated the sparse point cloud using OpenSfM and exported “scene.mvs”.
Next, I performed dense point cloud calculation using the command: “./DensifyPointCloud scene.mvs -w data/openmvs --remove-dmaps 1”, and obtained scene_dense.mvs and scene_dense.ply.

I want to make some point cloud deletions or alignments on “scene_dense.ply”. However, when I try to run the mesh reconstruction, it fails. 
My command is: “./ReconstructMesh scene_dense.mvs -w data/openmvs -p scene_dense.ply --target-face-num 2000000 --close-holes 150”.

I want to Know，How can I continue the subsequent mesh reconstruction work after editing the point cloud? 

log Information：

17:35:08 [App     ] OpenMVS x64 v2.3.0
17:35:08 [App     ] Build date: Jul 10 2024, 15:01:03
17:35:08 [App     ] CPU: 13th Gen Intel(R) Core(TM) i9-13900K (16 cores)
17:35:08 [App     ] RAM: 62.76GB Physical Memory 2.00GB Virtual Memory
17:35:08 [App     ] OS: Linux 5.15.0-113-generic (x86_64)
17:35:08 [App     ] Disk: 104.65GB (195.31GB) space
17:35:08 [App     ] SSE & AVX compatible CPU & OS detected

17:35:08 [App     ] Camera model loaded: platform 0; camera  0; f 0.500x0.500; poses 3042
17:35:08 [App     ] Scene loaded from interface format (77ms):
	3042 images (3042 calibrated) with a total of 1188.28 MPixels (0.39 MPixels/image)
	305301 points, 0 vertices, 0 faces
17:35:10 [App     ] Point-cloud 'scene_dense.ply' loaded: 18587514 points (1s325ms)
段错误 (核心已转储)

**Comment by cdcseacave** [comment]
The dense point cloud from the PLY can be edited (only removing points) as long as during editing all point attributes are preserved (not only color and normal, but also views, etc). Unfortunately I do not know any point cloud editor that can do that. I think we need to write one ourselves.

**Comment by StevenssW** [comment]
Many thanks for your reply
