### ISSUE TITLE
ReconstructMesh only produce .ply , no .mvs output

### ISSUE THREAD

**Issue by ddkats** [cdcseacave/openMVS#1159]
**Describe the bug**
I have the same issue as described in https://github.com/cdcseacave/openMVS/issues/1058, the ReconstructMesh did not produce .mvs file. However, using the same input dataset (images, sparse, dense, database.db) on another PC worked fine a while ago, generating both .ply and .mvs files. Do you have any idea what might be causing this? 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20/04

**Comment by cdcseacave** [comment]
during mesh reconstruction the MVS file does not change, so it does not need to generate a new mvs file; simply use the same mvs file together with the generated mesh stored in the ply file for the next stage

**Comment by ddkats** [comment]
Thanks for your reply. It worked after doing a clean rerun of all the stages.
