### ISSUE TITLE
Depth map image retrieved from dmap file does not match the original image in size

### ISSUE THREAD

**Issue by nick0622** [cdcseacave/openMVS#1160]
Description:
After performing dense reconstruction, I aim to analyze the depth map (dmap) output further. To achieve this, I use MvsReadDMAP.py in the scripts/python directory to save the depth, normal, and confidence map images. However, I have encountered an issue where the produced depth map size does not match the original image size.

Steps to Reproduce:
1. Run dense reconstruction to generate the depth map.
2. Use MvsReadDMAP.py to save the depth, normal, and confidence map images.
3. Compare the size of the produced depth map with the original image size.

Expected Behavior:
The size of the depth map should match the size of the original image.

Questions:
Where in the program might the size of the depth map be modified?
How can I use the depth information to back-project the points in the original image?

**Comment by cdcseacave** [comment]
The resolution of the depth map is set by a parameter during densification. By default half the resolution in each dimension

**Comment by nick0622** [comment]
The issue with --resolution-level parameter not matching the expected downscaling behavior

I notice that the --resolution-level parameter halves the resolution in each dimension. However, I am experiencing unexpected behavior. I have images with an original size of (3024, 4032), but after densification, their size became (1496, 1995), which doesn't match my expectations. Based on a resolution level of 1, I expect the downscaled resolution to be (1512, 2016).

Is there an additional factor influencing the output resolution, or is this a bug in the --resolution-level scaling process? Any insights would be appreciated.

**Comment by cdcseacave** [comment]
yes, there is also `max-resolution`

**Comment by nick0622** [comment]
Hi,

I’m trying to understand how the --max-resolution argument works with --resolution-level.

Given an image with an original size of (3024, 4032), scaling it down by a --resolution-level of 1 results in dimensions of (1512, 2016). Since both of these dimensions are below the --max-resolution value of 2560, I expected the final output to be (1512, 2016).

However, the final result is (1496, 1995). Could u explain why this is happening? Is there additional processing or constraints applied that could cause the final dimensions to be slightly smaller than expected?

Thanks!

**Comment by cdcseacave** [comment]
yes, that is the logic, the smallest resolution of the two params is used

pls send me the data and command line u used to debug

**Comment by nick0622** [comment]
![IMG_1252](https://github.com/user-attachments/assets/18120c48-665c-4299-b89c-a3bb42f5655e)
[DensifyPointCloud-2405230244308CBE84.log](https://github.com/user-attachments/files/16975691/DensifyPointCloud-2405230244308CBE84.log)

Issue with Dense Reconstruction and Scene Size Changes

My dataset includes a cylinder pier, and the image dimensions are 3024x4032. I only provided scene.mvs during the process, so all other parameters were set to default.

A few points:

- The scene.mvs file was generated using COLMAP.

Maybe size change may have originated from the COLMAP export, but I will double-check this.
Thank you!

**Comment by nick0622** [comment]
This is the link to my data. It includes 100 images of a pier in different angles.
https://drive.google.com/drive/folders/1vVerd4w57-SvlJoVb-FyK2l20fR22hrQ?usp=sharing

This is my scene.mvs
https://drive.google.com/file/d/1nULPcd-r91su1GcnlhGJ2Rpy8WYE38dd/view?usp=sharing

command line I used: DensifyPointCloud scene.mvs

**Comment by cdcseacave** [comment]
I think some steps of the photogrammetry pipeline are not clear to you; here is a small breakdown of the important steps:
- sfm: the original images are processed to compute camera poses and intrinsics
- undistortion: the original images are undistorted
- mvs: the undistorted images and their camera poses are used for densification
so the original images are not the input to OpenMVS, but the undistorted images produced by COLMAP in your case; the undistortion process can (and often does) change the resolution for two reasons:
- keep as many valid pixels (or all) in the undistorted images
- remove invalid pixels border pixels
so check the resolution of the undistorted images nor the original images

**Comment by nick0622** [comment]
I found where the issue originates. During the COLMAP process, the image_undistorter changes the image resolution.

Sorry for bothering
