### ISSUE TITLE
Mac OS build

### ISSUE THREAD

**Issue by jerome-godbout-lychens** [cdcseacave/openMVS#1177]
**Describe the bug**
Compiling OpenMVS from the git checkout and compiling it.

**To Reproduce**
following the steps into https://github.com/electech6/openMVS_comments/blob/master/BUILD.md

**Expected behavior**
Compile and link

**Desktop (please complete the following information):**
 - OS: Mac OS 15.0.1
 - Machine: Macbook M3 Pro

**Additional context**
Seems like source is using deprecated features in C++20, recent compiler refuse to compile this. 

** CMake output **
```
cmake ../openMVS 
Compiling with C++20
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Can't find OpenMP. Continuing without it.
CMake Warning (dev) at CMakeLists.txt:112 (FIND_PACKAGE):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Can't find CUDA. Continuing without it.
-- WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
-- Python 3.12 found (include: /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12)
CMake Warning (dev) at CMakeLists.txt:193 (FIND_PACKAGE):
  Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
  --help-policy CMP0167" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Boost: /opt/homebrew/lib/cmake/Boost-1.86.0/BoostConfig.cmake (found version "1.86.0") found components: iostreams program_options system serialization missing components: python312
-- Eigen 3.4.0 found (include: /opt/homebrew/include/eigen3)
-- OpenCV 4.10.0 found (include: /opt/homebrew/Cellar/opencv/4.10.0_11/include/opencv4)
-- Targeting Unix Makefiles
-- Using /Library/Developer/CommandLineTools/usr/bin/c++ compiler.
-- Running in macOS DARWIN_VERSION=24
CMake Warning (dev) at /opt/homebrew/lib/cmake/CGAL/CGAL_SetupBoost.cmake:20 (find_package):
  Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
  --help-policy CMP0167" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

Call Stack (most recent call first):
  /opt/homebrew/lib/cmake/CGAL/CGAL_SetupCGALDependencies.cmake:48 (include)
  /opt/homebrew/lib/cmake/CGAL/CGALConfig.cmake:169 (include)
  libs/MVS/CMakeLists.txt:2 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Boost: /opt/homebrew/lib/cmake/Boost-1.86.0/BoostConfig.cmake (found suitable version "1.86.0", minimum required is "1.72")
-- Boost include dirs: /opt/homebrew/include
-- Boost libraries:    
-- VCG  found (include: /Users/godboutj/code/vcglib)
-- GLEW  found (include: /opt/homebrew/include)
-- GLFW3 3.4.0 found (include: )
-- Configuring done (1.0s)
-- Generating done (0.1s)
-- Build files have been written to: /Users/godboutj/code/build
```

** Compile fix deprecated **
```
diff --git a/libs/Common/FastDelegateCPP11.h b/libs/Common/FastDelegateCPP11.h
index 26a565b..9fda227 100644
--- a/libs/Common/FastDelegateCPP11.h
+++ b/libs/Common/FastDelegateCPP11.h
@@ -152,7 +152,7 @@ public:
     {
         using functor_type = typename ::std::decay<T>::type;
 
-        if ((sizeof(functor_type) > store_size_) || !store_.unique())
+        if ((sizeof(functor_type) > store_size_) || store_.use_count() > 1)
         {
             store_.reset(operator new(sizeof(functor_type)), functor_deleter<functor_type>);
             store_size_ = sizeof(functor_type);
```

But after I still it a bad usage of  Windows features _vscprintf() that should be defined as  something like that instead:
```
#if (defined _MSC_VER) && (_MSC_VER < 1400 ) && (!defined WINCE)
	#define OPENMVS_VSCPRINTF(...)   _vscprintf(__VA_ARGS__)
#else
	#define OPENMVS_VSCPRINTF(...)   vsnprintf(nullptr, 0, __VA_ARGS__)
#endif
```

I did not dig too much about this one, seems like it use a bad print format call. But those 2 issue prevent compiling it on Mac OS

`mac build % make
[ 13%] Built target Common
[ 21%] Built target Math
[ 39%] Built target IO
[ 62%] Built target MVS
[ 64%] Built target pyOpenMVS
[ 65%] Linking CXX executable ../../bin/InterfaceCOLMAP
Undefined symbols for architecture arm64:
  "_vscprintf(char const*, char*)", referenced from:
      SEACAVE::String::FormatString(char const*, ...) in InterfaceCOLMAP.cpp.o
  "cv::Mat::create(int, int, int)", referenced from:
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
  "cv::Mat::Mat(cv::Mat const&)", referenced from:
      std::__1::vector<cv::Mat, std::__1::allocator<cv::Mat>>::vector[abi:ne180100](std::initializer_list<cv::Mat>) in InterfaceCOLMAP.cpp.o
  "cv::Mat::Mat(int, int, int, void*, unsigned long)", referenced from:
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      cv::Mat::operator cv::Matx<double, 3, 3><double, 3, 3>() const in InterfaceCOLMAP.cpp.o
  "cv::Mat::Mat()", referenced from:
      SEACAVE::TRMatrixBase<double>::EnforceOrthogonality() in InterfaceCOLMAP.cpp.o
      SEACAVE::TRMatrixBase<double>::EnforceOrthogonality() in InterfaceCOLMAP.cpp.o
      SEACAVE::TRMatrixBase<double>::EnforceOrthogonality() in InterfaceCOLMAP.cpp.o
      SEACAVE::TRMatrixBase<double>::EnforceOrthogonality() in InterfaceCOLMAP.cpp.o
  "cv::Mat::Mat(int, int, int)", referenced from:
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
  "cv::Mat::Mat()", referenced from:
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
  "cv::Mat::~Mat()", referenced from:
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      ...
  "cv::Mat::~Mat()", referenced from:
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
      ...
  "cv::SVD::operator()(cv::_InputArray const&, int)", referenced from:
      SEACAVE::TRMatrixBase<double>::EnforceOrthogonality() in InterfaceCOLMAP.cpp.o
  "cv::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, char const*, char const*, int)", referenced from:
      cv::Mat::operator cv::Matx<double, 3, 3><double, 3, 3>() const in InterfaceCOLMAP.cpp.o
  "cv::merge(cv::_InputArray const&, cv::_OutputArray const&)", referenced from:
      (anonymous namespace)::ImportScene(SEACAVE::String const&, SEACAVE::String const&, MVS::Interface&, MVS::PointCloud&) in InterfaceCOLMAP.cpp.o
  "cv::operator*(cv::Mat const&, cv::Mat const&)", referenced from:
      SEACAVE::TRMatrixBase<double>::EnforceOrthogonality() in InterfaceCOLMAP.cpp.o
  "boost::program_options::validators::check_first_occurrence(boost::any const&)", referenced from:
      void boost::program_options::validate<unsigned int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, unsigned int*, long) in InterfaceCOLMAP.cpp.o
      void boost::program_options::validate<int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, int*, long) in InterfaceCOLMAP.cpp.o
  "boost::program_options::to_internal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)", referenced from:
      std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> boost::program_options::to_internal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) in InterfaceCOLMAP.cpp.o
  "boost::program_options::variables_map::variables_map()", referenced from:
      __GLOBAL__sub_I_InterfaceCOLMAP.cpp in InterfaceCOLMAP.cpp.o
  "boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)", referenced from:
      boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) in InterfaceCOLMAP.cpp.o
  "boost::program_options::basic_parsed_options<char> boost::program_options::parse_config_file<char>(std::__1::basic_istream<char, std::__1::char_traits<char>>&, boost::program_options::options_description const&, bool)", referenced from:
      _main in InterfaceCOLMAP.cpp.o
  "boost::program_options::options_description::add_options()", referenced from:
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
  "boost::program_options::options_description::m_default_line_length", referenced from:
      _main in InterfaceCOLMAP.cpp.o
  "boost::program_options::options_description::add(boost::program_options::options_description const&)", referenced from:
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
  "boost::program_options::options_description::options_description(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned int, unsigned int)", referenced from:
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
  "boost::program_options::options_description::options_description(unsigned int, unsigned int)", referenced from:
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
  "boost::program_options::invalid_option_value::invalid_option_value(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)", referenced from:
      void boost::program_options::validate<unsigned int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, unsigned int*, long) in InterfaceCOLMAP.cpp.o
      void boost::program_options::validate<int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, int*, long) in InterfaceCOLMAP.cpp.o
  "boost::program_options::error_with_option_name::error_with_option_name(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int)", referenced from:
      boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) in InterfaceCOLMAP.cpp.o
  "boost::program_options::options_description_easy_init::operator()(char const*, boost::program_options::value_semantic const*, char const*)", referenced from:
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      ...
  "boost::program_options::options_description_easy_init::operator()(char const*, char const*)", referenced from:
      _main in InterfaceCOLMAP.cpp.o
  "boost::program_options::positional_options_description::add(char const*, int)", referenced from:
      _main in InterfaceCOLMAP.cpp.o
  "boost::program_options::positional_options_description::positional_options_description()", referenced from:
      _main in InterfaceCOLMAP.cpp.o
  "boost::program_options::arg", referenced from:
      boost::program_options::typed_value<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, char>::name() const in InterfaceCOLMAP.cpp.o
      boost::program_options::typed_value<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, char>::name() const in InterfaceCOLMAP.cpp.o
      boost::program_options::typed_value<unsigned int, char>::name() const in InterfaceCOLMAP.cpp.o
      boost::program_options::typed_value<unsigned int, char>::name() const in InterfaceCOLMAP.cpp.o
      boost::program_options::typed_value<int, char>::name() const in InterfaceCOLMAP.cpp.o
      boost::program_options::typed_value<int, char>::name() const in InterfaceCOLMAP.cpp.o
      boost::program_options::typed_value<bool, char>::name() const in InterfaceCOLMAP.cpp.o
      boost::program_options::typed_value<bool, char>::name() const in InterfaceCOLMAP.cpp.o
      ...
  "boost::program_options::store(boost::program_options::basic_parsed_options<char> const&, boost::program_options::variables_map&, bool)", referenced from:
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
  "boost::program_options::detail::cmdline::set_positional_options(boost::program_options::positional_options_description const&)", referenced from:
      _main in InterfaceCOLMAP.cpp.o
  "boost::program_options::detail::cmdline::set_options_description(boost::program_options::options_description const&)", referenced from:
      _main in InterfaceCOLMAP.cpp.o
  "boost::program_options::detail::cmdline::get_canonical_option_prefix()", referenced from:
      boost::program_options::basic_command_line_parser<char>::run() in InterfaceCOLMAP.cpp.o
  "boost::program_options::detail::cmdline::run()", referenced from:
      boost::program_options::basic_command_line_parser<char>::run() in InterfaceCOLMAP.cpp.o
  "boost::program_options::detail::cmdline::cmdline(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&)", referenced from:
      boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*) in InterfaceCOLMAP.cpp.o
  "boost::program_options::notify(boost::program_options::variables_map&)", referenced from:
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
  "boost::program_options::validate(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, int)", referenced from:
      boost::program_options::typed_value<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, char>::xparse(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) const in InterfaceCOLMAP.cpp.o
  "boost::program_options::validate(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, bool*, int)", referenced from:
      boost::program_options::typed_value<bool, char>::xparse(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) const in InterfaceCOLMAP.cpp.o
  "boost::program_options::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, boost::program_options::options_description const&)", referenced from:
      SEACAVE::Log& SEACAVE::Log::operator<<<boost::program_options::options_description>(boost::program_options::options_description const&) in InterfaceCOLMAP.cpp.o
  "boost::throw_exception(std::exception const&)", referenced from:
      void boost::program_options::validate<unsigned int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, unsigned int*, long) in InterfaceCOLMAP.cpp.o
      void boost::program_options::validate<unsigned int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, unsigned int*, long) in InterfaceCOLMAP.cpp.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const& boost::program_options::validators::get_single_string<char>(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, bool) in InterfaceCOLMAP.cpp.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const& boost::program_options::validators::get_single_string<char>(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, bool) in InterfaceCOLMAP.cpp.o
      void boost::program_options::validate<int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, int*, long) in InterfaceCOLMAP.cpp.o
      void boost::program_options::validate<int, char>(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, int*, long) in InterfaceCOLMAP.cpp.o
  "SEACAVE::LogConsole::Open()", referenced from:
      _main in InterfaceCOLMAP.cpp.o
  "SEACAVE::LogConsole::Close()", referenced from:
      (anonymous namespace)::Application::~Application() in InterfaceCOLMAP.cpp.o
      SEACAVE::LogConsole::~LogConsole() in InterfaceCOLMAP.cpp.o
  "SEACAVE::LogConsole::LogConsole()", referenced from:
      _main in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::Application::~Application() in InterfaceCOLMAP.cpp.o
  "SEACAVE::g_nVerbosityLevel", referenced from:
      _main in InterfaceCOLMAP.cpp.o
  "SEACAVE::g_strWorkingFolder", referenced from:
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      ...
  "SEACAVE::g_strWorkingFolderFull", referenced from:
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ExportScene(SEACAVE::String const&, MVS::Interface const&, bool, bool) in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::ExportScene(SEACAVE::String const&, MVS::Interface const&, bool, bool) in InterfaceCOLMAP.cpp.o
      ...
  "SEACAVE::Log::Write(char const*, ...)", referenced from:
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      ...
  "SEACAVE::Log::Log()", referenced from:
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
      ...
  "SEACAVE::Util::getCurrentFolder()", referenced from:
      SEACAVE::Util::getFullPath(SEACAVE::String const&) in InterfaceCOLMAP.cpp.o
  "SEACAVE::Util::LogBuild()", referenced from:
      _main in InterfaceCOLMAP.cpp.o
  "SEACAVE::Timer::GetTimeFactor()", referenced from:
      _main in InterfaceCOLMAP.cpp.o
      _main in InterfaceCOLMAP.cpp.o
  "SEACAVE::LogFile::Open(char const*)", referenced from:
      _main in InterfaceCOLMAP.cpp.o
  "SEACAVE::LogFile::Close()", referenced from:
      (anonymous namespace)::Application::~Application() in InterfaceCOLMAP.cpp.o
      SEACAVE::LogFile::~LogFile() in InterfaceCOLMAP.cpp.o
  "SEACAVE::LogFile::LogFile()", referenced from:
      _main in InterfaceCOLMAP.cpp.o
      (anonymous namespace)::Application::~Application() in InterfaceCOLMAP.cpp.o
  "SEACAVE::ColorType<float>::ONE", referenced from:
      ___cxx_global_var_init.30 in InterfaceCOLMAP.cpp.o
  "cv::Mat::convertTo(cv::_OutputArray const&, int, double, double) const", referenced from:
      cv::Mat::operator cv::Matx<double, 3, 3><double, 3, 3>() const in InterfaceCOLMAP.cpp.o
  "boost::program_options::error_with_option_name::substitute_placeholders(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) const", referenced from:
      vtable for boost::program_options::validation_error in InterfaceCOLMAP.cpp.o
  "boost::program_options::error_with_option_name::what() const", referenced from:
      vtable for boost::program_options::validation_error in InterfaceCOLMAP.cpp.o
  "boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, bool) const", referenced from:
      vtable for boost::program_options::typed_value<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, char> in InterfaceCOLMAP.cpp.o
      vtable for boost::program_options::typed_value<unsigned int, char> in InterfaceCOLMAP.cpp.o
      vtable for boost::program_options::typed_value<int, char> in InterfaceCOLMAP.cpp.o
      vtable for boost::program_options::typed_value<bool, char> in InterfaceCOLMAP.cpp.o
  "typeinfo for boost::program_options::error_with_option_name", referenced from:
      typeinfo for boost::program_options::validation_error in InterfaceCOLMAP.cpp.o
  "typeinfo for boost::program_options::value_semantic_codecvt_helper<char>", referenced from:
      typeinfo for boost::program_options::typed_value<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, char> in InterfaceCOLMAP.cpp.o
      typeinfo for boost::program_options::typed_value<unsigned int, char> in InterfaceCOLMAP.cpp.o
      typeinfo for boost::program_options::typed_value<int, char> in InterfaceCOLMAP.cpp.o
      typeinfo for boost::program_options::typed_value<bool, char> in InterfaceCOLMAP.cpp.o
  "vtable for boost::program_options::variables_map", referenced from:
      boost::program_options::variables_map::~variables_map() in InterfaceCOLMAP.cpp.o
   NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for boost::program_options::error_with_option_name", referenced from:
      boost::program_options::invalid_option_value::~invalid_option_value() in InterfaceCOLMAP.cpp.o
      boost::program_options::validation_error::~validation_error() in InterfaceCOLMAP.cpp.o
      boost::program_options::validation_error::~validation_error() in InterfaceCOLMAP.cpp.o
   NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture arm64
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by cdcseacave** [comment]
Thank you for spotting the deprecated function. I fixed that on the last commit on develop, and tested it on the exact setup you have and it all builds fine now.

**Comment by jerome-godbout-lychens** [comment]
How to you make it build, it always fails for me either with or without specifying gcc? can you share the commands you use and the exact commit (head of dev)? Cause me it never pass with the aboves problems. Do you build from clean state or from cached cmake?

**Comment by cdcseacave** [comment]
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/b5ee1bf5-3167-4789-b85c-a6cc194ed605">
