### ISSUE TITLE
TextureMesh | The texturemesh.exe generate unexpected outcome, with images not correctly aligning with meshes

### ISSUE THREAD

**Issue by Li291216576** [cdcseacave/openMVS#1178]
Hello CDC @cdcseacave,
I came across with a problem when I conducted texture meshing on my data. The following steps are how I processed my data:

1. I did dense reconstruction through COLMAP, and I copied the dense folder to the working directory of OpenMVS.

2. I ran the following command to get `scene.mvs` file:
**command**:  `interfaceCOLMAP.exe -i path\to\working\folder -o ./scene.mvs --image-folder path\to\working\folder\images`
**outcome**:
![image](https://github.com/user-attachments/assets/4dec21df-78b0-4294-97ea-5d9173720fd6)

3. On the basis of `scene.mvs`, I ran ReconstructMesh command directly, because I've done dense reconstruction in COLMAP already, and I had enough points:
**command**: `ReconstructMesh.exe -w path\to\working\folder -i scene_dense.mvs`
**outcome**:
![image](https://github.com/user-attachments/assets/a3e2139e-a399-485c-9eea-9908e3727c30)

4. Then, I skip refinedmesh process, using the ReconstructionMesh outcomes, `scene_mesh.mvs` and `scene_mesh.ply`, to do textureMeshing.
**command**: `TextureMesh.exe -w path\to\working\folder -i scene_dense.mvs -m scene_refined_mesh.ply -o texture_mesh.mvs`
**outcome**: (as you can see, the texture mesh is not corresponding with the outcome of step 2)
![image](https://github.com/user-attachments/assets/ed245be0-1699-486f-9d06-ec12d0d0fd9c)

Could you please give me some hints on how I can solve this problem?

The configuration of my computer is below:
CPU: 12th Gen Intel(R) Core(TM) i9-12900H (20 cores)
RAM: 31.67GB Physical Memory 128.00TB Virtual Memory
CUDA device 0 initialized: NVIDIA GeForce RTX 3080 Ti Laptop GPU

And I processed the data using openMVS-2.1.0.

You can find the data here: https://drive.google.com/file/d/11-UWseDB6oaCFNcjeGut2Rm99r4gNDSm/view?usp=drive_link

**Comment by cdcseacave** [comment]
pls use the latest develop branch of openmvs

if the problem persists, pls upload the data and share access

**Comment by Li291216576** [comment]
Hello cdc @cdcseacave,

I've tried the latest develop branch, but the problem still exists. 

Here are steps I come to the problem:
1. Generate `scene.ply` and `scene.mvs` through `InterfaceCOLMAP.exe`:
command: `InterfaceCOLMAP.exe -i "F:\openMVS\openMVS data\dense" -o scene.mvs --image-folder "F:\openMVS\openMVS data\dense\images"`

2. Using `scene.mvs` to generate mesh file through `ReconstructMesh.exe`:
command: `ReconstructMesh.exe -w "F:\openMVS\openMVS data\dense" -i scene.mvs `

3. Doing texturemeshing through `TextureMesh.exe`:
command: `TextureMesh.exe -w "F:\openMVS\openMVS data\dense" -i scene.mvs -m scene_mesh.ply -o texture_mesh.mvs --export-type ply`
Outcome of step 3: (As you can see, the images patches were wrongly matched.)
![image](https://github.com/user-attachments/assets/ee5d7d78-46ea-49d5-b261-b684cccb13b7)

Here is the **data** I used: (It is a bit larger, which might take time to download)
https://drive.google.com/file/d/1USoxw3fVC6cD8Qlpbfra1I_cw0k1YAYn/view?usp=drive_link

**Comment by cdcseacave** [comment]
I still do not have read access to the shared data

**Comment by Li291216576** [comment]
Sorry, please try this link: 
https://drive.google.com/file/d/1USoxw3fVC6cD8Qlpbfra1I_cw0k1YAYn/view?usp=sharing

**Comment by cdcseacave** [comment]
there was a problem with the importer, use latest develop, should work now

<img width="1073" alt="image" src="https://github.com/user-attachments/assets/d7b0cbff-27ea-4b1f-944d-4b140ca17949">

**Comment by Li291216576** [comment]
Many thanks, cdc @cdcseacave, I am going to try it right now!

**Comment by Li291216576** [comment]
Problem solved! Thanks for your excellent job! @cdcseacave
