### ISSUE TITLE
ReconstructMesh doesn't create mesh

### ISSUE THREAD

**Issue by alli-a** [cdcseacave/openMVS#118]
Hello,

I am trying to reconstruct a scene from 200 4K images. I imported an nvm file from VisualSFM and the interfacevisualsfm and densifypointcloud applications worked fine. However, when I try to use reconstructmesh it just works for a minute and then produces nothing (see below). Does anyone know what might be going wrong here and/or potential fixes? OpenMVS did work for me when I used the same number of images but at a lower resolution, so I'm curious if it's some sort of memory issue. 

F:\2016_Summer_Research\Last_Version\openMVS_sample-master\openMVS_sample-master>ReconstructMesh.exe
 F:\2016_Summer_Research\Last_Version\openMVS_sample-master\openMVS_sample-master\model_dense.mvs
14:28:22 [App     ] Build date: Jul  2 2016, 14:57:30
14:28:22 [App     ] CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
14:28:22 [App     ] RAM: 31.95GB Physical Memory 8.00TB Virtual Memory
14:28:22 [App     ] OS: Windows 7 (SP1) x64
14:28:22 [App     ] SSE & AVX compatible CPU & OS detected
14:28:22 [App     ] Command line: F:\2016_Summer_Research\Last_Version\openMVS_sample-master\openMVS
_sample-master\model_dense.mvs
14:28:57 [App     ] Scene loaded (34s206ms):
        200 images (200 calibrated) with a total of 421.88 MPixels (2.11 MPixels/image)
        30908543 points, 0 vertices, 0 faces

Thank you!

**Comment by cdcseacave** [comment]
Indeed, 30M points could be an issue for the reconstruct mesh memory footprint. However it seems it stop before starting. Did you start ReconstructMesh the same way you started DensifyPointCloud (working path, how the scene is passed, etc)? How soon after the scene was loaded ReconstructMesh stops?

**Comment by alli-a** [comment]
Hi cdcseacave,

Thanks for your response! The working path is the same, but what exactly do you mean by how the scene is passed? ReconstructMesh stops a few seconds after the scene is loaded. I'm not sure if this is relevant, but the InterfaceVisualSFM step only takes one second and then DensifyPointCloud takes about two hours. I've been following the tutorial posted on the VisualSFM google group (which based on the similar usernames I assume was posted by you?) and haven't changed any parameters, so my steps are the same as the ones listed here: https://groups.google.com/forum/#!topic/vsfm/VcXGvP1HuMo.

**Comment by TMwhuhan** [comment]
I meet same problem too~In my case, the processing use all RAM while the point cloud is 200M,  so maybe the tools can't handle big project yet. And  the poisson reconstruction works fine, but I don't known how to write a ".mvs" file for MeshRefine.

**Comment by cdcseacave** [comment]
Indeed, memory is a problem for big datasets for now.

If you created a mesh externally (using poisson reconstruction, etc), you can use it by using the command line:
```
TextureMesh scene.mvs --mesh-file <filename>
```
where scene.mvs can be the first mvs project exported by OpenMVG, and TextureMesh can be replaced with any module that expects a mesh, like RefineMesh. This will work fine as long as the mesh reconstruction tool does not change the reference coordinates system in any way.

**Comment by jpwhitney** [comment]
When I run ReconstructMesh I get the following:

**Comment by cdcseacave** [comment]
That is strange. I never saw it stuck in an infinite loop. Stop it and try again. It should finish in max 10 min, and in the terminal window should appear a progress counter that estimates the time left.

**Comment by jpwhitney** [comment]
It stays like this.
01:08:49 [App ] Delaunay tetrahedralization completed: 6717677 points -> 1933301 vertices, 11796688 (+256) cells, 23593504 (+384) faces (32s539ms)
But no files are output.  I have tried several times with the same result.  I get the message:Delaunay tetrahedralization completed: 6717677 points -> 1933301 vertices, 11796688 (+256) cells, 23593504 (+384) faces 
Shortly after that the CPU usage on all eight cores jumps to 100%.

**Comment by cdcseacave** [comment]
Since we can not reproduce your problem, you could try to do a bit of debugging yourself to find where it gets blocked. Compile in Release with debug info, run the tool in gdb, and break it when you think it entered the infinite loop.

**Comment by jpwhitney** [comment]
Okay, I'll see how that goes and check back in with the results.

**Comment by jpwhitney** [comment]
Hi cdcseacave, I noticed on [this thread](https://github.com/cdcseacave/openMVS/issues/105) that there is some desire for others to contribute to the debugging process.  Previously I had reran the pipeline, but now I am having a similar infinite loop error that I cannot get past during the ReconstructMesh.

You mentioned three steps:
1. Compile in Release with debug info
2. run the tool in gdb
3. break it when you think it entered the infinite loop.

I would like to try these steps but I do not know how as I have never done them before.  I'm familiar with debugging in python but have never used gdb.

If you or someone could breakdown how to achieve this I would be very grateful.

**Comment by cdcseacave** [comment]
I do not have experience in using gdb either, never used it and never will (it is such an ancient tool still without a good UI). However I have experience in visual studio, so I can help if switch to Windows.

**Comment by ywjia** [comment]
Is there any update on this issue, please? I experienced the same, i.e., the program hangs at the following:
"22:14:01 [App     ] Delaunay tetrahedralization completed: 1690406 points -> 1117628 vertices, 7010884 (+276) cells, 14021906 (+414) faces (12s667ms)"

**Comment by stereoa** [comment]
@ywjia try #180. It fixed this bug for me.

**Comment by ywjia** [comment]
@stereoa thanks. I got it and indeed it fixes the issue.

**Comment by lexvandersluijs** [comment]
In my case I had to convert the PNG images (without EXIF) to JPG (without EXIF). I passed the focal length of the camera (in pixels) to one of the earlier tools. With JPG the reconstruction works.. Looks like a bug.
