### ISSUE TITLE
error: opening file  .........XXXXX.dmap for reading depth-data

### ISSUE THREAD

**Issue by xjxinchina** [cdcseacave/openMVS#1186]
Dear Developer, thank you very much for your work. I have indeed encountered a problem that has troubled me for a long time while using this project.
When I was rebuilding using Ubuntu 20.04, everything went smoothly when I used the images provided by the project. However, I encountered problems when I used images taken by my own drone during the Dense Point-Cloud Reconstruction. When I used the default mode, specifically DensifyPointCloud scene.mvs, the logs showed:

12:30:11 [App     ] Reference image 234 paired with 8 views
12:30:11 [App     ] Depth-map for image 313 estimated using  8 images: 2000x1125 (300ms)
12:30:11 [App     ] Reference image  23 paired with 8 views
12:30:12 [App     ] Depth-map for image 234 estimated using  8 images: 2000x1125 (292ms)
12:30:12 [App     ] Reference image 104 paired with 8 views
12:30:12 [App     ] Depth-map for image  23 estimated using  8 images: 2000x1125 (297ms)
12:30:12 [App     ] error: opening file '/root/autodl-tmp/moudels/chengdongout/depth0023.geo.dmap.tmp' for writing depth-data
12:30:12 [App     ] Reference image 182 paired with 8 views
12:30:12 [App     ] Depth-map for image 104 estimated using  8 images: 2000x1125 (297ms)
12:30:12 [App     ] error: opening file '/root/autodl-tmp/moudels/chengdongout/depth0104.geo.dmap.tmp' for writing depth-data
12:30:12 [App     ] Reference image 130 paired with 8 views
12:30:12 [App     ] Depth-map for image 182 estimated using  8 images: 2000x1125 (294ms)
12:30:12 [App     ] error: opening file '/root/autodl-tmp/moudels/chengdongout/depth0182.geo.dmap.tmp' for writing depth-data
12:30:12 [App     ] Reference image 286 paired with 8 views
12:30:13 [App     ] Depth-map for image 130 estimated using  8 images: 2000x1125 (290ms)
12:30:13 [App     ] error: opening file '/root/autodl-tmp/moudels/chengdongout/depth0130.geo.dmap.tmp' for writing depth-data
12:30:13 [App     ] Reference image  50 paired with 8 views
12:30:13 [App     ] Depth-map for image 286 estimated using  8 images: 2000x1125 (299ms)
It seems that the depth information cannot be read. What could be the reason for this?

**Comment by cdcseacave** [comment]
the error is for creating a new file! check you have write permissions or that there is space
