### ISSUE TITLE
MVS file format

### ISSUE THREAD

**Issue by mrbemani** [cdcseacave/openMVS#119]
A description of the MVS file format would be nice.
It would help to edit between steps. ie. remove extra stuff between DensifyPointCloud and ReconstructMesh.

**Comment by cdcseacave** [comment]
There is no easy description, I simply serialize all objects in one continuous file. However, for the first step, you can force DensifyPointCloud to export in the interface MVS format which is easy to edit (selft explained in Interface.h). A better solution is to enhance the library itself with the filtering algorithm (which is I imagine you want to implement).

**Comment by mrbemani** [comment]
Thanks for the quick reply! ...Just out of curiosity. Since the OpenCV library is required, why not use cv::FileStorage?

**Comment by cdcseacave** [comment]
Cause the interface is meant to be used by anybody, even with no OpenCV dependency. So Interface.h is self contained and does not depend on any library.
