### ISSUE TITLE
RefineMesh segfault on linux

### ISSUE THREAD

**Issue by ORNis** [cdcseacave/openMVS#12]
Hi, 
I'm using openMVS successfully for about nearly one month, thank you for all your work ! All modules work perfectly except for the RefineMesh one. It systematically throws a segfault....

RefineMesh SfM/statue_mesh.mvs
08:58:31 [App     ] Build date: Sep 24 2015, 08:56:46
08:58:31 [App     ] CPU: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
08:58:31 [App     ] RAM: 62.87GB Physical Memory 29.80GB Virtual Memory
08:58:31 [App     ] OS: Linux 3.13.0-64-generic (x86_64)
08:58:31 [App     ] SSE & AVX compatible CPU & OS detected
08:58:31 [App     ] Command line: SfM/statue_mesh.mvs
Erreur de segmentation (core dumped)

I'm wondering if someone else running openMVS on Linux has already experienced the same issue.
Regards,
R.

**Comment by cdcseacave** [comment]
Hi,

Did you try the commit of yesterday on development branch?

Thanks!

**Comment by ORNis** [comment]
thanks,
Yes.
the issue is present on all revisions since you publish this module
R.

**Comment by ORNis** [comment]
...and on alll my datasets (small: 10 image to large: 1600 images)

**Comment by cdcseacave** [comment]
I found the problem, it is a bug in the gcc compiler. Till I push the change, please delete & on the line 449 from SceneRefine.cpp

**Comment by ORNis** [comment]
thanks ! It works now.

**Comment by cdcseacave** [comment]
please share your thoughts on using the library
and if you get some nice results (and possible) please share them with all of us :)

**Comment by C8PAN** [comment]
Hi,
I have used openMVG and openMVS for a few days. I have run the demo successfully. But when I repeated the demo several times, I sometimes have the same problem. Have you push any changes? 
I tried to comment line 449 from SceneRefine.cpp which is as follows at the moment:
         //FOREACH(idxImage, images)
It did not work.
I also tried to comment both line 449 and 450 from SceneRefine.cpp:
	//FOREACH(idxImage, images)
		//events.AddEvent(new EVTProjectMesh(idxImage, arrCameraFaces[idxImage]));
it still  did not work. 

I am working with Ubuntu 14.04 with cuda enabled. The first time I compiled openMVS, all the modules worked perfectly, including RefineMesh. But now I re-run the demo under a new directory, RefineMesh throws segmentation fault.

**Comment by FlachyJoe** [comment]
Hi C8PAN,
check twice your folders : as the openMVS files store relative paths you 
can't use them from another directory than the one used for creation.
It's missing some error handlers so such usage can results on segfault 
or silent failure. See #92

Can you try the attached script ? It's still in development 
("passthrough" options are not usable yet) but managed working folders 
quiet well.

**Comment by C8PAN** [comment]
@FlachyJoe 
Hi FlachyJoe, Thank you for your help. Unfortunately the problem remains. After a few attempts, I think the problem is due to cuda, specifically, the file SceneRefineCUDA.cpp. 
With cuda enabled, all the modules work perfectly except RefineMesh, the only module that use SceneRefineCUDA.cpp instead of SceneRefine.cpp. 
With cuda disabled, all the modules work perfectly (same folders, same commands as previous) including RefineMesh, who is now using SceneRefine.cpp instead of SceneRefineCUDA.cpp.
I hope the authors @cdcseacave @pmoulon can fix this problem because the cuda acceleration is very important (Running on my desktop, the whole pipeline takes a bit more than 10 minutes, and the module RefineMesh takes approximately 6 minutes  without cuda).

**Comment by C8PAN** [comment]
Hi, 
I found that the Module RefineMeshCUDA calls the function RefineMeshCUDA, RefineMeshCUDA calls SubdivideMesh, SubdivideMesh calls ListFaceAreas(maxAreas), ListFaceAreas calls faceMap(j,i). When j=266, i=4, idxFace=faceMap(j=266,i=4)=84093168, while areas.size()=1039625 which is smaller than idxFace. So the program throws a segmentation fault when it comes to the following line of code:
++areas[idxFace];
at line 2372 in the file SceneRefineCUDA.cpp
So it seems to me that faceMap is not correctly obtained from GPU memeory, see line 2363-2365.

**Comment by cdcseacave** [comment]
If you can share a small test case that reproduce the problem I'd be happy to see what happens.
PS: "Authors" is at singular for this project, just me

**Comment by C8PAN** [comment]
Hi cdcseacave,
I am sorry about my mistake. 
I guess a small test case would be just initial faceMap using CUDA and then check the values of it.

**Comment by charlescva** [comment]
I am having the same issue with on of my input datasets using CUDA on Linux.

oints inserted 5951 (100%, 1s18ms)               
16:09:25 [App     ] Delaunay tetrahedralization completed: 5951 points -> 5656 vertices, 35405 (+108) cells, 70864 (+162) faces (1s47ms)
Points weighted 5656 (100%, 1s535ms)              
16:09:27 [App     ] 	weighting completed in 1s535ms
16:09:27 [App     ] Delaunay tetrahedras weighting completed: 35513 cells, 71026 faces (1s687ms)
16:09:27 [App     ] Delaunay tetrahedras graph-cut completed (6754.27 flow): 3519 vertices, 7017 faces (233ms)
16:09:27 [App     ] Fixed 0/1 non-manifold edges/vertices and 0 faces removed: 0 pyramid3 and 0 pyramid4 (95ms)
16:09:27 [App     ] Fixed 0/0 non-manifold edges/vertices and 0 faces removed: 0 pyramid3 and 0 pyramid4 (101ms)
16:09:27 [App     ] Mesh reconstruction completed: 3520 vertices, 7017 faces (3s255ms)
16:09:28 [App     ] Mesh saved: 3520 vertices, 7017 faces (7ms)
16:09:28 [App     ] Removed 0 zero-area faces
16:09:28 [App     ] Removed 0 duplicate faces
16:09:28 [App     ] Removed 1 non-manifold faces
16:09:28 [App     ] Removed 0 degenerate vertices
16:09:28 [App     ] Removed 0 unreferenced vertices
16:09:28 [App     ] Removed 1 duplicate vertices
16:09:28 [App     ] Split 1 non-manifold vertices
16:09:28 [App     ] Split 1 non-manifold vertices
16:09:28 [App     ] Split 0 non-manifold vertices
16:09:28 [App     ] Removed 0 faces with edges longer than 14.579506
16:09:28 [App     ] Removed 0 connected components out of 1
16:09:28 [App     ] Removed 0 spikes
16:09:28 [App     ] Closed 1 holes and added 13 new faces
16:09:28 [App     ] Smoothed 3521 vertices
16:09:28 [App     ] Cleaned mesh: 3521 vertices, 7029 faces (163ms)
16:09:28 [App     ] Removed 0 zero-area faces
16:09:28 [App     ] Removed 0 duplicate faces
16:09:28 [App     ] Removed 0 non-manifold faces
16:09:28 [App     ] Removed 0 degenerate vertices
16:09:28 [App     ] Removed 0 unreferenced vertices
16:09:28 [App     ] Removed 0 duplicate vertices
16:09:28 [App     ] Split 0 non-manifold vertices
16:09:28 [App     ] Removed 0 spikes
16:09:28 [App     ] Closed 1 holes and added 9 new faces
16:09:28 [App     ] Cleaned mesh: 3521 vertices, 7038 faces (96ms)
16:09:28 [App     ] Removed 0 zero-area faces
16:09:28 [App     ] Removed 0 duplicate faces
16:09:28 [App     ] Removed 0 non-manifold faces
16:09:28 [App     ] Removed 0 degenerate vertices
16:09:28 [App     ] Removed 0 unreferenced vertices
16:09:28 [App     ] Removed 0 duplicate vertices
16:09:28 [App     ] Split 0 non-manifold vertices
16:09:28 [App     ] Cleaned mesh: 3521 vertices, 7038 faces (75ms)
16:09:28 [App     ] Scene saved (24ms):
	42 images (42 calibrated)
	0 points, 3521 vertices, 7038 faces
16:09:28 [App     ] Mesh saved: 3521 vertices, 7038 faces (4ms)
Segmentation fault
ottch@CLCFQ92:~/Development/reconstructions/UVA_Rotunda$ RefineMesh UVA_CUDA_MESH
UVA_CUDA_MESH.mlp      UVA_CUDA_MESH.mvs      UVA_CUDA_MESH.ply      UVA_CUDA_MESH_raw.ply  
ottch@CLCFQ92:~/Development/reconstructions/UVA_Rotunda$ RefineMesh UVA_CUDA_MESH.mvs
16:09:51 [App     ] Build date: Mar  2 2018, 14:59:13
16:09:51 [App     ] CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
16:09:51 [App     ] RAM: 31.13GB Physical Memory 19.31GB Virtual Memory
16:09:51 [App     ] OS: Linux 4.9.0-1-amd64 (x86_64)
16:09:51 [App     ] SSE & AVX compatible CPU & OS detected
16:09:51 [App     ] Command line: UVA_CUDA_MESH.mvs
16:09:51 [App     ] CUDA device 0 initialized: Quadro M3000M (compute capability 5.2; memory 3.94GB)
16:09:51 [App     ] Scene loaded (21ms):
	42 images (42 calibrated) with a total of 83.06 MPixels (1.98 MPixels/image)
	0 points, 3521 vertices, 7038 faces
16:09:51 [App     ] Refine mesh at: 0.25 image scale
16:09:52 [App     ] Compute Incident Faces Rows: 270
RefineMesh: /home/ottch/Development/openmvs/openMVS-master/libs/MVS/../Common/List.h:353: TYPE& SEACAVE::cList<TYPE, ARG_TYPE, useConstruct, grow, IDX_TYPE>::operator[](SEACAVE::cList<TYPE, ARG_TYPE, useConstruct, grow, IDX_TYPE>::IDX) [with TYPE = short unsigned int; ARG_TYPE = short unsigned int; int useConstruct = 0; int grow = 16; IDX_TYPE = unsigned int; SEACAVE::cList<TYPE, ARG_TYPE, useConstruct, grow, IDX_TYPE>::IDX = unsigned int]: Assertion `index < _size' failed.
Aborted


I will have to review the paper for http://is.ulsan.ac.kr/files/announcement/441/PAMI-2012%20High%20Accuracy%20and%20Visibility-Consistent%20Dense%20Multiview%20Stereo.pdf and hopefully understand what is being attempted in this module and perhaps determine the solution to this problem.  The RefineMesh without CUDA works well, however some models can take several hours to refine and this delay is frustrating when attempting to understand Refinement results with varied settings and multiple iterations.  Expensive GPUs are available and I would like to use them.

**Comment by xiaoxiongkubi** [comment]
![2019-01-30 09-53-25](https://user-images.githubusercontent.com/35690284/51952851-eb0fd380-2474-11e9-8b30-f6f24e45cb01.png)
Thanks for your reply. My GPU memory is 6g, I monitor the change of gpu memory just find RefineMesh use little memory .I still cannot avoid this error...
