### ISSUE TITLE
Replace FindCGAL.cmake

### ISSUE THREAD

**Issue by wow2006** [cdcseacave/openMVS#120]
### Specifications like the version of the project, operating system, and hardware

version 0.7 ,Fedora 24, CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz, RAM: 62.75GB Physical Memory 4.00GB Virtual Memory
### Steps to reproduce the problem

I Install CGAL using package manager 

> > sudo dnf install CGAL-devel.x86_64
> > current FindCGAL can not found CGAL .
1. cd build && cmake .. -DVCG_DIR=$$$
2. error can not found FindCGAL.cmake
3. I replace FindCGAL.cmake
4. replace CGAL_LIB -> CGAL_LIBRARIES at libs/MVS/CMakeLists.txt @ line 40
5. try to run cmake again it working

note i convert FindCGAL.cmake -> FindCGAL.txt to attach it.
[FindCGAL.txt](https://github.com/cdcseacave/openMVS/files/454930/FindCGAL.txt)

I hope to help

**Comment by cdcseacave** [comment]
Thank you, but this version does not work on windows. Please fix the problem you have on Fedora in the original version, and send me the patch.

**Comment by wow2006** [comment]
Hello,

Thank you for your patience. I would like to attach two patches.

- [FedoraBuilding.txt](https://github.com/cdcseacave/openMVS/files/489901/FedoraBuilding.txt), Steps to build OpenMVS for Fedora 24.
- [AddCGALPATH_Fedora.txt](https://github.com/cdcseacave/openMVS/files/489902/AddCGALPATH_Fedora.txt), Add CGAL Path to Original CGALconfig file.

I recommend First Patch which did not add fixed path. It use CGAL_ROOT to give path to CGALConfig.
I hope That help. Thank you for this Library.
