### ISSUE TITLE
TextureMesh problem

### ISSUE THREAD

**Issue by ADDDDD** [cdcseacave/openMVS#122]
### How can I control the resolution of the texture image?

**Comment by cdcseacave** [comment]
You can rescale it using any image editor, or use --resolution-level parameter during texture generation

**Comment by ADDDDD** [comment]
ok, I will try to use --resolution-level parameter . Thanks a lot!

**Comment by gree303** [comment]
May I ask if 32768*32768 is the overall maximum in all tools. Or is this number just some Matlab internal maximum? Any workaround to this?

**Comment by ADDDDD** [comment]
In my case, I try to rescale it in some image editors, but failed.

**Comment by gree303** [comment]
you could set up a tiler which cuts the image into multiple pieces. process them and stitch it back together. keep in mind to have a some fill on the edges in case of "blur" or any other fancy filter
