### ISSUE TITLE
Why my images cannot compute densifypointcloud after openmvg(UI GCP TOOLS)?

### ISSUE THREAD

**Issue by mitsubishisony** [cdcseacave/openMVS#124]
I have several UAV images. When I compute densifypointcloud through openMVG+openMVS. It has a good result. Therefore, I use GCP UI to add some GCP point(4~5 points) after openmvg progress. Then the openmvs cannot conpute the densifypointcloud. It shows 0 point after openmvs computation. It dose not make any ply file? What is the problem? 
BTW, when I use GCP UI to save the project. I modify the file name to any, the same result also overright the source file(sfm_data.bin). Why?

07:24:31 [App ] Build date: Jul 12 2016, 12:02:31
07:24:31 [App ] CPU: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
07:24:31 [App ] RAM: 15.89GB Physical Memory 128.00TB Virtual Memory
07:24:31 [App ] OS: Windows 10+ x64
07:24:31 [App ] SSE & AVX compatible CPU & OS detected
07:24:31 [App ] Command line: D:\test\exercise\output\mvs_geo\scene_geo.mvs
07:24:31 [App ] Scene loaded (160ms):
7 images (4 calibrated) with a total of 45.78 MPixels (11.44 MPixels/image)
2786 points, 0 vertices, 0 faces
07:24:31 [App ] Preparing images for dense reconstruction completed: 7 images (323ms)
07:24:31 [App ] Selecting images for dense reconstruction completed: 4 images (1ms)
07:24:32 [App ] Reference image 0 paired with 2 views
07:24:32 [App ] Reference image 1 paired with 3 views
07:24:34 [App ] Reference image 2 paired with 3 views
07:24:35 [App ] Reference image 3 paired with 2 views
07:24:40 [App ] Depth map 0 filtered using 2 other images: 1996364/1996364 depths discarded (317ms)
07:24:40 [App ] Depth map 3 filtered using 2 other images: 2519306/2519306 depths discarded (319ms)
07:24:41 [App ] Depth map 2 filtered using 3 other images: 2335050/2335050 depths discarded (611ms)
07:24:41 [App ] Depth map 1 filtered using 3 other images: 2249120/2249120 depths discarded (715ms)
07:24:49 [App ] Depth-maps fused and filtered: 4 depth-maps, 9099840 depths, 0 points (0%%) (7s151ms)
07:24:49 [App ] Densifying point-cloud completed: 0 points (18s176ms)
07:24:49 [App ] Scene saved (1ms):
7 images (4 calibrated)
0 points, 0 vertices, 0 faces
07:24:49 [App ] MEMORYINFO: {
07:24:49 [App ] PageFaultCount 467848
07:24:49 [App ] PeakWorkingSetSize 569.95MB
07:24:49 [App ] WorkingSetSize 138.64MB
07:24:49 [App ] QuotaPeakPagedPoolUsage 310.33KB
07:24:49 [App ] QuotaPagedPoolUsage 308.60KB
07:24:49 [App ] QuotaPeakNonPagedPoolUsage 25.97KB
07:24:49 [App ] QuotaNonPagedPoolUsage 21.59KB
07:24:49 [App ] PagefileUsage 208.00MB
07:24:49 [App ] PeakPagefileUsage 591.14MB
07:24:49 [App ] } ENDINFO

 I try to convert the sfm_data.bin file to ply file. The registration is work well. The ply file is shows:

Before Registration:
ply
format ascii 1.0
element vertex 6645
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
0.00422358 -0.00145019 0.0528926 0 255 0
0.451963 -0.0095177 0.0316263 0 255 0
0.859444 -0.00296969 0.0343761 0 255 0
1.25795 0.00972832 0.0378345 0 255 0
0.168813 -0.430477 1.09806 255 255 255
0.727493 -0.544852 1.20904 255 255 255
0.534126 0.547679 0.960416 255 255 255
0.809692 -0.542868 1.20661 255 255 255
0.174053 -0.771535 1.11756 255 255 255
0.431114 -0.451336 1.15318 255 255 255
0.912816 -0.921614 1.32534 255 255 255
...............

After Registration :
ply
format ascii 1.0
element vertex 6650
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
83.7101 48.1057 95.1847 0 255 0
91.9136 63.3377 93.7094 0 255 0
100.743 78.8991 89.7542 0 255 0
109.226 92.3147 84.4908 0 255 0
59.7329 63.4192 64.4109 255 255 255
65.9323 82.911 56.7324 255 255 255
96.4723 51.7319 49.8063 255 255 255
67.8394 85.1661 56.2194 255 255 255
51.1759 70.8928 68.1766 255 255 255
63.3734 71.8487 60.142 255 255 255
59.5266 94.7669 57.5238 255 255 255
77.7184 78.9585 51.9799 255 255 255
70.8218 91.2781 53.7649 255 255 255
78.684 80.794 51.0776 255 255 255
89.7157 42.1862 53.3728 255 255 255
...........
The bin file(after registration) is not work well with openMVS. The result is also has 0 point after DensifyPointCloud.

Why?

**Comment by cdcseacave** [comment]
If I correctly understand, you say the registration with OpenMVG goes well, however I see that out of the 7 images only 4 are registered. How do you check the registration went well? Could you share the 7 images and the mvs file you try to densify?

**Comment by riyueshi** [comment]
@mitsubishisony  I have received your email. It seems I had meet this problem several month ago. but I cannot remember what measure finally solved this problem. As cdcseacave said there might be some error in the image registration progress. Have you checked the RMS value after run openMVG. Since the GCP you used have a huge value, you should move the coordinate origin as you have already done, after doing that you could try to make a scales on the GCP (eg. divided by 50.0 in your data, I am not sure whether this help but I tried this). And one more thing, have you ever checked the residual error after you add GCP to the data using openMVG.

**Comment by cdcseacave** [comment]
yes, please follow @riyueshi advises in case the registration id really ok: parts of the MVS pipeline are done in single floating point precision, which is sensitive to the numbers range.

**Comment by pmoulon** [comment]
I think @cdcseacave is right.
So please process your initial scene (the unregistered one) and then apply the transform found by the GCP registration to the OpenMVS resulting mesh.

**Comment by mitsubishisony** [comment]
@riyueshi @cdcseacave @pmoulon 
I re-select 4 images for processing. During the openMVG, the 4 image are calibrated. The RMSE after BA is 0.267258. In GCP, I have make a scale, such as 100. The range of XYZ coordinate is from 0-1 and keep 2 decimal. After GCP, the RMSE is 0.943653. Then I use openMVG2openMVS module to transform the file format. And use DensifyPointCloud module to do next processing. The result also shows 0 point. The image and mvs file have been sent to your email.
The log file of DensifyPointCloud is shown as:

15:09:57 [App     ] Build date: Sep 21 2016, 20:43:31
15:09:57 [App     ] CPU: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
15:09:57 [App     ] RAM: 15.89GB Physical Memory 128.00TB Virtual Memory
15:09:57 [App     ] OS: Windows 10+ x64
15:09:57 [App     ] SSE & AVX compatible CPU & OS detected
15:09:57 [App     ] Command line: D:\test\exercise\output4\mvs\scene100_2.mvs
15:09:57 [App     ] Scene loaded (145ms):
	4 images (4 calibrated) with a total of 45.78 MPixels (11.44 MPixels/image)
	6639 points, 0 vertices, 0 faces
15:09:58 [App     ] Preparing images for dense reconstruction completed: 4 images (316ms)
15:09:58 [App     ] Selecting images for dense reconstruction completed: 4 images (3ms)
15:09:58 [App     ] Reference image   0 paired with 2 views
15:09:59 [App     ] Reference image   1 paired with 3 views
15:10:00 [App     ] Reference image   2 paired with 3 views
15:10:01 [App     ] Reference image   3 paired with 2 views
15:10:06 [App     ] Depth map   0 filtered using 2 other images: 2155328/2190995 depths discarded (751ms)
15:10:06 [App     ] Depth map   3 filtered using 2 other images: 2467848/2522926 depths discarded (838ms)
15:10:06 [App     ] Depth map   2 filtered using 3 other images: 2283943/2283943 depths discarded (855ms)
15:10:06 [App     ] Depth map   1 filtered using 3 other images: 2126440/2229056 depths discarded (1s41ms)
15:10:14 [App     ] Depth-maps fused and filtered: 4 depth-maps, 9226920 depths, 0 points (0%%) (6s546ms)
15:10:14 [App     ] Densifying point-cloud completed: 0 points (16s933ms)
15:10:14 [App     ] Scene saved (1ms):
	4 images (4 calibrated)
	0 points, 0 vertices, 0 faces
15:10:14 [App     ] MEMORYINFO: {
15:10:14 [App     ] 	PageFaultCount 460969
15:10:14 [App     ] 	PeakWorkingSetSize 620.89MB
15:10:14 [App     ] 	WorkingSetSize 112.64MB
15:10:14 [App     ] 	QuotaPeakPagedPoolUsage 310.30KB
15:10:14 [App     ] 	QuotaPagedPoolUsage 308.57KB
15:10:14 [App     ] 	QuotaPeakNonPagedPoolUsage 27.03KB
15:10:14 [App     ] 	QuotaNonPagedPoolUsage 21.85KB
15:10:14 [App     ] 	PagefileUsage 208.35MB
15:10:14 [App     ] 	PeakPagefileUsage 660.24MB
15:10:14 [App     ] } ENDINFO

**Comment by mitsubishisony** [comment]
@cdcseacave 
After GCP processing, I transform the file format from sfm_data.bin to ply file. And add it in to Meshlab, It is shown well. The coordinate also shown well.

**Comment by mitsubishisony** [comment]
@cdcseacave @pmoulon 
![scene100_2](https://cloud.githubusercontent.com/assets/22383990/18914278/f856a912-85be-11e6-84a7-bdacbcfc8dd6.jpg)
Please change the extension name of scene100_2.jpg to scene100_2.mvs,DensifyPointCloud_Result.jpg
![densifypointcloud_result](https://cloud.githubusercontent.com/assets/22383990/18914390/8acab7d4-85bf-11e6-84e0-0332d37eec1a.jpg)
 to DensifyPointCloud_Result.log.
![dji_0240](https://cloud.githubusercontent.com/assets/22383990/18914297/14eb3886-85bf-11e6-9d00-1fca26a1f3e7.JPG)
![dji_0241](https://cloud.githubusercontent.com/assets/22383990/18914299/14ed698a-85bf-11e6-9b6b-bd330e137ca4.JPG)
![dji_0242](https://cloud.githubusercontent.com/assets/22383990/18914298/14ebb072-85bf-11e6-8ed2-d5de1cae4d41.JPG)
![dji_0243](https://cloud.githubusercontent.com/assets/22383990/18914300/14f34800-85bf-11e6-89e8-649d06206f56.JPG)

**Comment by mitsubishisony** [comment]
@cdcseacave @pmoulon 
Please change the extension name txt to mvs or jpg.
[DensifyPointCloud_Result.txt](https://github.com/cdcseacave/openMVS/files/498073/DensifyPointCloud_Result.txt)
[scene100_2_dense.txt](https://github.com/cdcseacave/openMVS/files/498072/scene100_2_dense.txt)
[DJI_0240.txt](https://github.com/cdcseacave/openMVS/files/498078/DJI_0240.txt)
[DJI_0241.txt](https://github.com/cdcseacave/openMVS/files/498076/DJI_0241.txt)
[DJI_0242.txt](https://github.com/cdcseacave/openMVS/files/498075/DJI_0242.txt)
[DJI_0243.txt](https://github.com/cdcseacave/openMVS/files/498077/DJI_0243.txt)

**Comment by cdcseacave** [comment]
Thanks for sharing the data. However on my machine it works just fine, here are the results:
![sc](https://cloud.githubusercontent.com/assets/2802670/18917370/88ea08fc-854c-11e6-9a34-ad2d2ad10194.jpg)


[scene_dense.ply.zip](https://github.com/cdcseacave/openMVS/files/498276/scene_dense.ply.zip)

**Comment by pmoulon** [comment]
@mitsubishisony 
You must process the densification before doing the GCP registration.
And then apply the transform found by GCP UI to the dense point cloud.

**Comment by mitsubishisony** [comment]
@cdcseacave 
In my machine, it works bad. Why? What is your machine platform? My platform is win10 x64+ VS2015 X64.
Could you give me a latest version of openMVS by exe file?
I download from https://github.com/cdcseacave/openMVS and https://github.com/cdcseacave/openMVS to get source code and exe file. But they can not word with my mvs file（after GCP UI）.

**Comment by mitsubishisony** [comment]
@pmoulon 
The GCP UI only support sfm_data.bin file. However, after DensifyPointCloud on openMVS, the file format is mvs. How can I transform the format from mvs to bin, and add to the GCP UI?

**Comment by mitsubishisony** [comment]
@cdcseacave 
Could you process the attached file scenegeo.mvs. Please change the extension name to mvs. The range of coordinate of this file is from 0-100. 
[scenegeo.txt](https://github.com/cdcseacave/openMVS/files/499513/scenegeo.txt)

**Comment by mitsubishisony** [comment]
I have uploaded the video of my progress pipeline.
Could you tell me, where is mistake in my progress video.
The video is youtube website.
https://www.youtube.com/watch?v=Zx302S-quM4

**Comment by cdcseacave** [comment]
I also use Windows 10 x64 with openMVS_sample binaries. I run DensifyPointCloud as you do on the MVS file you just sent and it run fine. So the only explanation is that the MVS file you just sent is not the same with the file you used.

**Comment by mitsubishisony** [comment]
I use uploaded file scene100_2_dense.txt to do DensifyPointCloud.exe. But there is also 0 point as result.
The result of scenegeo.txt also have not any point?
Could you process the scenegeo.txt file witn openMVS?

**Comment by mitsubishisony** [comment]
I find the reason why the openMVS result is 0 point. In each progress of openMVS, the dmap file should be removed.

**Comment by pmoulon** [comment]
So you can obtain the desired output and close this issue?

**Comment by mitsubishisony** [comment]
@pmoulon 
OK,thanks for reply.
