### ISSUE TITLE
Error: typedef redefinition with different types

### ISSUE THREAD

**Issue by zharvey-welltok** [cdcseacave/openMVS#126]
### Specifications like the version of the project, operating system, and hardware
Using whatever is in the `master` branch on Mac OS (El Capitan, `10.11.5`). MacBrook Pro.

### Steps to reproduce the problem
I followed the [build instructions](https://github.com/cdcseacave/openMVS/wiki/Building) from your GitHub docs. I was able to run the following commands without any problems:

    brew update
    brew tap homebrew/science
    brew install boost eigen opencv cgal ceres-solver
    cd ~/thelab
    main_path=`pwd`

    git clone https://github.com/cdcseacave/VCG.git vcglib

    git clone https://github.com/cdcseacave/openMVS.git

    mkdir openMVS_build && cd openMVS_build
    cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="$main_path/vcglib"
    
But when I ran:

    make && sudo make install

I get the following output/errors:

    /Users/myuser/thelab/openMVS/libs/IO/../Common/SML.h:29:21: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
            ~SMLVALUE_TYPE() { delete data; }
                               ^      ~~~~
    In file included from /Users/myuser/thelab/openMVS/libs/IO/ImageTIFF.cpp:14:
    In file included from /usr/local/include/tiffio.h:33:
    /usr/local/include/tiff.h:77:23: error: typedef redefinition with different types ('long' vs 'int64_t' (aka 'long long'))
    typedef TIFF_INT64_T  int64;
                          ^
    /usr/local/include/opencv2/core/types_c.h:163:20: note: previous definition is here
       typedef int64_t int64;
                       ^
    In file included from /Users/myuser/thelab/openMVS/libs/IO/ImageTIFF.cpp:14:
    In file included from /usr/local/include/tiffio.h:33:
    /usr/local/include/tiff.h:78:23: error: typedef redefinition with different types ('unsigned long' vs 'uint64_t' (aka 'unsigned long long'))
    typedef TIFF_UINT64_T uint64;
                          ^
    /usr/local/include/opencv2/core/types_c.h:164:21: note: previous definition is here
       typedef uint64_t uint64;
                        ^
    1 warning and 2 errors generated.
    make[2]: *** [libs/IO/CMakeFiles/IO.dir/ImageTIFF.cpp.o] Error 1
    make[1]: *** [libs/IO/CMakeFiles/IO.dir/all] Error 2
    make: *** [all] Error 2

**Please advise!**

**Comment by cdcseacave** [comment]
the version of the TIFF library included with opencv differs from the version installed on the machine:
- either make opencv use the installed version
- or uninstall the machine version and make openmvs use opencv version of TIFF
- or make sure they are the same version

**Comment by zharvey-welltok** [comment]
Thanks @cdcseacave - How can I tell which version of the TIFF library OpenCV is trying to use? Any command line magic you can suggest here? Thanks!

**Comment by cdcseacave** [comment]
can't help here, I tried before, but I didn't manage to opencv easily use the system TIFF

**Comment by zharvey-welltok** [comment]
Gotchya, so, all of your suggestions above seem to require tweaking OpenCV in some way, or getting OpenMVS to use OpenCV a particular way. If what you're saying is that OpenCV isn't easily manipulated, can you offer any concrete suggestions for getting OpenMVS to build here?

I'm not worried about getting OpenMVS working as efficiently as possible, tuning things, etc. I have created some output from OpenMVG and am trying to load it (as input) into OpenMVS so I can generate a dense point cloud and some 3D reconstructions.

This is a "hello world!" type sample problem I'm trying to get working, so I'll happily go with any route that you feel confident will work here! Thanks in advance for any and all help!

**Comment by cdcseacave** [comment]
no, the simplest solution and the one I am using is the third

**Comment by zharvey-welltok** [comment]
Ok, I'm honestly not trying to be a PITA here (really!!!) but for that third option you state:

> or make sure they are the same version

If I'm understanding you correctly, this means I need to:

1. Figure out which version of the TIFF library is installed on my machine (we'll call this `LOCAL_TIFF_VERS`; then
2. Figure out which version of the TIFF library OpenCV is trying to use (we'll call this `OPENCV_TIFF_VERS`; then
3. Figure out a game plan to make sure `LOCAL_TIFF_VERS` is the same as `OPENCV_TIFF_VERS`

You mentioned that you were able to get this working, which again to me, means that you were able to figure out what `OPENCV_TIFF_VERS` was on your machine.

**How did you figure this out?!?** (Or am I missing something?!?) Thanks again!

**Comment by paulinus** [comment]
If you don't need tiff support, you can comment out this lines https://github.com/cdcseacave/openMVS/blob/8cbeda19ad7c240723fd7583e34691f77fd0e80e/libs/IO/CMakeLists.txt#L19-L25
That worked for me to build on a Mac

**Comment by cdcseacave** [comment]
all third party libraries of opencv are located in 3rdparty folder

**Comment by zharvey-welltok** [comment]
Hey now! Thanks @paulinus - **that worked for me too!**
