### ISSUE TITLE
How to import data from OpenMVG?

### ISSUE THREAD

**Issue by zharvey-welltok** [cdcseacave/openMVS#127]
### Specifications like the version of the project, operating system, and hardware
* Using `master` branch
* Mac OS El Capitan `10.11.5`
* MacBook Pro

### Steps to reproduce the problem
I am trying to play around with SfM and 3D reconstructions for the first time. I used OpenMVG to convert a series of images into some outputs (which I *believe* are a sparse point cloud and some other parameters) that can be fed into OpenMVS as inputs. My ultimate goal is to generate a 3D scene (with textures/colors/etc.) from the original image set I provided to OpenMVG.

I have successfully built OpenMVS using the [Mac OS build instructions](https://github.com/cdcseacave/openMVS/wiki/Building#mac-os-x-compilation). When I navigate to `openMVS_build/bin` I see the following binaries/executables:

* `DensifyPointCloud`
* `InterfaceVisualSFM`
* `ReconstructMesh`
* `RefineMesh`
* `TextureMesh`

However, according to the [OpenMVG documentation](http://openmvg.readthedocs.io/en/latest/software/MVS/OpenMVS/), it looks like OpenMVS has an importer/converter tool called `InterfaceOpenMVG` that I could use like so:

    InterfaceOpenMVG -i PATH/sfm_data.json -o scene.mvs

Does anybody know where this tool is located, or if there's a separate repo that I have to build it from? Thanks in advance!

**Comment by cdcseacave** [comment]
OpenMVG has an exporter to OpenMVS

**Comment by zharvey-welltok** [comment]
Thanks @cdcseacave - is that exporter the `openMVG_main_openMVG2openMVS` tool mentioned in that link above?

Either way, what is that `InterfaceOpenMVG`? Is it something that used to exist in OpenMVS but is no longer supported? Just curious.

**Comment by pmoulon** [comment]
InterfaceOpenMVG is now deprecated.
Please follow the instructions here:
http://openmvg.readthedocs.io/en/latest/software/MVS/OpenMVS/

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon 

So on that page (same as what I linked above earlier), there seems to be an OpenMVG tool that I can use like so:

    openMVG_main_openMVG2openMVS -i PATH/sfm_data.json -d OUTPUT_PATH -o OUTPUT_PATH/Scene

I build OpenMVG and then ran `software/SfM/tutorial_demo.py` (unmodified). Now I'm looking to connect the outputs of that Python script to this `openMVG_main_openMVG2openMVS` above. It looks like there is a `tutorial_out/sfm_data.json` file, and so I think I can tweak that command to be:

    openMVG_main_openMVG2openMVS -i ~/workspace/openMVG_build/software/SfM/tutorial_out/sfm_data.json -d OUTPUT_PATH -o OUTPUT_PATH/Scene

...but what about the other inputs that OpenMVG provides (and that `openMVG_main_openMVG2openMVS` requires)? Any ideas? Thanks again!

**Comment by pmoulon** [comment]
You don't need to specify other input. The sfm_data file contain all the data about the sfm scene.
Just use one from the reconstruction_sequential or reconstruction_global directory

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon, last followup here (I promise!).

I ran the following command:

    openMVG_Build/Darwin-x86_64-RELEASE/RELEASE/openMVG_main_openMVG2openMVS -i tutorial_out/matches/sfm_data.json -d tutorial_out/reconstruction_global/ -o tutorial_out/reconstruction_global/scene.mvs

And got this as output:

```
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
error: no image using camera 0 of platform 0
Scene saved to OpenMVS interface format:
	11 images (0 calibrated)
	0 Landmarks
```

Can you (or anyone) confirm that this was a correct use of args and that the output indicates success (meaning, I have successfully converted `tutorial_demo.py`'s output into an OpenMVS scene)? Thanks again!

**Comment by pmoulon** [comment]
As I said you must provide one of the sfm_data file that is reconstruction_sequential or reconstruction_global directory.
The one in matches contains only image description, there is not 3D data inside it.
