### ISSUE TITLE
DensifyPointCloud yields "Segmentation fault: 11"

### ISSUE THREAD

**Issue by zharvey-welltok** [cdcseacave/openMVS#128]
### Specifications like the version of the project, operating system, and hardware
* Using `master` branch
* Mac OS El Capitan `10.11.5`
* MacBook Pro

### Steps to reproduce the problem
I used the following command to convert OpenMVG outputs into an OpenMVS-compatible scene:

    openMVG_main_openMVG2openMVS -i /path/to/openmvs-examples/sfm_data.bin -d /path/to/openmvg-examples -o /path/to/openmvg-examples/scene.mvs

This created a `scene.mvs` at the correct location.

I then ran:

    DensifyPointCloud /path/to/openmvg-examples/scene.mvs

And got this as output:

```
20:41:06 [App     ] Build date: Oct  4 2016, 15:29:46
20:41:06 [App     ] CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
20:41:06 [App     ] RAM: 16.00GB Physical Memory 16.00GB Virtual Memory
20:41:06 [App     ] OS: Darwin 15.5.0 (x86_64)
20:41:06 [App     ] SSE & AVX compatible CPU & OS detected
20:41:06 [App     ] Command line: scene.mvs
20:41:06 [App     ] Camera model loaded: platform 0; camera  0; f 1.056x1.056; poses 10
Segmentation fault: 11
```

When I list all the files/folders in that directory, all I see is a `DensifyPointCloud-161004204106013DB8.log` created there (whose contents are identical to the output posted above). I **do not** see anything like `scene_dense.mvs` or similar.

**Has something gone wrong (if so, how do I troubleshoot it?) or am I just looking in the wrong place (if so, where should I be looking for a `scene_dense.mvs`?**

**Comment by cdcseacave** [comment]
yes, cause by using different version of jpg or png libraries (between the system and opencv)

**Comment by zharvey-welltok** [comment]
Oh boy, here we go with OpenCV again...

Which exact file under `third_party/jpeg/` will tell me the version that OpenCV is trying to use?
