### ISSUE TITLE
Where is the MVS file format documented?

### ISSUE THREAD

**Issue by zharvey-welltok** [cdcseacave/openMVS#129]
### Specifications like the version of the project, operating system, and hardware
* Using `master` branch
* Mac OS El Capitan `10.11.5`
* MacBook Pro

### Steps to reproduce the problem
It is my understanding that OpenMVG binaries such as `DensifyPointCloud`, `ReconstructMesh` and `TextureMesh` all produce MVS files (`*.mvs`) as outputs.

Upon opening up one such a file (`scene.mvs`) I see it is not a plaintext file.

I'd like to take a stab at writing a tool that could convert these MVS files into [Blender files](http://archive.blender.org/development/architecture/blender-file-format/) (`*.blend`) so that the 3D models could be loaded into Blender (unless such a tool already exists!).

**Is there any documentation surrounding MVS file formats?**

**Comment by pmoulon** [comment]
=> Wiki https://github.com/cdcseacave/openMVS/wiki/Interface

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon - a few quick followup questions here. From the the **Output** section in that link:

> The output is a triangle mesh, exported by default in the PLY file format, and a texture image, exported by default as PNG. OBJ is also supported.

1. Does this mean that OpenMVS outputs both a MVS file as well as a PLY file?
2. Does Blender need **both** the PLY file and the PNG (texture image) in order to load the model properly?
3. Once I have the PLY file and PNG, do I need to run any other special processing to make this output compatible with Blender?

Thanks again!

**Comment by pmoulon** [comment]
1. Yes
2. Blender can load a PLY or a textured PLY
3. I don't think so.

Since Blender 2.56 the PLY reader must be integrated.
https://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/Import-Export/Stanford_PLY
