### ISSUE TITLE
TextureMesh throws an out_of_range exception

### ISSUE THREAD

**Issue by ORNis** [cdcseacave/openMVS#13]
07:52:10 [App     ] Command line: -i SfM/sfm_data_mesh_refine.mvs --resolution-level 4
07:52:20 [App     ] Initializing images completed: 1625 images (8s199ms)
08:07:25 [App     ] Assigning the best view to each face completed: 1159345 faces (15m5s397ms)
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Abandon (core dumped)

Note that I have already textured this dataset with a coarser mesh (~300 k facets) without experiencing this problem. 
Regards,
R.

**Comment by cdcseacave** [comment]
might be indeed a problem with the size of the mesh, but not due to the number of faces, but to the size of each face which I think in your case is way too small relative to the resolution 4 you chose for the images. Do you have enough memory to try the same mesh with a higher resolution?

Do you get the same error on a smaller dataset, so that I can debug?

**Comment by ORNis** [comment]
Ok thanks. Running with --resolution-level 2 to see if I have more luck...

**Comment by ORNis** [comment]
So... no luck at levels 2,1 and 0. It's the first time I get this error.

**Comment by cdcseacave** [comment]
I see. Me too is the first time I hear about this error and I can not debug without a test scene.

Could you please check if the mesh is manifold?

**Comment by ORNis** [comment]
So you were right, thanks
In meshlab I did a Filters > cleaning and repairing > split vertices incident on non Manifold Faces
then launched with `--mesh-file`  option pointing to my cleaned mesh.
it is still computing but it seems like the original problem is gone...

**Comment by cdcseacave** [comment]
Even so, it is not ok to crash, and a non-manifold mesh can create problems in all the modules. However, I did not find a good way to fix this kind of problem yet, none of the mesh processing libraries I know offers a good fix. Therefore, I implemented a custom algorithm, that seems to miss some non-manifold faces.

**Comment by ORNis** [comment]
at last, the texture file is so hudge that I'm not able to open it in CC nor Meshlab.
btw, 
I'm not sure, but maybe there is an issue with the way you pack the texture patches.
![converted](https://cloud.githubusercontent.com/assets/1537100/10191868/406fab10-6778-11e5-87c2-5f12277ca1e7.png)

**Comment by cdcseacave** [comment]
yes, there seems to be a problem with estimating the texture size (packing it is fine, it is just too big)
the texture can be also exported in multiple images, but PLY format does not support this

**Comment by ORNis** [comment]
obj does, but I guess you are already aware of that.

**Comment by pmoulon** [comment]
In order to make the texture loadable in Meshlab and co... just open resize the image and save it again. Since UVs coords are in [0;1] the texture will still be fine.

**Comment by cdcseacave** [comment]
yes, I even started implementing an OBJ exporter, but I stop cause it is such an ugly and text only format

**Comment by pmoulon** [comment]
VCG could be used to export the mesh as OBJ file.
Else I have found recently this mesh container... http://www.openmesh.org/

**Comment by cdcseacave** [comment]
OpenMesh is just a container for operating on a mesh, just like CGAL and VCG or SurfaceMesh (which by the way seems the best of them - https://opensource.cit-ec.de/projects/surface_mesh)... we need a progressive mesh file format more or less like https://github.com/Esri/i3s-spec but I am not aware of any such formats

**Comment by ORNis** [comment]
http://vcg.isti.cnr.it/nexus/ ?

**Comment by ORNis** [comment]
I think there is no texture support in the nexus spec

**Comment by cdcseacave** [comment]
:) that is fanny cause I was just reading about Nexus, and yes, it is exactly what we would need, except there is no texture support

**Comment by pmoulon** [comment]
- Nexus for mesh
- PTex for texture http://ptex.us/ (no more UVs)

**Comment by ORNis** [comment]
Intersing. 
so, here we are: https://xkcd.com/927/

**Comment by pmoulon** [comment]
:+1:

**Comment by cdcseacave** [comment]
@ORNis :) true, that is why I will not develop any new standard, just wait for the right one to emerge
@pmoulon indeed, interesting the ptex method, I will search for the paper explaining it...

good news though, I just received a reply from the developer of Nexus and he says that he is actually working right now on texture support, and it will be ready in maximum 2 weeks. So no more worries about storing and streaming meshes!!! He even requested for a mesh sample from OpenMVS

In the light of this recent events, what we need to focus on next is support for huge datascenes, which translates to clustering the input dataset, apply OpenMVS on each cluster, and glue everything back together. Main issues:
- develop a good clustering method that takes as parameter only the maximum number of pixels to be contained in a cluster (and be able to automatically find the minimum number of such clusters)
- zip such clustered meshes together
- smooth texture transition between clusters

**Comment by cdcseacave** [comment]
The conclusion of this issue is that non-manifold input makes TextureMesh crash.

**Comment by ORNis** [comment]
@cdcseacave: it seems that multires texture support has finaly landed in nexus 4.0

**Comment by pmoulon** [comment]
Just a reminder about Nexus 4.0 (http://vcg.isti.cnr.it/nexus/)
There is also an updated version of 3DHOP http://3dhop.net/

**Comment by pmoulon** [comment]
I got a similar issue when I try to texture a model:
```terminate called recursively
terminate called after throwing an instance of 'std::out_of_range'
terminate called recursively
  what():  _Map_base::at```

I tried to provide a simplified mesh or a mesh where I have fixed its error (non manifold faces).

By launching multiple time I realized that in fact, the issue seems to be in the `seam` process because running with `--global-seam-leveling 1 --local-seam-leveling 0` is creating an issue, but running with `--global-seam-leveling 0 --local-seam-leveling 1` does not create a crash.

Is it possible that a bug remains in the global seam leveling. I don't know if I will have time to investigate and try to pinpoint the issue but I wanted to let you know that for me the behavior seems to be in the `seam` algorithm.

**Comment by cdcseacave** [comment]
Thx Pierre! I saw this type of error when the input mesh is non-manifold. Pls make sure that it is!

**Comment by donlk** [comment]
Hey, I just looked at this commit that references this issue:
https://github.com/cdcseacave/openMVS/commit/75de6ecd1002abb6cc91fe5d0ec6e3a71c48c515

It's quite interesting as it introduces planar decimation and mesh fairness computation. Any chance if it will make it into the main repository?

regards,
donlk

**Comment by cdcseacave** [comment]
I worked on this a long time ago. As far as I remember it worked well. If it is of interest I can look back for the final version and merge it.

**Comment by donlk** [comment]
Thanks you, i'd really appreciate that. I'm just very keen on any new options that would help in mesh post-processing.
