### ISSUE TITLE
What versions of PNG/JPEG/TIFF libraries are required for OpenMVS to compile/run?

### ISSUE THREAD

**Issue by zharvey-welltok** [cdcseacave/openMVS#130]
### Specifications like the version of the project, operating system, and hardware
* Using `master` branch
* CentOS 7
* VirtualBox/Vagrant running on MacBook Pro

### Steps to reproduce the problem
From several other issues I've reported recently (like [this one](https://github.com/cdcseacave/openMVS/issues/128) or [this one](https://github.com/cdcseacave/openMVS/issues/126)) it has been pointed out to me multiple times that, in order for OpenMVS to compile and/or run correctly, you need to make sure that the version of PNG, JPG and TIFF libraries used on your system are the same as the ones used by OpenCV.

However, when I run `yum deplist libopencv-dev`, which lists all the dependencies of OpenCV, I don't see PNG/JPG/TIFF libraries (`libpng-dev`, `libjpeg-dev` and `libtiff-dev` respectively) listed as dependencies. In fact I see that OpenCV has **no** dependencies.

Can someone explain to me how this is possible? How can these libraries (PNG/JPG/TIFF, etc.) be the culprits of these compile/runtime problems if OpenCV doesn't use them or depend on them?

**Comment by zharvey-welltok** [comment]
Why was this closed without yielding an answer? Its a valid question! If you have a mailing list, email or some other format (IRC, whatever) where you'd like questions posted, please let me know and I'll direct this question there.

But if GitHub issues are the *only* place where questions like this can be asked, I would really appreciate an answer and some help here...

**Comment by FlachyJoe** [comment]
Hi zharvey-welltok,
libopencv-dev depends of something which depends of libjeg and so.
Here is the full *-dev dependencies of the debian package:
```
  libatk1.0-dev libavcodec-dev libavformat-dev libavutil-dev libcairo2-dev
  libcv-dev libcvaux-dev libdc1394-22-dev libexpat1-dev libfontconfig1-dev
  libfreetype6-dev libgdk-pixbuf2.0-dev libglib2.0-dev libgraphite2-dev
  libgtk2.0-dev libharfbuzz-dev libhighgui-dev libice-dev libicu-dev
  libilmbase-dev libjbig-dev libjpeg-dev libjpeg62-turbo-dev liblzma-dev
  libopencv-calib3d-dev libopencv-contrib-dev libopencv-core-dev
  libopencv-features2d-dev libopencv-flann-dev libopencv-gpu-dev
  libopencv-highgui-dev libopencv-imgproc-dev libopencv-legacy-dev
  libopencv-ml-dev libopencv-objdetect-dev libopencv-ocl-dev
  libopencv-photo-dev libopencv-stitching-dev libopencv-superres-dev
  libopencv-ts-dev libopencv-video-dev libopencv-videostab-dev libopenexr-dev
  libpango1.0-dev libpcre3-dev libpixman-1-dev libpng-dev
  libpthread-stubs0-dev libraw1394-dev libsm-dev libswresample-dev
  libswscale-dev libtiff5-dev libx11-dev libxau-dev libxcb-render0-dev
  libxcb-shm0-dev libxcb1-dev libxcomposite-dev libxcursor-dev libxdamage-dev
  libxdmcp-dev libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev
  libxrandr-dev libxrender-dev x11proto-composite-dev x11proto-core-dev
  x11proto-damage-dev x11proto-fixes-dev x11proto-input-dev x11proto-kb-dev
  x11proto-randr-dev x11proto-render-dev x11proto-xext-dev
  x11proto-xinerama-dev xtrans-dev zlib1g-dev
```

It seems cdcseacave doesn't like opened issue ;-)

**Comment by zharvey-welltok** [comment]
Thanks @FlachyJoe 👍 

So it sounds like there is a difference in the dependency graph between debian and rpm packages?

On CentOS 7 I ran `yum deplist libopencv-dev` and did not see anything listed as a dependency. I assume you are on Ubuntu or something Debian-esque? If so what command did you run to get the output? I have access to an Ubuntu 16.04 machine as well, if you don't mind, I'd like to run the same command on my machine to see what it outputs...

Thanks again!!!

**Comment by zharvey-welltok** [comment]
Figured it out, solution is to use MVE instead of OpenMVS.

**Comment by FlachyJoe** [comment]
@zharvey-welltok 
To got this list I've removed all "-dev" packages and run `apt-get install libopencv-dev` on Debian Sid.
