### ISSUE TITLE
Is use with a fully calibrated camera array supported?

### ISSUE THREAD

**Issue by drewm1980** [cdcseacave/openMVS#131]
Does openMVS support the use case where your cameras are all rigidly mounted and fully calibrated for intrinsics and extrinsics? 

"DensifyPointCloud" implies that you actually need a point cloud to start with.

If openMVS is tightly tied to increasingly complex MVG output, that will prevent it's use in some industrial applications that want to skip that stage entirely for speed and reliability.

**Comment by cdcseacave** [comment]
OpenMVS is not tide to any SfM solutions, and can be used completely stand alone simply by supplying the input data needed using the Interface.h (please read the wiki for more).
