### ISSUE TITLE
Is use with a fully calibrated camera array supported?

### ISSUE THREAD

**Issue by drewm1980** [cdcseacave/openMVS#132]
Does openMVS support the use case where your cameras are all rigidly mounted and fully calibrated for intrinsics and extrinsics, like PMVS2? Or are you going to have a bad time if you try running it outside of the full pipeline?  "DensifyPointCloud" implies that you actually need a point cloud to start with, which you don't have if you just dropped a new object into the middle of your awesome array of inward facing cameras.

PMVS2 is the best I've used so far, but I'm shopping around for something that works faster for quick and dirty point clouds. We can afford to throw enough hardware at the problem to make our 100 ms timing constraint, but I would prefer something more elegant.

**Comment by cdcseacave** [comment]
You can play with the parameters to DensifyPointCloud to adjust for speed in trade of accuracy. You can easily increase the speed 4times compared to default params.

**Comment by cdcseacave** [comment]
I realise I didn't answer the main question: so yes, OpenMVS format already supports platforms with multiple cameras (non-central cameras), please have a look at Interface.h

**Comment by drewm1980** [comment]
Thanks for the response! I looked at Interface.h; judging from the API, you need to seed OpenVMS with a reasonable sparse depth map, which means it's not a stand-alone tool for the PMVS use-case (calibrated images -> point cloud).  The code looks nice and clean, though!

**Comment by drewm1980** [comment]
I looked into the code just to make sure there wasn't un-document support for the seed-free use case; looks like no:

```
	if (scene.pointcloud.IsEmpty()) {
		VERBOSE("error: empty initial point-cloud");
		return EXIT_FAILURE;
	}

```
