### ISSUE TITLE
openMVS DensifyPointCloud error (error: preparing images for dense reconstruction failed)

### ISSUE THREAD

**Issue by deusclovis** [cdcseacave/openMVS#133]
When I try to run DensifyPointCloud on the mvs file produced using openMVG_main_openMVG2openMVS, I get these errors:-

11:11:50 [App     ] Build date: Oct  9 2016, 09:38:50
11:11:50 [App     ] CPU: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
11:11:50 [App     ] RAM: 14.69GB Physical Memory 0B Virtual Memory
11:11:50 [App     ] OS: Linux 4.4.0-36-generic (x86_64)
11:11:50 [App     ] SSE & AVX compatible CPU & OS detected
11:11:50 [App     ] Command line: -i /home/ubuntu/openMVG_Build/pineapple_out/pineapple.mvs -o /home/ubuntu/openMVG_Build/pineapple_out/pineapple_dense.mvs
11:11:50 [App     ] Camera model loaded: platform 0; camera  0; f 3459.090x3459.090; poses 0
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4037.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4038.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4039.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4040.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4041.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4042.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4043.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4044.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4045.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4046.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4047.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4048.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4049.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4050.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4051.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4052.jpg'
11:11:50 [App     ] warning: uncalibrated image 'undistorted_images//IMG_4053.jpg'
11:11:50 [App     ] Scene loaded from interface format (45ms):
    17 images (0 calibrated) with a total of 0.00 MPixels (-nan MPixels/image)
    9851 points, 0 vertices, 0 faces
11:11:50 [App     ] error: preparing images for dense reconstruction failed (errors loading images)

Why is it having problems loading the images? Does the mvs file have to be in a particular location?

**Comment by cdcseacave** [comment]
it seems like the MVS project is not valid (0 poses), pls make sure the SFM reconstruction is ok, and that the conversion is done right

**Comment by deusclovis** [comment]
Hi, thanks so much for such a swift response :D

This is the SfM reconstruction output after running the python script :- 

Structure estimation took (s): 3.83.
#landmark found: 6811
...Generating SfM_Report.html
Found a sfm_data scene with:
 #views: 17
 #poses: 17
 #intrinsics: 1
 #tracks: 6811

So it seems that it was reconstructed properly ...

But.. when I convert to mvs using openMVG_main_openMVG2openMVS, I get this:-

error: no image using camera 0 of platform 0
Scene saved to OpenMVS interface format:
	17 images (0 calibrated)
	9692 Landmarks

I guess that's what you meant.
Might you know why is this? What could be wrong?

**Comment by cdcseacave** [comment]
seems like you are not running well openMVG_main_openMVG2openMVS; but since you are using the python [script](https://github.com/cdcseacave/openMVS_sample/blob/master/MvgMvs_Pipeline.py), please use it till the end. Why stop at openMVG?

**Comment by deusclovis** [comment]
Yes I have tried that too, but I got this error:--

# Using input dir  :  /home/ubuntu/openMVG_Build/pineapple
#       output_dir :  /home/ubuntu/pineapple_final
# First step  :  0
# Last step :  11
#0. Intrinsics analysis
Traceback (most recent call last):
  File "MvgMvs_Pipeline.py", line 236, in <module>
    pStep = subprocess.Popen(cmdline)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

----
I am still not able to get this to work..

**Comment by cdcseacave** [comment]
you have to edit the script (the top of the file) and correctly set the paths to the binaries, etc

**Comment by deusclovis** [comment]
Thanks! Yes the script works now. Overlooked that. But I still cannot convert to the mvs file using openMVG_main_openMVG2openMVS successfully, even though I probably don't have to do that now..

**Comment by pmoulon** [comment]
@deusclovis this binary openMVG2openMVS allow to convert a OpenMVG scee to an OpenMVS scene.

**Comment by deusclovis** [comment]
Hi, thanks for the reply. yes I know that, but when I tried to convert the OpenMVG scene (sfm_data.bin file) to an OpenMVS  scene using openMVG_main_openMVG2openMVS, I got this:-

error: no image using camera 0 of platform 0
Scene saved to OpenMVS interface format:
17 images (0 calibrated)
9692 Landmarks

===

But the SfM reconstruction was valid:-

Structure estimation took (s): 3.83.
#landmark found: 6811
...Generating SfM_Report.html
Found a sfm_data scene with:
#views: 17
#poses: 17
#intrinsics: 1
#tracks: 6811

**Comment by deusclovis** [comment]
And just a follow up on the MvgMvs_Pipeline.py script.

It works, but somehow it stops at the densification and does not follow through to the end of the pipeline .. 

The logs for ReconstructMesh, RefineMesh and TextureMesh are produced but they are empty...

I tried to run the OpenMVS binary ReconstructMesh manually, but it says segmentation fault:-

02:34:25 [App     ] Build date: Oct  9 2016, 09:38:50
02:34:25 [App     ] CPU: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
02:34:25 [App     ] RAM: 14.69GB Physical Memory 0B Virtual Memory
02:34:25 [App     ] OS: Linux 4.4.0-38-generic (x86_64)
02:34:25 [App     ] SSE & AVX compatible CPU & OS detected
02:34:25 [App     ] Command line: /home/ubuntu/pineapple_final/mvs/scene_dense.mvs
02:34:31 [App     ] Scene loaded (5s865ms):
	17 images (17 calibrated) with a total of 49.42 MPixels (2.91 MPixels/image)
	4138675 points, 0 vertices, 0 faces
Segmentation fault (core dumped)

Might anyone know what is the issue here?

**Comment by pmoulon** [comment]
Please share your sfm_data.bin file

**Comment by deusclovis** [comment]
I tried ./ReconstructMesh /root/pineapple_out/mvs/scene_dense.mvs but i am still getting this:-

08:50:49 [App     ] Build date: Oct  8 2016, 11:06:01
08:50:49 [App     ] CPU: Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
08:50:49 [App     ] RAM: 7.80GB Physical Memory 2.00GB Virtual Memory
08:50:49 [App     ] OS: Linux 4.4.0-38-generic (x86_64)
08:50:49 [App     ] SSE & AVX compatible CPU & OS detected
08:50:49 [App     ] Command line: /root/pineapple_out/mvs/scene_dense.mvs
08:50:58 [App     ] Scene loaded (9s766ms):
	17 images (17 calibrated) with a total of 49.42 MPixels (2.91 MPixels/image)
	4295064 points, 0 vertices, 0 faces
Segmentation fault (core dumped)

I have included the sfm_data.bin in https://github.com/deusclovis/pineapple-reconstruction-openmvg

----------------------------------
What could be the reason the mesh reconstruction is failing?

**Comment by deusclovis** [comment]
I tried with a server with more CPU and Ram but I get the same:-

09:29:14 [App     ] Build date: Oct  8 2016, 11:06:01
09:29:14 [App     ] CPU: Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz
09:29:14 [App     ] RAM: 15.67GB Physical Memory 2.00GB Virtual Memory
09:29:14 [App     ] OS: Linux 4.4.0-38-generic (x86_64)
09:29:14 [App     ] SSE & AVX compatible CPU & OS detected
09:29:14 [App     ] Command line: /root/pineapple_out/mvs/scene_dense.mvs
09:29:22 [App     ] Scene loaded (7s942ms):
	17 images (17 calibrated) with a total of 49.42 MPixels (2.91 MPixels/image)
	4295064 points, 0 vertices, 0 faces
Segmentation fault (core dumped)

**Comment by cdcseacave** [comment]
I'm afraid I do not have a solution for you and I can not reproduce it on my end. Please compile in debug mode and try to GDB the issue.

**Comment by vevi1982** [comment]
the error is u use sfm_data.json instead of sfm_data.bin to create openmvs scene.

**Comment by prakruti** [comment]
About this error 
error: no image using camera 0 of platform 0
I got this because I ran the first part of the pipeline (OpenMVG) in another location. Change the "root_path" in both sfm_data.json and sfm_data.bin (you can use openMVG_main_ConvertSfM_DataFormat to convert from .json to .bin and back) so that it points to the folder with the images.

**Comment by xqyd** [comment]
Simply remove the following lines from the CMakeLists.txt of OpenMVG
if (DEFINED OpenMVG_USE_INTERNAL_JPEG)
  message(STATUS "LIBJPEG (internal)")
else()
  message(STATUS "LIBJPEG (external)")
endif()

This will make the cmake to bypass the libjpeg and the jpeg stuff can be processed by OpenMVS like this:

CEREAL: (internal)
EIGEN: 3.3.4 (internal)
CERES: 1.13.0 (internal)
FLANN: 1.8.4 (internal)
LIBTIFF: 4.1.0 (external)
LIBPNG: 1.6.37 (external)
CLP: 1.16.10 (internal)
COINUTILS: 2.10.13 (internal)
OSI:  (internal)
LEMON: 1.3 (internal)

Notice the "LIBJPEG (external)" is GONE!
With this approach, I can finally use OpenMVG+OpenMVS without any problem.

**Comment by cdcseacave** [comment]
thx, assume this solved
