### ISSUE TITLE
DensifyPointCloud (ComputeCoveredArea Assertion `size > 0' failed)

### ISSUE THREAD

**Issue by hcjghr** [cdcseacave/openMVS#135]
Hi,

I'm having problems running DensifyPointCloud binary. I performed a reconstruction using **openMVG_main_IncrementalSfm** and got 627 out of 975 images successfully reconstructed. Then I ran the **openMVG_main_openMVG2openMVS** to export the scene and undistorted images (all 975 images are extracted and undistorted). 

Once I run DensifyPointCloud scene.mvs I get this output:

19:52:48 [App     ] Build date: Oct 11 2016, 19:26:50
19:52:48 [App     ] CPU: Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz
19:52:48 [App     ] RAM: 251.80GB Physical Memory 383.81GB Virtual Memory
19:52:49 [App     ] OS: Linux 4.4.0-38-generic (x86_64)
19:52:49 [App     ] SSE & AVX compatible CPU & OS detected
19:52:49 [App     ] Command line: openmvs/scene.mvs
19:52:49 [App     ] Camera model loaded: platform 0; camera  0; f 0.441x0.441; poses 126
19:52:49 [App     ] Camera model loaded: platform 1; camera  0; f 0.440x0.440; poses 150
19:52:49 [App     ] Camera model loaded: platform 2; camera  0; f 0.443x0.443; poses 127
19:52:49 [App     ] Camera model loaded: platform 3; camera  0; f 0.447x0.447; poses 195
19:52:49 [App     ] Camera model loaded: platform 4; camera  0; f 0.445x0.445; poses 29

then for each image that was among the reconstructed ones:
19:52:51 [App     ] Image loaded   3: frame00001_cam_5.jpg
and for the ones that were not:
19:52:49 [App     ] warning: uncalibrated image '/home/klemen/processing/Boreas/wd_2_3min_F4_A/openmvs/udist//frame00001_cam_4.jpg'

...

19:53:39 [App     ] Scene loaded from interface format (50s672ms):
    975 images (627 calibrated) with a total of 3279.01 MPixels (5.23 MPixels/image)
    88296 points, 0 vertices, 0 faces

(multiple similar matrices)
19:53:40 [App     ] K234 = 
  594.6767     0.0000   670.0012 
    0.0000   594.6767   521.2723 
    0.0000     0.0000     1.0000 

...

19:53:47 [App     ] Preparing images for dense reconstruction completed: 975 images (7s680ms)
DensifyPointCloud: /home/klemen/workspace/openMVS/codes/openMVS_masterr/libs/MVS/../Common/Util.inl:824: TYPE SEACAVE::ComputeCoveredArea(const TYPE_, std::size_t, const TYPE_, int) [with TYPE = float; int n = 2; int s = 16; bool bCentered = false; std::size_t = long unsigned int]: Assertion `size > 0' failed.
Aborted (core dumped)

Does anybody have any idea what could be the problem? I hope I gave all the necessary information, if not, please let me know and I will provide whatever you might find useful.

thanks,
Klemen

**Comment by cdcseacave** [comment]
Please compile OpenMVS in release mode as that is just an ASSERT not correctly set trigered only in Debug mode.

**Comment by hcjghr** [comment]
Perfect...it solved it!!

Thanks for such a quick answer!
