### ISSUE TITLE
1 small issue

### ISSUE THREAD

**Issue by francoflamigni** [cdcseacave/openMVS#136]
I compile openMVS using visual studio 2015.

When creating image ortho projection, in the class "TRasterMesh", method "project" (file mesh.h),  you calculate the normal  vector to the facet plane. Depending on the coordinate values this could be very small (1.e-9) and the subsequent check 
static_cast<DERIVED*>(this)->CheckNormal(faceCenter)
fails producing an image with black holes (sometimes very large)
I substitute the normalPlane vector with its versor and the black hole disappear

**Comment by cdcseacave** [comment]
Indeed, vectors with small norms can be problematic, and even though the solution you presented might work in your case, it will not work in general. Please fix it instead by comparing against 0 and not ZEROTOLERANCE<REAL>()
