### ISSUE TITLE
DenseReconstruction() returns false on example dataset

### ISSUE THREAD

**Issue by refaelw** [cdcseacave/openMVS#137]
### Specifications like the version of the project, operating system, and hardware

Using Ubuntu 16.04 and using the provided bash script to build openMVS. Then used the provided MvgMvs_Pipeline.py script on the provided SceauxCastle dataset. 

The problem is the Densify point cloud is failing, however when the verbose output is used the individual dense .ply files exist, I'm managed to track it down to line 1629 in SceneDensify.cpp is true therefore the function is returning false and stopping the dense reconstruction. 
https://github.com/cdcseacave/openMVS/blob/master/libs/MVS/SceneDensify.cpp#L1629

Any idea why this would be the case? Do you need any log files or any more information?

**Comment by cdcseacave** [comment]
If it exits there, that means either there was an error during the computation of one depth-map, or there is a bug in the multithreading framework. What is the type of the event still in the queue at that point?
