### ISSUE TITLE
Convert .ply file to .mvs file

### ISSUE THREAD

**Issue by ADDDDD** [cdcseacave/openMVS#138]
There is a mesh file(it's a ply file, not generated from those apps in openmvs)，and I want to use the TextureMesh.exe to do the mesh texturing. So, I need to convert this ply file to a mvs file .

Is there any way to do this?

Thanks for your work!

**Comment by cdcseacave** [comment]
No, there is not, you need more data for that, like camera positions.

**Comment by genjiezio** [comment]
> No, there is not, you need more data for that, like camera positions.

Excuse me，if I have the camera positions data and .ply point clouds data，is it possible to build a .mvs manually？ So could you please tell me the data format of .mvs，such as where is the camera positions data stored and where is the point clouds data stored？

**Comment by cdcseacave** [comment]
no, still cant, you need also visibility info per each point (what images are seeing the point)
once you have the data, use `Interface.h` file; pls see the wiki for more info
