### ISSUE TITLE
Cant't build openMVS

### ISSUE THREAD

**Issue by thankjura** [cdcseacave/openMVS#139]
### Specifications like the version of the project, operating system, and hardware
gentoo amd64
### Steps to reproduce the problem
can't build openMVS, see log
cuda-8.0.44

[build.zip](https://github.com/cdcseacave/openMVS/files/576312/build.zip)

**Comment by cdcseacave** [comment]
You are the first to try compiling on gentoo as far as I know, so I am not surprise if the compilation is not smooth. There are two ways to do this: 1) either find a way to make cuda work on you system, or 2) disable it using -DOpenMVS_USE_CUDA=OFF

**Comment by thankjura** [comment]
-DOpenMVS_USE_CUDA=OFF - compile fine

Cuda work in blender (cycles) (render and vieport)

**Comment by cdcseacave** [comment]
I am sure CUDA work, I ment to make it compile with CUDA.
