### ISSUE TITLE
Interface.h is not self-contained

### ISSUE THREAD

**Issue by kyle-mp** [cdcseacave/openMVS#14]
I was following the documentation and trying to serialize an Interface object using Interface.h.    The trouble is, boost can't serialize it because cv::Matx is not serializable.  Not a big deal--I hacked around it by copy the lines related to serializing OpenCV objects from Common/Types.inl--but it could be helpful for other users if Interface.h was really self-contained so it could be used in other projects.  Or alternatively, update the documentation to mention serialization of OpenCV objects.

**Comment by cdcseacave** [comment]
You are right, Interface.h should be self contained. That was the intention, but due to lack of testing, it is not. I will fix it and push it soon.
