### ISSUE TITLE
Is TextureMesh a simplified version of the original alogirthm?

### ISSUE THREAD

**Issue by PacificDou** [cdcseacave/openMVS#140]
### Specifications like the version of the project, operating system, and hardware
version: commit 8cbeda19ad7c240723fd7583e34691f77fd0e80e
OS: Ubuntu 14.04.5 LTS

### Steps to reproduce the problem
According to this page https://github.com/cdcseacave/openMVS/wiki/Modules
The tool "TextureMesh" seems an implementation of the cited paper.
However, after checking the code carefully (especially function ListCameraFaces in libs/MVS/SceneTexture.cpp), I found that:
for the data term, it seems ONLY the image gradient magnitude and photo-consistency checking (or FaceOutlierDetection as named in SceneTexture.cpp) are included?!

This is different from the algorithm described in the paper. Because another important factor, the projection areas of faces are NOT included.

There dose exists a variable named "areas" (Line 583 in SceneTexture.cpp), but I cannot find anywhere it has been assigned as the projection areas.
On Line 598, the "area" (element of "areas") is increased by 1.

Could you kindly explain the differences between the method used in TextureMesh and the method described in their original work?

Thank you very much!

**Comment by cdcseacave** [comment]
Indeed, there several differences, and for this particular part of the algorithm, the difference is that I do compute the area of the face projection in a discrete manner, by projecting the entire mesh to the image and counting the pixels covered by a face. In my opinion this has many advantages over the original paper, but also one drawback: if the mesh resolution is too high and some faces cover less than one pixel in the images, they will be labeled as invisible. However, the reconstruction done through OpenMVS ensures that the mesh is only as detailed as there is data to justify it, and this will never happen, especially after RefineMesh module.

**Comment by PacificDou** [comment]
Thank you for your quick reply!
So, the variable "areas" should contain the number of pixels inside the projected area.
Could tell me where did you add this factor to the data term?

I think the data term cost is faceData.quality, is it right? But I can only find that the "quality" is assigned or added by the image gradient.

Thank you!

**Comment by cdcseacave** [comment]
I don't understand your question. That is how the area is computed, by addition.
