### ISSUE TITLE
cmake can not find breakpad

### ISSUE THREAD

**Issue by bkyifanleo** [cdcseacave/openMVS#141]
my program core dump when run refinemesh
i install breakpad to find the reason (/usr/local/include/breakpad)
but when i run cmake ..  it turns out can not find BreakPad.
so plz tell me how to fix it thx~

**Comment by cdcseacave** [comment]
it should work, so no idea why it not works in your case
however, in your case installing using breakpad makes no sens; breakpad goal is to help debugging release code distribute out to the world which does not have the source code
you have the source code, so just do a normal debug, either compile in debug or relwithdebinfo and run gdb

**Comment by bkyifanleo** [comment]
en.. i see thanks
