### ISSUE TITLE
openMVS build problem

### ISSUE THREAD

**Issue by jagadish482** [cdcseacave/openMVS#142]
>cmake D:\jagadish_gitHub\openMVS\src -DCMAKE_BUILD_TYPE=RELEASE -DEIGEN_DIR="D:\jagadish_gitHub\openMVS\eigen-eigen-b9cd8366d4e8" -DOPENCV_DIR="D:\jagadish_gitHub\openMVS\OpenCV" -DCERES_DIR="D:\jagadish_gitHub\openMVS\ceres-solver" -DCGAL_DIR="D:\jagadish_gitHub\openMVS\CGAL-4.9" -DVCG_DIR="D:\jagadish_gitHub\openMVS\vcglib" -DBOOST_INCLUDEDIR="D:\jagadish_gitHub\openMVS\boost_1_62_0"  -DOpenCV_CAN_BREAK_BINARY_COMPATIBILITY=OFF

i run openMVS by above commmand in cmd.exe. it's not configured ..it's showing below errors.

![build_problem1](https://cloud.githubusercontent.com/assets/23214629/20306598/1b2a848c-ab61-11e6-8f65-19dbd2db5e5b.PNG)

**Comment by jagadish482** [comment]
I am trying build openMVS using cmake-gui. Below i am showing i was done.
![build_problem2](https://cloud.githubusercontent.com/assets/23214629/20307057/a8f31dae-ab63-11e6-964b-0a4d4b1b9d02.PNG)

but i got errors i am copying my log files also below
# LOG # INFO

cotire 1.7.8 loaded.
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.7/Modules/FindOpenMP.cmake:179 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindOpenMP.cmake:224 (_OPENMP_GET_SPEC_DATE)
  CMakeLists.txt:58 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.7/Modules/FindOpenMP.cmake:179 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindOpenMP.cmake:266 (_OPENMP_GET_SPEC_DATE)
  CMakeLists.txt:58 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CUDA_TOOLKIT_ROOT_DIR not found or specified
Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Can't find CUDA. Continuing without it.
WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1793 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.62.0

  Boost include path: D:/jagadish_gitHub/openMVS/boost_1_62_0

  Could not find the following Boost libraries:

          boost_iostreams
          boost_program_options
          boost_system
          boost_serialization

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:91 (FIND_PACKAGE)


Eigen 3.2.10 found (include: D:/jagadish_gitHub/openMVS/eigen-eigen-b9cd8366d4e8)
OpenCV ARCH: x86
OpenCV RUNTIME: vc14
OpenCV STATIC: ON
CMake Warning at D:/jagadish_gitHub/opencv/build/OpenCVConfig.cmake:163 (message):
  Found OpenCV Windows Pack but it has not binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:106 (FIND_PACKAGE)


OpenCV 2.4.13 found (include: )
CMake Error at build/Utils.cmake:216 (message):
  CGAL required, but not found: Please specify CGAL directory using CGAL_ROOT
  env.  variable
Call Stack (most recent call first):
  build/Modules/FindCGAL.cmake:77 (package_report_not_found)
  libs/MVS/CMakeLists.txt:2 (FIND_PACKAGE)


Configuring incomplete, errors occurred!
See also "D:/jagadish_gitHub/openMVS_build/build6/CMakeFiles/CMakeOutput.log".

**Comment by jagadish482** [comment]
one more thing for boost library  does not have any CMakeLists.txt file. can we provide any link to get this library that must have CMakeLists.txt file

**Comment by ShikiGami** [comment]
I'm having the same problem, specially with Boost. It says it doesn't found some of the libraries, which makes no sense.

**Comment by cdcseacave** [comment]
@jagadish482 CMakeLists.txt is not always needed by CMake, depends how the Find functionality is implemented

@ShikiGami make sure you set the right flags; for instance if boost was compiled as static lib, you need to set -DBoost_USE_STATIC_LIBS=ON when configuring openmvs

**Comment by RemoteSensingFrank** [comment]
I installed all lib by using : _

> vcpkg install zlib boost eigen3 ceres opencv cgal glew glfw3

and then I compile the code with cmake it show the error:

>   CGAL required, but not found: Please specify CGAL directory using CGAL_ROOT env.  variable
But the CGAL was installed when I use vcpkg sreach cgal, could you plz tell me how to solve this?

**Comment by cdcseacave** [comment]
if u followed the steps I listed in build wiki, then there must be some particular setup you have that creates problems to FindCGAL.cmake module in OpenMVS; pls adjust it in order to find the vcpkg CGAL and post the finding

**Comment by wujun007** [comment]
Compiled openMVS project, I generated in VS error, prompting C++ does not support int type, how to solve it?
