### ISSUE TITLE
DensifyPointCloud error on Assertion

### ISSUE THREAD

**Issue by jagadish482** [cdcseacave/openMVS#145]
i am running DensifyPointCloud on openMVG_main_openMVG2openMVS results but i am getting below error
sample_output pdu$ /Users/pdu/Documents/jagadish_github/openMVS_build5/bin/Debug/DensifyPointCloud /Users/pdu/Documents/jagadish_github/sample_output/scene.mvs
13:04:34 [App     ] Build date: Nov 24 2016, 10:18:58
13:04:34 [App     ] CPU: Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
13:04:34 [App     ] RAM: 8.00GB Physical Memory 8.00GB Virtual Memory
13:04:34 [App     ] OS: Darwin 14.5.0 (x86_64)
13:04:34 [App     ] SSE & AVX compatible CPU & OS detected
13:04:34 [App     ] Command line: /Users/pdu/Documents/jagadish_github/sample_output/scene.mvs
13:04:34 [App     ] Camera model loaded: platform 0; camera  0; f 1.057x1.057; poses 10
13:04:34 [App     ] Image loaded   0: 100_7100.JPG
13:04:34 [App     ] Image loaded   1: 100_7101.JPG
13:04:34 [App     ] Image loaded   2: 100_7102.JPG
13:04:34 [App     ] Image loaded   3: 100_7103.JPG
13:04:34 [App     ] Image loaded   4: 100_7104.JPG
13:04:34 [App     ] Image loaded   5: 100_7105.JPG
13:04:34 [App     ] Image loaded   6: 100_7106.JPG
13:04:34 [App     ] Image loaded   7: 100_7107.JPG
13:04:34 [App     ] Image loaded   8: 100_7108.JPG
13:04:34 [App     ] Image loaded   9: 100_7109.JPG
13:04:34 [App     ] warning: uncalibrated image 'undistorted_images//100_7110.JPG'
13:04:34 [App     ] Scene loaded from interface format (40ms):
	11 images (10 calibrated) with a total of 57.47 MPixels (5.75 MPixels/image)
	6074 points, 0 vertices, 0 faces
13:04:34 [App     ] K0 = 
 1496.4065     0.0000   731.1147 
    0.0000  1496.4065   560.1893 
    0.0000     0.0000     1.0000 

13:04:35 [App     ] K1 = 
 1496.4065     0.0000   731.1147 
    0.0000  1496.4065   560.1893 
    0.0000     0.0000     1.0000 

13:04:35 [App     ] K2 = 
 1496.4065     0.0000   731.1147 
    0.0000  1496.4065   560.1893 
    0.0000     0.0000     1.0000 

13:04:35 [App     ] K3 = 
 1496.4065     0.0000   731.1147 
    0.0000  1496.4065   560.1893 
    0.0000     0.0000     1.0000 

13:04:35 [App     ] K4 = 
 1496.4065     0.0000   731.1147 
    0.0000  1496.4065   560.1893 
    0.0000     0.0000     1.0000 

13:04:35 [App     ] K5 = 
 1496.4065     0.0000   731.1147 
    0.0000  1496.4065   560.1893 
    0.0000     0.0000     1.0000 

13:04:35 [App     ] K6 = 
 1496.4065     0.0000   731.1147 
    0.0000  1496.4065   560.1893 
    0.0000     0.0000     1.0000 

13:04:35 [App     ] K7 = 
 1496.4065     0.0000   731.1147 
    0.0000  1496.4065   560.1893 
    0.0000     0.0000     1.0000 

13:04:35 [App     ] K8 = 
 1496.4065     0.0000   731.1147 
    0.0000  1496.4065   560.1893 
    0.0000     0.0000     1.0000 

13:04:35 [App     ] K9 = 
 1496.4065     0.0000   731.1147 
    0.0000  1496.4065   560.1893 
    0.0000     0.0000     1.0000 

13:04:35 [App     ] Preparing images for dense reconstruction completed: 11 images (1s159ms)
13:04:35 [App     ] Reference image   0 sees 9 views:   1(1420pts,1.06scl)   2(934pts,1.11scl)   3(753pts,1.11scl)   4(663pts,1.15scl)   5(443pts,1.16scl)   6(385pts,1.12scl)   7(362pts,1.04scl)   8(244pts,0.95scl)   9(36pts,0.80scl) (1704 shared points)
13:04:36 [App     ] Reference image   1 sees 9 views:   3(1396pts,1.04scl)   0(1420pts,0.94scl)   4(1099pts,1.07scl)   2(1782pts,1.04scl)   5(733pts,1.08scl)   6(643pts,1.05scl)   7(578pts,0.97scl)   8(379pts,0.89scl)   9(56pts,0.78scl) (2804 shared points)
13:04:36 [App     ] Reference image   2 sees 9 views:   4(1171pts,1.02scl)   1(1782pts,0.96scl)   0(934pts,0.91scl)   5(794pts,1.03scl)   6(698pts,1.00scl)   7(652pts,0.92scl)   3(1759pts,1.00scl)   8(431pts,0.85scl)   9(59pts,0.74scl) (2692 shared points)
13:04:36 [App     ] Reference image   3 sees 9 views:   1(1396pts,0.96scl)   5(945pts,1.02scl)   6(742pts,0.99scl)   4(1441pts,1.02scl)   0(753pts,0.91scl)   7(670pts,0.92scl)   2(1759pts,1.00scl)   8(461pts,0.84scl)   9(66pts,0.75scl) (2498 shared points)
13:04:36 [App     ] Reference image   4 sees 9 views:   1(1099pts,0.94scl)   2(1171pts,0.98scl)   6(1011pts,0.97scl)   7(937pts,0.90scl)   3(1441pts,0.99scl)   5(1283pts,1.00scl)   0(663pts,0.89scl)   8(642pts,0.82scl)   9(84pts,0.74scl) (2383 shared points)
13:04:36 [App     ] Reference image   5 sees 9 views:   3(945pts,0.98scl)   7(958pts,0.90scl)   2(794pts,0.98scl)   1(733pts,0.94scl)   4(1283pts,1.00scl)   6(1201pts,0.97scl)   8(625pts,0.82scl)   0(443pts,0.88scl)   9(97pts,0.75scl) (1938 shared points)
13:04:36 [App     ] Reference image   6 sees 9 views:   4(1011pts,1.03scl)   3(742pts,1.01scl)   2(698pts,1.01scl)   8(826pts,0.85scl)   1(643pts,0.97scl)   5(1201pts,1.03scl)   7(1227pts,0.92scl)   0(385pts,0.92scl)   9(118pts,0.78scl) (1926 shared points)
13:04:36 [App     ] Reference image   7 sees 9 views:   5(958pts,1.12scl)   4(937pts,1.13scl)   8(1219pts,0.92scl)   3(670pts,1.11scl)   2(652pts,1.11scl)   6(1227pts,1.08scl)   1(578pts,1.07scl)   0(362pts,1.01scl)   9(203pts,0.85scl) (2128 shared points)
13:04:36 [App     ] Reference image   8 sees 9 views:   6(826pts,1.19scl)   7(1219pts,1.08scl)   5(625pts,1.23scl)   4(642pts,1.24scl)   3(461pts,1.23scl)   2(431pts,1.22scl)   1(379pts,1.18scl)   0(244pts,1.12scl)   9(144pts,0.92scl) (1420 shared points)
13:04:36 [App     ] Reference image   9 sees 9 views:   7(203pts,1.19scl)   6(118pts,1.31scl)   5(97pts,1.37scl)   8(144pts,1.09scl)   4(84pts,1.40scl)   3(66pts,1.41scl)   1(56pts,1.37scl)   2(59pts,1.44scl)   0(36pts,1.37scl) (204 shared points)
13:04:36 [App     ] Selecting images for dense reconstruction completed: 10 images (223ms)
Assertion failed: (z > 0), function operator(), file /Users/pdu/Documents/jagadish_github/openMVS/libs/MVS/SceneDensify.cpp, line 524.
Abort trap: 6

please help me to solve this

**Comment by cdcseacave** [comment]
Please compile in Release mode

**Comment by jagadish482** [comment]
thank you for reply. yeah it is working in release mode.

why it is giving error in debug can you explain me?

**Comment by Harry-Yagami** [comment]
How to compile in release mode .I only see Debug folder under the path openMVS\build\bin\x64\
@jagadish482 @cdcseacave

**Comment by Harry-Yagami** [comment]
Yea can you elaborate on why it is giving error in Debug mode @cdcseacave
