### ISSUE TITLE
Can function TextureMesh support other data format?

### ISSUE THREAD

**Issue by BrightWHU** [cdcseacave/openMVS#146]
### Specifications like the version of the project, operating system, and hardware
version:  cdcseacave v0.7++
OS: Windows

### Steps to reproduce the problem
There are other ways as well to obtain 3D models with registered cameras, for example with range scanning, etc. Can function TextureMesh handle data set organized in other manner (data set including 3D model, images and camera parameters )?

**Comment by cdcseacave** [comment]
Yes, make sure you represent the scene as a compatible OpenMVS project (as described in Interface.h) and any module should work fine. However, for the TextureMesh module to work, we'll need to extend Interface.h with mesh information. This is easy, thought if for some reason you can not do it yourself, please give me a good reason why to do it and I'll try to allocate some time for it.
