### ISSUE TITLE
Can not build openMVS on windows

### ISSUE THREAD

**Issue by Masahiro1002** [cdcseacave/openMVS#148]
Hi,

I try to build openMVS on windows, but a lot of errors occurred. 
I could not solve by myself.

CMake log:

cotire 1.7.8 loaded.
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.7/Modules/FindOpenMP.cmake:179 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindOpenMP.cmake:224 (_OPENMP_GET_SPEC_DATE)
  CMakeLists.txt:58 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.7/Modules/FindOpenMP.cmake:179 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindOpenMP.cmake:266 (_OPENMP_GET_SPEC_DATE)
  CMakeLists.txt:58 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CUDA_TOOLKIT_ROOT_DIR not found or specified
Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Can't find CUDA. Continuing without it.
WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
Boost version: 1.62.0
Found the following Boost libraries:
  iostreams
  program_options
  system
  serialization
  regex
Eigen 3.2.10 found (include: C:/Ceres/3rdparty/eigen-eigen-b9cd8366d4e8)
OpenCV ARCH: x64
OpenCV RUNTIME: vc14
OpenCV STATIC: ON
Found OpenCV 3.1.0 in C:/opencv310/build/install/x64/vc14/lib
You might need to add C:\opencv310\build\install\x64\vc14\bin to your PATH to be able to run your applications.
OpenCV 3.1.0 found (include: C:/opencv310/build/install/include;C:/opencv310/build/install/include/opencv)
CGAL 4.9 found (include: C:/dev/CGAL-4.9/build/include;C:/dev/CGAL-4.9/include)
VCG  found (include: C:/vcglib-1.0.0)
Found required Ceres dependency: Eigen version 3.2.10 in C:/Ceres/3rdparty/eigen-eigen-b9cd8366d4e8
Found required Ceres dependency: Glog in C:/Ceres/3rdparty/glog-0.3.3/src/windows
Found Ceres version: 1.11.0 installed in: C:/Ceres/3rdparty/ceres-solver-1.11.0/build/install
CERES 1.11.0 found (include: C:/Ceres/3rdparty/ceres-solver-1.11.0/build/install/include;C:/Ceres/3rdparty/eigen-eigen-b9cd8366d4e8;C:/Ceres/3rdparty/glog-0.3.3/src/windows;C:/Ceres/3rdparty/ceres-solver-1.11.0/build/install/include)
Configuring done

vs 2015:

1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
2>------ Skipped Build: Project: clean_cotire, Configuration: Release x64 ------
2>Project not selected to build for this solution configuration 
3>------ Skipped Build: Project: uninstall, Configuration: Release x64 ------
3>Project not selected to build for this solution configuration 
4>------ Build started: Project: MVS, Configuration: Release x64 ------
4>cl : Command line warning D9025: overriding '/Zm170' with '/Zm150'
4>cl : Command line warning D9002: ignoring unknown option '/arch:SSE3'
4>cl : Command line warning D9002: ignoring unknown option '/arch:SSE3'
4>  DepthMap.cpp
4>C:\dev\CGAL-4.9\include\CGAL/auto_link/auto_link.h(376): fatal error C1189: #error:  "Mixing a dll CGAL library with a static runtime is a really bad idea..."
4>  Mesh.cpp
4>C:\vcglib-1.0.0\vcg/complex/algorithms/smooth.h : warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss
4>C:\vcglib-1.0.0\vcg/complex/algorithms/local_optimization/tri_edge_collapse_quadric.h(81): warning C4138: '*/' found outside of comment
4>C:\dev\CGAL-4.9\include\CGAL/auto_link/auto_link.h(376): fatal error C1189: #error:  "Mixing a dll CGAL library with a static runtime is a really bad idea..."
4>  SceneDensify.cpp
4>C:\dev\CGAL-4.9\include\CGAL/auto_link/auto_link.h(376): fatal error C1189: #error:  "Mixing a dll CGAL library with a static runtime is a really bad idea..."
4>  SceneReconstruct.cpp
4>C:\dev\CGAL-4.9\include\CGAL/auto_link/auto_link.h(376): fatal error C1189: #error:  "Mixing a dll CGAL library with a static runtime is a really bad idea..."
5>------ Build started: Project: DensifyPointCloud, Configuration: Release x64 ------
6>------ Build started: Project: InterfaceVisualSFM, Configuration: Release x64 ------
7>------ Build started: Project: ReconstructMesh, Configuration: Release x64 ------
8>------ Build started: Project: RefineMesh, Configuration: Release x64 ------
9>------ Build started: Project: TextureMesh, Configuration: Release x64 ------
7>LINK : fatal error LNK1181: cannot open input file '..\..\lib\vc14\x64\Release\MVS.lib'
6>LINK : fatal error LNK1181: cannot open input file '..\..\lib\vc14\x64\Release\MVS.lib'
5>LINK : fatal error LNK1181: cannot open input file '..\..\lib\vc14\x64\Release\MVS.lib'
8>LINK : fatal error LNK1181: cannot open input file '..\..\lib\vc14\x64\Release\MVS.lib'
9>LINK : fatal error LNK1181: cannot open input file '..\..\lib\vc14\x64\Release\MVS.lib'
10>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
11>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
11>Project not selected to build for this solution configuration 
========== Build: 2 succeeded, 6 failed, 3 up-to-date, 3 skipped ==========

1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
2>------ Skipped Build: Project: clean_cotire, Configuration: Debug x64 ------
2>Project not selected to build for this solution configuration 
3>------ Skipped Build: Project: uninstall, Configuration: Debug x64 ------
3>Project not selected to build for this solution configuration 
4>------ Build started: Project: MVS, Configuration: Debug x64 ------
4>cl : Command line warning D9025: overriding '/Zm170' with '/Zm150'
4>cl : Command line warning D9002: ignoring unknown option '/arch:SSE3'
4>cl : Command line warning D9002: ignoring unknown option '/arch:SSE3'
4>  DepthMap.cpp
4>C:\dev\CGAL-4.9\include\CGAL/auto_link/auto_link.h(376): fatal error C1189: #error:  "Mixing a dll CGAL library with a static runtime is a really bad idea..."
4>  Mesh.cpp
4>C:\vcglib-1.0.0\vcg/complex/algorithms/smooth.h : warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss
4>C:\vcglib-1.0.0\vcg/complex/algorithms/local_optimization/tri_edge_collapse_quadric.h(81): warning C4138: '*/' found outside of comment
4>C:\dev\CGAL-4.9\include\CGAL/auto_link/auto_link.h(376): fatal error C1189: #error:  "Mixing a dll CGAL library with a static runtime is a really bad idea..."
4>  SceneDensify.cpp
4>C:\dev\CGAL-4.9\include\CGAL/auto_link/auto_link.h(376): fatal error C1189: #error:  "Mixing a dll CGAL library with a static runtime is a really bad idea..."
4>  SceneReconstruct.cpp
4>C:\dev\CGAL-4.9\include\CGAL/auto_link/auto_link.h(376): fatal error C1189: #error:  "Mixing a dll CGAL library with a static runtime is a really bad idea..."
4>  Generating Code...
5>------ Build started: Project: DensifyPointCloud, Configuration: Debug x64 ------
6>------ Build started: Project: InterfaceVisualSFM, Configuration: Debug x64 ------
7>------ Build started: Project: ReconstructMesh, Configuration: Debug x64 ------
8>------ Build started: Project: RefineMesh, Configuration: Debug x64 ------
9>------ Build started: Project: TextureMesh, Configuration: Debug x64 ------
5>LINK : fatal error LNK1104: cannot open file '..\..\lib\vc14\x64\Debug\MVS.lib'
6>LINK : fatal error LNK1104: cannot open file '..\..\lib\vc14\x64\Debug\MVS.lib'
7>LINK : fatal error LNK1104: cannot open file '..\..\lib\vc14\x64\Debug\MVS.lib'
8>LINK : fatal error LNK1104: cannot open file '..\..\lib\vc14\x64\Debug\MVS.lib'
9>LINK : fatal error LNK1104: cannot open file '..\..\lib\vc14\x64\Debug\MVS.lib'
10>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
11>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
11>Project not selected to build for this solution configuration 
========== Build: 2 succeeded, 6 failed, 3 up-to-date, 3 skipped ==========

Thanks in advance.

**Comment by cdcseacave** [comment]
Not sure what can I explain, the error message is really clear: `Mixing a dll CGAL library with a static runtime is a really bad idea...` Just compile CGAL as a static library too.

**Comment by vevi1982** [comment]
When Cmake set 
BUILD_STATIC_RUNTIME = OFF 
can resolve the problem of error"Mixing a dll CGAL library with a static runtime is a really bad idea..."

**Comment by lishanlei** [comment]
Hi, I noticed that you have find the Boost libraries, such as iostreams, program_options,  system, serialization, regex. But when I use the Cmake to build CGAL, My cmake can't show the information about the Boost libraries. I really need your help,thanks a lot!

**Comment by cdcseacave** [comment]
pls see how to build at https://github.com/cdcseacave/openMVS/wiki/Building
