### ISSUE TITLE
cmake openMVS

### ISSUE THREAD

**Issue by jingzibelieve** [cdcseacave/openMVS#149]
![image](https://cloud.githubusercontent.com/assets/15321725/20737042/566811ba-b6e5-11e6-8bdf-1c54cca80bfe.png)
![image](https://cloud.githubusercontent.com/assets/15321725/20737053/6c8e25c4-b6e5-11e6-91a5-9a0b7baf5a2d.png)
![image](https://cloud.githubusercontent.com/assets/15321725/20737073/818e6ab0-b6e5-11e6-805b-815b861bf84b.png)
 I don't know why there was such a mistake,I have installed all the libraries.

**Comment by pmoulon** [comment]
You must define many directories
BOOST_INCLUDEDIR
BOOST_LIBRARYDIR 
You have defined only one
https://cmake.org/cmake/help/v3.0/module/FindBoost.html

**Comment by jingzibelieve** [comment]
I have defined two,and I just cut one of them.

**Comment by pmoulon** [comment]
Take a look to the cmake report and the FindBoost.cmake file in order to understand what it going wrong.

**Comment by jingzibelieve** [comment]
![image](https://cloud.githubusercontent.com/assets/15321725/20738300/1a2bc518-b6ed-11e6-8a23-19b45f745e97.png)
![image](https://cloud.githubusercontent.com/assets/15321725/20738449/24b654a2-b6ee-11e6-8390-a3047360a890.png)

**Comment by cdcseacave** [comment]
@pmoulon thx for your help, the FindBoost links is listing all the tricks needed to make it work, and there seem to be a lot of them

Unfortunately I can't help more, if you setup all BOOST variables correctly and still not working, please contact boost forum, its use inside OpenMVS cmake seems correct.

**Comment by jingzibelieve** [comment]
I have solved the problem,OpenMVS can be compiled through. Thank you very much!!! @cdcseacave @pmoulon

**Comment by ZhaozhengPlus** [comment]
@jingzibelieve   I have met the same problem, can you tell me how to solve it?

**Comment by jingzibelieve** [comment]
when you cmake the source code,you need add  Entry "Boost_USE_STATIC_LIBS"

**Comment by lishanlei** [comment]
Hi, jingzibelieve! I have met the same problem and tried your method when building openMVS. But I still can't fix this issues. I need your help!
