### ISSUE TITLE
DensifyPointCloud.exe error 

### ISSUE THREAD

**Issue by jingzibelieve** [cdcseacave/openMVS#152]
![1](https://cloud.githubusercontent.com/assets/15321725/20825589/1f7d1328-b8a0-11e6-9aa8-a9dd6ba81999.png)
How to solve the problem?

**Comment by cdcseacave** [comment]
by giving more details

**Comment by jingzibelieve** [comment]
“DensifyPointCloud.exe”(Win32): 已加载“D:\openMVS\build\openMVS\bin\vc14\x64\Release\DensifyPointCloud.exe”。模块已生成，不包含符号。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\ntdll.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\kernel32.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\KernelBase.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\opencv_calib3d300.dll”。已加载符号。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\opencv_features2d300.dll”。已加载符号。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\opencv_flann300.dll”。已加载符号。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\opencv_core300.dll”。已加载符号。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\msvcp140.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-crt-runtime-l1-1-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\ucrtbase.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-core-timezone-l1-1-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-core-file-l2-1-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-core-localization-l1-2-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-core-synch-l1-2-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-core-processthreads-l1-1-1.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-core-file-l1-2-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-crt-string-l1-1-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-crt-heap-l1-1-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-crt-stdio-l1-1-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-crt-convert-l1-1-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-crt-locale-l1-1-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-crt-math-l1-1-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-crt-multibyte-l1-1-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-crt-time-l1-1-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-crt-filesystem-l1-1-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-crt-environment-l1-1-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\api-ms-win-crt-utility-l1-1-0.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\concrt140.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\opencv_imgproc300.dll”。已加载符号。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\opencv_imgcodecs300.dll”。已加载符号。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\user32.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\gdi32.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\lpk.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\usp10.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\msvcrt.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\vcomp140.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\imm32.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\msctf.dll”。无法查找或打开 PDB 文件。
“DensifyPointCloud.exe”(Win32): 已加载“C:\Windows\System32\apphelp.dll”。无法查找或打开 PDB 文件。
线程 0x171c 已退出，返回值为 0 (0x0)。
程序“[4664] DensifyPointCloud.exe”已退出，返回值为 3 (0x3)。

**Comment by cdcseacave** [comment]
I imagine you don't speak much English, but I'm afraid I don't speak much Chinese either... so this will not work
