### ISSUE TITLE
InterfaceOpenMVG.exe error

### ISSUE THREAD

**Issue by jingzibelieve** [cdcseacave/openMVS#153]
![image](https://cloud.githubusercontent.com/assets/15321725/20855525/e64dc810-b938-11e6-9866-31ab5ba1835f.png)
![image](https://cloud.githubusercontent.com/assets/15321725/20855539/ff264ce0-b938-11e6-94c0-101887640035.png)

**Comment by cdcseacave** [comment]
you built OpenMVS and OpenCV with different version of JPEG, make sure both libraries use the same JPEG version

**Comment by jingzibelieve** [comment]
ok,thanks!Do I have to re compile the source code again?

**Comment by jingzibelieve** [comment]
![image](https://cloud.githubusercontent.com/assets/15321725/20870481/d3b6e092-bac3-11e6-93fb-11949a7157dd.png)
I built OpenMVG and OpenCV with some version of JPEG.But I view the openMVS source code, it seems that there is no JPEG third party Library,how do I view the JPEG version of openMVS?

**Comment by cdcseacave** [comment]
There is no such thing as JPEG of openMVS. openMVS uses any JPEG library you installed on the system

**Comment by jingzibelieve** [comment]
I did not find any JPEG  library in the system
