### ISSUE TITLE
Eigen 3.3.0 will be installed automatically on MacOSX

### ISSUE THREAD

**Issue by OGI1222** [cdcseacave/openMVS#154]
### Specifications like the version of the project, operating system, and hardware
MacOSX Elcaptain 10.11.4
### Steps to reproduce the problem

I installed these according to the document but 
installing ceres with 'brew install' causes eigen 3.3.0 to be installed without permission

How to downgrade Eigen version when execute brew install ceres-solver ?

**Comment by Roarster31** [comment]
I had issues with using eigen 3.3.0 as well.

I happened to have an older version 3.2.10 on my system (you can check with `brew info eigen`), so I could run `brew switch 3.2.10`.

Then I reverted the recipe for ceres-solver to one that didn't depend on eigen 3.3.0:

`cd $( brew --prefix )/Homebrew/Library/Taps/homebrew/homebrew-science && git checkout e983d70600e ceres-solver.rb`

Then finish the usual build instructions, but don't forget to revert the changes we've just made:

`cd $( brew --prefix )/Homebrew/Library/Taps/homebrew/homebrew-science && git checkout -- ceres-solver.rb`

and then `brew switch` back to your normal (probably latest) version of eigen.

**Comment by djazo** [comment]
If you're having eigen vs ceres version problems, install ceres-solver by:

# brew install --build-from-source ceres-solver

Should help.
