### ISSUE TITLE
 Is it okay if there are so many warnings?

### ISSUE THREAD

**Issue by OGI1222** [cdcseacave/openMVS#155]
### Specifications like the version of the project, operating system, and hardware
OSX in Install phase
### Steps to reproduce the problem
[  1%] Generating CXX prefix source libs/Common/cotire/Common_CXX_prefix.cxx
[  2%] Generating CXX prefix header libs/Common/cotire/Common_CXX_prefix.hxx
[  4%] Building CXX precompiled header libs/Common/cotire/Common_CXX_prefix.hxx.pch
In file included from /Users/install/openMVS_build/libs/Common/cotire/Common_CXX_prefix.hxx:4:
In file included from /Users/install/openMVS_build/libs/Common/cotire/Common_CXX_prefix.cxx:4:
In file included from /Users/install/openMVS/libs/Common/Common.h:176:
In file included from /Users/install/openMVS/libs/Common/Types.h:419:
/Users/install/openMVS/libs/Common/SML.h:29:21: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
        ~SMLVALUE_TYPE() { delete data; }
                           ^      ~~~~
1 warning generated.
Scanning dependencies of target Common
[  5%] Building CXX object libs/Common/CMakeFiles/Common.dir/Common.cpp.o
[  7%] Building CXX object libs/Common/CMakeFiles/Common.dir/CUDA.cpp.o
[  8%] Building CXX object libs/Common/CMakeFiles/Common.dir/ConfigTable.cpp.o
[ 10%] Building CXX object libs/Common/CMakeFiles/Common.dir/EventQueue.cpp.o
[ 11%] Building CXX object libs/Common/CMakeFiles/Common.dir/Log.cpp.o
[ 13%] Building CXX object libs/Common/CMakeFiles/Common.dir/SML.cpp.o
[ 14%] Building CXX object libs/Common/CMakeFiles/Common.dir/Timer.cpp.o
[ 16%] Building CXX object libs/Common/CMakeFiles/Common.dir/Types.cpp.o
[ 17%] Building CXX object libs/Common/CMakeFiles/Common.dir/Util.cpp.o
[ 19%] Building CXX object libs/Common/CMakeFiles/Common.dir/Wildcard.cpp.o
[ 20%] Linking CXX static library ../../lib/libCommon.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../lib/libCommon.a(CUDA.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../lib/libCommon.a(CUDA.cpp.o) has no symbols
[ 20%] Built target Common
[ 22%] Generating CXX prefix source libs/Math/cotire/Math_CXX_prefix.cxx
[ 23%] Generating CXX prefix header libs/Math/cotire/Math_CXX_prefix.hxx
[ 25%] Building CXX precompiled header libs/Math/cotire/Math_CXX_prefix.hxx.pch
In file included from /Users/install/openMVS_build/libs/Math/cotire/Math_CXX_prefix.hxx:4:
In file included from /Users/install/openMVS_build/libs/Math/cotire/Math_CXX_prefix.cxx:4:
In file included from /Users/install/openMVS/libs/Math/Common.h:18:
In file included from /Users/install/openMVS/libs/Math/./../Common/Common.h:176:
In file included from /Users/install/openMVS/libs/Math/./../Common/Types.h:419:
/Users/install/openMVS/libs/Math/./../Common/SML.h:29:21: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
        ~SMLVALUE_TYPE() { delete data; }
                           ^      ~~~~
1 warning generated.
Scanning dependencies of target Math
[ 26%] Building CXX object libs/Math/CMakeFiles/Math.dir/Common.cpp.o
[ 28%] Building CXX object libs/Math/CMakeFiles/Math.dir/IBFS/IBFS.cpp.o
[ 29%] Building CXX object libs/Math/CMakeFiles/Math.dir/LMFit/lmmin.cpp.o
[ 31%] Linking CXX static library ../../lib/libMath.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../lib/libMath.a(Common.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../lib/libMath.a(Common.cpp.o) has no symbols
[ 31%] Built target Math
[ 32%] Generating CXX prefix source libs/IO/cotire/IO_CXX_prefix.cxx
[ 34%] Generating CXX prefix header libs/IO/cotire/IO_CXX_prefix.hxx
[ 35%] Building CXX precompiled header libs/IO/cotire/IO_CXX_prefix.hxx.pch
In file included from /Users/install/openMVS_build/libs/IO/cotire/IO_CXX_prefix.hxx:4:
In file included from /Users/install/openMVS_build/libs/IO/cotire/IO_CXX_prefix.cxx:4:
In file included from /Users/install/openMVS/libs/IO/Common.h:18:
In file included from /Users/install/openMVS/libs/IO/../Common/Common.h:176:
In file included from /Users/install/openMVS/libs/IO/../Common/Types.h:419:
/Users/install/openMVS/libs/IO/../Common/SML.h:29:21: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
        ~SMLVALUE_TYPE() { delete data; }
                           ^      ~~~~
1 warning generated.
Scanning dependencies of target IO
[ 37%] Building CXX object libs/IO/CMakeFiles/IO.dir/Common.cpp.o
[ 38%] Building CXX object libs/IO/CMakeFiles/IO.dir/EXIF.cpp.o
[ 40%] Building CXX object libs/IO/CMakeFiles/IO.dir/Image.cpp.o
/Users/install/openMVS/libs/IO/Image.cpp:263:11: warning: 7 enumeration values
      not handled in switch: 'PF_UNKNOWN', 'PF_DXT1', 'PF_DXT2'... [-Wswitch]
                switch (formatSrc)
                        ^
/Users/install/openMVS/libs/IO/Image.cpp:297:11: warning: 7 enumeration values
      not handled in switch: 'PF_UNKNOWN', 'PF_DXT1', 'PF_DXT2'... [-Wswitch]
                switch (formatSrc)
                        ^
/Users/install/openMVS/libs/IO/Image.cpp:349:11: warning: 7 enumeration values
      not handled in switch: 'PF_UNKNOWN', 'PF_DXT1', 'PF_DXT2'... [-Wswitch]
                switch (formatSrc)
                        ^
/Users/install/openMVS/libs/IO/Image.cpp:416:11: warning: 7 enumeration values
      not handled in switch: 'PF_UNKNOWN', 'PF_DXT1', 'PF_DXT2'... [-Wswitch]
                switch (formatSrc)
                        ^
/Users/install/openMVS/libs/IO/Image.cpp:504:11: warning: 7 enumeration values
      not handled in switch: 'PF_UNKNOWN', 'PF_DXT1', 'PF_DXT2'... [-Wswitch]
                switch (formatSrc)
                        ^
/Users/install/openMVS/libs/IO/Image.cpp:593:11: warning: 7 enumeration values
      not handled in switch: 'PF_UNKNOWN', 'PF_DXT1', 'PF_DXT2'... [-Wswitch]
                switch (formatSrc)
                        ^
/Users/install/openMVS/libs/IO/Image.cpp:659:11: warning: 7 enumeration values
      not handled in switch: 'PF_UNKNOWN', 'PF_DXT1', 'PF_DXT2'... [-Wswitch]
                switch (formatSrc)
                        ^
/Users/install/openMVS/libs/IO/Image.cpp:747:11: warning: 7 enumeration values
      not handled in switch: 'PF_UNKNOWN', 'PF_DXT1', 'PF_DXT2'... [-Wswitch]
                switch (formatSrc)
                        ^
/Users/install/openMVS/libs/IO/Image.cpp:259:10: warning: 7 enumeration values
      not handled in switch: 'PF_UNKNOWN', 'PF_DXT1', 'PF_DXT2'... [-Wswitch]
        switch (formatDst)
                ^
9 warnings generated.
[ 41%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImageBMP.cpp.o
[ 43%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImageDDS.cpp.o
[ 44%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImageEXIF.cpp.o
[ 46%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImageJPG.cpp.o
[ 47%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImagePNG.cpp.o
[ 49%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImageSCI.cpp.o
[ 50%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImageTGA.cpp.o
[ 52%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImageTIFF.cpp.o
[ 53%] Building CXX object libs/IO/CMakeFiles/IO.dir/OBJ.cpp.o
[ 55%] Building CXX object libs/IO/CMakeFiles/IO.dir/PLY.cpp.o
[ 56%] Building CXX object libs/IO/CMakeFiles/IO.dir/TinyXML2.cpp.o
[ 58%] Linking CXX static library ../../lib/libIO.a
[ 58%] Built target IO
[ 59%] Generating CXX prefix source libs/MVS/cotire/MVS_CXX_prefix.cxx
[ 61%] Generating CXX prefix header libs/MVS/cotire/MVS_CXX_prefix.hxx
[ 62%] Building CXX precompiled header libs/MVS/cotire/MVS_CXX_prefix.hxx.pch
In file included from /Users/install/openMVS_build/libs/MVS/cotire/MVS_CXX_prefix.hxx:4:
In file included from /Users/install/openMVS_build/libs/MVS/cotire/MVS_CXX_prefix.cxx:4:
In file included from /Users/install/openMVS/libs/MVS/Common.h:42:
In file included from /Users/install/openMVS/libs/MVS/../Common/Common.h:176:
In file included from /Users/install/openMVS/libs/MVS/../Common/Types.h:419:
/Users/install/openMVS/libs/MVS/../Common/SML.h:29:21: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
        ~SMLVALUE_TYPE() { delete data; }
                           ^      ~~~~
1 warning generated.
Scanning dependencies of target MVS
[ 64%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/Common.cpp.o
[ 65%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/Camera.cpp.o
[ 67%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/DepthMap.cpp.o
[ 68%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/Image.cpp.o
[ 70%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/Mesh.cpp.o
[ 71%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/Platform.cpp.o
[ 73%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/PointCloud.cpp.o
[ 74%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/RectsBinPack.cpp.o
/Users/install/openMVS/libs/MVS/RectsBinPack.cpp:76:10: warning: enumeration
      value 'RectLast' not handled in switch [-Wswitch]
        switch (method) {
                ^
1 warning generated.
[ 76%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/Scene.cpp.o
[ 77%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/SceneDensify.cpp.o
[ 79%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/SceneReconstruct.cpp.o
[ 80%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/SceneRefine.cpp.o
[ 82%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/SceneRefineCUDA.cpp.o
[ 83%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/SceneTexture.cpp.o
[ 85%] Linking CXX shared library ../../lib/libMVS.dylib
[ 85%] Built target MVS
Scanning dependencies of target InterfaceVisualSFM
[ 86%] Building CXX object apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/InterfaceVisualSFM.cpp.o
In file included from /Users/install/openMVS/apps/InterfaceVisualSFM/InterfaceVisualSFM.cpp:32:
In file included from /Users/install/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/Common.h:42:
In file included from /Users/install/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/../Common/Common.h:176:
In file included from /Users/install/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/../Common/Types.h:419:
/Users/install/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/../Common/SML.h:29:21: warning: 
      cannot delete expression with pointer-to-'void' type 'void *'
      [-Wdelete-incomplete]
        ~SMLVALUE_TYPE() { delete data; }
                           ^      ~~~~
1 warning generated.
[ 88%] Linking CXX executable ../../bin/InterfaceVisualSFM
[ 88%] Built target InterfaceVisualSFM
Scanning dependencies of target DensifyPointCloud
[ 89%] Building CXX object apps/DensifyPointCloud/CMakeFiles/DensifyPointCloud.dir/DensifyPointCloud.cpp.o
In file included from /Users/install/openMVS/apps/DensifyPointCloud/DensifyPointCloud.cpp:32:
In file included from /Users/install/openMVS/apps/DensifyPointCloud/../../libs/MVS/Common.h:42:
In file included from /Users/install/openMVS/apps/DensifyPointCloud/../../libs/MVS/../Common/Common.h:176:
In file included from /Users/install/openMVS/apps/DensifyPointCloud/../../libs/MVS/../Common/Types.h:419:
/Users/install/openMVS/apps/DensifyPointCloud/../../libs/MVS/../Common/SML.h:29:21: warning: 
      cannot delete expression with pointer-to-'void' type 'void *'
      [-Wdelete-incomplete]
        ~SMLVALUE_TYPE() { delete data; }
                           ^      ~~~~
1 warning generated.
[ 91%] Linking CXX executable ../../bin/DensifyPointCloud
[ 91%] Built target DensifyPointCloud
Scanning dependencies of target ReconstructMesh
[ 92%] Building CXX object apps/ReconstructMesh/CMakeFiles/ReconstructMesh.dir/ReconstructMesh.cpp.o
In file included from /Users/install/openMVS/apps/ReconstructMesh/ReconstructMesh.cpp:32:
In file included from /Users/install/openMVS/apps/ReconstructMesh/../../libs/MVS/Common.h:42:
In file included from /Users/install/openMVS/apps/ReconstructMesh/../../libs/MVS/../Common/Common.h:176:
In file included from /Users/install/openMVS/apps/ReconstructMesh/../../libs/MVS/../Common/Types.h:419:
/Users/install/openMVS/apps/ReconstructMesh/../../libs/MVS/../Common/SML.h:29:21: warning: 
      cannot delete expression with pointer-to-'void' type 'void *'
      [-Wdelete-incomplete]
        ~SMLVALUE_TYPE() { delete data; }
                           ^      ~~~~
1 warning generated.
[ 94%] Linking CXX executable ../../bin/ReconstructMesh
[ 94%] Built target ReconstructMesh
Scanning dependencies of target RefineMesh
[ 95%] Building CXX object apps/RefineMesh/CMakeFiles/RefineMesh.dir/RefineMesh.cpp.o
In file included from /Users/install/openMVS/apps/RefineMesh/RefineMesh.cpp:32:
In file included from /Users/install/openMVS/apps/RefineMesh/../../libs/MVS/Common.h:42:
In file included from /Users/install/openMVS/apps/RefineMesh/../../libs/MVS/../Common/Common.h:176:
In file included from /Users/install/openMVS/apps/RefineMesh/../../libs/MVS/../Common/Types.h:419:
/Users/install/openMVS/apps/RefineMesh/../../libs/MVS/../Common/SML.h:29:21: warning: 
      cannot delete expression with pointer-to-'void' type 'void *'
      [-Wdelete-incomplete]
        ~SMLVALUE_TYPE() { delete data; }
                           ^      ~~~~
1 warning generated.
[ 97%] Linking CXX executable ../../bin/RefineMesh
[ 97%] Built target RefineMesh
Scanning dependencies of target TextureMesh
[ 98%] Building CXX object apps/TextureMesh/CMakeFiles/TextureMesh.dir/TextureMesh.cpp.o
In file included from /Users/install/openMVS/apps/TextureMesh/TextureMesh.cpp:32:
In file included from /Users/install/openMVS/apps/TextureMesh/../../libs/MVS/Common.h:42:
In file included from /Users/install/openMVS/apps/TextureMesh/../../libs/MVS/../Common/Common.h:176:
In file included from /Users/install/openMVS/apps/TextureMesh/../../libs/MVS/../Common/Types.h:419:
/Users/install/openMVS/apps/TextureMesh/../../libs/MVS/../Common/SML.h:29:21: warning: 
      cannot delete expression with pointer-to-'void' type 'void *'
      [-Wdelete-incomplete]
        ~SMLVALUE_TYPE() { delete data; }
                           ^      ~~~~
1 warning generated.
[100%] Linking CXX executable ../../bin/TextureMesh
[100%] Built target TextureMesh
Password:
[ 20%] Built target Common
[ 31%] Built target Math
[ 58%] Built target IO
[ 85%] Built target MVS
[ 88%] Built target InterfaceVisualSFM
[ 91%] Built target DensifyPointCloud
[ 94%] Built target ReconstructMesh
[ 97%] Built target RefineMesh
[100%] Built target TextureMesh
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/include/OpenMVS/ConfigLocal.h
-- Installing: /usr/local/lib/CMake/OpenMVS/OpenMVSConfig.cmake
-- Installing: /usr/local/lib/CMake/OpenMVS/OpenMVSConfigVersion.cmake
-- Installing: /usr/local/lib/CMake/OpenMVS/OpenMVSTargets.cmake
-- Installing: /usr/local/lib/CMake/OpenMVS/OpenMVSTargets-release.cmake
-- Installing: /usr/local/include/OpenMVS/MVS.h
-- Installing: /usr/local/lib/OpenMVS/libCommon.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /usr/local/lib/OpenMVS/libCommon.a(CUDA.cpp.o) has no symbols
-- Installing: /usr/local/include/OpenMVS/Common/AABB.h
-- Installing: /usr/local/include/OpenMVS/Common/AutoEstimator.h
-- Installing: /usr/local/include/OpenMVS/Common/AutoPtr.h
-- Installing: /usr/local/include/OpenMVS/Common/CUDA.h
-- Installing: /usr/local/include/OpenMVS/Common/Common.h
-- Installing: /usr/local/include/OpenMVS/Common/Config.h
-- Installing: /usr/local/include/OpenMVS/Common/ConfigTable.h
-- Installing: /usr/local/include/OpenMVS/Common/CriticalSection.h
-- Installing: /usr/local/include/OpenMVS/Common/EventQueue.h
-- Installing: /usr/local/include/OpenMVS/Common/FastDelegate.h
-- Installing: /usr/local/include/OpenMVS/Common/FastDelegateBind.h
-- Installing: /usr/local/include/OpenMVS/Common/FastDelegateCPP11.h
-- Installing: /usr/local/include/OpenMVS/Common/File.h
-- Installing: /usr/local/include/OpenMVS/Common/Filters.h
-- Installing: /usr/local/include/OpenMVS/Common/HTMLDoc.h
-- Installing: /usr/local/include/OpenMVS/Common/HalfFloat.h
-- Installing: /usr/local/include/OpenMVS/Common/Hash.h
-- Installing: /usr/local/include/OpenMVS/Common/LinkLib.h
-- Installing: /usr/local/include/OpenMVS/Common/List.h
-- Installing: /usr/local/include/OpenMVS/Common/Log.h
-- Installing: /usr/local/include/OpenMVS/Common/MemFile.h
-- Installing: /usr/local/include/OpenMVS/Common/OBB.h
-- Installing: /usr/local/include/OpenMVS/Common/Octree.h
-- Installing: /usr/local/include/OpenMVS/Common/Plane.h
-- Installing: /usr/local/include/OpenMVS/Common/Queue.h
-- Installing: /usr/local/include/OpenMVS/Common/Ray.h
-- Installing: /usr/local/include/OpenMVS/Common/Rotation.h
-- Installing: /usr/local/include/OpenMVS/Common/SML.h
-- Installing: /usr/local/include/OpenMVS/Common/Semaphore.h
-- Installing: /usr/local/include/OpenMVS/Common/SharedPtr.h
-- Installing: /usr/local/include/OpenMVS/Common/Sphere.h
-- Installing: /usr/local/include/OpenMVS/Common/Streams.h
-- Installing: /usr/local/include/OpenMVS/Common/Strings.h
-- Installing: /usr/local/include/OpenMVS/Common/Thread.h
-- Installing: /usr/local/include/OpenMVS/Common/Timer.h
-- Installing: /usr/local/include/OpenMVS/Common/Types.h
-- Installing: /usr/local/include/OpenMVS/Common/Util.h
-- Installing: /usr/local/include/OpenMVS/Common/Wildcard.h
-- Installing: /usr/local/include/OpenMVS/Common/AABB.inl
-- Installing: /usr/local/include/OpenMVS/Common/OBB.inl
-- Installing: /usr/local/include/OpenMVS/Common/Octree.inl
-- Installing: /usr/local/include/OpenMVS/Common/Plane.inl
-- Installing: /usr/local/include/OpenMVS/Common/Ray.inl
-- Installing: /usr/local/include/OpenMVS/Common/Rotation.inl
-- Installing: /usr/local/include/OpenMVS/Common/Sampler.inl
-- Installing: /usr/local/include/OpenMVS/Common/Sphere.inl
-- Installing: /usr/local/include/OpenMVS/Common/Types.inl
-- Installing: /usr/local/include/OpenMVS/Common/Util.inl
-- Installing: /usr/local/include/OpenMVS/Math/Common.h
-- Installing: /usr/local/include/OpenMVS/Math/LBP.h
-- Installing: /usr/local/include/OpenMVS/Math/IBFS/IBFS.h
-- Installing: /usr/local/include/OpenMVS/Math/LMFit/lmmin.h
-- Installing: /usr/local/include/OpenMVS/Math/TRWS/MRFEnergy.h
-- Installing: /usr/local/include/OpenMVS/Math/TRWS/instances.h
-- Installing: /usr/local/include/OpenMVS/Math/TRWS/typeBinary.h
-- Installing: /usr/local/include/OpenMVS/Math/TRWS/typeBinaryFast.h
-- Installing: /usr/local/include/OpenMVS/Math/TRWS/typeGeneral.h
-- Installing: /usr/local/include/OpenMVS/Math/TRWS/typePotts.h
-- Installing: /usr/local/include/OpenMVS/Math/TRWS/typeTruncatedLinear.h
-- Installing: /usr/local/include/OpenMVS/Math/TRWS/typeTruncatedLinear2D.h
-- Installing: /usr/local/include/OpenMVS/Math/TRWS/typeTruncatedQuadratic.h
-- Installing: /usr/local/include/OpenMVS/Math/TRWS/typeTruncatedQuadratic2D.h
-- Installing: /usr/local/include/OpenMVS/Math/TRWS/MRFEnergy.inl
-- Installing: /usr/local/include/OpenMVS/Math/TRWS/minimize.inl
-- Installing: /usr/local/include/OpenMVS/Math/TRWS/ordering.inl
-- Installing: /usr/local/include/OpenMVS/Math/TRWS/treeProbabilities.inl
-- Installing: /usr/local/lib/OpenMVS/libMath.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /usr/local/lib/OpenMVS/libMath.a(Common.cpp.o) has no symbols
-- Installing: /usr/local/lib/OpenMVS/libIO.a
-- Installing: /usr/local/include/OpenMVS/IO/Common.h
-- Installing: /usr/local/include/OpenMVS/IO/EXIF.h
-- Installing: /usr/local/include/OpenMVS/IO/Image.h
-- Installing: /usr/local/include/OpenMVS/IO/ImageBMP.h
-- Installing: /usr/local/include/OpenMVS/IO/ImageDDS.h
-- Installing: /usr/local/include/OpenMVS/IO/ImageEXIF.h
-- Installing: /usr/local/include/OpenMVS/IO/ImageJPG.h
-- Installing: /usr/local/include/OpenMVS/IO/ImagePNG.h
-- Installing: /usr/local/include/OpenMVS/IO/ImageSCI.h
-- Installing: /usr/local/include/OpenMVS/IO/ImageTGA.h
-- Installing: /usr/local/include/OpenMVS/IO/ImageTIFF.h
-- Installing: /usr/local/include/OpenMVS/IO/OBJ.h
-- Installing: /usr/local/include/OpenMVS/IO/PLY.h
-- Installing: /usr/local/include/OpenMVS/IO/TinyXML2.h
-- Installing: /usr/local/lib/OpenMVS/libMVS.dylib
-- Installing: /usr/local/include/OpenMVS/MVS/Camera.h
-- Installing: /usr/local/include/OpenMVS/MVS/Common.h
-- Installing: /usr/local/include/OpenMVS/MVS/DepthMap.h
-- Installing: /usr/local/include/OpenMVS/MVS/Image.h
-- Installing: /usr/local/include/OpenMVS/MVS/Interface.h
-- Installing: /usr/local/include/OpenMVS/MVS/Mesh.h
-- Installing: /usr/local/include/OpenMVS/MVS/Platform.h
-- Installing: /usr/local/include/OpenMVS/MVS/PointCloud.h
-- Installing: /usr/local/include/OpenMVS/MVS/RectsBinPack.h
-- Installing: /usr/local/include/OpenMVS/MVS/Scene.h
-- Installing: /usr/local/bin/OpenMVS/InterfaceVisualSFM
-- Installing: /usr/local/bin/OpenMVS/DensifyPointCloud
-- Installing: /usr/local/bin/OpenMVS/ReconstructMesh
-- Installing: /usr/local/bin/OpenMVS/RefineMesh
-- Installing: /usr/local/bin/OpenMVS/TextureMesh

**Comment by cdcseacave** [comment]
probably yes, almost all are linux specific warnings, on windows there are 0 warnings
