### ISSUE TITLE
Building error in windows 

### ISSUE THREAD

**Issue by vivzqs** [cdcseacave/openMVS#16]
I‘m using vs2013 to compile OpenMVS, but some errors occur in line 1258 of "common/list.h".

![1](https://cloud.githubusercontent.com/assets/3986288/10414753/bd2bd4ca-7016-11e5-98d4-347f39ec9b6d.png)

f:\github\openmvs\src\libs\common\List.h(1258): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>f:\github\openmvs\src\libs\common\List.h(1258): warning C4346: 'SEACAVE::cList<TYPE,ARG_TYPE,useConstruct,grow,IDX_TYPE>::NO_INDEX' : dependent name is not a type
2>          prefix with 'typename' to indicate a type
2>f:\github\openmvs\src\libs\common\List.h(1258): error C2988: unrecognizable template declaration/definition
2>f:\github\openmvs\src\libs\common\List.h(1258): error C2059: syntax error : ')'

**Comment by cdcseacave** [comment]
I do not have VC2013 to test, but the code looks fine to me. Could you please try to fix it and provide the solution?

For ex try to replace it by the following:

template <typename TYPE, typename ARG_TYPE, int useConstruct, int grow, typename IDX_TYPE>
typename const cList<TYPE,ARG_TYPE,useConstruct,grow,IDX_TYPE>::IDX
cList<TYPE,ARG_TYPE,useConstruct,grow,IDX_TYPE>::NO_INDEX(
	DECLARE_NO_INDEX(IDX)
);

**Comment by vivzqs** [comment]
Thanks for your reply. But this error still exists. Which version of VC do you use to compile it in windows?

**Comment by cdcseacave** [comment]
VC2015

**Comment by vivzqs** [comment]
OK. I will try VC2015.

**Comment by cdcseacave** [comment]
found the problem, in Types.h replace line 257 with:
```
#define DECLARE_NO_INDEX(...) std::numeric_limits<__VA_ARGS__>::max()
```
