### ISSUE TITLE
Opening up the output in Blender

### ISSUE THREAD

**Issue by oculushut** [cdcseacave/openMVS#160]
I am usingOpenMVS v0.7 and openMVG v1.0 with the Python pipeline sample (MvgMvs_Pipeline.py).  I am on Windows 10.

The processing appears to have been successful.  Within my [output]\mvs folder I have the following .ply files:

scene_dense.ply
scene_dense_mesh.ply
scene_dense_mesh_refine.ply
scene_dense_mesh_refine_texture.ply

I also have an associated texture file: scene_dense_mesh_refine_texture.png

I can open the PLY files up in MeshLab and they display with the texture, but not in Blender.

Couple of questions:

a) Anybody have any idea how to get the texture to display in Blender when you import the PLY file?  I can import and see the mesh, but the texture does not appear.  If I try to add the PNG file as a texture it looks like the mesh does not have UV and does not map to the mesh properly.  Am using Blender 2.77a.

b) Is there a particular reason why PLY is used rather than OBJ & MTL & Texture files?  I have had more luck with most packages when importing/exporting in OBJ & MTL.

Lastly, I currently workaround this problem by opening up in MeshLab and then exporting out as OBJ & MTL - this can then be opened up in Blender by creating an associated texture separately.  Would be great if I could skip this step though.

**Comment by rennu** [comment]
Hi,

You can use --export-type obj to output obj.

**Comment by charlescva** [comment]
@rennu Nice.  I noticed the PNG was out there and thought I may have to do my own mapping in blender for the texture.   I'll give OBJ a try sometime.

**Comment by abhimanyuchadha96** [comment]
The obj file works well in Meshlab with the texture but in Blender it is giving the same issue as the PLY file. The mesh is there but can't load the texture. 
Please help.

**Comment by charlescva** [comment]
Use Cycles engine in blender with nodes for image (png file) texture and ambient occlusion shader. Diffuse looks nice too, but can look odd when a scene has non uniform lighting. If you're not familiar with using image UV mapping in blender nodes you should do a quick YouTube tutorial first.

**Comment by abhimanyuchadha96** [comment]
The tutorials really got me confused. 
What is the difference between the Blender and Cycles engine in Blender?
And how do I change the ambient occlusion shader or the diffuse? I am sorry but I am pretty new to this.

**Comment by charlescva** [comment]
https://blender.stackexchange.com/questions/5820/how-is-cycles-different-from-blender-internal/5821#5821

**Comment by charlescva** [comment]
https://images.app.goo.gl/JDgk39EQioBWTPMe9

In the above image you will find example blender nodes diagram and can use the top three nodes as reference for image texture with diffuse shader. This works with OBJ, MTL and PNG output from openmvs textured model output.
