### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by charlescva** [cdcseacave/openMVS#161]
### Specifications like the version of the project, operating system, and hardware
Linux, Dell Precision, latest build as of 12/18/2016

### Steps to reproduce the problem
Create NVM from TheiaSfM
InterfaceVisualSFM reconstruction.nvm
DensifyPointCloud reconstruction.mvs
ReconstructMesh reconstruction_dense.mvs

17:21:41 [App     ] Build date: Dec 18 2016, 16:02:04
17:21:41 [App     ] CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
17:21:41 [App     ] RAM: 31.13GB Physical Memory 19.31GB Virtual Memory
17:21:41 [App     ] OS: Linux 4.7.0-0.bpo.1-amd64 (x86_64)
17:21:41 [App     ] SSE & AVX compatible CPU & OS detected
17:21:41 [App     ] Command line: reconstruction_dense.mvs
17:21:50 [App     ] Scene loaded (8s901ms):
	121 images (121 calibrated) with a total of 26.59 MPixels (0.22 MPixels/image)
	2317330 points, 0 vertices, 0 faces
Floating point exception (core dumped)

Thoughts?

**Comment by charlescva** [comment]
This worked about an hour ago on the same system doing a reconstruct from about 9 photos of a statue.  So I'm not using 130 photos of a building with some background terrain/trees, so the domain may be much larger than my first test.

**Comment by charlescva** [comment]
Okay so just for kicks, I tried opening the Dense PLY reconstruction in MeshLab, and it said that "1 verticies was NaN, Corrected.", and it has loaded in MeshLab successfully. However, trying to export the PLY with color values and re-running it through the ReconstructMesh has failed, probably doesnt like the Meshlab format it pushed out:

root@e817e954b65d:/home/output# ReconstructMesh reconstruction_dense_meshlab.ply 
18:15:11 [App     ] Build date: Dec 18 2016, 16:02:04
18:15:11 [App     ] CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
18:15:11 [App     ] RAM: 31.13GB Physical Memory 19.31GB Virtual Memory
18:15:11 [App     ] OS: Linux 4.7.0-0.bpo.1-amd64 (x86_64)
18:15:11 [App     ] SSE & AVX compatible CPU & OS detected
18:15:11 [App     ] Command line: reconstruction_dense_meshlab.ply
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted (core dumped)

**Comment by cdcseacave** [comment]
What Linux version you use?

**Comment by charlescva** [comment]
Debian 4.7.8-1~bpo8+1 (2016-10-19) x86_64 GNU/Linux

**Comment by charlescva** [comment]
Was just speaking w/ a colleague about this.  Perhaps we just toss the NaN floatpoint out if encountered, and dump the incident to the console.  Not sure we can or want to try to fix it or position it somewhere properly.

**Comment by cdcseacave** [comment]
Despite the name, the error is not related to floating point calculus, but
rather integers, so the nan is not the problem here. I encountered this
problem on GCC 4.8, and I solved it by upgrading to GCC 5.6 or later.

**Comment by charlescva** [comment]
Revisiting this because it has occurred again.  Not sure why the compiler would be an issue here, in that if there is an exception in the code we should just catch it right?  I've got a couple C/++ engineers I can work with to dig in to the codebase.  Upgrading my systems to using gcc5 is considered 'unstable', but i can always compile inside a linux container.

**Comment by charlescva** [comment]
root@66b542def6ef:/home/output# ReconstructMesh reconstruction_dense.mvs -v4
20:02:03 [App     ] Build date: Jan 12 2017, 19:59:48
20:02:03 [App     ] CPU: Intel(R) Xeon(R) CPU           X5680  @ 3.33GHz
20:02:03 [App     ] RAM: 39.12GB Physical Memory 0B Virtual Memory
20:02:03 [App     ] OS: Linux 3.10.0-514.2.2.el7.x86_64 (x86_64)
20:02:03 [App     ] warning: no AVX compatible CPU or OS detected
20:02:03 [App     ] Command line: reconstruction_dense.mvs -v4



20:03:19 [App     ] Scene loaded (1m16s384ms):
	230 images (230 calibrated) with a total of 113.71 MPixels (0.49 MPixels/image)
	11421500 points, 0 vertices, 0 faces
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: dexp != 2047
File: /usr/include/CGAL/Mpzf.h
Line: 433
Explanation: Creating an Mpzf from infinity or NaN.
Aborted (core dumped)

**Comment by charlescva** [comment]
(gdb) frame 16
#16 0x0000000000ac2c12 in MVS::Scene::<lambda(std::size_t)>::operator()(std::size_t) const (__closure=0x7ffeb1c0c4b0, 
    idx=11409350) at /openMVS/libs/MVS/SceneReconstruct.cpp:825
825					const cell_handle_t c(delaunay.locate(p, lt, li, lj, hint->cell()));
(gdb) print p
$1 = (const DELAUNAY::point_t &) @0x2a8bc000: {<CGAL::PointC3<CGAL::Epick>> = {base = {<CGAL::VectorC3<CGAL::Epick>> = {
        base = {_M_elems = {-nan(0x8000000000000), -nan(0x8000000000000), 
            -nan(0x8000000000000)}}}, <No data fields>}}, <No data fields>}

**Comment by charlescva** [comment]
Implement is isnan check on the X dimension of each point.  If isnan then we just return on the lambda loop.  PR: https://github.com/cdcseacave/openMVS/pull/169
