### ISSUE TITLE
Graphics Card

### ISSUE THREAD

**Issue by oculushut** [cdcseacave/openMVS#162]
I noticed that for much of the processing my CPU goes to 100%.

Does openMVS/openMVG make use of my graphics card automatically?  Or is there a setting or parameter I need to use to make use of my graphics card?  I have an NVIDIA card (so have CUDA support).

Am currently playing around with the python sample which shows the use of openMVS -> openMVG.

**Comment by rennu** [comment]
At least in my tests (with and without OpenCV) OpenMVG didn't use GPU for processing. Also, there are no switches to enable it (someone correct me if I'm wrong?).

OpenMVS, supports GPU processing for RefineMesh if you use RefineMeshCUDA.

**Comment by pmoulon** [comment]
OpenMVG does not use the GPU. If you want to use the GPU you can help to implemenent the GPU support or use OpenCV GPU keypoint detector and descriptor and the GPU matching framework.
BTW, some experiments shown me that cascade hashing is still faster than a brute force GPU matcher (for SIFT).
