### ISSUE TITLE
Problems while installing openMVS

### ISSUE THREAD

**Issue by patsia** [cdcseacave/openMVS#163]
Hi everybody
i have a problem while installing openMVS on Ubuntu: i followed exactly this steps: 
https://github.com/cdcseacave/openMVS/wiki/Building 

but there is allways the error:
CMake Error at build/Utils.cmake:216 (message):
  VCG required, but not found: Please specify VCG directory using VCG_ROOT
  env.  variable

how to proceed? I already added the path to the .profile in my home-folder but it still doesn't work
Maybe someone could help me (as for dummies)?
Thx :-)

**Comment by rennu** [comment]
I think you might have missed the step ```main_path=`pwd` ```, or you were in wrong directory when you did ```main_path=`pwd` ``` or you missed the step where you clone vcglib repository .

Either way, go to the directory where you have openMVS and openMVS_build directories ie. /home/patsia/build. Then:
```
main_path=`pwd`
git clone https://github.com/cdcseacave/VCG.git vcglib
cd openMVS_build
cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="$main_path/vcglib"
make -j2 && sudo make install
```

**Comment by patsia** [comment]
Thx very very much! :-) You saved my laptop from getting thrown out of the window ;-) `main_path='pwd'` was the point, don't know how i could have missed it (twice) but with this line, everything went perfect. Thanks again.

**Comment by dxqxiaoqiang** [comment]
I have done as your instrations but the errors as :
dxq@ubuntu:~/openMVS-master$ main_path=`pwd`
dxq@ubuntu:~/openMVS-master$ git clone https://github.com/cdcseacave/VCG.git vcglib
Cloning into 'vcglib'...
remote: Counting objects: 2379, done.
remote: Compressing objects: 100% (1332/1332), done.
remote: Total 2379 (delta 1021), reused 2379 (delta 1021), pack-reused 0
Receiving objects: 100% (2379/2379), 8.76 MiB | 153.00 KiB/s, done.
Resolving deltas: 100% (1021/1021), done.
Checking connectivity... done.
dxq@ubuntu:~/openMVS-master$ cd openMVS_build/
dxq@ubuntu:~/openMVS-master/openMVS_build$ cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="$main_path/vcglib"
CMake Error: The source directory "/home/dxq/openMVS-master/openMVS" does not exist.
Where i go wrong?  @rennu

**Comment by rennu** [comment]
Is that full log? You need to follow [full instructions](https://github.com/cdcseacave/openMVS/wiki/Building#linux-compilation). My message only had instructions how to fix patsia's problem.
