### ISSUE TITLE
invalid use of incomplete type 'struct Eigen::internal::enable_if<false, SEACAVE::TPoint3<double>*>'

### ISSUE THREAD

**Issue by samhodge** [cdcseacave/openMVS#164]
### Specifications like the version of the project, operating system, and hardware
Following default install instructions under OSX, brings in ceres-solver 1.12 and eigen 3.3.1

just rang brew update twice and brew doctor

build ceres-solver from source against eigen 3.3.1 which is stable in brew.

using gcc/6.3

Error follows:

/usr/local/include/eigen3/Eigen/src/Core/PlainObjectBase.h:844:30: note:   template argument deduction/substitution failed:
/usr/local/include/eigen3/Eigen/src/Core/PlainObjectBase.h: In substitution of 'template<class T> void Eigen::PlainObjectBase<Derived>::_init1(const Index&, typename Eigen::internal::enable_if<((((((! Eigen::internal::is_same<long int, typename Eigen::internal::traits<T>::Scalar>::value) && Eigen::internal::is_same<long int, T>::value) && (typename Eigen::internal::dense_xpr_base<Derived>::type:: SizeAtCompileTime != Eigen::Dynamic)) && (typename Eigen::internal::dense_xpr_base<Derived>::type:: SizeAtCompileTime != 1)) && Eigen::internal::is_convertible<T, typename Eigen::internal::traits<T>::Scalar>::value) && Eigen::internal::is_same<typename Eigen::internal::traits<T>::XprKind, Eigen::ArrayXpr>::value), T*>::type*) [with T = SEACAVE::TPoint3<double>]':
/usr/local/include/eigen3/Eigen/src/Core/Matrix.h:296:31:   required from 'Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const T&) [with T = SEACAVE::TPoint3<double>; _Scalar = double; int _Rows = 3; int _Cols = 1; int _Options = 0; int _MaxRows = 3; int _MaxCols = 1]'
/Users/sam/OpenMVS_build/openMVS/libs/MVS/Camera.cpp:187:59:   required from here
/usr/local/include/eigen3/Eigen/src/Core/PlainObjectBase.h:844:30: error: invalid use of incomplete type 'struct Eigen::internal::enable_if<false, SEACAVE::TPoint3<double>*>'
In file included from /usr/local/include/eigen3/Eigen/Core:341:0,
                 from /Users/sam/OpenMVS_build/openMVS/libs/MVS/../Common/Types.h:122,
                 from /Users/sam/OpenMVS_build/openMVS/libs/MVS/../Common/Common.h:176,
                 from /Users/sam/OpenMVS_build/openMVS/libs/MVS/Common.h:42,
                 from /Users/sam/OpenMVS_build/openMVS/libs/MVS/Camera.cpp:32:
/usr/local/include/eigen3/Eigen/src/Core/util/Meta.h:162:50: note: declaration of 'struct Eigen::internal::enable_if<false, SEACAVE::TPoint3<double>*>'
 template<bool Condition, typename T=void> struct enable_if;
                                                  ^~~~~~~~~
make[2]: *** [libs/MVS/CMakeFiles/MVS.dir/Camera.cpp.o] Error 1
make[1]: *** [libs/MVS/CMakeFiles/MVS.dir/all] Error 2
make: *** [all] Error 2
kaos:openMVS_build sam$ brew info eigen
eigen: stable 3.3.1 (bottled), HEAD
C++ template library for linear algebra
https://eigen.tuxfamily.org/
/usr/local/Cellar/eigen/3.3.1 (486 files, 6.4M) *
  Poured from bottle on 2016-12-24 at 12:24:22
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/eigen.rb
==> Dependencies
Build: cmake ✔
==> Options
--universal
	Build a universal binary
--HEAD
	Install HEAD version
kaos:openMVS_build sam$ brew info ceres-solver
homebrew/science/ceres-solver: stable 1.12.0 (bottled), HEAD
C++ library for large-scale optimization
http://ceres-solver.org/
/usr/local/Cellar/ceres-solver/1.12.0 (460 files, 15.7M) *
  Built from source on 2016-12-24 at 12:28:53
From: https://github.com/Homebrew/homebrew-science/blob/master/ceres-solver.rb
==> Dependencies
Required: cmake ✔, glog ✔, gflags ✔, eigen ✔, metis ✔
Recommended: suite-sparse ✔
==> Options
--without-suite-sparse
	Build without suite-sparse support
--without-test
	Do not build and run the tests (not recommended).
--HEAD
	Install HEAD version

/usr/local/include/eigen3/Eigen/src/Core/Matrix.h:296:31:   required from 'Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const T&) [with T = SEACAVE::TPoint3<double>; _Scalar = double; int _Rows = 3; int _Cols = 1; int _Options = 0; int _MaxRows = 3; int _MaxCols = 1]'
/Users/sam/OpenMVS_build/openMVS/libs/MVS/Camera.cpp:187:59:   required from here
/usr/local/include/eigen3/Eigen/src/Core/PlainObjectBase.h:844:30: error: invalid use of incomplete type 'struct Eigen::internal::enable_if<false, SEACAVE::TPoint3<double>*>'
In file included from /usr/local/include/eigen3/Eigen/Core:341:0,
                 from /Users/sam/OpenMVS_build/openMVS/libs/MVS/../Common/Types.h:122,
                 from /Users/sam/OpenMVS_build/openMVS/libs/MVS/../Common/Common.h:176,
                 from /Users/sam/OpenMVS_build/openMVS/libs/MVS/Common.h:42,
                 from /Users/sam/OpenMVS_build/openMVS/libs/MVS/Camera.cpp:32:
/usr/local/include/eigen3/Eigen/src/Core/util/Meta.h:162:50: note: declaration of 'struct Eigen::internal::enable_if<false, SEACAVE::TPoint3<double>*>'
 template<bool Condition, typename T=void> struct enable_if;
                                                  ^~~~~~~~~
make[2]: *** [libs/MVS/CMakeFiles/MVS.dir/Camera.cpp.o] Error 1
make[1]: *** [libs/MVS/CMakeFiles/MVS.dir/all] Error 2
make: *** [all] Error 2
kaos:openMVS_build sam$ brew info eigen
eigen: stable 3.3.1 (bottled), HEAD
C++ template library for linear algebra
https://eigen.tuxfamily.org/
/usr/local/Cellar/eigen/3.3.1 (486 files, 6.4M) *
  Poured from bottle on 2016-12-24 at 12:24:22
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/eigen.rb
==> Dependencies
Build: cmake ✔
==> Options
--universal
	Build a universal binary
--HEAD
	Install HEAD version
kaos:openMVS_build sam$ brew info ceres-solver
homebrew/science/ceres-solver: stable 1.12.0 (bottled), HEAD
C++ library for large-scale optimization
http://ceres-solver.org/
/usr/local/Cellar/ceres-solver/1.12.0 (460 files, 15.7M) *
  Built from source on 2016-12-24 at 12:28:53
From: https://github.com/Homebrew/homebrew-science/blob/master/ceres-solver.rb
==> Dependencies
Required: cmake ✔, glog ✔, gflags ✔, eigen ✔, metis ✔
Recommended: suite-sparse ✔
==> Options
--without-suite-sparse
	Build without suite-sparse support
--without-test
	Do not build and run the tests (not recommended).
--HEAD
	Install HEAD version
kaos:openMVS_build sam$ cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="$main_path/vcglib" -DCMAKE_C_COMPILER=/usr/local/Cellar/gcc/6.3.0/bin/gcc-6 -DCMAKE_CXX_COMPILER=/usr/local/Cellar/gcc/6.3.0/bin/g++-6 -DVCG_ROOT="$main_path/vcglib"
kaos:openMVS_build sam$ brew info gcc
gcc: stable 6.3.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org
/usr/local/Cellar/gcc/5.1.0 (1,380 files, 244.8M)
  Poured from bottle on 2015-05-20 at 01:34:08
/usr/local/Cellar/gcc/5.3.0 (1,390 files, 254.7M)
  Poured from bottle on 2016-04-17 at 13:28:24
/usr/local/Cellar/gcc/6.2.0 (1,435 files, 282M)
  Poured from bottle on 2016-12-17 at 13:19:33
/usr/local/Cellar/gcc/6.3.0 (1,367 files, 248.2M) *
  Built from source on 2016-12-23 at 20:31:45 with: --without-multilib
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb
==> Dependencies
Required: gmp ✔, libmpc ✔, mpfr ✔, isl ✔
==> Options
--with-all-languages
	Enable all compilers and languages, except Ada
--with-java
	Build the gcj compiler
--with-jit
	Build the jit compiler
--with-nls
	Build with native language support (localization)
--without-fortran
	Build without the gfortran compiler
--without-multilib
	Build without multilib support
--HEAD
	Install HEAD version
kaos:openMVS_build sam$ brew info boost
boost: stable 1.62.0 (bottled), HEAD
Collection of portable C++ source libraries
https://www.boost.org/
/usr/local/Cellar/boost/1.60.0_2 (11,139 files, 436.8M)
  Poured from bottle on 2016-06-04 at 14:12:00
/usr/local/Cellar/boost/1.62.0 (12,405 files, 416.4M) *
  Poured from bottle on 2016-12-17 at 13:17:15
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost.rb
==> Dependencies
Optional: icu4c ✔
==> Requirements
Optional: mpi ✔
==> Options
--c++11
	Build using C++11 mode
--universal
	Build a universal binary
--with-icu4c
	Build regexp engine with icu support
--with-mpi
	Build with MPI support
--without-single
	Disable building single-threading variant
--without-static
	Disable building static library variant
--HEAD
	Install HEAD version
kaos:openMVS_build sam$ brew info eigen
eigen: stable 3.3.1 (bottled), HEAD
C++ template library for linear algebra
https://eigen.tuxfamily.org/
/usr/local/Cellar/eigen/3.3.1 (486 files, 6.4M) *
  Poured from bottle on 2016-12-24 at 12:24:22
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/eigen.rb
==> Dependencies
Build: cmake ✔
==> Options
--universal
	Build a universal binary
--HEAD
	Install HEAD version
kaos:openMVS_build sam$ brew info opencv
homebrew/science/opencv: stable 2.4.13.2 (bottled), HEAD
Open source computer vision library
http://opencv.org/
/usr/local/Cellar/opencv/2.4.11_1 (258 files, 34.8M)
  Poured from bottle on 2015-06-11 at 17:14:57
/usr/local/Cellar/opencv/2.4.12_2 (261 files, 35.6M) *
  Poured from bottle on 2016-10-13 at 17:05:05
From: https://github.com/Homebrew/homebrew-science/blob/master/opencv.rb
==> Dependencies
Build: cmake ✔, pkg-config ✔
Required: jpeg ✔, libpng ✔, libtiff ✔
Recommended: eigen ✔, openexr ✔, homebrew/python/numpy ✘
Optional: jasper ✘, gstreamer ✘, libdc1394 ✘, openni ✘, tbb ✔, vtk ✘, ffmpeg ✘
==> Requirements
Optional: cuda ✘, java ✔
==> Options
--c++11
	Build using C++11 mode
--universal
	Build a universal binary
--with-cuda
	Build with cuda support
--with-ffmpeg
	Build with ffmpeg support
--with-gstreamer
	Build with gstreamer support
--with-jasper
	Build with jasper support
--with-java
	Build with Java support
--with-libdc1394
	Build with libdc1394 support
--with-opengl
	Build with OpenGL support
--with-openni
	Build with openni support
--with-quicktime
	Use QuickTime for Video I/O
--with-tbb
	Enable parallel code in OpenCV using Intel TBB
--with-vtk
	Build with vtk support
--with-ximea
	Build with XIMEA support
--without-eigen
	Build without eigen support
--without-numpy
	Use your own numpy instead of Homebrew's numpy
--without-opencl
	Disable GPU code in OpenCV using OpenCL
--without-openexr
	Build without openexr support
--without-python
	Build without python support
--without-test
	Build without accuracy and performance tests
--HEAD
	Install HEAD version
kaos:openMVS_build sam$ brew info cgal
cgal: stable 4.9 (bottled)
CGAL: Computational Geometry Algorithm Library
https://www.cgal.org/
/usr/local/Cellar/cgal/4.9 (2,974 files, 31.8M) *
  Poured from bottle on 2016-12-23 at 19:43:06
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cgal.rb
==> Dependencies
Build: cmake ✔
Required: mpfr ✔, boost ✔, gmp ✔
Optional: qt5 ✘, eigen ✔
==> Options
--c++11
	Build using C++11 mode
--with-eigen
	Build with Eigen3 support
--with-lapack
	Build with LAPACK support
--with-qt5
	Build ImageIO and QT5 compoments of CGAL
kaos:openMVS_build sam$ brew info ceres-solver
homebrew/science/ceres-solver: stable 1.12.0 (bottled), HEAD
C++ library for large-scale optimization
http://ceres-solver.org/
/usr/local/Cellar/ceres-solver/1.12.0 (460 files, 15.7M) *
  Built from source on 2016-12-24 at 12:28:53
From: https://github.com/Homebrew/homebrew-science/blob/master/ceres-solver.rb
==> Dependencies
Required: cmake ✔, glog ✔, gflags ✔, eigen ✔, metis ✔
Recommended: suite-sparse ✔
==> Options
--without-suite-sparse
	Build without suite-sparse support
--without-test
	Do not build and run the tests (not recommended).
--HEAD
	Install HEAD version

### Steps to reproduce the problem
cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="$main_path/vcglib" -DCMAKE_C_COMPILER=/usr/local/Cellar/gcc/6.3.0/bin/gcc-6 -DCMAKE_CXX_COMPILER=/usr/local/Cellar/gcc/6.3.0/bin/g++-6 -DVCG_ROOT="$main_path/vcglib"
make

Sorry about the bother this is the first time I have come to use OpenMVS, I thought the installation would go more smoothly.

But it seems eigen 3.3.1 was released less than 20 days ago and it not yet hardened, but it is considered stable in brew.

**Comment by cdcseacave** [comment]
Sorry for installation problem. You are not the first one reporting this problem, but nobody found a solution yet. Not sure what is the issue, the older versions of Eigen work as expected, but with the new release this abstract error message appear. If you do not have deep experience in Eigen in order to fix this issue, please use an older version.

**Comment by samhodge** [comment]
I am unable to use an older version of eigen with brew install system as far as I know.

Maybe some other users will have a better idea.

I wrestled with putting on a deprecated version of eigen for a number of hours before submitting this ticket.

**Comment by pmoulon** [comment]
Since Eigen is an header only library you can download an old version and specify to OpenMVS to use it by using -DEIGEN_INCLUDE_DIR="YOUR_PATH"

**Comment by cdcseacave** [comment]
This was an issue in Eigen 3.3.0 to 3.3.2, fixed now in 3.3.3

**Comment by samhodge** [comment]
OK I will give this another try. I was trying to install on a fresh machine on the weekend.
