### ISSUE TITLE
stlplus redefinition error

### ISSUE THREAD

**Issue by vivzqs** [cdcseacave/openMVS#17]
openMVG/third_party/stlplus3/filesystemSimplified/file_system.hpp
openmvs\src\libs\common\FileUtil.h

error C2572: 'stlplus::folder_delete' : redefinition of default parameter : parameter 2
error C2572: 'stlplus::folder_up' : redefinition of default parameter : parameter 2	
error C2572: 'stlplus::lookup' : redefinition of default parameter : parameter 3

**Comment by vivzqs** [comment]
I have modified file_system.hpp and compiled successfully.

However, when I try the program, it will crash quickly. My runtime library is "Multi-threaded DLL (/MD)", any problem with this option?

**Comment by pmoulon** [comment]
You can also add the following line in build/Utils.cmake (l446)
```
add_extra_compiler_option(-fpermissive)
```

**Comment by cdcseacave** [comment]
Those files are not needed, I removed them, just pull the changes.
