### ISSUE TITLE
Mesh.cpp compilation failure (due to JumpingPos in new vcglib?)

### ISSUE THREAD

**Issue by PolarNick239** [cdcseacave/openMVS#172]
Ubuntu 16.04

Compilation fails with errors:
```
/home/polarnick/mesh/openmvs/openMVS/libs/MVS/Mesh.cpp: In member function ‘void MVS::Mesh::Clean(float, float, bool, unsigned int, unsigned int, bool)’:
/home/polarnick/mesh/openmvs/openMVS/libs/MVS/Mesh.cpp:1092:5: error: ‘JumpingPos’ is not a member of ‘vcg::face’
     vcg::face::JumpingPos<CLEAN::Face> p(start, vi->cVFi(), &*vi);
     ^
/home/polarnick/mesh/openmvs/openMVS/libs/MVS/Mesh.cpp:1092:38: error: expected primary-expression before ‘>’ token
     vcg::face::JumpingPos<CLEAN::Face> p(start, vi->cVFi(), &*vi);
                                      ^
/home/polarnick/mesh/openmvs/openMVS/libs/MVS/Mesh.cpp:1092:65: error: ‘p’ was not declared in this scope
     vcg::face::JumpingPos<CLEAN::Face> p(start, vi->cVFi(), &*vi);
                                                                 ^
```

Checking out vcglib to 31 July 2016 seems to fix this (```git checkout b42e3ed7fa1a3861fd35060d40e8cbfe58278100```)

**Comment by FuchtelJockel** [comment]
I have the same issue on Arch Linux
The `git checkout b42e3ed7fa1a3861fd35060d40e8cbfe58278100` method fixed some issues but I still get:
`/home/alexander/Dokumente/build/src/openmvs/libs/MVS/DepthMap.cpp:174:49:   required from here
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:840:30: Fehler: falsche Benutzung des unvollständigen Typs »struct Eigen::internal::enable_if<false, SEACAVE::TPoint3<double> >«
In file included from /usr/include/eigen3/Eigen/Core:341:0`
and
`/home/alexander/Dokumente/build/src/openmvs/libs/MVS/DepthMap.cpp:174:49:   required from here
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:851:30: Fehler: falsche Benutzung des unvollständigen Typs »struct Eigen::internal::enable_if<false, SEACAVE::TPoint3<double>*>«
In file included from /usr/include/eigen3/Eigen/Core:341:0`
or
`/home/alexander/Dokumente/build/src/openmvs/libs/MVS/Camera.cpp:187:59:   required from here
/usr/include/eigen3/Eigen/src/Core/Matrix.h:296:31: Fehler: keine passende Funktion für Aufruf von »Eigen::Matrix<double, 3, 1>::_init1(const SEACAVE::TPoint3<double>&)«
       Base::template _init1<T>(x);`
and more.
I tried compiling it with eigen 3.3.2
This is my build file: [PKGBUILD](https://github.com/cdcseacave/openMVS/files/750928/PKGBUILD.txt)

**Comment by cdcseacave** [comment]
@PolarNick239 please add `#include <vcg/simplex/face/jumping_pos.h>` in Mesh.cpp
@FuchtelJockel your issue is not the same, please use Eigen 3.2.x

**Comment by PolarNick239** [comment]
Yes, it works, thanks! :)
