### ISSUE TITLE
Compilation issue on MacOSX

### ISSUE THREAD

**Issue by siddharthsrivastava** [cdcseacave/openMVS#175]
I am trying to compile openMVS on Mac OSX Sierra. While doing make & make install,following error occurs:

> In file included from /usr/local/include/eigen3/Eigen/Core:432:
> /usr/local/include/eigen3/Eigen/src/Core/Matrix.h:296:22: error: no matching member function for call to '_init1'
>       Base::template _init1<T>(x);

The errors are generated at the following lines:

> .../3dmodel/openMVS/libs/MVS/Camera.cpp:187:48: note: in instantiation of function template
>       specialization 'Eigen::Matrix<double, 3, 1, 0, 3, 1>::Matrix<SEACAVE::TPoint3<double> >' requested here
>         eT = ((const Matrix3x3::EMat)R) * (-((const Point3::EVec)C)); //3x1

and 

> /3dmodel/openMVS/libs/MVS/Camera.cpp:185:7: note: in instantiation of function template
>       specialization 'Eigen::Matrix<double, 3, 3, 1, 3, 3>::Matrix<SEACAVE::TRMatrixBase<double> >' requested here
>         eM = (const Matrix3x3::EMat)R;

I also searched over web and it seems [to be a problem with latest version of Eigen](https://github.com/Kitware/kwiver/pull/55)

My Eigen version is 3.3.1

Can anyone help me in replacing the above mentioned snippets of code to be compatible with the latest version ?

**Comment by rperrot** [comment]
The easier approach is to get eigen 3.2.1 using hg then specifying correct eigen version in cmake (using -DEIGEN_ROOT=... )

**Comment by cdcseacave** [comment]
A solution is well suggested by @rperrot. However in Eigen version 3.3.3 they fixed these errors. So feel free to either downgrade or upgrade Eigen version.
