### ISSUE TITLE
ReconstructMesh.exe  crash

### ISSUE THREAD

**Issue by sunguangjiang** [cdcseacave/openMVS#177]
### win10 X64 and VS2013
    openMVG 1.1
    openMVS latest

### Steps to ReconstructMesh.exe  crash
:#9. Reconstruct the mesh
15:21:31 [App     ] Build date: Feb  8 2017, 13:45:15
15:21:31 [App     ] CPU: Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
15:21:31 [App     ] RAM: 11.93GB Physical Memory 128.00TB Virtual Memory
15:21:31 [App     ] OS: Windows 8 x64
15:21:31 [App     ] SSE & AVX compatible CPU & OS detected
15:21:31 [App     ] Command line: D:\1234567\mvs/scene_dense.mvs -w D:\1234567\mvs
15:21:33 [App     ] Scene loaded (2s516ms):
        11 images (11 calibrated) with a total of 15.81 MPixels (1.44 MPixels/image)
        1295919 points, 0 vertices, 0 faces
15:21:59 [App     ] Delaunay tetrahedralization completed: 1295919 points -> 1023113 vertices, 6644424 (+216) cells, 13288956 (+324) faces (24s991ms)
15:22:31 [App     ] Delaunay tetrahedras weighting completed: 6644640 cells, 13289280 faces (31s617ms)

**VS2013 debug to:**
openMVS\libs\MVS\SceneReconstruct.cpp:
float computePlaneSphereAngle(const delaunay_t& Tr, const facet_t& facet)
{
	// compute facet normal
	if (Tr.is_infinite(facet.first)) return 1;
	const triangle_vhandles_t tri(getTriangle(facet.first, facet.second));
	**const Point3f v0(CGAL2MVS<float>(tri.verts[0]->point()));
	const Point3f v1(CGAL2MVS<float>(tri.verts[1]->point()));
	const Point3f v2(CGAL2MVS<float>(tri.verts[2]->point()));**
	const Point3f fn((v1-v0).cross(v2-v0));
tri.verts[0] is Null

**Comment by cdcseacave** [comment]
I was not able to reproduce this issue. Could you provide a debugging sample?

**Comment by sunguangjiang** [comment]
https://drive.google.com/open?id=0B4QHg_Tx6qLJVjZCMHNjbzA2dTA
This is I compiled exe with images.

**Comment by cdcseacave** [comment]
It does not crash on my PC, here is the result:
![image](https://cloud.githubusercontent.com/assets/2802670/24143884/e8a6b8d8-0e33-11e7-9e4a-f2da15808df3.png)

**Comment by sunguangjiang** [comment]
[https://drive.google.com/file/d/0B4QHg_Tx6qLJNmQ0Yjc5aFRIeHM/view?usp=sharing](url)

**Comment by sunguangjiang** [comment]
![20170321203843](https://cloud.githubusercontent.com/assets/2938804/24155328/7de67a46-0e8e-11e7-91a6-4fa3019fe1d3.jpg)

**Comment by sunguangjiang** [comment]
I used to give your exe running, and result in the two computers are the same

**Comment by cdcseacave** [comment]
You might need more RAM.

**Comment by sunguangjiang** [comment]
My memory is 12 g and unused
