### ISSUE TITLE
Using openMVS as a third party library

### ISSUE THREAD

**Issue by rajasjoshi** [cdcseacave/openMVS#179]
I tried following steps similar to those in the openMVG page (https://github.com/openMVG/openMVG/blob/master/BUILD#L127). But this doesn't create the folder share in the openMVS_install directory which has to be used when running cmake on my project that uses openMVS as a third party library. 

eg: cmake -DOpenMVG_DIR:STRING="/home/rajas/Software/openMVG_Build/openMVG_install/share/openMVG/cmake" -DCMAKE_BUILD_TYPE=RELEASE . ../HelloWorld

This is how it was done to use openMVG as a third party lib. Is there any similar way to do the same for openMVS? TIA

**Comment by cdcseacave** [comment]
I do not understand the question. To use OpenMVS as a library, simply run `make install` and include the files you need in your project.

**Comment by rajasjoshi** [comment]
I was referring to this particular line from the link above, under "Using OpenMVG as a third party library dependency in cmake":

***
Specify to CMAKE where OpenMVG have been installed by using the cmake OpenMVG_DIR variable that must point to:
-DOpenMVG_DIR:STRING="YourInstallPath"/share/openMVG/cmake

***

I'm trying to create an executable for my project and needed to link the cmake for openMVS. 

While following the steps in the link for a similar requirement from openMVG, after building openMVG locally (by specifying a path for "-DCMAKE_INSTALL_PREFIX" while running the cmake command), it generated a directory with 4 folders: bin, include, libs and share. 
This share folder's openMVG's cmake is then to be specified to the OpenMVG_DIR variable.

I am looking for a cmake file like above in openMVS that I can link in the cmake for my project.

**Comment by cdcseacave** [comment]
* OpenMVS does not depend on OpenMVG
 * OpenMVS cmake config file is installed by default in /usr/local/cmake

**Comment by rajasjoshi** [comment]
Found it in /usr/local/lib/CMake. Thanks a lot for the help..

**Comment by rajasjoshi** [comment]
Hi,

So going to the very basic, I tried writing a simple Hello World program with an extra statement- #include<MVS.h> and tried compiling it instead of creating an executable as before. During compilation, I got scores of warnings and errors. Some of them were as follows:

```
In file included from /usr/local/include/OpenMVS/Common/Types.h:357:0,
                 from /usr/local/include/OpenMVS/Common/Common.h:176,
                 from /usr/local/include/OpenMVS/MVS.h:39,
                 from HelloWorld.cpp:3:
/usr/local/include/OpenMVS/Common/Strings.h:198:20: error: ‘hash’ is not a class template
 template <> struct hash<SEACAVE::String> : public hash<string>{};
                    ^
/usr/local/include/OpenMVS/Common/Strings.h:198:55: error: expected ‘{’ before ‘<’ token
/usr/local/include/OpenMVS/Common/Strings.h:198:55: error: expected unqualified-id before ‘<’ token

/usr/local/include/OpenMVS/Common/List.h: In member function ‘void SEACAVE::cList<TYPE, ARG_TYPE, useConstruct, grow, IDX_TYPE>::ForEachRef(const Functor&) const’:
/usr/local/include/OpenMVS/Common/List.h:965:14: error: ‘ptr’ does not name a type
   FOREACHPTR(ptr, *this)
              ^
/usr/local/include/OpenMVS/Common/List.h:965:14: error: expected ‘;’ before ‘ptr’
   FOREACHPTR(ptr, *this)
              ^
```
Many such warnings/errors popped up, most of them repetitive. I also specified paths for the openMVS include and Eigen include while compiling so there were no more linking errors. Also, while installing openMVS (in the cmake step), I had -DBUILD_SHARED_LIBS=ON. What could have been the problem here? I couldn't comprehend the source of the errors. TIA.

**Comment by rajasjoshi** [comment]
Everything's working fine now, the errors were because a couple libraries hadn't been linked properly. Thanks.

**Comment by satyajitghana** [comment]
@rajas-j what was going wrong? I'm trying a similar thing and its not working. I get similar errors and I'm using the Dockerfile of openMVS
