### ISSUE TITLE
ReconstructMesh taking forever

### ISSUE THREAD

**Issue by mardy** [cdcseacave/openMVS#180]
### Specifications like the version of the project, operating system, and hardware
OpenMVS built from git (commit fa0c2d8be6847d3185827f650ce7a202bb8a44e1) running on Ubuntu 16.04.

### Steps to reproduce the problem
Running ReconstructMesh on a sparse model works. However, running it on the dense model seems to never end (it's been a few hours already). The application uses all 8 cores for about a minute, then it continues using a single core, apparently forever:
```
$ ReconstructMesh --max-threads 8 openmvs/scene_dense.mvs 
22:25:20 [App     ] Build date: Feb  8 2017, 08:46:24
22:25:20 [App     ] CPU: AMD FX-8370 Eight-Core Processor               
22:25:20 [App     ] RAM: 15.64GB Physical Memory 7.45GB Virtual Memory
22:25:20 [App     ] OS: Linux 4.4.0-62-generic (x86_64)
22:25:20 [App     ] SSE & AVX compatible CPU & OS detected
22:25:20 [App     ] Command line: --max-threads 8 openmvs/scene_dense.mvs
22:25:30 [App     ] Scene loaded (10s165ms):
	30 images (23 calibrated) with a total of 116.05 MPixels (5.05 MPixels/image)
	8044160 points, 0 vertices, 0 faces
22:27:09 [App     ] Delaunay tetrahedralization completed: 8044160 points -> 6382652 vertices, 41241162 (+274) cells, 82482461 (+411) faces (1m35s37ms)
```
If this is normal, it would be better to show some progress indicator, to make it clear that the computation is going on.

**Comment by cdcseacave** [comment]
No, this is not normal. Is this happening on all datasets?

**Comment by mardy** [comment]
I just tried on another reconstruction, and I get the same problem.

[gdb.txt](https://github.com/cdcseacave/openMVS/files/786962/gdb.txt)

I attached to the program with gdb and here's the backtrace for all threads. I ran it a few times (notice when the log says "Continuing.") to help you identify whether the code is stuck in a loop or doing something useful.

**Comment by mardy** [comment]
For the record, I'm using VCG at commit a306cdf07738d735e86d9f0fd84d46459c1405c5. I wonder if this bug might be related to https://github.com/cnr-isti-vclab/vcglib/issues/12 ?
Which version/commit of VCG do you recommend?

**Comment by cdcseacave** [comment]
Yes, VCG has some bugs, but not related to this case. Can you try compiling OpenMVS with `-march=x86-64` instead of `native` or something else?

**Comment by mardy** [comment]
Hi! I did it, but it still gets stuck. :-(

**Comment by cdcseacave** [comment]
I used to have a similar problem on Windows, and the cause was CGAL. Are you using a package or do you compile CGAL yourself? Make sure you compile it as instructed on their website, it is sensitive to floating precision setting.

**Comment by mardy** [comment]
I'm using cgal from ubuntu 16.04. I had a look at their website, but I didn't notice specific advise on how to build in on amd64.

**Comment by cdcseacave** [comment]
The CGAL package from Ubuntu is fine. Send me a test dataset to debug (the smallest possible).

**Comment by mardy** [comment]
The size of the mvs file is 135 MB. Should I upload it somewhere?
I'v obtained it by running the openMVG chain with [these images](https://github.com/rperrot/ReconstructionDataSet/tree/master/MirebeauStHilaireStatue).

**Comment by mardy** [comment]
For the record, I experienced the same problem on the same dataset on another machine (this time an intel i7 with no AVX extensions). Did you have time to verify if this dataset works for you?

**Comment by cdcseacave** [comment]
ok, I'll try, however I do not have time right now

**Comment by robeastham** [comment]
Seems I'm having similar issues. Mesh reconstruction works from the sparse scene.mvs, but I've just been waiting for dense_scene.mvs for nearly two hours and I just get stuck at:

"Delauny tetrahedralization completed"

... stage with all 6 cores pegged at 100%. I never kick on to the next step which should be the weighting step. My understanding is that this next "Delauny tetrahedras weighting completed" stage should show up in seconds or minutes and not hours. So something is amiss. 

I know this doesn't help move this issue forward. But I just thought report similar behaviour. Not sure where to start looking, but will try if pointed in the right direction.

I'm on Ubuntu 16.04 too.

**Comment by mrbemani** [comment]
Yea, I'm having the same problem with ReconstructMesh, just stuck at Delauny tetrahedralization completed. Not always, but it happens alot.

**Comment by TrevinGJ** [comment]
I'm having the same issue.

**Comment by stereoa** [comment]
I am also having this issue. I've tried in the time I have to narrow it down. Is there any useful info I can provide? Thank you for all your work @cdcseacave.

**Comment by TrevinGJ** [comment]
I have since gotten around this issue by reverting to CGAL 4.7. I was previously using CGAL 4.9.

**Comment by stereoa** [comment]
@TrevinGJ Thank you! I will try this right now and report back!

In the meantime, I have added more debug logging to this fork:
https://github.com/stereoa/openMVS

Please forgive me for any incorrect assumptions, I am a math and C++ noob.
When running, the process gets stuck (I think, I may be printing the value incorrectly) here:
https://github.com/stereoa/openMVS/blob/master/libs/MVS/SceneReconstruct.cpp#L925

```
23:13:00 [App     ] Delaunay tetrahedralization completed: 40019777 points -> 34893065 vertices, 232801459 (+226) cells, 465603031 (+339) faces (22m29s450ms)
23:13:00 [App     ] weighting started
23:13:00 [App     ] estimating the size of the smallest reconstructible object
23:14:40 [App     ] testing edge size index #1601212624
23:14:40 [App     ] testing edge size index #1601212624
23:14:40 [App     ] testing edge size index #1601212624
...last message repeats indefinitely

```
It looks like ei is never incrememented so the for loop never exits.

**Comment by stereoa** [comment]
@TrevinGJ I am using 4.7.4 CGAL (same as all the other xenial/16.04 ubuntu users in this thread) as that is what comes with libcgal-dev. I haven't been able to build 4.7.0 yet, but to confirm before I dig too deep is that the version that worked for you?  

@cdcseacave or @anyone Also, I believe there is an error in my output above, as ei and eei are Finite_edges_iterators and I believe that I am only printing out their memory address or something. I tried reading CGAL docs but I'm not sure how to get an "index" or "key" for said iterators. I hope this helps push finding the solution to this issue forward for someone. If so, please share your findings!

**Comment by cdcseacave** [comment]
I was able to reproduce this issue locally and debug. Please find on master the fix and confirm this solves it in your case as well.

**Comment by mardy** [comment]
Hi cdc, I've rebuild openmvs with the latest commit, and indeed it does not crash. However, the machine gets stuck swapping.
```
 3362 mardy     30  10 19,575g 0,011t     48 D   4,3 94,1  40:04.97 ReconstructMesh
```
I've got 12GB allocated to this VM, and the mesh is relatively simple. Here's the output:
```
$ openmvs.ReconstructMesh scene_dense.mvs
libdc1394 error: Failed to initialize libdc1394
12:43:07 [App     ] Build date: Mar 15 2017, 11:57:05
12:43:07 [App     ] CPU: AMD FX-8370 Eight-Core Processor               
12:43:07 [App     ] RAM: 11.56GB Physical Memory 8.00GB Virtual Memory
12:43:07 [App     ] OS: Linux 4.4.0-66-generic (x86_64)
12:43:07 [App     ] SSE & AVX compatible CPU & OS detected
12:43:07 [App     ] Command line: scene_dense.mvs
12:43:25 [App     ] Scene loaded (18s407ms):
	22 images (22 calibrated) with a total of 110.29 MPixels (5.01 MPixels/image)
	10493734 points, 0 vertices, 0 faces
12:46:09 [App     ] Delaunay tetrahedralization completed: 10493734 points -> 8809110 vertices, 58481956 (+286) cells, 116964055 (+429) faces (2m38s426ms)
12:51:12 [App     ] Delaunay tetrahedras weighting completed: 58482242 cells, 116964484 faces (5m1s506ms)
```

Is it normal that so much memory is required, or is there a leak somewhere?

**Comment by cdcseacave** [comment]
The amount of memory depends on the number of input points for 10M points you need around 16GB memory with the default settings. You have these options:
- densify with `--resolution-level 2` or higher
- reconstruct mesh with `-d 4` or higher
- buy more memory
- contribute to OpenMVS with a scalable mesh reconstruction algorithm
:)

**Comment by stereoa** [comment]
Just wanted to report that I'm not MIA. Work and hardware issues have me delayed on testing this. Will try to report back ASAP.

**Comment by stereoa** [comment]
This fixed the issue for me! Thank you so much @cdcseacave!

```
05:51:09 [App     ] Build date: Mar 16 2017, 20:05:15
05:51:09 [App     ] CPU: Six-Core AMD Opteron(tm) Processor 8435
05:51:09 [App     ] RAM: 31.48GB Physical Memory 31.99GB Virtual Memory
05:51:09 [App     ] OS: Linux 4.4.0-66-generic (x86_64)
05:51:09 [App     ] warning: no AVX compatible CPU or OS detected
05:51:09 [App     ] Command line: scene_dense.mvs -w output/handCarvedBuddah
05:51:26 [App     ] Scene loaded (16s769ms):
        157 images (144 calibrated) with a total of 153.77 MPixels (1.07 MPixels/image)
        8436608 points, 0 vertices, 0 faces
Points inserted 8436608 (100%, 2m652ms)
05:53:43 [App     ] Delaunay tetrahedralization completed: 8436608 points -> 7625706 vertices, 50348198 (+200) cells, 100696496 (+300) faces (2m13s385ms)
Points weighted 7625706 (100%, 2m19s208ms)
05:56:42 [App     ] Delaunay tetrahedras weighting completed: 50348398 cells, 100696796 faces (2m56s626ms)
06:06:16 [App     ] Delaunay tetrahedras graph-cut completed (1.28367e+07 flow): 1822301 vertices, 3644139 faces (9m33s909ms)
06:07:12 [App     ] Mesh reconstruction completed: 1822400 vertices, 3643795 faces (15m46s16ms)
```

I get no scene_dense_mesh.mvs output though, :(; I will dig deeper to find out why. Thank you again!

**Comment by prakruti** [comment]
Hi, 

Thanks for your work on OpenMVS.

This is still a problem for me. 
I am calling ./ReconstructMesh -i input -o output -d 8
 My OpenMVS version is upto date and I have meshed larger clouds in the past. Any other ideas why this may be happening? It just stays stuck on the last line forever.

Thanks!

```
02:42:56 [App     ] Scene loaded from interface format (4s370ms):
	70 images (70 calibrated) with a total of 799.33 MPixels (11.42 MPixels/image)
	265927 points, 0 vertices, 0 faces
Points inserted 265927 (100%, 1s931ms)
02:42:59 [App     ] Delaunay tetrahedralization completed: 265927 points -> 97149 vertices, 538674 (+322) cells, 1077509 (+483) faces (2s20ms)
Points weighted 97149 (100%, 1s783ms)              
02:43:01 [App     ] Delaunay tetrahedras weighting completed: 538996 cells, 1077992 faces (2s175ms)
```

**Comment by cdcseacave** [comment]
Is this problem happening only on this dataset? If yes, please share it for debuging. Normally the max flow should take a couple of seconds for this case.

**Comment by prakruti** [comment]
Hi, 

@cdcseacave I'll send it to you via email. Is that okay? 
Thanks!

**Comment by cdcseacave** [comment]
No, probably that will not work, please share a link. And you didn't answer my question.

**Comment by prakruti** [comment]
Hi,
@cdcseacave Apologies for the delayed reply.
This dataset of 70 images is a subset of a larger dataset of 1026 images. I successfully ran reconstruct mesh on the larger dataset of 1026 images a while back but cannot figure out why it gets stuck on a considerably smaller dataset. 

I am using OpenMVG in conjunction with OpenMVS and the scene.mvs file called in 

./ReconstructMesh -i scene.mvs -o scene_mesh.mvs

 was created using OpenMVG. Could this be the problem? It has worked well in the past though.

The dataset can be found [https://drive.google.com/drive/folders/0BxkNgfs2dxuXbjhDYlhEUUd0Nkk?usp=sharing](here)

Thank you for your help!

**Comment by cdcseacave** [comment]
I just submitted the fix for your issue. The problem is caused by using Geo-referenced coordinate system, which mean huge numbers for the 3D points that cause all kind of problems, including subtle instabilities for most of the algorithms, resulting in decrease performance/quality. You will notice that with this fix the mesh reconstruction works, but the final smoothing pass distorts the mesh (instead of smoothing it), caused in this case by numerical instability in the VCG library.

**Comment by prakruti** [comment]
I see. Thank you. I suppose I can side-step this issue by changing the coordinate frame to more manageable values.

**Comment by rennu** [comment]
Hi,

I was about to submit a bug report regarding to issue #191 but it seems this this fixed the problem for me. Thanks!

**Comment by nick0622** [comment]
I am facing the same issue. 
From the above discussion, I still don't know how to fix this problem.

I am using  Ubuntu 22.04.4,  libcgal-dev Version: 5.4-1

![image](https://github.com/cdcseacave/openMVS/assets/87253320/50a9c4bd-b448-4902-b58c-7a25327df34c)

**Comment by cdcseacave** [comment]
first of all why using WSL and not directly on windows
second, you seem to have little RAM, consider installing more ram
