### ISSUE TITLE
DensifyPointCloud,ReconstructMesh,RefineMesh demo crash on my windows 10 PC

### ISSUE THREAD

**Issue by johnzhou1** [cdcseacave/openMVS#188]
### Specifications like the version of the project, operating system, and hardware
https://github.com/cdcseacave/openMVS_sample: use the demo project for test
windows10, ThinkPad S3 Yoga.

### Steps to reproduce the problem
run DensifyPointCloud scene.mvs, every time it will crash.
Logs listed below:
16:36:36 [App     ] Build date: Sep 21 2016, 20:43:31
16:36:36 [App     ] CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
16:36:36 [App     ] RAM: 7.92GB Physical Memory 128.00TB Virtual Memory
16:36:36 [App     ] OS: Windows 10+ x64
16:36:36 [App     ] SSE & AVX compatible CPU & OS detected
16:36:36 [App     ] Command line: scene.mvs

Do I miss something?

**Comment by cdcseacave** [comment]
is there a crash info, message, log, dump, something?

**Comment by johnzhou1** [comment]
I only get the crash info like this:

Unhandled exception at 0x00007FF64B107068 in DensifyPointCloud.exe: Fatal program exit requested.

>	DensifyPointCloud.exe!00007ff64b107068()	Unknown
 	DensifyPointCloud.exe!00007ff64b10d23e()	Unknown
 	DensifyPointCloud.exe!00007ff64b0d5237()	Unknown
 	DensifyPointCloud.exe!00007ff64af7202c()	Unknown
 	[External Code]	
 	DensifyPointCloud.exe!00007ff64b0f7482()	Unknown
 	DensifyPointCloud.exe!00007ff64b08cd36()	Unknown
 	DensifyPointCloud.exe!00007ff64af4ed74()	Unknown
 	DensifyPointCloud.exe!00007ff64af52de7()	Unknown
 	DensifyPointCloud.exe!00007ff64af5297c()	Unknown
 	DensifyPointCloud.exe!00007ff64af4fe32()	Unknown
 	DensifyPointCloud.exe!00007ff64b207ef8()	Unknown
 	DensifyPointCloud.exe!00007ff64b20a73d()	Unknown
 	DensifyPointCloud.exe!00007ff64b1e479d()	Unknown
 	DensifyPointCloud.exe!00007ff64b0d4848()	Unknown

**Comment by johnzhou1** [comment]
Close this issue since no more information can be provided.
