### ISSUE TITLE
Build OpenMVS pass, but DensifyPointCloud/InterfaceMVG/ReconstructMesh/RefineMesh cannot run

### ISSUE THREAD

**Issue by johnzhou1** [cdcseacave/openMVS#189]
### Specifications like the version of the project, operating system, and hardware
Build on Windows 10 with VS2015, ThinkPad S3 Yoga;
newest openmvg/openmvs code

### Steps to reproduce the problem
openmvg can works as expected, but openmvs cannot work,with exe file generated.
compared with my compiled EXEs with openMVS_sample EXEs, the size of my DensifyPointCloud.exe is only 500K, but DensifyPointCloud.exe in openMVS_sample is about 10M.

my setting about openMVS listed:
cotire 1.7.8 loaded.
Boost version: 1.63.0
Found the following Boost libraries:
  iostreams
  program_options
  system
  serialization
Eigen 3.2.10 found (include: D:/InvestigationAndprogram/SFM/OPENMVG/openMVS/eigen)
OpenCV 3.2.0 found (include: D:/InvestigationAndprogram/SFM/OPENMVG/opencv/build_ok;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/include/opencv;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/core/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/flann/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/imgproc/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/ml/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/photo/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/video/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/imgcodecs/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/shape/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/videoio/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/highgui/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/objdetect/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/superres/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/ts/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/features2d/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/calib3d/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/stitching/include;D:/InvestigationAndprogram/SFM/OPENMVG/opencv/sources/modules/videostab/include)
CGAL  found (include: D:/InvestigationAndprogram/SFM/OPENMVG/openMVS/CGAL/include;D:/InvestigationAndprogram/SFM/OPENMVG/openMVS/CGAL/auxiliary/gmp/include)
VCG  found (include: D:/InvestigationAndprogram/SFM/OPENMVG/openMVS/vcglib)
CERES_EIGEN_VERSION: Eigen version 3.2.10
EIGEN_VERSION: Eigen version 3.2.10
Found required Ceres dependency: Eigen version 3.2.10 in D:/InvestigationAndprogram/SFM/OPENMVG/openMVS/eigen
CERES_USES_MINIGLOG: use miniglog status OFF
CERES_USES_GFLAGS: use gflags status ON
glog_DIR: use glog_DIR status glog_DIR-NOTFOUND
glog_DIR: use glog_DIR status @glog_DIR@
GLOG_INCLUDE_DIR: use GLOG INCLUDE DIR status D:/InvestigationAndprogram/SFM/OPENMVG/openMVS/glog/src/windows
Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
Found required Ceres dependency: glog
Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
Found required Ceres dependency: gflags
Found Ceres version: @CERES_VERSION@ installed in: D:/InvestigationAndprogram/SFM/OPENMVG/openMVS/ceres/cmake/Ceres with components: [@CERES_COMPILED_COMPONENTS@]
CERES @CERES_VERSION@ found (include: D:/InvestigationAndprogram/SFM/OPENMVG/openMVS/ceres/cmake/Ceres/include;D:/InvestigationAndprogram/SFM/OPENMVG/openMVS/eigen;D:/InvestigationAndprogram/SFM/OPENMVG/openMVS/glog/src/windows;D:/InvestigationAndprogram/SFM/OPENMVG/openMVS/ceres/cmake/Ceres/include)
----
OpenMVG Find_Package
----
Found OpenMVG version: 1.1.0
Installed in: C:/Program Files (x86)/openMVG
Used OpenMVG libraries: openMVG_image;openMVG_features;openMVG_matching_image_collection;openMVG_kvld;openMVG_multiview;openMVG_lInftyComputerVision;openMVG_system;openMVG_sfm
----
Configuring done

**Comment by johnzhou1** [comment]
The MVS.dll, OpenCV dlls looks like not included in the DensifyPointCloud.exe.
Do they have special settings to loop in all the dependent dlls in DensifyPointCloud.exe and other applications?

And I tried to copy all the depended dlls to system path, it still crash with 0xC0000142, it issue comes from MVS.dll, it looks like MVS.dll is not compiled correctly.

In additional, I compile openMVS with release/win32.

**Comment by cdcseacave** [comment]
the size of the EXE depends usually if the project is build with/without shared libs; I never tried to compiled with shared libs on windows; the demo EXEs are build with static libs.

**Comment by johnzhou1** [comment]
I'll try with static libs

**Comment by cdcseacave** [comment]
Pls update the status of this issue.

**Comment by johnzhou1** [comment]
I rebuild with debug mode, got this information while running DensityPointCloud.exe:
got fatal exception when running.

**Exception Call Stack:**
>	DensifyPointCloud.exe!OSSupportsAVX() Line 572	C++
 	DensifyPointCloud.exe!InitCPU() Line 450	C++
 	DensifyPointCloud.exe!`dynamic initializer for 'SEACAVE::Util::ms_CPUFNC''() Line 62	C++
 	DensifyPointCloud.exe!_initterm(void(*)() * first, void(*)() * last) Line 22	C++
 	[External Code]	

**Break Point:**
		not_supported:
		mov eax, 0; // mark as not supported
014EDC0C  mov         eax,0  
		done:
		mov esi, flag
014EDC11  mov         esi,dword ptr [flag]  
		mov [esi], eax
014EDC14  mov         dword ptr [esi],eax  
	}
	return flag != 0;
014EDC16  cmp         dword ptr [flag],0  
014EDC1A  je          done+14h (014EDC25h)  
014EDC1C  mov         dword ptr [ebp-8],1  
014EDC23  jmp         done+1Bh (014EDC2Ch)  
014EDC25  mov         dword ptr [ebp-8],0  
014EDC2C  mov         al,byte ptr [ebp-8]  
	#else

**the exception occurred at OSSupportsAVX()**

**Comment by johnzhou1** [comment]
In additional, I build with win32(x86)

**Comment by cdcseacave** [comment]
Maybe your system does not support AVX, so when you configure the project in CMake disable AVX support option.

**Comment by johnzhou1** [comment]
The issue disappear after disable AVX check. Thanks a lot!
