### ISSUE TITLE
 Densify point cloud can not run

### ISSUE THREAD

**Issue by nbn555** [cdcseacave/openMVS#190]
### Specifications like the version of the project, operating system, and hardware
Ubuntu 16.10 64bit, HP Envy 15. CPU: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz. RAM: 12.0GB Physical Memory 128.00TB
### Steps to reproduce the problem
#4. Export to openMVS
Scene saved to OpenMVS interface format:
	40 images (40 calibrated)
	1264 Landmarks
#5. Densify point cloud
/usr/local/bin/OpenMVS/DensifyPointCloud: error while loading shared libraries: libMVS.so: cannot open shared object file: No such file or directory
#6. Reconstruct the mesh
/usr/local/bin/OpenMVS/ReconstructMesh: error while loading shared libraries: libMVS.so: cannot open shared object file: No such file or directory
#7. Refine the mesh
/usr/local/bin/OpenMVS/RefineMesh: error while loading shared libraries: libMVS.so: cannot open shared object file: No such file or directory
#8. Texture the mesh
/usr/local/bin/OpenMVS/TextureMesh: error while loading shared libraries: libMVS.so: cannot open shared object file: No such file or directory

Do i make anything wrong?

**Comment by cdcseacave** [comment]
you most probably move manually the binaries, and didn't copy the shared
libs as well
1. either do not move them
2. copy the shared libs as well
3. use make install

**Comment by nbn555** [comment]
Here is all the steps I  build OpenMVS. Can you have a look on this

#OpenMVG, OpenMVS will be installed in home/Projects/oh/MVS
#Open terminal
cd /Projects/oh/MVS
mkdir build
#Ceres (Required)
sudo apt-get install libgoogle-glog-dev libatlas-base-dev libeigen3-dev libsuitesparse-dev
# - However, if you want to build Ceres as a *shared* library, you must
#   add the following PPA:
sudo add-apt-repository ppa:bzindovic/suitesparse-bugfix-1319687
sudo apt-get update
sudo apt-get install libsuitesparse-dev

#clone Ceres
git clone https://ceres-solver.googlesource.com/ceres
cd build
mkdir ceres
cd ceres
cmake ../../ceres
make –j2
sudo make install
#CGAL (Required)
sudo apt-get -y install libcgal-dev libcgal-qt5-dev

#OpenCV (Required)
sudo apt-get -y install libopencv-dev

#MESA (Required)
sudo apt-get –y install mesa-dev

#Boost (Required)
sudo apt-get -y install libboost-iostreams-dev libboost-program-options-dev libboost-system-dev libboost-serialization-dev

#VCGLib (Required)
git clone https://github.com/cdcseacave/VCG.git vcglib

#OpenMVG (Optional)
sudo apt-get install libpng-dev libjpeg-dev libtiff-dev libxxf86vm1 libxxf86vm-dev libxi-dev libxrandr-dev graphviz
git clone --recursive https://github.com/openMVG/openMVG.git
cd build
mkdir openMVG
cd openMVG
current_path=`pwd`
cmake -DCMAKE_BUILD_TYPE=RELEASE . ../../openMVG/src/ -DOpenMVG_BUILD_TESTS=ON -DOpenMVG_BUILD_EXAMPLES=ON  -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$current_path/openMVG_installl
make 
sudo make install

#OpenMVS build
cd ../.. #go back home/Projects/oh/MVS
git clone https://github.com/cdcseacave/openMVS.git openMVS
main_path=`pwd`
cd build
mkdir openMVS
cd openMVS
cmake . ../../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="$main_path/vcglib" -DBUILD_SHARED_LIBS=ON -DCERES_DIR="/usr/local/share/Ceres" -DOpenCV_CAN_BREAK_BINARY_COMPATIBILITY=OFF -DOpenMVG_DIR:STRING="$main_path/build/openMVG/openMVG_install/share/openMVG/cmake/"
make –j2
sudo make install

**Comment by nbn555** [comment]
I also build on Windows as well. But it was not success when run DensifyPointCloud. Here is output
..
..
..
SequentialSfMReconstructionEngine::ComputeResidualsMSE.
        -- #Tracks:     3524
        -- Residual min:        1.95755e-06
        -- Residual median:     0.188017
        -- Residual max:         3.61878
        -- Residual mean:        0.320135

Histogram of residuals:

0       |       14389
0.362   |       3553
0.724   |       1316
1.09    |       522
1.45    |       229
1.81    |       118
2.17    |       54
2.53    |       30
2.9     |       16
3.26    |       16
3.62


 Total Ac-Sfm took (s): 11.7587
...Generating SfM_Report.html
...Export SfM_Data to disk.
#4. Export to openMVS
Scene saved to OpenMVS interface format:
        40 images (40 calibrated)
        3524 Landmarks
#5. Densify point cloud
22:09:04 [App     ] Build date: Feb 17 2017, 16:10:23
22:09:04 [App     ] CPU: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
22:09:04 [App     ] RAM: 11.93GB Physical Memory 128.00TB Virtual Memory
22:09:04 [App     ] OS: Windows 8 x64
22:09:04 [App     ] SSE & AVX compatible CPU & OS detected
22:09:04 [App     ] Command line: --input-file C:\WM\Share\MVS\Teeth_out\mvs/scene.mvs
22:09:04 [App     ] Camera model loaded: platform 0; camera  0; f 1.591x1.591; poses 40
22:09:04 [IO      ] error: unknown image format 'C:/WM/Share/MVS/Teeth_out/mvs/01.png'
22:09:04 [App     ] error: failed loading image header
22:09:04 [App     ] error: failed reloading image 'C:/WM/Share/MVS/Teeth_out/mvs/01.png'
22:09:04 [App     ] error: invalid project
#6. Reconstruct the mesh
22:09:04 [App     ] Build date: Feb 17 2017, 16:10:23
22:09:04 [App     ] CPU: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
22:09:04 [App     ] RAM: 11.93GB Physical Memory 128.00TB Virtual Memory
22:09:04 [App     ] OS: Windows 8 x64
22:09:04 [App     ] SSE & AVX compatible CPU & OS detected
22:09:04 [App     ] Command line: C:\WM\Share\MVS\Teeth_out\mvs/scene_dense.mvs
#7. Refine the mesh
22:09:05 [App     ] Build date: Feb 17 2017, 16:10:23
22:09:05 [App     ] CPU: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
22:09:05 [App     ] RAM: 11.93GB Physical Memory 128.00TB Virtual Memory
22:09:05 [App     ] OS: Windows 8 x64
22:09:05 [App     ] SSE & AVX compatible CPU & OS detected
22:09:05 [App     ] Command line: C:\WM\Share\MVS\Teeth_out\mvs/scene_dense_mesh.mvs
#8. Texture the mesh
22:09:05 [App     ] Build date: Feb 17 2017, 16:10:23
22:09:05 [App     ] CPU: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
22:09:05 [App     ] RAM: 11.93GB Physical Memory 128.00TB Virtual Memory
22:09:05 [App     ] OS: Windows 8 x64
22:09:05 [App     ] SSE & AVX compatible CPU & OS detected
22:09:05 [App     ] Command line: C:\WM\Share\MVS\Teeth_out\mvs/scene_dense_mesh_refine.mvs

**Comment by cdcseacave** [comment]
it seems you build OpenMVS without PNG support.

**Comment by nbn555** [comment]
Could you tell me please how can I build with PNG support. Did I forget to add anything in cmake?

**Comment by pmoulon** [comment]
Seems like you are on windows.
By default OpenMVG must ship PNG.
Take a look to the cmake log and see if `libpng (internal)` is written at the end.

If you are on Linux, just be sure that libpng is present on your install
https://github.com/openMVG/openMVG/blob/master/BUILD#L47

**Comment by WenyinWei** [comment]
Hello guys, I met the problem too and found it easy to settle by recompiling with cmake and compiling again. [Build Tutorial](https://github.com/cdcseacave/openMVS/wiki/Building) has some trouble with cmake on Windows. I used cmake-gui to avoid undistinguishable errors in cmake generating procedure with no need for setting the vcpkg path.

Only need to set the cmake-gui as the following image.
![image](https://user-images.githubusercontent.com/33152225/58378649-e9d95800-7fc9-11e9-90cd-9c89904ed795.png)

![image](https://user-images.githubusercontent.com/33152225/58378657-fc539180-7fc9-11e9-9097-2accaa84bf23.png)

And configure enough times to make sure that the cmake has found you libpng, libjpeg, libtiff and so on.
