### ISSUE TITLE
How to use passthrough option on MvgMvs_Pipeline.py

### ISSUE THREAD

**Issue by jpwhitney** [cdcseacave/openMVS#193]
How can I use the passthrough option? 
@FlachyJoe 
The code says 

> Passthrough:
>   Option to be pass to command lines (remove - in front of option names)
>   e.g. --1 p ULTRA to use the ULTRA preset in openMVG_main_ComputeFeatures

I have tried:
`python 'MvgMvs_Pipeline.py' --1 p HIGH '/home/user1/source' '/home/user1/output'`
But I get the error message.

`MvgMvs_Pipeline_Global.py: error: too few arguments`

**Comment by cdcseacave** [comment]
try using the arguments as you would normally use them, except add the module id first:
`python 'MvgMvs_Pipeline.py' --1 -p HIGH '/home/user1/source' '/home/user1/output'`
