### ISSUE TITLE
Is the MVS format platform-specific?

### ISSUE THREAD

**Issue by mrbemani** [cdcseacave/openMVS#196]
I ran DensifyPointCloud on windows, then ran ReconstructMesh on ubuntu, it gives me an error about the "long" data type has different length on the platform. I had to do openMVG_main_openMVG2openMVS then DensifyPointCloud then ReconstructMesh on ubuntu to make it work.

**Comment by cdcseacave** [comment]
I use Boost Serialization, which is not platform independent.
