### ISSUE TITLE
Exception occur when running DensifyPointCloud.exe in debug mode on Win10

### ISSUE THREAD

**Issue by johnzhou1** [cdcseacave/openMVS#197]
### Specifications like the version of the project, operating system, and hardware
DensifyPointCloud, Debug mode, Win10, Thinkpad S3 Yoga

CallStack:
>	DensifyPointCloud.exe!DepthMapsData::FuseDepthMaps(MVS::PointCloud & pointcloud, bool bEstimateNormal) Line 1358	C++
 	DensifyPointCloud.exe!MVS::Scene::DenseReconstruction() Line 1663	C++
 	DensifyPointCloud.exe!main(int argc, const char * * argv) Line 221	C++
 	[External Code]	

### Steps to reproduce the problem
Steps:
1. build DensifyPointCloud.exe with Debug mode
2. run with sample images(castle)
3. Exception happened at "ASSERT(ISINSIDE(depth, depthData.dMin, depthData.dMax));"

**Comment by cdcseacave** [comment]
Please compile in Release

**Comment by zzxp** [comment]
Have you solved this problem? I want to know specific implementation of the algorithm in openMVS, so I run the DenseReconstruction in debug, then I have encountered the same problem as you.
