### ISSUE TITLE
Compillation error

### ISSUE THREAD

**Issue by F0x06** [cdcseacave/openMVS#20]
**Used branch:** develop

Hi, i fixed this error by replacing "mK" by "K", i'm not sure if this attempt is correct...

Thanks in advance,
F0x.

```
/home/user/src/openMVS/libs/MVS/Camera.h:186:23: error: ‘mK’ was not declared in this scope
```

**Comment by cdcseacave** [comment]
Correct is invK
I'll fix it in the next commit.
Thx
Pe 20.10.2015 13:32, "Kevin Velickovic" <notifications@github.com> a scris:

**Comment by F0x06** [comment]
Perfect it works, thank you :)
