### ISSUE TITLE
Mismatch between dense point cloud and cameras (please close, the openMVG data was faulty)

### ISSUE THREAD

**Issue by ThomasEgi** [cdcseacave/openMVS#200]
### Specifications
git version 4f91c8f , Ubuntu Yakkety (not that it matters), opencv 2.4.9.1

### Steps to reproduce the problem:
running densify point cloud on whatever data set you have.

### The problem:
when running densifyPointCloud the resulting pointcloud and camera positions and rotations do not match. The error is rather significant and prevents further processing if you require pointcloud and image data to be aligned.
![snapshot02](https://cloud.githubusercontent.com/assets/1004882/24822259/0a06e08e-1bf4-11e7-84a5-fce8f1599e2c.png)

My input images are taken with a Canon EOS350D, raw pictures, low iso, aperture tuned down for sharp images (near optimal input images, except from slight distortior). OpenMVG outputs a residual mean of 0.227074 with about 61000 tracks. The Scene gets oriented and calibrated, all distances are in cm-units. Just to rule out some image based problem, the error also occurs on every other source of images i tried including raw jpeg tiff on 4 different cameras.
I run openMVS with --number-views-fuse 5 and -v 5 to get low noise, accurate pointclouds and as much debug data as possible (including the mlp scene).
Loading the mlp in Meshlab reveals a breathtaking accurate point cloud. However the raster layers (cameras) do not match the point cloud. All images are offset by about 20pix horizontally and 40 pixel vertically (measuring in the input images coordinate space).
The same offset can be reproduced when setting up the scene and cameras in blender with the data from the MLP file.
I tried to match the mlp file with the original (un-oriented, uncalibrated openmvg scene). Registering the meshes revealed that the camera positions relative to the meshes are different. I can't tell if the meshes are in different locations or the cameras are, but they don't line up relative to the mesh.

I originally suspected that some transform matrices get messed up upon loading, but this does not seem to be the issue. Also the generated depth maps align perfectly with the input images (if scaled correctly).

Doing more tests on the data delivered by openMVG indicates that both meshes, the openMVG sparse mesh and the dense pointcloud match, same goes for the camera positions. So for now it may be possible that openMVG outputs faulty rotations already. I'll investigate further and report back.

After dealing with this issue for 3 weeks, I found the error and fix within 5 hours after opening this issue. OpenMVG or more specifically IncrementalSfM was trying to optimize the principal point of my camera intrinsics, resulting in a rather silly huge offset. Setting proper parameters on the IncrementalSfM run to only optimize focal length and distortion resulted in a lower overall error, and in perfectly aligned cameras

**Comment by cdcseacave** [comment]
Thanks!

**Comment by pmoulon** [comment]
@ThomasEgi Can you elaborate and say why OpenMVG data is faulty?
On my understanding often using Blender or Meshlab preview with images (camera) is that the camera projection model in those 3d software does not support having a not centered principal point.

So if you want to have a perfect camera,3d data alignement in those software you can constraint the principal point to remains as the image center in OpenMVG pipeline by using `-f ADJUST_FOCAL_LENGTH|ADJUST_DISTORTION` on the OpenMVG SfM pipeline (Incremental or Global).

**Comment by ThomasEgi** [comment]
@pmoulon Valid point. I don't know about Meshlab. Blender certainly support non-center cameras but looking at the script I wrote to position the cameras, the one parameter I did not take into account was indeed the center point. Knowing my camera lens can shift around about 0.1mm horizontally and about 0.2mm vertically in its mount that would explain half of the offset error. The other half is probably static offset from the camera body itself.
About your suggestion to constraint the principal point in openMVG , that's exactly what solved my issue for the moment. But this goes a lot deeper than I initially thought it would.

From my initial thought that the depth maps might be off followed by some transform matrix trouble, via openMVG the origin of the error appears to be the camera itself in combination with some software not respecting all parameters.

@pmoulon @cdcseacave Since I try to set up a smooth and robust workflow/pipeline to do photogrammetry for 3d game assets I encountered many small but important details to take into account. They concern everything from choosing the right camera settings and lighting conditions down to fine-tuning individual parameters of openMVG/MVS. I'd like to write a complete tutorial about how to get the best possible reconstruction results possible. Since it concerns both, openMVG and openMVS I'm not sure where to put this. readthedocs appears to be the primary source of information for openMVG whilst having an empty wiki, openMVS has the github wiki. Taking pictures wouldn't exactly be part of either as well as post processing the data. Is there a good place to put it anyway? like maybe the openMVS wiki as an example of a practical complete reconstruction process (compared to just running openMVS on sample data)

**Comment by cdcseacave** [comment]
A guide describing how to best take pictures for photogrammetry applies to any pipeline and does not depend on OpenMVG / OpenMVS. This is a great project, and when complete, wherever you put it, just add a link to it both to OpenMVG and OpenMVS.
