### ISSUE TITLE
Cuda compilation

### ISSUE THREAD

**Issue by giacomodabisias** [cdcseacave/openMVS#203]
Hi,

I am quite sure the way you are building the library with cuda is wrong. I fixed it on my machine but I would like to know if someone else tried.
You are actually looking for cuda in the main CMakeLists.txt but then you are not linking the library (see Densifypointcloud).
You also set CUDA_CUDA_LIBRARY and then never use it.

Just wanted to know if this is a known issue. If yes I will just fix it

**Comment by gwfraley** [comment]
@giacomodabisias could you share how you were able to build with cuda successfully?

**Comment by giacomodabisias** [comment]
I just linked the libraries were they are used. I will just create a pull request to fix the issue

**Comment by gwfraley** [comment]
@giacomodabisias Thanks! Look forward to seeing your pull request.
