### ISSUE TITLE
How to use OpenMVS if I know the camera intrinsic and extrinsic parameters?

### ISSUE THREAD

**Issue by wguo68** [cdcseacave/openMVS#204]
Suppose I know the camera intrinsic and extrinsic parameters for all images using other SFM tool (not OpenMVG). Can I use these simple info to do MVS without editing complex data format in OpenMVG or OpenMVS ? It seems The OpenMVS ask for sparse points ? And What is the input data format ?

**Comment by cdcseacave** [comment]
please read the wiki (Interface.h)
