### ISSUE TITLE
CUDA kernels source code + OpenCL support

### ISSUE THREAD

**Issue by PolarNick239** [cdcseacave/openMVS#206]
Hi!

1) I wonder why CUDA kernels in SceneRefineCUDA.cpp stored as ptx-assembly without source code? If you didn't upload source code because you had no time to make kernels automatically compiled by nvcc from cmake - I will be glad to help with this.
2) I want to implement SceneRefineOpenCL.cpp, and I will be glad to do so if you will commit source code of CUDA kernels.

And thanks a lot for this project! :)

**Comment by mabrowning** [comment]
So apparently (from [mailing list](https://groups.google.com/d/msg/openmvs/Y9fGuV5cGA8/XVeDpbehDwAJ)), ptx-assembly *is* the native format; there are no C-kernels.

**Comment by PolarNick239** [comment]
Wow, this is impressive :)

**Comment by zoey9628** [comment]
@PolarNick239  Did you implement SceneRefineOpenCL.cpp ? It will help me a lot !!!! thank u !!

**Comment by PolarNick239** [comment]
No, I wasn't able to do so because there are no CUDA code to be ported to OpenCL. And I don't speak ptx :)

**Comment by zoey9628** [comment]
> No, I wasn't able to do so because there are no CUDA code to be ported to OpenCL. And I don't speak ptx :)

Well,  Thank you for your reply, I'll give it a try.
