### ISSUE TITLE
Floating point exception (core dumped)  in ReconstructMesh

### ISSUE THREAD

**Issue by profdunny** [cdcseacave/openMVS#210]
Although I have already checked the issue "Check Points for NaN #169" and uses the modified version, I get similar errors as follows.

### Specifications like the version of the project, operating system, and hardware

Ubuntu 14.04, latest build as of 5/6/2017

### Steps to reproduce the problem

Create mvs from OpenSfM
 - run_all
 - opensfm undistort
 - opensfm export_openmvs
DensifyPointCloud reconstruction.mvs
ReconstructMesh reconstruction_dense.mvs

07:00:40 [App     ] Build date: May  5 2017, 15:14:43
07:00:41 [App     ] CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
07:00:41 [App     ] RAM: 62.84GB Physical Memory 30.52GB Virtual Memory
07:00:41 [App     ] OS: Linux 4.2.0-36-generic (x86_64)
07:00:41 [App     ] SSE & AVX compatible CPU & OS detected
07:00:41 [App     ] Command line: scene_dense.mvs
07:01:07 [App     ] Scene loaded (25s344ms):
        995 images (995 calibrated) with a total of 1482.67 MPixels (1.49 MPixels/image)
        32616141 points, 0 vertices, 0 faces
Points inserted 522404 (1.60%, 6s, ETA 6m)...Floating point exception (core dumped)

**Comment by cdcseacave** [comment]
I saw that error before, and only on Ubuntu 14. Please try Ubuntu 16, as I suspect there is a problem with the old gcc.

**Comment by profdunny** [comment]
Thank you for your quick reply. It works on Ubuntu 16.10 and 17.04 using docker. (The same error happens on Ubuntu 16.04.)
