### ISSUE TITLE
Add GMP and MPFR as deps

### ISSUE THREAD

**Issue by mdaiter** [cdcseacave/openMVS#214]
### Specifications like the version of the project, operating system, and hardware
master branch
### Steps to reproduce the problem
Not really a problem, but I would include MPFR and GMP to the necessary dependencies. It's possible to build the required dependencies without these libraries (look at VCG -- it doesn't *mandate* GMP's installation because it's a header-only install). However, the build will break when including headers from these libraries if the system does not contain an installation of GMP or MPFR.
Here are the dependencies I would include in the README:

1. MPFR
2. GMP
3. GLOG

**Comment by cdcseacave** [comment]
thx, but none of these are openMVS dependencies, but 3rd party libraries dependencies, and their responsibility to include them
