### ISSUE TITLE
merging two MVS models

### ISSUE THREAD

**Issue by ywjia** [cdcseacave/openMVS#215]
Hi,

For a same structure (say a building), I've build two models (i.e., mesh + texture) using openmvg / openmvs, one from a set of aerial photos (S1), and the other from a set of ground-level photos (S2). S1 and S2 have no common images but certainly contain overlapping areas. All the images contain GPS data, but they may not be very reliable. I want to merge these two models into one. 

The first thing I did was to make sure the two models are registered correctly. This was achieved by using GPS non-rigid registration for SfM in openmvg and by using some ground control points to transform S2 model to S1. Viewing together on Meshlab, they look quite accurate (i.e., no apparent discrepancy or outliers).

The second thing I did was to try to combine the two mvs files into one, and I suspect this is where some mistakes were made. The code is shown at the end of this message. Anyway, I was able to generate the combined point cloud and it looks correct and contains details from both models.

Then, I used ReconstructMesh. The resultant mesh looks much less accurate, blurry, and does not contain details from the two original models.

Any help is very much appreciated. 

//// combine two MVS files and dump the combined point cloud

#include "../../libs/MVS/Common.h"
#include "../../libs/MVS/Scene.h"
#include "../../libs/MVS/PointCloud.h"
#include <boost/program_options.hpp>
#include <boost/numeric/ublas/matrix.hpp>

using namespace MVS;

int main(int argc, char* argv[])
{
        if (argc != 5) {
             std::cout <<"usage: "<<argv[0]<< " input_mvs_1 input_mvs_2 output_mvs output_ply" << std::endl;
       		return EXIT_FAILURE;
	}	

	Scene scene_1(0);
	Scene scene_2(0);
	Scene scene_o(0);

	// load input scenes
	if (!scene_1.Load(argv[1]))
		return EXIT_FAILURE;
	if (!scene_2.Load(argv[2]))
                return EXIT_FAILURE;

	// platforms
        int number_of_platforms_1 = scene_1.platforms.size();
        int number_of_platforms_2 = scene_2.platforms.size();
        scene_o.platforms.Resize(number_of_platforms_1 + number_of_platforms_2);
        for(int i=0; i<number_of_platforms_1; i++) {
                scene_o.platforms[i] = scene_1.platforms[i];
        }
	for(int i=0; i<number_of_platforms_2; i++) {
                scene_o.platforms[i+number_of_platforms_1] = scene_2.platforms[i];
        }

	// images
        int number_of_images_1 = scene_1.images.size();
        int number_of_images_2 = scene_2.images.size();
        scene_o.images.resize(number_of_images_1 + number_of_images_2);
	for(int i=0; i<number_of_images_1; i++) {
                scene_o.images[i] = scene_1.images[i];
        }
        for(int i=0; i<number_of_images_2; i++) {
                scene_o.images[i+number_of_images_1] = scene_2.images[i];
		scene_o.images[i+number_of_images_1].platformID += number_of_platforms_1;
        }
       
	// point cloud
	int number_of_points_1 = scene_1.pointcloud.GetSize();
	int number_of_points_2 = scene_2.pointcloud.GetSize();
       	scene_o.pointcloud.points.resize(number_of_points_1 + number_of_points_2);
	scene_o.pointcloud.pointViews.resize(number_of_points_1 + number_of_points_2);
 	scene_o.pointcloud.pointWeights.resize(number_of_points_1 + number_of_points_2);
 	scene_o.pointcloud.colors.resize(number_of_points_1 + number_of_points_2);
	for(int i=0; i<number_of_points_1; i++) {
                scene_o.pointcloud.points[i] = scene_1.pointcloud.points[i];
                scene_o.pointcloud.pointViews[i] = scene_1.pointcloud.pointViews[i];
                scene_o.pointcloud.pointWeights[i] = scene_1.pointcloud.pointWeights[i];
                scene_o.pointcloud.colors[i] = scene_1.pointcloud.colors[i];
        }
	for(int i=0; i<number_of_points_2; i++) {
		scene_o.pointcloud.points[i+number_of_points_1] = scene_2.pointcloud.points[i];
		scene_o.pointcloud.pointViews[i+number_of_points_1] = scene_2.pointcloud.pointViews[i];
    	        for(int j=0; j<scene_2.pointcloud.pointViews[i].size(); j++) {
			scene_o.pointcloud.pointViews[i+number_of_points_1][j] = scene_2.pointcloud.pointViews[i][j] + number_of_platforms_1; 
		}
		scene_o.pointcloud.pointWeights[i+number_of_points_1] = scene_2.pointcloud.pointWeights[i];
		scene_o.pointcloud.colors[i+number_of_points_1] = scene_2.pointcloud.colors[i];
	}

    	// save the merged mvs
    	scene_o.Save(argv[3]);
    	scene_o.pointcloud.Save(argv[4]);

    	return EXIT_SUCCESS;
}

**Comment by cdcseacave** [comment]
First of all, I find your project very interesting. At first I thought you try to tackle the scalability issue by splitting the scene in two, reconstruct separately, and merge back the results (this would be an interesting project as well).

Your merging code is almost correct. Two observations:
 - first of all I'd do the merging in the interface domain (more clear and more general, less chances to miss something); so use LoadInterface() and merge them there and save it back to a merged solution SaveInterface() that you will used with the standard pipeline
 - there is a mistake at line:
`scene_o.pointcloud.pointViews[i+number_of_points_1][j] = scene_2.pointcloud.pointViews[i][j] + number_of_platforms_1;`
correct would be:
`scene_o.pointcloud.pointViews[i+number_of_points_1][j] += number_of_images_1;`

If you share the datasets with me, I can implement and test this merging tool.

**Comment by ywjia** [comment]
Thanks for the spotting the bug in the code. After correcting it, I was able to combine the two mvs models and successfully generate the meshing model and textured model. I will look into how to merge the models in the interface domain as you suggested.

Indeed, this issue has some interesting applications such as divide-modeling-merge or partial updating of existing models. Sure, I can share the datasets with you. Please let me know how to proceed.

**Comment by cdcseacave** [comment]
The quality of the combine model reconstruction will depend a lot on the precision with which the two scenes are aligned.
Just send me a link for downloading the two image datasets, plus the two MVS files, after alignement

**Comment by ywjia** [comment]
@cdcseacave here is the link to the dataset.
https://drive.google.com/drive/folders/0B-dusFhfr3DVVzNKdGdfWHk3Mlk?usp=sharing

**Comment by cdcseacave** [comment]
thx! Everything seems fine. I imagine though that this is more like a test case for a bigger project, as I see no reason here not to reconstruct all images from the beginning together (which will give even better accuracy as the merged model, since during merging not all physical relations are restored).

**Comment by jpwhitney** [comment]
Hi @ywgia I'm trying to do the same thing.   But it looks like you got much further.

 I'm curious what process you used for GCP registration of the two sets.   Could you elaborate?

**Comment by ywjia** [comment]
@jpwhitney For now, I just manually identified several GCPs common to both models and performed a 3D transformation.

**Comment by jpwhitney** [comment]
@ywjia Okay, thanks, that's what I had gathered.  I was more specifically interested in the program or method that you used to perform the 3D transformation.

I can envision the process of finding the GCP's but the next step, "perform a 3D transformation" is still unclear.

**Comment by ywjia** [comment]
@jpwhitney By "3D transform" I just meant the standard 3D conformal coordinate transformation; for example, see the book "Elements of Photogrammetry" (Paul R. Wolf et al), Appendix C.

**Comment by jpwhitney** [comment]
Yes that was clear from the beginning; it seems like you are misinterpreting my question.  I'd like to know "the program or method" used to perform the 3D conformal coordinate transformation.

Thanks for the reference of the book, I'll check with the local library.

**Comment by cdcseacave** [comment]
I think what @ywjia tries to say is that you can compute that transform yourself; however many programs support this functionality (some of them even automatic methods), you can try Meshlab or CloudCompare

**Comment by jpwhitney** [comment]
Thanks @cdcseacave for trying to clarify @ywjia's intent. I have been asking since my first comment on this thread how to, as you say "compute the transform yourself"?

I suppose I should stop asking for specifics on how @ywjia performed this task?  Perhaps it is too simple to explain?

**Comment by cdcseacave** [comment]
it is indeed relatively easy: either implement "Closed-Form Solution of Absolute Orientation Using Unit Quaternions" or use the Eigen library built in function in Umeyama

**Comment by ywjia** [comment]
The transform I used was based on an implementation of the method described (with details) in the book mentioned above.

**Comment by jpwhitney** [comment]
@cdcseacave and @ywjia Thanks for helping to direct me in the right direction.  I'm trying to learn more so I appreciate the recommendations.  Sorry if I hijacked this thread, it would be great to have this capability to add detail to complex scenes in localized areas of interest.

**Comment by ManishSahu53** [comment]
@ywjia I am also trying to combine two mvs file. Does the code written above worked for you? Because Iam getting some compilation error.

**Comment by ManishSahu53** [comment]
Can you tell me the CMakeFile code for this project @ywjia
