### ISSUE TITLE
python 

### ISSUE THREAD

**Issue by dxqxiaoqiang** [cdcseacave/openMVS#217]
when i try to test the sample of openMVS  ,i get the following error 
```
dxq@dxq-great:~/openMVS_sample-master$ python ./MvgMvs_Pipeline.py /home/dxq/ImageDataset_ /home/dxq/8
# Using input dir  :  /home/dxq/ImageDataset_
#       output_dir :  /home/dxq/8
# First step  :  0
# Last step :  11
#0. Intrinsics analysis
Traceback (most recent call last):
  File "./MvgMvs_Pipeline.py", line 236, in <module>
    pStep = subprocess.Popen(cmdline)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
what's wrong with is ?

**Comment by cdcseacave** [comment]
make sure you follow the instructions, in this case to set the correct path to the compiled apps inside py

**Comment by dxqxiaoqiang** [comment]
Can you explain it in detail; i have follow the instructions as you shown us. But i don't know where wrong  i have got?

**Comment by jpwhitney** [comment]
I had this same error at some point, the following is what I did to fix it.

Open the python script in a text editor, find the two lines that specify the path to the openMVG binaries and the openMVS binaries (this is near the beginning of the script).  Change those to reflect the correct path on your machine.

After this correction the script should run fine.

**Comment by dxqxiaoqiang** [comment]
```
dxq@dxq-great:~$ ls
ceres-solver-master  eigen_build   openMVS_sample-master  公共的  视频  下载
cloudsfm-master      ImageDataset  output                 例子    图片  音乐
eigen                open          vcglib                 模板    文档  桌面
dxq@dxq-great:~$ cd open
dxq@dxq-great:~/open$ ls
openMVG  openMVS  openMVS_build
```
i change the "`OPENMVG_BIN = "D:/Pro/OpenMVG/install/bin/"   OPENMVS_BIN = "D:/Pro/OpenMVS/install/bin/"`into `OPENMVG_BIN = "/home/dxq/open/" OPENMVS_BIN = "/home/dxq/open/"` the error is same. Somewhere is wrong? @jpwhitney
