### ISSUE TITLE
Using openMVS with affine cameras

### ISSUE THREAD

**Issue by mdautume** [cdcseacave/openMVS#220]
Hello,

I'm working with images obtained from affine cameras (with satellites typically). 

Therefore the matrix P is singular and I cannot easily decompose it in a matrix K with the camera intrinsics data, a rotation matrix R and a camera center C.

Do you know if it is still possible to use your code ? Is there some way to give it directly the matrix P instead of the matrices K, R and C ?

Thank you very much

**Comment by cdcseacave** [comment]
The code as it is now expects projective cameras. However all modules can work, with some adjustments, in scenarios where the cameras are at infinity. You can have a look at ProjectOrtho() in Mesh.h for an example how to support othographic projection. It is a bit hacky, cause the camera model was not designed for it, but with a bit of work it can be done.

**Comment by mdautume** [comment]
Thank you very much for your fast answer. I will have a look at ProjectOrtho() and see how to make it work with affine camera.
