### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by Ntweat** [cdcseacave/openMVS#224]
I am trying to generate an accurate mesh (as accurate as possible) so I am keeping the resolution at "0" (I don't want it to scale) to get the Dense point cloud

At Reconstruct Mesh stage, the process uses up all of the RAM (16GB) and then slowly fills up the swap too (16GB more). CPU utilization drops from 100% to 1% when it starts using the swap. It never produces the result when it starts using swap, and I always have to restart (I have waited for 2 days also) 

Any ideas?

### Specifications like the version of the project, operating system, and hardware
Latest version of openMVG and openMVS
OS: Ubuntu 16.04 64 bit
Processor : Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
RAM : 16GB HyperX 

### Steps to reproduce the problem
- 30 images of object from Samsung Galaxy S3
- Sparse cloud from openMVG
- DensifyPointCloud of openMVS (with resolution to "0")
- Reconstruct mesh

**Comment by cdcseacave** [comment]
This issue was reported so many times, and each time the answer was the same: currently OpenMVS is not scalable, it can be done, but I do not have time for this right now. If anybody offers to help with the implementation, I can help with guiding.

**Comment by Ntweat** [comment]
@cdcseacave Thank you for your reply
