### ISSUE TITLE
Using colmap dense reconstruction file in OpenMVS

### ISSUE THREAD

**Issue by rennu** [cdcseacave/openMVS#226]
Hi,

Is it possible to use ReconstructMesh to create a mesh from a dense reconstruction made in colmap? I'm able to create a nvm file from the dense reconstruction, however it doesn't include the image names (and maybe some other data too?), so InterfaceVisualSFM outputs nothing.

Thanks!

**Comment by cdcseacave** [comment]
Yes, it is possible, cause as far as I know COLMAP outputs a list of views for each point (needed by OpenMVS). However I do not know exactly how to access all that data. But if you do, all you need is to store it in the `Interface.h` structure and you are done.

**Comment by cdcseacave** [comment]
pls see the solution here #360
