### ISSUE TITLE
Computation of the NCC

### ISSUE THREAD

**Issue by mcphatty** [cdcseacave/openMVS#227]
When computing the NCC in the DepthEstimator you compute the sum of squares for the patches free of their mean. Am I completely wrong here or shouldn't one also subtract the mean from the pixels before the dot product? Otherwise there might be quite a difference in size when dividing the dot product by the rooted sum of squares product?

Sorry if this is a duplicate or if I misunderstood the procedure somehow...

**Comment by cdcseacave** [comment]
ZNCC is used inside DepthEstimator, which is computed with the mean subtracted. Can  you point to the problem line?

**Comment by mcphatty** [comment]
https://github.com/cdcseacave/openMVS/blob/master/libs/MVS/DepthMap.cpp#L338

It seems to me that the pixels in the dot product are not free of their mean, but the values going into the denominator are.

**Comment by cdcseacave** [comment]
normSqZeroMean() is subtracting the mean from each pixel

**Comment by mcphatty** [comment]
Ah I see. Thanks for clarifying!
