### ISSUE TITLE
Reconstruction & Texturing using different image resolutions

### ISSUE THREAD

**Issue by MatillaMartin** [cdcseacave/openMVS#229]
I would like to reconstruct the 3D model using a set of images (enhanced for better feature detection), and then texture it using a different set (realistic images).
It would be straight forward if the sets had the same resolution, but they have different resolutions.
What parameters do I have to modify in the scene to change the input images, but keep the poses&mesh?

**Comment by cdcseacave** [comment]
This is something you have to solve during SfM, OpenMVS do not care about these details.

**Comment by MatillaMartin** [comment]
Wouldnt the enhanced images allow for a better DensifyPointCloud? I would like to introduce the images only for the TextureMesh step

**Comment by cdcseacave** [comment]
That depends on what means "enhanced" images. However, both enhanced and normal images need to me undistorted prior to OpenMVS. So you can simply compute the mesh with the enhanced MVS project, till texturing, and then call `TextureMesh scene.mvs --mesh-file <mesh.ply>` on the normal MVS project with the mesh from the previous step.

**Comment by MatillaMartin** [comment]
Worked perfectly with `TextureMesh scene.mvs --mesh-file <mesh.ply>`. Just had to make sure the SFM pose and camera calibration was exactly the same, but with the new resolution information.
