### ISSUE TITLE
How to build orthophoto and DEM?

### ISSUE THREAD

**Issue by mrgloom** [cdcseacave/openMVS#232]
Can we use `openMVS` to generate orthophoto and DEM? Ideally georeferenced (geotiff).

**Comment by cdcseacave** [comment]
That is more a matter of the SfM pipeline than MVS. Once the textured mesh is generated, you can ortho project it to generate the ortho, and use the geolocalization you got from the SfM step to set the absolute position.

**Comment by mrgloom** [comment]
> you can ortho project it to generate the ortho
Can you suggest any toolchain that can extend openMVS for orthophoto creation?

Also what is `nOrthoMapResolution` parameter about?
https://github.com/cdcseacave/openMVS/blob/9feae5355a90f6c5122a43aaf603e9f49aa825c1/apps/TextureMesh/TextureMesh.cpp#L110

**Comment by cdcseacave** [comment]
OpenMVS can ortho project the textured mesh by setting `nOrthoMapResolution` to the desired ortho image resolution, but this will work only if the scene is already oriented such that `up` corresponds to the `z` axes.
