### ISSUE TITLE
Error using DensifyPointCloud

### ISSUE THREAD

**Issue by bkjohnson** [cdcseacave/openMVS#235]
### Specifications like the version of the project, operating system, and hardware

**Operating System:** Linux Mint 18.2
**openMVS:** 0.7
**Boost:** 1.58.0
**Eigen:** 3.2.10
**OpenCV:** 2.4.9.1
**GCAL:** 4.7
**VCG:** 1.0.1

### Steps to reproduce the problem

I've used the `SfM_GlobalPipeline` from openMVG to create a `sfm_data.bin` file.  After that I ran the following commands:

```
$ openMVG_main_openMVG2openMVS -i sfm_data.bin -o scene.mvs
$ DensifyPointCloud scene.mvs
```

and `DensifyPointCloud` aborts part way through.  It prepared the images (22), selected images (13), estimated depth-maps, and filtered depth-maps seemingly without issue.  However, it aborts in `SceneDensify.cpp` due to a [failed assertion](https://github.com/cdcseacave/openMVS/blob/a5b1cc3dc8d253770d4a0500ff3efdc7084de586/libs/MVS/SceneDensify.cpp#L1358).

Does this mean that there is something wrong with my images, or is it a problem with my pipeline?

**Comment by cdcseacave** [comment]
Pls compile OpenMVS in Release and the assert will go away. But there seems to something wrong with the images too, normally the selected images should be all the input images.

**Comment by bkjohnson** [comment]
Reinstalling seems to have done the trick!  Not quite sure what the deal with the images is.  I'm currently repeating the entire process with a larger set of images, so I'll see what happens.
