### ISSUE TITLE
Question: Export Mesh and texture as one file

### ISSUE THREAD

**Issue by Ntweat** [cdcseacave/openMVS#237]
### Specifications like the version of the project, operating system, and hardware
N/A
### Steps to reproduce the problem
N/A

Is there a way to export the mesh and texture as one ply file (instead of one mesh and one texture file) 

Thanks.

**Comment by pmoulon** [comment]
PLY file format stores only the geometry.
So you can't :-/

**Comment by Ntweat** [comment]
@pmoulon 
Digging up I found the answer. I was looking for baking texture color to vertices color. 
I used meshlab to bake the texture onto the vertices. 
Is there any way to get the mesh that way from export the mesh from openMVS in such a format.

**Comment by cdcseacave** [comment]
no, and I do not recommend such a format, it will look much worse than the mesh plus texture. If you want to convince yourself, use meshlab to extract vertex color from the textured mesh, and export it without texture.
