### ISSUE TITLE
syntax error： missing ‘，’ before  ‘...’ on Visual studio 2010

### ISSUE THREAD

**Issue by MichaleWong** [cdcseacave/openMVS#238]
I compiled the openMVS(version: cdcseacave-openMVS-v0.7-20-g54766b9) on my visual studio 2010 accroding to the page of build wiki, and encounterd many syntax errores, such as  syntax error : missing ',' before '...'; error C2065: 'Args' : undeclared identifier; error C2988: unrecognizable template declaration/definition.

I think it's duo to c++11 support problem on visual studio 2010, but, how can solve it on VS 2010?

=====the detailed build output as follows:======
1>------ Build started: Project: Common, Configuration: Debug x64 ------
1>cl : Command line warning D9025: overriding '/Zm150' with '/Zm170'
1>cl : Command line warning D9002: ignoring unknown option '/arch:SSE3'
1>cl : Command line warning D9002: ignoring unknown option '/arch:SSE3'
1>  Common.cpp
1>D:\code\opencv\sources\modules\core\include\opencv2/core/mat.hpp(1965): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>D:\code\opencv\sources\modules\core\include\opencv2/core/persistence.hpp : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>D:\code\opencv\sources\modules\core\include\opencv2/core/mat.hpp(1965): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>D:\code\opencv\sources\modules\core\include\opencv2/core/utility.hpp : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>D:\code\opencv\sources\modules\core\include\opencv2/core/utility.hpp : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(429): error C2143: syntax error : missing ',' before '...'
1>          d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(1318) : see reference to class template instantiation 'SEACAVE::cList<TYPE,ARG_TYPE,useConstruct,grow,IDX_TYPE>' being compiled
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(430): error C2065: 'Args' : undeclared identifier
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(430): error C2988: unrecognizable template declaration/definition
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(430): error C2059: syntax error : '...'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(439): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(462): error C2988: unrecognizable template declaration/definition
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(462): error C2059: syntax error : 'if'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(463): error C2238: unexpected token(s) preceding ';'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(464): error C2988: unrecognizable template declaration/definition
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(464): error C2059: syntax error : 'if'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(465): error C2238: unexpected token(s) preceding ';'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(466): error C2988: unrecognizable template declaration/definition
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(466): error C2059: syntax error : 'else'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(467): error C2238: unexpected token(s) preceding ';'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(480): error C2143: syntax error : missing ';' before 'inline'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(1321): error C2039: 'NO_INDEX' : is not a member of 'SEACAVE::cList<TYPE,ARG_TYPE,useConstruct,grow,IDX_TYPE>'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(429): error C2143: syntax error : missing ',' before '...'
1>          d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\Hash.h(68) : see reference to class template instantiation 'SEACAVE::cList<TYPE,ARG_TYPE>' being compiled
1>          with
1>          [
1>              TYPE=SEACAVE::cHashTable<Type>::Key,
1>              ARG_TYPE=SEACAVE::cHashTable<Type>::Key
1>          ]
1>          d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\Hash.h(261) : see reference to class template instantiation 'SEACAVE::cHashTable<Type>' being compiled
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(430): error C2065: 'Args' : undeclared identifier
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(430): error C2988: unrecognizable template declaration/definition
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(430): error C2059: syntax error : '...'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(439): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(462): error C2988: unrecognizable template declaration/definition
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(462): error C2059: syntax error : 'if'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(463): error C2238: unexpected token(s) preceding ';'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(464): error C2988: unrecognizable template declaration/definition
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(464): error C2059: syntax error : 'if'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(465): error C2238: unexpected token(s) preceding ';'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(466): error C2988: unrecognizable template declaration/definition
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(466): error C2059: syntax error : 'else'
1>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(467): error C2238: unexpected token(s) preceding ';'
.
.
.
6>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(462): error C2059: syntax error : 'if'
6>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(463): error C2238: unexpected token(s) preceding ';'
6>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(464): error C2988: unrecognizable template declaration/definition
6>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(464): error C2059: syntax error : 'if'
6>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(465): error C2238: unexpected token(s) preceding ';'
6>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(466): error C2988: unrecognizable template declaration/definition
6>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(466): error C2059: syntax error : 'else'
6>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(467): error C2238: unexpected token(s) preceding ';'
6>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(480): error C2143: syntax error : missing ';' before 'inline'
6>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(429): error C2143: syntax error : missing ',' before '...'
6>          d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\Log.h(52) : see reference to class template instantiation 'SEACAVE::cList<TYPE>' being compiled
6>          with
6>          [
6>              TYPE=SEACAVE::Log::ClbkRecordMsg
6>          ]
6>d:\code\cdcseacave-openmvs-v0.7-20-g54766b9\libs\common\List.h(430): error C2065: 'Args' :

**Comment by cdcseacave** [comment]
the code compiles on VC2013 forward, pls upgrade or feel free to patch it to compile
