### ISSUE TITLE
undefined reference to symbol '__gmpq_mul'

### ISSUE THREAD

**Issue by yaustar** [cdcseacave/openMVS#239]
### Specifications like the version of the project, operating system, and hardware
Ubuntu 15.10 (32-bit) on Virtualbox
Branch: ubuntu_15_10

### Steps to reproduce the problem
Currently following the steps to build and run the openMVG GUI found here: https://github.com/open-anatomy/SfM_gui_for_openMVG/blob/master/BUILD_UBUNTU_15_10.md

I've had to make some minor changes to the project as some variable names and the such have changed and now on the last few steps and am a bit stumped. 

I get the following error:

```
[ 22%] Built target Common
[ 32%] Built target Math
[ 62%] Built target IO
[ 91%] Built target MVS
[ 93%] Built target InterfaceVisualSFM
[ 94%] Built target DensifyPointCloud
Linking CXX executable ../../bin/ReconstructMesh
/usr/bin/ld: ../../lib/libMVS.a(SceneReconstruct.cpp.o): undefined reference to symbol '__gmpq_mul'
/usr/lib/i386-linux-gnu/libgmp.so.10: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
apps/ReconstructMesh/CMakeFiles/ReconstructMesh.dir/build.make:134: recipe for target 'bin/ReconstructMesh' failed
make[2]: *** [bin/ReconstructMesh] Error 1
CMakeFiles/Makefile2:663: recipe for target 'apps/ReconstructMesh/CMakeFiles/ReconstructMesh.dir/all' failed
make[1]: *** [apps/ReconstructMesh/CMakeFiles/ReconstructMesh.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

The solutions that I'm looking at are https://github.com/cdcseacave/openMVS/issues/35 and https://stackoverflow.com/questions/8774643/makefile-for-cgal-libcgal8

The latter looking most promising but have no idea where to put that flag in the cmakefiles.

Thanks in advance!

**Comment by cdcseacave** [comment]
`libgmp` is a dependency of CGAL. If you are not sure how to fix CGAL, try compiling and using a newer release directly from sources.
