### ISSUE TITLE
Kubuntu 14.04 install

### ISSUE THREAD

**Issue by lulu1315** [cdcseacave/openMVS#24]
hello I'm in the process of installing openMVG and openMVS on a Kubuntu 14.04 workstation.
I'm following instructions from the building documentation : https://github.com/OpenMVS/openMVS/wiki/Building

for Ceres I installed libsuitesparse-dev (apt-get install libsuitesparse-dev)
btw there is a little typo in your doc : libboost-program_options-dev is libboost-program-options-dev
I didn't find mesa-dev but installed mesa-common-dev instead

now I'm in the process of installing openMVG first and I have some issues/questions 

missing libraries:
-- Did not find MOSEK header
-- Did not find MOSEK library
-- Could not find mosek library on this machine.
-- Could NOT find ILOG (missing:  ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR)
-- Could NOT find SOPLEX (missing:  SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR)
do I need MOSEK, ILOG and SOPLEX ?

Eigen:
-- Eigen 3.2.4 found (include: /mnt/media/Projects/Photogrametry/openMVG/src/third_party/eigen)
-- Failed to find Ceres - Found Eigen dependency, but the version of Eigen found (3.2.4) does not exactly match the version of Eigen Ceres was compiled with (3.2.0). This can cause subtle bugs by triggering violations of the One Definition Rule. See the Wikipedia article http://en.wikipedia.org/wiki/One_Definition_Rule for more details
-- Eigen 3.2.4 found (include: /mnt/media/Projects/Photogrametry/openMVG/src/third_party/eigen)
-- Found Eigen version 3.2.4: /mnt/media/Projects/Photogrametry/openMVG/src/third_party/eigen

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================
I'm a bit confused about eigen.I installed libeigen3-dev as advised..

SuiteSparse:
-- Building without SuiteSparse.
-- Enabling CERES_NO_SUITESPARSE in Ceres config.h
I've installed and compiled Ceres with libsuitesparse-dev so I'm surprised that it's not used here.

I'm more a user than a developer so maybe all these things are not important.
thanks for the good work.
luc

**Comment by lulu1315** [comment]
I compiled openMVS but got a lot of warnings.
the binaries are built but core dumps.
see attached cmake.log and make.log
luc

https://dl.dropboxusercontent.com/u/49687900/openMVS/cmake.txt
https://dl.dropboxusercontent.com/u/49687900/openMVS/make.txt

**Comment by pmoulon** [comment]
Happy to see that you have successfully compiled it.
We keep gcc warning active ... in order to detect all possible tiny pitfall we can make.

So don't worry your compilation ran fine.
I wish you happy experiments
