### ISSUE TITLE
CUDA compilation is broken

### ISSUE THREAD

**Issue by gpanders** [cdcseacave/openMVS#240]
After commit 54766b9 OpenMVS fails to build with the following error:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDA_LIBRARY (ADVANCED)
    linked by target "MVS" in directory /src/openmvs/libs/MVS
```

Reverting 54766b9 fixes the issue and allows OpenMVS to compile normally.

I am building OpenMVS in a Docker container based on the [NVIDIA CUDA Docker image](https://hub.docker.com/r/nvidia/cuda/).

**Comment by cdcseacave** [comment]
since `CUDA_CUDA_LIBRARY` is not set only if `if(CUDA_FOUND)` is true, then there is a problem with the CMake module which should set `CUDA_CUDA_LIBRARY`. Pls make sure you have the latest version of CMake. Ubuntu 16.04 is compiling fine with the default CMake from apt-get.

**Comment by gpanders** [comment]
I am using Ubuntu 16.04 with CMake version 3.5.1 from apt-get

**Comment by gpanders** [comment]
To anyone else who may stumble upon this problem, here was my solution:

- You must use `nvidia-docker` to build the Docker container
- You must add the following cmake flag: `-DCUDA_CUDA_LIBRARY=/usr/local/nvidia/lib64`

**Comment by cdcseacave** [comment]
thx @gpanders
