### ISSUE TITLE
DensifyPointCloud problem: opencv error assertion failed channels() == cv_mat_cn(dtype) in cv::mat::copyto

### ISSUE THREAD

**Issue by MichaleWong** [cdcseacave/openMVS#241]
After using interfaceVisualSFM to transform the *.nvm (visualSfm) to *.mvs, I run the DensifyPointCloud，the step：Estimated depth-maps, Filtered depth-maps Fused depth-maps have finished, but at the last step, when the code run on the scene.Save(); it's broken, throw the cv:exception

open Error: Assertion failed (channels() == cv_mat_cn(dtype)) in cv::mat::copyTo, file xxxxx\opencv\modules\core\src\copy.cpp, line 259

I track the issue, when the  code in types.inl :
bool SerializeSave(const TYPE& obj, std::ofstream& fs, ARCHIVE_TYPE type, unsigned flags=0)
{
	// serialize out the current state
	switch (type) {
	case ARCHIVE_TEXT: {
		boost::archive::text_oarchive ar(fs, flags);
		_ar << obj;_  

> //when it runs on the line ar<<obj, that will throw the cv:exception

break; }
...}
and I go ahead to debug this, finally it runs on
void save(Archive& ar, const cv::Mat_<_Tp>& m, const unsigned int /*version*/)
{
	ar & m.cols;
	ar & m.rows;
	const size_t data_size = m.cols * m.rows;
	if (m.isContinuous()) {
		ar & boost::serialization::make_array((const _Tp*)m.ptr(), data_size);
	} else {
		cv::Mat_<_Tp> m_cont;
		_m.copyTo(m_cont);_ 

> //m.copyTo(m_cont)  it was broken on this line finally

		ar & boost::serialization::make_array((const _Tp*)m_cont.ptr(), data_size);
	}
}

how to fix it

**Comment by cdcseacave** [comment]
try updating to the latest OpenCV code; there was a problem with release() at some point, but fixed in the latest code; hope this helps

**Comment by MichaleWong** [comment]
@cdcseacave, thank you for your quick react, I am using opencv 3.0 , I will try 3.3 later

**Comment by MichaleWong** [comment]
now it is solved after using the opencv 3.3, it should be a bug on opencv 3.0
