### ISSUE TITLE
How to view the depth maps?

### ISSUE THREAD

**Issue by mojovski** [cdcseacave/openMVS#242]
Is there a way to inspect the computed depth maps (*.dmap) ?

**Comment by cdcseacave** [comment]
you can use `-v 4` command line param

**Comment by mojovski** [comment]
:) In what application? 
Thank you!

**Comment by NextDesign1** [comment]
@mojovski Providing -v 4 to DensifyPointCloud will export the depth and normal maps as PNGs.
