### ISSUE TITLE
Texture a different mesh using OpenMVG+OpenMVS pipeline

### ISSUE THREAD

**Issue by Nish160** [cdcseacave/openMVS#243]
### Specifications like the version of the project, operating system, and hardware
I am working on OpenMVS master with updated interface.h from mesh_interface branch
and running this project on VMware machine (Ubuntu16.04) 

### Steps to reproduce the problem
Actually I want to intercept this pipeline and give my own mesh(CAD model- highly detailed) for texturing in between.
Basically I want to give my CAD model to TextureMesh module of OpenMVS, while the other inputs remaining the same , so that I can get a fully textured CAD model.
Any idea how to do that?

**Comment by cdcseacave** [comment]
If the mesh model you want to pass to OpenMVS (the CAD model) has the coordinate system unchanged from the original model, the process is simple. Just fill the Interface with the mesh data and the camera poses, and you are good to go.

**Comment by Nish160** [comment]
I can change the coordinate system of my CAD model to the mesh generated by OpenMVG-MVS pipeline by using georef tool of meshlab(with errors upto 5-8 cms max).
As per your suggestion to fill the Interface with the mesh data and the camera poses, my question is after these changes are made ,where are we going to use the Interface object?
Fromm my interpretation, Scene.cpp has **Load** function which then calls **LoadInterface** function, should I inject another function call to overwrite the parameters computed by pipeline i.e in **LoadInterface** function?
Further I don't have camera poses explicitly, do I have to use the camera poses computed by the OpenMVG-OpenMVS pipeline(I have run the complete pipeline once and have got the output folder with all necessary files.now I want to texture My CAD model using it ) or is there some other way?

**Comment by Nish160** [comment]
Sorry for such a confusing question, So I'll rephrase it:

I have run the complete pipeline once giving a set of images as inputs and I finally got a textured mesh from OpenMVG+OpenMVS pipeline.
Now, I want that OpenMVS should not reconstruct a mesh , but use my (AUTOCAD model-highly detailed) mesh to give me the final output as the textured CAD model.

Could you please provide a step by step procedure on how to do that(from changes in interface.h to running the required modules)?

Thanks

**Comment by cdcseacave** [comment]
I understand, and my initial reply was answering this. I'll try to reformulate. Your CAD model can be textured fine, as long as it is in the same coordinates system as the one reconstructed by OpenMVS. So you have to make sure they are, if not you have to align them using a similarity transform based on 3D correspondences. This is fairly easy to do it yourself, or if you do not want to get your hands dirty just use Meshlab. Next pass this CAD mesh to OpenMVS for texturing, using the Interface.h file.

**Comment by Nish160** [comment]
Thanks for your response @cdcseacave 
Could you please tell me how to pass this CAD mesh to OpenMVS for texturing, using the Interface.h file?
Actually I am new to this programming...my regrets for that!
So, I would highly appreciate if you could tell me where and what to add in the code to get a Textured CAD model.
I have CAD model in openMVS coordinates (.obj file, vertices and faces) as inputs.

Thanks

**Comment by cdcseacave** [comment]
Interface.h is self explanatory. I'd like to help with programming too, but unfortunately I do not have now.

**Comment by Nish160** [comment]
I made the following edits to scene.cpp to load my CAD model for which I ad a list of vertices and faces:
![screenshot from 2017-08-17 17-16-36](https://user-images.githubusercontent.com/30828701/29410831-ec48bcce-8341-11e7-9fda-8f79a881d9f2.png)
Then I ran the complete pipeline from DensifyPointCloud to TextureMesh refering:
https://github.com/cdcseacave/openMVS/wiki/Usage
But the TextureMesh module uses The same mesh created by ReconstructMesh.
Please let me know if I am going wrong somewhere?
Thanks

**Comment by cdcseacave** [comment]
Indeed, quite wrong. First of all your code is not used for anything, as it is added after return. Even if added above, you load the mesh in a temporary object that is deleted as soon as the fucntion exits. Third, and most important, you should not modify any file in OpenMVS, all you need to do is to open the mvs project that contains the original mesh and replace it with your mesh, all these through `Interface.h` (I think I repeated this several times already). I'm sorry, I'd like to help you, but I am over my had now with work, and you need a lot of tutoring as your familiarity with programming is near 0.

**Comment by Nish160** [comment]
Thanks a lot for the guidance @cdcseacave .
Sorry to bother you again amidst your hectic schedule.
As you told to replace my mesh with the original mesh using interface.h, I tried to do the same and ran a sample code:
![1](https://user-images.githubusercontent.com/30828701/29483562-8308c616-8498-11e7-9f75-1216d86b0a6f.png)
![2](https://user-images.githubusercontent.com/30828701/29483566-8a6abfa4-8498-11e7-9fcf-274ce294af43.png)
When I run this code,the resulting mvs file is of 204 Bytes only .Also, obj.mesh.vertices and obj.mesh.faces contain all the vertices and faces of mesh respectively ie., the mesh has been loaded but I guess not saved to mvs file using --------->   MVS:ARCHIVE::SerializeSave(obj , "mine.mvs"); 
It would be great if you could help me out in this.
Thanks

**Comment by Nish160** [comment]
I got where the problem lies-I need to first load the mvs file generated by OpenMVS before texturing  using SerializeLoad() ie., scene_dense_mesh_refine.mvs ,replace its mesh object data with my mesh and then save this interface object using SerializeSave() ...n I will get an mvs file as output that I can feed to TextureMesh module.I Hope I am correct this time?
 Now the problem is I am not able to load the scene_dense_mesh_refine.mvs file which is of 10.5MB using SerializeLoad().
On running the code I get the following error: std::bad_alloc
![3](https://user-images.githubusercontent.com/30828701/29507961-0d218a90-8642-11e7-8f54-135974bdf21f.png)
This is due to memory storage problem.
But I am already running this code on Ubuntu 16.04 VM ,RAM=64GB(also tried with 32GB RAM), HardDisk=60GB.

I am able to run my code and load scene.mvs file which is of 2.3MB only that means its correct.
Any idea how to solve this issue???

Thanks

**Comment by Nish160** [comment]
Finally I have been successful in texturing my CAD model through openMVG+MVS pipeline .
And the way to do it was pretty simple.
I just had to enable the hidden option of "mesh-file" while running TextureMesh module and feed in scene_dense.mvs file (created by running OpenMVG+OpenMVS pipeline ) and my CAD mesh (in obj or ply).
No changes in code are required or implemenation of interface.h.
Just felt like posting this easy way out that may be helpful for future users!!!

Thanks

**Comment by cdcseacave** [comment]
That is a valid option, glad it was enough for your needs. I mentioned this method in some of the previous posts, I thought you already know about it but was not enough and you need a deeper integration. Should we close this issue now?

**Comment by Nish160** [comment]
Sure
Thanks
