### ISSUE TITLE
DensifyPointCloud Precision of Output PLY File

### ISSUE THREAD

**Issue by mchildsCO76** [cdcseacave/openMVS#244]
I am using the latest OpenMVS Windows 64-bit binaries from https://github.com/cdcseacave/openMVS_sample to generate a dense point cloud from the output from an OpenMVG pipeline working on a series of drone images.

I am trying to get a high quality dense point cloud in PLY format with high precision (centimeter precision or so) coordinates based on the EXIF position information in the source JPG images. I'm finding that while the output PLY file is at the correct ECEF coordinate location, there seems to be limited precision in the output, resulting in little stripes of points.

I believe this is due to the use of 32-bit float output for the XYZ fields in the generated PLY file. The ECEF (Earth-Centered Earth-Fixed) coordinate values are quite large as they are distances from the center of the earth along each axis, so you can't get much precision beyond the decimal in a 32-bit float field. Note I have also tried the UTM coordinate option with OpenMVG and see similar issues as those coordinate values are also quite large (not the mention that the UTM coordinates are incorrect).

Is there a way to either generate the PLY file with 64-bit double-precision coordinate fields or some way to scale the PLY XYZ files so significant precision isn't lost  when using 32-bit floats? All of the XYZ locations should be in limited ranges, so a simple offset to subtract and then apply back later would be enough.

I have attached a text file that lists the entire series of commands that I call in the OpenMVG and OpenMVS pipeline, as well as the stdout/stderr output of each command and a list of each input image file with EXIF coordinate information at the beginning.

Any help is greatly appreciated as this is the final step in getting my project finished.
[image_to_cloud_log.txt](https://github.com/cdcseacave/openMVS/files/1253024/image_to_cloud_log.txt)

Thanks,

Mike Childs

**Comment by pmoulon** [comment]
Can you explain if you notice the `little stripes of points` at the SfM or the MVS stage.

1. MVS does not like numbers with large precision.
The best consists in moving the scene around (0,0,0) and run MVS.
You can use the binary `main_ChangeLocalOrigin` proposed here https://github.com/openMVG/openMVG/pull/961 to recenter your SFM results and then process it with OpenMVS.

2.  If the problem appear at the SfM stage you can try this: https://github.com/openMVG/openMVG/issues/949#issuecomment-310429812

**Comment by cdcseacave** [comment]
@mchildsCO76 I also believe is the first issue explained by Pierre; exporting the pointcloud in 64bit PLY will not help, as the neither OpenMVS nor OpenMVG can work with huge numbers. Extract the average position from the scene before processing with OpenMVS and re-add it to the result.

**Comment by mchildsCO76** [comment]
Thanks for the quick reply. I will give that a try!

**Comment by rttgnck** [comment]
@mchildsCO76 Is this the little stripes of points that you are talking about? I am trying to do the same thing as you.
![point strips](https://user-images.githubusercontent.com/30731858/29737405-b0fd9878-89d2-11e7-9054-34e0612c2039.png)

**Comment by mchildsCO76** [comment]
Yes those are the stripes. They are what you would expect by a loss of precision.

I'm hoping the suggested fix to offset the XYZ to the center of the images during processing which would reduce the issue with precision in the MVS process as the magnitude of the numbers will be much smaller so more decimal precision can be maintained.

**Comment by cdcseacave** [comment]
to the center of the scene or camera positions (what @mchildsCO76 was probably wanting to say)

**Comment by rttgnck** [comment]
This issue was and is mitigated by re-orientating the scene to 0,0,0. As both of us were able to correct this, it could probably be closed now.
