### ISSUE TITLE
How to output binary PLY instead of ASCII?

### ISSUE THREAD

**Issue by rttgnck** [cdcseacave/openMVS#245]
I would like to output my PLY files as binary instead of ASCII. Is this a possibillity? If so what needs to change to do this? If this is not an option this can be closed.

**Comment by pmoulon** [comment]
Why not using Meshlab or CloudCompare to do that?

**Comment by rttgnck** [comment]
I just found a previous issue that addressed this and that is what you suggested there. I will look into installing CloudCompare or Meshlab on Ubuntu to that I can add a command to my pipeline to convert the final output.
