### ISSUE TITLE
DensifyPointCloud Redirect StdOut/StdErr from Command Line

### ISSUE THREAD

**Issue by mchildsCO76** [cdcseacave/openMVS#246]
I'm using an OpenMVG/OpenMVS pipeline to generate point clouds. I log the stdout and stderr of all of the .exe's in the pipeline to a single log file. This works fine for all of the OpenMVG .exe files, but DensifyPointCloud.exe does not provide any output.

When I run from the command line I see live updates on the screen, but a re-direct to a text file of stdout and/or stderr is not capturing anything. For example, running the following does not put anything in the densify_stdout.txt or densify_stderr.txt files:

DensifyPointCloud.exe --input-file "scene.mvs" --output-file "scene_dense.ply" --max-threads 15 > densify_stdout.txt 2> densify_stderr.txt

In my real code I'm using CreateProcess and passing in handles to my log file for stderr and stdout and the problem is the same.

Is there some alternate method to provide a log file name to DensifyPointCloud.exe and the other OpenMVS .exe files?

**Comment by cdcseacave** [comment]
never tested to capture the stdout, ,but even if it would work it is not the right thing to do; on stdout it is printed a live progress, that does not logs well; the correct/full log is stored in LOG files created in the working directory; if you need them all in one file, just concatenate them

**Comment by mchildsCO76** [comment]
Thanks I went ahead and updated my live logging to display the log from DensifyPointCloud as it is created and then append it to my master log when the application finishes. That works well.

**Comment by AL9501** [comment]
@mchildsCO76 Hi mchildsCO76, I meet the same question. Can you tell me your solution. Thank you.

**Comment by mchildsCO76** [comment]
What I did was just use the DensifyPointCloud*.log file that are written by DensifyPointCloud.exe. I just check every few seconds for an increase in the size of any file matching DensifyPointCloud*.log. If the size increases, whatever text made up the change in size is dumped to my master log (or stdout).

**Comment by AL9501** [comment]
@mchildsCO76 Thank you so much.

**Comment by FavorMylikes** [comment]
This project seems using a own `LOG` system

By checking `libs/Common/Log.cpp` file.

I found the code below

https://github.com/cdcseacave/openMVS/blob/c658b72298019544a5b0522d303fc158f226857e/libs/Common/Log.cpp#L302-L306

It try to redirect `stdout` and `stderr` to same console.

But, as the same time, you can not redirect the output to a file by using `command > out.txt`
