### ISSUE TITLE
Compiling openMVS Windows

### ISSUE THREAD

**Issue by BigAloz** [cdcseacave/openMVS#247]
I am having huge problems trying to create the openMVS project on Windows using CMake

My main issues relate to having many of the required libraries already on my system but compiled using either static or dynamically. 

Am I able to download from somewhere a SLN file with all the required files to save using CMAKE ?

**Comment by BigAloz** [comment]
On the same issue.

I am not very good with CMake.

When a directory path is required for a libary where should it point to ?
- The root path of the built files ?
- The root path of the original source directory ?

This is where I am getting mixed as I just experiment with the paths until it finds the files which may nt be the best method :-(

**Comment by cdcseacave** [comment]
Impossible to share only SLN files, as they depend on the library version and desired configuration.
The procedure is quite simple:
 - download & compile (preferably all either static or dynamic) each dependency
 - cmake OpenMVS and point to the paths of the compiled dependencies
Pls check CMake docs for more info.
