### ISSUE TITLE
Thirdparty stlplus3 compilation error

### ISSUE THREAD

**Issue by pyp22** [cdcseacave/openMVS#25]
Hi guys,

I'm meeting those 2 errors on stlplus3 thirdparty: 

In file included from /usr/local/include/openMVG/sfm/sfm_view.hpp:10:0,
                 from /usr/local/include/openMVG/sfm/sfm_data.hpp:11,
                 from /mnt/pacman/NuxSFM-2.0/unstable/computer-vision/openMVS/src/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:38:
/usr/local/include/openMVG/third_party/stlplus3/filesystemSimplified/file_system.hpp:113:71: error: default argument given for parameter 2 of âstd::string stlplus::folder_up(const string&, unsigned int)â [-fpermissive]
   std::string folder_up(const std::string& folder, unsigned levels = 1);

In file included from /usr/local/include/openMVG/sfm/sfm_view.hpp:10:0,
                 from /usr/local/include/openMVG/sfm/sfm_data.hpp:11,
                 from /mnt/pacman/NuxSFM-2.0/unstable/computer-vision/openMVS/src/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:38:
/usr/local/include/openMVG/third_party/stlplus3/filesystemSimplified/file_system.hpp:192:116: error: default argument given for parameter 3 of âstd::string stlplus::lookup(const string&, const string&, const string&)â [-fpermissive]
   std::string lookup (const std::string& file, const std::string& path, const std::string& splitter = PATH_SPLITTER);

[ 91%] Linking CXX executable ../../bin/InterfaceOpenMVG
[ 92%] Linking CXX executable ../../bin/RefineMesh
[ 92%] Built target InterfaceOpenMVG
[ 92%] Built target RefineMesh
[ 94%] Linking CXX executable ../../bin/ReconstructMesh
[ 94%] Built target ReconstructMesh
apps/InterfaceOpenMVG/CMakeFiles/InterfaceOpenMVG2.dir/build.make:62: recipe for target 'apps/InterfaceOpenMVG/CMakeFiles/InterfaceOpenMVG2.dir/InterfaceOpenMVG2.cpp.o' failed
make[2]: *** [apps/InterfaceOpenMVG/CMakeFiles/InterfaceOpenMVG2.dir/InterfaceOpenMVG2.cpp.o] Error 1
CMakeFiles/Makefile2:409: recipe for target 'apps/InterfaceOpenMVG/CMakeFiles/InterfaceOpenMVG2.dir/all' failed
make[1]: *** [apps/InterfaceOpenMVG/CMakeFiles/InterfaceOpenMVG2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Linking CXX executable ../../bin/DensifyPointCloud
[ 98%] Linking CXX executable ../../bin/TextureMesh
[ 98%] Built target DensifyPointCloud
[ 98%] Built target TextureMesh
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

Is there a STL stuff dependency i'm missing ?

Tnx

**Comment by pmoulon** [comment]
This message must not longer appear in https://github.com/OpenMVS/openMVS master branch.
BTW,

**Comment by pyp22** [comment]
correct ! Thanks. Can be closed.
