### ISSUE TITLE
How to produce a compact texture file ?

### ISSUE THREAD

**Issue by alvaro562003** [cdcseacave/openMVS#250]
Hello,

First, I find that the openMVS texture is really really well done. Congratulations.

In the post-process, i have to do some corrections including in the texture. The openMVS Texture is very fragmented and it makes it difficult to rework.

Is it possible to produce a more compact texture directly from openMVS?

Does someone have an idea how to compact the texture ? (blender's term: texture baking)

regards

**Comment by pmoulon** [comment]
You can try to extend the existing API in order to use your own UVs.

**Comment by cdcseacave** [comment]
@pmoulon idea is great, that would be the best; other options are to improve the existing UV algo, or to use an external app for rebaking the texture (don't know any free options out there though)

**Comment by alvaro562003** [comment]
@pmoulon, i have no idea on how to start :-(

**Comment by pmoulon** [comment]
1. Look in the code where the UV Atlas is created.
Try to implement your own method there or import your own UV that you have generated with the software or your choice.
You can certainly play with https://github.com/Microsoft/UVAtlas/wiki
