### ISSUE TITLE
Minor mistakes in Hash.h and Types.inl

### ISSUE THREAD

**Issue by srivathsanmurali** [cdcseacave/openMVS#256]
Hi,
I found some minor mistakes that raised errors while trying to compile the library. Just thought I would report them.

**Hash.h**
https://github.com/cdcseacave/openMVS/blob/54766b9209f48428df1f332a82e52a43e341d2dd/libs/Common/Hash.h#L246
I think you forgot to type cast the c_string to const uint8* like you did in the previous two lines.
``` c++
static inline Key HashKey(const String& str) { return HashKey((const uint8*) str.c_str(), str.size()); } 
```
**Types.inl**
https://github.com/cdcseacave/openMVS/blob/54766b9209f48428df1f332a82e52a43e341d2dd/libs/Common/Types.inl#L2065
The object is missing while calling the cv::Mat::channels() function.
``` c++
const int scn(out.cv::Mat::channels());
```

**Comment by cdcseacave** [comment]
thx, but both seem fine as they are, pls report back if they are causing some issues for you

**Comment by srivathsanmurali** [comment]
I wasn't able to compile without errors unless I made these changes.
