### ISSUE TITLE
CUDA device 0 initialized: GeForce GTX 1060 6GB (compute capability 6.1; memory 5.93GB) in Desne Point Cloud Step

### ISSUE THREAD

**Issue by ManishSahu53** [cdcseacave/openMVS#259]
### Specifications like the version of the project, operating system, and hardware
latest version mvs, Ubuntu 16.04, 16GB Ram, i7-7700k, 1060 GTX 6GB Graphic Card
### Steps to reproduce the problem
While running Densifypointcloud step in openMVS from openMVG sfm, I am getting this message (not error) "CUDA device 0 initialized: GeForce GTX 1060 6GB (compute capability 6.1; memory 5.93GB)". Although I could complete the dense point cloud step but I want to know if this step is using my cuda or not? Since it says CUDA device 0 initialized. If not then what should I do to make sure it use graphic card and reduces the time taken. Thank You

**Comment by rennu** [comment]
I think if you increase the verbosity of the binary by using option -v (ie. -v 3) it should tell you wether it's actually using GPU for processing or not.

You could also use nvidia-smi command to view GPU load to confirm this.

**Comment by cdcseacave** [comment]
none of the modules is using CUDA, except RefineMesh
