### ISSUE TITLE
import scene file format

### ISSUE THREAD

**Issue by edgarriba** [cdcseacave/openMVS#26]
Hi! I'm trying use openMVS for dense reconstruction with camera calibration extracted from different frameworks such as TheiaSfm, openSfM, Libmv, etc.

Is there any specific documentation about loading scenes from a format file different to openMVG? I Miss an API to simply set calibrated views with corresponded images.

Thanks in advance!
Edgar

**Comment by ORNis** [comment]
not sure, but maybe you can look at this file https://github.com/cdcseacave/openMVS/blob/master/libs/MVS/Interface.h
Regards,
R.

**Comment by edgarriba** [comment]
@ORNis thanks for your answer, It's what I was looking for! Besides, the documentation says that openMVS supports scene import from a plane text but I couldn't find how this file format must be.

**Comment by ORNis** [comment]
It could be anything you want given that your data meets the requierement of openMVS. Look at these files https://github.com/cdcseacave/openMVS/blob/develop/apps/InterfaceOpenMVG/InterfaceOpenMVG.cpp or https://github.com/cdcseacave/openMVS/blob/develop/apps/InterfaceVisualSFM/InterfaceVisualSFM.cpp. These apps load a third-party format (e.g. one from OpenMVG) and convert it to the format used by OpenMVS

**Comment by edgarriba** [comment]
cool! The code a bit messy but thanks again.

**Comment by ORNis** [comment]
Please don't say it's messy, instead you can say you don't like the coding style :)
good luck,
R.

**Comment by pmoulon** [comment]
I'm agree with @ORNis 
When some code is open, how we can say it is messy or not.
I mean, at least, something it's better than nothing!!

**Comment by edgarriba** [comment]
Hey guys I didn't want to offend anyone.
It's only an opinion in front of trying to understand docs and code. You do a great job.

**Comment by pmoulon** [comment]
We understand your point... always better to ask first (try first, and once we don't succeed ask help).
And opensource is also a way in which everyone can contribute to make the code & docs better ;-)

**Comment by cdcseacave** [comment]
Plus, please check the wiki before anything else; although it contains minimum information for now, it had the answers to all your questions already: https://github.com/cdcseacave/openMVS/wiki/Interface
