### ISSUE TITLE
Incompleate mesh reconstruction

### ISSUE THREAD

**Issue by vid12** [cdcseacave/openMVS#260]
I am trying to reconstruct 3Dmesh from a pointcloud generated by OpenMVS and am getting incomplete result. If I use only a subset of images to produce a pointcloud (a third of images - 300) I get a complete mesh reconstruction (cca 32 million triangles).
![image](https://user-images.githubusercontent.com/4492058/31813129-9c6ef4ae-b585-11e7-814a-58467a2f4475.png)

However if I use all of the images (650 images) to reconstruct a pointclout, then mesh reconstruction produces only a part of 3D surface (1.5 Million triangles):
![image](https://user-images.githubusercontent.com/4492058/31813257-021fcb0c-b586-11e7-8d0d-f016565c687d.png)

What could be the reason behind this issue?I tried changing different parameters (increasing and decreasing)- like --thickness-factor and--quality-factor Is there perhaps some hidden option that can be changed that governs the filtering of triangles?

**Comment by cdcseacave** [comment]
Didn't see this problem before. Could you share the image dataset and the openmvs projects?

**Comment by vid12** [comment]
Yes of course:) 

Here is a link to download the full dataset:
https://1drv.ms/f/s!AtdGgC4epGJ8brkQeN3W6FsbZb4

**Comment by vid12** [comment]
And here are links to 250 dataset:

https://wetransfer.com/downloads/6bc55ddeee8e4316c6b042df863d597420171021090101/625c4f9d753f83c23b2fd9d28608509620171021090101/6a6ee4
--
https://wetransfer.com/downloads/bb970cc8f97808f715bbd6e5055f2daf20171021090234/df6f8d2a97006d6206b42457a4c147c120171021090234/c1133f

**Comment by cdcseacave** [comment]
seems like the project was generated on Linux, for some reason boost on linux is not compatible with boost on windows; pls send me the original images so that I reconstruct it from the begining

**Comment by vid12** [comment]
Hi,

The project was definitely generated on windows. Undistorted images and initial mvs file were generated by openmvg. If you like i cane share initial mvs scene file with you.

**Comment by cdcseacave** [comment]
did you compile OpenMVS on 32 or 64 bit? and what version of boost did you use? one thing is sure, it is not compatible with what I have on my machine

**Comment by vid12** [comment]
I used precompiled binaries, that i downloaded from your site, so that is 64bit

**Comment by vid12** [comment]
After some testing I figured out that increasing min-point-distance from default 2.5 to larger value (in my case 7) solves this issue
