### ISSUE TITLE
Problem when loading dense .mvs file with Interface.h

### ISSUE THREAD

**Issue by ShikiGami** [cdcseacave/openMVS#262]
I'm trying to load the resulting file of DensifyPointCloud using Interface.h, but I'm getting a `std::bad_alloc` exception.
If I try to load the not dense scene, imported from OpenMVG I have no problem, but if I process this scene and try to open the resulting dense scene, I always get this exception.

As far as I can see, it is failing when trying to resize a `std::vector` in the load process, which could be because of a weird value in a `size_t` value.

Any help would be appreciated.

**Comment by cdcseacave** [comment]
for that to work you need to modify DensifyPointCloud to save the result with SaveInterface() not Save()
