### ISSUE TITLE
[Question] Poor quality of Mesh with ReconstructMesh command. How to improve it?

### ISSUE THREAD

**Issue by ManishSahu53** [cdcseacave/openMVS#263]
### Specifications like the version of the project, operating system, and hardware
Latest openMVS master, Linux 16.04, i7-7700K, 6GB 1060GTX, 16 GB Ram, SSD
### Steps to reproduce the problem
I have 20 MP , 20 images (Aerial oblique) and I have already reconstructed Dense Point Cloud from openMVS. It looks good. After running ReconstructMesh command, I got mesh of the scene. But Mesh is of very poor quality see [screenshot]. I have tried running Refine Mesh also but it always goes out as Segmentation fault (core dumped) even tried with 6 images only. So I am skipping refine mesh step for now and doing olny ReconstructMesh step on dense point cloud. Am I doing something wrong here? 
command I ran - 1. DensifyPointCloud -options number views fuse - 4
                           2. ReconstructMesh -options -d 0 
                           3.  RefineMesh -options --use-cuda 0 --max-views 10
* I am using eigen 3.2 only
![image](https://user-images.githubusercontent.com/27155127/32237886-2da52c54-be8c-11e7-8731-a2d218bc2cb1.png)
Google drive link for dense point cloud and mesh - https://drive.google.com/file/d/0BxdowQswHG4GZzJCc24zSHJDOTQ/view?usp=sharing

**Comment by cdcseacave** [comment]
pls share the original images as well

**Comment by ManishSahu53** [comment]
here - https://drive.google.com/file/d/0BxdowQswHG4GdFVLVUZtVUhMWUU/view?usp=sharing

**Comment by cdcseacave** [comment]
a big problem that I see is that you georeferenced the scene before openmvs, that will create so many problems, including accuracy issues; please make sure to georeference only after OpenMVS

**Comment by ManishSahu53** [comment]
ok i will try to do it. But georeferencing/Ground Control points need to be done at sfm step only inorder to get accuracy? after generating dense point cloud how can I put Ground control points?

**Comment by cdcseacave** [comment]
you misunderstood me, the GCPs should be used at SfM step, but the scene should be exported in a local coordinates system (ex the center of the scene to be 0), so that the coordinates of any point in the scene is relatively small; otherwise there will be problems due to limited precision of the floating points.

**Comment by ManishSahu53** [comment]
Ok. Now I got it. This might be the case as I am using UTM coordinate system and it range in 7 digit interger plus decimal digits. Can I solve this problem by defining to double data type instead of float? Thanks. I will let you know the results once I get it.

**Comment by ManishSahu53** [comment]
@cdcseacave I ran it as local coordinate system. Point Cloud issue of line pattern is resolved.
Mesh is also looking better, see screenshot below. 
But still I can seems to run Refine mesh command?? Also I am trying for orthophoto generation option in textured mesh option. No error is coming but orthophoto size is in bytes and contain no data although I could get texturedmesh.ply file correctly. Can you tell me what am I doing wrong. Thanks.
Attached 1. RefineMesh log file
               2. TexturedMesh log file
               3. Screenshot of Mesh(without refine mesh).

[TextureMesh-1711021211308BAE32.log](https://github.com/cdcseacave/openMVS/files/1436701/TextureMesh-1711021211308BAE32.log)

![image](https://user-images.githubusercontent.com/27155127/32312995-a3d00224-bfc6-11e7-91d6-715dc82a4082.png)

**Comment by ManishSahu53** [comment]
Hi @cdcseacave ,
Can you tell me how to align it in Z up? I think my model is correctly aligned as it was geo-referenced and localised it afterwards.

**Comment by cdcseacave** [comment]
yes, if it was geo-referenced before and only recentered (no rotation) for OpenMVS, should be fine for ortho projection
