### ISSUE TITLE
[Question] Unable to generate orthophoto

### ISSUE THREAD

**Issue by ManishSahu53** [cdcseacave/openMVS#272]
### Specifications like the version of the project, operating system, and hardware
Intel core i7-7700K, 16 GB RAM, SSD.
### Steps to reproduce the problem
Ran complete pipeline perfectly from sfm(openMVG) to Textured Mesh. No problem occurred but when I choose to generate orthophoto also its only of 67 bytes. I could generate Textured Mesh correctly and I think my model Z up also as it is georeferenced (not sure though). But when I open my model in meshlab it opens up upright(screenshot attached). Can you tell me What could be the problem?

![image](https://user-images.githubusercontent.com/27155127/33185312-b6aa04de-d0a7-11e7-958e-a9613c3f2084.png)

**Comment by cdcseacave** [comment]
Pls post the log

**Comment by ManishSahu53** [comment]
[TextureMesh-1711240031458BC11B.log](https://github.com/cdcseacave/openMVS/files/1500083/TextureMesh-1711240031458BC11B.log)

**Comment by cdcseacave** [comment]
`--orthographic-image-resolution` is in pixels

**Comment by ManishSahu53** [comment]
Can you tell me pixels as in pixels/metre?

**Comment by ManishSahu53** [comment]
OK Got it. Thanks. It worked very well.

**Comment by Jiatutu** [comment]
can you tell me who to set the para --orthographic-image-resolution. before ortho i cannot know the pixels.

**Comment by Jiatutu** [comment]
> OK Got it. Thanks. It worked very well.

can you tell me who to set the para --orthographic-image-resolution. before ortho i cannot know the pixels.
