### ISSUE TITLE
Issue with FuseDepthMaps

### ISSUE THREAD

**Issue by bvanderj** [cdcseacave/openMVS#275]
SceneDensify.cpp:1358: void DepthMapsData::FuseDepthMaps(MVS::PointCloud&, bool): Assertion `ISINSIDE(depth, depthData.dMin, depthData.dMax)' failed.

Interesting issue I _seem_ to have stumbled upon.  Depth maps are created fine, but getting an Assertion error on the FuseDepthMaps step.  Dataset is an orbit of 42 images (oblique), haven't had this issue with other datasets.  Will start hacking away if i don't hear any suggestions..

### Specifications like the version of the project, operating system, and hardware
linux OS (xenial) - 
### Steps to reproduce the problem
Can include the dataset if needed

**Comment by bvanderj** [comment]
simple typo in the compile flags.  closing this issue.

**Comment by CanCanZeng** [comment]
@bvanderj hi, I also meet the seem problem, how did you fix this bug? and do you know why this happen?

**Comment by bvanderj** [comment]
Yes, It was just a typo mistake in the cmake configuration file. I had -DMAKE_INSTALL_PREFIX originally, which i changed to -DCMAKE_INSTALL_PREFIX
