### ISSUE TITLE
Need to disable architecture specific code

### ISSUE THREAD

**Issue by UrQuan3** [cdcseacave/openMVS#279]
### Specifications like the version of the project, operating system, and hardware
Version: OpenMVS clone from 12/15/2017
OS: Ubuntu 16.04
HW: ThunderX CPU, 64GB RAM, no GPU.

### Steps to reproduce the problem

When compiling on non-ia32/AMD64 machines, the build fails in libs/Common/Util.cpp

I had already found the option for "-DOpenMVS_USE_SSE=false".  This does seem to do it's job.  However Util.cpp is full of ia32/AMD64 code and includes.  Since I am unsure how Util.cpp is used, I am unsure how to bypass it.  It looks like a file that combines hand-coded SSE/AVX, Intel specific cpuid functions, and generic file-op functions similar to Boost::Filesystem.  I tried setting all the other available optimizations to false (-DOpenMVS_USE_FAST_FLOAT2INT=false -DOpenMVS_USE_FAST_INVSQRT=false -DOpenMVS_USE_FAST_CBRT=false -DOpenMVS_USE_CUDA=false -DOpenMVS_USE_BREAKPAD=false).  I didn't expect that to work, and it didn't.

I do not expect you to make code changes for me, but if there is an easy flag somewhere, I will go use it.

Minor unrelated note: when cmake cannot find cgal, it says to set CGAL_ROOT, however, the actual environment variable seems to be CGAL_DIR.

**Comment by cdcseacave** [comment]
I never tried to compile it on anything other than a PC, and I never thought at this while coding it. The main reason for this is cause the lib is very resource demanding and I do not see the benefit of running it on thin devices. So I have no idea how hard would be to make it compile on ARM. Not only that I have 0 experience in coding on ARM, but I am more a researcher than a programmer. I'd love to help you, but if you were able to detect architecture specific code, that makes you already better prepared than me to do this.

**Comment by UrQuan3** [comment]
Thanks for the reply.  I thought I would ask if there was a C++ path in Util.cpp or if the only one was written in assembly.  You can go ahead and close the issue if you like.

I agree that running this on a small machine would be silly.  The whole reason I am looking at this is because my Windows machine only has 8GB of RAM and that is proving to be less than half of what I need for the current project.  I have this nice HPC node with 64GB and 4 times the performance, but rewriting x64 assembly in C/C++ is probably too much for me.  I may try one of the machines in the office instead.

BTW, thank you for sharing your work.  It's really cool.

**Comment by ggardet** [comment]
Any update here? I also try to get it build on Arm (aarch64), but `-DOpenMVS_USE_SSE=false` is not enough, as `Util.cpp` is still not building on aarch64. 1st issue is `cpuid.h` does not exist on Arm.

**Comment by cdcseacave** [comment]
I can not test and fix, for now you can comment the function that checks the cpu

**Comment by cdcseacave** [comment]
I still do not have access to an ARM platform, but I pushed in develop a blind attempt to solve this issue by simply disabling the CPUID functionality.

Can anybody test it on ARM and confirm that it compiles now?

**Comment by ggardet** [comment]
> I still do not have access to an ARM platform, but I pushed in develop a blind attempt to solve this issue by simply disabling the CPUID functionality.
> 
> Can anybody test it on ARM and confirm that it compiles now?

There is still an error:
```
[  187s] In file included from /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Common.h:176,
[  187s]                  from /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Log.cpp:8:
[  187s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h:156:10: fatal error: xmmintrin.h: No such file or directory
[  187s]   156 | #include <xmmintrin.h>
[  187s]       |          ^~~~~~~~~~~~~
```

**Comment by cdcseacave** [comment]
can u comment it out and see if it compiles?

**Comment by ggardet** [comment]
> can u comment it out and see if it compiles?

There is also `#include <emmintrin.h>` in `libs/Common/Types.h`.

Then it fails with:
```
[   20s] In file included from /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Common.h:176,
[   20s]                  from /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Timer.cpp:8:
[   20s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h: At global scope:
[   20s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h:1025:10: error: '__m128' does not name a type; did you mean '__fmaf128'?
[   20s]  1025 |  typedef __m128 sse_t;
[   20s]       |          ^~~~~~
[   20s]       |          __fmaf128
[   20s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h:1026:16: error: 'sse_t' does not name a type; did you mean 'sse_f_t'?
[   20s]  1026 |  typedef const sse_t& arg_sse_t;
[   20s]       |                ^~~~~
[   20s]       |                sse_f_t
[   20s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h:1029:23: error: 'sse_t' does not name a type; did you mean 'sse_f_t'?
[   20s]  1029 |  inline sse_f_t(const sse_t& p) : v(p)        {}
[   20s]       |                       ^~~~~
[   20s]       |                       sse_f_t
[   20s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h:1033:18: error: expected type-specifier before 'sse_t'
[   20s]  1033 |  inline operator sse_t() const                {return v;}
[   20s]       |                  ^~~~~
[   20s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h:1034:18: error: 'sse_t' does not name a type; did you mean 'sse_f_t'?
[   20s]  1034 |  inline operator sse_t&()                     {return v;}
[   20s]       |                  ^~~~~
[   20s]       |                  sse_f_t
[   20s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h:1035:9: error: 'sse_t' does not name a type; did you mean 'sse_f_t'?
[   20s]  1035 |  inline sse_t operator ==(sse_t s) const      {return cmpeq(v,s);}
[   20s]       |         ^~~~~
[   20s]       |         sse_f_t
[   20s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h:1036:9: error: 'sse_t' does not name a type; did you mean 'sse_f_t'?
[   20s]  1036 |  inline sse_t operator =(sse_t s)             {return v=s;}
[   20s]       |         ^~~~~
[   20s]       |         sse_f_t
[   20s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h:1037:9: error: 'sse_t' does not name a type; did you mean 'sse_f_t'?
[   20s]  1037 |  inline sse_t operator +(sse_t s) const       {return add(v,s);}
[   20s]       |         ^~~~~
[   20s]       |         sse_f_t
[   20s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h:1038:9: error: 'sse_t' does not name a type; did you mean 'sse_f_t'?
[   20s]  1038 |  inline sse_t operator +=(sse_t s)            {return v=add(v,s);}
[   20s]       |         ^~~~~
[   20s]       |         sse_f_t
[   20s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h:1039:9: error: 'sse_t' does not name a type; did you mean 'sse_f_t'?
[   20s]  1039 |  inline sse_t operator -(sse_t s) const       {return sub(v,s);}
[   20s]       |         ^~~~~
[   20s]       |         sse_f_t
[   20s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h:1040:9: error: 'sse_t' does not name a type; did you mean 'sse_f_t'?
[   20s]  1040 |  inline sse_t operator -=(sse_t s)            {return v=sub(v,s);}
[   20s]       |         ^~~~~
[   20s]       |         sse_f_t
[   20s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h:1041:9: error: 'sse_t' does not name a type; did you mean 'sse_f_t'?
[   20s]  1041 |  inline sse_t operator *(sse_t s) const       {return mul(v,s);}
[   20s]       |         ^~~~~
[   20s]       |         sse_f_t
[   20s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/Common/Types.h:1042:9: error: 'sse_t' does not name a type; did you mean 'sse_f_t'?
[   20s]  1042 |  inline sse_t operator *=(sse_t s)            {return v=mul(v,s);}
[   20s]       |         ^~~~~
[   20s]       |         sse_f_t
```
and more.

**Comment by cdcseacave** [comment]
you need to set `OpenMVS_USE_SSE` OFF in CMAKE and that will comment out both the includes and the new errors you get now
and try again to compile

**Comment by ggardet** [comment]
> you need to set `OpenMVS_USE_SSE` OFF in CMAKE and that will comment out both the includes and the new errors you get now
> and try again to compile

Ah yes! So, here is the next error:
```
[   43s] /home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/MVS/SceneReconstruct.cpp:338:29: error: pragma or attribute 'target("no-fma")' is not valid
[   43s]   338 | #pragma GCC target ("no-fma")
[   43s]       |                             ^
```

**Comment by cdcseacave** [comment]
just comment them, we will not advance much like this, if you want to help pls try to make it work on your side and propose the needed changes

**Comment by ggardet** [comment]
I have a successful buildwith the following workarounds:
* Your patch from the devel branch
* `sed -i 's/#include <xmmintrin.h>//'` libs/Common/Types.h
* `sed -i 's/#include <emmintrin.h>//'` libs/Common/Types.h
* `sed -i 's/#pragma GCC target ("no-fma")//'` libs/MVS/SceneReconstruct.cpp
* Add `-DOpenMVS_USE_SSE=OFF` to the cmake options

**Comment by cdcseacave** [comment]
thx, I've added the comment to deveop

**Comment by liangchen97** [comment]
@ggardet @cdcseacave 
I tried to compile on jetson nx, it reported error cpuid.h does not exist
I don't understand the simply disabling the CPUID functionality mentioned in the answer, how do I solve it?
OS: Ubuntu18.04
HW: arm64

**Comment by cdcseacave** [comment]
simply undefine `_PLATFORM_X86`

**Comment by liangchen97** [comment]
@cdcseacave 
Where should I undefine _PLATFORM_X86, could you explain it clearly?

**Comment by liangchen97** [comment]
@cdcseacave @ggardet 
Do I need to switch branches? Or what changes are made in the source code?

**Comment by cdcseacave** [comment]
pls try debug branch
