### ISSUE TITLE
compilation error with OpenMVG

### ISSUE THREAD

**Issue by edgarriba** [cdcseacave/openMVS#28]
Got this error while compiling. Any idea?
----------------------------------------

[ 24%] Built target Common
[ 31%] Built target Math
[ 60%] Built target IO
[ 89%] Built target MVS
[ 91%] Built target InterfaceOpenMVG
[ 93%] Building CXX object apps/InterfaceOpenMVG/CMakeFiles/InterfaceOpenMVG2.dir/InterfaceOpenMVG2.cpp.o
In file included from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/image/image.hpp:20:0,
                 from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/cameras/Camera_undistort_image.hpp:11,
                 from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/cameras/cameras.hpp:15,
                 from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/sfm/sfm_data.hpp:14,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:38:
/home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/image/image_container.hpp:16:1: warning: multi-line comment [-Wcomment]
 //  ( )( ) )(  ) _//__\
 ^
In file included from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/image/image.hpp:23:0,
                 from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/cameras/Camera_undistort_image.hpp:11,
                 from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/cameras/cameras.hpp:15,
                 from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/sfm/sfm_data.hpp:14,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:38:
/home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/image/image_drawing.hpp:12:1: warning: multi-line comment [-Wcomment]
 //  ( )( ) )(  ) _//__\
 ^
In file included from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:347:0,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Common.h:176,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/Common.h:38,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:33:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/HalfFloat.h: In static member function ‘static short int SEACAVE::hfloat::fromFloat(float)’:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/HalfFloat.h:62:29: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   const int& fltInt32((int&)fv);
                             ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/HalfFloat.h: In static member function ‘static float SEACAVE::hfloat::toFloat(short int)’:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/HalfFloat.h:70:18: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   return (float&)fltInt32;
                  ^
In file included from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:397:0,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Common.h:176,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/Common.h:38,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:33:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/SML.h: In destructor ‘SEACAVE::SMLVALUE_TYPE::~SMLVALUE_TYPE()’:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/SML.h:29:28: warning: deleting ‘void*’ is undefined [enabled by default]
  ~SMLVALUE_TYPE() { delete data; }
                            ^
In file included from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Common.h:176:0,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/Common.h:38,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:33:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h: In function ‘float SEACAVE::cbrt5(float)’:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:727:8: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  (int&)f = (((int&)f-(127<<23))/3+(127<<23));
        ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:727:20: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  (int&)f = (((int&)f-(127<<23))/3+(127<<23));
                    ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h: In member function ‘int SEACAVE::Float::Floor2Int() const’:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:1168:94: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  inline int  Floor2Int() const    { const double d((double)v.f + FLOOR_FIX); return (*(int*)&d) >> 16; }
                                                                                              ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h: In member function ‘int SEACAVE::Float::Ceil2Int() const’:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:1171:99: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  inline int  Ceil2Int() const    { const double d((double)v.f + 1.0 + FLOOR_FIX); return (*(int*)&d) >> 16; }
                                                                                                   ^
In file included from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Common.h:176:0,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/Common.h:38,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:33:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h: In member function ‘bool SEACAVE::TColor<TYPE>::operator==(const SEACAVE::TColor<TYPE>&) const [with TYPE = unsigned char]’:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:2004:108: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 template <> inline bool TColor<uint8_t>::operator==(const TColor& col) const { return (*((const uint32_t*)c) == *((const uint32_t*)col.c)); }
                                                                                                            ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:2004:137: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 template <> inline bool TColor<uint8_t>::operator==(const TColor& col) const { return (*((const uint32_t*)c) == *((const uint32_t*)col.c)); }
                                                                                                                                         ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h: In member function ‘bool SEACAVE::TColor<TYPE>::operator!=(const SEACAVE::TColor<TYPE>&) const [with TYPE = unsigned char]’:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:2005:108: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 template <> inline bool TColor<uint8_t>::operator!=(const TColor& col) const { return (*((const uint32_t*)c) != *((const uint32_t*)col.c)); }
                                                                                                            ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:2005:137: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 template <> inline bool TColor<uint8_t>::operator!=(const TColor& col) const { return (*((const uint32_t*)c) != *((const uint32_t*)col.c)); }
                                                                                                                                         ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h: In member function ‘uint32_t SEACAVE::TColor<TYPE>::toDWORD() const [with TYPE = unsigned char; uint32_t = unsigned int]’:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:2006:91: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 template <> inline uint32_t TColor<uint8_t>::toDWORD() const { return *((const uint32_t*)c); }
                                                                                           ^
In file included from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/sfm/sfm_view.hpp:10:0,
                 from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/sfm/sfm_data.hpp:11,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:38:
/home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/third_party/stlplus3/filesystemSimplified/file_system.hpp: At global scope:
/home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/third_party/stlplus3/filesystemSimplified/file_system.hpp:92:69: error: default argument given for parameter 2 of ‘bool stlplus::folder_delete(const string&, bool)’ [-fpermissive]
   bool folder_delete(const std::string& folder, bool recurse = false);
                                                                     ^
In file included from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:75:0,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Common.h:176,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/Common.h:38,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:33:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/FileUtil.h:90:8: error: after previous specification in ‘bool stlplus::folder_delete(const string&, bool)’ [-fpermissive]
   bool folder_delete(const std::string& folder, bool recurse = false);
        ^
In file included from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/sfm/sfm_view.hpp:10:0,
                 from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/sfm/sfm_data.hpp:11,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:38:
/home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/third_party/stlplus3/filesystemSimplified/file_system.hpp:113:71: error: default argument given for parameter 2 of ‘std::string stlplus::folder_up(const string&, unsigned int)’ [-fpermissive]
   std::string folder_up(const std::string& folder, unsigned levels = 1);
                                                                       ^
In file included from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:75:0,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Common.h:176,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/Common.h:38,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:33:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/FileUtil.h:111:15: error: after previous specification in ‘std::string stlplus::folder_up(const string&, unsigned int)’ [-fpermissive]
   std::string folder_up(const std::string& folder, unsigned levels = 1);
               ^
In file included from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/sfm/sfm_view.hpp:10:0,
                 from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/sfm/sfm_data.hpp:11,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:38:
/home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/third_party/stlplus3/filesystemSimplified/file_system.hpp:192:116: error: default argument given for parameter 3 of ‘std::string stlplus::lookup(const string&, const string&, const string&)’ [-fpermissive]
   std::string lookup (const std::string& file, const std::string& path, const std::string& splitter = PATH_SPLITTER);
                                                                                                                    ^
In file included from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:75:0,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Common.h:176,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/Common.h:38,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:33:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/FileUtil.h:191:15: error: after previous specification in ‘std::string stlplus::lookup(const string&, const string&, const string&)’ [-fpermissive]
   std::string lookup (const std::string& file, const std::string& path, const std::string& splitter = PATH_SPLITTER);
               ^
In file included from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Common.h:176:0,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/Common.h:38,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:33:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h: In instantiation of ‘SEACAVE::TPixel<TYPE>::TPixel(TYPE, TYPE, TYPE) [with TYPE = float]’:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.inl:23:45:   required from ‘const SEACAVE::TPixel<float> SEACAVE::TPixel<float>::WHITE’
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../IO/OBJ.h:45:67:   required from here
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:1816:9: warning: ‘SEACAVE::TPixel<float>::<anonymous union>::<anonymous struct>::r’ will be initialized after [-Wreorder]
    TYPE r;
         ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:1815:9: warning:   ‘float SEACAVE::TPixel<float>::<anonymous union>::<anonymous struct>::g’ [-Wreorder]
    TYPE g;
         ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:1846:9: warning:   when initialized here [-Wreorder]
  inline TPixel(TYPE _r, TYPE _g, TYPE _b) : r(_r), g(_g), b(_b) {}
         ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:1815:9: warning: ‘SEACAVE::TPixel<float>::<anonymous union>::<anonymous struct>::g’ will be initialized after [-Wreorder]
    TYPE g;
         ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:1814:9: warning:   ‘float SEACAVE::TPixel<float>::<anonymous union>::<anonymous struct>::b’ [-Wreorder]
    TYPE b;
         ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:1846:9: warning:   when initialized here [-Wreorder]
  inline TPixel(TYPE _r, TYPE _g, TYPE _b) : r(_r), g(_g), b(_b) {}
         ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h: In instantiation of ‘SEACAVE::TPixel<TYPE>::TPixel(TYPE, TYPE, TYPE) [with TYPE = unsigned char]’:
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/Scene.h:88:296:   required from here
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:1816:9: warning: ‘SEACAVE::TPixel<unsigned char>::<anonymous union>::<anonymous struct>::r’ will be initialized after [-Wreorder]
    TYPE r;
         ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:1815:9: warning:   ‘unsigned char SEACAVE::TPixel<unsigned char>::<anonymous union>::<anonymous struct>::g’ [-Wreorder]
    TYPE g;
         ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:1846:9: warning:   when initialized here [-Wreorder]
  inline TPixel(TYPE _r, TYPE _g, TYPE _b) : r(_r), g(_g), b(_b) {}
         ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:1815:9: warning: ‘SEACAVE::TPixel<unsigned char>::<anonymous union>::<anonymous struct>::g’ will be initialized after [-Wreorder]
    TYPE g;
         ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:1814:9: warning:   ‘unsigned char SEACAVE::TPixel<unsigned char>::<anonymous union>::<anonymous struct>::b’ [-Wreorder]
    TYPE b;
         ^
/home/eriba/software/openMVS/apps/InterfaceOpenMVG/../../libs/MVS/../Common/Types.h:1846:9: warning:   when initialized here [-Wreorder]
  inline TPixel(TYPE _r, TYPE _g, TYPE _b) : r(_r), g(_g), b(_b) {}
         ^
In file included from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/image/image.hpp:22:0,
                 from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/cameras/Camera_undistort_image.hpp:11,
                 from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/cameras/cameras.hpp:15,
                 from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/sfm/sfm_data.hpp:14,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:38:
/home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/image/image_converter.hpp:107:13: warning: ‘void openMVG::image::rgbFloat2rgbInt(const openMVG::image::Image<openMVG::image::Rgb<float> >&, openMVG::image::Image<openMVG::image::Rgb<unsigned char> >*, float)’ defined but not used [-Wunused-function]
 static void rgbFloat2rgbInt(
             ^
In file included from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/cameras/cameras.hpp:10:0,
                 from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/sfm/sfm_data.hpp:14,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:38:
/home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/cameras/Camera_Common.hpp:24:13: warning: ‘bool openMVG::cameras::isValid(openMVG::cameras::EINTRINSIC)’ defined but not used [-Wunused-function]
 static bool isValid(EINTRINSIC eintrinsic)
             ^
In file included from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/cameras/cameras.hpp:11:0,
                 from /home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/sfm/sfm_data.hpp:14,
                 from /home/eriba/software/openMVS/apps/InterfaceOpenMVG/InterfaceOpenMVG2.cpp:38:
/home/eriba/software/openMVG/openMVG_Build/install/include/openMVG/cameras/Camera_Intrinsics.hpp:129:15: warning: ‘double openMVG::cameras::AngleBetweenRay(const openMVG::geometry::Pose3&, const openMVG::cameras::IntrinsicBase*, const openMVG::geometry::Pose3&, const openMVG::cameras::IntrinsicBase*, const Vec2&, const Vec2&)’ defined but not used [-Wunused-function]
 static double AngleBetweenRay(
               ^
make[2]: *** [apps/InterfaceOpenMVG/CMakeFiles/InterfaceOpenMVG2.dir/InterfaceOpenMVG2.cpp.o] Error 1
make[1]: *** [apps/InterfaceOpenMVG/CMakeFiles/InterfaceOpenMVG2.dir/all] Error 2
make: *** [all] Error 2

**Comment by cdcseacave** [comment]
Please try the develop branch.

**Comment by edgarriba** [comment]
working ! Thanks.
