### ISSUE TITLE
[Question] I want to project 3D point (X,Y,Z) onto image (x,y) corrdinate. Can you tell how can I do that?

### ISSUE THREAD

**Issue by ManishSahu53** [cdcseacave/openMVS#283]
I have processed my images from openMVG and openMVS pipeline. Now I am trying to project a point (X,Y,Z) onto its pixel coordinate so I can get its rgb value. Can you tell me how to do it?

**Comment by ManishSahu53** [comment]
I found the answer x = K * (R * X + t)
x = pixel coordinate 
K = intrinsic matrix 
R = roatation 
t = translation 
X = 3D world point

**Comment by arun121cs** [comment]
Can anyone tell how to take  a pixel co-ordinate and get a real world depth from any reference?
