### ISSUE TITLE
DensifyPointCloud: command not found

### ISSUE THREAD

**Issue by squashking** [cdcseacave/openMVS#285]
Hi, I'm newbie to openMVS and Linux as well.
I have built openMVS according to the instructions 
[https://github.com/cdcseacave/openMVS/wiki/Building](url).
But when I try to run DensifyPointCloud it gives an error: command not found.
I can see the executable under /usr/local/bin/OpenMVS, and I can run the command if I include the full path  /usr/local/bin/OpenMVS/DensifyPointCloud. Could anyone tell me how to solve this problem? Did I miss something when building openMVS?
Thanks a lot!

**Comment by jpwhitney** [comment]
It likely has to do with your $PATH variable.
https://stackoverflow.com/questions/14637979/how-to-permanently-set-path-on-linux-unix

**Comment by squashking** [comment]
@jpwhitney Thank you very much, it is actually a Linux question.
