### ISSUE TITLE
Can't run ReconstructMesh on scence_dense (write(2, "std::bad_alloc", 14std::bad_alloc) (core dump)

### ISSUE THREAD

**Issue by pyp22** [cdcseacave/openMVS#29]
Hi guys,

ReconstructMesh is aborting without providing any mesh while using the dense scene. I'm thinking something dealing with ram. I tried on 2 diff. machines (16 & 32 ram) but got the same results. Here are the last strace lines:

futex(0x55c64e1e3654, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x55c64e1e0a74, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x55c653e8f234, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2971, ...}) = 0
write(1, "10:13:49 [App     ] Delaunay tet"..., 10710:13:49 [App     ] Delaunay tetrahedras weighting completed: 57443595 cells, 114887190 faces (3m36s444ms)
) = 107
write(3, "10:13:49 [App     ] Delaunay tet"..., 107) = 107
fsync(3)                                = 0
mmap(NULL, 2757296128, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc871f6f000
mmap(NULL, 459550720, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fca689bd000
mmap(NULL, 459550720, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc85692c000
mmap(NULL, 459550720, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc83b2e9000
mmap(NULL, 6433685504, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
brk(0x55c864426000)                     = 0x55c6e4c6c000
mmap(NULL, 6433816576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
mmap(NULL, 134217728, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x7fc8332e9000
munmap(0x7fc8332e9000, 13725696)        = 0
munmap(0x7fc838000000, 53383168)        = 0
mprotect(0x7fc834000000, 135168, PROT_READ|PROT_WRITE) = 0
mmap(NULL, 6433685504, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
futex(0x7fcade057650, FUTEX_WAKE_PRIVATE, 2147483647) = 0
write(2, "terminate called after throwing "..., 48terminate called after throwing an instance of ') = 48
write(2, "std::bad_alloc", 14std::bad_alloc)          = 14
write(2, "'\n", 2'
)                      = 2
write(2, "  what():  ", 11  what():  )             = 11
write(2, "std::bad_alloc", 14std::bad_alloc)          = 14
write(2, "\n", 1
)                       = 1
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
tgkill(29537, 29537, SIGABRT)           = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=29537, si_uid=0} ---
+++ killed by SIGABRT (core dumped) +++

regards

PY

**Comment by pyp22** [comment]
to complete. From a dmesg:

dmesg :

[ 4305.647556] Out of memory: Kill process 552 (ReconstructMesh) score 947 or sacrifice child
[ 4305.647567] Killed process 552 (ReconstructMesh) total-vm:6111928kB, anon-rss:5934304kB, file-rss:8kB

**Comment by cdcseacave** [comment]
Unfortunately openMVS is not yet scalable, please use smaller scenes.
