### ISSUE TITLE
Fused depth-maps 86 (86.00%, 43s, ETA 7s)...Killed

### ISSUE THREAD

**Issue by 945540968** [cdcseacave/openMVS#298]
The log is as following, can someone help me?
root@ubuntu:~# DensifyPointCloud /root/Documents/openMVS_result/Scene.mvs
22:32:00 [App     ] Build date: Feb  8 2018, 05:47:44
22:32:00 [App     ] CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
22:32:00 [App     ] RAM: 5.81GB Physical Memory 1022.00MB Virtual Memory
22:32:00 [App     ] OS: Linux 4.10.0-28-generic (x86_64)
22:32:00 [App     ] SSE & AVX compatible CPU & OS detected
22:32:00 [App     ] Command line: /root/Documents/openMVS_result/Scene.mvs
22:32:00 [App     ] Camera model loaded: platform 0; camera  0; f 0.902x0.902; poses 100
22:32:00 [App     ] Camera model loaded: platform 1; camera  0; f 1.169x1.169; poses 1
22:32:00 [App     ] Image loaded   0: IMG_0368.JPG
22:32:00 [App     ] Image loaded   1: IMG_0369.JPG
22:32:00 [App     ] Image loaded   2: IMG_0370.JPG
22:32:00 [App     ] Image loaded   3: IMG_0371.JPG
22:32:00 [App     ] Image loaded   4: IMG_0372.JPG
22:32:00 [App     ] Image loaded   5: IMG_0373.JPG
22:32:00 [App     ] Image loaded   6: IMG_0374.JPG
22:32:00 [App     ] Image loaded   7: IMG_0375.JPG
22:32:00 [App     ] Image loaded   8: IMG_0376.JPG
22:32:00 [App     ] Image loaded   9: IMG_0377.JPG
22:32:00 [App     ] Image loaded  10: IMG_0378.JPG
22:32:00 [App     ] Image loaded  11: IMG_0379.JPG
22:32:00 [App     ] Image loaded  12: IMG_0380.JPG
22:32:00 [App     ] Image loaded  13: IMG_0381.JPG
22:32:00 [App     ] Image loaded  14: IMG_0382.JPG
22:32:00 [App     ] Image loaded  15: IMG_0383.JPG
22:32:00 [App     ] Image loaded  16: IMG_0384.JPG
22:32:00 [App     ] Image loaded  17: IMG_0385.JPG
22:32:00 [App     ] Image loaded  18: IMG_0386.JPG
22:32:00 [App     ] Image loaded  19: IMG_0387.JPG
22:32:00 [App     ] Image loaded  20: IMG_0388.JPG
22:32:00 [App     ] Image loaded  21: IMG_0389.JPG
22:32:00 [App     ] Image loaded  22: IMG_0390.JPG
22:32:00 [App     ] Image loaded  23: IMG_0391.JPG
22:32:00 [App     ] Image loaded  24: IMG_0392.JPG
22:32:00 [App     ] Image loaded  25: IMG_0393.JPG
22:32:00 [App     ] Image loaded  26: IMG_0394.JPG
22:32:00 [App     ] Image loaded  27: IMG_0396.JPG
22:32:00 [App     ] Image loaded  28: IMG_0397.JPG
22:32:00 [App     ] Image loaded  29: IMG_0398.JPG
22:32:01 [App     ] Image loaded  30: IMG_0399.JPG
22:32:01 [App     ] Image loaded  31: IMG_0400.JPG
22:32:01 [App     ] Image loaded  32: IMG_0401.JPG
22:32:01 [App     ] Image loaded  33: IMG_0402.JPG
22:32:01 [App     ] Image loaded  34: IMG_0403.JPG
22:32:01 [App     ] Image loaded  35: IMG_0404.JPG
22:32:01 [App     ] Image loaded  36: IMG_0405.JPG
22:32:01 [App     ] Image loaded  37: IMG_0406.JPG
22:32:01 [App     ] Image loaded  38: IMG_0407.JPG
22:32:01 [App     ] Image loaded  39: IMG_0408.JPG
22:32:01 [App     ] Image loaded  40: IMG_0409.JPG
22:32:01 [App     ] Image loaded  41: IMG_0410.JPG
22:32:01 [App     ] Image loaded  42: IMG_0411.JPG
22:32:01 [App     ] Image loaded  43: IMG_0412.JPG
22:32:01 [App     ] Image loaded  44: IMG_0413.JPG
22:32:01 [App     ] Image loaded  45: IMG_0414.JPG
22:32:01 [App     ] Image loaded  46: IMG_0415.JPG
22:32:01 [App     ] Image loaded  47: IMG_0416.JPG
22:32:01 [App     ] Image loaded  48: IMG_0417.JPG
22:32:01 [App     ] Image loaded  49: IMG_0418.JPG
22:32:01 [App     ] Image loaded  50: IMG_0419.JPG
22:32:01 [App     ] Image loaded  51: IMG_0420.JPG
22:32:01 [App     ] Image loaded  52: IMG_0421.JPG
22:32:01 [App     ] Image loaded  53: IMG_0422.JPG
22:32:01 [App     ] Image loaded  54: IMG_0423.JPG
22:32:01 [App     ] Image loaded  55: IMG_0424.JPG
22:32:01 [App     ] Image loaded  56: IMG_0425.JPG
22:32:01 [App     ] Image loaded  57: IMG_0426.JPG
22:32:01 [App     ] Image loaded  58: IMG_0427.JPG
22:32:01 [App     ] Image loaded  59: IMG_0428.JPG
22:32:01 [App     ] Image loaded  60: IMG_0429.JPG
22:32:01 [App     ] Image loaded  61: IMG_0430.JPG
22:32:01 [App     ] Image loaded  62: IMG_0431.JPG
22:32:01 [App     ] Image loaded  63: IMG_0432.JPG
22:32:01 [App     ] Image loaded  64: IMG_0433.JPG
22:32:01 [App     ] Image loaded  65: IMG_0434.JPG
22:32:01 [App     ] Image loaded  66: IMG_0435.JPG
22:32:01 [App     ] Image loaded  67: IMG_0436.JPG
22:32:01 [App     ] Image loaded  68: IMG_0437.JPG
22:32:01 [App     ] Image loaded  69: IMG_0438.JPG
22:32:01 [App     ] Image loaded  70: IMG_0439.JPG
22:32:01 [App     ] Image loaded  71: IMG_0440.JPG
22:32:01 [App     ] Image loaded  72: IMG_0441.JPG
22:32:01 [App     ] Image loaded  73: IMG_0442.JPG
22:32:01 [App     ] Image loaded  74: IMG_0443.JPG
22:32:01 [App     ] Image loaded  75: IMG_0444.JPG
22:32:01 [App     ] Image loaded  76: IMG_0445.JPG
22:32:01 [App     ] Image loaded  77: IMG_0446.JPG
22:32:01 [App     ] Image loaded  78: IMG_0447.JPG
22:32:01 [App     ] Image loaded  79: IMG_0448.JPG
22:32:01 [App     ] Image loaded  80: IMG_0449.JPG
22:32:01 [App     ] Image loaded  81: IMG_0450.JPG
22:32:01 [App     ] Image loaded  82: IMG_0451.JPG
22:32:01 [App     ] Image loaded  83: IMG_0452.JPG
22:32:01 [App     ] Image loaded  84: IMG_0453.JPG
22:32:01 [App     ] Image loaded  85: IMG_0454.JPG
22:32:01 [App     ] Image loaded  86: IMG_0455.JPG
22:32:01 [App     ] Image loaded  87: IMG_0456.JPG
22:32:01 [App     ] Image loaded  88: IMG_0457.JPG
22:32:01 [App     ] Image loaded  89: IMG_0458.JPG
22:32:01 [App     ] Image loaded  90: IMG_0459.JPG
22:32:01 [App     ] Image loaded  91: IMG_0460.JPG
22:32:01 [App     ] Image loaded  92: IMG_0461.JPG
22:32:01 [App     ] Image loaded  93: IMG_0462.JPG
22:32:01 [App     ] Image loaded  94: IMG_0463.JPG
22:32:01 [App     ] Image loaded  95: IMG_0464.JPG
22:32:01 [App     ] Image loaded  96: IMG_0465.JPG
22:32:01 [App     ] Image loaded  97: IMG_0466.JPG
22:32:01 [App     ] Image loaded  98: IMG_0467.JPG
22:32:01 [App     ] Image loaded  99: IMG_0468.JPG
22:32:01 [App     ] Image loaded 100: IMG_0469.JPG
22:32:01 [App     ] Scene loaded from interface format (1s156ms):
	101 images (101 calibrated) with a total of 767.71 MPixels (7.60 MPixels/image)
	81112 points, 0 vertices, 0 faces
22:32:07 [App     ] Preparing images for dense reconstruction completed: 101 images (5s767ms)
22:32:07 [App     ] error: reference image  27 has no good images in view
22:32:07 [App     ] Selecting images for dense reconstruction completed: 100 images (333ms)
Estimated depth-maps 100 (100%, 2m5s32ms)           
Filtered depth-maps 100 (100%, 6m36s331ms)        
Fused depth-maps 86 (86.00%, 43s, ETA 7s)...Killed

what is it means?Fused depth-maps 86 (86.00%, 43s, ETA 7s)...Killed and error: reference image  27 has no good images in view

**Comment by cdcseacave** [comment]
you might not have enough RAM

**Comment by 945540968** [comment]
thank you for your answer!

**Comment by ThakurSarveshGit** [comment]
> The log is as following, can someone help me? root@ubuntu:~# DensifyPointCloud /root/Documents/openMVS_result/Scene.mvs 22:32:00 [App ] Build date: Feb 8 2018, 05:47:44 22:32:00 [App ] CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz 22:32:00 [App ] RAM: 5.81GB Physical Memory 1022.00MB Virtual Memory 22:32:00 [App ] OS: Linux 4.10.0-28-generic (x86_64) 22:32:00 [App ] SSE & AVX compatible CPU & OS detected 22:32:00 [App ] Command line: /root/Documents/openMVS_result/Scene.mvs 22:32:00 [App ] Camera model loaded: platform 0; camera 0; f 0.902x0.902; poses 100 22:32:00 [App ] Camera model loaded: platform 1; camera 0; f 1.169x1.169; poses 1 22:32:00 [App ] Image loaded 0: IMG_0368.JPG 22:32:00 [App ] Image loaded 1: IMG_0369.JPG 22:32:00 [App ] Image loaded 2: IMG_0370.JPG 22:32:00 [App ] Image loaded 3: IMG_0371.JPG 22:32:00 [App ] Image loaded 4: IMG_0372.JPG 22:32:00 [App ] Image loaded 5: IMG_0373.JPG 22:32:00 [App ] Image loaded 6: IMG_0374.JPG 22:32:00 [App ] Image loaded 7: IMG_0375.JPG 22:32:00 [App ] Image loaded 8: IMG_0376.JPG 22:32:00 [App ] Image loaded 9: IMG_0377.JPG 22:32:00 [App ] Image loaded 10: IMG_0378.JPG 22:32:00 [App ] Image loaded 11: IMG_0379.JPG 22:32:00 [App ] Image loaded 12: IMG_0380.JPG 22:32:00 [App ] Image loaded 13: IMG_0381.JPG 22:32:00 [App ] Image loaded 14: IMG_0382.JPG 22:32:00 [App ] Image loaded 15: IMG_0383.JPG 22:32:00 [App ] Image loaded 16: IMG_0384.JPG 22:32:00 [App ] Image loaded 17: IMG_0385.JPG 22:32:00 [App ] Image loaded 18: IMG_0386.JPG 22:32:00 [App ] Image loaded 19: IMG_0387.JPG 22:32:00 [App ] Image loaded 20: IMG_0388.JPG 22:32:00 [App ] Image loaded 21: IMG_0389.JPG 22:32:00 [App ] Image loaded 22: IMG_0390.JPG 22:32:00 [App ] Image loaded 23: IMG_0391.JPG 22:32:00 [App ] Image loaded 24: IMG_0392.JPG 22:32:00 [App ] Image loaded 25: IMG_0393.JPG 22:32:00 [App ] Image loaded 26: IMG_0394.JPG 22:32:00 [App ] Image loaded 27: IMG_0396.JPG 22:32:00 [App ] Image loaded 28: IMG_0397.JPG 22:32:00 [App ] Image loaded 29: IMG_0398.JPG 22:32:01 [App ] Image loaded 30: IMG_0399.JPG 22:32:01 [App ] Image loaded 31: IMG_0400.JPG 22:32:01 [App ] Image loaded 32: IMG_0401.JPG 22:32:01 [App ] Image loaded 33: IMG_0402.JPG 22:32:01 [App ] Image loaded 34: IMG_0403.JPG 22:32:01 [App ] Image loaded 35: IMG_0404.JPG 22:32:01 [App ] Image loaded 36: IMG_0405.JPG 22:32:01 [App ] Image loaded 37: IMG_0406.JPG 22:32:01 [App ] Image loaded 38: IMG_0407.JPG 22:32:01 [App ] Image loaded 39: IMG_0408.JPG 22:32:01 [App ] Image loaded 40: IMG_0409.JPG 22:32:01 [App ] Image loaded 41: IMG_0410.JPG 22:32:01 [App ] Image loaded 42: IMG_0411.JPG 22:32:01 [App ] Image loaded 43: IMG_0412.JPG 22:32:01 [App ] Image loaded 44: IMG_0413.JPG 22:32:01 [App ] Image loaded 45: IMG_0414.JPG 22:32:01 [App ] Image loaded 46: IMG_0415.JPG 22:32:01 [App ] Image loaded 47: IMG_0416.JPG 22:32:01 [App ] Image loaded 48: IMG_0417.JPG 22:32:01 [App ] Image loaded 49: IMG_0418.JPG 22:32:01 [App ] Image loaded 50: IMG_0419.JPG 22:32:01 [App ] Image loaded 51: IMG_0420.JPG 22:32:01 [App ] Image loaded 52: IMG_0421.JPG 22:32:01 [App ] Image loaded 53: IMG_0422.JPG 22:32:01 [App ] Image loaded 54: IMG_0423.JPG 22:32:01 [App ] Image loaded 55: IMG_0424.JPG 22:32:01 [App ] Image loaded 56: IMG_0425.JPG 22:32:01 [App ] Image loaded 57: IMG_0426.JPG 22:32:01 [App ] Image loaded 58: IMG_0427.JPG 22:32:01 [App ] Image loaded 59: IMG_0428.JPG 22:32:01 [App ] Image loaded 60: IMG_0429.JPG 22:32:01 [App ] Image loaded 61: IMG_0430.JPG 22:32:01 [App ] Image loaded 62: IMG_0431.JPG 22:32:01 [App ] Image loaded 63: IMG_0432.JPG 22:32:01 [App ] Image loaded 64: IMG_0433.JPG 22:32:01 [App ] Image loaded 65: IMG_0434.JPG 22:32:01 [App ] Image loaded 66: IMG_0435.JPG 22:32:01 [App ] Image loaded 67: IMG_0436.JPG 22:32:01 [App ] Image loaded 68: IMG_0437.JPG 22:32:01 [App ] Image loaded 69: IMG_0438.JPG 22:32:01 [App ] Image loaded 70: IMG_0439.JPG 22:32:01 [App ] Image loaded 71: IMG_0440.JPG 22:32:01 [App ] Image loaded 72: IMG_0441.JPG 22:32:01 [App ] Image loaded 73: IMG_0442.JPG 22:32:01 [App ] Image loaded 74: IMG_0443.JPG 22:32:01 [App ] Image loaded 75: IMG_0444.JPG 22:32:01 [App ] Image loaded 76: IMG_0445.JPG 22:32:01 [App ] Image loaded 77: IMG_0446.JPG 22:32:01 [App ] Image loaded 78: IMG_0447.JPG 22:32:01 [App ] Image loaded 79: IMG_0448.JPG 22:32:01 [App ] Image loaded 80: IMG_0449.JPG 22:32:01 [App ] Image loaded 81: IMG_0450.JPG 22:32:01 [App ] Image loaded 82: IMG_0451.JPG 22:32:01 [App ] Image loaded 83: IMG_0452.JPG 22:32:01 [App ] Image loaded 84: IMG_0453.JPG 22:32:01 [App ] Image loaded 85: IMG_0454.JPG 22:32:01 [App ] Image loaded 86: IMG_0455.JPG 22:32:01 [App ] Image loaded 87: IMG_0456.JPG 22:32:01 [App ] Image loaded 88: IMG_0457.JPG 22:32:01 [App ] Image loaded 89: IMG_0458.JPG 22:32:01 [App ] Image loaded 90: IMG_0459.JPG 22:32:01 [App ] Image loaded 91: IMG_0460.JPG 22:32:01 [App ] Image loaded 92: IMG_0461.JPG 22:32:01 [App ] Image loaded 93: IMG_0462.JPG 22:32:01 [App ] Image loaded 94: IMG_0463.JPG 22:32:01 [App ] Image loaded 95: IMG_0464.JPG 22:32:01 [App ] Image loaded 96: IMG_0465.JPG 22:32:01 [App ] Image loaded 97: IMG_0466.JPG 22:32:01 [App ] Image loaded 98: IMG_0467.JPG 22:32:01 [App ] Image loaded 99: IMG_0468.JPG 22:32:01 [App ] Image loaded 100: IMG_0469.JPG 22:32:01 [App ] Scene loaded from interface format (1s156ms): 101 images (101 calibrated) with a total of 767.71 MPixels (7.60 MPixels/image) 81112 points, 0 vertices, 0 faces 22:32:07 [App ] Preparing images for dense reconstruction completed: 101 images (5s767ms) 22:32:07 [App ] error: reference image 27 has no good images in view 22:32:07 [App ] Selecting images for dense reconstruction completed: 100 images (333ms) Estimated depth-maps 100 (100%, 2m5s32ms) Filtered depth-maps 100 (100%, 6m36s331ms) Fused depth-maps 86 (86.00%, 43s, ETA 7s)...Killed
> 
> what is it means?Fused depth-maps 86 (86.00%, 43s, ETA 7s)...Killed and error: reference image 27 has no good images in view

One way to overcome this is, increase your SWAP memory. I was getting same error as all memory(8GB) was being used. Added a SWAP memory of 4GB and it worked.
