### ISSUE TITLE
An error in OpenMVS Building files!

### ISSUE THREAD

**Issue by 945540968** [cdcseacave/openMVS#299]
Hi,  cdcseacave!  When running DensifyPointCloud, I receive a problem as following:
root@ubuntu:~/Documents# DensifyPointCloud /root/Documents/test_result/openMVS_result/scene.mvs
22:57:05 [App     ] Build date: Feb  9 2018, 22:38:20
22:57:05 [App     ] CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
22:57:05 [App     ] RAM: 3.84GB Physical Memory 4.00GB Virtual Memory
22:57:05 [App     ] OS: Linux 4.10.0-28-generic (x86_64)
22:57:05 [App     ] SSE & AVX compatible CPU & OS detected
22:57:05 [App     ] Command line: /root/Documents/test_result/openMVS_result/scene.mvs
22:57:05 [App     ] Camera model loaded: platform 0; camera  0; f 1.058x1.058; poses 11
22:57:05 [App     ] error: failed loading image header
22:57:05 [App     ] error: failed reloading image '/root/Documents/test_result/openMVS_result/100_7100.JPG'
22:57:05 [App     ] error: invalid project
My friends say the reason is lacking of Devil library. But your building files hasn't mentioned this library.

What's more, i find Devil library can be installed successfully before openMVS's installation. But Devil library can't be installed after i finished the configuration of openMVS.

Error is as following:
/usr/bin/ld: /usr/local/lib/libpng.a(png.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpng.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src-IL/CMakeFiles/IL.dir/build.make:2104: recipe for target 'lib/x64/libIL.so' failed
make[2]: *** [lib/x64/libIL.so] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src-IL/CMakeFiles/IL.dir/all' failed
make[1]: *** [src-IL/CMakeFiles/IL.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cdcseacave** [comment]
Pls use the same procedure you used to compile it for the issue #298.

**Comment by rozentill** [comment]
Hi, I also met the same problem : 

17:03:32 [App     ] Build date: Mar  2 2018, 16:29:54                                        │pIntrisics.wait()
17:03:32 [App     ] CPU: Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz  
17:03:32 [App     ] RAM: 7.67GB Physical Memory 7.88GB Virtual Memory 
17:03:33 [App     ] OS: Linux 4.13.0-32-generic (x86_64)       
17:03:33 [App     ] SSE & AVX compatible CPU & OS detected                         
17:03:33 [App     ] Command line: ../openMVG_Build/data/Face_5/output/Scene/scene.mvs  
17:03:33 [App     ] Camera model loaded: platform 0; camera  0; f 1.182x1.182; poses 55   
17:03:33 [App     ] error: failed loading image header      
17:03:33 [App     ] error: failed reloading image '/home/yaoyuan/Project/openMVS_build/data/Face_5/output/Scene/1003882810.jpg'                                                           
17:03:33 [App     ] error: invalid project 

Do you know what's the problem? Thanks a lot!

**Comment by rozentill** [comment]
Fixed now by changing the relative path to the absolute path when exporting MVS from MVG.

**Comment by 945540968** [comment]
Hi @rozentill ，can you tell me the details about how do you solve the problem? For example, where should I change the relative path to absolute path? Thank you!

**Comment by 945540968** [comment]
Hi,@rozentill,Can you tell me which os do you build openmvs on? Windows or ubuntu?

**Comment by rozentill** [comment]
Hi @945540968  I wanted to export MVG to MVS, so I followed this page http://openmvg.readthedocs.io/en/latest/software/MVS/OpenMVS/  and typed the following command using openMVG : 

`$openMVG_main_openMVG2openMVS -i PATH/sfm_data.(json/xml/bin) -d OUTPUT_PATH -o OUTPUT_PATH/Scene`

but the path I typed in this command was used later when calling 

`$DensifyPointCloud scene.mvs`

So the path is wrong and can be noticed here : 

17:03:33 [App ] error: failed reloading image '/home/yaoyuan/Project/openMVS_build/data/Face_5/output/Scene/1003882810.jpg'

Best,
Rozentill

**Comment by 945540968** [comment]
@rozentill, I always use absolute path, but I still met the problem. Someone tell me the reason is lacking Devil library.But I can not install the library successfully! Do you use ubuntu as your work platform? I suspect that my ubuntu have some problems.

**Comment by 945540968** [comment]
Oh, I have seen your reply. ubuntu 16.04?have you ever install devil library?

**Comment by rozentill** [comment]
I just followed the installation process here https://github.com/cdcseacave/openMVS/wiki/Building . Yeah I am using ubuntu 16.04.

**Comment by 945540968** [comment]
Thank you for your reply! It seems that my problem is not normal so that almost people have not the phenomenon like me!

**Comment by XudongYong** [comment]
@945540968 Hi, maybe I can solve your problem. Actually, I faced the same issue as yours. After reading almost every suggestions here, I attempted to build openMVS with JPEG_INCLUDE_DIR and JPEG_LIBRARY set in cmake-gui. Here, I set JPEG_INCLUDE_DIR as "../opencv/sources/3rdparty/libjpeg" and JPEG_LIBRARY as "openCV/3rdparty/lib/Release/libjpeg.lib". After that, rebuild it and I found this issue is solved, and DensifyPointCloud could read jpg pictures normally. Hope this info could help you.

**Comment by 945540968** [comment]
@XudongYong Thanks for your answer!
In the begin, i built openMVS on windows, but i found DensifyPointCloud counldn't run. Someone told me it may because I don't configure MVS with jpeg library. But i counldn't find JPEG_INCLUDE_DIR in MVS's cmake parameters. So i given up windows.
Unfortunately, i met the same problem(DensifyPointCloud can't run) on Ubuntu 16.04.....
Yesterday, i build openMVS on docker's ubuntu successfully just as the building files on github. But i still faild on my ubuntu virtual machine.
 I notice you use "cmake-gui", do you build openMVS on windows?

**Comment by XudongYong** [comment]
@945540968 Yes, I encounter this issue when building openMVS on windows. But when building on Ubuntu 16.04 as well as 14.04, everythins is ok. On my side, I can find JPEG_INCLUDE_DIR and JPEG_LIBRARY in cmake-gui on Windows. If you cannot find these tags, try to add them manually and maybe it works.

**Comment by 945540968** [comment]
@XudongYong  Thanks for your answer，I will try your method. What”s more, I have built openmvs successfully in ubuntu using a tool named Docker.

**Comment by 945540968** [comment]
If someone can't build openmvg +openmvs successfully on ubuntu 16.04, you can try Docker!

**Comment by Jaspr987** [comment]
@945540968 Which Docker image do you use? I find one which is outdated and don't have openMVG_main_openMVG2openMVS in openMVG.

**Comment by 945540968** [comment]
@Jaspr987 I have built a openmvg+openmvs(554198480/openmvg-openmvs:v1) image based on ubuntu 16.04, and you can find it on dock hub.
