### ISSUE TITLE
Usage question 

### ISSUE THREAD

**Issue by pyp22** [cdcseacave/openMVS#30]
hi @cdcseacave ,

I'm meeting a pb running InterfaceOpenMVG. It does not find images dataset. My work dirs:

/home/dataset is where the images are stored
/home/dataset/OUT is openMVG results
/home/dataset/OUT/MVS is openMVS working dir

While trying to run InterfaceOpenMVG i have the following error. It doubles dir:

13:53:47 [App     ] Command line: -i reconstruction_sequential/sfm_data.json -o MVS/scene.mvs
13:53:49 [App     ] Imported data: 8 cameras, 74 poses, 84 images, 65127 vertices
Error: Couldn't open /home/dataset/OUT//home/dataset/Eodez//1M6A5597.JPG fopen returned 0Empty JPEG image (DNL not supported)

I remarked the same pb with prior version with the 'images' dir that was solved by symlinking it.

Regards,

PY

**Comment by cdcseacave** [comment]
fixed in develop branch
