### ISSUE TITLE
Issues Generating Project with CMake

### ISSUE THREAD

**Issue by Scuwr** [cdcseacave/openMVS#301]
I am having issues generating the project from cmake on Windows 10. Specifically, CMake is unable to load the OpenCV dependency. I notice that you removed the FindOpenCV.cmake file a little over a year ago, and I'm sure there is some idiosyncrasy I'm missing to get this working. Are we expected to generate our own FindOpenCV cmake file?

Error received:
`CMake Error at CMakeLists.txt:120 (FIND_PACKAGE):`
`  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has`
`  asked CMake to find a package configuration file provided by "OpenCV", but`
`  CMake did not find one.`
``
 `Could not find a package configuration file provided by "OpenCV" with any`
 `of the following names:`
``
`    OpenCVConfig.cmake`
`    opencv-config.cmake`
``
`  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set`
`  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"`
`  provides a separate development package or SDK, be sure it has been`
`  installed.``

I am running CMake with the following parameters:
`cmake . ../src -DCMAKE_BUILD_TYPE=RELEASE -DEIGEN_DIR="../Eigen" -DOPENCV_DIR="../Opencv"`
`-DCERES_DIR="../Ceres" -DCGAL_DIR="../CGAL" -DVCG_DIR="../VCG"`

Thank you for your help!

**Comment by cdcseacave** [comment]
The CMake error provides also the solution, you need to set `OpenCV_DIR` (case sensitive) to the path where one of those files exist.

**Comment by Scuwr** [comment]
Ah, case sensitive, that'll do it. I'm still a bit new to CMake, so these are my growing pains. 

When, and if, I get the whole system compiled, would you mind if I update the windows compile instructions on the project?

Thank you for your time and help!

**Comment by cdcseacave** [comment]
pls do, from the beginning of the project I encouraged everybody to contribute, but till now there are nearly 0 contributions

**Comment by cdcseacave** [comment]
vcpkg is now supported by the latest develop
