### ISSUE TITLE
sfm with control point and  no good image in view error

### ISSUE THREAD

**Issue by TMwhuhan** [cdcseacave/openMVS#302]
### Specifications like the version of the project, operating system, and hardware
 I compile latest  master version mvs in win7 system
### Steps to reproduce the problem
 It's run and get good point cloud with normal sfm (just relative orientation)
 but when using sfm  after absolute orientation,  the densifypointcloud get no good image in view error.
 Here is the some line of nvm file (this project has 73 images)
 DSC05.JPG 5262.261617 0.063721 0.478095 -0.871453 0.089076 431156.282204 3446654.264266 385.143269 0 0
DSC06.JPG 5262.261617 0.127749 0.381219 -0.915602 -0.005027 431200.997333 3446600.688534 386.423968 0 0 
any idea with right parameter with this big scale sfm?
I think maybe fMinArea, fMinScale and fMaxScale~~

**Comment by cdcseacave** [comment]
this is a recurring issue, answer few times already: you need to do the absolute pose alignment after the dense reconstruction, not before
