### ISSUE TITLE
Can we seperate Depth Map Estimation step and Depth Map Fusion step in openMVS?

### ISSUE THREAD

**Issue by ManishSahu53** [cdcseacave/openMVS#304]
### Specifications like the version of the project, operating system, and hardware
Latest Build openMVS, 
PC - 32 GB Ram, GTX1060 6GB
### Steps to reproduce the problem
I want to know if I can separate Depth Map Estimation and Fusion step. I thought that this would increase scalability of openMVS and help us run larger project since Fusion step takes whole RAM.
The Idea is computing depth map of all images, then fusing few images at a time according to RAM available. Thanks

**Comment by cdcseacave** [comment]
Yes, that can be done relatively easy (though I think some points will be duplicated). Feel free to contribute with this functionality.

**Comment by ManishSahu53** [comment]
Can you guide how to start where to look in the code? Then it would be very helpful.
Thanks

**Comment by cdcseacave** [comment]
`SceneDensify.cpp::FuseDepthMaps()` loads all depth-maps and processes all of them at once. Split the depth maps in few overlapping clusters and process them individually.

**Comment by ManishSahu53** [comment]
@cdcseacave  I am working on memory consumption issue. However I cant understand in SceneDensify.cpp::FuseDepthMaps() https://github.com/cdcseacave/openMVS/blob/877917fd8b9085b65176ab00ee01f620c2ba8a41/libs/MVS/SceneDensify.cpp#L1301. I this loop MVS is consuming very high memory and as number of images increases memory increases. I couldn't understand how <<connection>> is consuming memory. I thought it is only storing size of neighbours only. Can you tell me how and where memory is consuming in the loop.

**Comment by cdcseacave** [comment]
`IncRef()` loads the depth map for each image

**Comment by ManishSahu53** [comment]
I saw that images with strong connection's score are processed first. I couldn't understand why this convention is followed. Does this give greater accuracy/ stability of reconstruction?

**Comment by ManishSahu53** [comment]
[UPDATE] I could bypass memory error and generated point cloud to 3600 images and each of 24MP. However I wanted to ask @cdcseacave if considering depth map according to score increases stability of reconstruction or not?

**Comment by cdcseacave** [comment]
great job @ManishSahu53, congrats
do you mean the confidence maps?
that depends on the fusion algorithm; for the one implemented in OpenMVS I don't think it is making a huge difference

**Comment by ManishSahu53** [comment]
Thanks. I will soon put a pull request.

**Comment by ManishSahu53** [comment]
I working on bounding box right now

**Comment by ManishSahu53** [comment]
No i meant connections.score function. In the code you have sorted this score then processed.https://github.com/cdcseacave/openMVS/blob/877917fd8b9085b65176ab00ee01f620c2ba8a41/libs/MVS/SceneDensify.cpp#L1310 
Sorted Here
https://github.com/cdcseacave/openMVS/blob/877917fd8b9085b65176ab00ee01f620c2ba8a41/libs/MVS/SceneDensify.cpp#L1313

**Comment by cdcseacave** [comment]
no, that should not make a big difference either

**Comment by ManishSahu53** [comment]
I generated dense point cloud from ~3600 images without clustering.
![image](https://user-images.githubusercontent.com/27155127/37523122-025c296e-294c-11e8-96a0-e4518b613346.png)

**Comment by cdcseacave** [comment]
great, so why do you need clustering for than?

**Comment by ManishSahu53** [comment]
Yes i don't have to do clustering now

**Comment by jpwhitney** [comment]
This is awesome! Many people, including myself have ran info memory issues during dense reconstruction.
If you've managed a workaround to the memory issue it could clearly help with scalability of this framework.
I would be very interested in using this new approach with some of my datasets to see if I can get good results.
Will you be making your changes available, or do you have a fork with these changes?

**Comment by ManishSahu53** [comment]
@jpwhitney I will be posting all changes online soon. I am still testing its stability and quality of reconstruction so haven't put a pull request.

**Comment by cdcseacave** [comment]
Thanks @ManishSahu53!
Clustering might still be needed though if more than dense point-cloud is wanted.

**Comment by KeoChi** [comment]
Hello! I also encountered a memory error when FuseDepthMaps(). Has the latest version solved this problem? @cdcseacave @ManishSahu53 Thank you!

**Comment by cdcseacave** [comment]
no, I didn't have time to address this, and nobody else seems interested in helping

**Comment by KeoChi** [comment]
@ManishSahu53 Did you submit all changes online? @cdcseacave How can I see all his changes? Thank you.

**Comment by cdcseacave** [comment]
There is a misunderstanding, nobody did any changes. See my previous post.

**Comment by cdcseacave** [comment]
it is addressed in #438

**Comment by pierotofy** [comment]
Hey @cdcseacave :hand: my organization (UAV4GEO) is interested in sponsoring the development of this feature (reduce memory usage for the depthmap fusion step via clustering). If you have availability, what's a good way to get in touch? :pray:

**Comment by cdcseacave** [comment]
feel free to contact me by email

**Comment by pierotofy** [comment]
Sent :+1:
