### ISSUE TITLE
Parsing .dmap

### ISSUE THREAD

**Issue by ibexibex** [cdcseacave/openMVS#305]
### Specifications like the version of the project, operating system, and hardware
Windows pre-build binaries. 
### Steps to reproduce the problem
I would like to read the floating point depth map created during the dens reconstruction step (.dmap), and convert it to a OpenCV matrix. By inspecting the OpenMVS code source it seems that boost serialization is used to write the dmap file, but I have some trouble to use it to read the dmap file to an OpenCV matrix. 
I have written this function:
```
template <typename TYPE>
void load(TYPE& obj, const std::string& path){

    std::ifstream fs(path, std::ios::in | std::ios::binary);
    std::cout << fs.is_open() << std::endl;
    namespace io = boost::iostreams;
    io::filtering_streambuf<io::input> ffs;
    ffs.push(io::zlib_decompressor());
    ffs.push(fs);
    boost::archive::binary_iarchive ar(ffs, 0);
    ar >> obj;
}
```
But I don't know how the cv::Mat serialization is done in OpenMVS.
Is there a simple way to do that without using OpenMVS (I want to avoid the compilation and linking steps) ?

Thanks!

**Comment by d-b-h** [comment]
Hi @ibexibex ! This is very late, but I am trying to do the same thing. Did you ever work out how to get the depth map in matrix form?

**Comment by cdcseacave** [comment]
indeed, in the latest develop the DMAP files are stored in an easy to parse format (not using BOOST anymore), pls check `ImportDepthDataRaw()` in `DepthMap.cpp` for an example.

**Comment by Uncle-Justice** [comment]
In ```ImportDepthDataRaw()```, it seems that there is no limit to the input file format(no comments or exceptions). 

Does it mean i can use formats like ```.png``` instead of ```dmap``` to import the depth data?

**Comment by cdcseacave** [comment]
No, the extension in not important, important is the binary data inside the file to be the expected format.
