### ISSUE TITLE
does openMVS support GPU / CUDA computing?

### ISSUE THREAD

**Issue by comsyspro** [cdcseacave/openMVS#306]
### Specifications like the version of the project, operating system, and hardware
Windows OS, Intel CPU, Nvidia GPU with CUDA

### Steps to reproduce the problem
I downloaded the openMVS_sample file including the Windows executables from here: https://github.com/cdcseacave/openMVS_sample/releases/tag/v0.7a

Now I want to know if openMVS also support GPU / CUDA computing as I've  read something that the refinement step can run as CUDA (RefineMeshCUDA.exe). But this file isn't included in the openMVS_sample file. 

Please can someone explain which of the steps (DensifyPointCloud.exe - ReconstructMesh.exe -
 RefineMesh.exe / RefineMeshCUDA.exe - TextureMesh.exe) can run with CUDA and where to find the binaries for Windows OS?

Thanks.

**Comment by ManishSahu53** [comment]
Only Mesh refining step can be Cuda enabled. All other work on CPU only

**Comment by pmoulon** [comment]
@beta-tester here a project that can do MVS only by using your CPU ;-)

**Comment by calmelo** [comment]
> Only Mesh refining step can be Cuda enabled. All other work on CPU only

Can TextureMesh only work on CPU? I want to speed TextureMesh using CUDA, and are there some ways to achieve it? Thanks!

**Comment by calmelo** [comment]
> Only Mesh refining step can be Cuda enabled. All other work on CPU only

Can TextureMesh only work on CPU? I want to speed TextureMesh using CUDA, and are there some ways to achieve it? Thanks!

**Comment by cdcseacave** [comment]
yes, use OpenGL to render the mesh in each view instead of the CPU renderer
