### ISSUE TITLE
error: unknown image format again

### ISSUE THREAD

**Issue by xuhuanzhimeng** [cdcseacave/openMVS#308]
### Steps to reproduce the problem
14:38:04 [App     ] Build date: Mar 14 2018, 23:08:27
14:38:04 [App     ] CPU: AMD A8-5550M APU with Radeon(tm) HD Graphics   
14:38:04 [App     ] RAM: 3.21GB Physical Memory 8.00TB Virtual Memory
14:38:04 [App     ] OS: Windows 7 (SP1) x64
14:38:04 [App     ] SSE & AVX compatible CPU & OS detected
14:38:04 [App     ] Command line: scene.mvs -w E:\final_test\output\mvs
14:38:04 [App     ] Camera model loaded: platform 0; camera  0; f 1.056x1.056; poses 11
14:38:04 [IO      ] error: unknown image format 'E:/final_test/output/mvs/100_7100.JPG'
14:38:04 [App     ] error: failed loading image header
14:38:04 [App     ] error: failed reloading image 'E:/final_test/output/mvs/100_7100.JPG'
14:38:04 [App     ] error: invalid project

I have read all the questions and answers but I still don't how to solve this problem. I have replaced MAKE_PATH_FULL(WORKING_FOLDER_FULL, image.name); with MAKE_PATH_SAFE(image.name); in code and recompile but still not work. Also I didn't use VisualSFM. I just use openMVG to produce scene.bin and met the problem when using DensityPointCloud.exe.  And I'm confused CMake does not have JPEG_INCLUDE_DIR and JPEG_LIBRARY. Shall we add entry for them? 
Anyone has a specific solution?

**Comment by xuhuanzhimeng** [comment]
Finally I locate the problem in  "Image.cpp"
in this function:
CImage* CImage::Create(LPCTSTR szName, IMCREATE mode)
_IMAGE_BMP,_IMAGE_TGA,_IMAGE_DDShave been defined , while _IMAGE_PNG,_IMAGE_JPG,_IMAGE_TIFF not(in vs2015 the font in grey color).
That is because in "Common.h":
_USE_PNG  , _USE_JPG , _USE_TIFF are not defined.
Finally in Libs/IO/CMakeList.txt, for example 
FIND_PACKAGE(PNG QUIET)
if(PNG_FOUND)
	INCLUDE_DIRECTORIES(${PNG_INCLUDE_DIRS})
	ADD_DEFINITIONS(${PNG_DEFINITIONS} -D_USE_PNG)
	SET(_USE_PNG TRUE CACHE INTERNAL "")
else()
	SET(PNG_LIBRARIES "")
endif()

So PNG,JPG,TIFF are not found by FIND_PACKAGE() 
I am confused in using cmake. Anyone could teach me how to let cmake find them?

**Comment by xuhuanzhimeng** [comment]
I have solved this problem. I feel so bad!

**Comment by slowly77** [comment]
hi @zcoo how you fix your problem,i don't know how to deal with it!please help me !
