### ISSUE TITLE
#branch=develop compilation error

### ISSUE THREAD

**Issue by pyp22** [cdcseacave/openMVS#31]
Hi @cdcseacave ,

Meeting this error on compilation: (cotire & google-glog ?)

In file included from /mnt/pacman/NuxSFM-2.0/testing/computer-vision/openMVS/src/openMVS/libs/Common/Types.h:42:0,
                 from /mnt/pacman/NuxSFM-2.0/testing/computer-vision/openMVS/src/openMVS/libs/Common/Common.h:176,
                 from /mnt/pacman/NuxSFM-2.0/testing/computer-vision/openMVS/src/openMVS/openMVS_Build/libs/Common/cotire/Common_CXX_prefix.cxx:4,
                 from /mnt/pacman/NuxSFM-2.0/testing/computer-vision/openMVS/src/openMVS/openMVS_Build/libs/Common/cotire/Common_CXX_prefix.hxx:4:
/usr/include/c++/5.2.0/functional: In instantiation of 'struct std::_Bind_check_arity<void (SEACAVE::LogFile::*)(const SEACAVE::String&), SEACAVE::LogFile*>':
/usr/include/c++/5.2.0/functional:1439:12:   required from 'struct std::_Bind_helper<false, void (SEACAVE::LogFile::*)(const SEACAVE::String&), SEACAVE::LogFile*>'
/usr/include/c++/5.2.0/functional:1462:5:   required by substitution of 'template<class _Func, class ... _BoundArgs> typename std::_Bind_helper<std::__is_socketlike<_Func>::value, _Func, _BoundArgs ...>::type std::bind(_Func&&, _BoundArgs&& ...) [with _Func = void (SEACAVE::LogFile::*)(const SEACAVE::String&); _BoundArgs = {SEACAVE::LogFile*}]'
../../../libs/Common/Log.cpp:186:56:   required from here
/usr/include/c++/5.2.0/functional:1426:7: error: static assertion failed: Wrong number of arguments for pointer-to-member
       static_assert(_Varargs::value

/usr/include/c++/5.2.0/functional:1426:7: error: static assertion failed: Wrong number of arguments for pointer-to-member
In file included from /mnt/pacman/NuxSFM-2.0/testing/computer-vision/openMVS/src/openMVS/libs/Common/Types.h:65:0,
                 from /mnt/pacman/NuxSFM-2.0/testing/computer-vision/openMVS/src/openMVS/libs/Common/Common.h:176,
                 from /mnt/pacman/NuxSFM-2.0/testing/computer-vision/openMVS/src/openMVS/openMVS_Build/libs/Common/cotire/Common_CXX_prefix.cxx:4,
                 from /mnt/pacman/NuxSFM-2.0/testing/computer-vision/openMVS/src/openMVS/openMVS_Build/libs/Common/cotire/Common_CXX_prefix.hxx:4:
/mnt/pacman/NuxSFM-2.0/testing/computer-vision/openMVS/src/openMVS/libs/Common/FastDelegate.h: In instantiation of 'void fastdelegate::detail::ClosurePtr<GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr>::CopyFrom(DerivedClass*, const fastdelegate::DelegateMemento&) [with DerivedClass = fastdelegate::FastDelegate1<const SEACAVE::String&, void>; GenericMemFunc = void (fastdelegate::detail::GenericClass::*)(const SEACAVE::String&); StaticFuncPtr = void (*)(const SEACAVE::String&); UnvoidStaticFuncPtr = void (*)(const SEACAVE::String&)]':
/mnt/pacman/NuxSFM-2.0/testing/computer-vision/openMVS/src/openMVS/libs/Common/FastDelegate.h:951:3:   required from 'fastdelegate::FastDelegate1<Param1, RetType>::FastDelegate1(const fastdelegate::FastDelegate1<Param1, RetType>&) [with Param1 = const SEACAVE::String&; RetType = void]'
/mnt/pacman/NuxSFM-2.0/testing/computer-vision/openMVS/src/openMVS/libs/Common/FastDelegate.h:1676:7:   required from here
/mnt/pacman/NuxSFM-2.0/testing/computer-vision/openMVS/src/openMVS/libs/Common/FastDelegate.h:756:38: warning: unused parameter 'pParent' [-Wunused-parameter]
  inline void CopyFrom (DerivedClass *pParent, const DelegateMemento &right) {
                                      ^
libs/Common/CMakeFiles/Common.dir/build.make:176: recipe for target 'libs/Common/CMakeFiles/Common.dir/Log.cpp.o' failed

Best regards,

PY

**Comment by cdcseacave** [comment]
I thought you were able to compile it before. What changed? Cause I didn't change anything related to those error you got.

**Comment by pyp22** [comment]
Correct, but using the #branch=master. I'm trying the  #branch=develop on the same machine. Nohting changed on it.

**Comment by pmoulon** [comment]
Be sure you remove the cmake cache file

Regards/Cordialement,
Pierre M

2015-11-02 11:13 GMT+01:00 Pierre-Yves Paranthoën <notifications@github.com>
:

**Comment by pyp22** [comment]
I'm compiling it from scratch without no previous compilation. I rechecked compiling master branch and it works. I'm trying to compile dev branch using the same command line parameters. Strange. I keep investigating.

Best regards

PY

**Comment by pyp22** [comment]
Found why. Due to specific gcc 5.02 default optimizations on Arch64.

**Comment by cdcseacave** [comment]
Could you detail a bit what exactly was the problem so that others can ovoid it?
Thanks!
