### ISSUE TITLE
Some texture is missing after running TextureMesh

### ISSUE THREAD

**Issue by XudongYong** [cdcseacave/openMVS#318]
Hi @cdcseacave and @pmoulon ,

Thanks for your great job! Currently, I followed the pipeline as your sample in Windows and found an issue. 

The generated mesh was normal. But in the final textured mesh after running TextureMesh.exe, there were a big region without normal texture but just yellow color. The snapshot is as follows.
![default](https://user-images.githubusercontent.com/17871648/38715080-c3eb317c-3f0b-11e8-9006-02412a89244d.PNG)
Have anyone faced the same issue? Do you have any suggestion? Thanks a lot.

**Comment by cdcseacave** [comment]
that is strange, never seen before
did you pre-process the mesh in any way before texturing?

**Comment by XudongYong** [comment]
We only introduced GPS info during openMVG, and then all other processes in openMVS were the same as yours. Meanwhile, I noticed sometimes there were small yellow regions as this link: [https://user-images.githubusercontent.com/34540802/34980518-17ceb148-faa5-11e7-8cf3-e2f9c4507c6c.png](url)

Do you think my issue with a big empty region is the same as others with small regions?

**Comment by cdcseacave** [comment]
no, this time should be texture
Pls try without adding GPS info
all datasets you tried have same problem?

**Comment by XudongYong** [comment]
@cdcseacave Thanks for your reply. I tried it without adding GPS and the final texture result was normal. So I think this problem is caused by GPS and I will look deep into it. Thanks a lot.
