### ISSUE TITLE
[texture output] proposal

### ISSUE THREAD

**Issue by pyp22** [cdcseacave/openMVS#32]
Hi @cdcseacave ,

PNG texture file might be huge sometimes. It might be a pb on 'small' machines or some kind of 3D editing softs.

I'm wondering if a jpg or resized file would be easier to use. Or maybe small multiple png file, e.g. scene_mesh_texture0.png to scene_mesh_textureN.png ?

Something like  TextureMesh --setoutput-texture-rez &  --setoutput-texture-format ? 

Regards

PY

**Comment by cdcseacave** [comment]
You do not need special software to do that. You can  resize the texture or convert it to any format using any image processing tool.

**Comment by pyp22** [comment]
Yes i know ;) It was just and idea about ergonomy. My last test provided an approx 400Mo texture file that even meshlab was unable to open. I had to downscale it.
