### ISSUE TITLE
Using OpenMVS as a third party library

### ISSUE THREAD

**Issue by prakruti** [cdcseacave/openMVS#320]
### Specifications like the version of the project, operating system, and hardware
Ubuntu 14.04, 16 GB RAM machine

### Steps to reproduce the problem
Thanks for your work on OpenMVS! I am using OpenMVS as a third party library and have built and installed it

This is what my CMakeLists.txt looks like 

`
find_package(OpenMVS CONFIG REQUIRED)  
include_directories(${OpenMVS_INCLUDE_DIRS})  
add_executable (main src/main.cpp)  
target_link_libraries (main  ${OpenMVS_LIBRARIES})  
`
When I use the following line in main.cpp

`#include "OpenMVS/MVS/Common.h"`

I get the following error. This is in a part of the code between #if 0 #endif  that throws up the error

`In file included from /usr/local/include/OpenMVS/Common/Rotation.h:586:0,  
                 from /usr/local/include/OpenMVS/Common/Types.h:2731,  
                 from /usr/local/include/OpenMVS/Common/Common.h:176,  
                 from /usr/local/include/OpenMVS/MVS/Common.h:42,  
                 from /home/user/main.cpp:19:  
/usr/local/include/OpenMVS/Common/Rotation.inl: In member function   ‘SEACAVE::TRMatrixBase<TYPE>::Vec SEACAVE::TRMatrixBase<TYPE>::GetRotationAxisAngle() const’:  
/usr/local/include/OpenMVS/Common/Rotation.inl:1312:19: error: ‘T’ was not declared in this scope
  Eigen::AngleAxis<T> aa;  
                   ^
/usr/local/include/OpenMVS/Common/Rotation.inl:1312:20: error: template argument 1 is invalid
  Eigen::AngleAxis<T> aa;  
                    ^
/usr/local/include/OpenMVS/Common/Rotation.inl:1312:24: error: invalid type in declaration before ‘;’ token
  Eigen::AngleAxis<T> aa;  
                        ^
/usr/local/include/OpenMVS/Common/Rotation.inl:1313:5: error: request for member ‘fromRotationMatrix’ in ‘aa’, which is of non-class type ‘int’
  aa.fromRotationMatrix(Base::EMatMap((TYPE*)this));  
     ^
/usr/local/include/OpenMVS/Common/Rotation.inl:1314:21: error: request for member ‘angle’ in ‘aa’, which is of non-class type ‘int’
  angle_axis[0] = aa.angle() * aa.axis()[0];  
                     ^
`

And so on. Any idea why this is happening and what I can do to prevent it? Thanks!

**Comment by cdcseacave** [comment]
it seems that the define `_USE_EIGEN` is not defined, so either Eigen lib was not found during CMake, or there might be a problem with CMake scripts in OpenMVS

**Comment by prakruti** [comment]
Thanks for your reply. The error is gone after I defined _USE_EIGEN and _USE_BOOST. Basically the OpenMVS_DEFINITIONS do not seem to propagate. I'll look into it tomorrow and let you know if I find a solution. 

As a temporary fix, I added the following lines from OpenMVS/CMakeLists.txt to my CMakeLists.txt

FIND_PACKAGE(Eigen ${SYSTEM_PACKAGE_REQUIRED})
if(EIGEN_FOUND)
	INCLUDE_DIRECTORIES(${EIGEN_INCLUDE_DIRS})
	ADD_DEFINITIONS(${EIGEN_DEFINITIONS} -D_USE_EIGEN)
	SET(_USE_EIGEN TRUE)
#endif()

FIND_PACKAGE(Boost ${SYSTEM_PACKAGE_REQUIRED} COMPONENTS iostreams program_options system serialization)
if(Boost_FOUND)
	INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIRS})
	ADD_DEFINITIONS(${Boost_DEFINITIONS} -D_USE_BOOST)
	LINK_DIRECTORIES(${Boost_LIBRARY_DIRS})
	SET(_USE_BOOST TRUE)
endif()
