### ISSUE TITLE
Invalid Project from openMVG

### ISSUE THREAD

**Issue by Tkong1** [cdcseacave/openMVS#323]
### Specifications like the version of the project, operating system, and hardware
Project: openMVG (latest version), openMVS (latest version)
OS: Linux, Kubuntu 16.04
Hardware: Fujitsu ESPRIMO Q956 

### Steps to reproduce the problem
1. Cloned openMVG and openMVS via git and Build the Projects
2. Downloaded ImageDataset_SceauxCastle
3. Run openMVG
  * openMVG_main_SfMInit_ImageListing
  * openMVG_main_ComputeFeatures
  * openMVG_main_ComputeMatches
  * openMVG_main_IncrementalSfM
  * openMVG_main_ComputeSfM_DataColor
  * openMVG_main_ComputeStructureFromKnownPoses
  * openMVG_main_openMVG2openMVS
4. Run openMVS with the `scene.mvs` from openMVG
  * DensifyPointCloud
  * [scene.txt](https://github.com/cdcseacave/openMVS/files/1996012/scene.txt)

## Errors
16:42:14 [App     ] Build date: May  4 2018, 14:05:19
16:42:14 [App     ] CPU: Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz
16:42:14 [App     ] RAM: 31.25GB Physical Memory 31.83GB Virtual Memory
16:42:14 [App     ] OS: Linux 4.4.0-124-generic (x86_64)
16:42:14 [App     ] SSE & AVX compatible CPU & OS detected
16:42:14 [App     ] Command line: /media/trti1300/DATEN/development/trti1300/ImageDataset_SceauxCastle/out/scene.mvs
16:42:14 [App     ] Camera model loaded: platform 0; camera  0; f 1.056x1.056; poses 11
16:42:14 [App     ] error: failed loading image header
16:42:14 [App     ] error: failed reloading image '/media/trti1300/DATEN/development/trti1300/openMVS/openMVS_build/bin/undistorted_images/100_7100.JPG'
16:42:14 [App     ] error: invalid project  

Hi there,
could you please help me with this error?

**Comment by pmoulon** [comment]
Did you check if the image `/media/trti1300/DATEN/development/trti1300/openMVS/openMVS_build/bin/undistorted_images/100_7100.JPG` is on disk and valid?

**Comment by przeslawski** [comment]
I am having the same problem with OSX build. The mentioned files are valid. Any idea what can be wrong?

**Comment by Tkong1** [comment]
@pmoulon Thanks! 
I moved the image folder to the directory of `scene.mvs` and renamed it to `undistorted_images`.
And now it works.

**Comment by przeslawski** [comment]
@Tkong1 did you rename the directory with `scene.mvs` to `undistorted_images` ?

**Comment by CaslerTheTesticle** [comment]
@przeslawski this might be a little late but it is 5 years later and I have the same issue, did you get it fixed?
