### ISSUE TITLE
[Usage][Question] : log interpretation

### ISSUE THREAD

**Issue by pyp22** [cdcseacave/openMVS#33]
hi @cdcseacave,

I'm wondering if this 

![mvs_tottime](https://cloud.githubusercontent.com/assets/8407357/11015108/81a60452-8551-11e5-8816-9690797634b5.jpg)

is a correct interpretation of the logs.

Thanks, regards

PY

**Comment by cdcseacave** [comment]
At a first look, it seems that the dense reconstruction took too little, but I can not say much without the logs. If the results look fine than all is fine :)

**Comment by pyp22** [comment]
ok thanks. Wanted to be sure as i'm writing a short py script.
