### ISSUE TITLE
Debug openMVS through gdb 

### ISSUE THREAD

**Issue by jianweike** [cdcseacave/openMVS#336]
### Specifications like the version of the project, operating system, and hardware
Ubuntu 16.04
### Steps to reproduce the problem
I am not sure if here is the right place to ask this question. After "make install", openMVS was installed inito /usr/local/ of my machine. I think openMVS is installed correctly. I can run the executables (DensifyPointCoud, ReconstructeMesh,..) as well as including openMVS as a third party library for my own project.

The problem that I am facing is that gdb can't step in the functions in openMVS. For example, gdb will step over scene.DenseReconstruction() instead of step in it. And I couldn't set a breakpoint in SceneDensify.cpp as gdb couldn't find the source file.   

I did build openMVS and my program in debug mode. 

Thank you in advanced.

The detailed log is as followed:
-- cotire 1.7.8 loaded.
-- Detected version of GNU GCC: 54 (504)
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Can't find CUDA. Continuing without it.
-- WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   iostreams
--   program_options
--   system
--   serialization
--   regex
-- Eigen 3.3.4 found (include: /usr/local/include/eigen3)
-- OpenCV 3.4.1 found (include: /usr/local/include;/usr/local/include/opencv)
-- CGAL 4.7 found (include: /usr/include)
-- VCG  found (include: /home/jianwei/Documents/OpenMVS/vcglib)
-- Found installed version of Eigen: /usr/local/share/eigen3/cmake
-- Found required Ceres dependency: Eigen version 3.3.4 in /usr/local/include/eigen3
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.14.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
-- CERES 1.14.0 found (include: /usr/local/include;/usr/local/include/eigen3;/usr/include;/usr/include;/usr/local/include)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jianwei/Documents/OpenMVS/openMVS_build_debug
[ 18%] Built target Common
[ 27%] Built target Math
[ 50%] Built target IO
[ 74%] Built target MVS
[ 76%] Built target InterfaceVisualSFM
[ 79%] Built target DensifyPointCloud
[ 81%] Built target ReconstructMesh
[ 84%] Built target RefineMesh
[ 87%] Built target TextureMesh
[100%] Built target Viewer
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/include/OpenMVS/ConfigLocal.h
-- Installing: /usr/local/lib/CMake/OpenMVS/OpenMVSConfig.cmake
-- Installing: /usr/local/lib/CMake/OpenMVS/OpenMVSConfigVersion.cmake
-- Old export file "/usr/local/lib/CMake/OpenMVS/OpenMVSTargets.cmake" will be replaced.  Removing files [/usr/local/lib/CMake/OpenMVS/OpenMVSTargets-release.cmake].
-- Installing: /usr/local/lib/CMake/OpenMVS/OpenMVSTargets.cmake
-- Installing: /usr/local/lib/CMake/OpenMVS/OpenMVSTargets-debug.cmake
-- Up-to-date: /usr/local/include/OpenMVS/MVS.h
-- Installing: /usr/local/lib/OpenMVS/libCommon.a
-- Up-to-date: /usr/local/include/OpenMVS/Common/EventQueue.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/SharedPtr.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Ray.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Timer.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/AABB.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/File.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/OBB.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Octree.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/AutoEstimator.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Util.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Plane.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Log.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/HalfFloat.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/CriticalSection.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/ConfigTable.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Queue.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Types.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/AutoPtr.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Common.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Filters.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Semaphore.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Strings.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/List.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Thread.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Hash.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/LinkLib.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/FastDelegateCPP11.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/MemFile.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Wildcard.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Sphere.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Rotation.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/HTMLDoc.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/FastDelegateBind.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Streams.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/CUDA.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/SML.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/FastDelegate.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Config.h
-- Up-to-date: /usr/local/include/OpenMVS/Common/Ray.inl
-- Up-to-date: /usr/local/include/OpenMVS/Common/Rotation.inl
-- Up-to-date: /usr/local/include/OpenMVS/Common/Util.inl
-- Up-to-date: /usr/local/include/OpenMVS/Common/Sampler.inl
-- Up-to-date: /usr/local/include/OpenMVS/Common/Plane.inl
-- Up-to-date: /usr/local/include/OpenMVS/Common/OBB.inl
-- Up-to-date: /usr/local/include/OpenMVS/Common/Types.inl
-- Up-to-date: /usr/local/include/OpenMVS/Common/Sphere.inl
-- Up-to-date: /usr/local/include/OpenMVS/Common/Octree.inl
-- Up-to-date: /usr/local/include/OpenMVS/Common/AABB.inl
-- Up-to-date: /usr/local/include/OpenMVS/Math/Common.h
-- Up-to-date: /usr/local/include/OpenMVS/Math/LBP.h
-- Up-to-date: /usr/local/include/OpenMVS/Math/IBFS/IBFS.h
-- Up-to-date: /usr/local/include/OpenMVS/Math/LMFit/lmmin.h
-- Up-to-date: /usr/local/include/OpenMVS/Math/TRWS/typeTruncatedLinear2D.h
-- Up-to-date: /usr/local/include/OpenMVS/Math/TRWS/typeTruncatedLinear.h
-- Up-to-date: /usr/local/include/OpenMVS/Math/TRWS/MRFEnergy.h
-- Up-to-date: /usr/local/include/OpenMVS/Math/TRWS/typeTruncatedQuadratic.h
-- Up-to-date: /usr/local/include/OpenMVS/Math/TRWS/typeGeneral.h
-- Up-to-date: /usr/local/include/OpenMVS/Math/TRWS/typePotts.h
-- Up-to-date: /usr/local/include/OpenMVS/Math/TRWS/typeBinaryFast.h
-- Up-to-date: /usr/local/include/OpenMVS/Math/TRWS/typeBinary.h
-- Up-to-date: /usr/local/include/OpenMVS/Math/TRWS/typeTruncatedQuadratic2D.h
-- Up-to-date: /usr/local/include/OpenMVS/Math/TRWS/instances.h
-- Up-to-date: /usr/local/include/OpenMVS/Math/TRWS/minimize.inl
-- Up-to-date: /usr/local/include/OpenMVS/Math/TRWS/treeProbabilities.inl
-- Up-to-date: /usr/local/include/OpenMVS/Math/TRWS/MRFEnergy.inl
-- Up-to-date: /usr/local/include/OpenMVS/Math/TRWS/ordering.inl
-- Installing: /usr/local/lib/OpenMVS/libMath.a
-- Installing: /usr/local/lib/OpenMVS/libIO.a
-- Up-to-date: /usr/local/include/OpenMVS/IO/ImageSCI.h
-- Up-to-date: /usr/local/include/OpenMVS/IO/ImageBMP.h
-- Up-to-date: /usr/local/include/OpenMVS/IO/ImageTGA.h
-- Up-to-date: /usr/local/include/OpenMVS/IO/ImageEXIF.h
-- Up-to-date: /usr/local/include/OpenMVS/IO/ImageDDS.h
-- Up-to-date: /usr/local/include/OpenMVS/IO/Common.h
-- Up-to-date: /usr/local/include/OpenMVS/IO/EXIF.h
-- Up-to-date: /usr/local/include/OpenMVS/IO/Image.h
-- Up-to-date: /usr/local/include/OpenMVS/IO/ImageTIFF.h
-- Up-to-date: /usr/local/include/OpenMVS/IO/ImageJPG.h
-- Up-to-date: /usr/local/include/OpenMVS/IO/TinyXML2.h
-- Up-to-date: /usr/local/include/OpenMVS/IO/OBJ.h
-- Up-to-date: /usr/local/include/OpenMVS/IO/PLY.h
-- Up-to-date: /usr/local/include/OpenMVS/IO/ImagePNG.h
-- Installing: /usr/local/lib/OpenMVS/libMVS.a
-- Up-to-date: /usr/local/include/OpenMVS/MVS/PointCloud.h
-- Up-to-date: /usr/local/include/OpenMVS/MVS/Scene.h
-- Up-to-date: /usr/local/include/OpenMVS/MVS/Mesh.h
-- Up-to-date: /usr/local/include/OpenMVS/MVS/RectsBinPack.h
-- Up-to-date: /usr/local/include/OpenMVS/MVS/DepthMap.h
-- Up-to-date: /usr/local/include/OpenMVS/MVS/Common.h
-- Up-to-date: /usr/local/include/OpenMVS/MVS/Camera.h
-- Up-to-date: /usr/local/include/OpenMVS/MVS/Platform.h
-- Up-to-date: /usr/local/include/OpenMVS/MVS/Image.h
-- Up-to-date: /usr/local/include/OpenMVS/MVS/Interface.h
-- Installing: /usr/local/bin/OpenMVS/InterfaceVisualSFM
-- Set runtime path of "/usr/local/bin/OpenMVS/InterfaceVisualSFM" to ""
-- Installing: /usr/local/bin/OpenMVS/DensifyPointCloud
-- Set runtime path of "/usr/local/bin/OpenMVS/DensifyPointCloud" to ""
-- Installing: /usr/local/bin/OpenMVS/ReconstructMesh
-- Set runtime path of "/usr/local/bin/OpenMVS/ReconstructMesh" to ""
-- Installing: /usr/local/bin/OpenMVS/RefineMesh
-- Set runtime path of "/usr/local/bin/OpenMVS/RefineMesh" to ""
-- Installing: /usr/local/bin/OpenMVS/TextureMesh
-- Set runtime path of "/usr/local/bin/OpenMVS/TextureMesh" to ""
-- Installing: /usr/local/bin/OpenMVS/Viewer
-- Set runtime path of "/usr/local/bin/OpenMVS/Viewer" to ""

**Comment by jianweike** [comment]
The output after I run "make VERBOSE = 1" is 
/usr/bin/cmake -H/home/jianwei/Documents/Eclipse-Theia-test-debug -B/home/jianwei/Documents/Eclipse-Theia-test-debug --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/jianwei/Documents/Eclipse-Theia-test-debug/CMakeFiles /home/jianwei/Documents/Eclipse-Theia-test-debug/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/jianwei/Documents/Eclipse-Theia-test-debug'
make -f CMakeFiles/openMVS-Debug.dir/build.make CMakeFiles/openMVS-Debug.dir/depend
make[2]: Entering directory '/home/jianwei/Documents/Eclipse-Theia-test-debug'
cd /home/jianwei/Documents/Eclipse-Theia-test-debug && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/jianwei/Documents/Eclipse-Theia-test-debug /home/jianwei/Documents/Eclipse-Theia-test-debug /home/jianwei/Documents/Eclipse-Theia-test-debug /home/jianwei/Documents/Eclipse-Theia-test-debug /home/jianwei/Documents/Eclipse-Theia-test-debug/CMakeFiles/openMVS-Debug.dir/DependInfo.cmake --color=
Dependee "/home/jianwei/Documents/Eclipse-Theia-test-debug/main.cpp" is newer than depender "CMakeFiles/openMVS-Debug.dir/main.cpp.o".
Clearing dependencies in "/home/jianwei/Documents/Eclipse-Theia-test-debug/CMakeFiles/openMVS-Debug.dir/depend.make".
Scanning dependencies of target openMVS-Debug
make[2]: Leaving directory '/home/jianwei/Documents/Eclipse-Theia-test-debug'
make -f CMakeFiles/openMVS-Debug.dir/build.make CMakeFiles/openMVS-Debug.dir/build
make[2]: Entering directory '/home/jianwei/Documents/Eclipse-Theia-test-debug'
[ 50%] Building CXX object CMakeFiles/openMVS-Debug.dir/main.cpp.o
/usr/bin/c++   -DTHEIA_GFLAGS_NAMESPACE=google -DTHEIA_SUITESPARSE_VERSION=\"4.4.6\" -D_USE_BOOST -D_USE_EIGEN -isystem /usr/local/include -I/usr/local/include/eigen3 -I/usr/include/suitesparse -I/usr/local/include/theia/libraries -I/usr/local/include/theia/libraries/akaze -I/usr/local/include/theia/libraries/cereal -I/usr/local/include/theia/libraries/cereal/include -I/usr/local/include/theia/libraries/flann -I/usr/local/include/theia/libraries/gtest -I/usr/local/include/theia/libraries/gtest/include -I/usr/local/include/theia/libraries/optimo -I/usr/local/include/theia/libraries/spectra -I/usr/local/include/theia/libraries/statx -I/usr/local/include/theia/libraries/stlplus3 -I/usr/local/include/theia/libraries/vlfeat -I/usr/local/include/theia/libraries/visual_sfm -isystem /usr/local/include/opencv -I/home/jianwei/Documents/OpenMVS/openMVS -I/home/jianwei/Documents/OpenMVS/openMVS_build  -g   -std=gnu++11 -o CMakeFiles/openMVS-Debug.dir/main.cpp.o -c /home/jianwei/Documents/Eclipse-Theia-test-debug/main.cpp

/usr/bin/cmake -E cmake_link_script CMakeFiles/openMVS-Debug.dir/link.txt --verbose=1
/usr/bin/c++   -g   CMakeFiles/openMVS-Debug.dir/main.cpp.o  -o openMVS-Debug /usr/local/lib/libtheia.a /usr/lib/x86_64-linux-gnu/libGLU.so /usr/lib/x86_64-linux-gnu/libGL.so /usr/lib/x86_64-linux-gnu/libglut.so /usr/lib/x86_64-linux-gnu/libXmu.so /usr/lib/x86_64-linux-gnu/libXi.so /usr/local/lib/libopencv_optflow.so.3.4.1 /usr/local/lib/libopencv_rgbd.so.3.4.1 /usr/local/lib/libopencv_xobjdetect.so.3.4.1 /usr/local/lib/libopencv_freetype.so.3.4.1 /usr/local/lib/libopencv_face.so.3.4.1 /usr/local/lib/libopencv_bgsegm.so.3.4.1 /usr/local/lib/libopencv_hfs.so.3.4.1 /usr/local/lib/libopencv_reg.so.3.4.1 /usr/local/lib/libopencv_aruco.so.3.4.1 /usr/local/lib/libopencv_saliency.so.3.4.1 /usr/local/lib/libopencv_dnn_objdetect.so.3.4.1 /usr/local/lib/libopencv_line_descriptor.so.3.4.1 /usr/local/lib/libopencv_hdf.so.3.4.1 /usr/local/lib/libopencv_tracking.so.3.4.1 /usr/local/lib/libopencv_dpm.so.3.4.1 /usr/local/lib/libopencv_plot.so.3.4.1 /usr/local/lib/libopencv_xphoto.so.3.4.1 /usr/local/lib/libopencv_ccalib.so.3.4.1 /usr/local/lib/libopencv_stereo.so.3.4.1 /usr/local/lib/libopencv_cvv.so.3.4.1 /usr/local/lib/libopencv_bioinspired.so.3.4.1 /usr/local/lib/libopencv_structured_light.so.3.4.1 /usr/local/lib/libopencv_phase_unwrapping.so.3.4.1 /usr/local/lib/libopencv_fuzzy.so.3.4.1 /usr/local/lib/libopencv_img_hash.so.3.4.1 /usr/local/lib/libopencv_ximgproc.so.3.4.1 /usr/local/lib/libopencv_sfm.so.3.4.1 /usr/local/lib/libopencv_surface_matching.so.3.4.1 /home/jianwei/Documents/OpenMVS/openMVS_build/lib/libMVS.so /usr/local/lib/libOpenImageIO.so /usr/local/lib/libakaze.a /usr/local/lib/libflann_cpp.so.1.8.4 -Wl,-whole-archive /usr/local/lib/libflann_cpp_s.a -Wl,-no-whole-archive /usr/local/lib/libstatx.a /usr/local/lib/libstlplus3.a /usr/local/lib/libvlfeat.so /usr/local/lib/libvisual_sfm.a /usr/local/lib/libopencv_datasets.so.3.4.1 /usr/local/lib/libopencv_text.so.3.4.1 /usr/local/lib/libceres.a /usr/lib/x86_64-linux-gnu/libgflags.so /usr/lib/x86_64-linux-gnu/libglog.so /usr/lib/x86_64-linux-gnu/libcxsparse.so -lgomp -lpthread /usr/lib/x86_64-linux-gnu/libspqr.so /usr/lib/x86_64-linux-gnu/libtbb.so /usr/lib/x86_64-linux-gnu/libtbbmalloc.so /usr/lib/x86_64-linux-gnu/libcholmod.so /usr/lib/x86_64-linux-gnu/libccolamd.so /usr/lib/x86_64-linux-gnu/libcamd.so /usr/lib/x86_64-linux-gnu/libcolamd.so /usr/lib/x86_64-linux-gnu/libamd.so /usr/lib/liblapack.so /usr/lib/libf77blas.so /usr/lib/libatlas.so /usr/lib/libf77blas.so /usr/lib/libatlas.so /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so /usr/lib/x86_64-linux-gnu/librt.so /home/jianwei/Documents/OpenMVS/openMVS_build/lib/libMath.a /home/jianwei/Documents/OpenMVS/openMVS_build/lib/libIO.a /home/jianwei/Documents/OpenMVS/openMVS_build/lib/libCommon.a /usr/local/lib/libopencv_objdetect.so.3.4.1 /usr/local/lib/libopencv_stitching.so.3.4.1 /usr/local/lib/libopencv_xfeatures2d.so.3.4.1 /usr/local/lib/libopencv_videostab.so.3.4.1 /usr/local/lib/libopencv_calib3d.so.3.4.1 /usr/local/lib/libopencv_shape.so.3.4.1 /usr/local/lib/libopencv_ml.so.3.4.1 /usr/local/lib/libopencv_features2d.so.3.4.1 /usr/local/lib/libopencv_highgui.so.3.4.1 /usr/local/lib/libopencv_flann.so.3.4.1 /usr/local/lib/libopencv_photo.so.3.4.1 /usr/local/lib/libopencv_dnn.so.3.4.1 /usr/local/lib/libopencv_viz.so.3.4.1 /usr/local/lib/libopencv_superres.so.3.4.1 /usr/local/lib/libopencv_video.so.3.4.1 /usr/local/lib/libopencv_videoio.so.3.4.1 /usr/local/lib/libopencv_imgcodecs.so.3.4.1 /usr/local/lib/libopencv_imgproc.so.3.4.1 /usr/local/lib/libopencv_core.so.3.4.1 /usr/lib/x86_64-linux-gnu/libboost_iostreams.so /usr/lib/x86_64-linux-gnu/libboost_program_options.so /usr/lib/x86_64-linux-gnu/libboost_serialization.so /usr/lib/x86_64-linux-gnu/libboost_regex.so /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib/x86_64-linux-gnu/libtiff.so /usr/lib/x86_64-linux-gnu/libCGAL.so.11.0.1 /usr/lib/x86_64-linux-gnu/libCGAL_Core.so.11.0.1 /usr/lib/x86_64-linux-gnu/libCGAL_ImageIO.so.11.0.1 /usr/lib/x86_64-linux-gnu/libboost_thread.so /usr/lib/x86_64-linux-gnu/libboost_system.so -lpthread /usr/lib/x86_64-linux-gnu/libGLU.so /usr/lib/x86_64-linux-gnu/libGL.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libmpfr.so /usr/lib/x86_64-linux-gnu/libgmp.so -Wl,-rpath,/usr/local/lib:/home/jianwei/Documents/OpenMVS/openMVS_build/lib 
make[2]: Leaving directory '/home/jianwei/Documents/Eclipse-Theia-test-debug'
[100%] Built target openMVS-Debug
make[1]: Leaving directory '/home/jianwei/Documents/Eclipse-Theia-test-debug'
/usr/bin/cmake -E cmake_progress_start /home/jianwei/Documents/Eclipse-Theia-test-debug/CMakeFiles 0

**Comment by snowzurfer** [comment]
Can you paste the `cmake` command you run to generate the project?
