### ISSUE TITLE
I want to run <DensifyPointCloud scene.mvs>. Does this demo have output?

### ISSUE THREAD

**Issue by TianQi-777** [cdcseacave/openMVS#338]
Hello, I just started learning 3D reconstruction.

I am running openMVS as a third-party library in the ubuntu16.04 system, but now there are some problems with the operation, I should be able to solve this problem myself, but **I want to know whether <DensifyPointCloud scene.mvs> will output scene_dense.mvs and scene_dense.ply**, I know that these are all directly given documents in OpenMVS_sample, but I want to deal with my own data.

I can process my own picture data as **scene_myself.mvs**, How should I get **scene_dense_myself.mvs**, I want to run <DensifyPointCloud scene_myself.mvs> to get scene_dense_myself.mvs, but what puzzles me is that <DensifyPointCloud scene_myself.mvs> doesn't specify an output file.

Another question is if I want to run <python MvgMvs_Pipeline.py <images_folder> <output_folder>>, what should be the file format stored on <images_folder>(Images and camera_file_params?)?

I hope the author gives me some guidance, thank you.

**Comment by jianweike** [comment]
Suppose you used OpenMVG to perform SfM upon your images and got scene.mvs, you can use the executable "DensifyPointCloud" under the folder "bin" to get scene_dense.mvs and scene_dense.ply. Simple run "./DensifyPointCloud scene.mvs", the executable will generate scene_dense.mvs for you

If you are talking about performing dense reconstruction in your program, this line "scene.DenseReconstruction()" will do the job, then you can use these two functions "scene.Save(baseFileName+_T(".mvs"), (ARCHIVE_TYPE)OPT::nArchiveType);
 scene.pointcloud.Save(baseFileName+_T(".ply"));"  to save your dense reconstruction. These are all included in DensifyPointCloud.cpp
