### ISSUE TITLE
Importing from openMVG

### ISSUE THREAD

**Issue by neoaurion** [cdcseacave/openMVS#34]
Hi,

I couldn't import from openMVG and had to modify InterfaceOpenMVG at line 592 from:

const String srcImage(MAKE_PATH_FULL(WORKING_FOLDER_FULL, pathRoot+view.second->s_Img_path));

to

const String srcImage(MAKE_PATH_FULL(pathRoot,view.second->s_Img_path));

Am I in a particular case ? Or maybe I used it the wrong way.

Thank you for this awesome piece of software.

**Comment by cdcseacave** [comment]
Looks like you are not using the latest code (branch develop). Please try it and see if the problem persists.

**Comment by neoaurion** [comment]
You're right I'm on the master branch, but develop branch does not compile on my machine. I have a build error on bool DELAUNAY::intersect() function . Maybe my libraries are too old (I use the ones of ubuntu 14.04) I will take a deeper look on why it does not compile.

**Comment by cdcseacave** [comment]
that is strange, cause not much changed in ReconstructMesh(). Please tell me where in OpenMVS is used the CGAL function that gives you errors?

**Comment by ORNis** [comment]
Yep the cgal version in 14.04 is pretty old one (4.2.1). I'm not sure it's the root of your issue but you'd better building  your own CGAL lib from source.

**Comment by neoaurion** [comment]
Sorry in intersect function it was just a warning, the error is :

/home/data/ThirdPartyLibs/openMVS/libs/MVS/SceneReconstruct.cpp: At global scope:
/home/data/ThirdPartyLibs/openMVS/libs/MVS/SceneReconstruct.cpp:710:20: error: member ‘DELAUNAY::vertex_handle_t DELAUNAY::triangle_vhandles_t::<anonymous union>::<anonymous struct>::v0’ with constructor not allowed in anonymous aggregate
    vertex_handle_t v0, v1, v2;

**Comment by cdcseacave** [comment]
I'll fix it and push it in 3 minutes, please try again

**Comment by neoaurion** [comment]
Thank you, your fix works. I now try to import OpenMVG to MVS

**Comment by neoaurion** [comment]
And importing is working on this branch. Thanks a lot for your reactivity.
