### ISSUE TITLE
Crash when removing vertices

### ISSUE THREAD

**Issue by KristianZarn** [cdcseacave/openMVS#340]
### Specifications
project version: 0.7.0 (pulled from master branch a month ago)
operating system: ubuntu 17.10
gpu: gtx 1050

### Problem
I want to remove vertices (and corresponding faces) from `MVS::Mesh`. I tried using the function `Mesh::RemoveVertices` but the program crashes (segmentation fault). Interestingly the function `Mesh::RemoveFaces` works as expected. The mesh was generated from point cloud, by function `Scene::ReconstructMesh`. Here is the input MVS (and ply) file I used for testing: 
[input_files.zip](https://github.com/cdcseacave/openMVS/files/2102293/input_files.zip)

### Steps to reproduce the problem
Here are some code samples to show what I mean. 
#### Removing faces (works)
```
#include <iostream>
#include <OpenMVS/MVS.h>

int main(int argc, char *argv[]) {
    // Set paths
    std::string base_folder = "path_to_input_files";
    std::string mvs_file = base_folder + "in.mvs";

    // Read mvs
    MVS::Scene mvs_scene;
    mvs_scene.Load(mvs_file);

    // Remove faces
    std::vector<int> selected_faces_idx = {2079, 1968, 2080, 2033};
    MVS::Mesh::FaceIdxArr faces;
    for (const auto& i : selected_faces_idx) {
        MVS::Mesh::FIndex& tmp = faces.AddEmpty();
        tmp = (MVS::Mesh::FIndex) i;
    }
    mvs_scene.mesh.RemoveFaces(faces, false);

    // Save mvs
    mvs_scene.Save(base_folder + "out.mvs");
    mvs_scene.mesh.Save(base_folder + "out.ply");

    return EXIT_SUCCESS;
}
```

#### Removing vertices (does not work)
```
#include <iostream>
#include <OpenMVS/MVS.h>

int main(int argc, char *argv[]) {
    // Set paths
    std::string base_folder = "path_to_input_files";
    std::string mvs_file = base_folder + "in.mvs";

    // Read mvs
    MVS::Scene mvs_scene;
    mvs_scene.Load(mvs_file);

    // Remove vertices (vertices of face 2033)
    std::vector<int> selected_vertices_idx = {123, 1296, 1319};
    MVS::Mesh::VertexIdxArr vertices;
    for (const auto& i : selected_vertices_idx) {
        MVS::Mesh::VIndex& tmp = vertices.AddEmpty();
        tmp = (MVS::Mesh::VIndex) i;
    }
    mvs_scene.mesh.RemoveVertices(vertices, false);

    // Save mvs
    mvs_scene.Save(base_folder + "out.mvs");
    mvs_scene.mesh.Save(base_folder + "out.ply");

    return EXIT_SUCCESS;
}
```

Am I doing something wrong or is this a bug in the MVS code?

**Comment by KristianZarn** [comment]
Ok, so now I found one solution to my problem. I call the function `ListIncidenteFaces` before calling `RemoveVertices` and it seems to work. If this is the intended usage then I will close the issue, but I do suggest calling the function inside `RemoveVertices`.

**Comment by cdcseacave** [comment]
that is the intended usage, the problem here is that for some reason an old vertex state is saved to the disk; this is the problem that needs to be fixed

**Comment by KristianZarn** [comment]
Ok, thank you.
