### ISSUE TITLE
Error loading libMVS.so

### ISSUE THREAD

**Issue by fasterthan** [cdcseacave/openMVS#341]
I'm trying to run the DensifyPointCloud executable in the **apps**  folder of openMVS but I receive an error message saying it can't open libMVS.so. Within the **lib** folder in openMVS root however is the libMVS.so file, so I am not sure why I am getting this error message.

The administrator for my workstation installed all of the require dependencies for openMVS and I installed openMVS itself using the build instructions [https://github.com/cdcseacave/openMVS/wiki/Building](here). I do not have sudo.

### Specifications like the version of the project, operating system, and hardware

openMVS v 0.8 on Fedora 27

### Steps to reproduce the problem

Run the following command from **apps** folder in root openMVS folder:
```
[d***@hmd***]$ DensifyPointCloud
DensifyPointCloud: error while loading shared libraries: libMVS.so: cannot open shared object file: No such file or directory
```

Thanks in advance.

**Comment by cdcseacave** [comment]
Using OpenMVS as a 3rd party lib was never tested. If there are indeed issues with the OpenMVS compilation/installation scripts, pls share a fix with us using a pull request. Thx

**Comment by fasterthan** [comment]
I resolved the issue by adding the directory containing libMVS.so to my `LD_LIBRARY_PATH`.

I ran `locate libMVS.so` in terminal to find the location of libMVS.so, and then added that path to my `.bashrc` file:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path to libMVS.so>
```
