### ISSUE TITLE
Reconstructing 3D textured mesh from SenseFly Quarry dataset stuck on ReconstructMesh

### ISSUE THREAD

**Issue by jpwhitney** [cdcseacave/openMVS#344]
### Specifications like the version of the project, operating system, and hardware
Ubuntu 16.04
7:14:13 [App     ] CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
07:14:13 [App     ] RAM: 15.54GB Physical Memory 48.10GB Virtual Memory
07:14:13 [App     ] OS: Linux 4.10.0-28-generic (x86_64)
07:14:13 [App     ] SSE & AVX compatible CPU & OS detected
07:14:13 [App     ] Command line: scene_dense.mvs
07:14:13 [App     ] CUDA device 0 initialized: GeForce GTX 960M (compute capability 5.0; memory 3.95GB)
### Steps to reproduce the problem
I ran openMVG using the dataset specified [here](http://openmvg.readthedocs.io/en/latest/software/Geodesy/geodesy/#use-case-command-line-used-for-a-flat-uav-survey) exactly using these commands. Everything worked fine and a sfm_data.bin file was formed.
Then I ran this line:
openMVG_main_openMVG2openMVS -i sfm_data.bin -o scene.mvs && DensifyPointCloud scene.mvs && ReconstructMesh scene_dense.mvs && RefineMesh scene_mesh.mvs && TextureMesh scene_dense_mesh.mvs
And I recieved this output:

> openMVG_main_openMVG2openMVS -i sfm_data.bin -o scene.mvs && DensifyPointCloud scene.mvs && ReconstructMesh scene_dense.mvs && RefineMesh scene_mesh.mvs && TextureMesh scene_dense_mesh.mvs
> 
> - PROCESS VIEWS -
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> ***************************************************
> 
> - UNDISTORT IMAGES -
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> ***************************************************
> Scene saved to OpenMVS interface format:
>  #platforms: 1
>   platform ( 0 ) #cameras: 1
>   211 images (180 calibrated)
>   218959 Landmarks
> 01:07:24 [App     ] Build date: Jun 18 2018, 17:30:17
> 01:07:25 [App     ] CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
> 01:07:25 [App     ] RAM: 15.54GB Physical Memory 18.10GB Virtual Memory
> 01:07:26 [App     ] OS: Linux 4.10.0-28-generic (x86_64)
> 01:07:26 [App     ] SSE & AVX compatible CPU & OS detected
> 01:07:26 [App     ] Command line: scene.mvs
> 01:07:27 [App     ] CUDA device 0 initialized: GeForce GTX 960M (compute capability 5.0; memory 3.95GB)
> 01:07:29 [App     ] Camera model loaded: platform 0; camera  0; f 0.715x0.715; poses 180
> 01:07:29 [App     ] Image loaded   0: IMG_1383.JPG
> 01:07:30 [App     ] Image loaded   1: IMG_1384.JPG
> 01:07:30 [App     ] Image loaded   2: IMG_1385.JPG
> 01:07:30 [App     ] Image loaded   3: IMG_1386.JPG
> 01:07:30 [App     ] Image loaded   4: IMG_1387.JPG
> 01:07:30 [App     ] Image loaded   5: IMG_1388.JPG
> 01:07:30 [App     ] Image loaded   6: IMG_1389.JPG
> 01:07:30 [App     ] Image loaded   7: IMG_1390.JPG
> 01:07:31 [App     ] Image loaded   8: IMG_1391.JPG
> 01:07:31 [App     ] Image loaded   9: IMG_1392.JPG
> 01:07:31 [App     ] Image loaded  10: IMG_1393.JPG
> 01:07:31 [App     ] Image loaded  11: IMG_1394.JPG
> 01:07:31 [App     ] Image loaded  12: IMG_1395.JPG
> 01:07:31 [App     ] Image loaded  13: IMG_1396.JPG
> 01:07:31 [App     ] Image loaded  14: IMG_1397.JPG
> 01:07:31 [App     ] Image loaded  15: IMG_1398.JPG
> 01:07:31 [App     ] Image loaded  16: IMG_1399.JPG
> 01:07:31 [App     ] Image loaded  17: IMG_1400.JPG
> 01:07:31 [App     ] Image loaded  18: IMG_1401.JPG
> 01:07:31 [App     ] Image loaded  19: IMG_1402.JPG
> 01:07:31 [App     ] Image loaded  20: IMG_1403.JPG
> 01:07:31 [App     ] Image loaded  21: IMG_1404.JPG
> 01:07:32 [App     ] Image loaded  22: IMG_1405.JPG
> 01:07:32 [App     ] Image loaded  23: IMG_1406.JPG
> 01:07:32 [App     ] Image loaded  24: IMG_1407.JPG
> 01:07:32 [App     ] Image loaded  25: IMG_1408.JPG
> 01:07:32 [App     ] Image loaded  26: IMG_1409.JPG
> 01:07:32 [App     ] Image loaded  27: IMG_1410.JPG
> 01:07:32 [App     ] Image loaded  28: IMG_1411.JPG
> 01:07:32 [App     ] Image loaded  29: IMG_1412.JPG
> 01:07:32 [App     ] Image loaded  30: IMG_1413.JPG
> 01:07:32 [App     ] Image loaded  31: IMG_1414.JPG
> 01:07:32 [App     ] Image loaded  32: IMG_1415.JPG
> 01:07:32 [App     ] Image loaded  33: IMG_1416.JPG
> 01:07:32 [App     ] Image loaded  34: IMG_1417.JPG
> 01:07:32 [App     ] Image loaded  35: IMG_1418.JPG
> 01:07:32 [App     ] Image loaded  36: IMG_1419.JPG
> 01:07:33 [App     ] Image loaded  37: IMG_1420.JPG
> 01:07:33 [App     ] Image loaded  38: IMG_1421.JPG
> 01:07:33 [App     ] Image loaded  39: IMG_1422.JPG
> 01:07:33 [App     ] Image loaded  40: IMG_1423.JPG
> 01:07:33 [App     ] Image loaded  41: IMG_1424.JPG
> 01:07:33 [App     ] Image loaded  42: IMG_1425.JPG
> 01:07:33 [App     ] Image loaded  43: IMG_1426.JPG
> 01:07:33 [App     ] Image loaded  44: IMG_1427.JPG
> 01:07:33 [App     ] Image loaded  45: IMG_1428.JPG
> 01:07:33 [App     ] Image loaded  46: IMG_1429.JPG
> 01:07:33 [App     ] Image loaded  47: IMG_1430.JPG
> 01:07:33 [App     ] Image loaded  48: IMG_1431.JPG
> 01:07:34 [App     ] Image loaded  49: IMG_1432.JPG
> 01:07:34 [App     ] Image loaded  50: IMG_1433.JPG
> 01:07:34 [App     ] Image loaded  51: IMG_1434.JPG
> 01:07:34 [App     ] Image loaded  52: IMG_1435.JPG
> 01:07:34 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1436.JPG'
> 01:07:34 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1437.JPG'
> 01:07:34 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1438.JPG'
> 01:07:34 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1439.JPG'
> 01:07:34 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1440.JPG'
> 01:07:34 [App     ] Image loaded  58: IMG_1441.JPG
> 01:07:35 [App     ] Image loaded  59: IMG_1442.JPG
> 01:07:35 [App     ] Image loaded  60: IMG_1443.JPG
> 01:07:35 [App     ] Image loaded  61: IMG_1444.JPG
> 01:07:35 [App     ] Image loaded  62: IMG_1445.JPG
> 01:07:35 [App     ] Image loaded  63: IMG_1446.JPG
> 01:07:36 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1447.JPG'
> 01:07:36 [App     ] Image loaded  65: IMG_1448.JPG
> 01:07:36 [App     ] Image loaded  66: IMG_1449.JPG
> 01:07:36 [App     ] Image loaded  67: IMG_1450.JPG
> 01:07:36 [App     ] Image loaded  68: IMG_1451.JPG
> 01:07:36 [App     ] Image loaded  69: IMG_1452.JPG
> 01:07:36 [App     ] Image loaded  70: IMG_1453.JPG
> 01:07:36 [App     ] Image loaded  71: IMG_1454.JPG
> 01:07:36 [App     ] Image loaded  72: IMG_1455.JPG
> 01:07:36 [App     ] Image loaded  73: IMG_1456.JPG
> 01:07:36 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1457.JPG'
> 01:07:36 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1458.JPG'
> 01:07:36 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1459.JPG'
> 01:07:36 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1460.JPG'
> 01:07:37 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1461.JPG'
> 01:07:37 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1462.JPG'
> 01:07:37 [App     ] Image loaded  80: IMG_1463.JPG
> 01:07:37 [App     ] Image loaded  81: IMG_1464.JPG
> 01:07:37 [App     ] Image loaded  82: IMG_1465.JPG
> 01:07:37 [App     ] Image loaded  83: IMG_1466.JPG
> 01:07:37 [App     ] Image loaded  84: IMG_1467.JPG
> 01:07:37 [App     ] Image loaded  85: IMG_1468.JPG
> 01:07:37 [App     ] Image loaded  86: IMG_1469.JPG
> 01:07:37 [App     ] Image loaded  87: IMG_1470.JPG
> 01:07:37 [App     ] Image loaded  88: IMG_1471.JPG
> 01:07:37 [App     ] Image loaded  89: IMG_1472.JPG
> 01:07:37 [App     ] Image loaded  90: IMG_1473.JPG
> 01:07:37 [App     ] Image loaded  91: IMG_1474.JPG
> 01:07:37 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1475.JPG'
> 01:07:38 [App     ] Image loaded  93: IMG_1476.JPG
> 01:07:38 [App     ] Image loaded  94: IMG_1477.JPG
> 01:07:38 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1478.JPG'
> 01:07:38 [App     ] Image loaded  96: IMG_1479.JPG
> 01:07:38 [App     ] Image loaded  97: IMG_1480.JPG
> 01:07:38 [App     ] Image loaded  98: IMG_1481.JPG
> 01:07:38 [App     ] Image loaded  99: IMG_1482.JPG
> 01:07:38 [App     ] Image loaded 100: IMG_1483.JPG
> 01:07:38 [App     ] Image loaded 101: IMG_1484.JPG
> 01:07:38 [App     ] Image loaded 102: IMG_1485.JPG
> 01:07:38 [App     ] Image loaded 103: IMG_1486.JPG
> 01:07:38 [App     ] Image loaded 104: IMG_1487.JPG
> 01:07:38 [App     ] Image loaded 105: IMG_1488.JPG
> 01:07:38 [App     ] Image loaded 106: IMG_1489.JPG
> 01:07:39 [App     ] Image loaded 107: IMG_1490.JPG
> 01:07:39 [App     ] Image loaded 108: IMG_1491.JPG
> 01:07:39 [App     ] Image loaded 109: IMG_1492.JPG
> 01:07:39 [App     ] Image loaded 110: IMG_1493.JPG
> 01:07:39 [App     ] Image loaded 111: IMG_1494.JPG
> 01:07:39 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1495.JPG'
> 01:07:39 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1496.JPG'
> 01:07:39 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1497.JPG'
> 01:07:39 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1498.JPG'
> 01:07:39 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1499.JPG'
> 01:07:39 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1500.JPG'
> 01:07:41 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1501.JPG'
> 01:07:41 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1502.JPG'
> 01:07:41 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1503.JPG'
> 01:07:42 [App     ] Image loaded 121: IMG_1504.JPG
> 01:07:42 [App     ] Image loaded 122: IMG_1505.JPG
> 01:07:42 [App     ] Image loaded 123: IMG_1506.JPG
> 01:07:42 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1507.JPG'
> 01:07:42 [App     ] Image loaded 125: IMG_1508.JPG
> 01:07:42 [App     ] Image loaded 126: IMG_1509.JPG
> 01:07:42 [App     ] Image loaded 127: IMG_1510.JPG
> 01:07:42 [App     ] Image loaded 128: IMG_1511.JPG
> 01:07:42 [App     ] Image loaded 129: IMG_1512.JPG
> 01:07:42 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1513.JPG'
> 01:07:42 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1514.JPG'
> 01:07:42 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1515.JPG'
> 01:07:42 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1516.JPG'
> 01:07:42 [App     ] Image loaded 134: IMG_1517.JPG
> 01:07:43 [App     ] Image loaded 135: IMG_1518.JPG
> 01:07:43 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1519.JPG'
> 01:07:43 [App     ] Image loaded 137: IMG_1520.JPG
> 01:07:43 [App     ] Image loaded 138: IMG_1521.JPG
> 01:07:43 [App     ] Image loaded 139: IMG_1522.JPG
> 01:07:43 [App     ] Image loaded 140: IMG_1523.JPG
> 01:07:43 [App     ] Image loaded 141: IMG_1524.JPG
> 01:07:43 [App     ] Image loaded 142: IMG_1525.JPG
> 01:07:43 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1526.JPG'
> 01:07:43 [App     ] Image loaded 144: IMG_1527.JPG
> 01:07:43 [App     ] Image loaded 145: IMG_1528.JPG
> 01:07:43 [App     ] Image loaded 146: IMG_1529.JPG
> 01:07:43 [App     ] Image loaded 147: IMG_1530.JPG
> 01:07:44 [App     ] Image loaded 148: IMG_1531.JPG
> 01:07:44 [App     ] Image loaded 149: IMG_1532.JPG
> 01:07:44 [App     ] Image loaded 150: IMG_1533.JPG
> 01:07:44 [App     ] Image loaded 151: IMG_1534.JPG
> 01:07:44 [App     ] Image loaded 152: IMG_1535.JPG
> 01:07:44 [App     ] Image loaded 153: IMG_1536.JPG
> 01:07:44 [App     ] Image loaded 154: IMG_1537.JPG
> 01:07:44 [App     ] Image loaded 155: IMG_1538.JPG
> 01:07:44 [App     ] Image loaded 156: IMG_1539.JPG
> 01:07:44 [App     ] Image loaded 157: IMG_1540.JPG
> 01:07:44 [App     ] Image loaded 158: IMG_1541.JPG
> 01:07:45 [App     ] warning: uncalibrated image 'undistorted_images/IMG_1542.JPG'
> 01:07:45 [App     ] Image loaded 160: IMG_1543.JPG
> 01:07:45 [App     ] Image loaded 161: IMG_1544.JPG
> 01:07:45 [App     ] Image loaded 162: IMG_1545.JPG
> 01:07:45 [App     ] Image loaded 163: IMG_1546.JPG
> 01:07:46 [App     ] Image loaded 164: IMG_1547.JPG
> 01:07:46 [App     ] Image loaded 165: IMG_1548.JPG
> 01:07:46 [App     ] Image loaded 166: IMG_1549.JPG
> 01:07:46 [App     ] Image loaded 167: IMG_1550.JPG
> 01:07:46 [App     ] Image loaded 168: IMG_1551.JPG
> 01:07:46 [App     ] Image loaded 169: IMG_1552.JPG
> 01:07:46 [App     ] Image loaded 170: IMG_1553.JPG
> 01:07:46 [App     ] Image loaded 171: IMG_1554.JPG
> 01:07:46 [App     ] Image loaded 172: IMG_1555.JPG
> 01:07:46 [App     ] Image loaded 173: IMG_1556.JPG
> 01:07:46 [App     ] Image loaded 174: IMG_1557.JPG
> 01:07:46 [App     ] Image loaded 175: IMG_1558.JPG
> 01:07:46 [App     ] Image loaded 176: IMG_1559.JPG
> 01:07:46 [App     ] Image loaded 177: IMG_1560.JPG
> 01:07:47 [App     ] Image loaded 178: IMG_1561.JPG
> 01:07:47 [App     ] Image loaded 179: IMG_1562.JPG
> 01:07:47 [App     ] Image loaded 180: IMG_1563.JPG
> 01:07:47 [App     ] Image loaded 181: IMG_1564.JPG
> 01:07:47 [App     ] Image loaded 182: IMG_1565.JPG
> 01:07:47 [App     ] Image loaded 183: IMG_1566.JPG
> 01:07:47 [App     ] Image loaded 184: IMG_1567.JPG
> 01:07:47 [App     ] Image loaded 185: IMG_1568.JPG
> 01:07:47 [App     ] Image loaded 186: IMG_1569.JPG
> 01:07:47 [App     ] Image loaded 187: IMG_1570.JPG
> 01:07:47 [App     ] Image loaded 188: IMG_1571.JPG
> 01:07:47 [App     ] Image loaded 189: IMG_1572.JPG
> 01:07:47 [App     ] Image loaded 190: IMG_1573.JPG
> 01:07:47 [App     ] Image loaded 191: IMG_1574.JPG
> 01:07:48 [App     ] Image loaded 192: IMG_1575.JPG
> 01:07:48 [App     ] Image loaded 193: IMG_1576.JPG
> 01:07:48 [App     ] Image loaded 194: IMG_1577.JPG
> 01:07:48 [App     ] Image loaded 195: IMG_1578.JPG
> 01:07:48 [App     ] Image loaded 196: IMG_1579.JPG
> 01:07:48 [App     ] Image loaded 197: IMG_1580.JPG
> 01:07:48 [App     ] Image loaded 198: IMG_1581.JPG
> 01:07:48 [App     ] Image loaded 199: IMG_1582.JPG
> 01:07:48 [App     ] Image loaded 200: IMG_1583.JPG
> 01:07:48 [App     ] Image loaded 201: IMG_1584.JPG
> 01:07:48 [App     ] Image loaded 202: IMG_1585.JPG
> 01:07:48 [App     ] Image loaded 203: IMG_1586.JPG
> 01:07:48 [App     ] Image loaded 204: IMG_1587.JPG
> 01:07:48 [App     ] Image loaded 205: IMG_1588.JPG
> 01:07:48 [App     ] Image loaded 206: IMG_1589.JPG
> 01:07:48 [App     ] Image loaded 207: IMG_1590.JPG
> 01:07:49 [App     ] Image loaded 208: IMG_1591.JPG
> 01:07:49 [App     ] Image loaded 209: IMG_1592.JPG
> 01:07:49 [App     ] Image loaded 210: IMG_1593.JPG
> 01:07:49 [App     ] Scene loaded from interface format (20s147ms):
> 	211 images (180 calibrated) with a total of 2733.75 MPixels (15.19 MPixels/image)
> 	218959 points, 0 vertices, 0 faces
> 01:07:56 [App     ] Preparing images for dense reconstruction completed: 211 images (6s673ms)
> 01:07:56 [App     ] Selecting images for dense reconstruction completed: 180 images (627ms)
> Estimated depth-maps 180 (100%, 4h26m14s84ms)            
> Filtered depth-maps 180 (100%, 9m6s826ms)          
> Fused depth-maps 180 (100%, 1h7m58s983ms)         
> 06:56:32 [App     ] Depth-maps fused and filtered: 180 depth-maps, 543535275 depths, 43574631 points (8%%) (1h13m14s815ms)
> 07:09:53 [App     ] Densifying point-cloud completed: 43574631 points (6h2m4s12ms)
> 07:13:15 [App     ] Scene saved (3m22s145ms):
> 	211 images (180 calibrated)
> 	43574631 points, 0 vertices, 0 faces
> 07:13:26 [App     ] Point-cloud saved: 43574631 points (10s598ms)
> 07:13:29 [App     ] MEMORYINFO: {
> 07:13:29 [App     ] 	VmPeak:	62089368 kB
> 07:13:29 [App     ] 	VmSize:	52057520 kB
> 07:13:29 [App     ] } ENDINFO
> 07:14:13 [App     ] Build date: Jun 18 2018, 17:30:17
> 07:14:13 [App     ] CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
> 07:14:13 [App     ] RAM: 15.54GB Physical Memory 48.10GB Virtual Memory
> 07:14:13 [App     ] OS: Linux 4.10.0-28-generic (x86_64)
> 07:14:13 [App     ] SSE & AVX compatible CPU & OS detected
> 07:14:13 [App     ] Command line: scene_dense.mvs
> 07:14:13 [App     ] CUDA device 0 initialized: GeForce GTX 960M (compute capability 5.0; memory 3.95GB)
> 07:15:10 [App     ] Scene loaded (56s130ms):
> 	211 images (180 calibrated) with a total of 683.44 MPixels (3.80 MPixels/image)
> 	43574631 points, 0 vertices, 0 faces
> Points inserted 43574631 (100%, 3m49s193ms)           
> 07:19:37 [App     ] Delaunay tetrahedralization completed: 43574631 points -> 7663194 vertices, 44868451 (+548) cells, 89737176 (+822) faces (4m20s875ms)
> Points weighted 7663194 (100%, 5m1s31ms)           
> 07:25:14 [App     ] Delaunay tetrahedras weighting completed: 44868999 cells, 89737998 faces (5m35s931ms)
> 07:29:02 [App     ] Delaunay tetrahedras graph-cut completed (1.66808e+07 flow): 6302363 vertices, 12605167 faces (3m47s528ms)
> 07:32:59 [App     ] Mesh reconstruction completed: 6302493 vertices, 12604447 faces (17m47s398ms)
> 07:34:25 [App     ] Cleaned mesh: 6300545 vertices, 12600214 faces (1m26s478ms)

The process ReconstructMesh is now still active and has been for over 8 hrs (currently shows 12% CPU and is using 5.4 GB of RAM, it's now 14:12 and last reported timestamp as you can see is 7:34). Is this a normal process and should I wait until something else happens? Or is this a sign that the process has frozen at this step?

Thanks for your fine work.

**Comment by jpwhitney** [comment]
Same still

**Comment by cdcseacave** [comment]
no, this is not normal, you can try run reconstruct mesh again

**Comment by LamboAventador** [comment]
@jpwhitney Did you solve this problem? I was also stuck in ReconstructMesh step.
`$OPENMVS_BIN_PATH/ReconstructMesh -d 6 scene_dense.mvs
16:25:40 [App     ] Build date: Jan 17 2019, 11:20:33
16:25:40 [App     ] CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
16:25:40 [App     ] RAM: 15.61GB Physical Memory 9.54GB Virtual Memory
16:25:40 [App     ] OS: Linux 4.18.0-13-generic (x86_64)
16:25:40 [App     ] SSE & AVX compatible CPU & OS detected
16:25:40 [App     ] Command line: -d 6 scene_dense.mvs
16:25:52 [App     ] Scene loaded (11s437ms):
	77 images (77 calibrated) with a total of 220.30 MPixels (2.86 MPixels/image)
	14698574 points, 0 vertices, 0 faces
Points inserted 14698574 (100%, 38s951ms)           
16:26:39 [App     ] Delaunay tetrahedralization completed: 14698574 points -> 1302654 vertices, 8135445 (+122) cells, 16270951 (+183) faces (46s684ms)
Points weighted 47535 (3.65%, 2s, ETA 1m)...段错误 (核心已转储)`

**Comment by jpwhitney** [comment]
No, as I recall it seemed to be a memory issue, (not enough RAM). I haven't tried the clustering method discussed [here](https://github.com/cdcseacave/openMVS/issues/231), but it does seem promising. For this dataset I ended up using [OpenDroneMap](https://github.com/OpenDroneMap/ODM) to make the desired georeferenced DEM.

**Comment by LamboAventador** [comment]
Thanks for your reply.  It seem to caused by different Eigen version as issue#219 mentioned. I have solved my problem. Hope this is helpful to your work.
