### ISSUE TITLE
Compile error: libboost_system.so.1.58.0: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by jianweike** [cdcseacave/openMVS#346]
### Specifications like the version of the project, operating system, and hardware
Ubuntu 16.04
### Steps to reproduce the problem
I could compile and use OpenMVS both in Debug and Release mode, but recently when I tried to recompile OpenMVS, linking error happens. It seems like something unexpected going on when linking boost. 

I followed exactly the instructions in https://github.com/cdcseacave/openMVS/wiki/Building. 
Then cmake 
cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT="$main_path/vcglib" -DBUILD_SHARED_LIBS=ON

[ 78%] Linking CXX executable ../../bin/ReconstructMesh
/usr/bin/ld: CMakeFiles/ReconstructMesh.dir/ReconstructMesh.cpp.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
apps/ReconstructMesh/CMakeFiles/ReconstructMesh.dir/build.make:95: recipe for target 'bin/ReconstructMesh' failed
make[2]: *** [bin/ReconstructMesh] Error 1
CMakeFiles/Makefile2:711: recipe for target 'apps/ReconstructMesh/CMakeFiles/ReconstructMesh.dir/all' failed
make[1]: *** [apps/ReconstructMesh/CMakeFiles/ReconstructMesh.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 80%] Linking CXX executable ../../bin/InterfaceVisualSFM
/usr/bin/ld: CMakeFiles/InterfaceVisualSFM.dir/InterfaceVisualSFM.cpp.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/build.make:95: recipe for target 'bin/InterfaceVisualSFM' failed
make[2]: *** [bin/InterfaceVisualSFM] Error 1
CMakeFiles/Makefile2:601: recipe for target 'apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/all' failed
make[1]: *** [apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/all] Error 2
[ 81%] Linking CXX executable ../../bin/DensifyPointCloud
/usr/bin/ld: CMakeFiles/DensifyPointCloud.dir/DensifyPointCloud.cpp.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
apps/DensifyPointCloud/CMakeFiles/DensifyPointCloud.dir/build.make:95: recipe for target 'bin/DensifyPointCloud' failed
make[2]: *** [bin/DensifyPointCloud] Error 1
CMakeFiles/Makefile2:656: recipe for target 'apps/DensifyPointCloud/CMakeFiles/DensifyPointCloud.dir/all' failed
make[1]: *** [apps/DensifyPointCloud/CMakeFiles/DensifyPointCloud.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Thank you all in advanced.

**Comment by jianweike** [comment]
In my project I also tried to link openmvs as third library. It was fine before until recently linking error happens. I couldn't recall what I changed. 
usr/bin/ld: warning: libopencv_videoio.so.3.2, needed by /usr/local/lib/libOpenImageIO.so, may conflict with libopencv_videoio.so.3.3
/usr/bin/ld: warning: libopencv_imgproc.so.3.2, needed by /usr/local/lib/libOpenImageIO.so, may conflict with libopencv_imgproc.so.3.3
/usr/bin/ld: warning: libopencv_core.so.3.2, needed by /usr/local/lib/libOpenImageIO.so, may conflict with libopencv_core.so.3.3
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.2, needed by /usr/local/lib/libopencv_videoio.so.3.2, may conflict with libopencv_imgcodecs.so.3.3
/home/jianwei/Documents/openMVS-Test/openMVS_build_debug_2/lib/libMVS.a(SceneDensify.cpp.o): In function `SEACAVE::Util::Progress::process()':
SceneDensify.cpp:(.text._ZN7SEACAVE4Util8Progress7processEv[_ZN7SEACAVE4Util8Progress7processEv]+0x40): undefined reference to `SEACAVE::Timer::GetTimeFactor()'
/home/jianwei/Documents/openMVS-Test/openMVS_build_debug_2/lib/libMVS.a(SceneDensify.cpp.o): In function `SEACAVE::Util::Progress::close()':
SceneDensify.cpp:(.text._ZN7SEACAVE4Util8Progress5closeEv[_ZN7SEACAVE4Util8Progress5closeEv]+0x38): undefined reference to `SEACAVE::Timer::GetTimeFactor()'
/home/jianwei/Documents/openMVS-Test/openMVS_build_debug_2/lib/libMVS.a(SceneDensify.cpp.o): In function `DepthMapsData::FilterDepthMap(MVS::DepthData&, SEACAVE::cList<unsigned int, unsigned int, 0, 16, unsigned long> const&, bool)':
SceneDensify.cpp:(.text._ZN13DepthMapsData14FilterDepthMapERN3MVS9DepthDataERKN7SEACAVE5cListIjjLi0ELi16EmEEb+0x187b): undefined reference to `SEACAVE::Timer::GetTimeFactor()'
/home/jianwei/Documents/openMVS-Test/openMVS_build_debug_2/lib/libMVS.a(SceneDensify.cpp.o): In function `MVS::Scene::DenseReconstructionFilter(void*)':
SceneDensify.cpp:(.text._ZN3MVS5Scene25DenseReconstructionFilterEPv+0x57): undefined reference to `SEACAVE::EventQueue::GetEvent(unsigned int)'
SceneDensify.cpp:(.text._ZN3MVS5Scene25DenseReconstructionFilterEPv+0x9b): undefined reference to `SEACAVE::EventQueue::GetEvent(unsigned int)'
SceneDensify.cpp:(.text._ZN3MVS5Scene25DenseReconstructionFilterEPv+0xd1): undefined reference to `SEACAVE::EventQueue::AddEventFirst(SEACAVE::Event*)'
SceneDensify.cpp:(.text._ZN3MVS5Scene25DenseReconstructionFilterEPv+0xb54): undefined reference to `SEACAVE::EventQueue::AddEvent(SEACAVE::Event*)'
SceneDensify.cpp:(.text._ZN3MVS5Scene25DenseReconstructionFilterEPv+0xb7e): undefined reference to `SEACAVE::EventQueue::AddEventFirst(SEACAVE::Event*)'
/home/jianwei/Documents/openMVS-Test/openMVS_build_debug_2/lib/libMVS.a(SceneDensify.cpp.o): In function `DepthMapsData::FuseDepthMaps(MVS::PointCloud&, bool)':
SceneDensify.cpp:(.text._ZN13DepthMapsData13FuseDepthMapsERN3MVS10PointCloudEb+0xe63): undefined reference to `SEACAVE::Timer::GetTimeFactor()'
SceneDensify.cpp:(.text._ZN13DepthMapsData13FuseDepthMapsERN3MVS10PointCloudEb+0x10dc): undefined reference to `SEACAVE::Timer::GetTimeFactor()'
SceneDensify.cpp:(.text._ZN13DepthMapsData13FuseDepthMapsERN3MVS10PointCloudEb+0x238b): undefined reference to `SEACAVE::Timer::GetTimeFactor()'
/home/jianwei/Documents/openMVS-Test/openMVS_build_debug_2/lib/libMVS.a(SceneDensify.cpp.o): In function `DepthMapsData::InitDepthMap(MVS::DepthData&)':
SceneDensify.cpp:(.text._ZN13DepthMapsData12InitDepthMapERN3MVS9DepthDataE+0xf17): undefined reference to `SEACAVE::Timer::GetTimeFactor()'
/home/jianwei/Documents/openMVS-Test/openMVS_build_debug_2/lib/libMVS.a(SceneDensify.cpp.o): In function `DepthMapsData::EstimateDepthMap(unsigned int)':
SceneDensify.cpp:(.text._ZN13DepthMapsData16EstimateDepthMapEj+0x1429): undefined reference to `SEACAVE::Timer::GetTimeFactor()'
/home/jianwei/Documents/openMVS-Test/openMVS_build_debug_2/lib/libMVS.a(SceneDensify.cpp.o): In function `MVS::Scene::DenseReconstructionEstimate(void*)':
SceneDensify.cpp:(.text._ZN3MVS5Scene27DenseReconstructionEstimateEPv+0x64): undefined reference to `SEACAVE::EventQueue::GetEvent()'
SceneDensify.cpp:(.text._ZN3MVS5Scene27DenseReconstructionEstimateEPv+0xac): undefined reference to `SEACAVE::EventQueue::AddEvent(SEACAVE::Event*)'
SceneDensify.cpp:(.text._ZN3MVS5Scene27DenseReconstructionEstimateEPv+0x6fd): undefined reference to `SEACAVE::EventQueue::AddEventFirst(SEACAVE::Event*)'
SceneDensify.cpp:(.text._ZN3MVS5Scene27DenseReconstructionEstimateEPv+0x73c): undefined reference to `SEACAVE::EventQueue::AddEvent(SEACAVE::Event*)'
SceneDensify.cpp:(.text._ZN3MVS5Scene27DenseReconstructionEstimateEPv+0x82c): undefined reference to `SEACAVE::EventQueue::AddEventFirst(SEACAVE::Event*)'
SceneDensify.cpp:(.text._ZN3MVS5Scene27DenseReconstructionEstimateEPv+0xa45): undefined reference to `SEACAVE::EventQueue::AddEvent(SEACAVE::Event*)'
SceneDensify.cpp:(.text._ZN3MVS5Scene27DenseReconstructionEstimateEPv+0xc0e): undefined reference to `SEACAVE::EventQueue::AddEventFirst(SEACAVE::Event*)'
SceneDensify.cpp:(.text._ZN3MVS5Scene27DenseReconstructionEstimateEPv+0xc41): undefined reference to `SEACAVE::Timer::GetTimeFactor()'
SceneDensify.cpp:(.text._ZN3MVS5Scene27DenseReconstructionEstimateEPv+0xe55): undefined reference to `SEACAVE::EventQueue::AddEventFirst(SEACAVE::Event*)'
SceneDensify.cpp:(.text._ZN3MVS5Scene27DenseReconstructionEstimateEPv+0xe8b): undefined reference to `SEACAVE::Timer::GetTimeFactor()'
/home/jianwei/Documents/openMVS-Test/openMVS_build_debug_2/lib/libMVS.a(SceneDensify.cpp.o): In function `MVS::Scene::DenseReconstruction()':
SceneDensify.cpp:(.text._ZN3MVS5Scene19DenseReconstructionEv+0x10d4): undefined reference to `SEACAVE::Timer::GetTimeFactor()'
SceneDensify.cpp:(.text._ZN3MVS5Scene19DenseReconstructionEv+0x131c): undefined reference to `SEACAVE::Timer::GetTimeFactor()'
SceneDensify.cpp:(.text._ZN3MVS5Scene19DenseReconstructionEv+0x13f0): undefined reference to `SEACAVE::EventQueue::AddEvent(SEACAVE::Event*)'
SceneDensify.cpp:(.text._ZN3MVS5Scene19DenseReconstructionEv+0x1784): undefined reference to `SEACAVE::EventQueue::IsEmpty() const'
SceneDensify.cpp:(.text._ZN3MVS5Scene19DenseReconstructionEv+0x186a): undefined reference to `SEACAVE::EventQueue::AddEvent(SEACAVE::Event*)'
SceneDensify.cpp:(.text._ZN3MVS5Scene19DenseReconstructionEv+0x1ae1): undefined reference to `SEACAVE::EventQueue::IsEmpty() const'
/home/jianwei/Documents/openMVS-Test/openMVS_build_debug_2/lib/libMVS.a(Scene.cpp.o): In function `boost::archive::detail::common_iarchive<boost::archive::text_iarchive>::~common_iarchive()':
Scene.cpp:(.text._ZN5boost7archive6detail15common_iarchiveINS0_13text_iarchiveEED2Ev[_ZN5boost7archive6detail15common_iarchiveINS0_13text_iarchiveEED5Ev]+0x8): undefined reference to `boost::archive::detail::basic_iarchive::~basic_iarchive()'
/home/jianwei/Documents/openMVS-Test/openMVS_build_debug_2/lib/libMVS.a(Scene.cpp.o): In function `boost::archive::detail::common_iarchive<boost::archive::text_iarchive>::~common_iarchive()':
Scene.cpp:(.text._ZN5boost7archive6detail15common_iarchiveINS0_13text_iarchiveEED0Ev[_ZN5boost7archive6detail15common_iarchiveINS0_13text_iarchiveEED5Ev]+0xc): undefined reference to `boost::archive::detail::basic_iarchive::~basic_iarchive()'

**Comment by liumarcus70s** [comment]
I got the same issue. Did u get the answer?

**Comment by PaulDebus** [comment]
I have a similar issue when building with the `-DBUILD_SHARED_LIBS=ON` flag. Linking of the interface visual sfm binary fails.

**Comment by kravinash** [comment]
I have the same issue. Any one found a solution

**Comment by rellikb** [comment]
Try updating your CMakeLists.txt to:
find_package(Boost COMPONENTS filesystem system REQUIRED)

**Comment by WenyinWei** [comment]
@PaulDebus Yes, Paul is right. The error disappears after unsetting the option.

**Comment by berniegach** [comment]
Also had the same problem setting  -DBUILD_SHARED_LIBS=ON worked for me.
