### ISSUE TITLE
Build Error  on ubuntu 14.04 , target_link CGAL

### ISSUE THREAD

**Issue by narutojxl** [cdcseacave/openMVS#349]
### Specifications like the version of the project, operating system, and hardware
Hello,   i follow this  [https://github.com/cdcseacave/openMVS/blob/master/BUILD.md](openMVS BUILD GUIDE), and installed CGAL  by `sudo apt-get install libcgal-dev  libcgal-demo ` , but when i  cmake  openMVS, it says can not link CGAL, but the printed log info says "CGAL 4.2 found (include: /usr/include)" , here is the result:
`jxl@jxl-dell:~/openMVS_build$ cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT="/home/jxl/openMVS/vcglib"
CMake Deprecation Warning at CMakeLists.txt:30 (cmake_policy):
  The OLD behavior for policy CMP0011 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- cotire 1.8.0 loaded.
-- Detected version of GNU GCC: 48 (408)
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Can't find CUDA. Continuing without it.
-- WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   iostreams
--   program_options
--   system
--   serialization
--   regex
-- Eigen 3.3.3 found (include: /usr/local/include/eigen3)
-- OpenCV 2.4.13 found (include: /usr/local/include/opencv;/usr/local/include)
-- CGAL 4.2 found (include: /usr/include)
-- VCG  found (include: /home/jxl/openMVS/vcglib)
-- GLEW  found (include: /usr/include)
-- Can't find GLFW3. Continuing without it.
-- Configuring done
CMake Error at build/Utils.cmake:808 (add_library):
  Target "MVS" links to target "CGAL::CGAL" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  libs/MVS/CMakeLists.txt:37 (cxx_library_with_type_no_pch)

CMake Error at build/Utils.cmake:842 (add_executable):
  Target "InterfaceVisualSFM" links to target "CGAL::CGAL" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  apps/InterfaceVisualSFM/CMakeLists.txt:8 (cxx_executable_with_flags_no_pch)

CMake Error at build/Utils.cmake:842 (add_executable):
  Target "DensifyPointCloud" links to target "CGAL::CGAL" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  apps/DensifyPointCloud/CMakeLists.txt:8 (cxx_executable_with_flags_no_pch)

CMake Error at build/Utils.cmake:842 (add_executable):
  Target "ReconstructMesh" links to target "CGAL::CGAL" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  apps/ReconstructMesh/CMakeLists.txt:8 (cxx_executable_with_flags_no_pch)

CMake Error at build/Utils.cmake:842 (add_executable):
  Target "RefineMesh" links to target "CGAL::CGAL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  apps/RefineMesh/CMakeLists.txt:8 (cxx_executable_with_flags_no_pch)

CMake Error at build/Utils.cmake:842 (add_executable):
  Target "TextureMesh" links to target "CGAL::CGAL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  apps/TextureMesh/CMakeLists.txt:8 (cxx_executable_with_flags_no_pch)

CMake Error at build/Utils.cmake:808 (add_library):
  Target "MVS" links to target "CGAL::CGAL" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  libs/MVS/CMakeLists.txt:37 (cxx_library_with_type_no_pch)

CMake Error at build/Utils.cmake:842 (add_executable):
  Target "InterfaceVisualSFM" links to target "CGAL::CGAL" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  apps/InterfaceVisualSFM/CMakeLists.txt:8 (cxx_executable_with_flags_no_pch)

CMake Error at build/Utils.cmake:842 (add_executable):
  Target "DensifyPointCloud" links to target "CGAL::CGAL" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  apps/DensifyPointCloud/CMakeLists.txt:8 (cxx_executable_with_flags_no_pch)

CMake Error at build/Utils.cmake:842 (add_executable):
  Target "ReconstructMesh" links to target "CGAL::CGAL" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  apps/ReconstructMesh/CMakeLists.txt:8 (cxx_executable_with_flags_no_pch)

CMake Error at build/Utils.cmake:842 (add_executable):
  Target "RefineMesh" links to target "CGAL::CGAL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  apps/RefineMesh/CMakeLists.txt:8 (cxx_executable_with_flags_no_pch)

CMake Error at build/Utils.cmake:842 (add_executable):
  Target "TextureMesh" links to target "CGAL::CGAL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  apps/TextureMesh/CMakeLists.txt:8 (cxx_executable_with_flags_no_pch)

-- Generating done
-- Build files have been written to: /home/jxl/openMVS_build
jxl@jxl-dell:~/openMVS_build$ 
`

**Comment by sbocconi** [comment]
I have the same error on Mac, following the instructions on the wiki

**Comment by sbocconi** [comment]
For me here the CGAL_DIR path was wrong, I had to specify the path where the CGALConfig.cmake could be found, thus in my case:
`/usr/local/Cellar/cgal/4.12/lib/cmake/CGAL/`

and then the command was:
`cmake  . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT="$main_path/vcglib" -DCGAL_DIR="/usr/local/Cellar/cgal/4.12/lib/cmake/CGAL"`

**Comment by Henrywh15** [comment]
Did you solve the problem on ubuntu？I face the same problem。

**Comment by cdcseacave** [comment]
did u try latest develop branch?

**Comment by Henrywh15** [comment]
I tried to install CGAL again，and I solved the  problem.

**Comment by Soup666** [comment]
> CGALConfig.cmake

This worked for me
