### ISSUE TITLE
Compilation error - gmp undefined symbol

### ISSUE THREAD

**Issue by kwahoo2** [cdcseacave/openMVS#35]
Compilation fails for me in the final (linking) stage.

```
Linking CXX executable ../../bin/ReconstructMesh
/usr/bin/ld: ../../lib/libMVS.a(SceneReconstruct.cpp.o): undefined reference to symbol '__gmpq_mul'
/usr/lib/x86_64-linux-gnu/libgmp.so.10: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
apps/ReconstructMesh/CMakeFiles/ReconstructMesh.dir/build.make:122: polecenia dla obiektu 'bin/ReconstructMesh' nie powiodły się
make[2]: *** [bin/ReconstructMesh] Błąd 1
CMakeFiles/Makefile2:655: polecenia dla obiektu 'apps/ReconstructMesh/CMakeFiles/ReconstructMesh.dir/all' nie powiodły się
make[1]: *** [apps/ReconstructMesh/CMakeFiles/ReconstructMesh.dir/all] Błąd 2
Makefile:75: polecenia dla obiektu 'all' nie powiodły się
make: *** [all] Błąd 2
```

cmake was invoked with those arguments:

```
cmake . ../openMVS -DCMAKE_BUILD_TYPE=RELEASE -DVCG_DIR="$main_path/vcglib" -DCERES_DIR="/usr/local/share/Ceres" -DOpenCV_CAN_BREAK_BINARY_COMPATIBILITY=OFF -DOpenMVG_DIR:STRING="/home/adi/Desktop/fotogrametria/openMVG_Build/openMVG_install/share/openMVG/cmake/"
```

and final info of cmake configuration:

```
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE) 
-- Can't find CUDA. Continuing without it.
-- WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   iostreams
--   program_options
--   system
--   serialization
-- Eigen 3.2.5 found (include: /usr/include/eigen3)
-- OpenCV 2.4.9 found (include: /usr/include/opencv;/usr/include;/usr/share/OpenCV/include)
-- CGAL found (include: /usr/include/include;/usr/include/auxiliary/gmp/include)
-- VCG  found (include: /home/adi/Desktop/fotogrametria/vcglib)
-- Found required Ceres dependency: Eigen version 3.2.5 in /usr/include/eigen3
-- Found required Ceres dependency: Glog in /usr/include
-- Found Ceres version: 1.11.0 installed in: /usr/local
-- CERES 1.11.0 found (include: /usr/local/include;/usr/include/eigen3;/usr/include;/usr/local/include)
-- ----
-- OpenMVG Find_Package
-- ----
-- Found OpenMVG version: 0.8.1
-- Installed in: /home/adi/Desktop/fotogrametria/openMVG_Build/openMVG_install
-- Used OpenMVG libraries: openMVG_image;openMVG_features;openMVG_matching_image_collection;openMVG_kvld;openMVG_multiview;openMVG_lInftyComputerVision;openMVG_system;openMVG_sfm
-- ----
-- Configuring done
-- Generating done
-- Build files have been written to: /home/adi/Desktop/fotogrametria/openMVS_Build
```

Ubuntu 15.10, 64bit.

**Comment by rperrot** [comment]
Make sure you install the gmp developer libs : 

```
sudo apt-get install libgmp-dev
```

**Comment by kwahoo2** [comment]
Thank you for the reply. libgmp-dev is installed
`
$ dpkg-query -L libgmp-dev
/.
/usr
/usr/include
/usr/include/x86_64-linux-gnu
/usr/include/x86_64-linux-gnu/gmp.h
/usr/include/gmpxx.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libgmpxx.a
/usr/lib/x86_64-linux-gnu/libgmp.a
/usr/share
/usr/share/doc
/usr/share/doc/libgmp-dev
/usr/share/doc/libgmp-dev/AUTHORS
/usr/share/doc/libgmp-dev/copyright
/usr/share/doc/libgmp-dev/README.gz
/usr/share/doc/libgmp-dev/NEWS.gz
/usr/lib/x86_64-linux-gnu/libgmpxx.so
/usr/lib/x86_64-linux-gnu/libgmp.so
/usr/share/doc/libgmp-dev/changelog.Debian.gz
`
I'll investigate CMakeLists.txt and share results later.

**Comment by rperrot** [comment]
Maybe an issue with 32 bits compilation and 64 bits libs (or vice versa).

**Comment by cdcseacave** [comment]
Thank you, Romuald, for helping with this issue. I wish I could help, but I have no clue what the problem is (for me seems strange that the library compiles at all on linux, it is such a messed up environment in my opinion)

**Comment by kwahoo2** [comment]
Finally compiled successfully under U15.10, after adding:

```
-DCGAL_ROOT="/usr/lib/x86_64-linux-gnu/cmake/CGAL/"
```

Full cmake options
```
cmake . ../openMVS -DCMAKE_BUILD_TYPE=RELEASE -DVCG_DIR="$main_path/vcglib" -DCERES_DIR="/usr/local/share/Ceres" -DOpenCV_CAN_BREAK_BINARY_COMPATIBILITY=OFF -DOpenMVG_DIR:STRING="$main_path/openMVG_Build/openMVG_install/share/openMVG/cmake/" -DCGAL_ROOT="/usr/lib/x86_64-linux-gnu/cmake/CGAL/"

```

**Comment by yudhisthira123** [comment]
Hello every one,
I am also facing this issue while linking gmp lib in my android project.  I have some static libraries ( .a extension ) and try to compile and get shared library ( .so extension ) see my logs...

FAILED: : && /Users/yudhisthira/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv5te-none-linux-androideabi --gcc-toolchain=/Users/yudhisthira/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/yudhisthira/Library/Android/sdk/ndk-bundle/sysroot -fPIC -isystem /Users/yudhisthira/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=15 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++1z -frtti -fexceptions -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot /Users/yudhisthira/Library/Android/sdk/ndk-bundle/platforms/android-15/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -L/Users/yudhisthira/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ../../../../build/intermediates/cmake/debug/obj/armeabi/libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/andr_crypto_core.c.o CMakeFiles/native-lib.dir/src/main/cpp/CException.c.o CMakeFiles/native-lib.dir/src/main/cpp/crypto_core.c.o CMakeFiles/native-lib.dir/src/main/cpp/csmp.c.o  ../../../../src/main/cpp/jniLibs/armeabi/libgmp.a ../../../../src/main/cpp/jniLibs/armeabi/libhogweed.a ../../../../src/main/cpp/jniLibs/armeabi/libnettle.a ../../../../src/main/cpp/jniLibs/armeabi/libsodium.a -llog -latomic -lm "/Users/yudhisthira/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi/libc++.a" && :
  ecc-384.c:102: error: undefined reference to '__gmpn_cnd_add_n'
  ecc-j-to-a.c:64: error: undefined reference to '__gmpn_copyi'
  ecc-j-to-a.c:65: error: undefined reference to '__gmpn_zero'
  ecc-j-to-a.c:67: error: undefined reference to '__gmpn_zero'
  ecc-j-to-a.c:73: error: undefined reference to '__gmpn_copyi'
  ecc-j-to-a.c:74: error: undefined reference to '__gmpn_zero'
  ecc-j-to-a.c:83: error: undefined reference to '__gmpn_copyi'
  ecc-add-jjj.c:100: error: undefined reference to '__gmpn_copyi'
  ecc-mul-g.c:63: error: undefined reference to '__gmpn_zero'
  ecc-point.c:82: error: undefined reference to '__gmpz_sub'
  ecc-point.c:83: error: undefined reference to '__gmpz_add_ui'
  ecc-point.c:84: error: undefined reference to '__gmpz_mul_ui'
  ecc-point.c:85: error: undefined reference to '__gmpz_mul_ui'
  gmp-glue.c:177: error: undefined reference to '__gmpz_limbs_read'
  gmp-glue.c:191: error: undefined reference to '__gmpz_limbs_modify'
  gmp-glue.c:205: error: undefined reference to '__gmpz_limbs_read'
  gmp-glue.c:213: error: undefined reference to '__gmpz_limbs_write'
  gmp-glue.c:214: error: undefined reference to '__gmpz_limbs_finish'
  gmp-glue.c:317: error: undefined reference to '__gmp_get_memory_functions'
  gmp-glue.c:327: error: undefined reference to '__gmp_get_memory_functions'
  gmp-glue.c:338: error: undefined reference to '__gmp_get_memory_functions'
  gmp-glue.c:349: error: undefined reference to '__gmp_get_memory_functions'
  ecc-mod.c:83: error: undefined reference to '__gmpn_cnd_add_n'
  ecc-mod.c:110: error: undefined reference to '__gmpn_cnd_add_n'
  ecc-mod-inv.c:141: error: undefined reference to '__gmpn_cnd_sub_n'
  ecc-mod-inv.c:142: error: undefined reference to '__gmpn_cnd_add_n'
  ecc-mod-inv.c:146: error: undefined reference to '__gmpn_cnd_sub_n'
  ecc-mod-arith.c:62: error: undefined reference to '__gmpn_cnd_sub_n'
  ecc-mod-arith.c:63: error: undefined reference to '__gmpn_cnd_sub_n'
  ecc-a-to-j.c:47: error: undefined reference to '__gmpn_copyd'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

I have 2 setup with me in one setup it is working fine but in another setup it is not compiling

**1) Working setup =>** 
      In this I am using gradle experimental version to link with STATIC libs. gradle script looks something like this ... 
         repositories {
        libs(PrebuiltLibraries) {
            gmp {
                headers.srcDir "src/main/jni/include"
                binaries.withType(StaticLibraryBinary) {
                    staticLibraryFile = file("src/main/jni/jniLibs/${targetPlatform.getName()}/libgmp.a")
                }
            }
        }
    }
**1) Not Working setup =>** 
     Here I am trying to build with cmake. And I have created CmakeList.txt .here i get those undefined references..

Could anyone please guide me to fix this issue.

**Comment by rdp** [comment]
See https://stackoverflow.com/questions/25944209/nettle-3-0-and-gmp-6-0-0-undefined-symbols-gmpz-limbs-write-gmpz-limbs-read perhaps

**Comment by mengdandel** [comment]
@yudhisthira123 Have you resolved the problem ? I have met the same thing.

**Comment by tkalfaoglu** [comment]
Just  FYI, I solved the same problem by adding:
 /usr/lib64/libgmp.so
to the end of the line in:
/home/turgut/openMVS_build/apps/ReconstructMesh/CMakeFiles/ReconstructMesh.dir/link.txt
