### ISSUE TITLE
How to remove faces with no texture in TextureMesh

### ISSUE THREAD

**Issue by XudongYong** [cdcseacave/openMVS#352]
### Specifications like the version of the project, operating system, and hardware
openMVS master, Ubuntu 16.04 with 16G RAM
### Steps to reproduce the problem
Hi @cdcseacave ,
Thanks for your great contribution! Currently, I'm trying to modify the normal pipeline (SparsePointCloud -> DensifyPointCloud -> Mesh -> Texture) without using the DensifyPointCloud step. Now, I can get a reasonable 3D model except one thing. From below snapshot, we can see there are several faces with no texture but just predefined yellow color and these faces are introduced owing to mesh with sparse point cloud. 
To keep the effect, I want to remove these faces with no texture. I look deep into the source code and find the part named "create texture patches" in function FaceViewSelection() of SceneTexture.cpp, and I think maybe I can remove faces in the last element of texturePatches, but I don't know how to establish the relationship between "scene.mesh.faces" and "texturePatches.Last().faces". 
For the problem "how to remove faces with no texutre", could you give me any suggestions?
![snapshot00](https://user-images.githubusercontent.com/17871648/42503261-dcc21ba8-846a-11e8-8027-66f5426f20fa.png)

**Comment by XudongYong** [comment]
Today I fix this issue and my guess is right, that "scene.mesh.faces" and "texturePatches.Last().faces" is one-to-one correspondence in index. Meanwhile, the faceTexcoords should also be updated after removing textureless faces. Since this issue has been fixed, I will close this thread.

**Comment by calmelo** [comment]
> Today I fix this issue and my guess is right, that "scene.mesh.faces" and "texturePatches.Last().faces" is one-to-one correspondence in index. Meanwhile, the faceTexcoords should also be updated after removing textureless faces. Since this issue has been fixed, I will close this thread.

How did you resolve the problem? Can you share steps and codes?

**Comment by cdcseacave** [comment]
Pls try this PR https://github.com/cdcseacave/openMVS/pull/1162

**Comment by calmelo** [comment]
> Pls try this PR #1162

Thanks! But I use the 1.1.1 version, and the changes are adapted to version 2? I try to add those codes to version 1.1.1, which leads to the incorrect results. Some places which can be textured correctly are textured with the empty color. This is really strange. Do you know how can I fix this bug?

**Comment by cdcseacave** [comment]
Pls use latest OpenMVS code in develop

**Comment by calmelo** [comment]
> Pls use latest OpenMVS code in develop

However, the latest texture result is incorrect. What's the difference between poses of version 2 and version 1? I can get the correct texture using version 1.1.1

**Comment by cdcseacave** [comment]
there are no differences

**Comment by calmelo** [comment]
> there are no differences

Version2.3.0, master branch, can obtain the correct result using "TextureMesh scene_dense.mvs -m scene_dense_mesh_refine.ply -o scene_dense_mesh_refine_texture.mvs" from the openmvs_sample. However, using the same data and command, version 1.1.1 get the error "14:15:19 [App     ] unrecognised option '-m'". I change the -m to --mesh-file, and get the error "14:15:29 [App     ] error: invalid project". Why I get the different results using version 2.3.0 and 1.1.1?

**Comment by calmelo** [comment]
> there are no differences

There are my own data result of version 1.1.1 and 2.3.0:
![openmvs1 1 1](https://github.com/user-attachments/assets/0ed2617b-ade8-48d0-bb97-3508cc76609c)
![openmvs2 3 0](https://github.com/user-attachments/assets/2808520a-89d7-46ec-b36c-39ffdcd6069c)
The result of version 1.1.1 is correct, but the result of version 2.3.0 is significantly offset towards the upper right.

**Comment by cdcseacave** [comment]
so you are saying that you get the correct result with 2.3.0, so just use it, no need for 1.1.1 now, right?
```
Version2.3.0, master branch, can obtain the correct result 
```

**Comment by calmelo** [comment]
> so you are saying that you get the correct result with 2.3.0, so just use it, no need for 1.1.1 now, right?
> 
> ```
> Version2.3.0, master branch, can obtain the correct result 
> ```

Now for my own data, I can get the correct result using version 1.1.1, but cannot get the correct result using version 2.3.0. I don't know why, so I want to know the differences between the two branch.

**Comment by calmelo** [comment]
> Pls try this PR #1162

I try to add those codes to version 1.1.1, which leads to the incorrect results. Some places which can be textured correctly are textured with the empty color. The empty color is set to white.
![Uploading openmvs1.1.1_remove.png…]()

**Comment by calmelo** [comment]
> Pls try this PR #1162

I try to add those codes to version 1.1.1, which leads to the incorrect results. Some places which can be textured correctly are textured with the empty color. The empty color is set to white.
![openmvs1 1 1_remove](https://github.com/user-attachments/assets/61c3f5c1-7613-4212-abb4-ccdabca0bc77)
