### ISSUE TITLE
Snap package not working

### ISSUE THREAD

**Issue by PaulDebus** [cdcseacave/openMVS#355]
Hey,
I installed the snap package on Ubuntu 18.04. Using the InterfaceVisualSFM as described in the documentation, I get the following output:

```
> openmvs.InterfaceVisualSFM -i model.nvm
libdc1394 error: Failed to initialize libdc1394
10:00:10 [App     ] Build date: Mar 15 2017, 11:57:05
10:00:10 [App     ] CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
10:00:10 [App     ] RAM: 31.34GB Physical Memory 2.00GB Virtual Memory
10:00:10 [App     ] OS: Linux 4.15.0-24-generic (x86_64)
10:00:10 [App     ] SSE & AVX compatible CPU & OS detected
10:00:10 [App     ] Command line: -i model.nvm
10:00:10 [App     ] Loading cameras/points: model.nvm
>
```
Nothing more happens. When compiling from source myself, it works well. Is there a way to test and/or update the snap?

Thanks for the great tool and the support!!!

**Comment by cdcseacave** [comment]
Pls address this issue to the person that crate the package. I did not do it and I do not know who did.

**Comment by PaulDebus** [comment]
Ok, thanks. I tried this but did not find a way to contact them. Will try again. Sorry for the inconvenience.
