### ISSUE TITLE
ReconstructMesh exits after delaunay tetrahedras weighting

### ISSUE THREAD

**Issue by quadrplax** [cdcseacave/openMVS#356]
Hello, apologies if I am posting this in the wrong place. I am having some trouble getting OpenMVS to reconstruct a mesh from a dense point cloud. 

### Specifications like the version of the project, operating system, and hardware
Build date: May 26 2017, 18:38:57
CPU: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
RAM: 15.88GB Physical Memory 128.00TB Virtual Memory
GPU: GTX 1070
OS: Windows 10+ x64
SSE & AVX compatible CPU & OS detected

### Steps to reproduce the problem
After completing the delaunay tetrahedras weighting step, the program exits after a few seconds with no error message. This is in contrast to another model I have ran through the same pipeline (sparse point cloud from Colmap, InterfaceVisualSFM, DensifyPointCloud, ReconstructMesh, RefineMesh, TextureMesh). The main difference I am aware of between the two datasets is that the one that works is smaller, and its going around an object instead of a room. This object one will complete other steps after the weighting, such as graph-cut, and end with a completed mesh file, while the room one does not generate any output. The log is below. I tried increasing the verbosity level to 3, but it didn't output any more information that way. Does anyone have any idea what I'm doing wrong? I'm pretty new to this, so any help would be greatly appreciated!

```
14:54:23 [App     ] Build date: May 26 2017, 18:38:57
14:54:23 [App     ] CPU: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
14:54:23 [App     ] RAM: 15.88GB Physical Memory 128.00TB Virtual Memory
14:54:23 [App     ] OS: Windows 10+ x64
14:54:23 [App     ] SSE & AVX compatible CPU & OS detected
14:54:23 [App     ] Command line: -i model_dense.mvs -o model_dense_mesh.mvs
14:54:33 [App     ] Scene loaded (9s582ms):
        255 images (255 calibrated) with a total of 151.70 MPixels (0.59 MPixels/image)
        8434376 points, 0 vertices, 0 faces
Points inserted 8434376 (100%, 1m46s487ms)
14:56:29 [App     ] Delaunay tetrahedralization completed: 8434376 points -> 7307944 vertices, 47235585 (+220) cells, 94471280 (+330) faces (1m51s529ms)
Points weighted 7307944 (100%, 2m4s127ms)
14:59:09 [App     ] Delaunay tetrahedras weighting completed: 47235805 cells, 94471610 faces (2m38s506ms)
```

**Comment by cdcseacave** [comment]
You are running out of memory. Try add RAM, increase virtual memory or decrease the point density using the `-d` command.

**Comment by quadrplax** [comment]
Thank you, I was able to get it to work by closing Chrome and MeshLab. I had no idea that the graph-cut step took so much RAM! In case I want to process something bigger in the future, what would be the process of adding virtual memory? Does that just mean increasing the size of the pagefile in Windows (currently 8GB on my SSD and 24GB on my HDD)? Thanks again for the help!
