### ISSUE TITLE
Build Error on MacOS

### ISSUE THREAD

**Issue by dytmh** [cdcseacave/openMVS#357]
### Specifications like the version of the project, operating system, and hardware
macOS 10.13.5

### Steps to reproduce the problem
cotire 1.8.0 loaded.
Boost version: 1.67.0
Found the following Boost libraries:
  iostreams
  program_options
  system
  serialization
  regex
Eigen 3.3.4 found (include: /usr/local/include/eigen3)
OpenCV 3.4.2 found (include: /Volumes/SATAHD/opencv/build;/Volumes/SATAHD/opencv/include;/Volumes/SATAHD/opencv/include/opencv;/Volumes/SATAHD/opencv/modules/core/include;/Volumes/SATAHD/opencv/modules/flann/include;/Volumes/SATAHD/opencv/modules/imgproc/include;/Volumes/SATAHD/opencv/modules/ml/include;/Volumes/SATAHD/opencv/modules/objdetect/include;/Users/dyt/work/opencv_contrib/modules/phase_unwrapping/include;/Volumes/SATAHD/opencv/modules/photo/include;/Users/dyt/work/opencv_contrib/modules/plot/include;/Users/dyt/work/opencv_contrib/modules/reg/include;/Users/dyt/work/opencv_contrib/modules/surface_matching/include;/Volumes/SATAHD/opencv/modules/video/include;/Users/dyt/work/opencv_contrib/modules/xphoto/include;/Volumes/SATAHD/opencv/modules/dnn/include;/Users/dyt/work/opencv_contrib/modules/face/include;/Users/dyt/work/opencv_contrib/modules/fuzzy/include;/Users/dyt/work/opencv_contrib/modules/hfs/include;/Users/dyt/work/opencv_contrib/modules/img_hash/include;/Volumes/SATAHD/opencv/modules/imgcodecs/include;/Volumes/SATAHD/opencv/modules/shape/include;/Volumes/SATAHD/opencv/modules/videoio/include;/Users/dyt/work/opencv_contrib/modules/xobjdetect/include;/Volumes/SATAHD/opencv/modules/highgui/include;/Volumes/SATAHD/opencv/modules/superres/include;/Volumes/SATAHD/opencv/modules/ts/include;/Users/dyt/work/opencv_contrib/modules/bioinspired/include;/Users/dyt/work/opencv_contrib/modules/dnn_objdetect/include;/Users/dyt/work/opencv_contrib/modules/dpm/include;/Volumes/SATAHD/opencv/modules/features2d/include;/Users/dyt/work/opencv_contrib/modules/line_descriptor/include;/Users/dyt/work/opencv_contrib/modules/saliency/include;/Users/dyt/work/opencv_contrib/modules/text/include;/Volumes/SATAHD/opencv/modules/calib3d/include;/Users/dyt/work/opencv_contrib/modules/ccalib/include;/Users/dyt/work/opencv_contrib/modules/cvv/include;/Users/dyt/work/opencv_contrib/modules/datasets/include;/Users/dyt/work/opencv_contrib/modules/rgbd/include;/Users/dyt/work/opencv_contrib/modules/stereo/include;/Users/dyt/work/opencv_contrib/modules/structured_light/include;/Users/dyt/work/opencv_contrib/modules/tracking/include;/Volumes/SATAHD/opencv/modules/videostab/include;/Users/dyt/work/opencv_contrib/modules/xfeatures2d/include;/Users/dyt/work/opencv_contrib/modules/ximgproc/include;/Users/dyt/work/opencv_contrib/modules/aruco/include;/Users/dyt/work/opencv_contrib/modules/bgsegm/include;/Users/dyt/work/opencv_contrib/modules/optflow/include;/Volumes/SATAHD/opencv/modules/stitching/include)
__cplusplus is 199711
Boost version: 1.67.0
Found the following Boost libraries:
  thread
  system
  chrono
  date_time
  atomic
Boost include dirs: /usr/local/include
Boost libraries:    /usr/local/lib/libboost_thread.dylib;/usr/local/lib/libboost_system.dylib;/usr/local/lib/libboost_chrono.dylib;/usr/local/lib/libboost_date_time.dylib;/usr/local/lib/libboost_atomic.dylib
CGAL 4.12 found (include: /usr/local/Cellar/cgal/4.12//include)
VCG  found (include: /Users/dyt/work/vcglib)
Found installed version of Eigen: /usr/local/share/eigen3/cmake
Found required Ceres dependency: Eigen version 3.3.4 in /usr/local/include/eigen3
Found required Ceres dependency: glog
Found installed version of gflags: /usr/local/lib/cmake/gflags
Detected gflags version: 2.2.1
Found required Ceres dependency: gflags
Found Ceres version: 1.14.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations]
CERES 1.14.0 found (include: /usr/local/include;/usr/local/include/eigen3;/usr/local/include;/usr/local/include)
GLEW  found (include: /usr/local/include)
GLFW3 3.2.1 found (include: )
Configuring done
Generating done

Scanning dependencies of target InterfaceVisualSFM
[ 75%] Building CXX object apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/InterfaceVisualSFM.cpp.o
In file included from /Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/InterfaceVisualSFM.cpp:32:
In file included from /Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/Common.h:42:
In file included from /Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/../Common/Common.h:176:
In file included from /Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/../Common/Types.h:440:
/Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/../Common/Log.h:66:40: warning: 'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a supported interface. For SYS_kdebug_trace use kdebug_signpost().
      [-Wdeprecated-declarations]
                std::ostringstream& ostr = m_streams[__THREAD__];
                                                     ^
/Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/../Common/Types.h:201:41: note: expanded from macro '__THREAD__'
#  define __THREAD__ ((unsigned)((pid_t)syscall(SYS_gettid)))
                                        ^
/usr/include/unistd.h:745:6: note: 'syscall' has been explicitly marked deprecated here
int      syscall(int, ...);
         ^
In file included from /Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/InterfaceVisualSFM.cpp:32:
In file included from /Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/Common.h:42:
In file included from /Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/../Common/Common.h:176:
In file included from /Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/../Common/Types.h:440:
/Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/../Common/Log.h:86:40: warning: 'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a supported interface. For SYS_kdebug_trace use kdebug_signpost().
      [-Wdeprecated-declarations]
                std::ostringstream& ostr = m_streams[__THREAD__];
                                                     ^
/Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/../Common/Types.h:201:41: note: expanded from macro '__THREAD__'
#  define __THREAD__ ((unsigned)((pid_t)syscall(SYS_gettid)))
                                        ^
/usr/include/unistd.h:745:6: note: 'syscall' has been explicitly marked deprecated here
int      syscall(int, ...);
         ^
In file included from /Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/InterfaceVisualSFM.cpp:32:
In file included from /Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/Common.h:42:
In file included from /Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/../Common/Common.h:176:
In file included from /Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/../Common/Types.h:442:
/Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/../../libs/MVS/../Common/SML.h:29:21: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
        ~SMLVALUE_TYPE() { delete data; }
                           ^      ~~~~
/Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/InterfaceVisualSFM.cpp:377:4: warning: bool literal returned from 'main' [-Wmain]
                        return false;
                        ^      ~~~~~
/Volumes/SATAHD/openMVS/apps/InterfaceVisualSFM/InterfaceVisualSFM.cpp:389:4: warning: bool literal returned from 'main' [-Wmain]
                        return false;
                        ^      ~~~~~
5 warnings generated.
make[2]: *** No rule to make target `/usr/local/lib/libboost_thread-mt.dylib', needed by `bin/InterfaceVisualSFM'.  Stop.
make[1]: *** [apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/all] Error 2
make: *** [all] Error 2

**Comment by pilafniev** [comment]
Not sure if you solved this yet, but I had the same error and I just compiled with Xcode, make sure is up to date.

in openMVS_build:

cmake -DCMAKE_BUILD_TYPE=RELEASE -G "Xcode" . ../openMVS -DVCG_ROOT="$main_path/vcglib"

xcodebuild -configuration Release
