### ISSUE TITLE
Recover 3D coordinates from Ortho Projection

### ISSUE THREAD

**Issue by didi16** [cdcseacave/openMVS#365]
Hi, 

I have adapted the ProjectOrhtoTopDown to do the orthoprojection of the pointcloud from whatever point I want. For that, I orient the camera using camera.R.SetFromOrthogonalBasis. Everything works as it should until this point, as given by the corresponding ortho projection image I am able to see. However, once I try to recover the 3D coordinates of a certain pixel these are not correct, except when I rotate the point cloud 90 or 180 degrees (in any axis).
I feel I am a bit lost here... I know exactly how I want to orient my point cloud or the camera, I am just not sure whether I am doing it correctly or not. Also, to recover 3D position I don't know if I should use  
	Point3 xyzCoordinates  	= camera.TransformPointI2W(Point3(xCenter.x, xCenter.y, camera.C.z ));
or 
	Point3 pointInWorldFrame = camera.TransformPointI2W(Point3(xCenter.y, xCenter.x ));

I have the feeling that this is related with the last variable parse to the functions. 
My main two questions are:
-> How to get the 3D Coordinates of any point given any orthoprojection
-> Is it possible to rotate each point of the pointcloud at any stage of computations?

Best regards,
Diogo Martins.

**Comment by didi16** [comment]
Does that mean using `Point3 xyzCoordinates = camera.TransformPointI2W(Point3(xCenter.x, xCenter.y, camera.C.z ));` ?

**Comment by cdcseacave** [comment]
pls check the last commit I just pushed

**Comment by didi16** [comment]
Isn't that function exactly the same as this one? Which was already implemented
`	inline TPoint3<TYPE> TransformPointI2C(const TPoint3<TYPE>& X) const {
		return TPoint3<TYPE>(
			TYPE((X.x-K(0,2))*X.z/K(0,0)),
			TYPE((X.y-K(1,2))*X.z/K(1,1)),
			X.z );
	}`

**Comment by didi16** [comment]
Thank you so much for your help! 
How is possible to make the correct recovery of the Z coordinate of any pixel from the image, since that information is lost when you make the orthoprojection?

**Comment by cdcseacave** [comment]
not possible if lost
