### ISSUE TITLE
RefineMesh produces nothing?

### ISSUE THREAD

**Issue by AIBluefisher** [cdcseacave/openMVS#366]
Hi, @cdcseacave 

I use openMVS to refine mesh, but when it goes to the end, nothing produced! I provide an .mvs file and a .ply file  that are generated by my program. The command I used and the running procedure is shown below:
![image](https://user-images.githubusercontent.com/18096136/46196378-7b100600-c339-11e8-841b-0b9fdaba8354.png)

After that, nothing changed! Could you tell me what's wrong?

Thank you very much!

**Comment by cdcseacave** [comment]
You should try first running RefineMesh normally on the project file generated by the previous module, ReconstructMesh. You do not need to pass the ply file as input, only the MVS file. (all ply files are only for vizualization purposes)

**Comment by AIBluefisher** [comment]
Actually, I didn't use ReconstructMesh to produce mesh, I just used my own program to generate the mesh, and export the file that the OpenMVS required, then, I use RefineMesh on my project file to read the mesh.mvs file. I use the source code of InterfaceMVS.h in my project to generate the .mvs file.

Besides, I re-run the RefineMesh without passing the ply file, but error occurs as the figure shown below:
![image](https://user-images.githubusercontent.com/18096136/46239968-fb367a00-c3d2-11e8-9a04-36fc959f9fa8.png)
The last row reports an error: ```error: empty initial mesh```. It's a puzzle.
