### ISSUE TITLE
Integrate openMVS and openMVG in VS2017 project!

### ISSUE THREAD

**Issue by danielunifim55** [cdcseacave/openMVS#367]
Hi guys!

I am working on a program to obtain orthorectified mosaic of aerial images. I used openMVG to perform SFM steps and now I want to densify my point cloud. I think I have installed successfully openMVS because I run DensifyCloudPoint in console and it works. I created a project on VS2017 where I am using some code of openMVG. Now I want to use the code of DensifyPointCloud.cpp but I am having the following problems:

1. After the configuration of the properties of the project, I have a lot of errors in DepthMap.h, matx.hpp, operations.hpp and type.hpp such as "Vec3 is ambiguous", "MVS::DepthEstimator::ViewData::ViewData() provides no initializer for:", "class SEACAVE::TRMatrixBase<double> has no member t" and more errors for DepthMath and the rest.

2. I am not sure how to pass the inputs for DensifyPointCloud because the parameters for the main function are read from command line.

I am new using C++ and I really do not know how to configure the project well in order to use openMVG, openMVS and then I have to generate a DEM so I will use another library. I hope you can help me @cdcseacave 

Thanks a lot!

**Comment by pmoulon** [comment]
Seems like a variable name exists in the two frameworks.
Using the namespace accordingly should fix the issue.

**Comment by danielunifim55** [comment]
Hello @pmoulon !

Thank you. Yeah there are some variable name defined in two framework. I solve some of them with the namespace, but in matx.hpp (openMVS) there is a class "Matx" with namespace "cv", and in InterfaceMSV.h (openMVG) there is another class called "Matx" with the same namespace. What should I do? Change the class name of one of them?

Thank you!

**Comment by cdcseacave** [comment]
best C++ practice is to never use something like `using namespace <name>`, especially inside header files, and always use the full type name, including the namespace, ex: `cv::Matx`. However this is not an OpenMVS related issue, but C++, so I'll have to close it.
