### ISSUE TITLE
Improper distortion parameters for interfacevisualsfm?

### ISSUE THREAD

**Issue by charlescva** [cdcseacave/openMVS#371]
Any idea why my sparse NVM would densify to this kind of noisy result? Could it be the undistorted pngs?

![screenshot from 2018-10-11 12-38-22](https://user-images.githubusercontent.com/5343462/46820009-2619ba00-cd53-11e8-93bd-c480f0640bbf.png)

**Comment by charlescva** [comment]
I found an NVM description here,
http://ccwu.me/vsfm/doc.html#nvm

My NVM description file,
$ head Top-6Views.nvm
NVM_V3 

41
image_D2018-07-02T17-12-24-599997Z_2.jpg 4915.2 0.999899 0.00335589 -0.0137181 0.00155599 -0.0262821 -0.789873 0.115685 -0.0325684 0
image_D2018-07-02T17-12-24-133366Z_1.jpg 4915.2 0.921095 0.00940171 -0.389222 -0.00155583 -0.846123 -0.751313 0.457408 -0.0325684 0

I am going to attempt to read here to learn more,
https://github.com/cdcseacave/openMVS/blob/master/apps/InterfaceVisualSFM/InterfaceVisualSFM.cpp#L353

Thank you.

**Comment by charlescva** [comment]
When comparing the input images to the calibrated pngs generated in the 'undistorted_images' folder, it appears to my eye to be "good" with very subtle distortion removal when comparing the two.  So perhaps this is not related to the undistort.  So, I still do not understand why the dense point cloud in original post is very inaccurate.  I have densified other sparse point clouds and had very good quality results.

**Comment by cdcseacave** [comment]
VisualSFM uses two types of distortions models of one parameter, but afaik there is no way to specify that in the NVM format. Apart of that VisualSFM was found multiple times to deliver not so accurate reconstructions. In order to solve both problems at the same time, I recommend to use OpenMVG.

**Comment by charlescva** [comment]
Confirmed!  When treating each image as it's own camera, i obtain different optimized distortion coefficients (in theia).  The result in open MVS is that image distortion is input optimally.

![screenshot from 2018-10-11 15-26-22](https://user-images.githubusercontent.com/5343462/46828884-3f7a3080-cd6a-11e8-9adf-a7a40a7a689d.png)

**Comment by charlescva** [comment]
Example of working NVM Input:
`NVM_V3 

35
image_D2018-07-02T17-12-24-133366Z_1.jpg 3239.64 0.927545 0.372012 0.031035 -0.0174437 0.442909 -8.34573 9.28835 0.0224773 0
image_D2018-07-02T17-12-23-333347Z_1.jpg 3233.61 0.850107 0.331647 0.379211 -0.153384 4.48124 -6.77651 10.6636 -0.0588316 0
image_D2018-07-02T17-12-22-133354Z_1.jpg 3225.89 0.851405 0.328138 0.379017 -0.154211 4.56225 -5.9258 9.76172 -0.0288972 0
image_D2018-07-02T17-12-21-666682Z_0.jpg 3249.44 0.928544 0.36942 0.0311807 -0.0190424 0.5544 -7.25429 8.13811 -0.0299937 0
`

Example of unoptimized focal and distortion parameters:
`NVM_V3 

35
image_D2018-07-02T17-12-24-133366Z_1.jpg 2135.28 0.92753 0.372038 0.0312524 -0.0173106 0.440881 -8.27973 9.29788 -0.20483 0
image_D2018-07-02T17-12-23-333347Z_1.jpg 2135.28 0.856661 0.312512 0.378572 -0.158589 4.53848 -6.826 10.6668 -0.20483 0
image_D2018-07-02T17-12-22-133354Z_1.jpg 2135.28 0.851223 0.328138 0.379358 -0.154375 4.5507 -5.8945 9.74121 -0.20483 0
image_D2018-07-02T17-12-21-666682Z_0.jpg 2135.28 0.928633 0.369203 0.0310973 -0.0190796 0.549436 -7.1925 8.14821 -0.20483 0
`
