### ISSUE TITLE
The entire texture is too large to load into the meshlab

### ISSUE THREAD

**Issue by lcsdz** [cdcseacave/openMVS#373]
Hello,
I used openmvs to reconstruct a larger area. But I found that neither meshlab nor unity3d could be opened, mainly because the resulting texture image was too large.The above software supports only 8192 resolution.
Can openmvs generate multiple sub-textures with less than 8192 resolution?
Or what tools are available to break the entire texture into multiple subtextures?
Best regards.

**Comment by cdcseacave** [comment]
OpenMVS does not support creation of multiple textures, but this should be possible as a post processing: split the big texture in multiple smaller textures. However I do not know any such tool.

Does anybody know a texture processing tool that can retexture a given mesh?
