### ISSUE TITLE
OpenMPI Support

### ISSUE THREAD

**Issue by williamlai3a** [cdcseacave/openMVS#376]
Hi,
I am planning to let openMVS handling a large set of high-res photos.
In order to speed up the computation time, I am planning to set up a elastic HPC cluster in AWS.
However, that would require transforming openMVS to OpenMPI implementation.
Any ideas on how could achieve that? Or are there any other ways to speed up the process time?

Thanks!
William

**Comment by cdcseacave** [comment]
no, this is outside my competence
