### ISSUE TITLE
CUDA NVLink

### ISSUE THREAD

**Issue by williamlai3a** [cdcseacave/openMVS#377]
Hi,

I am trying to reconstruct a large set of High-Res photo using the MvgMvs pipeline in AWS p3.8xlarge instances with 4 Tesla V100 GPUs NVLinked.
However, it seems that DensifyPointCloud does not seem to see the NVLinked GPUs as one single logical unit. It neither uses all GPUs, instead it only initialized device 0.
Below is the App output:
```
#8. Densify point cloud
['/home/ubuntu/openMVS_build/bin/DensifyPointCloud', 'scene.mvs', '-w', '/media/                                                                                                                                                             data/oldhole_result/mvs']
17:03:56 [App     ] Build date: Oct 18 2018, 04:17:06
17:03:56 [App     ] CPU: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
17:03:56 [App     ] RAM: 240.09GB Physical Memory 0B Virtual Memory
17:03:56 [App     ] OS: Linux 4.4.0-1069-aws (x86_64)
17:03:56 [App     ] SSE & AVX compatible CPU & OS detected
17:03:56 [App     ] Command line: scene.mvs -w /media/data/oldhole_result/mvs
17:03:56 [App     ] MapSMtoCores for SM 7.0 is undefined; default to use 128 cores/SM
17:03:56 [App     ] MapSMtoCores for SM 7.0 is undefined; default to use 128 cores/SM
17:03:56 [App     ] MapSMtoCores for SM 7.0 is undefined; default to use 128 cores/SM
17:03:56 [App     ] MapSMtoCores for SM 7.0 is undefined; default to use 128 cores/SM
17:03:56 [App     ] CUDA device 0 initialized: Tesla V100-SXM2-16GB (compute capability 7.0; memory 15.78GB)
17:03:57 [App     ] Camera model loaded: platform 0; camera  0; f 0.965x0.965; poses 340
17:03:57 [App     ] Camera model loaded: platform 1; camera  0; f 0.786x0.786; poses 99
```

May I have any advises or pointer to what might go wrong?
Thanks.
William

**Comment by williamlai3a** [comment]
Another thing is that the GPU usage is indeed extremely low, it seems CUDA does not help much on the process:
```
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   36C    P0    50W / 300W |    419MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:00:1C.0 Off |                    0 |
| N/A   32C    P0    36W / 300W |     11MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   35C    P0    39W / 300W |     11MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   36C    P0    39W / 300W |     11MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2077      C   ...ntu/openMVS_build/bin/DensifyPointCloud   408MiB |
+-----------------------------------------------------------------------------+
```

However, I tried to launch a c5.18xlarge instance equipped with 72 vCPUs, the estimated finishing time is 1d8hrs, instead of 10h7m while using p3.8xlarge with only 32 vCPUs but with GPUs.
I really cannot understand the situation, and would like kind advises.

Thanks so much.
William

**Comment by cdcseacave** [comment]
The only module that is currently using GPU is RefineMesh. I never tested it on multiple GPUs.

**Comment by williamlai3a** [comment]
> The only module that is currently using GPU is RefineMesh. I never tested it on multiple GPUs.

Oh! So may I ask for DensifyPointCloud, does it Estimate depth-maps on one image per thread? 
Or does it Estimate depth-maps using all threads on one image by image?
Since it is weird that 72 vCPUs run much slower than a 32 vCPUs instance on the cloud.

Thanks!

**Comment by cdcseacave** [comment]
it estimates one image alone on all threads, this is efficient when tehre are not many CPUs

**Comment by jiaerping123** [comment]
> it estimates one image alone on all threads, this is efficient when tehre are not many CPUs

hi, I wonder if SceneDensify is implemented with CUDA, which has an impact on the reconstruction of point clouds？

**Comment by cdcseacave** [comment]
no, it is not

**Comment by jiaerping123** [comment]
> no, it is not
Sorry， I may not have made it clear. I have the following questions:
1.  I mean that If I use CUDA to calculate depth maps, can the accuracy be consistent with the CPU version?  
In my opinion， I don't think I'll get a better depth value than the CPU version through Spatial propagation, because these depths of the surrounding neighborhoods may not be updated yet.

2. Will you consider to provide depth map calculation for CUDA version in the future?

**Comment by jiaerping123** [comment]
> no, it is not

Sorry， I may not have made it clear. I have the following questions:
1. I mean that If I use CUDA to calculate depth maps, can the accuracy be consistent with the CPU version?
  In my opinion， I don't think I'll get a better depth value than the CPU version through Spatial propagation, because these depths of the surrounding neighborhoods may not be updated yet.
2. Will you consider to provide depth map calculation for CUDA version in the future?

**Comment by cdcseacave** [comment]
1. yes, there are special pattern you can follow to implement the parallelization needed for GPU, ex chess board pattern, see https://arxiv.org/abs/1904.08103
2. not a priority for me
