### ISSUE TITLE
Get 2d coordinations of a dense point cloud

### ISSUE THREAD

**Issue by McNicole** [cdcseacave/openMVS#379]
### Specifications like the version of the project, operating system, and hardware

Can I get the corresponding coordinates in the input image of each point of the dense point cloud?
Such as the openMVG output result of json file.
<img width="538" alt="2018-10-23 16 17 49" src="https://user-images.githubusercontent.com/44386819/47342679-3d579080-d6df-11e8-8f79-5f2b1c5d94c4.png">

### Steps to reproduce the problem

**Comment by cdcseacave** [comment]
sure you can, each dense point has a list of images in which is seen, so you just have to project the point in those images to get the pixel pos
