### ISSUE TITLE
How DensifyPointCloud does dense reconstruction from sparse reconstruction?

### ISSUE THREAD

**Issue by squashking** [cdcseacave/openMVS#382]
Could anyone give a brief introduction of the basic idea?
In the wiki, it's said the algorithm is based on the paper "PatchMatch: A Randomized Correspondance...". However that paper does not seem to be very relevant. Maybe it just adopts some idea from the paper.
I am trying to dig into the code and understand what openMVS actually does for dense reconstruction. But the code is not very straightforward.
Thank you!

**Comment by cdcseacave** [comment]
The code is indeed based on the ideas from that paper, but adapted to 3D point estimation case. There are many papers about patch-match for 3D out there, published after the original paper, pls check some of them to get the idea.

**Comment by cdcseacave** [comment]
Here is just a list I have:
2009 - PatchMatch A Randomized Correspondence Algorithm for Structural Image Editing - patchmatch.pdf
2010 - The Generalized PatchMatch Correspondence Algorithm - generalized_pm.pdf
2011 - PatchMatch Stereo - Stereo Matching with Slanted Support Windows - patchmatchstereo_bmvc2011_6mb.pdf
2012 - PMBP PatchMatch Belief Propagation for Correspondence Field Estimation - PMBP.pdf
2012 - PMBP PatchMatch Belief Propagation for Correspondence Field Estimation - PMPBPsupmat.pdf
2012 - Scale Robust Multi View Stereo - ECCV2012-Bailer-Finckh-SRMVS.pdf
2013 - Accurate Multiple View 3D Reconstruction Using Patch-Based Stereo for Large-Scale Scenes - TIP2013.pdf
2013 - PatchMatch Filter Efficient Edge-Aware Filtering Meets Randomized Search for Fast Correspondence Field%.pdf
2013 - PM-Huber PatchMatch with Huber Regularization for Stereo Matching - Heise2013.pdf
2014 - As-Rigid-As-Possible Stereo under Second Order Smoothness Priors - 86900112.pdf
2014 - PatchMatch Based Joint View Selection and Depthmap Estimation - cameraReady_enliangCVPR2014.pdf
2015 - Massively Parallel Multiview Stereopsis by Surface Normal Diffusion - galliani-lasinger-iccv15.pdf
2015 - SPM-BP Sped-up PatchMatch Belief Propagation for Continuous MRFs - SPM-BP_iccv2015_slides.pdf
2015 - SPM-BP Sped-up PatchMatch Belief Propagation for Continuous MRFs - SPM_BP-ICCV15.pdf
2016 - PatchMatch Filter Edge-Aware Filtering Meets Randomized Search for Visual Correspondence - PMF_PAMI_preprint.pdf

**Comment by squashking** [comment]
@cdcseacave Thanks for the quick answer. I _only_ want to know how **DensifyPointCloud** works.  Could you introduce a bit about the basic idea or give me a reference paper? Thank you!

**Comment by cdcseacave** [comment]
sure, np
the basic steps are:
- random intialization
- go over each pixel and evaluate neighbor pixel estimates if they perform better, if yes keep the best (propagation), and next evaluate current estimate with a small random offset (refinement)
- repeat previous step several times

**Comment by squashking** [comment]
@cdcseacave Thanks. The 2nd step, what does "each pixel" refer to? each pixel in each image or 3D points? Don't you make use of the already triangulated 3D point cloud from sparse reconstruction (e.g., from openMVG) ? And "evaluate current estimate" of what? Thank you very much!

**Comment by squashking** [comment]
@cdcseacave Maybe my understanding about dense reconstruction is wrong. Isn't it just to generate more 3D points based on the already given sparse 3D points? For example, sparse 3D reconstruction from openMVG generates 1000 3D points, and dense reconstruction (**DensifyPointCloud**) generates 10,000 3D points. How does dense reconstruction computes the rest 9000 points? That's what I want to know. As I said, maybe my understanding about dense reconstruction is completely wrong...

**Comment by squashking** [comment]
@cdcseacave After reading the PatchMatch paper, I start to understand a bit what you said. So you traverse all pixels in each image and try to find their matches in another image for each image pair, right?  After finding the matches, how do you compute the 3D points? Since there has already been camera poses information from sparse 3D reconstruction, what is the point of computing pixel-wise matches? I am still puzzled. Thank you very much for any answer!

**Comment by xuelinchao** [comment]
发电房
