### ISSUE TITLE
SceneReconstruct.cpp void fetchCellFacets(...) possible error?

### ISSUE THREAD

**Issue by williamlai3a** [cdcseacave/openMVS#383]
Hi,

While executing the function `void fetchCellFacets()` in SceneReconstruct.cpp
I am experiencing `segmentation fault (core dump)` during the constructor of `Frustum`.
`Frustum frustum(imageData.camera.P, imageData.width, imageData.width, 0, 1);`
I am not sure if it is intended to put both `imageData.width` instead of width and height of the `imageData` respectively. 
I also tried to modify the code to input width and height:
`Frustum frustum(imageData.camera.P, imageData.width, imageData.height, 0, 1);`
but the `segmentation fault (core dump)` is still there without any luck.

Note that not all input dataset experience this segmentation fault, would that possible to be some corner case?

Thanks for your always help!

**Comment by neoaurion** [comment]
Hi,
same issue for me using ReconstructMesh it crashes at fetchCellFacets. I've run in debug mode and it seems to be an alignement issue with eigen but I'm not good enough to solve this kind of issue

**Comment by cdcseacave** [comment]
I do not have details about the platform u r using, but I assume you built it on linux using Eigen 3.3.x instead of Eigen 3.2.x; if that's the case try rebuild with the older version of Eigen

**Comment by neoaurion** [comment]
All your assumptions were rights and it seems to work now with eigen 3.2 (reconstruction went further and is still ongoing). I'm on ubuntu 18.04 and the default eigen was 3.3. Thanks a lot :)
