### ISSUE TITLE
Errors building OpenMVS on Mac using Xcode

### ISSUE THREAD

**Issue by VerdaMunir** [cdcseacave/openMVS#384]
CGAL version: 4.13
When Installing OpenMVS using Xcode, it gives the following error:

No member named 'circumcenter' in 'CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<CGAL::Triangulation_data_structure_3<CGAL::Triangulation_vertex_base_with_info_3<DELAUNAY::vert_info_t, CGAL::Epick, CGAL::Triangulation_vertex_base_3<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<void> > >, CGAL::Sequential_tag> > > >'

It requires CGAL 4.2. But unable to compile it as I think it's not available for Mac.
I have tried many ways to compile it, but its giving the same error. 
I am new to this and would highly appreciate your time.

**Comment by cdcseacave** [comment]
pls try develop branch

**Comment by zhaozilongwhu** [comment]
it doesn't work~!

**Comment by VerdaMunir** [comment]
Can you please suggest any other alternatives for OpenMVS for Mac?

**Comment by cdcseacave** [comment]
I do not understand, first you said develop branch does not work and now that it works; which one is it?

**Comment by zhaozilongwhu** [comment]
I am sorry, I made a mistake about checkout the develop branch firstly ,then it doesn't work. Actually it work on develop branch! I develop on windows 10 with visual studio 2017.

**Comment by cdcseacave** [comment]
solved on latest develop
