### ISSUE TITLE
arnhf port progress: error: 'class CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<CGAL::Triangulation_data_structure_3<CGAL::Triangulation_vertex_base_with_info_3<DELAUNAY::vert_info_t, CGAL::Epick>, CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick> > > > >' has no member named 'circumcenter'

### ISSUE THREAD

**Issue by Joel-Mckay** [cdcseacave/openMVS#385]
This is a log of my attempt to get a demo port working on Raspbian/Debian Stretch.
Specifically, I am interested in metrics of how armhf architecture handles these types of challenges. as compared to the standard I7/CUDA benchmarks.

The CGAL build issue seemed similar to the MacOS build bug report, but the diff did not seem to offer a solution.   Any advice will certainly be welcomed... =) 
 
################
git clone https://github.com/CGAL/cgal.git 
cd ~/SRC/cgal
mkdir -p build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DWITH_CGAL_Qt5=OFF ..
make

################
cd ~/SRC
git clone https://ceres-solver.googlesource.com/ceres-solver
cd ~/SRC/ceres-solver
mkdir build
cd ~/SRC/ceres-solver/build
cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DEIGEN_INCLUDE_DIR=/usr/local/include/eigen3
make
sudo make install
sudo ldconfig

###############3
# OpenMVS
git clone --depth 1 https://github.com/cdcseacave/openMVS.git
cd openMVS
mkdir obuild 
cd ~/SRC/openMVS/obuild
export CGAL_ROOT="/usr/local/include/CGAL" 

/*************** patch ******************/
/* problem area for armhf port and CGAL  */
nano /home/pi/SRC/openMVS/libs/MVS/SceneReconstruct.cpp
...
#if !(defined(__arm__)  && defined(__ARMEL__))
#pragma GCC target ("no-fma")
#endif
...

/************** patch *******************/
/* fix type error */
nano /home/pi/SRC/openMVS/libs/MVS/Interface.h
...
#if defined(__arm__) || defined(__ARMEL__)
ARCHIVE_DEFINE_TYPE(uint64_t)
#else
ARCHIVE_DEFINE_TYPE(size_t)
#endif
...

/***************** patch ****************/
/* Bypass x86 CPU ID probes */
nano /home/pi/SRC/openMVS/libs/Common/Util.cpp
...
#ifdef _MSC_VER
#include <intrin.h>
inline void CPUID(int CPUInfo[4], int level) {
        __cpuid(CPUInfo, level);
}
#else
 #if !(defined(__arm__) || defined(__ARMEL__))
  #include <cpuid.h>
 #endif
inline void CPUID(int CPUInfo[4], int level) {
  #if !(defined(__arm__) || defined(__ARMEL__))
        unsigned* p((unsigned*)CPUInfo);
        __get_cpuid((unsigned&)level, p+0, p+1, p+2, p+3);
  #endif
}
#endif
 ...

//both versions of:
bool OSSupportsAVX()
{
 #if defined(__arm__) || defined(__ARMEL__)
    return false;
 #else
 ...
 #endif
}
...

####### build #########

cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT="/home/pi/SRC/vcglib" -DOpenMVS_USE_CUDA=OFF -DBUILD_SHARED_LIBS=ON \
-DOpenMVS_USE_SSE=OFF  -DOpenMVS_USE_FAST_CBRT=OFF -DOpenMVS_USE_FAST_FLOAT2INT=OFF \
-DCERES_DIR_HINTS=/usr/local/include/ceres  -DCERES_INCLUDE_DIR=/usr/local/include/ceres \
-DCGAL_DIR=/usr/local/lib/cmake/CGAL  -DCGAL_INCLUDE_DIR=/usr/local/include/CGAL -DOpenMVG_DIR=/usr/local/share/openMVG
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected version of GNU GCC: 63 (603)
-- Performing Test HAVE_CXX_W
-- Performing Test HAVE_CXX_W - Success
-- Performing Test HAVE_C_W
-- Performing Test HAVE_C_W - Success
-- Performing Test HAVE_CXX_WALL
-- Performing Test HAVE_CXX_WALL - Success
-- Performing Test HAVE_C_WALL
-- Performing Test HAVE_C_WALL - Success
-- Performing Test HAVE_CXX_WERROR_ADDRESS
-- Performing Test HAVE_CXX_WERROR_ADDRESS - Success
-- Performing Test HAVE_C_WERROR_ADDRESS
-- Performing Test HAVE_C_WERROR_ADDRESS - Success
-- Performing Test HAVE_CXX_WERROR_SEQUENCE_POINT
-- Performing Test HAVE_CXX_WERROR_SEQUENCE_POINT - Success
-- Performing Test HAVE_C_WERROR_SEQUENCE_POINT
-- Performing Test HAVE_C_WERROR_SEQUENCE_POINT - Success
-- Performing Test HAVE_CXX_WFORMAT
-- Performing Test HAVE_CXX_WFORMAT - Success
-- Performing Test HAVE_C_WFORMAT
-- Performing Test HAVE_C_WFORMAT - Success
-- Performing Test HAVE_CXX_WERROR_FORMAT_SECURITY
-- Performing Test HAVE_CXX_WERROR_FORMAT_SECURITY - Success
-- Performing Test HAVE_C_WERROR_FORMAT_SECURITY
-- Performing Test HAVE_C_WERROR_FORMAT_SECURITY - Success
-- Performing Test HAVE_CXX_WSTRICT_PROTOTYPES
-- Performing Test HAVE_CXX_WSTRICT_PROTOTYPES - Failed
-- Performing Test HAVE_C_WSTRICT_PROTOTYPES
-- Performing Test HAVE_C_WSTRICT_PROTOTYPES - Success
-- Performing Test HAVE_CXX_WINIT_SELF
-- Performing Test HAVE_CXX_WINIT_SELF - Success
-- Performing Test HAVE_C_WINIT_SELF
-- Performing Test HAVE_C_WINIT_SELF - Success
-- Performing Test HAVE_CXX_WSIGN_PROMO
-- Performing Test HAVE_CXX_WSIGN_PROMO - Success
-- Performing Test HAVE_C_WSIGN_PROMO
-- Performing Test HAVE_C_WSIGN_PROMO - Failed
-- Performing Test HAVE_CXX_WREORDER
-- Performing Test HAVE_CXX_WREORDER - Success
-- Performing Test HAVE_C_WREORDER
-- Performing Test HAVE_C_WREORDER - Failed
-- Performing Test HAVE_CXX_WNO_UNDEF
-- Performing Test HAVE_CXX_WNO_UNDEF - Success
-- Performing Test HAVE_C_WNO_UNDEF
-- Performing Test HAVE_C_WNO_UNDEF - Success
-- Performing Test HAVE_CXX_WNO_COMMENT
-- Performing Test HAVE_CXX_WNO_COMMENT - Success
-- Performing Test HAVE_C_WNO_COMMENT
-- Performing Test HAVE_C_WNO_COMMENT - Success
-- Performing Test HAVE_CXX_WNO_NARROWING
-- Performing Test HAVE_CXX_WNO_NARROWING - Success
-- Performing Test HAVE_C_WNO_NARROWING
-- Performing Test HAVE_C_WNO_NARROWING - Success
-- Performing Test HAVE_CXX_WNO_ATTRIBUTES
-- Performing Test HAVE_CXX_WNO_ATTRIBUTES - Success
-- Performing Test HAVE_C_WNO_ATTRIBUTES
-- Performing Test HAVE_C_WNO_ATTRIBUTES - Success
-- Performing Test HAVE_CXX_WNO_ENUM_COMPARE
-- Performing Test HAVE_CXX_WNO_ENUM_COMPARE - Success
-- Performing Test HAVE_C_WNO_ENUM_COMPARE
-- Performing Test HAVE_C_WNO_ENUM_COMPARE - Success
-- Performing Test HAVE_CXX_WNO_MISSING_DECLARATIONS
-- Performing Test HAVE_CXX_WNO_MISSING_DECLARATIONS - Success
-- Performing Test HAVE_C_WNO_MISSING_DECLARATIONS
-- Performing Test HAVE_C_WNO_MISSING_DECLARATIONS - Success
-- Performing Test HAVE_CXX_WNO_MISSING_PROTOTYPES
-- Performing Test HAVE_CXX_WNO_MISSING_PROTOTYPES - Failed
-- Performing Test HAVE_C_WNO_MISSING_PROTOTYPES
-- Performing Test HAVE_C_WNO_MISSING_PROTOTYPES - Success
-- Performing Test HAVE_CXX_WNO_MISSING_FIELD_INITIALIZERS
-- Performing Test HAVE_CXX_WNO_MISSING_FIELD_INITIALIZERS - Success
-- Performing Test HAVE_C_WNO_MISSING_FIELD_INITIALIZERS
-- Performing Test HAVE_C_WNO_MISSING_FIELD_INITIALIZERS - Success
-- Performing Test HAVE_CXX_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HAVE_CXX_WNO_UNUSED_LOCAL_TYPEDEFS - Success
-- Performing Test HAVE_C_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HAVE_C_WNO_UNUSED_LOCAL_TYPEDEFS - Success
-- Performing Test HAVE_CXX_WNO_DELETE_NON_VIRTUAL_DTOR
-- Performing Test HAVE_CXX_WNO_DELETE_NON_VIRTUAL_DTOR - Success
-- Performing Test HAVE_C_WNO_DELETE_NON_VIRTUAL_DTOR
-- Performing Test HAVE_C_WNO_DELETE_NON_VIRTUAL_DTOR - Failed
-- Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Performing Test HAVE_CXX_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HAVE_CXX_FDIAGNOSTICS_SHOW_OPTION - Success
-- Performing Test HAVE_C_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HAVE_C_FDIAGNOSTICS_SHOW_OPTION - Success
-- Performing Test HAVE_CXX_FTEMPLATE_BACKTRACE_LIMIT_0
-- Performing Test HAVE_CXX_FTEMPLATE_BACKTRACE_LIMIT_0 - Success
-- Performing Test HAVE_C_FTEMPLATE_BACKTRACE_LIMIT_0
-- Performing Test HAVE_C_FTEMPLATE_BACKTRACE_LIMIT_0 - Failed
-- Performing Test HAVE_CXX_PTHREAD
-- Performing Test HAVE_CXX_PTHREAD - Success
-- Performing Test HAVE_C_PTHREAD
-- Performing Test HAVE_C_PTHREAD - Success
-- Performing Test HAVE_CXX_FOMIT_FRAME_POINTER
-- Performing Test HAVE_CXX_FOMIT_FRAME_POINTER - Success
-- Performing Test HAVE_C_FOMIT_FRAME_POINTER
-- Performing Test HAVE_C_FOMIT_FRAME_POINTER - Success
-- Performing Test HAVE_CXX_FROUNDING_MATH
-- Performing Test HAVE_CXX_FROUNDING_MATH - Success
-- Performing Test HAVE_C_FROUNDING_MATH
-- Performing Test HAVE_C_FROUNDING_MATH - Success
-- Performing Test HAVE_CXX_FFUNCTION_SECTIONS
-- Performing Test HAVE_CXX_FFUNCTION_SECTIONS - Success
-- Performing Test HAVE_C_FFUNCTION_SECTIONS
-- Performing Test HAVE_C_FFUNCTION_SECTIONS - Success
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found OpenGL: /usr/lib/arm-linux-gnueabihf/libGL.so  
-- WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   iostreams
--   program_options
--   system
--   serialization
--   regex
-- Eigen 3.2.10 found (include: /usr/local/include/eigen3)
-- OpenCV 2.4.9.1 found (include: /usr/include/opencv;/usr/include)
-- __cplusplus is 201402
--   --> Do not link with Boost.Thread
-- Boost version: 1.62.0
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- CGAL 4.14 found (include: /usr/local//include)
-- VCG  found (include: /home/pi/SRC/vcglib)
-- GLEW  found (include: /usr/include)
-- GLFW3 3.2.1 found (include: )
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CERES_DIR_HINTS
    CERES_INCLUDE_DIR
    CGAL_INCLUDE_DIR

-- Build files have been written to: /home/pi/SRC/openMVS/obuild

...

make
[ 16%] Built target Common
[ 22%] Built target Math
[ 47%] Built target IO
[ 49%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/SceneReconstruct.cpp.o
In file included from /usr/local/include/eigen3/Eigen/Core:326:0,
                 from /home/pi/SRC/openMVS/libs/MVS/../Common/Types.h:120,
                 from /home/pi/SRC/openMVS/libs/MVS/../Common/Common.h:176,
                 from /home/pi/SRC/openMVS/libs/MVS/Common.h:42,
                 from /home/pi/SRC/openMVS/libs/MVS/SceneReconstruct.cpp:32:
/usr/local/include/eigen3/Eigen/src/Core/products/GeneralBlockPanelKernel.h: In member function 'void Eigen::internal::gebp_kernel<LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs>::operator()(Eigen::internal::gebp_kernel<LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs>::ResScalar*, Index, const LhsScalar*, const RhsScalar*, Index, Index, Index, Eigen::internal::gebp_kernel<LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs>::ResScalar, Index, Index, Index, Index, RhsScalar*)':
/usr/local/include/eigen3/Eigen/src/Core/products/GeneralBlockPanelKernel.h:574:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
         if(nr==4) traits.initAcc(C3);
         ^~
/usr/local/include/eigen3/Eigen/src/Core/products/GeneralBlockPanelKernel.h:575:19: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
                   traits.initAcc(C4);
                   ^~~~~~
/usr/local/include/eigen3/Eigen/src/Core/products/GeneralBlockPanelKernel.h:946:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
         if(nr==4) R3 = ploadu<ResPacket>(r3);
         ^~
/usr/local/include/eigen3/Eigen/src/Core/products/GeneralBlockPanelKernel.h:948:19: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
                   traits.acc(C0, alphav, R0);
                   ^~~~~~
/usr/local/include/eigen3/Eigen/src/Core/products/GeneralBlockPanelKernel.h:951:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
         if(nr==4) traits.acc(C3, alphav, R3);
         ^~
/usr/local/include/eigen3/Eigen/src/Core/products/GeneralBlockPanelKernel.h:953:19: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
                   pstoreu(r0, R0);
                   ^~~~~~~
In file included from /usr/local/include/eigen3/Eigen/SparseLU:29:0,
                 from /usr/local/include/eigen3/Eigen/Sparse:22,
                 from /home/pi/SRC/openMVS/libs/MVS/../Common/Types.h:122,
                 from /home/pi/SRC/openMVS/libs/MVS/../Common/Common.h:176,
                 from /home/pi/SRC/openMVS/libs/MVS/Common.h:42,
                 from /home/pi/SRC/openMVS/libs/MVS/SceneReconstruct.cpp:32:
/usr/local/include/eigen3/Eigen/src/SparseLU/SparseLU_gemm_kernel.h: In function 'void Eigen::internal::sparselu_gemm(Index, Index, Index, const Scalar*, Index, const Scalar*, Index, Scalar*, Index)':
/usr/local/include/eigen3/Eigen/src/SparseLU/SparseLU_gemm_kernel.h:78:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
         if(RK==4) b30 = pset1<Packet>(Bc0[3]);
         ^~
/usr/local/include/eigen3/Eigen/src/SparseLU/SparseLU_gemm_kernel.h:79:19: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
                   b01 = pset1<Packet>(Bc1[0]);
                   ^~~
In file included from /home/pi/SRC/openMVS/libs/MVS/../Common/Types.h:442:0,
                 from /home/pi/SRC/openMVS/libs/MVS/../Common/Common.h:176,
                 from /home/pi/SRC/openMVS/libs/MVS/Common.h:42,
                 from /home/pi/SRC/openMVS/libs/MVS/SceneReconstruct.cpp:32:
/home/pi/SRC/openMVS/libs/MVS/../Common/SML.h: In destructor 'SEACAVE::SMLVALUE_TYPE::~SMLVALUE_TYPE()':
/home/pi/SRC/openMVS/libs/MVS/../Common/SML.h:29:28: warning: deleting 'void*' is undefined [-Wdelete-incomplete]
  ~SMLVALUE_TYPE() { delete data; }
                            ^~~~
In file included from /home/pi/SRC/openMVS/libs/MVS/../Common/Common.h:176:0,
                 from /home/pi/SRC/openMVS/libs/MVS/Common.h:42,
                 from /home/pi/SRC/openMVS/libs/MVS/SceneReconstruct.cpp:32:
/home/pi/SRC/openMVS/libs/MVS/../Common/Types.h: In function 'float SEACAVE::cbrt5(float)':
/home/pi/SRC/openMVS/libs/MVS/../Common/Types.h:753:8: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  (int&)f = (((int&)f-(127<<23))/3+(127<<23));
        ^
/home/pi/SRC/openMVS/libs/MVS/../Common/Types.h:753:20: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  (int&)f = (((int&)f-(127<<23))/3+(127<<23));
                    ^
In file included from /home/pi/SRC/openMVS/libs/MVS/../Common/Common.h:176:0,
                 from /home/pi/SRC/openMVS/libs/MVS/Common.h:42,
                 from /home/pi/SRC/openMVS/libs/MVS/SceneReconstruct.cpp:32:
/home/pi/SRC/openMVS/libs/MVS/../Common/Types.h: In member function 'bool SEACAVE::TColor<TYPE>::operator==(const SEACAVE::TColor<TYPE>&) const [with TYPE = unsigned char]':
/home/pi/SRC/openMVS/libs/MVS/../Common/Types.h:1999:108: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 ::operator==(const TColor& col) const { return (*((const uint32_t*)c) == *((const uint32_t*)col.c)); }
                                                                     ^
/home/pi/SRC/openMVS/libs/MVS/../Common/Types.h:1999:137: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 or& col) const { return (*((const uint32_t*)c) == *((const uint32_t*)col.c)); }
                                                                           ^
/home/pi/SRC/openMVS/libs/MVS/../Common/Types.h: In member function 'bool SEACAVE::TColor<TYPE>::operator!=(const SEACAVE::TColor<TYPE>&) const [with TYPE = unsigned char]':
/home/pi/SRC/openMVS/libs/MVS/../Common/Types.h:2000:108: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 ::operator!=(const TColor& col) const { return (*((const uint32_t*)c) != *((const uint32_t*)col.c)); }
                                                                     ^
/home/pi/SRC/openMVS/libs/MVS/../Common/Types.h:2000:137: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 or& col) const { return (*((const uint32_t*)c) != *((const uint32_t*)col.c)); }
                                                                           ^
/home/pi/SRC/openMVS/libs/MVS/../Common/Types.h: In member function 'uint32_t SEACAVE::TColor<TYPE>::toDWORD() const [with TYPE = unsigned char; uint32_t = unsigned int]':
/home/pi/SRC/openMVS/libs/MVS/../Common/Types.h:2001:91: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 ine uint32_t TColor<uint8_t>::toDWORD() const { return *((const uint32_t*)c); }
                                                                            ^
/home/pi/SRC/openMVS/libs/MVS/SceneReconstruct.cpp: In function 'float DELAUNAY::computePlaneSphereAngle(const delaunay_t&, const facet_t&)':
/home/pi/SRC/openMVS/libs/MVS/SceneReconstruct.cpp:727:48: error: 'class CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<CGAL::Triangulation_data_structure_3<CGAL::Triangulation_vertex_base_with_info_3<DELAUNAY::vert_info_t, CGAL::Epick>, CGAL::Triangulation_cell_base_with_info_3<unsigned int, CGAL::Epick> > > > >' has no member named 'circumcenter'
  const Point3f cc(CGAL2MVS<float>(facet.first->circumcenter(Tr.geom_traits())));
                                                ^~~~~~~~~~~~
libs/MVS/CMakeFiles/MVS.dir/build.make:302: recipe for target 'libs/MVS/CMakeFiles/MVS.dir/SceneReconstruct.cpp.o' failed
make[2]: *** [libs/MVS/CMakeFiles/MVS.dir/SceneReconstruct.cpp.o] Error 1

**Comment by Joel-Mckay** [comment]
As mentioned here:
https://github.com/cdcseacave/openMVS/pull/375

This patch handles most of the remaining .o build errors for static libs :
https://aur.archlinux.org/cgit/aur.git/tree/cgal.patch?h=openmvs-git

note: An build error from use of -DBUILD_SHARED_LIBS=ON
[ 75%] Linking CXX executable ../../bin/InterfaceVisualSFM
/usr/bin/ld: CMakeFiles/InterfaceVisualSFM.dir/InterfaceVisualSFM.cpp.o: undefined reference to symbol '_ZN5boost15program_options29options_description_easy_initclEPKcS3_'
//usr/lib/arm-linux-gnueabihf/libboost_program_options.so.1.62.0: error adding symbols: DSO missing from command line

**Comment by cdcseacave** [comment]
can you pls create a PR for the armhf patches?
also, for the `circumcenter` error, the develop branch contains a custom implementation, can you pls check why is it not finding that one and still searches it inside CGAL?

**Comment by Joel-Mckay** [comment]
Our club has been developing a full-color 3D  printer, and is setting up open-process pipelines for Scanning, CAD, and CAM CNC manufacturing. On Dec 28, 2018 rc1 will probably include this project along with OpenMVG to allow people to play with the SfM pipelines ( https://sourceforge.net/projects/micrometer-cnc-on-raspberry-pi/ ).  
We only have a few users, but do gift our project hardware back to relevant open-source developers in hopes it will help them in their own project builds. Note, everything is hand-made around here, as we want hardware that will be useful 10 years from now. :-)

One project I am currently stuck with... as no one seems to volunteer to clean up Arduino code... is refactoring the old Horus laser scanner firmware to run on more recent hardware. At some-point, I may have to look at trying a simple scanner upgrade based on OpenMVG+OpenMVS, that can use the same motion controller to reduce search scopes (known theta+Z axis offsets).

There are always "big" possibilities in every action we take, but I prefer to build useful things for fun when possible... rather than to speculate what the future may show us. ;-)

Cheers,
~J~

**Comment by cdcseacave** [comment]
Cool project, good luck with it!
As for using photogrammetry instead of laser scaners it will not always be a good idea. While photogrammetry is easier to use and works great when the scene has enough texture and Lambertian materials, it will deliver worse results for scenes without texture. Photogrammetry can be used in such scenarios also if combined with structured light. Keep this in mind when recommending scanning techniques to your users.

**Comment by Joel-Mckay** [comment]
The plan so far:
I was thinking of also trying two simple quadrature encoded concentric rings of glyphs in a De Bruijn sequence to "cook" one plane with marker data that is always distinctive, water soluble gray scan-spay should take care of reflective/transparent objects,  and high contrast flat black spatter from a toothbrush should provide enough chaotic features for later extraction. 

The COLMAP based process of overlapping distinct features/edges we currently use is documented here: http://www.micrometer.xyz/cdn/node/89
I may be wrong about advising against that you-tube guys object ROI-crop advice (never looked into colmaps implementation), but we traditionally recommend a camera data source with consistent properties.

I would be curious if someone has tried the openMVG/openMVS pipeline on an HDR image data-set yet.
=)

**Comment by cdcseacave** [comment]
pls check the latest develop commit, this should solve the above issues

**Comment by qiancao** [comment]
Hi, I stumbled upon this thread after having the same issue ("no member circumcenter" for Triangular_cell_base_with_info_3). Could I ask what the solution was in the end? It was not obvious to me upon reading the thread.

`/usr/local/include/CGAL/Delaunay_triangulation_3.h:1835:13: error: ‘class CGAL::Triangulation_cell_base_with_info_3<CellInfo, CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<CGAL::Triangulation_data_structure_3<CGAL::Triangulation_vertex_base_with_info_3<VertexInfo, CGAL::Epick>, CGAL::Triangulation_cell_base_with_info_3<CellInfo, CGAL::Epick> > > > >’ has no member named ‘circumcenter’`

This happens with the libcgal-dev package on apt-get for ubuntu 20.04 as well as the master branch in the github repository for CGAL. Thanks!
