### ISSUE TITLE
Is there a way to filter the dense point cloud according the quality/confidence of the vertices ??

### ISSUE THREAD

**Issue by MartinAlexParis** [cdcseacave/openMVS#386]
It works great....i try to improve the quality by willing to filter the vertex at the generated dense point cloud by a confidence/quality criteria ?
But i do not see the info in the ply i generated.

**Comment by cdcseacave** [comment]
that info is stored individually for each image in the `dmap` file

**Comment by MartinAlexParis** [comment]
Thanks,  i saw them and the c++ code;
What is the fastest/easiest way to get this info ?

**Comment by cdcseacave** [comment]
the fastest is to add the filter code inside OpenMVS code, during densification

**Comment by MartinAlexParis** [comment]
ok, thank you
