### ISSUE TITLE
Compilation error (Eigen related)

### ISSUE THREAD

**Issue by FlachyJoe** [cdcseacave/openMVS#39]
On Debian sid with
Eigen 3.3alpha1.2
OpenCV 2.4.9.1
Ceres from git
CGAL 4.7.4
Boost 1.58
VCG from svn
OpenMVG from git

Compilation failed with this message :
```
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:817:30: error: invalid use of incomplete type ‘struct Eigen::internal::enable_if<false, SEACAVE::TPoint3<double>*>’
In file included from /usr/include/eigen3/Eigen/Core:295:0,
                 from ./openMVS/libs/MVS/../Common/Types.h:113,
                 from ./openMVS/libs/MVS/../Common/Common.h:176,
                 from ./openMVS/libs/MVS/Common.h:38,
                 from ./openMVS_Build/libs/MVS/cotire/MVS_CXX_prefix.cxx:4,
                 from ./openMVS_Build/libs/MVS/cotire/MVS_CXX_prefix.hxx:4:
```

Thks !

**Comment by cdcseacave** [comment]
This is no surprise, since you are using an alpha version. I do not have time and patience to test and debug alpha versions of third party libs, but if you fix it I can add the patch.

**Comment by FlachyJoe** [comment]
The problem is that SEACAVE::TPoint3<double>* is not defined when Eigen is include.
But I'm not C++ guru so I'm not able to fix it ;-)

PS :
