### ISSUE TITLE
  Please help me...

### ISSUE THREAD

**Issue by wujun007** [cdcseacave/openMVS#390]
Compiled openMVS project, I generated in VS error, prompting C++ does not support int type, how to solve it?

**Comment by chris-aeviator** [comment]
You could try using a docker container that has openMVS pre-installed: https://github.com/berlius/openMVS

you will have a ready-to-use system by simply running:  `docker run -it --name openmvs --volume $(pwd):/opt/myProject berlius/openmvs bash`

**Comment by cdcseacave** [comment]
update to latest vcpkg version and rerun the build instructions
