### ISSUE TITLE
SceneDensify.cpp, in function InitDepthMap(), bad Point3f conversion when calling Image8U::RasterizeTriangle()

### ISSUE THREAD

**Issue by romain-75** [cdcseacave/openMVS#393]
When compiling on OSX with Clang, in InitDepthMap(), file SceneDensify.cpp, line :

`Image8U::RasterizeTriangle((const Point2f&)i2, (const Point2f&)i1, (const Point2f&)i0, data);`

the conversions from Point3f (i2,i1 and i0) to Point2f using `(const Point2f&)` give wrong values, so corrupt initialization through delaunay triangulation and make initialization very long by rasterizing very big triangles.

I replace the previous line by :
```
const Point2f i2b(i2.x, i2.y);
const Point2f i1b(i1.x, i1.y);
const Point2f i0b(i0.x, i0.y);
Image8U::RasterizeTriangle(i2b, i1b, i0b, data);
```
and everything works fine.

**Comment by cdcseacave** [comment]
thx, should be fixed now
