### ISSUE TITLE
Editing PLY or MVS File before mesh reconstruction

### ISSUE THREAD

**Issue by john-mathew** [cdcseacave/openMVS#396]
Hi,
Thank you so much for this repository.
I'm in need of some assistance.
What I'm trying to do is reconstructing 3d models from surrounding photos using openMVG and create a mesh using openMVS. But after the final point cloud is generated from densification, there is some unwanted noise in the ply which I need to remove. When I try to reconstruct mesh with ply file, it says "invalid object". I tried it with the noisy mvs and the reconstruction is carried out and a distorted mesh is formed. Is there any way where I can manually remove the unwanted noise from the MVS or PLY file at any point in the workflow so that a clean mesh can be created?
Thanks a lot.

**Comment by cdcseacave** [comment]
no need to remove the noise, the mesh reconstruction automatically removes it
you might have a different problem, like you didn't take enough photos to cover well each part of the scene (every point on the surface you want to reconstruct should be visible in at least 5 images), or the resolution is not high enough, or maybe all above is fine, but it is an open scene with far away objects reconstructed, and in this case you should manually crop the mesh to contain only the object of interest before mesh refinement (suing any mesh editing tool like MeshLab, and using `--mesh-file` param to load the cropped version), etc

**Comment by john-mathew** [comment]
Thank you for your response.
So I've manually removed the noise from the ply using Meshlab; how do I provide the ply as input to reconstruct? --mesh-file does not show up in the Available Options menu so I'm lost as to how to use the parameter, is there any documentation I can refer?
Thank you!

**Comment by john-mathew** [comment]
I'm working on a project that captures pictures of a human within an enclosed room from all sides. So during reconstruction the walls also get reconstructed as noise. When mesh is generated with this noise, the wall covers the actual human mesh.

Following are the generated plys as meshes:
![capture1](https://user-images.githubusercontent.com/41278915/50269419-35546c80-0454-11e9-9929-7161dfa523a2.PNG)

![capture4](https://user-images.githubusercontent.com/41278915/50270214-da704480-0456-11e9-9005-5fe141af6c1e.PNG)

I just need a way to remove the noise outside a fixed radius at any point in the workflow. 
Thanks in advance!

**Comment by cdcseacave** [comment]
you can process the mesh in any way you want before running the next module and then use it with the commadn line `--mesh-file <new-mesh-file>`

**Comment by aashutosh1997** [comment]
Is this possible after DensifyPointCloud @cdcseacave ? 

I want to remove the base of the model using Plane Detection and Outlier Removal, so is there a way to edit the dense scene and pass that edited scene to ReconstructMesh?

**Comment by cdcseacave** [comment]
no, there is not, though it would be easy to add; there are to ways to implement this:
- pass a (oriented) bounding box to DensifyPointCloud to crop the point cloud before saving it to disk
- add functionality to the Viewer app to crop&save the opened point cloud

**Comment by edin45** [comment]
When I execute: `DensifyPointCloud scene.mvs --mesh-file scene_pointcloud_cropped.ply`
I get the error: error: invalid mesh file

I edited & exported the scene_pointcloud_cropped.ply with meshlab, What did I do wrong?

Thank you

**Comment by cdcseacave** [comment]
it does not work like that, the point cloud has also views assigned to each point, which are not stored in the PLY file.
however you can include in the MVS scene file the Region Of Interest, and the point cloud will be automatically cropped at the end of the densification step

**Comment by edin45** [comment]
Thanks for the answer,
Do I understand correctly, that the region of interest has to be written into the scene.mvs file by the application that reconstructed the sparse point cloud?

**Comment by cdcseacave** [comment]
yes, that is one solution, or you can also do it after that, just initialize the OBB structure with your data

**Comment by yukinoljx** [comment]
> yes, that is one solution, or you can also do it after that, just initialize the OBB structure with your data

[roi.txt](https://github.com/cdcseacave/openMVS/files/15141328/roi.txt)
I used such a ROI file to pass to OBB, but it seems that I couldn't get the desired result (using Sceaux Castle data). Is it due to using the wrong format or incorrect data?

**Comment by yukinoljx** [comment]
> yes, that is one solution, or you can also do it after that, just initialize the OBB structure with your data

[roi.txt](https://github.com/cdcseacave/openMVS/files/15141373/roi.txt)
I used such a ROI file to pass to OBB, but it seems that I couldn't get the desired result (used the Sceaux Castle images and OpenMVG pipeline). Is it due to using the wrong format or incorrect data?
