### ISSUE TITLE
DensifyPointCloud doesn't generate valid scene_dense.mvs

### ISSUE THREAD

**Issue by yutoichinohe** [cdcseacave/openMVS#397]
Hello,

I'm trying to reconstruct the surface of a toy alligator. The command 'DensifyPointCloud scene.mvs' doesn't generate valid scene_dense.mvs file with the output pasted below.

22:32:34 [App     ] Build date: Dec  7 2018, 13:12:06
22:32:34 [App     ] CPU: Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz
22:32:34 [App     ] RAM: 31.30GB Physical Memory 975.50MB Virtual Memory
22:32:34 [App     ] OS: Linux 4.15.0-29-generic (x86_64)
22:32:34 [App     ] SSE & AVX compatible CPU & OS detected
22:32:34 [App     ] Command line: /home/ichinohe/scratch/structure-from-motion/ana/wani/out/reconstruction_sequential//scene.mvs
22:32:35 [App     ] MapSMtoCores for SM 6.1 is undefined; default to use 128 cores/SM
22:32:35 [App     ] MapSMtoCores for SM 6.1 is undefined; default to use 128 cores/SM
22:32:35 [App     ] CUDA device 0 initialized: GeForce GTX 1080 Ti (compute capability 6.1; memory 10.92GB)
22:32:35 [App     ] Camera model loaded: platform 0; camera  0; f 0.662x0.662; poses 12
22:32:35 [App     ] Image loaded   0: DSCN0089.JPG
22:32:35 [App     ] Image loaded   1: DSCN0090.JPG
22:32:35 [App     ] Image loaded   2: DSCN0091.JPG
22:32:35 [App     ] Image loaded   3: DSCN0092.JPG
22:32:35 [App     ] Image loaded   4: DSCN0093.JPG
22:32:35 [App     ] Image loaded   5: DSCN0094.JPG
22:32:35 [App     ] Image loaded   6: DSCN0095.JPG
22:32:35 [App     ] Image loaded   7: DSCN0096.JPG
22:32:35 [App     ] Image loaded   8: DSCN0097.JPG
22:32:35 [App     ] Image loaded   9: DSCN0098.JPG
22:32:35 [App     ] Image loaded  10: DSCN0099.JPG
22:32:35 [App     ] Image loaded  11: DSCN0100.JPG
22:32:35 [App     ] Scene loaded from interface format (441ms):
        12 images (12 calibrated) with a total of 182.25 MPixels (15.19 MPixels/image)
        832 points, 0 vertices, 0 faces
22:32:36 [App     ] Preparing images for dense reconstruction completed: 12 images (343ms)
22:32:36 [App     ] error: reference image   7 has no good images in view
22:32:36 [App     ] error: reference image   1 has no good images in view
22:32:36 [App     ] error: reference image   5 has no good images in view
22:32:36 [App     ] error: reference image   5 has no good images in view
22:32:36 [App     ] error: reference image   5 has no good images in view
22:32:36 [App     ] error: reference image   5 has no good images in view
22:32:36 [App     ] error: reference image   5 has no good images in view
22:32:36 [App     ] error: reference image   5 has no good images in view
22:32:36 [App     ] error: reference image   9 has no good images in view
22:32:36 [App     ] error: reference image   9 has no good images in view
22:32:36 [App     ] error: reference image   0 has no good images in view
22:32:36 [App     ] error: reference image   0 has no good images in view
22:32:36 [App     ] Selecting images for dense reconstruction completed: 0 images (242ms)
22:32:36 [App     ] Depth-maps fused and filtered: 0 depth-maps, 0 depths, 0 points (-2147483648%%) (0ms)
22:32:36 [App     ] Densifying point-cloud completed: 0 points (700ms)
22:32:36 [App     ] Scene saved (0ms):
        12 images (12 calibrated)
        0 points, 0 vertices, 0 faces
22:32:36 [App     ] MEMORYINFO: {
22:32:36 [App     ]     VmPeak: 23831132 kB
22:32:36 [App     ]     VmSize: 23552244 kB
22:32:36 [App     ] } ENDINFO

I use ubuntu 16.04.10 and here are the files to reproduce the problem.
https://drive.google.com/open?id=1KQKfvcof7HSbBaWFtx8MJMkbfzvBr6-I
I used the openMVG pipeline to make the 'sfm_data.bin' file and used the openMVG_main_openMVG2openMVS command to convert it to 'scene.mvs'.

I did the exactly same procedure to produce scene_dense.mvs using the sample castle images provided in the openMVG tutorial but it generated the correct scene_dense.mvs. In that case the error message 'error: reference image **  has no good images in view' didn't appear.

I would appreciate any feedback. Thank you very much.

**Comment by abhaykagalkar** [comment]
Is the scene as you expect (points and cameras in the right place, cameras oriented towards the points, etc)? and also I think the images are **to be in order to visualize it**. Here is an example MVS file that works [Example.zip](https://github.com/cdcseacave/openMVS/files/2108288/Example.zip)

**Comment by yutoichinohe** [comment]
Thank you for the response.
I tried your example and it worked as the sample dataset contained in openMVG did.

I think the scene is OK (I noticed that the points are not colored but I think it's a different problem).
<img width="1552" alt="img1" src="https://user-images.githubusercontent.com/1172496/50066663-7c4a2400-0200-11e9-9763-892c96a7090e.png">
<img width="1552" alt="img2" src="https://user-images.githubusercontent.com/1172496/50066664-7ce2ba80-0200-11e9-92a0-b5865c6606d4.png">

Does 'in order' mean I need to change the filenames? In that case, do I need to 
run the openMVG pipeline again using the newly named same files? or are there an command option or something to make the images 'in order'?

**Comment by cdcseacave** [comment]
in your case the problem is openMVG is finding very few points; in a normal scene from 12 photos at 16MPix you should get ~10000 points; you need better photos (the subject should be visible in at least 80% of each image, in you case it is like a dot in each image, and should be of good quality, not blurred, good lighting, etc)

**Comment by stq054188** [comment]
> 谢谢你的意见！我将使用条件更好的照片进行尝试。



> Thank you for the comment! I'll try it with photos of better conditions.

Maybe you can change mvs file name from scene.mvs to out.mvs and test again. The way works for me.
