### ISSUE TITLE
How to use the viewer

### ISSUE THREAD

**Issue by oleg-alexandrov** [cdcseacave/openMVS#399]
### Specifications like the version of the project, operating system, and hardware

I use the version of openMVS from GitHub on Ubuntu 16 on an Intel machine.

### Steps to reproduce the problem

The page at https://github.com/cdcseacave/openMVS/wiki/Usage does not explain how to use the viewer. The viewer is not helpful in explaining why it fails, it does so quietly (sometimes there was no file, yet it did not say so). I try with a valid file:

Viewer dense_mesh.mvs

and it exits quietly. 

It would be nice if the wiki page would add a line about the viewer, and if the viewer could have better error messages.

I also had to figure out how to create ply files. The wiki page does not explain that either and should be quick to add. 

Thank you otherwise for the nice tool.

**Comment by cdcseacave** [comment]
The viewer expects the MVS or PLY or OBJ file as input either at command line or drag and drop after you start it.

**Comment by oleg-alexandrov** [comment]
Thank you very much for the clarification. The issue here is more about documenting your very nice tool chain. I expanded your wiki page at  https://github.com/cdcseacave/openMVS/wiki/Usage explaining all this.
