### ISSUE TITLE
cmake does not work

### ISSUE THREAD

**Issue by francoflamigni** [cdcseacave/openMVS#40]
I am trying to build openmvs from sources.
I create a root directory: openMVS-master in which I copied all the files of the openMVS-master zip in their original folder. In this folder I copied Eigen, ceres, cgal vcg opencv, finally I run cmake, adding manually the path to eigen, opencv etc. but for ceres I get the followin message     CMake Error at build/Modules/FindCERES.cmake:31 (include):
  include could not find load file:

    D:\temp\openmvs\openMVS-master\ceres-solver-1.11.0/CeresConfig.cmake

**Comment by cdcseacave** [comment]
great

**Comment by jagadish482** [comment]
i compile some libraries finally i got below error please help me solve this
i run this 
>cmake D:\jagadish_gitHub\openMVS\src -DCMAKE_BUILD_TYPE=RELEASE -DEIGEN_DIR="D:\jagadish_gitHub\openMVS\eigen-eigen-b9cd8366d4e8" -DOPENCV_DIR="D:\jagadish_gitHub\openMVS\OpenCV" -DCERES_DIR="D:\jagadish_gitHub\openMVS\ceres-solver" -DCGAL_DIR="D:\jagadish_gitHub\openMVS\CGAL-4.9" -DVCG_DIR="D:\jagadish_gitHub\openMVS\vcglib" -DBOOST_INCLUDEDIR="D:\jagadish_gitHub\openMVS\boost_1_62_0"  -DOpenCV_CAN_BREAK_BINARY_COMPATIBILITY=OFF

then it's showing below output error message

![capture](https://cloud.githubusercontent.com/assets/23214629/20347906/2c5fd126-ac29-11e6-85ac-9687e9716932.PNG)

please help me to solve this
