### ISSUE TITLE
COLMAP interface / error: failed loading image header

### ISSUE THREAD

**Issue by fishcu** [cdcseacave/openMVS#402]
### Specifications like the version of the project, operating system, and hardware
Ubuntu 16.04, CUDA 10.0, OpenCV 4.0.0-rc built from source.

OpenMVS is latest from master branch.

Both OpenCV and OpenMVS have been built with identical libjpeg libraries:
`/usr/lib/x86_64-linux-gnu/libjpeg.so (ver 80)`

### Steps to reproduce the problem
1. I converted a COLMAP scene using InterfaceColmap (following #360), which went fine (`Exported data: 41 images & 44140 vertices (463ms)`).
2. I tried viewing the generated scene, which went fine:
```
10:21:55 [App     ] Camera model loaded: platform 0; camera  0; f 1.079x1.079; poses 41
10:21:55 [App     ] Image loaded   0: DSC_9325.JPG
10:21:55 [App     ] Image loaded   1: DSC_9324.JPG
...
10:21:55 [App     ] Image loaded  39: DSC_9365.JPG
10:21:55 [App     ] Image loaded  40: DSC_9360.JPG
10:21:55 [App     ] Scene loaded from interface format (35ms):
	41 images (41 calibrated) with a total of 941.31 MPixels (22.96 MPixels/image)
	44140 points, 0 vertices, 0 faces
```
3. I tried to do MVS on the scene with DensifyPointCloud. This failed:
```
./DensifyPointCloud /home/isaac/Downloads/buddha_recon_2/scene.mvs 
10:22:43 [App     ] Build date: Jan 18 2019, 21:30:28
10:22:43 [App     ] CPU: Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
10:22:43 [App     ] RAM: 31.33GB Physical Memory 977.00MB Virtual Memory
10:22:43 [App     ] OS: Linux 4.15.0-43-generic (x86_64)
10:22:43 [App     ] SSE & AVX compatible CPU & OS detected
10:22:43 [App     ] Command line: /home/isaac/Downloads/buddha_recon_2/scene.mvs
10:22:43 [App     ] MapSMtoCores for SM 6.1 is undefined; default to use 128 cores/SM
10:22:43 [App     ] CUDA device 0 initialized: TITAN Xp (compute capability 6.1; memory 11.91GB)
10:22:43 [App     ] Camera model loaded: platform 0; camera  0; f 1.079x1.079; poses 41
10:22:43 [App     ] error: failed loading image header
10:22:43 [App     ] error: failed reloading image '/home/isaac/dev/openMVS/openMVS_build/bin/dense/0/images/DSC_9325.JPG'
10:22:43 [App     ] error: invalid project
```

**Any ideas how to solve this?**

Possibly related:
#258, but I have confirmed the libjpeg library version is consistent.
#158, I will investigate this next. But the issue is old, and I checked the source -- the recommended search/replace does not exist anymore. So I assume the issue has really been fixed.

**Comment by fishcu** [comment]
What puzzles me the most is that `Viewer` can load the images, but `DensifyPointCloud` cannot.

**Comment by fishcu** [comment]
Fixed, I realized you need to run `DensifyPointCloud` from INSIDE the folder where you saved the `scene.mvs`, as the interfacing program will convert paths to relative ones.

**Comment by xuelinchao** [comment]
test

**Comment by xqyd** [comment]
Simply remove the following lines from the CMakeLists.txt of OpenMVG
if (DEFINED OpenMVG_USE_INTERNAL_JPEG)
  message(STATUS "LIBJPEG (internal)")
else()
  message(STATUS "LIBJPEG (external)")
endif()

This will make the cmake bypass the libjpeg and the jpeg stuff can be processed by OpenMVS like this:

CEREAL: (internal)
EIGEN: 3.3.4 (internal)
CERES: 1.13.0 (internal)
FLANN: 1.8.4 (internal)
LIBTIFF: 4.1.0 (external)
LIBPNG: 1.6.37 (external)
CLP: 1.16.10 (internal)
COINUTILS: 2.10.13 (internal)
OSI:  (internal)
LEMON: 1.3 (internal)

Notice the "LIBJPEG (external)" is GONE!
With this approach, I can finally use OpenMVG+OpenMVS without any problem.

**Comment by citystrawman** [comment]
> Fixed, I realized you need to run `DensifyPointCloud` from INSIDE the folder where you saved the `scene.mvs`, as the interfacing program will convert paths to relative ones.

Hi, I encountered the same error when using DensifyPointCloud. I followed your way (run DensifyPointCloud inside the mvs folder), and the program ran without errors, however, there's no output or other info, the program seems to run nothing. Here's the screenshot:  
![image](https://github.com/cdcseacave/openMVS/assets/9004748/13a68f18-d36c-4df4-949c-8abc3787b88e)
Do you know how to solve this ?  Thank you!

**Comment by xuelinchao** [comment]
这是来自QQ邮箱的假期自动回复邮件。您的邮件已收到，谢谢。   ----薛林超
