### ISSUE TITLE
Segfault with refinemesh

### ISSUE THREAD

**Issue by xiaoxiongkubi** [cdcseacave/openMVS#407]
Thanks for you work.These is some trouble with me.
 Ubuntu16.04,Cuda 10,cudnn 7,eigen 3.2
The module in MVS_build/bin work well except refinemesh.
when i run   "~/mvs/openMVS_build/bin/RefineMesh ./scene_dense_mesh.mvs"  there is segfault.
When i run  "~/mvs/openMVS_build/bin/RefineMesh ./scene_dense_mesh.mvs --use-cuda 0",that is ok.
But i cannot use gpu.I haev already re-installed ubuntu16.04 several times.I really donnot know what to do.
Could you pls help me?
Thanks !

**Comment by cdcseacave** [comment]
most probably the GPU card runs out of memeory

**Comment by xiaoxiongkubi** [comment]
![2019-01-30 09-53-25](https://user-images.githubusercontent.com/35690284/51956311-2664cf00-2482-11e9-994c-2d535b0c0582.png)
Thanks for your reply and advice,I  monitor the gpu memory just find RefuineMesh take little memory.I also test little images for input,but still cannot get the scene_dense_mesh_refine.mvs.
Thanks.

**Comment by fxia22** [comment]
use `--use-cuda false`

**Comment by chris-aeviator** [comment]
same here :( any ideas? Installed via arch linux aur

```
❯ ReconstructMesh shampoo_dense.mvs         
17:17:35 [App     ] Build date: Mar  9 2019, 15:07:14
17:17:35 [App     ] CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
17:17:35 [App     ] RAM: 15.38GB Physical Memory 15.37GB Virtual Memory
17:17:35 [App     ] OS: Linux 4.20.10-arch1-1-ARCH (x86_64)
17:17:35 [App     ] SSE & AVX compatible CPU & OS detected
17:17:35 [App     ] Command line: shampoo_dense.mvs
17:17:35 [App     ] MapSMtoCores for SM 6.1 is undefined; default to use 128 cores/SM
17:17:35 [App     ] CUDA device 0 initialized: GeForce GTX 1070 (compute capability 6.1; memory 7.93GB)
17:17:39 [App     ] Scene loaded (3s795ms):
	25 images (25 calibrated) with a total of 95.91 MPixels (3.84 MPixels/image)
	5377851 points, 0 vertices, 0 faces
Points inserted 5377851 (100%, 25s979ms)           
[1]    16620 segmentation fault (core dumped)  ReconstructMesh shampoo_dense.mvs

```

**Comment by xiaoxiongkubi** [comment]
Sorry for late reply. I still cannot solve the problem. My trouble is in RefineMesh, yours is in ReconstructMesh. I think it's different because my ReconstructionMesh is okay, you can reinstall the eigen==3.2 again.

**Comment by superwang11** [comment]
@xiaoxiongkubi 
Hello，do you have solve this problem? I also encountered the same problem. Refinemesh can not use gpu.
![image](https://user-images.githubusercontent.com/49363342/55682231-3fe33500-5963-11e9-94eb-583f52b6bb29.png)

**Comment by xiaoxiongkubi** [comment]
Sorry I did not solve the problem,I just compiled it in CPU.So I did not use MVS with GPU.

**Comment by cdcseacave** [comment]
I also encourage to disable CUDA and use CPU only.

**Comment by 478161648** [comment]
I am a freshman,can you tell me how to disable CUDA? Thank you.

**Comment by 478161648** [comment]
I set the bUseCUDA=false...
and it works.
