### ISSUE TITLE
Reconstruct complete mesh without hole at the bottom

### ISSUE THREAD

**Issue by john-mathew** [cdcseacave/openMVS#408]
I'd like some guidance about how to go about reconstructing mesh. I'm trying to create a mesh from photos of an object on a flat surface, and hence understandably, the object has a hollow bottom. How can I ensure the reconstruction is fully solid? Is it possible to reconstruct two sets of photos of the object from different angles and somehow merge them together? Thanks in advance!

**Comment by cdcseacave** [comment]
the photos can be acquired in multiple sessions, but processed together as a whole, with the condition that there is nothing in the photos that witness the scene change. In other words it is ok to move the object (if the object is solid, it is as you would keep it in place and only move the camera around), but there should no be any background that disagrees with what is seen from the previous photos. If in a studio, make sure the table and background is of the same color.
