### ISSUE TITLE
Is there any limitaions on input 3d structre which can be textured properly?

### ISSUE THREAD

**Issue by sathishkumark27** [cdcseacave/openMVS#409]
Hi all,
I am using openMVG and opemMVS to 3D texture on Ubuntu16.04. I have given some complex outdoor scene(images attached with this issue) for reconstruction and texturing using complete pipeline python script "MvgMvs_Pipeline.py" but could not able to get the dens point-cloud and texture correctly. Are there any limitations on the input scene for correct texturing and reconstruction?

### Steps to reproduce the problem
Running the pipeline with below images will not reconstruct and texture correctly. I have used around 1200 images of the below scene but could not able t get the correct reconstruction

![frame0](https://user-images.githubusercontent.com/31283567/52294289-28250b80-2936-11e9-990f-744f856b0021.JPG)
![frame1](https://user-images.githubusercontent.com/31283567/52294290-28250b80-2936-11e9-93af-e6971b04c29b.JPG)
![frame2](https://user-images.githubusercontent.com/31283567/52294292-28250b80-2936-11e9-8308-121a82b31187.JPG).

Any help greatly appreciated.

**Comment by cdcseacave** [comment]
the only limitation is set by the amount of memory you have on your system, for 1200 images you probably need 128GB RAM

**Comment by sathishkumark27** [comment]
I have ran the pipeline overnight with 16GB of RAM, 8 cores. Can you please
tell why the memory matters? Even if we have less memory it should
construct property but takes lot of time right?

**Comment by cdcseacave** [comment]
Wrong, some steps require looking at all images, triangles, etc at the same time, so they need to fit in memory all at once. Try increasing the memory size, or split the scene in smaller subscenes and process them individually. OpenMVG supports that.
