### ISSUE TITLE
DensifyPointCloud : operation not permitted

### ISSUE THREAD

**Issue by lulu1315** [cdcseacave/openMVS#41]
hello
I'm having trouble running DensifyPointCloud and ReconstructMesh on one of my machines.it's an older machine than the other one which is running fine.
compilation is ok but when running I got this message : 
19:51:05 [App     ] Build date: Jan 10 2016, 19:42:19
19:51:05 [App     ] CPU: Intel(R) Xeon(R) CPU           X5355  @ 2.66GHz
19:51:05 [App     ] RAM: 15.67GB Physical Memory 22.35GB Virtual Memory
19:51:05 [App     ] OS: Linux 3.16.0-57-generic (x86_64)
19:51:05 [App     ] warning: no AVX compatible CPU or OS detected
19:51:06 [App     ] Command line: scene.mvs
19:51:06 [App     ] Preparing images for dense reconstruction completed: 9 images (666ms)
Instruction non permise (core dumped)
(operation not permitted)
i'm running linux Kubuntu 14.04
could it be a hardware problem ?
thanks in advance
luc

this is the output of cmake : 
cmake . ../openMVS -DCMAKE_BUILD_TYPE=RELEASE -DVCG_DIR="$main_path/vcglib" -DCERES_DIR="/usr/local/share/Ceres" -DOpenCV_CAN_BREAK_BINARY_COMPATIBILITY=OFF -DOpenMVG_DIR:STRING="$main_path/openMVG-build/openMVG_install/share/openMVG/cmake/"
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detected version of GNU GCC: 48 (408)
-- Performing Test COMPILER_HAS_CXX11_FLAG
-- Performing Test COMPILER_HAS_CXX11_FLAG - Success
-- Performing Test HAVE_CXX_STD_C++11
-- Performing Test HAVE_CXX_STD_C++11 - Success
-- Performing Test HAVE_C_STD_C++11
-- Performing Test HAVE_C_STD_C++11 - Failed
-- Performing Test HAVE_CXX_W
-- Performing Test HAVE_CXX_W - Success
-- Performing Test HAVE_C_W
-- Performing Test HAVE_C_W - Success
-- Performing Test HAVE_CXX_WALL
-- Performing Test HAVE_CXX_WALL - Success
-- Performing Test HAVE_C_WALL
-- Performing Test HAVE_C_WALL - Success
-- Performing Test HAVE_CXX_WERROR_ADDRESS
-- Performing Test HAVE_CXX_WERROR_ADDRESS - Success
-- Performing Test HAVE_C_WERROR_ADDRESS
-- Performing Test HAVE_C_WERROR_ADDRESS - Success
-- Performing Test HAVE_CXX_WERROR_SEQUENCE_POINT
-- Performing Test HAVE_CXX_WERROR_SEQUENCE_POINT - Success
-- Performing Test HAVE_C_WERROR_SEQUENCE_POINT
-- Performing Test HAVE_C_WERROR_SEQUENCE_POINT - Success
-- Performing Test HAVE_CXX_WFORMAT
-- Performing Test HAVE_CXX_WFORMAT - Success
-- Performing Test HAVE_C_WFORMAT
-- Performing Test HAVE_C_WFORMAT - Success
-- Performing Test HAVE_CXX_WERROR_FORMAT_SECURITY
-- Performing Test HAVE_CXX_WERROR_FORMAT_SECURITY - Success
-- Performing Test HAVE_C_WERROR_FORMAT_SECURITY
-- Performing Test HAVE_C_WERROR_FORMAT_SECURITY - Success
-- Performing Test HAVE_CXX_WSTRICT_PROTOTYPES
-- Performing Test HAVE_CXX_WSTRICT_PROTOTYPES - Failed
-- Performing Test HAVE_C_WSTRICT_PROTOTYPES
-- Performing Test HAVE_C_WSTRICT_PROTOTYPES - Success
-- Performing Test HAVE_CXX_WINIT_SELF
-- Performing Test HAVE_CXX_WINIT_SELF - Success
-- Performing Test HAVE_C_WINIT_SELF
-- Performing Test HAVE_C_WINIT_SELF - Success
-- Performing Test HAVE_CXX_WSIGN_PROMO
-- Performing Test HAVE_CXX_WSIGN_PROMO - Success
-- Performing Test HAVE_C_WSIGN_PROMO
-- Performing Test HAVE_C_WSIGN_PROMO - Failed
-- Performing Test HAVE_CXX_WNO_UNDEF
-- Performing Test HAVE_CXX_WNO_UNDEF - Success
-- Performing Test HAVE_C_WNO_UNDEF
-- Performing Test HAVE_C_WNO_UNDEF - Success
-- Performing Test HAVE_CXX_WNO_COMMENT
-- Performing Test HAVE_CXX_WNO_COMMENT - Success
-- Performing Test HAVE_C_WNO_COMMENT
-- Performing Test HAVE_C_WNO_COMMENT - Success
-- Performing Test HAVE_CXX_WNO_NARROWING
-- Performing Test HAVE_CXX_WNO_NARROWING - Success
-- Performing Test HAVE_C_WNO_NARROWING
-- Performing Test HAVE_C_WNO_NARROWING - Success
-- Performing Test HAVE_CXX_WNO_ATTRIBUTES
-- Performing Test HAVE_CXX_WNO_ATTRIBUTES - Success
-- Performing Test HAVE_C_WNO_ATTRIBUTES
-- Performing Test HAVE_C_WNO_ATTRIBUTES - Success
-- Performing Test HAVE_CXX_WNO_ENUM_COMPARE
-- Performing Test HAVE_CXX_WNO_ENUM_COMPARE - Success
-- Performing Test HAVE_C_WNO_ENUM_COMPARE
-- Performing Test HAVE_C_WNO_ENUM_COMPARE - Success
-- Performing Test HAVE_CXX_WNO_MISSING_DECLARATIONS
-- Performing Test HAVE_CXX_WNO_MISSING_DECLARATIONS - Success
-- Performing Test HAVE_C_WNO_MISSING_DECLARATIONS
-- Performing Test HAVE_C_WNO_MISSING_DECLARATIONS - Success
-- Performing Test HAVE_CXX_WNO_MISSING_PROTOTYPES
-- Performing Test HAVE_CXX_WNO_MISSING_PROTOTYPES - Failed
-- Performing Test HAVE_C_WNO_MISSING_PROTOTYPES
-- Performing Test HAVE_C_WNO_MISSING_PROTOTYPES - Success
-- Performing Test HAVE_CXX_WNO_MISSING_FIELD_INITIALIZERS
-- Performing Test HAVE_CXX_WNO_MISSING_FIELD_INITIALIZERS - Success
-- Performing Test HAVE_C_WNO_MISSING_FIELD_INITIALIZERS
-- Performing Test HAVE_C_WNO_MISSING_FIELD_INITIALIZERS - Success
-- Performing Test HAVE_CXX_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HAVE_CXX_WNO_UNUSED_LOCAL_TYPEDEFS - Success
-- Performing Test HAVE_C_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HAVE_C_WNO_UNUSED_LOCAL_TYPEDEFS - Success
-- Performing Test HAVE_CXX_WNO_DELETE_NON_VIRTUAL_DTOR
-- Performing Test HAVE_CXX_WNO_DELETE_NON_VIRTUAL_DTOR - Success
-- Performing Test HAVE_C_WNO_DELETE_NON_VIRTUAL_DTOR
-- Performing Test HAVE_C_WNO_DELETE_NON_VIRTUAL_DTOR - Failed
-- Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Performing Test HAVE_CXX_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HAVE_CXX_FDIAGNOSTICS_SHOW_OPTION - Success
-- Performing Test HAVE_C_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HAVE_C_FDIAGNOSTICS_SHOW_OPTION - Success
-- Performing Test HAVE_CXX_FTEMPLATE_BACKTRACE_LIMIT_0
-- Performing Test HAVE_CXX_FTEMPLATE_BACKTRACE_LIMIT_0 - Success
-- Performing Test HAVE_C_FTEMPLATE_BACKTRACE_LIMIT_0
-- Performing Test HAVE_C_FTEMPLATE_BACKTRACE_LIMIT_0 - Failed
-- Performing Test HAVE_CXX_WNO_LONG_LONG
-- Performing Test HAVE_CXX_WNO_LONG_LONG - Success
-- Performing Test HAVE_C_WNO_LONG_LONG
-- Performing Test HAVE_C_WNO_LONG_LONG - Success
-- Performing Test HAVE_CXX_PTHREAD
-- Performing Test HAVE_CXX_PTHREAD - Success
-- Performing Test HAVE_C_PTHREAD
-- Performing Test HAVE_C_PTHREAD - Success
-- Performing Test HAVE_CXX_FOMIT_FRAME_POINTER
-- Performing Test HAVE_CXX_FOMIT_FRAME_POINTER - Success
-- Performing Test HAVE_C_FOMIT_FRAME_POINTER
-- Performing Test HAVE_C_FOMIT_FRAME_POINTER - Success
-- Performing Test HAVE_CXX_FROUNDING_MATH
-- Performing Test HAVE_CXX_FROUNDING_MATH - Success
-- Performing Test HAVE_C_FROUNDING_MATH
-- Performing Test HAVE_C_FROUNDING_MATH - Success
-- Performing Test HAVE_CXX_MSSE
-- Performing Test HAVE_CXX_MSSE - Success
-- Performing Test HAVE_C_MSSE
-- Performing Test HAVE_C_MSSE - Success
-- Performing Test HAVE_CXX_MSSE2
-- Performing Test HAVE_CXX_MSSE2 - Success
-- Performing Test HAVE_C_MSSE2
-- Performing Test HAVE_C_MSSE2 - Success
-- Performing Test HAVE_CXX_MSSE3
-- Performing Test HAVE_CXX_MSSE3 - Success
-- Performing Test HAVE_C_MSSE3
-- Performing Test HAVE_C_MSSE3 - Success
-- Performing Test HAVE_CXX_MSSSE3
-- Performing Test HAVE_CXX_MSSSE3 - Success
-- Performing Test HAVE_C_MSSSE3
-- Performing Test HAVE_C_MSSSE3 - Success
-- Performing Test HAVE_CXX_MSSE4_1
-- Performing Test HAVE_CXX_MSSE4_1 - Success
-- Performing Test HAVE_C_MSSE4_1
-- Performing Test HAVE_C_MSSE4_1 - Success
-- Performing Test HAVE_CXX_MSSE4_2
-- Performing Test HAVE_CXX_MSSE4_2 - Success
-- Performing Test HAVE_C_MSSE4_2
-- Performing Test HAVE_C_MSSE4_2 - Success
-- Performing Test HAVE_CXX_FFUNCTION_SECTIONS
-- Performing Test HAVE_CXX_FFUNCTION_SECTIONS - Success
-- Performing Test HAVE_C_FFUNCTION_SECTIONS
-- Performing Test HAVE_C_FFUNCTION_SECTIONS - Success
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Can't find CUDA. Continuing without it.
-- WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   iostreams
--   program_options
--   system
--   serialization
-- Eigen 3.2.0 found (include: /usr/include/eigen3)
-- OpenCV 2.4.8 found (include: /usr/include/opencv;/usr/include;/usr/share/OpenCV/include)
-- CGAL found (include: /usr/include)
-- VCG  found (include: /mnt/shared/v14/vcglib)
-- Found required Ceres dependency: Eigen version 3.2.0 in /usr/include/eigen3
-- Found required Ceres dependency: Glog in /usr/include
-- Found Ceres version: 1.12.0 installed in: /usr/local
-- CERES 1.12.0 found (include: /usr/local/include;/usr/include/eigen3;/usr/include;/usr/local/include)
-- ----
-- OpenMVG Find_Package
-- ----
-- Found OpenMVG version: 0.8.1
-- Installed in: /mnt/shared/v14/openMVG-build/openMVG_install
-- Used OpenMVG libraries: openMVG_image;openMVG_features;openMVG_matching_image_collection;openMVG_kvld;openMVG_multiview;openMVG_lInftyComputerVision;openMVG_system;openMVG_sfm
-- ----
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/shared/v14/tmp

**Comment by cdcseacave** [comment]
I never saw this error before. I am not an expert programmer, but to me it seems indeed like some kind of SSE instruction could not be run. Though the CMake seem to have found all possible SSE except AVX. But as far as I know no AVX instructions are used, at least not by me, maybe by the third party libs. Sorry I can not help more, maybe somebody with more experience can give us a hint.

**Comment by lulu1315** [comment]
ok I nailed it.
I disabled all the SSExx flags in the CMakeCache.txt files and let only SSE and it's working now.
thanks.

//Enable SSE instructions
ENABLE_SSE:BOOL=ON
//Enable SSE2 instructions
ENABLE_SSE2:BOOL=OFF
//Enable SSE3 instructions
ENABLE_SSE3:BOOL=OFF
//Enable SSE4.1 instructions
ENABLE_SSE41:BOOL=OFF
//Enable SSE4.2 instructions
ENABLE_SSE42:BOOL=OFF
//Enable SSSE3 instructions
ENABLE_SSSE3:BOOL=OFF
