### ISSUE TITLE
RefineMesh and Cuda

### ISSUE THREAD

**Issue by 2d3** [cdcseacave/openMVS#410]
Hi all! While doing RefineMesh, in my case, the error log states `Mesh subdivided: 20780/41480 -> 80530/160927 vertices/faces
14:43:41 [App     ] CUDA error: kernelComputeImageMean(size, mask, imageMean, size.width, size.height, HalfSize ) (CUDA_ERROR_ILLEGAL_ADDRESS (code 700) - an illegal memory access was encountered)
14:43:41 [App     ] CUDA error: kernelComputeImageVar(size, imageMean, mask, imageVar, size.width, size.height, HalfSize ) (CUDA_ERROR_ILLEGAL_ADDRESS (code 700) - an illegal memory access was encountered)
14:43:41 [App     ] CUDA error: kernelComputeImageMean(size, mask, imageMean, size.width, size.height, HalfSize ) (CUDA_ERROR_ILLEGAL_ADDRESS (code 700) - an illegal memory access was encountered)
14:43:41 [App     ] CUDA error: kernelComputeImageVar(size, imageMean, mask, imageVar, size.width, size.height, HalfSize ) (CUDA_ERROR_ILLEGAL_ADDRESS (code 700) - an illegal memory access was encountered)
14:43:41 [App     ] CUDA error: kernelComputeImageCov(size, imageMeanA, imageMeanAB, mask, imageCov, size.width, size.height, HalfSize ) (CUDA_ERROR_ILLEGAL_ADDRESS (code 700) - an illegal memory access was encountered)
14:43:41 [App     ] CUDA error: kernelComputeImageZNCC(size, imageCov, imageVarA, imageVarAB, mask, imageZNCC, size.width, size.height, HalfSize ) (CUDA_ERROR_ILLEGAL_ADDRESS (code 700) - an illegal memory access was encountered)
14:43:41 [App     ] CUDA error: kernelComputeImageDZNCC(size, imageMeanA, imageMeanAB, imageVarA, imageVarAB, imageZNCC, mask, imageDZNCC, size.width, size.height, HalfSize ) (CUDA_ERROR_ILLEGAL_ADDRESS (code 700) - an illegal memory access was encountered)
14:43:41 [App     ] CUDA error: cuMemsetD32(photoGradPixels, 0, numVertices) (CUDA_ERROR_ILLEGAL_ADDRESS (code 700) - an illegal memory access was encountered)` and so on. A textured mesh is generated but it cannot be visualized in meshlab. It doesnt show anything but states the number of vertices and faces. Any idea?

**Comment by cdcseacave** [comment]
I encourage to disable CUDA and use CPU only.
