### ISSUE TITLE
ReconstructMesh - bad_alloc

### ISSUE THREAD

**Issue by chris-aeviator** [cdcseacave/openMVS#412]
I'm running into this while my RAM get's eaten up:

```
Arch Linux
❯ /var/lib/snapd/snap/openmvs/2/command-ReconstructMesh.wrapper project_dense.mvs 
21:57:36 [App     ] Build date: Mar  9 2019, 15:07:14
21:57:36 [App     ] CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
21:57:36 [App     ] RAM: 15.38GB Physical Memory 15.37GB Virtual Memory
21:57:36 [App     ] OS: Linux 4.20.10-arch1-1-ARCH (x86_64)
21:57:36 [App     ] SSE & AVX compatible CPU & OS detected
21:57:36 [App     ] Command line: project_dense.mvs
21:57:36 [App     ] MapSMtoCores for SM 6.1 is undefined; default to use 128 cores/SM
21:57:37 [App     ] CUDA device 0 initialized: GeForce GTX 1070 (compute capability 6.1; memory 7.93GB)
21:57:45 [App     ] Scene loaded (8s793ms):
	99 images (99 calibrated) with a total of 379.82 MPixels (3.84 MPixels/image)
	14377566 points, 0 vertices, 0 faces
Points inserted 14377566 (100%, 1m14s503ms)

```

It seems for me that the same Error happens one time as `segfault` one time as `bad_alloc` depending on the system/version of the dependencies. 

When running `ReconstructMesh` on my dataset (99 pictures of a 20sqm indoor room) in my "native" arch linux installation it will trigger a `segfault`, when running inside  a ubuntu based docker image (https://github.com/berlius/openMVS) it will error with `bad_alloc` (the error happens in both environments in the same step, which is the end of ReconstructMesh)

Edit:
same happens when using AUR package instead of snap

**Comment by chris-aeviator** [comment]
I'm running into this while my RAM get's eaten up:

```
Arch Linux
❯ /var/lib/snapd/snap/openmvs/2/command-ReconstructMesh.wrapper project_dense.mvs 
21:57:36 [App     ] Build date: Mar  9 2019, 15:07:14
21:57:36 [App     ] CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
21:57:36 [App     ] RAM: 15.38GB Physical Memory 15.37GB Virtual Memory
21:57:36 [App     ] OS: Linux 4.20.10-arch1-1-ARCH (x86_64)
21:57:36 [App     ] SSE & AVX compatible CPU & OS detected
21:57:36 [App     ] Command line: project_dense.mvs
21:57:36 [App     ] MapSMtoCores for SM 6.1 is undefined; default to use 128 cores/SM
21:57:37 [App     ] CUDA device 0 initialized: GeForce GTX 1070 (compute capability 6.1; memory 7.93GB)
21:57:45 [App     ] Scene loaded (8s793ms):
	99 images (99 calibrated) with a total of 379.82 MPixels (3.84 MPixels/image)
	14377566 points, 0 vertices, 0 faces
Points inserted 14377566 (100%, 1m14s503ms)

```

It seems for me that the same Error happens one time as `segfault` on time as `bad_alloc` depending on the system/version of the dependencies. 

When running `ReconstructMesh` on my dataset (99 pictures of a 20sqm indoor room) in my "native" arch linux installation it will trigger a `segfault`, when running inside  a ubuntu based docker image (https://github.com/berlius/openMVS) it will error with `bad_alloc` (as it seems)

**Comment by cdcseacave** [comment]
if u run out of RAM, these kind of errors are not a surprise; pls free more RAM, buy more RAM, or process at lower resolution, or try increasing `-d 4`

**Comment by satyajitghana** [comment]
I am getting the same issue of `bad_alloc`, it's not an issue with RAM, i took a 4TB RAM machine and it still persists. increased the swap to additional 4TB, still same thing, and while meshing it doesn't even take up all the ram (increased insert distance).

i don't exactly remember the stack trace but it was something to do with initSize or something in delaunay IBFS Graph
