### ISSUE TITLE
The nEstimateNormals parameter of DensifyPointCloud

### ISSUE THREAD

**Issue by KeoChi** [cdcseacave/openMVS#413]
Hello! In DensifyPointCloud, when I use defaulte value(0) of nEstimateNormals, the surface of dense point cloud is smooth and perfect. But I set nEstimateNormals to 1, the surface of point cloud is rough. For example:
  nEstimateNormals is 0:
  
![soomth](https://user-images.githubusercontent.com/9250491/54249985-0514f980-457d-11e9-96fd-8be0cf18e2f8.png)

  nEstimateNormals is 1:
  
![rough](https://user-images.githubusercontent.com/9250491/54250005-178f3300-457d-11e9-86a7-2d9b6180e883.png)
   
   I need dense point cloud to have normals and its surface is soomth. How should I set the parameter in DepthMap.cpp or other places? Looking forward to your reply! Thank you!

**Comment by cdcseacave** [comment]
This is only a display difference, the surface is equal in both cases. In meshlab u can disable light and it will look as without normals. But if you need normals, I suggest to use `--estimate-normals 2` not `1`:
 1 - estimates normals based on neighbor points
 2 - fuse normals estimated during densification

**Comment by KeoChi** [comment]
Thank you! I try it!
