### ISSUE TITLE
Refine Mesh 

### ISSUE THREAD

**Issue by veolata** [cdcseacave/openMVS#414]
newest version from git , get seg fault while using a script to run
may be same as #407

**Comment by veolata** [comment]
Starting program: /usr/local/bin/OpenMVS/RefineMesh ~/Desktop/openmvg_pic/wthphotos/ref/mvs/scene_dense_mesh.mvs
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdc24f700 (LWP 3997)]
00:56:50 [App     ] Build date: Mar 22 2019, 00:09:09
00:56:50 [App     ] CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
00:56:50 [App     ] RAM: 31.32GB Physical Memory 7.63GB Virtual Memory
00:56:50 [App     ] OS: Linux 4.15.0-46-generic (x86_64)
00:56:50 [App     ] SSE & AVX compatible CPU & OS detected
00:56:50 [App     ] Command line: /home/dl/Desktop/openmvg_pic/wthphotos/ref/mvs/scene_dense_mesh.mvs
[New Thread 0x7fffd5a4e700 (LWP 4000)]
00:56:50 [App     ] MapSMtoCores for SM 6.1 is undefined; default to use 128 cores/SM
00:56:51 [App     ] MapSMtoCores for SM 6.1 is undefined; default to use 128 cores/SM
[New Thread 0x7fffd524d700 (LWP 4001)]
[New Thread 0x7fffd4a4c700 (LWP 4002)]
00:56:51 [App     ] CUDA device 0 initialized: GeForce GTX 1080 Ti (compute capability 6.1; memory 10.92GB)
00:56:51 [App     ] Scene loaded (113ms):
	18 images (5 calibrated) with a total of 34.16 MPixels (6.83 MPixels/image)
	0 points, 144715 vertices, 289287 faces
[New Thread 0x7fffd16c8700 (LWP 4003)]
[New Thread 0x7fffd0ec7700 (LWP 4004)]
[New Thread 0x7fffadfff700 (LWP 4005)]
[New Thread 0x7fffad7fe700 (LWP 4006)]
[New Thread 0x7fffacffd700 (LWP 4007)]
[New Thread 0x7fffac7fc700 (LWP 4008)]
[New Thread 0x7fffabffb700 (LWP 4009)]
[New Thread 0x7fffab7fa700 (LWP 4010)]
[New Thread 0x7fffaaff9700 (LWP 4011)]
[New Thread 0x7fffaa7f8700 (LWP 4012)]
[New Thread 0x7fffa9ff7700 (LWP 4013)]
[New Thread 0x7fffa97f6700 (LWP 4014)]
[New Thread 0x7fffa8ff5700 (LWP 4015)]
[New Thread 0x7fffa87f4700 (LWP 4016)]
[New Thread 0x7fffa7ff3700 (LWP 4017)]
[New Thread 0x7fffa77f2700 (LWP 4018)]
[New Thread 0x7fffa73f1700 (LWP 4019)]
[New Thread 0x7fffa6ff0700 (LWP 4020)]
[New Thread 0x7fffa6bef700 (LWP 4021)]
[New Thread 0x7fffa481d700 (LWP 4023)]
[New Thread 0x7fffa67ee700 (LWP 4022)]
[New Thread 0x7fffa441c700 (LWP 4024)]
[New Thread 0x7fff9fbfe700 (LWP 4026)]
[New Thread 0x7fff9f3fc700 (LWP 4028)]
[New Thread 0x7fff9f7fd700 (LWP 4027)]
[New Thread 0x7fff9ffff700 (LWP 4025)]
[New Thread 0x7fff9effb700 (LWP 4029)]
[New Thread 0x7fff9e3f8700 (LWP 4030)]
[New Thread 0x7fff9e7f9700 (LWP 4031)]
[New Thread 0x7fff9ebfa700 (LWP 4032)]
Decimated faces 260358 (100%, 1s541ms)              
00:56:53 [App     ] Cleaned mesh: 14534 vertices, 28928 faces (1s668ms)
00:56:53 [App     ] Cleaned mesh: 14534 vertices, 28928 faces (29ms)

Thread 1 "RefineMesh" received signal SIGSEGV, Segmentation fault.
0x0000000000523b4c in MeshRefineCUDA::ListFaceAreas(SEACAVE::cList<unsigned short, unsigned short, 0, 16, unsigned int>&) ()

**Comment by cdcseacave** [comment]
I encourage to disable CUDA and use CPU only.
