### ISSUE TITLE
Reconstruction from own aligned pointcloud, depthmaps and photos

### ISSUE THREAD

**Issue by UannaFF** [cdcseacave/openMVS#415]
Hello, I want to use openmvs to do the last steps of my 3d reconstruction, I already do the pose estimation and then align the point clouds. I wanted to know how I'd proceed with this kind of information to obtain a mesh.

**Comment by cdcseacave** [comment]
simply fill in the structure defined in Interface.h and proceed with RecontructMesh

**Comment by 478161648** [comment]
Hello,I have cameras poses and sparse 3D point-cloud,how can I generate the .mvs file to run the DensifyPointCloud. Can you tell me the detail of the .mvs file? Thank you.

**Comment by 478161648** [comment]
Sorry,I am too careless,I should first to read the OpenMVG.
