### ISSUE TITLE
Parameters used for ETH3D benchmark results

### ISSUE THREAD

**Issue by FlakPacket** [cdcseacave/openMVS#416]
@cdcseacave,

In your recent February submission to the ETH3D Benchmark (https://www.eth3d.net/result_details?id=98), there are a few parameters to `DensifyPointCloud` that I had questions about:

- `DensifyPointCloud --optimize 0` : what is the "optimize" flag and how does one access it?
- `DensifyPointCloud --filter-point-cloud -1` : what is the "filter-point-cloud" flag and how does one access it?
- `nSizeHalfWindow` : this was hard-coded to a value of 9, rather than the usual 3. Have you thought about adding this as a user parameter in DensifyPointCloud?
- Which set of parameters was used for the "High-res multi-view" results versus the "Low-res many-view" results?

It would be nice if openMVS users could easily reproduce your benchmark results.

**Comment by cdcseacave** [comment]
sry, I do not understand your questions
I posted the parameters used in the results submission description, just use them and you get those results

**Comment by rennu** [comment]
@FlakPacket,

--optimize and --filter-point-cloud arguments are available in the develop branch version of DensifyPointCloud.

**Comment by FlakPacket** [comment]
Thank you, @rennu, that explains why I couldn't find those arguments! I was looking in the default (master) branch and didn't see any references to them.

As a feature request, it would be nice if the `nSizeHalfWindow` window size was exposed as a command-line parameter.
