### ISSUE TITLE
Error when viewing my own cionstructed .mvs file

### ISSUE THREAD

**Issue by JimZhou-001** [cdcseacave/openMVS#417]
When I tried to view my own .mvs data, it when wrong. How can I solve it? Who can help me? Thanks.

./Viewer scene_first_mesh.mvs 
20:37:06 [App     ] Build date: Mar 22 2019, 20:34:24
20:37:06 [App     ] CPU: Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz
20:37:06 [App     ] RAM: 31.37GB Physical Memory 7.45GB Virtual Memory
20:37:06 [App     ] OS: Linux 4.4.0-34-generic (x86_64)
20:37:06 [App     ] SSE & AVX compatible CPU & OS detected
20:37:06 [App     ] Command line: scene_first_mesh.mvs
20:37:06 [App     ] CUDA device 0 initialized: Quadro M6000 (compute capability 5.2; memory 11.92GB)
20:37:06 [App     ] Loading: 'scene_first_mesh.mvs'
20:37:06 [App     ] Camera model loaded: platform 0; camera  0; f 0.898x0.900; poses 8
20:37:06 [App     ] Image loaded   0: 0000.jpg
20:37:06 [App     ] Image loaded   1: 0001.jpg
20:37:06 [App     ] Image loaded   2: 0002.jpg
20:37:06 [App     ] Image loaded   3: 0003.jpg
20:37:06 [App     ] Image loaded   4: 0004.jpg
20:37:06 [App     ] Image loaded   5: 0005.jpg
20:37:06 [App     ] Image loaded   6: 0006.jpg
20:37:06 [App     ] Image loaded   7: 0007.jpg
20:37:06 [App     ] Scene loaded from interface format (7ms):
	8 images (8 calibrated) with a total of 48.00 MPixels (6.00 MPixels/image)
	14532 points, 0 vertices, 0 faces
[1]    24289 segmentation fault  ./Viewer scene_first_mesh.mvs

**Comment by cdcseacave** [comment]
I do not see anything wrong in this log, so just build in debug and see where the problem is

**Comment by JimZhou-001** [comment]
> I do not see anything wrong in this log, so just build in debug and see where the problem is

/home/xin/.clion10/system/cmake/generated/90e00386/90e00386/Debug/apps/Viewer/Viewer /home/xin/zjx/SfM_quality_evaluation/Benchmarking_Camera_Calibration_2008/Herz-Jesus-P8/scene_first_mesh.mvs
22:42:03 [App     ] Build date: Mar 22 2019, 22:33:46
22:42:03 [App     ] CPU: Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz
22:42:03 [App     ] RAM: 31.37GB Physical Memory 7.45GB Virtual Memory
22:42:03 [App     ] OS: Linux 4.4.0-34-generic (x86_64)
22:42:03 [App     ] SSE & AVX compatible CPU & OS detected
22:42:03 [App     ] Command line: /home/xin/zjx/SfM_quality_evaluation/Benchmarking_Camera_Calibration_2008/Herz-Jesus-P8/scene_first_mesh.mvs
22:42:03 [App     ] CUDA device 0 initialized: Quadro M6000 (compute capability 5.2; memory 11.92GB)
22:42:04 [App     ] Loading: 'scene_first_mesh.mvs'
22:42:04 [App     ] Camera model loaded: platform 0; camera  0; f 0.898x0.900; poses 8
22:42:04 [App     ] Image loaded   0: 0000.jpg
22:42:04 [App     ] Image loaded   1: 0001.jpg
22:42:04 [App     ] Image loaded   2: 0002.jpg
22:42:04 [App     ] Image loaded   3: 0003.jpg
22:42:04 [App     ] Image loaded   4: 0004.jpg
22:42:04 [App     ] Image loaded   5: 0005.jpg
22:42:04 [App     ] Image loaded   6: 0006.jpg
22:42:04 [App     ] Image loaded   7: 0007.jpg
22:42:04 [App     ] Scene loaded from interface format (21ms):
	8 images (8 calibrated) with a total of 48.00 MPixels (6.00 MPixels/image)
	14532 points, 0 vertices, 0 faces
Viewer: /home/xin/zjx/openMVS/apps/Viewer/Window.cpp:294: void VIEWER::Window::MouseButton(int, int, int): Assertion `ISEQUAL(invV(3,3),1.0)' failed.

Process finished with exit code 6

**Comment by JimZhou-001** [comment]
The window appear but I can't see any points.

When I click on the window, the following information was shown.

Viewer: /home/xin/zjx/openMVS/apps/Viewer/Window.cpp:294: void VIEWER::Window::MouseButton(int, int, int): Assertion `ISEQUAL(invV(3,3),1.0)' failed.

**Comment by cdcseacave** [comment]
that is an assert, where is the crash? pls check some tutorial on net about debugging C++ code, I can not help you here
if you follow the instructions in the Interface.h or an example as the one in OpenMVG you should get a good solution

**Comment by JimZhou-001** [comment]
/home/xin/zjx/openMVS/openMVS_Build/bin/DensifyPointCloud ./scene_first_mesh.mvs 
22:36:56 [App     ] Build date: Mar 22 2019, 20:34:24
22:36:56 [App     ] CPU: Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz
22:36:56 [App     ] RAM: 31.37GB Physical Memory 7.45GB Virtual Memory
22:36:56 [App     ] OS: Linux 4.4.0-34-generic (x86_64)
22:36:56 [App     ] SSE & AVX compatible CPU & OS detected
22:36:56 [App     ] Command line: ./scene_first_mesh.mvs
22:36:56 [App     ] CUDA device 0 initialized: Quadro M6000 (compute capability 5.2; memory 11.92GB)
22:36:56 [App     ] Camera model loaded: platform 0; camera  0; f 0.898x0.900; poses 8
22:36:56 [App     ] Image loaded   0: 0000.jpg
22:36:56 [App     ] Image loaded   1: 0001.jpg
22:36:56 [App     ] Image loaded   2: 0002.jpg
22:36:57 [App     ] Image loaded   3: 0003.jpg
22:36:57 [App     ] Image loaded   4: 0004.jpg
22:36:57 [App     ] Image loaded   5: 0005.jpg
22:36:57 [App     ] Image loaded   6: 0006.jpg
22:36:57 [App     ] Image loaded   7: 0007.jpg
22:36:57 [App     ] Scene loaded from interface format (385ms):
	8 images (8 calibrated) with a total of 48.00 MPixels (6.00 MPixels/image)
	14532 points, 0 vertices, 0 faces
22:36:57 [App     ] Preparing images for dense reconstruction completed: 8 images (160ms)
22:36:57 [App     ] error: reference image   0 has no good images in view
22:36:57 [App     ] error: reference image   1 has no good images in view
22:36:57 [App     ] error: reference image   4 has no good images in view
22:36:57 [App     ] error: reference image   2 has no good images in view
22:36:57 [App     ] error: reference image   7 has no good images in view
22:36:57 [App     ] error: reference image   5 has no good images in view
22:36:57 [App     ] error: reference image   3 has no good images in view
22:36:57 [App     ] error: reference image   6 has no good images in view
22:36:57 [App     ] Selecting images for dense reconstruction completed: 0 images (78ms)
Fused depth-maps 0 (100%, 0ms)
22:36:57 [App     ] Depth-maps fused and filtered: 0 depth-maps, 0 depths, 0 points (-2147483648%%) (0ms)
22:36:57 [App     ] Densifying point-cloud completed: 0 points (500ms)
22:36:57 [App     ] Scene saved (0ms):
	8 images (8 calibrated)
	0 points, 0 vertices, 0 faces
22:36:57 [App     ] MEMORYINFO: {
22:36:57 [App     ] 	VmPeak:	56463932 kB
22:36:57 [App     ] 	VmSize:	56276524 kB
22:36:58 [App     ] } ENDINFO

**Comment by JimZhou-001** [comment]
@cdcseacave 
As you can see, it ran out of memory.

**Comment by JimZhou-001** [comment]
@cdcseacave Thank you. I read the points incorrectly before.
