### ISSUE TITLE
input and original point cloud address

### ISSUE THREAD

**Issue by taoqian123** [cdcseacave/openMVS#418]
Hello! I saw the scene_dense.ply in your openMVS_sample, which is a point cloud with RGB information. I would like to ask,the input of openmvs is an image and a point cloud without RGB? In addition, I only saw the image used in your openMVS_sample, I want to trouble you to give me the original point cloud address, thank you again!

**Comment by cdcseacave** [comment]
the input is the image set and the camera poses, pls see OpenMVG for more details.
