### ISSUE TITLE
How to compile Viewer.exe

### ISSUE THREAD

**Issue by fengyunxuan** [cdcseacave/openMVS#419]
@cdcseacave   I try to compile Viewer, but failed when it link. Can you guide me? tks!
![image](https://user-images.githubusercontent.com/19601392/55134675-70a5bc00-5164-11e9-9f61-2d7c5c7adfbc.png)

**Comment by cdcseacave** [comment]
you need to link to OpenGL libs
maybe I forgot to add it to CMake, pls add it there or add it to the project directly: opengl32.lib

**Comment by fengyunxuan** [comment]
@cdcseacave According to your suggestion, this problem has been solved.  Thanks for your help!
