### ISSUE TITLE
Incomplete mesh

### ISSUE THREAD

**Issue by Just5D** [cdcseacave/openMVS#42]
![qq 20160112161858](https://cloud.githubusercontent.com/assets/16056823/12258262/4b5f4a86-b948-11e5-9836-1c3fea6309ab.jpg)
![qq 20160112161906](https://cloud.githubusercontent.com/assets/16056823/12258267/51e740ac-b948-11e5-9764-deb055224378.jpg)

**Comment by cdcseacave** [comment]
could you please share the images and the input scene to debug this?

**Comment by Just5D** [comment]
500 images too big to upload. i try other smaller and share

**Comment by XYue** [comment]
hello, @Just5D have you tried the latest version of ReconstrucMesh?

**Comment by Just5D** [comment]
thanks.
