### ISSUE TITLE
Install OpenMVS under windows 

### ISSUE THREAD

**Issue by wow2006** [cdcseacave/openMVS#421]
Install OpenMVS using cmake and VS 2017 Don't install libs files to install directory.

### Specifications like the version of the project, operating system, and hardware
Windows 10 64
current master branch d19dae8473682a565823d6a6258420c052d483ec
Visual Studio 15 2017
with CMake 3.12
and vcpkg toolchain
and CUDA 10

Intel Core I7 5820K
Ram 32GB
980 GTX
### Steps to reproduce the problem
1. flow building steps on windows [build](https://github.com/cdcseacave/openMVS/wiki/Building#windows-compilation)
2. Open Solution on VS and build all
3. Install OpenMVS `just headers and cmake is installed no libs`

**Comment by cdcseacave** [comment]
That might be true, never had the chance to test it. Feel free to make a PR with a fix.

**Comment by cdcseacave** [comment]
OpenMVS as added as a library to vcpkg and the compiled libs are also exported, along with the header files

**Comment by wow2006** [comment]
That is great news thanks
