### ISSUE TITLE
CMake Error: install(EXPORT "OpenMVSTargets" ...) includes target "MVS" which requires target "CGAL"

### ISSUE THREAD

**Issue by q87956256** [cdcseacave/openMVS#425]
### Specifications like the version of the project, operating system, and hardware
use CMAKE-gui in Windows
### Steps to reproduce the problem
when I use CMAKE to  Generate OpenMVS ,problem happend:
Configuring done
CMake Error: install(EXPORT "OpenMVSTargets" ...) includes target "MVS" which requires target "CGAL" that is not in the export set.
CMake Error: install(EXPORT "OpenMVSTargets" ...) includes target "MVS" which requires target "CGAL" that is not in the export set.
Generating done.

How can I solve thie problem?

**Comment by cdcseacave** [comment]
I was trying to solve this but without success. Even though CGAL is included as header only (the latest CGAL has this option), CMake still complains that CGAL is not set in the exports. Anybody with more CMake experience can help?

**Comment by maxGimeno** [comment]
CMake's doc about `export` specifies :
```
If a library target is included in the export but a target to which it links is not included the behavior is unspecified
```
I think you just need to add CGAL to the list of exported targets [here](https://github.com/cdcseacave/openMVS/blob/d19dae8473682a565823d6a6258420c052d483ec/libs/MVS/CMakeLists.txt#L45)

**Comment by cdcseacave** [comment]
thx for looking into this, unfortunately it does not help, applying your suggestion does not change anything, I still get same error:
```
-- Configuring done
CMake Error: install(EXPORT "OpenMVSTargets" ...) includes target "MVS" which requires target "CGAL" that is not in the export set.
CMake Error: install(EXPORT "OpenMVSTargets" ...) includes target "MVS" which requires target "CGAL" that is not in the export set.
-- Generating done
```

**Comment by maxGimeno** [comment]
Another possibility is that ${CGAL_LIBS} contains unwanted things. Since CGAL::CGAL is there, CGAL_LIBS is not supposed to be needed. Try to remove that from [here](https://github.com/cdcseacave/openMVS/blob/d19dae8473682a565823d6a6258420c052d483ec/libs/MVS/CMakeLists.txt#L45) maybe it will be sufficient.

**Comment by cdcseacave** [comment]
this does not work either, the only thing that changes is taht now is only one error message:
```
-- Configuring done
CMake Error: install(EXPORT "OpenMVSTargets" ...) includes target "MVS" which requires target "CGAL" that is not in the export set.
-- Generating done
```

besides, the reason I do not use `CGAL::CGAL` directly is because this is not supported by old CGAL versions, so that is why I do the conversion

**Comment by maxGimeno** [comment]
@lrineau might know more about this.

**Comment by lrineau** [comment]
@q87956256 There is indeed a bug in CGAL CMake scripts, that prevent from using CGAL as an imported target. The PR https://github.com/CGAL/cgal/pull/3922 will fix that in CGAL-4.13.2, CGAL-4.14.1, and CGAL-5.0.

**Comment by cdcseacave** [comment]
thx @q87956256 @lrineau

**Comment by cdcseacave** [comment]
fix in the latest CGAL and VCPKG
