### ISSUE TITLE
Questions about openMVS install

### ISSUE THREAD

**Issue by Gthq** [cdcseacave/openMVS#431]
Hello, 
  When I installed openMVS something wrong occured. 
  Input:_make -j12 && sudo make install_
  Output: 
  [ 92%] Linking CXX executable ../../bin/Viewer
CMakeFiles/Viewer.dir/Image.cpp.o: In function `VIEWER::Image::AssignImage(cv::_InputArray const&)':
Image.cpp:(.text._ZN6VIEWER5Image11AssignImageERKN2cv11_InputArrayE+0x163): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
Image.cpp:(.text._ZN6VIEWER5Image11AssignImageERKN2cv11_InputArrayE+0x170): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
CMakeFiles/Viewer.dir/Image.cpp.o: In function `VIEWER::Image::TransferImage()':
Image.cpp:(.text._ZN6VIEWER5Image13TransferImageEv+0x2b): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
CMakeFiles/Viewer.dir/Scene.cpp.o: In function `EVTLoadImage::Run(void*)':
Scene.cpp:(.text._ZN12EVTLoadImage3RunEPv[_ZN12EVTLoadImage3RunEPv]+0x29c): undefined reference to `vtable for cv::_InputArray'
CMakeFiles/Viewer.dir/Scene.cpp.o: In function `VIEWER::Scene::Open(char const*, char const*)':
Scene.cpp:(.text._ZN6VIEWER5Scene4OpenEPKcS2_+0x1809): undefined reference to `vtable for cv::_OutputArray'
Scene.cpp:(.text._ZN6VIEWER5Scene4OpenEPKcS2_+0x1812): undefined reference to `vtable for cv::_InputArray'
Scene.cpp:(.text._ZN6VIEWER5Scene4OpenEPKcS2_+0x183e): undefined reference to `vtable for cv::_InputArray'
../../lib/libMVS.a(Image.cpp.o): In function `MVS::Image::ResizeImage(unsigned int)':
Image.cpp:(.text._ZN3MVS5Image11ResizeImageEj+0x32d): undefined reference to `vtable for cv::_OutputArray'
Image.cpp:(.text._ZN3MVS5Image11ResizeImageEj+0x336): undefined reference to `vtable for cv::_InputArray'
../../lib/libMVS.a(Image.cpp.o): In function `MVS::Image::ReloadImage(unsigned int, bool)':
Image.cpp:(.text._ZN3MVS5Image11ReloadImageEjb+0x335): undefined reference to `vtable for cv::_OutputArray'
Image.cpp:(.text._ZN3MVS5Image11ReloadImageEjb+0x33e): undefined reference to `vtable for cv::_InputArray'
../../lib/libMVS.a(Scene.cpp.o): In function `boost::archive::detail::oserializer<boost::archive::binary_oarchive, cv::Mat_<SEACAVE::TPixel<unsigned char> > >::save_object_data(boost::archive::detail::basic_oarchive&, void const*) const':
Scene.cpp:(.text._ZNK5boost7archive6detail11oserializerINS0_15binary_oarchiveEN2cv4Mat_IN7SEACAVE6TPixelIhEEEEE16save_object_dataERNS1_14basic_oarchiveEPKv[_ZNK5boost7archive6detail11oserializerINS0_15binary_oarchiveEN2cv4Mat_IN7SEACAVE6TPixelIhEEEEE16save_object_dataERNS1_14basic_oarchiveEPKv]+0x114): undefined reference to `vtable for cv::_OutputArray'
../../lib/libMVS.a(Scene.cpp.o): In function `void boost::serialization::save<boost::archive::text_oarchive, SEACAVE::TPixel<unsigned char> >(boost::archive::text_oarchive&, cv::Mat_<SEACAVE::TPixel<unsigned char> > const&, unsigned int)':
Scene.cpp:(.text._ZN5boost13serialization4saveINS_7archive13text_oarchiveEN7SEACAVE6TPixelIhEEEEvRT_RKN2cv4Mat_IT0_EEj[_ZN5boost13serialization4saveINS_7archive13text_oarchiveEN7SEACAVE6TPixelIhEEEEvRT_RKN2cv4Mat_IT0_EEj]+0x197): undefined reference to `vtable for cv::_OutputArray'
../../lib/libMVS.a(Mesh.cpp.o): In function `SEACAVE::TImage<SEACAVE::TPixel<unsigned char> >::Load(SEACAVE::String const&)':
Mesh.cpp:(.text._ZN7SEACAVE6TImageINS_6TPixelIhEEE4LoadERKNS_6StringE[_ZN7SEACAVE6TImageINS_6TPixelIhEEE4LoadERKNS_6StringE]+0x10e): undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
Mesh.cpp:(.text._ZN7SEACAVE6TImageINS_6TPixelIhEEE4LoadERKNS_6StringE[_ZN7SEACAVE6TImageINS_6TPixelIhEEE4LoadERKNS_6StringE]+0x34c): undefined reference to `vtable for cv::_OutputArray'
Mesh.cpp:(.text._ZN7SEACAVE6TImageINS_6TPixelIhEEE4LoadERKNS_6StringE[_ZN7SEACAVE6TImageINS_6TPixelIhEEE4LoadERKNS_6StringE]+0x43f): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
Mesh.cpp:(.text._ZN7SEACAVE6TImageINS_6TPixelIhEEE4LoadERKNS_6StringE[_ZN7SEACAVE6TImageINS_6TPixelIhEEE4LoadERKNS_6StringE]+0x44c): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
../../lib/libMVS.a(Mesh.cpp.o): In function `SEACAVE::TImage<SEACAVE::TPixel<unsigned char> >::Save(SEACAVE::String const&) const':
Mesh.cpp:(.text._ZNK7SEACAVE6TImageINS_6TPixelIhEEE4SaveERKNS_6StringE[_ZNK7SEACAVE6TImageINS_6TPixelIhEEE4SaveERKNS_6StringE]+0x10f): undefined reference to `vtable for cv::_InputArray'
Mesh.cpp:(.text._ZNK7SEACAVE6TImageINS_6TPixelIhEEE4SaveERKNS_6StringE[_ZNK7SEACAVE6TImageINS_6TPixelIhEEE4SaveERKNS_6StringE]+0x131): undefined reference to `cv::imwrite(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
../../lib/libMVS.a(Camera.cpp.o): In function `MVS::DecomposeProjectionMatrix(SEACAVE::TMatrix<double, 3, 4> const&, SEACAVE::TMatrix<double, 3, 3>&, SEACAVE::TRMatrixBase<double>&, SEACAVE::TPoint3<double>&)':
Camera.cpp:(.text._ZN3MVS25DecomposeProjectionMatrixERKN7SEACAVE7TMatrixIdLi3ELi4EEERNS1_IdLi3ELi3EEERNS0_12TRMatrixBaseIdEERNS0_7TPoint3IdEE+0x4b): undefined reference to `vtable for cv::_InputArray'
Camera.cpp:(.text._ZN3MVS25DecomposeProjectionMatrixERKN7SEACAVE7TMatrixIdLi3ELi4EEERNS1_IdLi3ELi3EEERNS0_12TRMatrixBaseIdEERNS0_7TPoint3IdEE+0x533): undefined reference to `vtable for cv::_OutputArray'
Camera.cpp:(.text._ZN3MVS25DecomposeProjectionMatrixERKN7SEACAVE7TMatrixIdLi3ELi4EEERNS1_IdLi3ELi3EEERNS0_12TRMatrixBaseIdEERNS0_7TPoint3IdEE+0x563): undefined reference to `vtable for cv::_OutputArray'
Camera.cpp:(.text._ZN3MVS25DecomposeProjectionMatrixERKN7SEACAVE7TMatrixIdLi3ELi4EEERNS1_IdLi3ELi3EEERNS0_12TRMatrixBaseIdEERNS0_7TPoint3IdEE+0x582): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
../../lib/libMVS.a(Camera.cpp.o): In function `MVS::DecomposeProjectionMatrix(SEACAVE::TMatrix<double, 3, 4> const&, SEACAVE::TRMatrixBase<double>&, SEACAVE::TPoint3<double>&)':
Camera.cpp:(.text._ZN3MVS25DecomposeProjectionMatrixERKN7SEACAVE7TMatrixIdLi3ELi4EEERNS0_12TRMatrixBaseIdEERNS0_7TPoint3IdEE+0x3e): undefined reference to `vtable for cv::_InputArray'
Camera.cpp:(.text._ZN3MVS25DecomposeProjectionMatrixERKN7SEACAVE7TMatrixIdLi3ELi4EEERNS0_12TRMatrixBaseIdEERNS0_7TPoint3IdEE+0x4e7): undefined reference to `vtable for cv::_OutputArray'
../../lib/libMVS.a(Camera.cpp.o): In function `MVS::AssembleProjectionMatrix(SEACAVE::TMatrix<double, 3, 3> const&, SEACAVE::TRMatrixBase<double> const&, SEACAVE::TPoint3<double> const&, SEACAVE::TMatrix<double, 3, 4>&)':
Camera.cpp:(.text._ZN3MVS24AssembleProjectionMatrixERKN7SEACAVE7TMatrixIdLi3ELi3EEERKNS0_12TRMatrixBaseIdEERKNS0_7TPoint3IdEERNS1_IdLi3ELi4EEE+0xd8): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
Camera.cpp:(.text._ZN3MVS24AssembleProjectionMatrixERKN7SEACAVE7TMatrixIdLi3ELi3EEERKNS0_12TRMatrixBaseIdEERKNS0_7TPoint3IdEERNS1_IdLi3ELi4EEE+0x386): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
collect2: error: ld returned 1 exit status
apps/Viewer/CMakeFiles/Viewer.dir/build.make:289: recipe for target 'bin/Viewer' failed
make[2]: *** [bin/Viewer] Error 1
CMakeFiles/Makefile2:956: recipe for target 'apps/Viewer/CMakeFiles/Viewer.dir/all' failed
make[1]: *** [apps/Viewer/CMakeFiles/Viewer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
 

How can I fix it? Thank you.

**Comment by cdcseacave** [comment]
no idea, there seems to be something wrong with your OpenCV library, try updating the code and rebuild it.
