### ISSUE TITLE
Densification - Discarding points with depths farther than 1m

### ISSUE THREAD

**Issue by UannaFF** [cdcseacave/openMVS#434]
Hello, Is there any way I can discard depths equivalent to 1m in real life? I'm trying to do a reconstruction but the scale of the important structure is too small because it's also reconstructing the ceiling. Here's an example:

![image](https://user-images.githubusercontent.com/5957673/57227005-a023d000-7010-11e9-895f-ce2fa941010c.png)

When I'm really just interested in this area:

![image](https://user-images.githubusercontent.com/5957673/57227055-bf226200-7010-11e9-813e-d626978d5c22.png)

I noticed that in the fusion step there's a conditional for discarding depths that are equal to zero, usually I would add my condition there but I don't know what the depth values represent, meters, mm?

**Comment by cdcseacave** [comment]
You can certainly chance the code to do that, but I will not recommend. Best is to reconstruct the dense point cloud as it is and next apply a bounding box at the end that remove anything outside it. That is easy to do, but I do not have time right now. Feel free to do it and add a PR.

**Comment by UannaFF** [comment]
Thanks for the reply, I'll try to do it around mid june when i have time.

**Comment by danivelikova** [comment]
Hi,
@UannaFF did you succeeded in doing it? I'm also interested.
