### ISSUE TITLE
Volume estimation

### ISSUE THREAD

**Issue by XiaoR** [cdcseacave/openMVS#435]
Hi Guys,
Thanks for you great work.  My final goal is volume estimation, so I'm wondering if this is in your roadmap ? and if not, how can I implement it in an easy way?
I just want a rough result on volume of a structure, so any related open source projects would help.

**Comment by cdcseacave** [comment]
not on the road map, sry
easiest is to use the mesh of the object you want to measure and compute its volume

**Comment by XiaoR** [comment]
Thanks!!!
