### ISSUE TITLE
InterfaceCOLMAP in develop branch

### ISSUE THREAD

**Issue by griegler** [cdcseacave/openMVS#436]
The results on the ETH3D and Tanks and Temples benchmarks seem to be produced with the code from the `develop` branch, as some options are only available there (e.g., `optimize`).  I tried to run the code from the `develop` branch on the on the Tanks and Temples dataset, but `DensifyPointCloud` fails with a `std::length_error`. 

I computed the camera poses and sparse point cloud with COLMAP and used the InterfaceCOLMAP to convert it. Note that this works fine with the code in the `master` branch. Is the InterfaceCOLMAP not compatible with the `develop` branch, or is there some other issue?

**Comment by cdcseacave** [comment]
It is compatible, maybe you are doing something wrong, pls see #360 for a detailed explanation of how to use it. Develop was also merged in master now.
