### ISSUE TITLE
Due to the large number of images used, I encountered a memory error when FuseDepthMaps().

### ISSUE THREAD

**Issue by KeoChi** [cdcseacave/openMVS#444]
Due to the large number of images used, I encountered a memory error when FuseDepthMaps(). In issues, I found that someone has encountered similar problems:#298 , #304 . In addition to increasing the memory size, there should be other ways to deal with it. In openMVG, there is a scene clustering approach [openMVG#857](https://github.com/openMVG/openMVG/issues/857), [openMVG#1071](https://github.com/openMVG/openMVG/issues/1071), [openMVG#1059](https://github.com/openMVG/openMVG/issues/1059). Has anyone solved this problem? Can someone share relevant advice and experience? Let's discuss this issue together.

**Comment by cdcseacave** [comment]
#438
