### ISSUE TITLE
ReconstructMesh never end

### ISSUE THREAD

**Issue by shauidu** [cdcseacave/openMVS#447]
Hi cdcseacave,

I may have found some bugs in ReconstructMesh project, please check about them.
Problems are in function bool intersect(***);

1. when nb_coplanar == 1, you should check whether there are infinite facets in the output, for the edge may be on the convex boundary. (may have the same problem in case 2, but I did not check that)

2. // skip this cell if the intersection is not in the desired direction
Should we update inter.dist before checking? I think "inter.dist = inter.ray.IntersectsDist(getFacetPlane(in_facet));" should be placed after the following judgement.

**Comment by cdcseacave** [comment]
Please make a PR and add the also the data to reproduce the problem.

**Comment by shauidu** [comment]
I'm not sure whether you can reproduce the problem in the master branch or not, sorry for that. But it do have a problem on my computer.

The data is quite large, it require more than 16GB memory to run, and I'm testing the data on a server using a forked repository, based on v0.8.

I checked the code, and I think it's a logical error, as I said in the first comment. (Maybe I'm wrong :-) )

I will check the data on the master branch later, if I can reproduce the problem, and I'm allowed to share the data. How can I send you the data, it about 1.1GB (200+ images and a densify mvs result).

Thanks

**Comment by shauidu** [comment]
Hi,

I test the same data using master branch code. And it reproduces the problem on one computer, but it works 'fine' on another computer.

The problem is when segment intersects with tetrahedron's edge in bool intersect(***) function in file "openMVS/libs/MVS/SceneReconstruct.cpp", the out_facets will sometimes contain infinite facets when the hit edge is on the boundary.
And inifinite facet's vertex position seems to have different hebavior, sometime it is (0,0,0), sometime one or more its components will be Inf.

I have pulled a request, you can check that.
But I'm not allowed to share the data, sorry for that.

**Comment by cdcseacave** [comment]
Thx, pls check my PR review.

**Comment by shauidu** [comment]
I think the problem is solved, thanks.
