### ISSUE TITLE
Get all cameras that see selected face

### ISSUE THREAD

**Issue by danivelikova** [cdcseacave/openMVS#448]
Hi,
I have generated 3d textured mesh from a set of images using OpenMVG+OpenMVS.
I am able to open the model with the Viewer and by double clicking on the mesh to select faces. What I need is by selecting a face to get all cameras that are seeing that face. How can I do that?

**Comment by cdcseacave** [comment]
that information is not readily available, but you can compute it using `ListCameraFaces()`

**Comment by danivelikova** [comment]
how can I access ListCameraFaces() from Viewer/Scene.cpp
