### ISSUE TITLE
common object's memory illegial overwrite

### ISSUE THREAD

**Issue by sxsong1207** [cdcseacave/openMVS#455]
### Specifications like the version of the project, operating system, and hardware
c70f51f2c87b4cb6548084067571746d16358d2a on master branch
Ubuntu 18.04
i7 8700k 48GB RAM

### Steps to reproduce the problem
I have observed some annoying bug with in Scene IO module. It runs good in your designed pipeline. But io system (including basic common types) looks like very fragile. For example, I tried to add another OBJ material by creating second face group, with very simple codes:

> #include "../../libs/MVS/Common.h"
> #include "../../libs/MVS/Scene.h"

> int main(int argc, const char **argv) {
>   ObjModel model;
>   ObjModel::Group &group0 = model.AddGroup(_T("mat0"));
>   std::cout << "Groups: " << group0.material_name << std::endl;
>   ObjModel::Group &group1 = model.AddGroup(_T("mat1"));
>   std::cout << "Groups: " << group0.material_name << " " << group1.material_name << std::endl;
>   ObjModel::Group &group2 = model.AddGroup(_T("mat2"));
>   std::cout << "Groups: " << group0.material_name << " " << group1.material_name << " " << group2.material_name
>             << std::endl;
>   return 0;
> }

and it print such lines:

> Groups: mat0
> Groups:  mat1
> Groups:   mat2

See? previous mat0 mat1 was disappeared.

Every time I called AddGroup to create new object, the previous one, I haven't found what exact happened here. I suppose part of data was overwrited by second one.

I also found that, If I Load a scene from file, and then insert a new Platform object to platformarr. and call scene.Release(). the program was crashed due to double free memory detected. String's behavior is weird in IO, especially the part that work with boost serialization.

Anyway, I am very appreciate your contribution to maintainance such a sophiscated project. If you have any idea where may I found the solution, pls let me know. Thanks.

**Comment by cdcseacave** [comment]
I do not understand about what solution are you speaking. If you found a bug, pls submit a PR with a fix and I'll consider adding it. Thank you!
