### ISSUE TITLE
usage of 32bit exr for texturing

### ISSUE THREAD

**Issue by thunders82** [cdcseacave/openMVS#461]
Hi @cdcseacave ,

I'd like to use 32bit exr to texture the final mesh. I had a quick look at the code and it seems it's using opencv which is already compatible with 32bit exr. (using 3rd party modules)

In the current code I was thinking to :
- change all the Image8U by Image32F3 
- remove all the log to lin conversions
- change the Save function in Type.inl to handle exr.

Is there anything else I'm missing ?

Thanks,

Geoffrey

**Comment by thunders82** [comment]
Hi @cdcseacave ,

I can now successfully read EXRs. As the program is currently only working with 8bit images I'm converting the linear float output from my imageEXR.cpp into 8bit (+ gamma correction) and everything seems to work as expected.

Instead of only focusing on the part I'm interested (TextureMesh) I was thinking I could update the whole code to support 8bit and 32bit float... In your opinion, what would be the best way to tackle this and handle both 8bit and 32bit in a easy way? I'd like to avoid to botch the original code too much.

Thanks,

Geoffrey

**Comment by thunders82** [comment]
This is now completed and pull request submitted. closing ticket !

**Comment by cdcseacave** [comment]
Can u pls point me to the PR containing this?
