### ISSUE TITLE
DensifyPointCloud locks up

### ISSUE THREAD

**Issue by john-davies** [cdcseacave/openMVS#463]
### Specifications like the version of the project, operating system, and hardware
17:02:03 [App     ] Build date: Oct 21 2018, 14:47:56
17:02:03 [App     ] CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
17:02:03 [App     ] RAM: 15.59GB Physical Memory 15.92GB Virtual Memory
17:02:03 [App     ] OS: Linux 4.4.0-154-generic (x86_64)
17:02:03 [App     ] SSE & AVX compatible CPU & OS detected
( Ubuntu 16.04 )

### Steps to reproduce the problem
I have 288 images ( 4644px x 3084px ) and the sparse reconstruction has been done using openMVG. The log file for DensifyPointCloud is attached and essentially what happens is that the processing gets through the Depth Map filtering and then the whole PC just locks up and is unresponsive to keyboard inputs. The only way out is to power cycle the machine. It may eventually come back of its own accord but the last entry in the log is at 15:29 and I rebooted at 16:45.

Is this likely to be a problem with lack of memory? If so then is there a way of reducing the size of the dense point cloud to work around this problem?

I've used openMVS quite successfully in the past. Dense reconstruction using MVE works successfully on the same image set.

For comparison, a different reconstruction using 144 images worked fine and the equivalent log entries are:

```
19:31:25 [App     ] Depth map 107 filtered using 8 other images: 1827650/2836933 depths discarded (2s72ms)
19:35:28 [App     ] Depth-maps fused and filtered: 143 depth-maps, 146737115 depths, 21577442 points (15%%) (2m51s62ms)
```

[DensifyPointCloud-1907290921258B5B91.log](https://github.com/cdcseacave/openMVS/files/3443208/DensifyPointCloud-1907290921258B5B91.log)

**Comment by john-davies** [comment]
Possibly the same as #444 and #438

**Comment by cdcseacave** [comment]
indeed, most likely OOM; you can try enabling virtual memory, in this case could work fine OR reduce image resolution using `--resolution-level 2` or more

**Comment by john-davies** [comment]
Thanks, that was the problem. I also had similar issues with running out of memory in the subsequent processing stages and eventually used the following settings:

`DensifyPointCloud --resolution-level 2`
`ReconstructMesh --min-point-distance 5` ( as suggested by #180 )
`TextureMesh --resolution-level 2` ( as suggested by #358 )

( Maybe it's worth adding these to an FAQ somewhere? )

If anybody's interested the final model is here - https://sketchfab.com/3d-models/sea-shell-3a6223bdb48a4bcaa91889b0ee6b9fac
