### ISSUE TITLE
openMVS visual studio 15 rebuild issues

### ISSUE THREAD

**Issue by Rahma-15** [cdcseacave/openMVS#464]
Hi, i am having trouble building openMVS in VS 2017.  

**Severity	Error	LNK1104	cannot open file '..\..\lib\vc15\x64\Debug\MVS.lib'.	
Would appreciate any help !**

1>------ Rebuild All started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Checking Build System
1>CMake is re-running because C:/Users/rnawab/Documents/vcpkg/src/build/CMakeFiles/generate.stamp is out-of-date.
1>  the file 'C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake'
1>  is newer than 'C:/Users/rnawab/Documents/vcpkg/src/build/CMakeFiles/generate.stamp.depend'
1>  result='-1'
1>-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
1>CMake Deprecation Warning at CMakeLists.txt:30 (cmake_policy):
1>  The OLD behavior for policy CMP0011 will be removed from a future version
1>  of CMake.
1>
1>  The cmake-policies(7) manual explains that the OLD behaviors of all
1>  policies are deprecated and that a policy should be set to OLD only under
1>  specific short-term circumstances.  Projects should be ported to the NEW
1>  behavior and not rely on setting a policy to OLD.
1>
1>
1>-- cotire 1.8.0 loaded.
1>Compiling with C++14
1>CUSTOMBUILD : -- warning : BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
1>-- Can't find BreakPad. Continuing without it.
1>**CHECK <> _ <> **
1>C:/local/boost_1_70_0
1>-- Boost version: 1.70.0
1>-- Found the following Boost libraries:
1>--   iostreams
1>--   program_options
1>--   system
1>--   serialization
1>--   regex
1>INSIDE  o.O
1>**CHECK_LATER <> _ <> **
1>CMake Warning (dev) at CMakeLists.txt:124 (FIND_PACKAGE):
1>  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
1>  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
1>  command to set the policy and suppress this warning.
1>
1>  Environment variable Eigen_ROOT is set to:
1>
1>    C:\Users\rnawab\Downloads\eigen-eigen-b9cd8366d4e8\eigen-eigen-b9cd8366d4e8
1>
1>  For compatibility, CMake is ignoring the variable.
1>This warning is for project developers.  Use -Wno-dev to suppress it.
1>
1>-- Eigen 3.2.10 found (include: C:/Users/rnawab/Downloads/eigen-eigen-b9cd8366d4e8/eigen-eigen-b9cd8366d4e8)
1>-- OpenCV 4.1.1 found (include: C:/Users/rnawab/Documents/opencv-4.1.1/build;C:/Users/rnawab/Documents/opencv-4.1.1/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/core/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/flann/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/imgproc/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/ml/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/phase_unwrapping/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/photo/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/plot/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/quality/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/reg/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/surface_matching/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/xphoto/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/dnn/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/features2d/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/fuzzy/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/gapi/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/hfs/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/img_hash/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/imgcodecs/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/line_descriptor/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/videoio/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/calib3d/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/highgui/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/objdetect/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/rgbd/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/shape/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/structured_light/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/text/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/ts/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/video/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/videostab/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/xfeatures2d/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/ximgproc/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/xobjdetect/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/aruco/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/bgsegm/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/bioinspired/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/ccalib/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/datasets/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/dnn_objdetect/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/dpm/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/face/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/optflow/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/stitching/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/superres/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/tracking/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/stereo/include)
1>CMake Error at build/Utils.cmake:223 (message):
1>  CGAL required, but not found: Please specify CGAL directory using CGAL_ROOT
1>  env.  variable
1>Call Stack (most recent call first):
1>  build/Modules/FindCGAL.cmake:87 (package_report_not_found)
1>  libs/MVS/CMakeLists.txt:2 (FIND_PACKAGE)
1>
1>
1>-- Configuring incomplete, errors occurred!
1>See also "C:/Users/rnawab/Documents/vcpkg/src/build/CMakeFiles/CMakeOutput.log".
1>CMake Configure step failed.  Build files cannot be regenerated correctly.  Attempting to stop IDE build.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code -1073741819.
1>Done building project "ZERO_CHECK.vcxproj" -- FAILED.
2>------ Rebuild All started: Project: Common, Configuration: Debug x64 ------
3>------ Skipped Rebuild All: Project: Continuous, Configuration: Debug x64 ------
3>Project not selected to build for this solution configuration 
4>------ Skipped Rebuild All: Project: Experimental, Configuration: Debug x64 ------
4>Project not selected to build for this solution configuration 
5>------ Skipped Rebuild All: Project: Nightly, Configuration: Debug x64 ------
5>Project not selected to build for this solution configuration 
6>------ Skipped Rebuild All: Project: NightlyMemoryCheck, Configuration: Debug x64 ------
6>Project not selected to build for this solution configuration 
7>------ Skipped Rebuild All: Project: clean_cotire, Configuration: Debug x64 ------
7>Project not selected to build for this solution configuration 
8>------ Skipped Rebuild All: Project: uninstall, Configuration: Debug x64 ------
8>Project not selected to build for this solution configuration 
2>Generating CXX prefix header C:\Users\rnawab\Documents\vcpkg\src\build\libs\Common\x64\Debug\cotire\Common_CXX_prefix.hxx
2>Building Custom Rule C:/Users/rnawab/Documents/vcpkg/src/libs/Common/CMakeLists.txt
2>CMake does not need to re-run because C:/Users/rnawab/Documents/vcpkg/src/build/libs/Common/CMakeFiles/generate.stamp is up-to-date.
2>Common.cpp
2>CUDA.cpp
2>ConfigTable.cpp
2>EventQueue.cpp
2>Log.cpp
2>SML.cpp
2>Timer.cpp
2>Types.cpp
2>Util.cpp
2>Generating Code...
2>Common.vcxproj -> C:\Users\rnawab\Documents\vcpkg\src\build\lib\vc15\x64\Debug\Common.lib
9>------ Rebuild All started: Project: Math, Configuration: Debug x64 ------
9>Generating CXX prefix header C:\Users\rnawab\Documents\vcpkg\src\build\libs\Math\x64\Debug\cotire\Math_CXX_prefix.hxx
9>Building Custom Rule C:/Users/rnawab/Documents/vcpkg/src/libs/Math/CMakeLists.txt
9>CMake does not need to re-run because C:/Users/rnawab/Documents/vcpkg/src/build/libs/Math/CMakeFiles/generate.stamp is up-to-date.
9>Common.cpp
9>IBFS.cpp
9>lmmin.cpp
9>Generating Code...
9>Math.vcxproj -> C:\Users\rnawab\Documents\vcpkg\src\build\lib\vc15\x64\Debug\Math.lib
10>------ Rebuild All started: Project: MVS, Configuration: Debug x64 ------
10>Generating CXX prefix header C:\Users\rnawab\Documents\vcpkg\src\build\libs\MVS\x64\Debug\cotire\MVS_CXX_prefix.hxx
10>Building Custom Rule C:/Users/rnawab/Documents/vcpkg/src/libs/MVS/CMakeLists.txt
10>CMake is re-running because C:/Users/rnawab/Documents/vcpkg/src/build/libs/MVS/CMakeFiles/generate.stamp is out-of-date.
10>  the file 'C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake'
10>  is newer than 'C:/Users/rnawab/Documents/vcpkg/src/build/libs/MVS/CMakeFiles/generate.stamp.depend'
10>  result='-1'
10>-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
10>CMake Deprecation Warning at CMakeLists.txt:30 (cmake_policy):
10>  The OLD behavior for policy CMP0011 will be removed from a future version
10>  of CMake.
10>
10>  The cmake-policies(7) manual explains that the OLD behaviors of all
10>  policies are deprecated and that a policy should be set to OLD only under
10>  specific short-term circumstances.  Projects should be ported to the NEW
10>  behavior and not rely on setting a policy to OLD.
10>
10>
10>-- cotire 1.8.0 loaded.
10>Compiling with C++14
10>CUSTOMBUILD : -- warning : BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
10>-- Can't find BreakPad. Continuing without it.
10>**CHECK <> _ <> **
10>C:/local/boost_1_70_0
10>-- Boost version: 1.70.0
10>-- Found the following Boost libraries:
10>--   iostreams
10>--   program_options
10>--   system
10>--   serialization
10>--   regex
10>INSIDE  o.O
10>**CHECK_LATER <> _ <> **
10>CMake Warning (dev) at CMakeLists.txt:124 (FIND_PACKAGE):
10>  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
10>  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
10>  command to set the policy and suppress this warning.
10>
10>  Environment variable Eigen_ROOT is set to:
10>
10>    C:\Users\rnawab\Downloads\eigen-eigen-b9cd8366d4e8\eigen-eigen-b9cd8366d4e8
10>
10>  For compatibility, CMake is ignoring the variable.
10>This warning is for project developers.  Use -Wno-dev to suppress it.
10>
10>-- Eigen 3.2.10 found (include: C:/Users/rnawab/Downloads/eigen-eigen-b9cd8366d4e8/eigen-eigen-b9cd8366d4e8)
10>-- OpenCV 4.1.1 found (include: C:/Users/rnawab/Documents/opencv-4.1.1/build;C:/Users/rnawab/Documents/opencv-4.1.1/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/core/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/flann/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/imgproc/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/ml/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/phase_unwrapping/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/photo/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/plot/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/quality/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/reg/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/surface_matching/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/xphoto/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/dnn/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/features2d/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/fuzzy/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/gapi/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/hfs/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/img_hash/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/imgcodecs/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/line_descriptor/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/videoio/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/calib3d/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/highgui/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/objdetect/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/rgbd/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/shape/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/structured_light/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/text/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/ts/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/video/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/videostab/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/xfeatures2d/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/ximgproc/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/xobjdetect/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/aruco/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/bgsegm/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/bioinspired/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/ccalib/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/datasets/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/dnn_objdetect/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/dpm/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/face/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/optflow/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/stitching/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/superres/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/tracking/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/stereo/include)
10>CMake Error at build/Utils.cmake:223 (message):
10>  CGAL required, but not found: Please specify CGAL directory using CGAL_ROOT
10>  env.  variable
10>Call Stack (most recent call first):
10>  build/Modules/FindCGAL.cmake:87 (package_report_not_found)
10>  libs/MVS/CMakeLists.txt:2 (FIND_PACKAGE)
10>
10>
10>-- Configuring incomplete, errors occurred!
10>See also "C:/Users/rnawab/Documents/vcpkg/src/build/CMakeFiles/CMakeOutput.log".
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1.
10>Done building project "MVS.vcxproj" -- FAILED.
11>------ Rebuild All started: Project: DensifyPointCloud, Configuration: Debug x64 ------
12>------ Rebuild All started: Project: InterfaceCOLMAP, Configuration: Debug x64 ------
13>------ Rebuild All started: Project: InterfaceVisualSFM, Configuration: Debug x64 ------
14>------ Rebuild All started: Project: ReconstructMesh, Configuration: Debug x64 ------
15>------ Rebuild All started: Project: RefineMesh, Configuration: Debug x64 ------
16>------ Rebuild All started: Project: TextureMesh, Configuration: Debug x64 ------
11>Building Custom Rule C:/Users/rnawab/Documents/vcpkg/src/apps/DensifyPointCloud/CMakeLists.txt
11>CMake does not need to re-run because C:/Users/rnawab/Documents/vcpkg/src/build/apps/DensifyPointCloud/CMakeFiles/generate.stamp is up-to-date.
12>Building Custom Rule C:/Users/rnawab/Documents/vcpkg/src/apps/InterfaceCOLMAP/CMakeLists.txt
13>Building Custom Rule C:/Users/rnawab/Documents/vcpkg/src/apps/InterfaceVisualSFM/CMakeLists.txt
12>CMake does not need to re-run because C:/Users/rnawab/Documents/vcpkg/src/build/apps/InterfaceCOLMAP/CMakeFiles/generate.stamp is up-to-date.
14>Building Custom Rule C:/Users/rnawab/Documents/vcpkg/src/apps/ReconstructMesh/CMakeLists.txt
13>CMake does not need to re-run because C:/Users/rnawab/Documents/vcpkg/src/build/apps/InterfaceVisualSFM/CMakeFiles/generate.stamp is up-to-date.
14>CMake does not need to re-run because C:/Users/rnawab/Documents/vcpkg/src/build/apps/ReconstructMesh/CMakeFiles/generate.stamp is up-to-date.
15>Building Custom Rule C:/Users/rnawab/Documents/vcpkg/src/apps/RefineMesh/CMakeLists.txt
15>CMake does not need to re-run because C:/Users/rnawab/Documents/vcpkg/src/build/apps/RefineMesh/CMakeFiles/generate.stamp is up-to-date.
16>Building Custom Rule C:/Users/rnawab/Documents/vcpkg/src/apps/TextureMesh/CMakeLists.txt
11>DensifyPointCloud.cpp
16>CMake does not need to re-run because C:/Users/rnawab/Documents/vcpkg/src/build/apps/TextureMesh/CMakeFiles/generate.stamp is up-to-date.
12>InterfaceCOLMAP.cpp
14>ReconstructMesh.cpp
16>TextureMesh.cpp
15>RefineMesh.cpp
13>InterfaceVisualSFM.cpp
11>LINK : fatal error LNK1104: cannot open file '..\..\lib\vc15\x64\Debug\MVS.lib'
11>Done building project "DensifyPointCloud.vcxproj" -- FAILED.
15>LINK : fatal error LNK1104: cannot open file '..\..\lib\vc15\x64\Debug\MVS.lib'
15>Done building project "RefineMesh.vcxproj" -- FAILED.
14>LINK : fatal error LNK1104: cannot open file '..\..\lib\vc15\x64\Debug\MVS.lib'
13>LINK : fatal error LNK1104: cannot open file '..\..\lib\vc15\x64\Debug\MVS.lib'
14>Done building project "ReconstructMesh.vcxproj" -- FAILED.
13>Done building project "InterfaceVisualSFM.vcxproj" -- FAILED.
16>LINK : fatal error LNK1104: cannot open file '..\..\lib\vc15\x64\Debug\MVS.lib'
16>Done building project "TextureMesh.vcxproj" -- FAILED.
12>LINK : fatal error LNK1104: cannot open file '..\..\lib\vc15\x64\Debug\MVS.lib'
12>Done building project "InterfaceCOLMAP.vcxproj" -- FAILED.
17>------ Rebuild All started: Project: ALL_BUILD, Configuration: Debug x64 ------
17>Building Custom Rule C:/Users/rnawab/Documents/vcpkg/src/CMakeLists.txt
17>CMake is re-running because C:/Users/rnawab/Documents/vcpkg/src/build/CMakeFiles/generate.stamp is out-of-date.
17>  the file 'C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake'
17>  is newer than 'C:/Users/rnawab/Documents/vcpkg/src/build/CMakeFiles/generate.stamp.depend'
17>  result='-1'
17>-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
17>CMake Deprecation Warning at CMakeLists.txt:30 (cmake_policy):
17>  The OLD behavior for policy CMP0011 will be removed from a future version
17>  of CMake.
17>
17>  The cmake-policies(7) manual explains that the OLD behaviors of all
17>  policies are deprecated and that a policy should be set to OLD only under
17>  specific short-term circumstances.  Projects should be ported to the NEW
17>  behavior and not rely on setting a policy to OLD.
17>
17>
17>-- cotire 1.8.0 loaded.
17>Compiling with C++14
17>CUSTOMBUILD : -- warning : BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
17>-- Can't find BreakPad. Continuing without it.
17>**CHECK <> _ <> **
17>C:/local/boost_1_70_0
17>-- Boost version: 1.70.0
17>-- Found the following Boost libraries:
17>--   iostreams
17>--   program_options
17>--   system
17>--   serialization
17>--   regex
17>INSIDE  o.O
17>**CHECK_LATER <> _ <> **
17>CMake Warning (dev) at CMakeLists.txt:124 (FIND_PACKAGE):
17>  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
17>  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
17>  command to set the policy and suppress this warning.
17>
17>  Environment variable Eigen_ROOT is set to:
17>
17>    C:\Users\rnawab\Downloads\eigen-eigen-b9cd8366d4e8\eigen-eigen-b9cd8366d4e8
17>
17>  For compatibility, CMake is ignoring the variable.
17>This warning is for project developers.  Use -Wno-dev to suppress it.
17>
17>-- Eigen 3.2.10 found (include: C:/Users/rnawab/Downloads/eigen-eigen-b9cd8366d4e8/eigen-eigen-b9cd8366d4e8)
17>-- OpenCV 4.1.1 found (include: C:/Users/rnawab/Documents/opencv-4.1.1/build;C:/Users/rnawab/Documents/opencv-4.1.1/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/core/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/flann/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/imgproc/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/ml/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/phase_unwrapping/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/photo/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/plot/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/quality/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/reg/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/surface_matching/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/xphoto/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/dnn/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/features2d/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/fuzzy/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/gapi/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/hfs/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/img_hash/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/imgcodecs/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/line_descriptor/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/videoio/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/calib3d/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/highgui/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/objdetect/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/rgbd/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/shape/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/structured_light/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/text/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/ts/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/video/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/videostab/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/xfeatures2d/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/ximgproc/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/xobjdetect/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/aruco/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/bgsegm/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/bioinspired/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/ccalib/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/datasets/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/dnn_objdetect/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/dpm/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/face/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/optflow/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/stitching/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/superres/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/tracking/include;C:/Users/rnawab/Documents/opencv_contrib-4.1.1/modules/stereo/include)
17>CMake Error at build/Utils.cmake:223 (message):
17>  CGAL required, but not found: Please specify CGAL directory using CGAL_ROOT
17>  env.  variable
17>Call Stack (most recent call first):
17>  build/Modules/FindCGAL.cmake:87 (package_report_not_found)
17>  libs/MVS/CMakeLists.txt:2 (FIND_PACKAGE)
17>
17>
17>-- Configuring incomplete, errors occurred!
17>See also "C:/Users/rnawab/Documents/vcpkg/src/build/CMakeFiles/CMakeOutput.log".
17>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1.
17>Done building project "ALL_BUILD.vcxproj" -- FAILED.
18>------ Skipped Rebuild All: Project: INSTALL, Configuration: Debug x64 ------
18>Project not selected to build for this solution configuration 
========== Rebuild All: 2 succeeded, 9 failed, 7 skipped ==========

**Comment by cdcseacave** [comment]
the message is quite clear:
```
 CGAL required, but not found: Please specify CGAL directory using CGAL_ROOT
```
