### ISSUE TITLE
 install(EXPORT "OpenMVSTargets" ...) includes target "MVS" which requires target "CGAL" that is not in the export set

### ISSUE THREAD

**Issue by Rahma-15** [cdcseacave/openMVS#465]
### Specifications like the version of the project, operating system, and hardware
CMAKE-GUI 3.14.5
CGAL 4.14
### Steps to reproduce the problem
Hi, I get this error even with the new CGAL version, which supposedly has a fix. Please let me know if i am missing something. Thanks !

Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
CMake Deprecation Warning at CMakeLists.txt:30 (cmake_policy):
  The OLD behavior for policy CMP0011 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

cotire 1.8.0 loaded.
Compiling with C++14
WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
Boost version: 1.70.0
Found the following Boost libraries:
  iostreams
  program_options
  system
  serialization
  regex
CMake Warning (dev) at CMakeLists.txt:113 (FIND_PACKAGE):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Eigen_ROOT is set to:

    C:\Users\rnawab\Downloads\eigen-eigen-b9cd8366d4e8\eigen-eigen-b9cd8366d4e8

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

Eigen 3.2.10 found (include: C:/Users/rnawab/Downloads/eigen-eigen-b9cd8366d4e8/eigen-eigen-b9cd8366d4e8)
OpenCV 4.1.1 found (include: C:/Users/rnawab/Documents/opencv-4.1.1/build;C:/Users/rnawab/Documents/opencv-4.1.1/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/core/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/flann/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/imgproc/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/ml/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/photo/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/dnn/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/features2d/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/gapi/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/imgcodecs/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/videoio/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/calib3d/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/highgui/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/objdetect/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/stitching/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/ts/include;C:/Users/rnawab/Documents/opencv-4.1.1/modules/video/include)
Visual Leak Detector (VLD) is not found.
Using header-only CGAL
Targetting Visual Studio 15 2017
Target build enviroment supports auto-linking
Using VC14 compiler.
Generator uses intermediate configuration directory: $(Platform)/$(Configuration)
Boost version: 1.70.0
Boost include dirs: C:/local/boost_1_70_0
Boost libraries:    
CGAL 4.14 found (include: C:/dev/CGAL-4.14/include)
VCG  found (include: C:/Users/rnawab/Downloads/vcglib-master/vcglib-master)
-- Can't find GLEW. Continuing without it.
Configuring done
**CMake Error: install(EXPORT "OpenMVSTargets" ...) includes target "MVS" which requires target "CGAL" that is not in the export set.**
Generating done

**Comment by cdcseacave** [comment]
All I can say for sure is that it works with the VCPKG build described in the documentation (as you can see from the autobuild system as well). If you use a custom build system, pls fix it and supply a PR.

**Comment by Rahma-15** [comment]
I had to remove CGAL_LIB from:
 # Link its dependencies
TARGET_LINK_LIBRARIES(MVS PRIVATE Common Math IO ${CERES_LIBS} ${CUDA_CUDA_LIBRARY})

in folder src/libs/MVS/cmakeLists in vcpkg.
The Cmake generate is working now.

**Comment by zfb132** [comment]
environments:  
* OS: ubuntu 18.04, 64-bit
* opencv3.4.13 built from source
* libcgal-dev4.11 (CGAL 5.0.0)
* [openMVS code version](https://github.com/cdcseacave/openMVS/tree/1de8e4bd83c37376914784d8bf47a17e80c95d7b) 
* [vcglib code version](https://github.com/cdcseacave/VCG/tree/88f12f212a1645d1fa6416592a434c29e63b57f0) 

I had the same problem with   
`CMake Error: install(EXPORT "OpenMVSTargets" ...) includes target "MVS" which requires target "CGAL" that is not in the export set.`  
However, I had the following problem when executing `make` after deleting `${CGAL_LIB}` according to Rahma-15.  
```txt
[ 81%] Built target InterfaceCOLMAP
../../lib/libMVS.a(SceneReconstruct.cpp.o):SceneReconstruct.cpp:function CGAL::Cartesian_converter<CGAL::Type_equality_wrapper<CGAL::Cartesian_base_no_ref_count<double, CGAL::Epick>, CGAL::Epick>, CGAL::Simple_cartesian<CGAL::Mpzf>, CGAL::NT_converter<double, CGAL::Mpzf> >::operator()(CGAL::Point_3<CGAL::Epick> const&) const [clone .constprop.961]: error: undefined reference to '__gmpn_copyi'
../../lib/libMVS.a(SceneReconstruct.cpp.o):SceneReconstruct.cpp:function CGAL::Cartesian_converter<CGAL::Type_equality_wrapper<CGAL::Cartesian_base_no_ref_count<double, CGAL::Epick>, CGAL::Epick>, CGAL::Simple_cartesian<CGAL::Mpzf>, CGAL::NT_converter<double, CGAL::Mpzf> >::operator()(CGAL::Point_3<CGAL::Epick> const&) const [clone .constprop.961]: error: undefined reference to '__gmpn_copyi'
../../lib/libMVS.a(SceneReconstruct.cpp.o):SceneReconstruct.cpp:function CGAL::Cartesian_converter<CGAL::Type_equality_wrapper<CGAL::Cartesian_base_no_ref_count<double, CGAL::Epick>, CGAL::Epick>, CGAL::Simple_cartesian<CGAL::Mpzf>, CGAL::NT_converter<double, CGAL::Mpzf> >::operator()(CGAL::Point_3<CGAL::Epick> const&) const [clone .constprop.961]: error: undefined reference to '__gmpn_copyi'
../../lib/libMVS.a(SceneReconstruct.cpp.o):SceneReconstruct.cpp:function CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int): error: undef
ined reference to '__gmpn_copyi'

                set(OpenMVS_USE_CERES OFF)
../../lib/libMVS.a(SceneReconstruct.cpp.o):SceneReconstruct.cpp:function CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int): error: undefined reference to '__gmpn_add_n'
../../lib/libMVS.a(SceneReconstruct.cpp.o):SceneReconstruct.cpp:function CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int): error: undefined reference to '__gmpn_sub_n'
../../lib/libMVS.a(SceneReconstruct.cpp.o):SceneReconstruct.cpp:function CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int): error: undefined reference to '__gmpn_add_n'
../../lib/libMVS.a(SceneReconstruct.cpp.o):SceneReconstruct.cpp:function CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int): error: undefined reference to '__gmpn_com'
../../lib/libMVS.a(SceneReconstruct.cpp.o):SceneReconstruct.cpp:function CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int): error: undefined reference to '__gmpn_com'
../../lib/libMVS.a(SceneReconstruct.cpp.o):SceneReconstruct.cpp:function CGAL::operator*(CGAL::Mpzf const&, CGAL::Mpzf const&): error: undefined reference to '__gmpn_mul'
../../lib/libMVS.a(SceneReconstruct.cpp.o):SceneReconstruct.cpp:function CGAL::operator*(CGAL::Mpzf const&, CGAL::Mpzf const&): error: undefined reference to '__gmpn_mul'
../../lib/libMVS.a(SceneReconstruct.cpp.o):SceneReconstruct.cpp:function CGAL::Mpzf_square(CGAL::Mpzf const&): error: undefined reference to '__gmpn_sqr'
collect2: error: ld returned 1 exit status
apps/ReconstructMesh/CMakeFiles/ReconstructMesh.dir/build.make:169: recipe for target 'bin/ReconstructMesh' failed
make[2]: *** [bin/ReconstructMesh] Error 1
CMakeFiles/Makefile2:781: recipe for target 'apps/ReconstructMesh/CMakeFiles/ReconstructMesh.dir/all' failed
make[1]: *** [apps/ReconstructMesh/CMakeFiles/ReconstructMesh.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs...
```
Finally, I solved it by replacing the `${CGAL_LIB}` to `${GMP_LIBRARIES}`. 
https://github.com/cdcseacave/openMVS/blob/1de8e4bd83c37376914784d8bf47a17e80c95d7b/libs/MVS/CMakeLists.txt#L45

Paste here for someone who had same problem.

@cdcseacave Do you mind if I pull a request to fix it?

**Comment by cdcseacave** [comment]
sure not, but I'll need to test it and I will add it if it works on all platforms, thank you
