### ISSUE TITLE
InterfaceCOLMAP terminate called after throwing an instance of 'std::out of range'

### ISSUE THREAD

**Issue by MarcWong** [cdcseacave/openMVS#469]
### Specifications like the version of the project, operating system, and hardware

OS: Ubuntu 18.04.2 (Linux 5.0.0-25-generic x86_64)
CPU: Intel(R) Xeon(R) CPU E5-2660 v4@ 2.00GHz(56 cores)
RAM: 125.78GB
GPU: TITAN RTX 2080

openMVS checked out on 3e9c369 develop branch, build date: Sep 1, 2019

### Steps to reproduce the problem

our SFM algorithm generates COLMAP standard results, and they can be successfully loaded by COLMAP GUI (cameras.txt, images.txt, points3D.txt)
However, when I use InterfaceCOLMAP to transfer them into *.mvs file, it gives back:

```
21:53:44 [APP      ] Command line: InterfaceCOLMAP -i /data3/dataset/Airlook-test/airlook0 -o /data3/dataset/Airlook-test/airlook0/dense/model.mvs
21:53:44 [APP      ] Reading cameras: /data3/dataset/Airlook-test/airlook0/sparse/cameras.txt
21:53:44 [APP      ] Reading images: /data3/dataset/Airlook-test/airlook0/sparse/images.txt
terminate called after throwing an instance of 'std::out of range'
   what():    Map base::at
Aborted (core dumped)
```

**Comment by MarcWong** [comment]
WIP: the default exported COLMAP camera model is SIMPLE_RADIAL, I replaced it to PINHOLE then worked... I'm now testing the post-processes, I'll report the further results

**Comment by cdcseacave** [comment]
that is wrong, you do not manually edit the txt file and switch to PINHOLE, you need to undistort the scene in COLMAP and use that camera model txt

**Comment by MarcWong** [comment]
@cdcseacave I used colmap image_undistorter to convert it, and it finally worked. THX!

**Comment by MarcWong** [comment]
same as #420, I undistorted the scene, but encountered "std::out of range" in InterfaceCOLMAP for some datasets.
Here's a sample of error scene:
https://drive.google.com/open?id=1gqnAR_tGEy3iMv3yo5Za14jsr10DJbyg

**Comment by cdcseacave** [comment]
fixed

**Comment by MarcWong** [comment]
test succeeded, thx.
