### ISSUE TITLE
Quantitative evaluation of dense point clouds on DTU dataset

### ISSUE THREAD

**Issue by rann1018** [cdcseacave/openMVS#471]
I would like to quantitatively evaluate dense point clouds of openMVS on DTU dataset. However, I found that the provided Matlab code by DTU dataset cannot give a result because the scale of the point clouds is totally different. I want to know if there is any method to evaluate the result?

**Comment by cdcseacave** [comment]
there sure is, however I never tried DTU; so you need to read the DTU benchmark description and requirements and make sure you follow them; if you have huge scale difference that is not from OpenMVS, but from whatever SfM method you are using

**Comment by flgw** [comment]
If you are only interested in the dense matching performance, you could skip the SfM step as the dataset provides orientations for all images. I would argue it even is a better evaluations as it avoids potential errors from SfM.

**Comment by rann1018** [comment]
> there sure is, however I never tried DTU; so you need to read the DTU benchmark description and requirements and make sure you follow them; if you have huge scale difference that is not from OpenMVS, but from whatever SfM method you are using

Thanks for your quick reply. I also load the dense point clouds from COLMAP using interfaceCOLMAP. However, I found that the scale of point clouds is different between the fused.ply in COLMAP and the scene.mvs in openMVS. The points in openMVS coordinate are around 1. I wonder if there is some special handles on the scale of there loaded points?

**Comment by rann1018** [comment]
> If you are only interested in the dense matching performance, you could skip the SfM step as the dataset provides orientations for all images. I would argue it even is a better evaluations as it avoids potential errors from SfM.

Thanks a lot for your great suggestion. However, I noticed that when conducting MVS using openMVS, the sparse point clouds are needed to choose the proper view. So maybe the SfM cannot be skipped. Have you ever tested openMVS dense point clouds on DTU dataset?  I am eager for your advice on the DTU dataset.

**Comment by cdcseacave** [comment]
I think you need a better understanding of this process. You can not skip SfM, all I am saying is that the scale is set during SfM not during MVS. Good luck.

**Comment by TWang1017** [comment]
@rann1018 hi, i encountered the same problem that the dtu coordinates is very different from the one i got from colmap or openmvs. have you found a solution? thanks

**Comment by cdcseacave** [comment]
did u try https://github.com/cdcseacave/DTUeval?
it was a long time ago but if I remember right I fixed (and improved) the evaluation in my fork

**Comment by TWang1017** [comment]
> did u try https://github.com/cdcseacave/DTUeval? it was a long time ago but if I remember right I fixed (and improved) the evaluation in my fork

I will have a look. Thansks a lot
