### ISSUE TITLE
openMVS 1.0 cmake -debug model problem

### ISSUE THREAD

**Issue by lvmingzhe** [cdcseacave/openMVS#473]
### Specifications like the version of the project, operating system, and hardware
openMVS-1.0
CPU: Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 cores)
RAM: 23.51GB Physical Memory 16.00GB Virtual Memory
OS: Linux 5.0.0-25-generic (x86_64)
SSE & AVX compatible CPU & OS detected
### Steps to reproduce the problem

I follow this guide https://github.com/cdcseacave/openMVS/wiki/Building
and everything goes well when I set -DCMAKE_BUILD_TYPE=Release

But the problem comes out when I turn the settings into -DCMAKE_BUILD_TYPE=Debug

although I can get the /bin/DensifyPointCloud ,the file size is 51.1MB
then the error occurs as follows:
------------------------------------------------------------------------------------------

lmz@ubuntu:~/work/Herz8/mvs7$ ./DensifyPointCloud 1.mvs
15:15:22 [App     ] Build date: Sep 12 2019, 15:12:11
15:15:22 [App     ] CPU: Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 cores)
15:15:22 [App     ] RAM: 23.51GB Physical Memory 16.00GB Virtual Memory
15:15:22 [App     ] OS: Linux 5.0.0-25-generic (x86_64)
15:15:22 [App     ] SSE & AVX compatible CPU & OS detected
15:15:22 [App     ] Command line: 1.mvs
15:15:22 [App     ] Scene loaded (40ms):
	8 images (8 calibrated) with a total of 1.92 MPixels (0.24 MPixels/image)
	5170 points, 0 vertices, 0 faces
15:15:22 [App     ] K2 = 
  551.6082     0.0000   303.7364 
    0.0000   551.6082   201.4128 
    0.0000     0.0000     1.0000 

15:15:22 [App     ] K5 = 
  551.6082     0.0000   303.7364 
    0.0000   551.6082   201.4128 
    0.0000     0.0000     1.0000 

15:15:22 [App     ] K3 = 
  551.6082     0.0000   303.7364 
    0.0000   551.6082   201.4128 
    0.0000     0.0000     1.0000 

15:15:22 [App     ] K7 = 
  551.6082     0.0000   303.7364 
    0.0000   551.6082   201.4128 
    0.0000     0.0000     1.0000 

15:15:22 [App     ] K1 = 
  551.6082     0.0000   303.7364 
    0.0000   551.6082   201.4128 
    0.0000     0.0000     1.0000 

15:15:22 [App     ] K6 = 
  551.6082     0.0000   303.7364 
    0.0000   551.6082   201.4128 
    0.0000     0.0000     1.0000 

15:15:22 [App     ] K4 = 
  551.6082     0.0000   303.7364 
    0.0000   551.6082   201.4128 
    0.0000     0.0000     1.0000 

15:15:22 [App     ] K0 = 
  551.6082     0.0000   303.7364 
    0.0000   551.6082   201.4128 
    0.0000     0.0000     1.0000 

15:15:22 [App     ] Preparing images for dense reconstruction completed: 8 images (35ms)
15:15:22 [App     ] Reference image   0 sees 7 views:   2(950pts,0.89scl)   3(754pts,0.95scl)   4(493pts,0.88scl)   1(901pts,0.80scl)   5(343pts,0.92scl)   6(245pts,0.97scl)   7(187pts,0.99scl) (1022 shared points)
15:15:22 [App     ] Reference image   2 sees 7 views:   3(2253pts,1.06scl)   4(1917pts,1.02scl)   1(1481pts,0.91scl)   0(950pts,1.13scl)   5(1270pts,1.08scl)   6(939pts,1.14scl)   7(698pts,1.14scl) (2646 shared points)
15:15:22 [App     ] Reference image   3 sees 7 views:   4(2229pts,0.97scl)   2(2253pts,0.95scl)   5(1594pts,1.03scl)   1(1239pts,0.86scl)   6(1193pts,1.08scl)   0(754pts,1.06scl)   7(880pts,1.08scl) (2792 shared points)
15:15:22 [App     ] Reference image   6 sees 7 views:   5(3062pts,0.95scl)   7(2486pts,0.99scl)   4(2239pts,0.90scl)   3(1193pts,0.93scl)   2(939pts,0.89scl)   1(402pts,0.83scl)   0(245pts,1.04scl) (3216 shared points)
15:15:22 [App     ] Reference image   7 sees 7 views:   6(2486pts,1.01scl)   5(2484pts,0.96scl)   4(1661pts,0.91scl)   3(880pts,0.93scl)   2(698pts,0.89scl)   1(301pts,0.82scl)   0(187pts,1.03scl) (2622 shared points)
15:15:22 [App     ] Reference image   5 sees 7 views:   6(3062pts,1.05scl)   7(2484pts,1.04scl)   4(2642pts,0.95scl)   3(1594pts,0.98scl)   2(1270pts,0.93scl)   1(587pts,0.88scl)   0(343pts,1.09scl) (3653 shared points)
15:15:22 [App     ] Reference image   1 sees 7 views:   2(1481pts,1.10scl)   3(1239pts,1.18scl)   4(891pts,1.10scl)   0(901pts,1.25scl)   5(587pts,1.16scl)   6(402pts,1.22scl)   7(301pts,1.24scl) (1564 shared points)
15:15:22 [App     ] Reference image   4 sees 7 views:   5(2642pts,1.06scl)   3(2229pts,1.03scl)   6(2239pts,1.11scl)   2(1917pts,0.98scl)   7(1661pts,1.10scl)   1(891pts,0.92scl)   0(493pts,1.14scl) (3467 shared points)
15:15:22 [App     ] Selecting images for dense reconstruction completed: 8 images (115ms)
DensifyPointCloud: /home/lmz/work/code0912/openMVS20190912/openMVS/libs/MVS/../Common/Util.inl:659: T SEACAVE::DepthSimilarity(T, T) [with T = float]: Assertion `d0 > 0 && d1 > 0' failed.
Aborted

-----------------------------------------------------------

Can you give me some suggestions ? Thanks a lot.

**Comment by cdcseacave** [comment]
I fixed it in the last commit.
