### ISSUE TITLE
DensifyPointCloud aborted(core dumped)

### ISSUE THREAD

**Issue by qixiaomu77** [cdcseacave/openMVS#474]
### Specifications like the version of the project, operating system, and hardware
ubuntu16.04
### Steps to reproduce the problem
./DensifyPointCloud scene.mvs

Estimated depth-maps 1 (9.09%, 2m52s, ETA 28m)...DensifyPointCloud: /home/ouyangxiaoyun/openMVS/libs/MVS/../Common/Util.inl:615: void SEACAVE::Normal2Dir(const SEACAVE::TPoint3<TYPE>&, SEACAVE::TPoint2<TTO>&) [with T = float; TR = float]: Assertion `ISEQUAL(norm(d), T(1))' failed.
Aborted (core dumped)

**Comment by cdcseacave** [comment]
compile in Release

**Comment by qixiaomu77** [comment]
change cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT="$main_path/vcglib"
into cmake . ../openMVS -DCMAKE_BUILD=Release -DVCG_ROOT="$main_path/vcglib"??

**Comment by nick0622** [comment]
I encounter the same problem.

[App     ] Selecting images for dense reconstruction completed: 100 images (297ms)
DensifyPointCloud: /home/openMVS/libs/MVS/DepthMap.cpp:682: void MVS::DepthEstimator::ProcessPixel(SEACAVE::IDX): Assertion `ISEQUAL(norm(normalMap0(nx)), 1.f)' failed.
Aborted (core dumped)

Is this problem solved?

**Comment by DanielMeMyself** [comment]
> change cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT="$main_path/vcglib" into cmake . ../openMVS -DCMAKE_BUILD=Release -DVCG_ROOT="$main_path/vcglib"??

did it work

**Comment by MrPolo-AI** [comment]
> > change cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT="$main_path/vcglib" into cmake . ../openMVS -DCMAKE_BUILD=Release -DVCG_ROOT="$main_path/vcglib"??
> 
> did it work

cd ~/openMVS/make
rm -rf CMakeCache.txt CMakeFiles
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build . -j$(nproc)

I met the same issue, and did those above, finally worked.
