### ISSUE TITLE
ReconstructMesh. Segmentation fault 

### ISSUE THREAD

**Issue by qixiaomu77** [cdcseacave/openMVS#475]
### Specifications like the version of the project, operating system, and hardware
ubuntu16.04 eigen 3.2.10
### Steps to reproduce the problem
~/openMVS_build/bin$ ./ReconstructMesh scene_dense.mvs
14:32:07 [App     ] Build date: Sep 16 2019, 11:25:14
14:32:07 [App     ] CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 cores)
14:32:07 [App     ] RAM: 39.23GB Physical Memory 975.00MB Virtual Memory
14:32:07 [App     ] OS: Linux 4.4.0-21-generic (x86_64)
14:32:07 [App     ] SSE & AVX compatible CPU & OS detected
14:32:08 [App     ] Command line: scene_dense.mvs
14:32:12 [App     ] Scene loaded (4s234ms):
	11 images (11 calibrated) with a total of 15.81 MPixels (1.44 MPixels/image)
	1119125 points, 0 vertices, 0 faces
Points inserted 1119125 (100%, 2m23s556ms)           
Segmentation fault (core dumped)

**Comment by josefrcm** [comment]
I'm facing the same error. After much looking around, it seems to be a SSE/AVX alignment error in Eigen. Some threads for reference:

http://eigen.tuxfamily.org/bz/show_bug.cgi?id=862
http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1233

I have tried compiling without AVX to no avail, and as far a I know SSE is mandatory in x64. Maybe someone more knowledgeable can help.

**Comment by zhouliyang** [comment]
> ### Specifications like the version of the project, operating system, and hardware
> ubuntu16.04 eigen 3.2.10
> 
> ### Steps to reproduce the problem
> ~/openMVS_build/bin$ ./ReconstructMesh scene_dense.mvs
> 14:32:07 [App ] Build date: Sep 16 2019, 11:25:14
> 14:32:07 [App ] CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 cores)
> 14:32:07 [App ] RAM: 39.23GB Physical Memory 975.00MB Virtual Memory
> 14:32:07 [App ] OS: Linux 4.4.0-21-generic (x86_64)
> 14:32:07 [App ] SSE & AVX compatible CPU & OS detected
> 14:32:08 [App ] Command line: scene_dense.mvs
> 14:32:12 [App ] Scene loaded (4s234ms):
> 11 images (11 calibrated) with a total of 15.81 MPixels (1.44 MPixels/image)
> 1119125 points, 0 vertices, 0 faces
> Points inserted 1119125 (100%, 2m23s556ms)
> Segmentation fault (core dumped)

Just replace the assignment statement in Line 393, Plane.inl will fix the crash!
as following,
	// M.template topLeftCorner<3,4>() = m;
	M(0, 0) = m(0, 0); M(0, 1) = m(0, 1); M(0, 2) = m(0, 2); M(0, 3) = m(0, 3);
	M(1, 0) = m(1, 0); M(1, 1) = m(1, 1); M(1, 2) = m(1, 2); M(1, 3) = m(1, 3);
	M(2, 0) = m(2, 0); M(2, 1) = m(2, 1); M(2, 2) = m(2, 2); M(2, 3) = m(2, 3);
	Set(M, w, h, n, f);

**Comment by cdcseacave** [comment]
pls try the latest develop, I hope that works for you
