### ISSUE TITLE
DensifyPointCloud, std::bad_alloc, core dumped

### ISSUE THREAD

**Issue by lianghouhao** [cdcseacave/openMVS#477]
I got my msv file by using Opensfm firstly. When I tried to use DensifyPointCloud to do the dense reconstruction, there was a error for bad_alloc and core dumped. Can you help me how to figure it out?

Here is the error.

> DensifyPointCloud scene.mvs 
> 11:25:12 [App     ] Build date: Sep 18 2019, 21:31:04
> 11:25:12 [App     ] CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (2 cores)
> 11:25:12 [App     ] RAM: 9.74GB Physical Memory 2.00GB Virtual Memory
> 11:25:12 [App     ] OS: Linux 5.0.0-29-generic (x86_64)
> 11:25:12 [App     ] SSE & AVX compatible CPU & OS detected
> 11:25:12 [App     ] Command line: scene.mvs
> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc
> Aborted (core dumped)

Also, I tried to use Viewer to check the msv results, it said **LLVM ERROR: out of memory.**

Actually, I'm using a virtual Linux machine. I'm not sure whether the memory of ram matters?

Really appreciate for your help.

**Comment by cdcseacave** [comment]
The MVS file is not valid. Pls try something else for SfM reconstruction, like OpenMVG.

**Comment by lianghouhao** [comment]
> The MVS file is not valid. Pls try something else for SfM reconstruction, like OpenMVG.

Thanks!
