### ISSUE TITLE
what's the mean of  "ViewArr" in "Vertex"?

### ISSUE THREAD

**Issue by 478161648** [cdcseacave/openMVS#478]
hi,I think I can use the result from like orb_slam2 or ldso,I get the pointcloud ,poses,undistort images. 
I ran openmvg, but instead of using the sfm_data.bin file,I saved the vertices, camera's poses,and somethingelse to .txt file.finally,I used the Interface.h and filled the struct.And it worked. 
I noticed that there is a "ViewArr" in the "vertex", does it means a collection of  images which can extract this feature point? 
thank you, hope you can help me.

**Comment by cdcseacave** [comment]
stores the list of images seeing that 3d point

**Comment by 478161648** [comment]
> stores the list of images seeing that 3d point
Thank you,I will try it again.

**Comment by manthan99** [comment]
Hii
@478161648, I am also willing to do a similar thing. I want to use the output of ORB SLAM2(point cloud, poses and undistorted images). Can you let me know a few more detailed steps required to run this? Any help would be appreciated
