### ISSUE TITLE
Unable to make on last step

### ISSUE THREAD

**Issue by morgand536** [cdcseacave/openMVS#48]
My environment is Ubuntu 14.04 LTS 64-bit on vm sphere.
I am stuck with the make process of openMVS:

username@ubuntu:~/openMVS_Build$ make
[ 89%] Built target Common
[ 89%] Built target Math
[ 89%] Built target IO
[ 89%] Built target MVS
make[2]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/libGLU.so', needed by `bin/InterfaceOpenMVG'.  Stop.
make[1]: *** [apps/InterfaceOpenMVG/CMakeFiles/InterfaceOpenMVG.dir/all] Error 2
make: *** [all] Error 2

I have tried to install mesa but doesn't work.
Anyone can help? Thanks a lot!

**Comment by cdcseacave** [comment]
sorry you have problems, I'm not a linux user, but I know that if you follow exactly the build steps it works;
check the build steps on the wiki page

**Comment by morgand536** [comment]
I think i have followed all the steps before until i reached here.
Would it be an issue for Virtual Machine since there is no physical display card?

**Comment by cdcseacave** [comment]
the video card is not a problem for sure, I tested OpenMVS in a virtual machine too

**Comment by pyp22** [comment]
You need to install extra deps libglu. If running virtualbox you need to install vbox tools too for opengl. 
Cheers
Py
