### ISSUE TITLE
Use OpenMVS with SurfaceTrimmer from Poisson Reconstruction

### ISSUE THREAD

**Issue by sealiutree7** [cdcseacave/openMVS#480]
Hello, thank you for sharing such a powerful library. And sorry I don't know whether this question is stupid or not.
Since I want to use SurfaceTrimmer tool (SurfaceTrimmer.exe) from Poisson Reconstruction to modification my final refined_texture.ply file produced by OpenMVS to highlight my main object in the scene, there is a problem that my final head file of refined_texture.ply is lost an important information `property float value` that SurfaceTrimmer.exe need. From  [Poisson Usage age](http://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version10.02/)  the `property float value` stored the estimated depth values of the iso-surface vertices which may be produced by the reconstruction process with the option `--density`. 
My final head file of refined_texture.ply look likes:

> ply
format binary_little_endian 1.0
comment TextureFile model_dense_mesh_refine_texture.png
element vertex 16619
property float32 x
property float32 y
property float32 z
element face 32488
property list uint8 uint32 vertex_indices
property list uint8 float32 texcoord
end_header

And the need head file may look like:

> ply
format binary_little_endian 1.0
comment Running Screened Poisson Reconstruction (Version 8.0)
comment --in fused.ply
comment --out fusedoutx64.ply
comment --density
comment # Tree set in: 0.9 (s), 16.1 (MB)
comment # Constraints set in: 0.2 (s), 25.0 (MB)
comment # Linear system solved in: 0.8 (s), 26.2 (MB)
comment # Got triangles in: 0.3 (s), 27.5 (MB)
comment # Total Solve: 2.3 (s), 27.5 (MB)
element vertex 6015
property float x
property float y
property float z
property float value
element face 11901
property list uchar int vertex_indices
end_header

I wonder whether there is a way OpenMVS can add the `property float value` property to the file or something I can do to solve this problem. If you have any idea or I say something wrong, please don't refuse to offer your kind advice. Thanks a lot again.

**Comment by cdcseacave** [comment]
I think you are not using the right approach:
- do dense reconstruction and estimate also the point normals
- export dense point-cloud to a PLY file
- run Poisson lib to convert it to a mesh (read Poisson documentation on how to use the trimmer)
- continue OpenMVS, ex: `RefineMesh scene_dense.mvs --mesh-file poisson_mesh.ply`
