### ISSUE TITLE
How is the *texture.png generated?

### ISSUE THREAD

**Issue by caokui1221** [cdcseacave/openMVS#481]
Hi , @cdcseacave ,
I call `TextureMesh` to get a structure with texture. After this process, *texture.png is generated. I opened it, find it is composed of many independent small pictures.
Which confused me is:
In Maya or others modeling software, each vertex of the mesh has a corresponding pixel point in the texture image(uv mapping), but what is the correspondence of mesh and texture map generated by MVS, or, How is the *texture.png generated?
Thanks for you time.

**Comment by cdcseacave** [comment]
pls see the wiki
