### ISSUE TITLE
How to compute NCC score in OPENMVS

### ISSUE THREAD

**Issue by Leo-Lemon** [cdcseacave/openMVS#482]
I am learning openmvs, but it is very hard to understand how to compute pixel's NCC score when DENSE_NCC == DENSE_NCC_WEIGHTED and DENSE_SMOOTHNESS == DENSE_SMOOTHNESS_PLANE, what are the details of the algorithm? Can you recommend a paper on the algorithm?

Thanks very much

**Comment by cdcseacave** [comment]
It is hard to understand cause it is very optimized, otherwise there is nothing special about it, normal ZNCC with each pixel weighted by color and distance weight; I don't know any paper about it.
