### ISSUE TITLE
How to reproduce correct results on ETH3D multi-view data set?

### ISSUE THREAD

**Issue by PengYao1988** [cdcseacave/openMVS#484]
### Specifications like the version of the project, operating system, and hardware
OpenMVG+OpenMVS
### Steps to reproduce the problem
Dear researchers,
     While I am implementing OpenMVG+OpenMVS for reproducing the point cloud on ETH3D multi-view data set, I found that the number of vertexes of point clouds is much less (one order of magnitude less) than ground truth. At the same time, I also found that the distances between two same point clouds on ground truth and my own results are different (measured by using Meshlab). My question is, are there some parameters to control the scale of images or point clouds in OpenMVG or OpenMVS?

**Comment by cdcseacave** [comment]
Please find the used params in the comments of the OpenMVS submitted results. Also, pls note that OpenMVG was not used for this experiment.

**Comment by PengYao1988** [comment]
Thanks for your help!
