### ISSUE TITLE
What's the effect of the"Viewarry" in ReconstructMesh step and TextureMesh step?

### ISSUE THREAD

**Issue by rock0201** [cdcseacave/openMVS#486]

**Comment by cdcseacave** [comment]
if the views assigned to each point have gross outliers (wrong views) the densification/meshing stage will have big problems

**Comment by rock0201** [comment]
> if the views assigned to each point have gross outliers (wrong views) the densification/meshing stage will have big problems

Thank u for ur reply! Now I'm working on the DSO SLAM. I have gotten the 3D pointcloud and camera poses, but the viewarry is difficult to get.

**Comment by cdcseacave** [comment]
I do not know the internal structure of DSO, but there should be a way to know which pixels are viewed by which view; in the worst case scenario, if you do not figure this out, just set for each 3d point a view if the ray from that view to that point does not pass by near an other point (basically this approximates each point with a sphere, where the radius defines "near")

**Comment by rock0201** [comment]
> I do not know the internal structure of DSO, but there should be a way to know which pixels are viewed by which view; in the worst case scenario, if you do not figure this out, just set for each 3d point a view if the ray from that view to that point does not pass by near an other point (basically this approximates each point with a sphere, where the radius defines "near")

Wow! It's a great idea for me, giving me so many thoughts. Thank u so much! I 'm really appreciated!
