### ISSUE TITLE
Build halts with "invalid use of incomplete type" error on Debian

### ISSUE THREAD

**Issue by tokiop** [cdcseacave/openMVS#49]
Hi,

Having issues trying to install on Debian Stretch, using [latest instructions](https://github.com/cdcseacave/openMVS/blob/master/BUILD.md#linux-compilation).

Only added `-DCGAL_ROOT` for CGAL to be found on this system : `cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="$main_path/vcglib" -DCGAL_ROOT="/usr/lib/x86_64-linux-gnu/cmake/CGAL/" -DOpenCV_CAN_BREAK_BINARY_COMPATIBILITY=OFF`

The build halts with errors such as `error: invalid use of incomplete type ‘struct Eigen::internal::enable_if<false, SEACAVE::TPoint3<float>*>’` see full log here : [openmvs_build_log.txt](https://github.com/cdcseacave/openMVS/files/108138/openmvs_build_log.txt)

Is anyone familiar with these errors, and their meaning ?

Thanks for any clues, and for this project !

**Comment by cdcseacave** [comment]
Hi,

What version of Eigen are you using?

**Comment by tokiop** [comment]
thanks for your quick reply, cmake indicates `-- Found Eigen version 3.2.92: /usr/include/eigen3`.

Is this message from cmake normal, or it could be related ?
```
===============================================================
Disabling the use of Eigen as a sparse linear algebra library.
This does not affect the covariance estimation algorithm 
which can still use the EIGEN_SPARSE_QR algorithm.
===============================================================
```

**Comment by pmoulon** [comment]
This last message is shown by Ceres library and this is just a warning.

**Comment by tokiop** [comment]
Thanks ! Indeed, copy/pasted ceres' cmake result by error, nice catch..!

OpenMVS's cmake command to also use Eigen 3.2.92.

**Comment by pmoulon** [comment]
I noted on the Eigen website that Eigen latest stable version is 3.2.7.
You seems to use a non official release... (unstable)

**Comment by cdcseacave** [comment]
I agree with Pierre, please try the latest stable release of Eigen 3.2.7

**Comment by tokiop** [comment]
Thanks for your help both. Using latest stable Eigen 3.2.7, cmake complains because of Ceres' dependency to 3.2.92 : 

```
-- Eigen 3.2.7 found (include: /home/victor/bin/OpenMVS/eigen-2.7)
-- OpenCV 2.4.9.1 found (include: /usr/include/opencv;/usr/include;/usr/share/OpenCV/include)
-- CGAL 4.7 found (include: /usr/include)
-- VCG  found (include: /home/victor/bin/OpenMVS/vcglib)
CMake Error at /usr/local/lib/cmake/Ceres/CeresConfig.cmake:88 (message):
  Failed to find Ceres - Missing required Ceres dependency: Eigen version
  3.2.92, please set EIGEN_INCLUDE_DIR.
```
I guess it is not possible to mix Eigen versions, should I try downgrading Ceres also ?
Ceres is git version like indicated in BUILD.md.

**Comment by cdcseacave** [comment]
do not downgrate Ceres, just recompile it and install it again using the new Eigen lib 3.2.7

**Comment by tokiop** [comment]
Ideed, rebuilding fixed it, thanks again both for your dedication ! Will now build with OpenMVG importer and test the workflow further..

**Comment by pmoulon** [comment]
Don't hesitate to share your reconstructions on G+ with the hashtags openMVG openMVS
https://plus.google.com/u/0/s/openmvg%20openmvs/top ;-)
