### ISSUE TITLE
A bug when build on vs2015

### ISSUE THREAD

**Issue by zgaoooo** [cdcseacave/openMVS#495]
https://github.com/cdcseacave/openMVS/blob/494e006670f1f9a0b077ffea343d2216146929e6/libs/Common/Types.h#L641
i compile openmvs on windows system with vs2015, and it occur an error 

> C3249 illegal statement or subexpression of "constexpr" function 

i think there a clerical error
`constexpr int log2i(int val) {` 
should be 
`inline int log2i(int val) {`

**Comment by zgaoooo** [comment]
the same problem at line 631 
`constexpr T powi(T base, int exp) {`

**Comment by cdcseacave** [comment]
I do not have vs2015 to test, pls cehck the like 198 in Config.h, and why it does not work

**Comment by zgaoooo** [comment]
Thx, I read Config.h and I think the reason maybe  vs2015 partly support c++11.  i have no problem. thanks very much.

**Comment by Zhongpeike** [comment]
I also have this problem (using vs 2015) , and I've changed "constexpr" to "inline" at these two areas.

But now at file **noncopyable.hpp line 42** I have this bug:

_**"defaulted default constructor cannot be constexpr because the corresponding implicitly declared default constructor would not be constexpr"**_

```
41 #if !defined(BOOST_NO_CXX11_DEFAULTED_FUNCTIONS) && !defined(BOOST_NO_CXX11_NON_PUBLIC_DEFAULTED_FUNCTIONS)
42      BOOST_CONSTEXPR noncopyable() = default;
43      ~noncopyable() = default;
44 #else
45      noncopyable() {}
46      ~noncopyable() {}
47 #endif
```

**Comment by cdcseacave** [comment]
you will need to replace log2i and powi used in the code where are expected to be consts by the actual result; VC2015 is not supported anymore, pls use VC2017 or later is no C++ background
