### ISSUE TITLE
Problem with relative path using --working-folder when exporting with [-d|--outdir] undistorted images path from openMVG_main_openMVG2openMVS

### ISSUE THREAD

**Issue by DiegoRibeiro** [cdcseacave/openMVS#496]
### Specifications like the version of the project, operating system, and hardware
Ubuntu 19.04 Disco x86_64

### Steps to reproduce the problem
Execute the entire pipeline from openMVG:
SCENE_DIR=output/dataset
```
openMVG_main_SfMInit_ImageListing -d $DB_CAMERA -i $DEMO_ROOT/Dataset/ImageDataset_$DATASET_NAME/images -o $SCENE_DIR
```
```
openMVG_main_ComputeFeatures -i $SCENE_DIR/sfm_data.json -m AKAZE_FLOAT -p HIGH -o $SCENE_DIR
```
```
openMVG_main_ComputeMatches -i $SCENE_DIR/sfm_data.json -o $SCENE_DIR
```
```
openMVG_main_IncrementalSfM -i $SCENE_DIR/sfm_data.json -m $SCENE_DIR -o $SCENE_DIR
```
```
openMVG_main_ComputeSfM_DataColor -i $SCENE_DIR/sfm_data.json -o $SCENE_DIR/sfm_data_color.ply
```
```
openMVG_main_ComputeStructureFromKnownPoses -i $SCENE_DIR/sfm_data.json -m $SCENE_DIR -o $SCENE_DIR/robustFitting.json
```
```
openMVG_main_ExportUndistortedImages -i $SCENE_DIR/sfm_data.json -o $SCENE_DIR/undistortedImages
```
```
openMVG_main_openMVG2openMVS -i $SCENE_DIR/sfm_data.bin -d $SCENE_DIR/undistortedImages -o $SCENE_DIR/point_cloud.mvs
```

DensifyPointCloud -w ./output/dataset/ point_cloud.mvs

10:01:56 [App     ] Build date: Oct 21 2019, 11:22:55
10:01:56 [App     ] CPU: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 cores)
10:01:56 [App     ] RAM: 15.60GB Physical Memory 7.00GB Virtual Memory
10:01:56 [App     ] OS: Linux 5.0.0-32-generic (x86_64)
10:01:56 [App     ] SSE & AVX compatible CPU & OS detected
10:01:56 [App     ] Command line: -w ./output/dataset/ point_cloud.mvs
10:01:56 [App     ] Camera model loaded: platform 0; camera  0; f 2.267x2.267; poses 31
10:01:56 [App     ] error: failed loading image header
10:01:56 [App     ] error: failed reloading image '/home/user/dev/project_x/workspace/apis/wrap-server/<b>output/dataset/output/dataset</b>/undistortedImages/DSC_0009.JPG'
10:01:56 [App     ] error: invalid project

Note the bold on the log, my real path is: /home/user/dev/project_x/workspace/apis/wrap-server/output/dataset/undistortedImages/DSC_0009.JPG

This happens when i am specifying the path for my undistorted images for the command openMVG_main_openMVG2openMVS, the openMVS duplicate my relative path  if i am using the -w for the command DensifyPointCloud. Causing an invalid project. Should i report this issue to openMVG or its a openMVS bug? Or am i not using the pipeline correctly?

thanks

**Comment by cdcseacave** [comment]
it is something related to OpenMVG; OpenMVS project should store the images either in full path (not recomended), or relative path from the MVS file

**Comment by DiegoRibeiro** [comment]
I see, i fix my problem executing commands always on the same folder. i dont see a case where i should use working-dir.

Since im developing an api to go with openMVS, its annoying the logs on the root folder and can cause errors. Since two requests will override the depth maps. So my solution was to use "cwd <string> Current working directory" of the child process from node. So it will change the working dir for me and the logs go to my desired folder. i assume that the -w should have the same effect.

regards.
