### ISSUE TITLE
ubuntu 61.04: complie error

### ISSUE THREAD

**Issue by guoxiangzhou** [cdcseacave/openMVS#498]
.......
[ 70%] Linking CXX static library ../../lib/libMVS.a
[ 70%] Built target MVS
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so', needed by 'bin/InterfaceCOLMAP'.  Stop.
CMakeFiles/Makefile2:563: recipe for target 'apps/InterfaceCOLMAP/CMakeFiles/InterfaceCOLMAP.dir/all' failed
make[1]: *** [apps/InterfaceCOLMAP/CMakeFiles/InterfaceCOLMAP.dir/all] Error 2
Makefile:129: recipe for target 'all' 

How to solve???

**Comment by cdcseacave** [comment]
good question

**Comment by lrineau** [comment]
You just have to install the package that provides the file:
```shell
apt install libgl1-mesa-dev
```

**Comment by cdcseacave** [comment]
@lrineau thx for your help
@guoxiangzhou pls see wiki for how to build
