### ISSUE TITLE
Can I finish dense reconstruction with photos and known poses？

### ISSUE THREAD

**Issue by Alexsupernova** [cdcseacave/openMVS#502]
### Steps to reproduce the problem
I have  a series of photos，and also have a txt which stores the exactly poses (in metric units) in real world. How can I finish dense reconstruction by openMVS? Is it possible to do so, or how can I generate the .mvs file?

**Comment by cdcseacave** [comment]
sure, pls use the `Interface.h` tu fill in your data and save it to a file; see OpenMVG2OpenMVS example in OpenMVG
