### ISSUE TITLE
Save mvs file using SaveInterface

### ISSUE THREAD

**Issue by shawnliu007** [cdcseacave/openMVS#509]
Hello,

I'm trying to use Scene::SaveInterface() to save a mvs file that can be read by using libs/MVS/Interface.h. I found the vertex colors are not saved.

In https://github.com/cdcseacave/openMVS/blob/c0b7a6f3dbe2cd4b7e9e1ee6c6afe3f1af9ca36f/libs/MVS/Scene.cpp#L259, just wondering if it should be "!pointcloud.colors.IsEmpty()". Thanks!

**Comment by cdcseacave** [comment]
Hi, true, that is a bug, I fixed it in the latest develop, pls try it.
