### ISSUE TITLE
Typing in : "cmake .. -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT=/media/zeng/work/3DReconstruction/devel/vcglib", errors occur!

### ISSUE THREAD

**Issue by zengletian1491** [cdcseacave/openMVS#510]
Typing in : "cmake .. -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT=/media/zeng/work/3DReconstruction/devel/vcglib"

All the dependencies are installed correctly, but errors occur and results are listed in the following:
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:30 (cmake_policy):
  The OLD behavior for policy CMP0011 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

**CMake Error at CMakeLists.txt:31 (INCLUDE):
  INCLUDE could not find load file:

    build/Utils.cmake

CMake Error at CMakeLists.txt:37 (GetOperatingSystemArchitectureBitness):
  Unknown CMake command "GetOperatingSystemArchitectureBitness".**

**-- Configuring incomplete, errors occurred!
See also "/media/zeng/work/3DReconstruction/openMVS/build/CMakeFiles/CMakeOutput.log".**

Could you please give me some suggestions?Thanks!

**Comment by artemkurylev** [comment]
Hi ! Did you succeed  with this issue?

**Comment by Chauncywu1999** [comment]
After you download the openMVS project, the project folder will already have a folder named build, and Utils.cmake is already in there, DON'T DELETE IT, cd to the folder, and execute cmake in the origin build folder(you need to copy this folder in case of accident). 
![Screenshot 2024-05-20 174804](https://github.com/cdcseacave/openMVS/assets/44538024/d5d1d7bd-a599-432e-8408-deea575cb421)
❤️❤️❤️Wish you all the best
