### ISSUE TITLE
Make error: ‘class vcg::tri::TriEdgeCollapseQuadricParameter’ has no member named ‘BoundaryWeight’    pp.BoundaryWeight = 1;

### ISSUE THREAD

**Issue by zengletian1491** [cdcseacave/openMVS#511]
**On ubuntu16.04LTS,  the following commands are typed in:**

"cmake .. -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT=/media/zeng/work/3DReconstruction/vcglib -DOpenMVS_USE_CUDA=OFF -DBUILD_SHARED_LIBS=ON 
make"

**Errors occur as follows:**

**openMVS_develop/libs/MVS/Mesh.cpp:1000:6: error: ‘class vcg::tri::TriEdgeCollapseQuadricParameter’ has no member named ‘BoundaryWeight’
   pp.BoundaryWeight = 1; // the importance of the boundary during simplification: the value is in the range (0..+inf), default (1.0) means that the boundary has the same importance as the rest; values gr**

Could you please give me some suggestions?Thank you!

**Comment by zengletian1491** [comment]
The matching between VCG version  and openMVS version  is very important!
I solved this problem by the following comands:
1) downloading:
https://github.com/cdcseacave/VCG      （master version）
https://github.com/cdcseacave/openMVS （master version）
2)compiling openMVS
cmake .. -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT=/your/path/to/VCG_master  
make
sudo make install

**Comment by cdcseacave** [comment]
that is what the build doc recommends too
