### ISSUE TITLE
Unable to load scene when using RefineMesh

### ISSUE THREAD

**Issue by XinShengHUST** [cdcseacave/openMVS#513]
Hi! Thank you for sharing this awesome project! Lately I tried to use the Refinemesh application. I used the **openMVS_sample** provided by you as input. I tried to refine the coarse mesh with **scene_mesh.mvs**.   However it failed to load the scene. The output is given:

- 14:45:24 [App     ] Build date: Jan  6 2020, 14:32:29
- 14:45:24 [App     ] CPU: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
- 14:45:24 [App     ] RAM: 251.84GB Physical Memory 23.25GB Virtual Memory
- 14:45:24 [App     ] OS: Linux 3.16.0-30-generic (x86_64)
- 14:45:24 [App     ] SSE & AVX compatible CPU & OS detected
- 14:45:24 [App     ] Command line: /mnt/D/shengxin_exp/openMVS_build/openMVS_sample_master/scene_mesh.mvs

It turned out the code ended with EXIT_FAILURE in RefineMesh.cpp, line 227:	
```
if (!scene.Load(MAKE_PATH_SAFE(OPT::strInputFileName)))
    return EXIT_FAILURE;
```
The code is compiled on Ubuntu 16.04 and the DensifyPointCloud works well. How should I fix this problem? Thanks a lot!

**Comment by cdcseacave** [comment]
MVS project files in openMVS_sample might be old, pls rerun from begining

**Comment by cdcseacave** [comment]
I've also updated openMVS_sample to match the new binaries

**Comment by XinShengHUST** [comment]
> I've also updated openMVS_sample to match the new binaries

Thanks!
