### ISSUE TITLE
Viewer fails to display the texture of the obj model

### ISSUE THREAD

**Issue by Jessicayanyan** [cdcseacave/openMVS#514]
I have encountered with the problem of displaying the textures, while the viewer logs tells all the needed files were loaded successfully, including .obj of 5.4 GB, .mtl of  173 bytes and .jpg of 93.7 MB.
The Viewer module works normally when displaying .obj with a small .jpg textures images, is there any restricts setting about the texture image?
![Screenshot from 2020-01-07 22-28-04](https://user-images.githubusercontent.com/25864947/71902557-49712600-319d-11ea-98b0-1394193ef176.png)

**Comment by cdcseacave** [comment]
No, the only restrictions are the GPU card itself. The OBJ is it working with other mesh viewer, ex MeshLab?

**Comment by Angel0003** [comment]
> I have encountered with the problem of displaying the textures, while the viewer logs tells all the needed files were loaded successfully, including .obj of 5.4 GB, .mtl of 173 bytes and .jpg of 93.7 MB.
> The Viewer module works normally when displaying .obj with a small .jpg textures images, is there any restricts setting about the texture image?
> ![Screenshot from 2020-01-07 22-28-04](https://user-images.githubusercontent.com/25864947/71902557-49712600-319d-11ea-98b0-1394193ef176.png)

请问Viewer怎么查看.ply文件？用什么命令？

**Comment by cdcseacave** [comment]
no input
