### ISSUE TITLE
Generated obj from TextureMesh has invalid format as does not contain any normals but used index 0 for null normal index

### ISSUE THREAD

**Issue by tompollok** [cdcseacave/openMVS#516]
### Specifications like the version of the project, operating system, and hardware

While the save function supports exporting normals to an obj file, the resulting obj files that i get do not contain any normals. See https://github.com/cdcseacave/openMVS/blob/master/libs/IO/OBJ.cpp#L123

According to the documentation vertex normal indices should start at 1, but the vertice indices in the resulting obj files contain a 0 index, which can cause crashes on some obj readers, like the one from openscenegraph. (See discussion https://groups.google.com/forum/#!topic/osg-users/BBUYMYiWGl8) fixed with workaround in https://github.com/openscenegraph/OpenSceneGraph/commit/2b9c501e18b6eded7375c0e272aff401ad9793a2 

So there are two questions/options:

A) In case of no normals, just save faces to the obj as follows: 
f v1/vt1 v2/vt2 v3/vt3 ...  

instead of 

f v1/vt1/vn1 v2/vt2/vn2 v3/vt3/vn3 ...

B) Investigate, why there are no normals available. Is this intended behavior? @cdcseacave 

### Steps to reproduce the problem

I used a script using an openMVS artifact from September 2019. But i dont see any commits adressing this issue.

::These parameters are specific to computer

::Store current Directory:
set currDir=%CD%

::get folder name as variable
SET "MYDIR=%~p0"
set MYDIR1=%MYDIR:~0,-1%
for %%f in (%MYDIR1%) do set myfolder=%%~nxf

:: Set colmap directory (change this to where you've downloaded colmap, replace 'dev' with version number if necessary):
set colDir=E:\ReconstructionScript\COLMAP\colmap.exe

:: Set openMVS directory (change this to where you've downloaded openMVS)
set oMVS=E:\ReconstructionScript\OpenMVS

:: Set Working Directory (I create a temporary folder on my D drive to process data in)
set workDir=E:\ReconstructionScript\Data

:: mkdir %workDir% 
:: copy *.jpg %workDir%\ 
::cd /d %workDir%

%colDir% feature_extractor --database_path database.db --image_path .
%colDir% exhaustive_matcher --database_path database.db
mkdir sparse
%colDir% mapper --database_path %workDir%\database.db --image_path . --export_path %workDir%\sparse
%colDir% model_converter --input_path sparse\0 --output_path model.nvm --output_type NVM
%oMVS%\InterfaceVisualSFM.exe model.nvm
%oMVS%\DensifyPointCloud.exe model.mvs
%oMVS%\ReconstructMesh.exe model_dense.mvs
%oMVS%\RefineMesh.exe --resolution-level 1 model_dense_mesh.mvs
%oMVS%\TextureMesh.exe --empty-color 0 --export-type obj -o %myfolder%.obj model_dense_mesh_refine.mvs

**Comment by cdcseacave** [comment]
no normals are estimated for the mesh, so no normals to export
if you see a problem with the OBJ exporter, feel free to make a PR with the fix
