### ISSUE TITLE
DensifyPointCloud / error: failed loading image header / failing at jpeg_create_decompress

### ISSUE THREAD

**Issue by guipaiqigong** [cdcseacave/openMVS#521]
### Specifications like the version of the project, operating system, and hardware

CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 cores)
RAM: 8.00GB Physical Memory 8.00GB Virtual Memory
OS: Darwin 18.7.0 (x86_64)

opencv: 4.2.0
libjpeg: 9d

### Steps to reproduce the problem

I am trying to run the sample dataset from [openMVS_sample](https://github.com/cdcseacave/openMVS_sample) with: 
```
DensifyPointCloud scene.mvs
```

The output I got:
```
19:39:58 [App     ] Build date: Feb  4 2020, 18:41:47
19:39:58 [App     ] CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 cores)
19:39:58 [App     ] RAM: 8.00GB Physical Memory 8.00GB Virtual Memory
19:39:58 [App     ] OS: Darwin 18.7.0 (x86_64)
19:39:58 [App     ] SSE & AVX compatible CPU & OS detected
19:39:58 [App     ] Command line: scene.mvs
19:39:58 [App     ] Camera model loaded: platform 0; camera  0; f 1.054x1.054; poses 11
19:39:58 [App     ] Image loaded   0: 00000.jpg
19:39:58 [App     ] Image loaded   1: 00001.jpg
19:39:58 [App     ] Image loaded   2: 00002.jpg
19:39:58 [App     ] Image loaded   3: 00003.jpg
19:39:58 [App     ] Image loaded   4: 00004.jpg
19:39:58 [App     ] Image loaded   5: 00005.jpg
19:39:58 [App     ] Image loaded   6: 00006.jpg
19:39:58 [App     ] Image loaded   7: 00007.jpg
19:39:58 [App     ] Image loaded   8: 00008.jpg
19:39:58 [App     ] Image loaded   9: 00009.jpg
19:39:58 [App     ] Image loaded  10: 00010.jpg
19:39:58 [App     ] Scene loaded from interface format (9ms):
	11 images (11 calibrated) with a total of 63.22 MPixels (5.75 MPixels/image)
	12683 points, 0 vertices, 0 faces
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed reloading image '/Users/gdl/openMVS_sample/images/00008.jpg'
19:39:58 [App     ] error: failed reloading image '/Users/gdl/openMVS_sample/images/00004.jpg'
19:39:58 [App     ] error: failed reloading image '/Users/gdl/openMVS_sample/images/00006.jpg'
19:39:58 [App     ] error: failed reloading image '/Users/gdl/openMVS_sample/images/00010.jpg'
19:39:58 [App     ] error: failed reloading image '/Users/gdl/openMVS_sample/images/00002.jpg'
19:39:58 [App     ] error: failed reloading image '/Users/gdl/openMVS_sample/images/00007.jpg'
19:39:58 [App     ] error: failed loading image header
19:39:58 [App     ] error: failed reloading image '/Users/gdl/openMVS_sample/images/00009.jpg'
19:39:58 [App     ] error: failed reloading image '/Users/gdl/openMVS_sample/images/00000.jpg'
19:39:58 [App     ] error: preparing images for dense reconstruction failed (errors loading images)
```
I dug around and it seems like `jpeg_create_decompress` in `libs/IO/ImageJPG.cpp` is failing without any error messages.

### Possibly related:
#258: both uses libjpeg 9d.
#402: I tried both executing with `-w`/ in the directory where `scene.mvs` is saved. 

Could someone kindly give me some guidance on how to approch this? 😇
Thanks in advance!

**Comment by cdcseacave** [comment]
I saw this issue before many times and the problem as always a conflict of JPEG lib version (parts of the code are compile with some version and then linked statically to other parts of the code compiled with other version).

**Comment by guipaiqigong** [comment]
Thanks for your quick reply!

I confirmed that both openMVS and opencv are using the same JPEG lib from their cmake outputs:
openMVS:
```
-- Found JPEG: /usr/local/lib/libjpeg.dylib (found version "80") 
```

opencv:
```
JPEG:                /usr/local/lib/libjpeg.dylib (ver 80)
```
Could any other part of the library be compiled with a different JPEG version?

**Comment by stq054188** [comment]
> 我之前已经多次看到此问题，而且该问题始终是JPEG lib版本的冲突（部分代码用某个版本编译，然后静态链接到使用其他版本编译的代码的其他部分）。



> I saw this issue before many times and the problem as always a conflict of JPEG lib version (parts of the code are compile with some version and then linked statically to other parts of the code compiled with other version).

You are right，I have rebuilt opencv and openmvs with libjpeg 2.0.2 and ran DensifyPointCloud.exe it works, thanks.

D:\OpenCV_SFM_Dependency\OpenMVS\OpenMVS_Build\bin\vc15\x64\Release>DensifyPointCloud.exe -i out_0.mvs
19:36:26 [App     ] Build date: Mar 18 2020, 19:23:05
19:36:26 [App     ] CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 cores)
19:36:26 [App     ] RAM: 31.92GB Physical Memory 128.00TB Virtual Memory
19:36:26 [App     ] OS: Windows 8 x64
19:36:26 [App     ] SSE & AVX compatible CPU & OS detected
19:36:26 [App     ] Command line: -i out_0.mvs
19:36:26 [App     ] MapSMtoCores for SM 6.1 is undefined; default to use 128 cores/SM
19:36:26 [App     ] CUDA device 0 initialized: GeForce GTX 1070 (compute capability 6.1; memory 8.00GB)
19:36:27 [App     ] Camera model loaded: platform 0; camera  0; f 0.903x0.903; poses 7
19:36:27 [App     ] Image loaded   0: P1000965.JPG
19:36:27 [App     ] Image loaded   1: P1000966.JPG
19:36:27 [App     ] Image loaded   2: P1000967.JPG
19:36:27 [App     ] Image loaded   3: P1000968.JPG
19:36:27 [App     ] Image loaded   4: P1000969.JPG
19:36:27 [App     ] Image loaded   5: P1000970.JPG
19:36:27 [App     ] Image loaded   6: P1000971.JPG
19:36:27 [App     ] Scene loaded from interface format (7ms):
        7 images (7 calibrated) with a total of 5.25 MPixels (0.75 MPixels/image)
        1521 points, 0 vertices, 0 faces
19:36:27 [App     ] Preparing images for dense reconstruction completed: 7 images (25ms)
19:36:27 [App     ] Selecting images for dense reconstruction completed: 7 images (2ms)
Estimated depth-maps 7 (100%, 1m47s934ms)
Filtered depth-maps 7 (100%, 3s529ms)
Fused depth-maps 7 (100%, 689ms)
19:38:21 [App     ] Depth-maps fused and filtered: 7 depth-maps, 1612651 depths, 245994 points (15%) (2s996ms)
19:38:21 [App     ] Densifying point-cloud completed: 245994 points (1m54s522ms)
19:38:22 [App     ] Scene saved (621ms):
        7 images (7 calibrated)
        245994 points, 0 vertices, 0 faces
19:38:22 [App     ] Point-cloud saved: 245994 points (32ms)
19:38:22 [App     ] MEMORYINFO: {
19:38:22 [App     ]     PageFaultCount 652421
19:38:22 [App     ]     PeakWorkingSetSize 434.48MB
19:38:22 [App     ]     WorkingSetSize 143.23MB
19:38:22 [App     ]     QuotaPeakPagedPoolUsage 24.52MB
19:38:22 [App     ]     QuotaPagedPoolUsage 24.52MB
19:38:22 [App     ]     QuotaPeakNonPagedPoolUsage 2.95MB
19:38:22 [App     ]     QuotaNonPagedPoolUsage 2.94MB
19:38:22 [App     ]     PagefileUsage 272.43MB
19:38:22 [App     ]     PeakPagefileUsage 536.53MB
19:38:22 [App     ] } ENDINFO

**Comment by xqyd** [comment]
Simply remove the following lines from the CMakeLists.txt of OpenMVG
if (DEFINED OpenMVG_USE_INTERNAL_JPEG)
  message(STATUS "LIBJPEG (internal)")
else()
  message(STATUS "LIBJPEG (external)")
endif()

This will make the cmake to bypass the libjpeg and the jpeg stuff can be processed by OpenMVS like this:

CEREAL: (internal)
EIGEN: 3.3.4 (internal)
CERES: 1.13.0 (internal)
FLANN: 1.8.4 (internal)
LIBTIFF: 4.1.0 (external)
LIBPNG: 1.6.37 (external)
CLP: 1.16.10 (internal)
COINUTILS: 2.10.13 (internal)
OSI:  (internal)
LEMON: 1.3 (internal)

Notice the "LIBJPEG (external)" is GONE!
With this approach, I can finally use OpenMVG+OpenMVS without any problem.

**Comment by chn-lee-yumi** [comment]
> Simply remove the following lines from the CMakeLists.txt of OpenMVG
> if (DEFINED OpenMVG_USE_INTERNAL_JPEG)
> message(STATUS "LIBJPEG (internal)")
> else()
> message(STATUS "LIBJPEG (external)")
> endif()
> 
> This will make the cmake bypass the libjpeg and the jpeg stuff can be processed by OpenMVS like this:
> 
> CEREAL: (internal)
> EIGEN: 3.3.4 (internal)
> CERES: 1.13.0 (internal)
> FLANN: 1.8.4 (internal)
> LIBTIFF: 4.1.0 (external)
> LIBPNG: 1.6.37 (external)
> CLP: 1.16.10 (internal)
> COINUTILS: 2.10.13 (internal)
> OSI: (internal)
> LEMON: 1.3 (internal)
> 
> Notice the "LIBJPEG (external)" is GONE!
> With this approach, I can finally use OpenMVG+OpenMVS without any problem.

I tried but it doesn't work for me.

**Comment by citystrawman** [comment]
> > 我之前已经多次看到此问题，而且该问题始终是JPEG lib版本的冲突（部分代码用某个版本编译，然后静态链接到使用其他版本编译的代码的其他部分）。
> 
> > I saw this issue before many times and the problem as always a conflict of JPEG lib version (parts of the code are compile with some version and then linked statically to other parts of the code compiled with other version).
> 
> You are right，I have rebuilt opencv and openmvs with libjpeg 2.0.2 and ran DensifyPointCloud.exe it works, thanks.
> 
> D:\OpenCV_SFM_Dependency\OpenMVS\OpenMVS_Build\bin\vc15\x64\Release>DensifyPointCloud.exe -i out_0.mvs 19:36:26 [App ] Build date: Mar 18 2020, 19:23:05 19:36:26 [App ] CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 cores) 19:36:26 [App ] RAM: 31.92GB Physical Memory 128.00TB Virtual Memory 19:36:26 [App ] OS: Windows 8 x64 19:36:26 [App ] SSE & AVX compatible CPU & OS detected 19:36:26 [App ] Command line: -i out_0.mvs 19:36:26 [App ] MapSMtoCores for SM 6.1 is undefined; default to use 128 cores/SM 19:36:26 [App ] CUDA device 0 initialized: GeForce GTX 1070 (compute capability 6.1; memory 8.00GB) 19:36:27 [App ] Camera model loaded: platform 0; camera 0; f 0.903x0.903; poses 7 19:36:27 [App ] Image loaded 0: P1000965.JPG 19:36:27 [App ] Image loaded 1: P1000966.JPG 19:36:27 [App ] Image loaded 2: P1000967.JPG 19:36:27 [App ] Image loaded 3: P1000968.JPG 19:36:27 [App ] Image loaded 4: P1000969.JPG 19:36:27 [App ] Image loaded 5: P1000970.JPG 19:36:27 [App ] Image loaded 6: P1000971.JPG 19:36:27 [App ] Scene loaded from interface format (7ms): 7 images (7 calibrated) with a total of 5.25 MPixels (0.75 MPixels/image) 1521 points, 0 vertices, 0 faces 19:36:27 [App ] Preparing images for dense reconstruction completed: 7 images (25ms) 19:36:27 [App ] Selecting images for dense reconstruction completed: 7 images (2ms) Estimated depth-maps 7 (100%, 1m47s934ms) Filtered depth-maps 7 (100%, 3s529ms) Fused depth-maps 7 (100%, 689ms) 19:38:21 [App ] Depth-maps fused and filtered: 7 depth-maps, 1612651 depths, 245994 points (15%) (2s996ms) 19:38:21 [App ] Densifying point-cloud completed: 245994 points (1m54s522ms) 19:38:22 [App ] Scene saved (621ms): 7 images (7 calibrated) 245994 points, 0 vertices, 0 faces 19:38:22 [App ] Point-cloud saved: 245994 points (32ms) 19:38:22 [App ] MEMORYINFO: { 19:38:22 [App ] PageFaultCount 652421 19:38:22 [App ] PeakWorkingSetSize 434.48MB 19:38:22 [App ] WorkingSetSize 143.23MB 19:38:22 [App ] QuotaPeakPagedPoolUsage 24.52MB 19:38:22 [App ] QuotaPagedPoolUsage 24.52MB 19:38:22 [App ] QuotaPeakNonPagedPoolUsage 2.95MB 19:38:22 [App ] QuotaNonPagedPoolUsage 2.94MB 19:38:22 [App ] PagefileUsage 272.43MB 19:38:22 [App ] PeakPagefileUsage 536.53MB 19:38:22 [App ] } ENDINFO

Hi, I also encountered the same problem. Can you give me some details how you fixed this issue?
