### ISSUE TITLE
Help Reconstructing Smooth Objects

### ISSUE THREAD

**Issue by saisanthoshdav** [cdcseacave/openMVS#522]
### Specifications like the version of the project, operating system, and hardware
Pulled from openMVG and openMVS repo two weeks back
Ubuntu 18
Hardware -
Cameras in fixed position; object places on white background / floor; photos taken from multiple angles (angles are always the same due to fixed setup)

### Steps to reproduce the problem
Objects with smooth surfaces are not getting reconstructed correctly.

Firstly, I'll admit I only have high level understanding of the full openMVG + openMVS process - msot of the math goes above my head. 

### What I Am Trying To Do:
Reconstruct a soft drink bottle from 80 photos. Using script mentioned <a href="https://github.com/cdcseacave/openMVS_sample/blob/master/MvgMvs_Pipeline.py">here</a> for end to end reconsturction.

### What Is My Problem:
Output is not good, especially the portions where surfaces are plain.

### What I Have Tried:
Placing some markers on the rotating floor to help differentiate each pose. Output mesh still has lot of holes.

### Questions:
1) Is there a way I can do the mesh creation and texture creation from different data sets ? I have considered maybe marking the bottle so its not plain, have the mesh created correctly, then have the system use different set of images (assume the poses will be direct one to one mapping between both data sets) so they can be textured correctly. I have no idea how to do this.

2) Can I use a highly textured object to reconsturct a mesh, use the known poses of the camera for the new object (I know I can use the StructureFromKnownPoses for this, will have to figure out workflow) ? Will this improve the texture of smooth surfaced objects ?

3) Will having just newspapers on the ground matter for the textures of plain surfaces on the object ?

Any other suggestions on how to do this would also be greatly appreciated. Also, please let me know if it makes more sense to have this discussion on the openMVG repo.

Screenshot of output -

![Frooti](https://user-images.githubusercontent.com/10094226/73934955-80a23680-4905-11ea-9d37-967a077723d0.jpeg)

**Comment by cdcseacave** [comment]
As of today, photogrammetry has intrinsics limitations when it comes to textureless/transparent areas or specular/glossy surfaces. If that is your use case and you know you have a fixed setup you should seek to use a structured light setup that mitigates some of these issues.

If still want to use photogrammetry, then make sure the input data is extremely good:
- high resolution, sharp, clean (no noise) images
- good and constant illumination
- high image overlap (~80%)
- calibrate your fixed camera setup before

If you do all above right, you will get decent results even with a photogrammetry pipeline.

**Comment by saisanthoshdav** [comment]
Thank you for the suggestions.

By "calibrate your fixed camera setup before" are you referring to 1) Use a highly textured object 2) Use ConvertSfMDataFormat to get the json 3) Use that json for the new run ?

I will take the other suggestions and see if they improve the result in the meantime, thanks again.

**Comment by cdcseacave** [comment]
no, since the cameras do not move with respect of eachother, you can compute their position once, very accurate, using a calibration technique, like checkerboard, etc

**Comment by saisanthoshdav** [comment]
I am not entirely sure where I will feed the calibration information, can you elaborate on it a bit more or is there any code files I can look at to better understand this ?

Additionally, I have one last question that I previously mentioned - 
Can I use two image datasets withexact positions - one with newspaper wrapped around it to generate the mesh, one normal smooth to generate the textures.

**Comment by cdcseacave** [comment]
search the web for calibrating multiple cameras
yes, you can

**Comment by saisanthoshdav** [comment]
I got an improved mesh and used different set of images for the texture, seems to work for now. Will try out other suggestions for improving the quality, thanks for your time.
