### ISSUE TITLE
Illegal instruction (core dumped) for ReconstructMesh

### ISSUE THREAD

**Issue by mad-de** [cdcseacave/openMVS#53]
Ubuntu 15.10 most recent openmvs + openmvg Files: OpenMVG tutorial files (reconstruction global)

Commands:
$ cd ~/openMVS_build/bin
$ ./InterfaceOpenMVG -i /home/martin/openMVG_build/software/SfM/tutorial_out/reconstruction_global/sfm_data.json -o scene.mvs
$ ./DensifyPointCloud scene.mvs
$ ./ReconstructMesh scene_dense.mvs

Error:
Program received signal SIGILL, Illegal instruction.

DEBUG:
Starting program: /home/martin/openMVS_build/bin/ReconstructMesh scene_dense.mvs
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffde97c700 (LWP 6979)]
19:18:42 [App     ] Build date: Feb  2 2016, 18:18:28
19:18:42 [App     ] CPU: Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
19:18:42 [App     ] RAM: 3.86GB Physical Memory 4.00GB Virtual Memory
19:18:42 [App     ] OS: Linux 4.2.0-27-generic (x86_64)
19:18:42 [App     ] warning: no AVX compatible CPU or OS detected
19:18:42 [App     ] Command line: scene_dense.mvs
19:18:45 [App     ] Scene loaded (3s635ms):
	11 images (11 calibrated) with a total of 15.81 MPixels (1.44 MPixels/image)
	1828498 points, 0 vertices, 0 faces
19:19:04 [App     ] Delaunay tetrahedralization completed: 1828498 points -> 427713 vertices, 2737545 (+194) cells, 5475187 (+291) faces (18s439ms)
[New Thread 0x7fffda2d1700 (LWP 6985)]
[New Thread 0x7fffd9ad0700 (LWP 6986)]
[New Thread 0x7fffd92cf700 (LWP 6987)]
19:19:27 [App     ] Delaunay tetrahedras weighting completed: 2737739 cells, 5475478 faces (22s877ms)
19:19:38 [App     ] Delaunay tetrahedras graph-cut completed (6.17633e+06 flow): 296049 vertices, 595920 faces (11s223ms)
19:19:52 [App     ] Mesh reconstruction completed: 297871 vertices, 588624 faces (1m6s464ms)

Program received signal SIGILL, Illegal instruction.
0x000000000061442c in MVS::Mesh::Clean(float, float, bool, unsigned int, unsigned int, bool) ()
(gdb) bt full
#0  0x000000000061442c in MVS::Mesh::Clean(float, float, bool, unsigned int, unsigned int, bool) ()
No symbol table info available.
#1  0x000000000056667b in main ()
No symbol table info available.

**Comment by cdcseacave** [comment]
There seems to be a problem in using the VCG library. This does not happen with the version of VCG I have (the latest I think). In order to know more, you should either link to breakpad or compile in debug mode to see the full info.

**Comment by mad-de** [comment]
I did a svn checkout svn://svn.code.sf.net/p/vcg/code/trunk/vcglib vcglib just today. How do I link to breakpad?

Building in Debug mode fails unfortunately:
$ mkdir openMVS_Debug && cd openMVS_Debug
$ cmake . ../openMVS -DCMAKE_BUILD_TYPE=DEBUG -DVCG_DIR="~/vcglib" -DOpenCV_CAN_BREAK_BINARY_COMPATIBILITY=OFF -DOpenMVG_DIR:STRING="~/openMVG_build/openMVG_install/share/openMVG/cmake/"
$ sudo make install

Result:
libs/MVS/CMakeFiles/MVS.dir/build.make:119: recipe for target 'libs/MVS/CMakeFiles/MVS.dir/DepthMap.cpp.o' failed
make[2]: *** [libs/MVS/CMakeFiles/MVS.dir/DepthMap.cpp.o] Error 1
CMakeFiles/Makefile2:415: recipe for target 'libs/MVS/CMakeFiles/MVS.dir/all' failed
make[1]: *** [libs/MVS/CMakeFiles/MVS.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cdcseacave** [comment]
Install/build breakpad, and give the path to it during openmvs cmake

**Comment by mad-de** [comment]
Commands:
$ svn checkout http://google-breakpad.googlecode.com/svn/trunk/ Breakpad
$ cd Breakpad && ./configure
$ make
$ sudo make install
$ cd ..
$ mkdir openMVS_Debug && cd openMVS_Debug
$ cmake . ../openMVS -BREAKPAD_ROOT="~/Breakpad" -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="~/vcglib" -DOpenCV_CAN_BREAK_BINARY_COMPATIBILITY=OFF -DOpenMVG_DIR:STRING="~/openMVG_build/openMVG_install/share/openMVG/cmake/"

Results in:
[...]
-- WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
[...]
-- Build files have been written to: /home/martin/openMVS_Debug/REAKPAD_ROOT=~/Breakpad

It actually writes these files to the "openMVS_Debug/REAKPAD_ROOT=~" folder

Seems like I can't use anything starting with -B as cmake cuts that. 

Update: Turns out that breakpad has issues making as well, so the "minidump_file_writer.h" file is not built. I'm giving up for today - might look in this during the next days. Thanks for your help so far...

**Comment by mad-de** [comment]
Can you recommend a distribution and version that will work, this right now seems easier, then what I tried so far to get it running...

**Comment by cdcseacave** [comment]
I am using only windows for developing and testing OpenMVS, I'm afraid I can not help you with any other suggestion than switch to MS

**Comment by mad-de** [comment]
Update: running
$ sudo ./ReconstructMesh scene_dense.mvs

solved this issue for now and gives a valid output file.
