### ISSUE TITLE
Not able to reconstructMesh, visual c++ debug assert failed, COLMAP + OpenMVS

### ISSUE THREAD

**Issue by sixgjack** [cdcseacave/openMVS#531]
Hi guys, I'm using COLMAP3.5 & the lastest version of openMVS to perform 3d reconstruction on Windows 10 cmd, and I tried to use dense pointcloud produced by COLMAP and feed it into OpenMVS to do meshing. However, when I perform reconstructMesh with the .mvs file(produced by InterfaceCOLMAP) , after "Delaunay tetrahedralization completed", then the program went on to "Points Weighted"  part, and then during compilation, suddenly a message box poped out ,shown as follow:
![image](https://user-images.githubusercontent.com/47474043/75056862-cae50380-5512-11ea-9933-a31d703e8b30.png)

cmd output at the moment
![image](https://user-images.githubusercontent.com/47474043/75059829-b7d53200-5518-11ea-8013-0c41edf210a5.png)

No matter I ignored it, retry or terminate it, the program will soon terminate itself. Can anyone help me out with this problem??? Many thanks!!!

Additional information:
InterfaceCOLMAP.log
22:16:32 [App     ] Build date: Feb 21 2020, 18:49:25
22:16:32 [App     ] CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 cores)
22:16:32 [App     ] RAM: 15.93GB Physical Memory 128.00TB Virtual Memory
22:16:32 [App     ] OS: Windows 8 x64
22:16:32 [App     ] SSE & AVX compatible CPU & OS detected
22:16:32 [App     ] Command line: InterfaceCOLMAP -i E:\ie_fyp\COLMAP\COLMAP_Results\New_test_rezero\dense\0 -o test.mvs
22:16:32 [App     ] Reading cameras: E:/ie_fyp/COLMAP/COLMAP_Results/New_test_rezero/dense/0/sparse/cameras.txt
22:16:32 [App     ] Reading images: E:/ie_fyp/COLMAP/COLMAP_Results/New_test_rezero/dense/0/sparse/images.txt
22:16:36 [App     ] Reading points: E:/ie_fyp/COLMAP/COLMAP_Results/New_test_rezero/dense/0/fused.ply and E:/ie_fyp/COLMAP/COLMAP_Results/New_test_rezero/dense/0/fused.ply.vis
22:16:43 [App     ] Point-cloud loaded: 2941728 points (7s466ms)
22:17:50 [App     ] Exported data: 104 images & 2941728 vertices (1m17s464ms)
22:17:51 [App     ] MEMORYINFO: {
22:17:51 [App     ] 	PageFaultCount 465675
22:17:51 [App     ] 	PeakWorkingSetSize 1.03GB
22:17:51 [App     ] 	WorkingSetSize 14.72MB
22:17:51 [App     ] 	QuotaPeakPagedPoolUsage 216.84KB
22:17:51 [App     ] 	QuotaPagedPoolUsage 216.67KB
22:17:51 [App     ] 	QuotaPeakNonPagedPoolUsage 18.45KB
22:17:51 [App     ] 	QuotaNonPagedPoolUsage 17.52KB
22:17:51 [App     ] 	PagefileUsage 7.75MB
22:17:51 [App     ] 	PeakPagefileUsage 1.05GB
22:17:51 [App     ] } ENDINFO

**Comment by cdcseacave** [comment]
first of all you should compile in Release mode; if the problem persists, pls provide the input to debug

**Comment by cdcseacave** [comment]
you do not even need to build it yourself, the binaries are just one click away right on the main page in releases

**Comment by sixgjack** [comment]
Sorry, what do you mean by compile in release mode? Should I just delete everything in vcpkg/build and build it in release mode again?

changing the "debug" box into "release"?
![image](https://user-images.githubusercontent.com/47474043/75063398-cffc7f80-551f-11ea-96fa-d9b2ae57926d.png)

**Comment by sixgjack** [comment]
Problem solved! Thank you very much!!!!
