### ISSUE TITLE
Save the depthmap in pfm format

### ISSUE THREAD

**Issue by KeoChi** [cdcseacave/openMVS#532]
Hello! I use `depthData.depthMap.Save(ComposeDepthFilePath(idx, "depth.pfm"));`  to save the depthmap. Then I load the *.pfm and show the depth image. I find that the image is upside down. Why? Can you explain why?

**Comment by cdcseacave** [comment]
that is how the PFM format is defined: http://netpbm.sourceforge.net/doc/pfm.html
