### ISSUE TITLE
colmap densifypointcloud result vs openmvs densifypointcloud result

### ISSUE THREAD

**Issue by yuancaimaiyi** [cdcseacave/openMVS#533]
@cdcseacave Hi,sorry to bother you!
data :1280*720 images
openmvs edition  :the master (Latest)
the result of colmap is as follow(I modified the colmap code to generate only dense point clouds on the ground):
![colmap](https://user-images.githubusercontent.com/28293910/75835653-68391500-5dfa-11ea-936e-1d34473ed458.png)
I use the colmap generate the sparse model,and then use openmvs DensifyPointCloud ,the resolution set is  0 (I do not scale down images),the result is as follow:
![openmvs](https://user-images.githubusercontent.com/28293910/75835873-104ede00-5dfb-11ea-8794-66836ccfc17f.png)
As you can see, both colmap and openmvs use the same pose. The point cloud on the ground of openmvs is obviously less than colmap. I also saw the depth map of openmvs, and the result is not very good. Is my image resolution too low? But 1280 * 720 is not low

**Comment by cdcseacave** [comment]
can u pls provide the original images? (not the undistorted ones)

**Comment by yuancaimaiyi** [comment]
@cdcseacave Because the image is too large, I sent  about 100 images  to your email(cdc.seacave@gmail.com). (undistorted images and Camera parameter）

**Comment by cdcseacave** [comment]
I specifically asked original image, not undistorted

**Comment by yuancaimaiyi** [comment]
@cdcseacave Sorry, I didn't send you the original image at the beginning ,send u email the original image(not undistorted)

**Comment by cdcseacave** [comment]
I did not receive anything, pls post the link to the images here

**Comment by rennu** [comment]
Tip: You could use google drive or a service like we transfer to send the files https://wetransfer.com/.

**Comment by yuancaimaiyi** [comment]
@cdcseacave @rennu  I  send the files https://wetransfer.com/ and send to your  email

**Comment by cdcseacave** [comment]
@yuancaimaiyi I did receive the link, but I am not sure I understand which is the input to OpenMVS: which are the images and which is the sparse point cloud + cameras?

**Comment by yuancaimaiyi** [comment]
@cdcseacave  openmvs input is colmap  generate sparse model ,and I fllow the issue   https://github.com/cdcseacave/openMVS/issues/360 to use the InterfaceCOLMAP ,the result is picture2 above ,but the colmap directly generate the dense point cloud is the picture1 above .

**Comment by cdcseacave** [comment]
sry, your data does not contain any of the above, I'll close this issue as I find it very difficult to interact with you
