### ISSUE TITLE
CMake Error in Windows for OpenMVG_DIR

### ISSUE THREAD

**Issue by morgand536** [cdcseacave/openMVS#54]
I am trying to install OpenMVG + OpenMVS in Windows 10 + VS2013.
However, when i was in the last step of cmaking the openMVS, i got this error and i could not get rid of it:

_CMake Error at C:/openMVG/bin/install/share/openMVG/cmake/OpenMVGTargets.cmake:34 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: zlib

  Targets not yet defined:
  lib_CoinUtils;lib_Osi;lib_clp;lib_OsiClpSolver;stlplus;lemon;jpeg;png;tiff;cxsparse;ceres;flann_cpp_s;easyexif;openMVG_features;openMVG_image;openMVG_lInftyComputerVision;openMVG_matching;openMVG_kvld;openMVG_matching_image_collection;openMVG_multiview;openMVG_numeric;openMVG_system;openMVG_sfm;vlsift

Call Stack (most recent call first):
  C:/openMVG/bin/install/share/openMVG/cmake/OpenMVGConfig.cmake:96 (INCLUDE)
  apps/InterfaceOpenMVG/CMakeLists.txt:1 (FIND_PACKAGE)_

The configuring was incomplete and i could not generate the .sln.

**Comment by cdcseacave** [comment]
I'd like to help you, but it seems more like a problem in OpenMVG as far as I can tell.

**Comment by cdcseacave** [comment]
Any news about this issue?
