### ISSUE TITLE
DensifyPointCloud doesn't generate valid scene_dense.mvs 

### ISSUE THREAD

**Issue by Lsz-20** [cdcseacave/openMVS#540]
I am trying to use different photos to generate point cloud data，some are right but others have some problems，and I can't get scene_dense.mvs（Is there not enough memory？）
### 
17:31:12 [App     ] Build date: Mar  5 2020, 11:43:11
17:31:12 [App     ] CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 cores)
17:31:12 [App     ] RAM: 7.90GB Physical Memory 128.00TB Virtual Memory
17:31:12 [App     ] OS: Windows 8 x64
17:31:12 [App     ] SSE & AVX compatible CPU & OS detected
17:31:12 [App     ] Command line: F:\Opencv\IMG\MVS\scene.mvs
17:31:12 [App     ] Camera model loaded: platform 0; camera  0; f 1.270x1.270; poses 51
17:31:12 [App     ] Image loaded   0: DSC_0859.JPG
17:31:12 [App     ] Image loaded   1: DSC_0860.JPG
17:31:12 [App     ] Image loaded   2: DSC_0861.JPG
·····
17:31:12 [App     ] Image loaded  49: DSC_0912.JPG
17:31:12 [App     ] Image loaded  50: DSC_0913.JPG
17:31:12 [App     ] Scene loaded from interface format (116ms):
        51 images (51 calibrated) with a total of 122.03 MPixels (2.39 MPixels/image)
        9020 points, 0 vertices, 0 faces
17:31:13 [App     ] Preparing images for dense reconstruction completed: 51 images (427ms)
17:31:13 [App     ] Selecting images for dense reconstruction completed: 51 images (14ms)
Estimated depth-maps 51 (100%, 16s454ms)
Filtered depth-maps 51 (100%, 32s964ms)

### Steps to reproduce the problem
①openMVG_main_openMVG2openMVS -i F:\Opencv\IMG\build\reconstruction\sfm_data.bin -o F:\Opencv\IMG\MVS\scene.mvs -d F:\Opencv\IMG\MVS
②DensifyPointCloud F:\Opencv\IMG\MVS\scene.mvs
Thanks

**Comment by cdcseacave** [comment]
it is possible to tun out of memory, you can monitor the memory status while you run it

and you can also use `--resolution-level 2` or more as a parameter for densification

**Comment by Lsz-20** [comment]
> 可以调出内存，可以在运行时监视内存状态
> 
> 并且您也可以使用`--resolution-level 2`或更多参数作为致密化参数

Thanks for your advice. I'll give it a try

**Comment by Lsz-20** [comment]
> 可以调出内存，可以在运行时监视内存状态
> 
> 并且您也可以使用`--resolution-level 2`或更多参数作为致密化参数

I can get scene_dense.mvs now,but when I run the "ReconstructMesh” it shows：
22:22:06 [App     ] Build date: Mar  5 2020, 11:43:11
22:22:06 [App     ] CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 cores)
22:22:06 [App     ] RAM: 7.90GB Physical Memory 128.00TB Virtual Memory
22:22:06 [App     ] OS: Windows 8 x64
22:22:06 [App     ] SSE & AVX compatible CPU & OS detected
22:22:06 [App     ] Command line: S:\IMG\MVS\scene_dense.mvs
22:22:06 [App     ] Scene loaded (2ms):
        57 images (47 calibrated) with a total of 134.47 MPixels (2.86 MPixels/image)
        0 points, 0 vertices, 0 faces
Points inserted 0 (100%, 0ms)

**Comment by Lsz-20** [comment]
> 可以调出内存，可以在运行时监视内存状态
> 
> 并且您也可以使用`--resolution-level 2`或更多参数作为致密化参数

I can get scene_dense.mvs now,but when I run the "ReconstructMesh” it shows：
22:22:06 [App     ] Build date: Mar  5 2020, 11:43:11
22:22:06 [App     ] CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 cores)
22:22:06 [App     ] RAM: 7.90GB Physical Memory 128.00TB Virtual Memory
22:22:06 [App     ] OS: Windows 8 x64
22:22:06 [App     ] SSE & AVX compatible CPU & OS detected
22:22:06 [App     ] Command line: S:\IMG\MVS\scene_dense.mvs
22:22:06 [App     ] Scene loaded (2ms):
        57 images (47 calibrated) with a total of 134.47 MPixels (2.86 MPixels/image)
        0 points, 0 vertices, 0 faces
Points inserted 0 (100%, 0ms)

Is this also a memory problem？Thanks

**Comment by cdcseacave** [comment]
no, the dense point cloud seems empty

**Comment by Lsz-20** [comment]
> 不，密集的点云似乎是空的

Is the DensifyPointCloud operation failing?It seems success？
17:18:33 [App     ] Build date: Mar  5 2020, 11:43:11
17:18:33 [App     ] CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 cores)
17:18:33 [App     ] RAM: 7.90GB Physical Memory 128.00TB Virtual Memory
17:18:33 [App     ] OS: Windows 8 x64
17:18:33 [App     ] SSE & AVX compatible CPU & OS detected
17:18:33 [App     ] Command line: C:\IMG\MVS\scene.mvs
17:18:33 [App     ] Camera model loaded: platform 0; camera  0; f 0.834x0.834; poses 47
17:18:33 [App     ] Image loaded   0: IMG_3811.JPG
17:18:33 [App     ] Image loaded   1: IMG_3812.JPG
17:18:33 [App     ] Image loaded   2: IMG_3813.JPG
·····
17:18:33 [App     ] warning: uncalibrated image 'C:\IMG\MVS\IMG_3859.JPG'
·····
17:18:33 [App     ] warning: uncalibrated image 'C:\IMG\MVS\IMG_3868.JPG'
17:18:33 [App     ] Image loaded  52: IMG_3869.JPG
·····
17:18:33 [App     ] Scene loaded from interface format (180ms):
        57 images (47 calibrated) with a total of 537.87 MPixels (11.44 MPixels/image)
        31525 points, 0 vertices, 0 faces
17:18:35 [App     ] Preparing images for dense reconstruction completed: 57 images (2s122ms)
17:18:35 [App     ] Selecting images for dense reconstruction completed: 47 images (37ms)
Estimated depth-maps 47 (100%, 17s167ms)
Filtered depth-maps 47 (100%, 18s744ms)
Fused depth-maps 47 (100%, 624ms)
17:19:14 [App     ] Depth-maps fused and filtered: 47 depth-maps, 0 depths, 0 points (-2147483648%) (2s579ms)
17:19:14 [App     ] Densifying point-cloud completed: 0 points (40s911ms)
17:19:14 [App     ] Scene saved (4ms):
        57 images (47 calibrated)
        0 points, 0 vertices, 0 faces
17:19:14 [App     ] MEMORYINFO: {
17:19:14 [App     ]     PageFaultCount 7174081
17:19:14 [App     ]     PeakWorkingSetSize 3.07GB
17:19:14 [App     ]     WorkingSetSize 415.00MB
17:19:14 [App     ]     QuotaPeakPagedPoolUsage 131.33KB
17:19:14 [App     ]     QuotaPagedPoolUsage 127.05KB
17:19:14 [App     ]     QuotaPeakNonPagedPoolUsage 44.48KB
17:19:14 [App     ]     QuotaNonPagedPoolUsage 19.38KB
17:19:14 [App     ]     PagefileUsage 1.18GB
17:19:14 [App     ]     PeakPagefileUsage 4.12GB
17:19:14 [App     ] } ENDINFO

Thanks

**Comment by cdcseacave** [comment]
you are doing something wrong in SfM most probably

just use https://github.com/cdcseacave/openMVS/blob/master/MvgMvsPipeline.py

**Comment by Lsz-20** [comment]
> 您很可能在SfM中做错了
> 
> 只需使用https://github.com/cdcseacave/openMVS/blob/master/MvgMvsPipeline.py

According to your suggestion, I have checked the process of SFM generation for many times, confirmed that there is no problem, and tried the previous successful image examples. Unfortunately, the original successful image also has the same situation now, which makes it impossible to proceed
This problem troubles me very much

**Comment by cdcseacave** [comment]
pls share the original images

**Comment by Lsz-20** [comment]
> 请分享原始图片
By mail to you (*^__^*)

**Comment by cdcseacave** [comment]
didn't not receive it, pls post a link here

**Comment by Lsz-20** [comment]
> 没有收到，请在此处发布链接
https://pan.baidu.com/s/1TMWUmfz6XSN0xlHNVcycxw （vcmo）

**Comment by cdcseacave** [comment]
all works just fine as you can see:

![demo](https://user-images.githubusercontent.com/2802670/76685852-833c2e00-661f-11ea-8873-f34294d3a985.gif)

**Comment by Lsz-20** [comment]
> all works just fine as you can see:
> 
> ![demo](https://user-images.githubusercontent.com/2802670/76685852-833c2e00-661f-11ea-8873-f34294d3a985.gif)

As your image shows, the image did succeed before, but now I'm using the same steps again to manipulate the image, and the error occurs

**Comment by cdcseacave** [comment]
I'm sorry I do not understand what you want

**Comment by Lsz-20** [comment]
If there are no errors in the image set in your opinion, is there a problem with openMVG?
(What puzzles me is why the same operation now has problems with ReconstructMesh)

**Comment by Lsz-20** [comment]
Maybe I'll try to reinstall it

**Comment by Lsz-20** [comment]
Thanks for your help. I reinstalled openMVS and tried it. Everything went well.It seems to me that the 'DensifyPointCloud' partially crashed earlier and failed to produce valid data.This seems to be the problem after I try to run a larger data set.
