### ISSUE TITLE
How to use Viewer to view xxx.mvs

### ISSUE THREAD

**Issue by Lsz-20** [cdcseacave/openMVS#543]
I'm trying to use the Viewer command line to open xxx.mvs,but it shows : The 'Viewer' is not an internal or external command, nor is it a runnable program or batch file
Thanks

**Comment by cdcseacave** [comment]
pls compile it

**Comment by Lsz-20** [comment]
As you said，I have compile it,and I can find Viewer file at : .\openMVS\newbuild\apps,but it also show the same problem?

**Comment by Lsz-20** [comment]
Wasn't the Viewer compiled with openMVS?
Thanks

**Comment by Lsz-20** [comment]
Wasn't the Viewer compiled together with openMVS?
Thanks

**Comment by cdcseacave** [comment]
it is, pls follow the build instruction in Wiki
