### ISSUE TITLE
Add vcpkg installation instructions

### ISSUE THREAD

**Issue by NancyLi1013** [cdcseacave/openMVS#544]
`OpenMVS `is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for openmvs and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build openmvs, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Windows: x86, x64) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and here is what the port script looks like. We try to keep the library maintained as close as possible to the original library.

I'm trying to add vcpkg installation instructions but I couldn't find the related docs in code item except for on `Wiki `page.

Could you please help add the following contents to this port?

```
Installing and building openmvs via vcpkg

You can download and install raylib using the [vcpkg](https://github.com/Microsoft/vcpkg) dependency manager:

      git clone https://github.com/Microsoft/vcpkg.git
      cd vcpkg
      ./bootstrap-vcpkg.sh
      ./vcpkg integrate install
      vcpkg install openmvs

The openmvs port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please [create an issue or pull request](https://github.com/Microsoft/vcpkg) on the vcpkg repository.
```
The similar pull request like this https://github.com/electronicarts/EASTL/pull/337

Thanks,
Nancy

**Comment by cdcseacave** [comment]
In my opinion the build instruction in the Wiki are detailed and complete. What is missing?

**Comment by NancyLi1013** [comment]
Hi @cdcseacave 
Thanks for your response.
It seems that the build instructions in the Wiki are for the dependency ports to install and `openmvs `to build via vcpkg.
Personally, It might be better to add both install and build instructions for `openmvs `via vcpkg.
I also noticed that there are no descriptions about how to get vcpkg.

**Comment by cdcseacave** [comment]
Ho to get/install/use vcpkg is not an OpenMVS topic, and is in detailed explained in the vcpkg documentation. As for OpenMVS, I encourage to compile it outside vcpkg so that you can tinker with tho code or even contribute with an improved algorithm, etc.

**Comment by NancyLi1013** [comment]
Thanks for your description about this.
