### ISSUE TITLE
make error in ubuntu16.04

### ISSUE THREAD

**Issue by tftangming** [cdcseacave/openMVS#548]
when i start to make the project, some problem occurs!!

tangming@HP-Pavilion:~/openMVS_build$ make -j2 && sudo make install
[  3%] Building CXX object libs/Common/CMakeFiles/Common.dir/CUDA.cpp.o
[  3%] Building CXX object libs/Common/CMakeFiles/Common.dir/Common.cpp.o
In file included from /home/tangming/openMVS/libs/Common/Common.h:176:0,
                 from /home/tangming/openMVS/libs/Common/Common.cpp:12:
/home/tangming/openMVS/libs/Common/Types.h:1488:70: error: ‘cv::Matx_DivOp’ has not been declared
  TMatrix(const TMatrix<TYPE,m,n>& a, const TMatrix<TYPE,m,n>& b, cv::Matx_DivOp) : Base(a, b, cv::Ma
                                                                      ^
/home/tangming/openMVS/libs/Common/Types.h: In constructor ‘SEACAVE::TMatrix<TYPE, m, n>::TMatrix(const SEACAVE::TMatrix<TYPE, m, n>&, const SEACAVE::TMatrix<TYPE, m, n>&, int)’:
/home/tangming/openMVS/libs/Common/Types.h:1488:95: error: ‘Matx_DivOp’ is not a member of ‘cv’
 rix(const TMatrix<TYPE,m,n>& a, const TMatrix<TYPE,m,n>& b, cv::Matx_DivOp) : Base(a, b, cv::Matx_Di
                                                                                          ^
/home/tangming/openMVS/libs/Common/Types.h: In member function ‘bool SEACAVE::TColor<TYPE>::operator==(const SEACAVE::TColor<TYPE>&) const [with TYPE = unsigned char]’:
/home/tangming/openMVS/libs/Common/Types.h:2080:108: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  bool TColor<uint8_t>::operator==(const TColor& col) const { return (*((const uint32_t*)c) == *((con
                                                                                          ^
/home/tangming/openMVS/libs/Common/Types.h:2080:137: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 operator==(const TColor& col) const { return (*((const uint32_t*)c) == *((const uint32_t*)col.c)); }
                                                                                                ^
/home/tangming/openMVS/libs/Common/Types.h: In member function ‘bool SEACAVE::TColor<TYPE>::operator!=(const SEACAVE::TColor<TYPE>&) const [with TYPE = unsigned char]’:
/home/tangming/openMVS/libs/Common/Types.h:2081:108: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  bool TColor<uint8_t>::operator!=(const TColor& col) const { return (*((const uint32_t*)c) != *((con
                                                                                          ^
/home/tangming/openMVS/libs/Common/Types.h:2081:137: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 operator!=(const TColor& col) const { return (*((const uint32_t*)c) != *((const uint32_t*)col.c)); }
                                                                                                ^
/home/tangming/openMVS/libs/Common/Types.h: In member function ‘uint32_t SEACAVE::TColor<TYPE>::toDWORD() const [with TYPE = unsigned char; uint32_t = unsigned int]’:
/home/tangming/openMVS/libs/Common/Types.h:2082:91: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 template <> inline uint32_t TColor<uint8_t>::toDWORD() const { return *((const uint32_t*)c); }
                                                                                           ^
In file included from /home/tangming/openMVS/libs/Common/Common.h:176:0,
                 from /home/tangming/openMVS/libs/Common/CUDA.cpp:8:
/home/tangming/openMVS/libs/Common/Types.h:1488:70: error: ‘cv::Matx_DivOp’ has not been declared
  TMatrix(const TMatrix<TYPE,m,n>& a, const TMatrix<TYPE,m,n>& b, cv::Matx_DivOp) : Base(a, b, cv::Matx_DivOp()) {}
                                                                      ^
/home/tangming/openMVS/libs/Common/Types.h: In constructor ‘SEACAVE::TMatrix<TYPE, m, n>::TMatrix(const SEACAVE::TMatrix<TYPE, m, n>&, const SEACAVE::TMatrix<TYPE, m, n>&, int)’:
/home/tangming/openMVS/libs/Common/Types.h:1488:95: error: ‘Matx_DivOp’ is not a member of ‘cv’
  TMatrix(const TMatrix<TYPE,m,n>& a, const TMatrix<TYPE,m,n>& b, cv::Matx_DivOp) : Base(a, b, cv::Matx_DivOp()) {}
                                                                                               ^
/home/tangming/openMVS/libs/Common/Types.h: In member function ‘bool SEACAVE::TColor<TYPE>::operator==(const SEACAVE::TColor<TYPE>&) const [with TYPE = unsigned char]’:
/home/tangming/openMVS/libs/Common/Types.h:2080:108: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 template <> inline bool TColor<uint8_t>::operator==(const TColor& col) const { return (*((const uint32_t*)c) == *((const uint32_t*)col.c)); }
                                                                                                            ^
/home/tangming/openMVS/libs/Common/Types.h:2080:137: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 template <> inline bool TColor<uint8_t>::operator==(const TColor& col) const { return (*((const uint32_t*)c) == *((const uint32_t*)col.c)); }
                                                                                                                                         ^
/home/tangming/openMVS/libs/Common/Types.h: In member function ‘bool SEACAVE::TColor<TYPE>::operator!=(const SEACAVE::TColor<TYPE>&) const [with TYPE = unsigned char]’:
/home/tangming/openMVS/libs/Common/Types.h:2081:108: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 template <> inline bool TColor<uint8_t>::operator!=(const TColor& col) const { return (*((const uint32_t*)c) != *((const uint32_t*)col.c)); }
                                                                                                            ^
/home/tangming/openMVS/libs/Common/Types.h:2081:137: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 template <> inline bool TColor<uint8_t>::operator!=(const TColor& col) const { return (*((const uint32_t*)c) != *((const uint32_t*)col.c)); }
                                                                                                                                         ^
/home/tangming/openMVS/libs/Common/Types.h: In member function ‘uint32_t SEACAVE::TColor<TYPE>::toDWORD() const [with TYPE = unsigned char; uint32_t = unsigned int]’:
/home/tangming/openMVS/libs/Common/Types.h:2082:91: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 template <> inline uint32_t TColor<uint8_t>::toDWORD() const { return *((const uint32_t*)c); }
                                                                                           ^
libs/Common/CMakeFiles/Common.dir/build.make:62: recipe for target 'libs/Common/CMakeFiles/Common.dir/Common.cpp.o' failed
make[2]: *** [libs/Common/CMakeFiles/Common.dir/Common.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....
libs/Common/CMakeFiles/Common.dir/build.make:75: recipe for target 'libs/Common/CMakeFiles/Common.dir/CUDA.cpp.o' failed
make[2]: *** [libs/Common/CMakeFiles/Common.dir/CUDA.cpp.o] Error 1
CMakeFiles/Makefile2:149: recipe for target 'libs/Common/CMakeFiles/Common.dir/all' failed
make[1]: *** [libs/Common/CMakeFiles/Common.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

If the opencv has some problem?

**Comment by cdcseacave** [comment]
closing as not even the min info requested in the template was not given

**Comment by xianweilv** [comment]
@tftangming I have the same problem, have you solved it?

**Comment by ayu1121** [comment]
我也遇到了，该怎么解决呢

**Comment by ZhangJchong** [comment]
Hi,my freind,I have the same problem, have you solved it? thanks?

**Comment by NameHaoZhang** [comment]
> 我也遇到了，该怎么解决呢

兄弟你后来怎么解决这个make error的呢？

**Comment by ayu1121** [comment]
太久了，我都忘记是什么问题了 On 03/05/2021 11:40, Hao Zhang wrote: 



我也遇到了，该怎么解决呢



兄弟你后来怎么解决这个make error的呢？



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/cdcseacave/openMVS/issues/548#issuecomment-791128944",

"url": "https://github.com/cdcseacave/openMVS/issues/548#issuecomment-791128944",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by DJever23** [comment]
> @tftangming I have the same problem, have you solved it?

我也遇到了这个问题，已经结局了吗? I have the same problem, have you solved it?thank you

**Comment by DJever23** [comment]
> > 我也遇到了，该怎么解决呢
> 
> 兄弟你后来怎么解决这个make error的呢？

这个问题解决了吗，现在我也遇到了这个问题

**Comment by curehabit** [comment]
> > > 我也遇到了，该怎么解决呢
> > 
> > 
> > 兄弟你后来怎么解决这个make error的呢？
> 
> 这个问题解决了吗，现在我也遇到了这个问题

我也遇到了，我带cuda编译报错，关了cuda标志就报这个了，你解决了吗？

**Comment by curehabit** [comment]
> > > 我也遇到了，该怎么解决呢
> > 
> > 
> > 兄弟你后来怎么解决这个make error的呢？
> 
> 这个问题解决了吗，现在我也遇到了这个问题

我应该解决这个问题了，opencv版本太老了，装了目前最新的3.4没有这个报错了，但是还有个InterfaceCOLMAP的错误没搞定。
Install opencv 3.4 solved this problem, opencv2.4 is too old.
