### ISSUE TITLE
Error in Ubuntu - OPENMVG_NOT FOUND

### ISSUE THREAD

**Issue by cogitas3d** [cdcseacave/openMVS#55]
How are you? I hope very well.

I'm working on a group are trying to put openMVS inside Blender how an addon (obs, I'm not a developer, I'm a 3D designer, but I have to test it to send to adeveloper put the code on script).

I tried again and again build it, but the same error ever appear:

-- Eigen 3.2.2 found (include: /usr/include/eigen3)
-- OpenCV 2.4.9 found (include: /usr/include/opencv;/usr/include;/usr/share/OpenCV/include)
-- CGAL 4.5 found (include: /usr/include)
-- VCG  found (include: /home/cogitas3d/Programs/photogrammetry/vcglib)
-- Found required Ceres dependency: Eigen version 3.2.2 in /usr/include/eigen3
-- Found Ceres compiled with miniglog substitute for glog, beware this will likely cause problems if glog is later linked.
-- Found Ceres version: 1.12.0 installed in: /usr/local
-- CERES 1.12.0 found (include: /usr/local/include;/usr/include/eigen3;/usr/local/include/ceres/internal/miniglog;/usr/local/include)
OPENMVG_NOT FOUND : OpenMVG importer with JSON support will not be build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cogitas3d/Programs/photogrammetry/openMVS_build

I follow the steps on https://github.com/cdcseacave/openMVS/wiki/Building and even this way the error message ever appear.

Do you have some idea, what can I do?

Thank you for attention and a big hug!

**Comment by pmoulon** [comment]
Hi @cogitas3d 
Have you used -DOpenMVG_DIR:STRING="$main_path/openMVG_build/openMVG_install/share/openMVG/cmake/" in the last cmake command line ?

**Comment by cogitas3d** [comment]
Hi Pierre,

Yes... I put it, but the error continue. I search the path but after I build openMVG the directory "share/openMVG/cmake" doesnt exist. I tried to put the path of other compiled openMVG I did, but the error continue. I really read about it, I tried to solve without boring anyone... but it doesnt works.

**Comment by pmoulon** [comment]
1. Check you have a local install of OpenMVG ready on your machine
When you have configured OpenMVG you have set an install path
```
cd openMVG_build
main_path=`pwd`
=> cmake... -DCMAKE_INSTALL_PREFIX=$main_path/openMVG_build/openMVG_install
```
Check that this path is existing. Else it means that you have not done 'make install' after 'make'

2. Provide this path to OpenMVS with the -DOpenMVG_DIR:STRING argument

**Comment by pmoulon** [comment]
I updated https://github.com/cdcseacave/openMVS/wiki/Building with the missing command for OpenMVG
```
make install
cd ..
```

**Comment by cogitas3d** [comment]
Now it worked!!!
With an error on make, but build the exporter and it works!
Thank you very much!

**Comment by pmoulon** [comment]
Can you close the issue, since now the BUILD wiki has been updated
