### ISSUE TITLE
Cannot disable CUDA 

### ISSUE THREAD

**Issue by luli2949** [cdcseacave/openMVS#558]
### Steps to reproduce the problem

Hi there,

I'm trying to build it on Mac by running  

`cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT="$main_path/vcglib" -DOpenMVS_USE_CUDA=OFF`. 
However, it's still giving me the error 

> -- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Can't find OpenMP. Continuing without it.
-- WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
CMake Error at /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR iostreams program_options
  system serialization)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.17.1/share/cmake/Modules/FindBoost.cmake:2145 (find_package_handle_standard_args)
  CMakeLists.txt:122 (FIND_PACKAGE)
-- Configuring incomplete, errors occurred!

Could someone help me, please? Thanks so much.

**Comment by cdcseacave** [comment]
from the log above boost is missing, not CUDA

**Comment by luli2949** [comment]
Thank you, I was able to build it. However, when I try to run the pipeline, it gives me this error. 

> #10. Densify point cloud
Cmd: /Users/luli/openMVS_build/apps/DensifyPointCloud scene.mvs --dense-config-file Densify.ini --resolution-level 1 -w /Users/luli/Desktop/2020-spring/CS380/OpenMVGExperiments/mvs/mvs
Traceback (most recent call last):
  File "MvgMvsPipeline.py", line 349, in <module>
    pStep = subprocess.Popen(cmdline)
  File "/Users/luli/opt/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/luli/opt/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Users/luli/openMVS_build/apps/DensifyPointCloud'

Is it because the build was not successful?

**Comment by cdcseacave** [comment]
PermissionError: [Errno 13] Permission denied

in the first case and also now the error message is quite clear, but you seem to blame a totally different thing, I close this, as your issues are not constructive

**Comment by luli2949** [comment]
> PermissionError: [Errno 13] Permission denied
> 
> in the first case and also now the error message is quite clear, but you seem to blame a totally different thing, I close this, as your issues are not constructive

I can see that it's a permission error. However, the permission error seems to be caused by the fact that the cpp files are not converted to an executable file in the building stage. There was no permission error caused by the openMVG programs and that's why I'm asking...

**Comment by luli2949** [comment]
> PermissionError: [Errno 13] Permission denied
> 
> in the first case and also now the error message is quite clear, but you seem to blame a totally different thing, I close this, as your issues are not constructive

My apologies if my questions were dumb. But your second response is not very constructive either. I can read that it's a permission error, but I'm asking because I'm not sure what caused it and how to fix it. I followed each step in the building Wiki page. I've tried giving it permission by running `chmod +x.` That did not fix it. Then I realized that the problem might be I don't have the executable file named DensifyPointCloud.exe.

**Comment by cdcseacave** [comment]
dear @luli2949 you seem to be new to computers, if you adventure into programming you should get some basic computer knowledge first (or during this process), but pls use tutorials or documentation for that, I do not have time to help you here

*.exe exists only in Windows OS, on MAC and Linux the executables do not have an extension
