### ISSUE TITLE
Binaries created after building are not executables

### ISSUE THREAD

**Issue by Pushkar2307** [cdcseacave/openMVS#561]
Hi I just built openmvs from Dev branch on Ubuntu 18.04 machine.
The binaries built using the building wiki are not executables. So I'm not able to do any of the steps.
Kindly guide where I'm going wrong. 
Thanks.

**Comment by cdcseacave** [comment]
if both cmake and build process finished without error, you get executables

**Comment by rennu** [comment]
@Pushkar2307 Can you describe what you mean by "not executables"? After you did `make install`, how did you try running the commands?

**Comment by Pushkar2307** [comment]
Hi, both the cmake and build processes completed without error.
On running any of the commands, for eg.
`DensifyPointCloud scene.mvs`
I get the error, 
`DensifyPointCloud: command not found`

**Comment by rennu** [comment]
@Pushkar2307 By default `make install` installs OpenMVS to `/usr/local/bin/OpenMVS` directory. To make the commands work, you need to add `/usr/local/bin/OpenMVS` to your $PATH. Default shell in Ubuntu is bash so if you haven't changed that, edit `.bashrc` file in your home directory and add following line:
```
export PATH=${PATH}:/usr/local/bin/OpenMVS
```
After this restart console and the commands should work.

Another option is to call executables with their absolute paths ie. `/usr/local/bin/OpenMVS/DensifyPointCloud` but in the long run I believe the first option is more comfortable.

**Comment by Pushkar2307** [comment]
Thanks a lot. Just noticed that. Works now!
