### ISSUE TITLE
Use OpenMVS in my project ?

### ISSUE THREAD

**Issue by Robertyaya** [cdcseacave/openMVS#565]
When I open the option -DOpenMVS_SHARED_LIBS
I can't compile the whole project successfully
Therefore, I turn off this option and I can compile it successfully

However, I only have the 
1. Common.a  
2. IO.a  
3. Math.a 
4. MVS.a file

Can I only use these file in my project if we want to use openMVS as third party library
or I need to try to compile it in DOpenMVS_SHARED_LIBS = on 

thank you very much

**Comment by cdcseacave** [comment]
yes, you can use it as it is, the only difference is that it will link statically
