### ISSUE TITLE
Use openMVS in my project ?

### ISSUE THREAD

**Issue by Robertyaya** [cdcseacave/openMVS#566]
Hello, I want to use the OpenMVS mesh texturing module in my own project.
I can use the OpenMVS's function in my own project now.
However, the output is so strange when I use the Viewer to see it.
I think the problem is the camera pose I send to the "Interface" struct.
Therefore, I have four questions want to check:

1. I can generate mesh (include vertices and faces) in my own project, so I only need to set the "platforms", "images" and "mesh" structure in  Interface which will use in Scene class, is it right?

2. What is different between the "R" in struct Camera and in struct Pose which both in the struct Platform, I set it the same matrix now

3. The rotation matrix and translation matrix is the absolute coordinate (relative to world coordinate)  or the relative coordinate (relative to the last pose)

4. Is there have a const transformation matrix to transform our data into OpenMVS's coordinate?

thank you very much!

**Comment by cdcseacave** [comment]
1. correct
2. the pose in the camera is relative to the platform pose, the pose of the platform is the absolute pose in world coordinates
3. absolute, but C is not translation is the camera position
4. do not understand

**Comment by Robertyaya** [comment]
I can't understand the third answer
What is mean that the C is not the translation is the camera position

In my project, I will get the transformation matrix in every frame and its dimension is 4x4 (relative to world coordinate)
I directly set the rotation matrix to "R"  and the translation vector to "C", is it in the right direction?

thanky you very much

**Comment by Robertyaya** [comment]
The fourth question is mean: I draw the camera pose before I send it to the OpenMVS's mesh texturing module. It seems correct (figure 1). However, when I use the Viewer to see the output of mesh texturing module, the camera pose is so strange (figure 2)
![Screenshot from 2020-05-19 18-43-41](https://user-images.githubusercontent.com/31315066/82317743-5af6f400-9a01-11ea-8df1-ee6e869241e2.png)

![Screenshot from 2020-05-19 18-33-24](https://user-images.githubusercontent.com/31315066/82317764-621e0200-9a01-11ea-863f-a7ab91f4aaa6.png)

what do I miss?

thank you

**Comment by cdcseacave** [comment]
> I directly set the rotation matrix to "R" and the translation vector to "C", is it in the right direction?

this is the problem: R is indeed the top-left 3x3 part of the matrix, but C is -R.t()*T ( translation vector)

**Comment by Robertyaya** [comment]
Sorry, I can't understand why the C is -R.t()*T

If our transformation matrix is relative to the world coordinate
Then we can define Pn =  P0 * Rn + Tn
Pn is the camera position in frame n
p0 is the camera position is frame 0 (represent the origin point)
Rn is the rotation matrix in frame n relative to the world coordinate
Tn is the translation vector in frame n relative to the world coordinate

If the C is defined as the camera's position, it represents the Cn = Tn
Cn is the camera position in frame n
Tn is the translation vector in frame n 

I already directly set the C as -R.t()*T the path of camera position is wrong
and I also directly set the C as T, the path of camera position is correct, however, the camera's rotation seems wrong (the following fig)
![Screenshot from 2020-05-21 10-38-43](https://user-images.githubusercontent.com/31315066/82517330-707a3400-9b4f-11ea-8626-498e94481529.png)

I guess maybe there have the const transform between our coordinate and OpenMVS coordinate
What is mean "transform" in Interface class which default value is Mat44d::eye()

**Comment by Robertyaya** [comment]
> this is the problem: R is indeed the top-left 3x3 part of the matrix, but C is -R.t()*T ( translation vector)
Thank you very much, my problem is solved
