### ISSUE TITLE
InterfaceColmap can tranform sparse type .mvs file to colmap type but not dense type .mvs file

### ISSUE THREAD

**Issue by CanCanZeng** [cdcseacave/openMVS#573]
### Specifications like the version of the project, operating system, and hardware
I use Ubuntu 16.04 on a desktop with intel cpu
And the commit id of openMVS is 86356d8a6857757087457853704d939f27c24d22

### Steps to reproduce the problem
I use InterfacCOLMAP to import the result from colmap, and then do dense reconstruction:
```
InterfaceCOLMAP -i .
DensifyPointCloud -i scene.mvs
```
And I get scene_dense.mvs. Then I tried to convert the result back to colmap type.
`InterfaceCOLMAP -i scene_dense.mvs -o openmvs/`
This time an error occured
```
20:01:20 [App     ] Build date: Jun  2 2020, 19:50:44
20:01:20 [App     ] CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 cores)
20:01:21 [App     ] RAM: 31.33GB Physical Memory 31.92GB Virtual Memory
20:01:21 [App     ] OS: Linux 4.15.0-101-generic (x86_64)
20:01:21 [App     ] SSE & AVX compatible CPU & OS detected
20:01:21 [App     ] Command line: InterfaceCOLMAP -i scene_dense.mvs -o openmvs/
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```
But when I tried the same operation on the sparse .mvs file, there will be no error and the result is right.

Maybe the scene_dense.mvs file contains more infromation and the `Interface` class can not read it?
I use qtcreator to debug this error and find that the error occured around here https://github.com/cdcseacave/openMVS/blob/304bb3cbe5d591d6910ea0842b129b1a0661c512/libs/MVS/Interface.h#L349
the vector size is 4300428877, it cannot be right, so I think maybe the file type of .mvs file saved by `Interface` and `Scene` are different.

**Comment by cdcseacave** [comment]
you are right, sorry for not making that clear, I know is confusing

so to make this work you need to add `--archive-type -1` at the densification command line, this will save the resulted MVS file in the interface format

**Comment by CanCanZeng** [comment]
Thank you for clarifying this issue, I'm trying to transform it directly from Scene class instead of Interface class.
