### ISSUE TITLE
While using ReconstructMesh app with compiled passed LibMVS, CGAL::Delaunay boom

### ISSUE THREAD

**Issue by ScuptFang** [cdcseacave/openMVS#577]
Hi, I got upseted with this problem for few days. Did someone get this same situation before?
![15919433015039](https://user-images.githubusercontent.com/40800491/84472493-d3c43580-acb9-11ea-86a0-f8e891bec450.png)

**Comment by ScuptFang** [comment]
oh btw, I think I have added cgal when compiling libmvs...
![15919439089034](https://user-images.githubusercontent.com/40800491/84472772-69f85b80-acba-11ea-947f-65747fc0459f.png)

**Comment by cdcseacave** [comment]
I do not speak anything other than English, so I can not help you

Plus, CGAL is header only since v5.0, no need to link anything when compiling OpenMVS

**Comment by ScuptFang** [comment]
> I do not speak anything other than English, so I can not help you
> Plus, CGAL is header only since v5.0, no need to link anything when compiling OpenMVS

thanks for your reply! sorry about I did not know how to switch en.
the problem is scene.ReconstructMesh try to new CGAL::Delaunay class but fail, that point to a nullptr. It obviously says that libMVS didnot compile with cgal. btw, I tried to use CGAL5.0 static library with my code, which is normal. 
Honestly, Id already known that CGAL5.x is header only, but everything told me they need cgal...lib or dll.

**Comment by cdcseacave** [comment]
OpenMVS can not be compiled without CGAL

**Comment by ScuptFang** [comment]
> OpenMVS can not be compiled without CGAL

OKAY then, may I ask which CGAL.ver did you use when compiling OpenMVS release?

**Comment by cdcseacave** [comment]
All version starting with 4

**Comment by ScuptFang** [comment]
> All version starting with 4

Hi cdc, I finally figured it out. 
It is because I didnt set SIMD Extensions to SSE2(for usual CPU) or AVX(for intel), which caused EIGEN didnt work right.(look the screenshot below)
![企业微信截图_15922098528552](https://user-images.githubusercontent.com/40800491/84639453-fad56e00-af2a-11ea-93a4-00a216e20cdb.png)
"m is 0XFF" Printed in the rect area.
Matrix m location cannot be correctly assigned by '='.
