### ISSUE TITLE
ReconstructMesh result issue when point cloud has collision

### ISSUE THREAD

**Issue by happyfrank** [cdcseacave/openMVS#578]
Hi @cdcseacave, we use AI depth infer algorithm to get the each spherical image depthmap. But due to the problem of prediction accuracy, some point clouds normal will be reversed. 
Just like this:
![1](https://user-images.githubusercontent.com/12987532/84476887-5f8d9000-acc1-11ea-8246-108434d6575c.png)
Then using ReconstructMesh this wall will broken.
![1](https://user-images.githubusercontent.com/12987532/84477014-8e0b6b00-acc1-11ea-841b-9db7a7b239f1.jpg)
Do you have any idea to solve this problem? Thanks. ^v^

**Comment by cdcseacave** [comment]
ReconstruMesh will reconstruct whatever input you feed in; so to solve the mesh you need to solve the alignment issue before calling mesh reconstruction

What AI are you using to generate the depth-maps/point clouds? Maybe it will be better to do the fusion also inside OpenMVS

**Comment by happyfrank** [comment]
Dear @cdcseacave Thanks reply. For AI we base on this paper [OmniDepth](http://openaccess.thecvf.com/content_ECCV_2018/papers/NIKOLAOS_ZIOULIS_OmniDepth_Dense_Depth_ECCV_2018_paper.pdf). So you think It will be better to do DensifyPointCloud(Load AI depth-map) before ReconstrucMesh? Sorry, but I'm not see any interface to do this step.

**Comment by cdcseacave** [comment]
There is nothing special you need to do, sply export the depth maps in the format supported by OpenMVS, and next call densification as usual. See: https://github.com/cdcseacave/openMVS/blob/122397e1af32ac5660a31a61e3a0c9c0091355a3/libs/MVS/DepthMap.cpp#L1699

By doing this the fusion step inside OpenMVS will be used, however if the poses of the individual depth-maps are not correct OpenMVS can not correct them, you should do that before.

**Comment by happyfrank** [comment]
Sorry I‘m not quiet understand. You mean I change our depthmap format(just a float arry size = imageWidth * imageHeight) to openMVS format. Then use **MVS::ImportDepthDataRaw** import each depthmap?

**Comment by happyfrank** [comment]
By the way, About the the **neighbor IDs** of depthmap,  does it matter at the fusion step?

**Comment by cdcseacave** [comment]
The neighbors are computed automatically if not available. All you need to do is to store the depth-maps in files called `depth0xxx.dmap` and call `./DensifyPointCloud scene.mvs`

**Comment by happyfrank** [comment]
Dear @cdcseacave, that's all right, thanks ^v^

**Comment by chaytonmin** [comment]
> The neighbors are computed automatically if not available. All you need to do is to store the depth-maps in files called `depth0xxx.dmap` and call `./DensifyPointCloud scene.mvs`

You mean that with the obtained dmap and scene.mvs, 

> Dear @cdcseacave Thanks for your reply. For AI we base on this paper [OmniDepth](http://openaccess.thecvf.com/content_ECCV_2018/papers/NIKOLAOS_ZIOULIS_OmniDepth_Dense_Depth_ECCV_2018_paper.pdf). So you think It will be better to do DensifyPointCloud(Load AI depth-map) before ReconstrucMesh? Sorry, but I'm not see any interface to do this step.

How to load the AI depth-map?  Did you transform the depthmap of pfm to .dmap used in openMVS?
