### ISSUE TITLE
ReconstructMesh:Delaunay tetrahedralization completed,but weighting points failed.

### ISSUE THREAD

**Issue by ZxYeah** [cdcseacave/openMVS#579]
When Delaunay tetrahedralization was completed,the program was calculating the weight of points.And the debug failed ,assert(facets.empty() && inter.type == intersection_t::VERTEX && inter.v1 == vi)  occured.It occured in 1005 of the file called 'SceneRecontruct.cpp'.I looked at the current value of the local variable.The value of 'inter.type' was zero,but the value of 'intersection_t::VERTEX' was two. I cannot  understand why it happened.Do you have this problem?Can you help me with that, please?

**Comment by cdcseacave** [comment]
pls compile in Release

**Comment by cdcseacave** [comment]
close as no follow-up

**Comment by Jason-YJ** [comment]
I have the same problem now and I've tried and confirmed that all files were installed in the suitable version...Can you help me ?

**Comment by apurvazaveri** [comment]
I too have the same problem and when I try to compile in Release (like below) and run ReconstructMesh:
```
cmake .. -DCMAKE_TOOLCHAIN_FILE=../../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release
cmake --build . -j4
```
I get a seg fault for which there is an open issue: [#927](https://github.com/cdcseacave/openMVS/issues/927)

**Comment by cdcseacave** [comment]
that line is an assert, and asserts are not compiled in Release, pls try using release mode, might be a false assert trigger

**Comment by apurvazaveri** [comment]
Yes, thanks! I am trying but stuck on [#927](https://github.com/cdcseacave/openMVS/issues/927)
