### ISSUE TITLE
I run RefineMesh, but get nothing

### ISSUE THREAD

**Issue by chaytonmin** [cdcseacave/openMVS#581]
### Specifications like the version of the project, operating system, and hardware
ubuntu 18.4, SFM using COLMAP
### Steps to reproduce the problem
I run RefineMesh, but did not get the refined mesh, there is no error but no refined process :
![捕获](https://user-images.githubusercontent.com/40260488/84880141-bda1e500-b0be-11ea-8147-5255620ae3b0.PNG)
Howerver, I can ran TextureMesh, and get the scene_mesh_texture.mvs.

I want to know why I can not refine the mesh.

**Comment by cdcseacave** [comment]
Most probably OOM. Try to compile without CUDA support
