### ISSUE TITLE
Building OpenMVS in visual studio 2019

### ISSUE THREAD

**Issue by RichardAW** [cdcseacave/openMVS#587]
**Describe the bug**
Hello I am trying to build openMVS in visual studio 2019. I successfully generated a project in CMAKE though when I build in release in visual studio I get this link error: LINK : fatal error LNK1181: cannot open input file '..\..\lib\x64\Release\IO.lib'

**CMAKE log:** 

Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
cotire 1.8.0 loaded.
Compiling with C++14
CUDA_TOOLKIT_ROOT_DIR not found or specified
Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Can't find CUDA. Continuing without it.
WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
Found Boost: C:/DEV/boost_1_70_0 (found version "1.70.0") found components: iostreams program_options system serialization regex 
Eigen 3.3.6 found (include: C:/DEV/ceres-solver-1.14.0/eigen)
OpenCV 4.4.0 found (include: C:/DEV/opencv-4.3/opencv-master/Build;C:/DEV/opencv-4.3/opencv-master/include;C:/DEV/opencv-4.3/opencv-master/modules/core/include;C:/DEV/opencv-4.3/opencv-master/modules/flann/include;C:/DEV/opencv-4.3/opencv-master/modules/imgproc/include;C:/DEV/opencv-4.3/opencv-master/modules/ml/include;C:/DEV/opencv-4.3/opencv-master/modules/photo/include;C:/DEV/opencv-4.3/opencv-master/modules/dnn/include;C:/DEV/opencv-4.3/opencv-master/modules/features2d/include;C:/DEV/opencv-4.3/opencv-master/modules/imgcodecs/include;C:/DEV/opencv-4.3/opencv-master/modules/videoio/include;C:/DEV/opencv-4.3/opencv-master/modules/calib3d/include;C:/DEV/opencv-4.3/opencv-master/modules/highgui/include;C:/DEV/opencv-4.3/opencv-master/modules/objdetect/include;C:/DEV/opencv-4.3/opencv-master/modules/stitching/include;C:/DEV/opencv-4.3/opencv-master/modules/ts/include;C:/DEV/opencv-4.3/opencv-master/modules/video/include;C:/DEV/opencv-4.3/opencv-master/modules/gapi/include)
Visual Leak Detector (VLD) is not found.
Using header-only CGAL
Targetting Visual Studio 16 2019
Target build enviroment supports auto-linking
Using VC toolset 142.
Generator uses intermediate configuration directory: $(Platform)/$(Configuration)
Found Boost: C:/DEV/boost_1_70_0 (found suitable version "1.70.0", minimum required is "1.48")  
Boost include dirs: C:/DEV/boost_1_70_0
Boost libraries:    
CGAL 5.00 found (include: C:/DEV/CGAL-5.0.2/include)
VCG  found (include: C:/DEV/OpenMSV/VCG)
CXX target MVS cotired without unity build.
GLEW  found (include: )
GLFW3 3.3.2 found (include: )
CXX target Viewer cotired without unity build.
Configuring done
Generating done

**BUILD LOG Visual studio: (Release x64)** 

1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>Checking Build System
2>------ Build started: Project: Common, Configuration: Release x64 ------
2>Generating CXX prefix header C:\DEV\openMVS-master\bin\libs\Common\x64\Release\cotire\Common_CXX_prefix.hxx
2>Building Custom Rule C:/DEV/openMVS-master/libs/Common/CMakeLists.txt
2>Common.cpp
2>CUDA.cpp
2>ConfigTable.cpp
2>EventQueue.cpp
2>Log.cpp
2>SML.cpp
2>Timer.cpp
2>Types.cpp
2>Util.cpp
2>Common.vcxproj -> C:\DEV\openMVS-master\bin\lib\x64\Release\Common.lib
3>------ Build started: Project: IO, Configuration: Release x64 ------
4>------ Build started: Project: Math, Configuration: Release x64 ------
3>Generating CXX prefix header C:\DEV\openMVS-master\bin\libs\IO\x64\Release\cotire\IO_CXX_prefix.hxx
3>Building Custom Rule C:/DEV/openMVS-master/libs/IO/CMakeLists.txt
3>Common.cpp
4>Generating CXX prefix header C:\DEV\openMVS-master\bin\libs\Math\x64\Release\cotire\Math_CXX_prefix.hxx
4>Building Custom Rule C:/DEV/openMVS-master/libs/Math/CMakeLists.txt
4>Common.cpp
3>Image.cpp
3>ImageBMP.cpp
3>ImageDDS.cpp
3>ImageJPG.cpp
3>C:\DEV\gstreamer\1.0\x86_64\include\jmorecfg.h(242,13): error C2371: 'boolean': redefinition; different basic types
3>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\rpcndr.h(193): message : see declaration of 'boolean'
3>ImagePNG.cpp
3>ImageSCI.cpp
3>ImageTGA.cpp
4>IBFS.cpp
3>ImageTIFF.cpp
3>OBJ.cpp
4>lmmin.cpp
3>PLY.cpp
4>Math.vcxproj -> C:\DEV\openMVS-master\bin\lib\x64\Release\Math.lib
3>Done building project "IO.vcxproj" -- FAILED.
5>------ Build started: Project: MVS, Configuration: Release x64 ------
5>Generating CXX prefix header C:\DEV\openMVS-master\bin\libs\MVS\x64\Release\cotire\MVS_CXX_prefix.hxx
5>Building Custom Rule C:/DEV/openMVS-master/libs/MVS/CMakeLists.txt
5>Common.cpp
5>Camera.cpp
5>DepthMap.cpp
5>Image.cpp
5>Mesh.cpp
5>C:\DEV\CGAL-5.0.2\include\CGAL/config.h(115,1): warning C4005: 'BOOST_PARAMETER_MAX_ARITY': macro redefinition
5>C:\DEV\boost_1_70_0\boost/parameter/config.hpp(10): message : see previous definition of 'BOOST_PARAMETER_MAX_ARITY'
5>Platform.cpp
5>PointCloud.cpp
5>RectsBinPack.cpp
5>Scene.cpp
5>SceneDensify.cpp
5>SceneReconstruct.cpp
5>SceneRefine.cpp
5>SceneRefineCUDA.cpp
5>SceneTexture.cpp
5>SemiGlobalMatcher.cpp
5>MVS.vcxproj -> C:\DEV\openMVS-master\bin\lib\x64\Release\MVS.lib
5>Done building project "MVS.vcxproj".
6>------ Build started: Project: DensifyPointCloud, Configuration: Release x64 ------
7>------ Build started: Project: InterfaceCOLMAP, Configuration: Release x64 ------
8>------ Build started: Project: InterfaceVisualSFM, Configuration: Release x64 ------
9>------ Build started: Project: ReconstructMesh, Configuration: Release x64 ------
10>------ Build started: Project: RefineMesh, Configuration: Release x64 ------
11>------ Build started: Project: TextureMesh, Configuration: Release x64 ------
12>------ Build started: Project: Viewer, Configuration: Release x64 ------
6>Building Custom Rule C:/DEV/openMVS-master/apps/DensifyPointCloud/CMakeLists.txt
6>DensifyPointCloud.cpp
10>Building Custom Rule C:/DEV/openMVS-master/apps/RefineMesh/CMakeLists.txt
8>Building Custom Rule C:/DEV/openMVS-master/apps/InterfaceVisualSFM/CMakeLists.txt
7>Building Custom Rule C:/DEV/openMVS-master/apps/InterfaceCOLMAP/CMakeLists.txt
10>RefineMesh.cpp
9>Building Custom Rule C:/DEV/openMVS-master/apps/ReconstructMesh/CMakeLists.txt
11>Building Custom Rule C:/DEV/openMVS-master/apps/TextureMesh/CMakeLists.txt
8>InterfaceVisualSFM.cpp
7>InterfaceCOLMAP.cpp
12>Generating CXX prefix header C:\DEV\openMVS-master\bin\apps\Viewer\x64\Release\cotire\Viewer_CXX_prefix.hxx
9>ReconstructMesh.cpp
12>Building Custom Rule C:/DEV/openMVS-master/apps/Viewer/CMakeLists.txt
11>TextureMesh.cpp
12>Common.cpp
10>LINK : fatal error LNK1181: cannot open input file '..\..\lib\x64\Release\IO.lib'
6>LINK : fatal error LNK1181: cannot open input file '..\..\lib\x64\Release\IO.lib'
11>LINK : fatal error LNK1181: cannot open input file '..\..\lib\x64\Release\IO.lib'
9>LINK : fatal error LNK1181: cannot open input file '..\..\lib\x64\Release\IO.lib'
8>LINK : fatal error LNK1181: cannot open input file '..\..\lib\x64\Release\IO.lib'
9>Done building project "ReconstructMesh.vcxproj" -- FAILED.
6>Done building project "DensifyPointCloud.vcxproj" -- FAILED.
10>Done building project "RefineMesh.vcxproj" -- FAILED.
8>Done building project "InterfaceVisualSFM.vcxproj" -- FAILED.
11>Done building project "TextureMesh.vcxproj" -- FAILED.
12>Camera.cpp
7>LINK : fatal error LNK1181: cannot open input file '..\..\lib\x64\Release\IO.lib'
7>Done building project "InterfaceCOLMAP.vcxproj" -- FAILED.
12>Image.cpp
12>Scene.cpp
12>Viewer.cpp
12>Window.cpp
12>LINK : fatal error LNK1181: cannot open input file '..\..\lib\x64\Release\IO.lib'
12>Done building project "Viewer.vcxproj" -- FAILED.
13>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
13>Building Custom Rule C:/DEV/openMVS-master/CMakeLists.txt
========== Build: 5 succeeded, 8 failed, 0 up-to-date, 0 skipped ==========

Thank you! 
RIchard

**Comment by cdcseacave** [comment]
3>C:\DEV\gstreamer\1.0\x86_64\include\jmorecfg.h(242,13): error C2371: 'boolean': redefinition; different basic types

**Comment by RichardAW** [comment]
Hello, thank you for your reply. Do you know any steps I could try to solve this issue? I tried moving the folder to C:\gstreamer but I'm still getting the same problem. Sorry, I'm quite new to this. Thank you! Richard

**Comment by cdcseacave** [comment]
no idea why you even need gstream, openmvs for sure does not need it
pls follow the build instructions in openmvs

**Comment by RichardAW** [comment]
Hello, OK I managed the instructions from the build wiki. It's more successful this time (just one failure). Thank you. I wasn't sure how to run CMAKE from the command line but I managed it now.
