### ISSUE TITLE
Error in Ubuntu - OPENMVG_NOT FOUND

### ISSUE THREAD

**Issue by cogitas3d** [cdcseacave/openMVS#59]
Hey there!

Some weeks ago I open an issue here with this same name.

I had a problem when I build the openMVS even following the step by step shown at: https://github.com/cdcseacave/openMVS/wiki/Building

Old issue: https://github.com/cdcseacave/openMVS/issues/55

So, Dr. Pierre Moulon helped me with other link and the project was build. The problem is that the link https://github.com/OpenMVS/openMVS/ doesn't exist anymore. The step-by-step on cdcseacave/openMVS doest work. I dont know why, I tested several times, but doesn't work:

OPENMVG_NOT FOUND : OpenMVG importer with JSON support will not be build

Whats happen with the https://github.com/OpenMVS/openMVS/ link? Is it possible make the same modifications at cdcseacave?

Thank you for the attention.

**Comment by pmoulon** [comment]
Hi @cogitas3d 
It's certainly because you did not add the 
It's because you don't have add
```
-DOpenMVG_DIR:STRING="$main_path/openMVG_build/openMVG_install/share/openMVG/cmake/" 
```
in the OpenMVS command line. Since it's an optional option it is not by default in the script.

**Comment by cogitas3d** [comment]
Sorry.

I was solved by Dr. Moulon observation:

-DOpenMVG_DIR:STRING="$main_path/openMVG_build/openMVG_install/share/openMVG/cmake/"

**Comment by cogitas3d** [comment]
Thank you very much!
