### ISSUE TITLE
Aborted (core dumped) upon PointCloud::RemovePoint()

### ISSUE THREAD

**Issue by aashutosh1997** [cdcseacave/openMVS#591]
**Describe the bug**
I implemented a statistical outlier removal on dense scene, before saving it. After figuring out the indices of the outliers in scene.pointcloud, I remove the points from the cloud using the pre-defined PointCloud::RemovePoint() function (which is also used by Scene::PointCloudFilter()). However, after saving the mvs and ply files, and displaying the memory log, DensifyPointCloud throws double free or corruption (!prev) followed byAborted (core dumped). Next module in the pipeline also throws a segmentation fault when using the .mvs as input. I don' understand this behaviour, am I not supposed to used the RemovePoint() on Scene::PointCloud object? 

**To Reproduce**
This is all that I added before saving the dense scene.
```
    for (size_t i:indices){
    	scene.pointcloud.RemovePoint((PointCloud::Index)i);
    }
```

**Expected behavior**
To be able to use the dense scene for mesh generation.

**Comment by cdcseacave** [comment]
That is exactly the function you want to use, but it makes sens to use it like that only if the indices are ordered from high to small.

**Comment by aashutosh1997** [comment]
Thank you for the quick response, I sorted the indices before using the function and it worked as expected.

Thanks again, closing.
