### ISSUE TITLE
 TextureMesh－－no texture, just green

### ISSUE THREAD

**Issue by yuancaimaiyi** [cdcseacave/openMVS#592]
@cdcseacave sorry to bother you!
I use colmap generate dense point cloud,and the use openmvs mesh and texture,but the result is None ,is just green area! so I am confused
result is :
![texture](https://user-images.githubusercontent.com/28293910/87872572-5e503100-c9ec-11ea-9737-72253c68b4db.png)
![colmap_mesh_texture](https://user-images.githubusercontent.com/28293910/87872585-6d36e380-c9ec-11ea-8a94-d34f96be9375.png)

**Comment by yuancaimaiyi** [comment]
@cdcseacave 
At the moment,I test the openmvs official images demo ,I use colmap generate dense point clould like this :
![open](https://user-images.githubusercontent.com/28293910/87875176-e987f180-ca01-11ea-83c8-4c39d35665a7.png)
and use openmvs to  mesh and texture ,the result is still green
mesh.ply 
![mesh](https://user-images.githubusercontent.com/28293910/87875203-353a9b00-ca02-11ea-95bc-51288fcb092a.png)
texture.ply
![texture](https://user-images.githubusercontent.com/28293910/87875211-50a5a600-ca02-11ea-9196-10b5be06c4d3.png)

my processing flow：
![flow](https://user-images.githubusercontent.com/28293910/87875252-93677e00-ca02-11ea-8b3d-40da4f3bcb3b.png)
There are no mistakes in the process, I'm confused！
thanks!

**Comment by cdcseacave** [comment]
pls check the wiki for how to use the library (you need to apply texture)
