### ISSUE TITLE
How to choose the GPU?

### ISSUE THREAD

**Issue by FarmerLiuAng** [cdcseacave/openMVS#593]
Thank you for your excellent work!
I have two GPUS, and I wonder how to choose which GPU to use when start using OpenMvs or using RefineMesh

**Comment by cdcseacave** [comment]
I suggest to completly disable CUDA suport

**Comment by FarmerLiuAng** [comment]
Thanks for your reply!
I'll trt it latter.
But if do so, will the speed be slow？

**Comment by FarmerLiuAng** [comment]
I have tried. It was very slow.
Is there any command to choose the GPU or any better choice to solve this problem?

**Comment by moepforfreedom** [comment]
you could try setting the CUDA_VISIBLE_DEVICES environment variable to the index of your desired GPU to make only one of the gpus visible to the openMVS

**Comment by FarmerLiuAng** [comment]
> 
> 
> you could try setting the CUDA_VISIBLE_DEVICES environment variable to the index of your desired GPU to make only one of the gpus visible to the openMVS

Thank you very much！ It works！It‘nice of you！

**Comment by cdcseacave** [comment]
cool solution, thx @moepforfreedom 

@FarmerLiuAng if this is solved, pls close the issue

**Comment by quicktwit** [comment]
Hi @FarmerLiuAng @cdcseacave 
How did you enable CUDA_VISIBLE_DEVICES  visible to the openMVS?
