### ISSUE TITLE
ReconstructMesh didn't produce a result

### ISSUE THREAD

**Issue by tangeroo** [cdcseacave/openMVS#595]
Hi,
 I tried ReconstructMesh command, here are the process details below.It didn't report errors, but I didn't find the output "scene_dense_mesh.mvs". Could you see any reason for this mistake. I can't figure it out.
Thank you.
![image](https://user-images.githubusercontent.com/25971461/88250175-52f55200-ccd9-11ea-860b-b6d82dbd82c1.png)

**Comment by cdcseacave** [comment]
I never tested OpenMVS with environmental variables for paths. Pls use it normally as explained in the wiki.
