### ISSUE TITLE
Errors Using DensifyPointCloud

### ISSUE THREAD

**Issue by maskerJT** [cdcseacave/openMVS#596]
**Describe the bug**
When use DensifyPointCloud.exe xxx.mvs in CMD, I get the  "unknow image format" error. 
The format I use is JPG, I can't figure out what's wrong.

**To Reproduce**
D: \openMVS\image \resultStore \result1 \reconstruction sequential>D: \openMVS \bui ld\openMVS \bin x64 \Debug\ DensifyPointCloud. exe 0723. mvs
16:06:39 [App     ] Build date: Jul 23 2020, 15:31:16
16:06:39 [App     ] CPU: AMD A8-6410 APU with AMD Radeon R5 Graphics     (4 cores)
16:06:39 [App     ] RAM: 10.96GB Physical Memory 128.00TB Virtual Memory
16:06:39 [App     ] OS: Windows 8 x64             [my OS is windows 10]
16:06:39 [App     ] SSE & AVX compatible CPU & OS detected
16:06:39 [App     ] Command line: 0723.mvs
16:06:39 [App     ] Camera model loaded: platform 0; camera  0; f 0.808x0.808; poses 15
16:06:39 [IO      ] error: unknown image format 'D:/openMVS/image/imageStore/imageSet1/1 (1).jpg'
16:06:39 [App     ] error: failed loading image header
16:06:39 [App     ] error: failed reloading image 'D:/openMVS/image/imageStore/imageSet1/1 (1).jpg'
16:06:39 [App     ] error: invalid project

**Expected behavior**
a dense version of .mvs is expected to generate, and my os is windows 10.

**Additional context**
Is there anything wrong when I build openMVS?
I build this openMVS with cmake-gui, I ignore the message[can't find GLEW], and openMVS.sln doesn't have viewer APP in it.
but it is not supposed to influence DensifyPointCloud...   : (

**Comment by cdcseacave** [comment]
yes, there is something wrong with your build; you can follow the build instructions or use the prebuilt windows binaries of any commit you want.

different jpeg library version was used for different parts of the library, and was discussed in tens other issues
