### ISSUE TITLE
Have GEOGRAM been used in Delaunay triangulation (SceneReconstruct.cpp), replacing the CGAL? 

### ISSUE THREAD

**Issue by luoyin500** [cdcseacave/openMVS#599]
I notice that there is an issue about replacing the CGAL with GEOGRAM in Delaunay triangulation (SceneReconstruct.cpp): https://github.com/cdcseacave/openMVS/issues/90. But I couldn't find any branch on it. Have geogram been used in Delaunay triangulation, replacing the CGAL?

**Comment by cdcseacave** [comment]
no, it was not
