### ISSUE TITLE
isnan/isinf vs std::isnan/std::isinf

### ISSUE THREAD

**Issue by stephane-lb** [cdcseacave/openMVS#60]
Hi,

I was compiling openMVS for a first time this morning and I got an issue on this lines:

```
inline bool   ISINFORNAN(float x)			{ return (isinf(x) || isnan(x)); }
inline bool   ISINFORNAN(double x)			{ return (isinf(x) || isnan(x)); }
inline bool   ISFINITE(float x)				{ return (!isinf(x) && !isnan(x)); }
inline bool   ISFINITE(double x)			{ return (!isinf(x) && !isnan(x)); }
```

(file : libs/Common/Types.h)

I fixed it by replacing isinf by std::isinf and isnan by std::isnan. 

I am working on Archlinux, do you think that could be something to change on the repo ?

Have a good day,

Stephane

**Comment by cdcseacave** [comment]
Hi Stephane,

That code was written long time ago, and I remember that at that time I couldn't use std cause was not available on all platforms. Probably now can be changed to std, but I am afraid not to break one of the existing working platforms. Can you confirm that std::isinf and std::isnan is available on all platforms?

Thanks!

**Comment by stephane-lb** [comment]
Hi,

Sorry for the delay, bad timing on my side ... It woks on Archlinux, I supposed that you are using windows to code, so I think we could suppose that it will work on all platforms.  Is that ok with you ?

**Comment by cdcseacave** [comment]
solved
