### ISSUE TITLE
DensifyPointCloud doesn't create a .mvs file

### ISSUE THREAD

**Issue by hallavar** [cdcseacave/openMVS#600]
Hello,
On my dataset of 751 images, the function DensifyPointCloud doesn't seems to create any .mvs file, even if it had run without error.

On my terminal i received a Killed at the end. but no additional .mvs had been created.

You can find a screnshot and the DesifyPointCloud logs below 

Command line: -i ./scene.mvs -o ./scene_dense.mvs

[DensifyPointCloud-200727093258AAE935.log](https://github.com/cdcseacave/openMVS/files/4981365/DensifyPointCloud-200727093258AAE935.log)
**Screenshot**
![](https://image.noelshack.com/fichiers/2020/31/1/1595844060-capture-d-ecran-du-2020-07-27-12-00-31.png)

**Desktop
 - OS: Linux 5.4 instance
 - Cpu Intel core Haswell 8 cores
 - RAM: 28.7 GB

**Comment by cdcseacave** [comment]
you run out of mem

**Comment by nick0622** [comment]
I have the same issue, but I still have 935GB of memory left. Idk why the program a killed.
![image](https://github.com/cdcseacave/openMVS/assets/87253320/a2e910ab-0f86-4246-b9bf-b50b785fcfb4)

**Comment by cdcseacave** [comment]
It is not about the lack of disk space but insufficient ram
