### ISSUE TITLE
Colmap compatibility

### ISSUE THREAD

**Issue by tompollok** [cdcseacave/openMVS#603]
Is there any information about the colmap compatibility? I guess its mostly about the compatibility of the nvm file.
I can successfully use an older version of colmap with an older version of openMVS (2019) . But when i tired the latest versions a while ago then it failed. 

And what about the mvs file? Is it only compatible within the same openMVS release? Because im getting an error: invalid stream (bad allocation)

**Comment by cdcseacave** [comment]
I think you have a wrong idea of what COLMAP interface is. NVM is not COLMAP native file format, but VisualSFM format. You do not need to convert it to NVM, but you can import directly the BIN or TXT project solved by COLMAP

**Comment by tompollok** [comment]
Yes i know that NVM is not the native Colmap format. Ok thanks, i will try to use the direct import. But regarding the mvs file, is it only compatible within the same openMVS version?

**Comment by cdcseacave** [comment]
no, the mvs file is supported by all versions
