### ISSUE TITLE
How can I reconstruct mesh and texture from pointcloud  generated by structured light camera?

### ISSUE THREAD

**Issue by WinterCodeForEverything** [cdcseacave/openMVS#608]
Is there any document for .mvs file format ? Or is there any interface for .ply from structured light and a camera data file( any format needed ) to get a .mvs? I need to reconstruct mesh from pointcloud  generated by structured light camera, please help me!

**Comment by cdcseacave** [comment]
use Interface.h; pls read the wiki

**Comment by WinterCodeForEverything** [comment]
thanks for repply, I used Interface.h to get a .mvs file, but ReconstructMesh's result is really bad because of only 6 picture.  And I have a .obj mesh and I wan get .mvs file for mesh and use TextureMesh directly. But there is no face interface in Interface.h. how I can get mesh .mvs?  write the Line interface can do it?

**Comment by cdcseacave** [comment]
use `--mesh-file <mesh.obj>` command line for TextureMesh

**Comment by WinterCodeForEverything** [comment]
Thanks vvvvvvvvvvv much! I finish it.

**Comment by greatwallet** [comment]
@WinterCodeForEverything Hi! Would you please provide your scripts of converting custom formatted dataset to `*.mvs` file. I'm a newbie to cpp and could really benefit from it. Thx!

**Comment by WinterCodeForEverything** [comment]
@greatwallet I'd like to help you but my format belongs to our team and I have to ask my teacher's permit so please wait. I think you'd better read interface.h and read interfaceColmap.cpp or interfaceVIsualSFM.cpp as example, it's pretty clear to understand. Simply say,  you only need to input camera intrinic and external parameter, image list and point into the structure. if you have mesh file, point structure can be ignored.

**Comment by greatwallet** [comment]
Ok, no problem! Thx for the tip!

**Comment by lihui1998** [comment]
> Thanks vvvvvvvvvvv much! I finish it.

If I have a ply file, camera internal parameters, camera external parameters and pictures, can I use texturemesh for texture reconstruction? Can you help me, thank you.

**Comment by WinterCodeForEverything** [comment]
you could read the above tips or read the interfaces I write.
[Interfaces.zip](https://github.com/cdcseacave/openMVS/files/7791567/Interfaces.zip)
.

**Comment by lihui1998** [comment]
> you could read the above tips or read the interfaces I write. [Interfaces.zip](https://github.com/cdcseacave/openMVS/files/7791567/Interfaces.zip) .

Okay, thank you for your advice.
