### ISSUE TITLE
Merged sparse point mvs model as the DensifyPointCloud command input failed

### ISSUE THREAD

**Issue by tangeroo** [cdcseacave/openMVS#609]
Hi,
  Really appreciate your excellent work. In  my study, I merged two sparse point clouds mvs model as the DensifyPointCloud input.  However when Estimating depth-maps was not finished, the  process just exited without any error output. Any suggestion can help me repair this problem, thank you.
  These two sparse points one is from openmvg, one is line points, which are sampled from lines and stored by line orders. In merging line points are stored just behind openmvg points. They have the same camera intrinsics and extrinsics.

**Comment by cdcseacave** [comment]
make sure when u add the line point you add them correctly as the sparse point cloud data was added:
point positions, point views, point color, whatever other info you have already for the existent points

**Comment by tangeroo** [comment]
Hi,
  thanks for your guidance, my problem has been solved. Some input points are wrong , they are (x, nan, nan)
