### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by raderic** [cdcseacave/openMVS#61]
Hello,

I've built and installed openMVS and I tried to compile so simple program:
```
#include <iostream>
#include <OpenMVS/Common/Common.h>
int main() {
    return 0;
}
```
And it caused errors:

> In file included from /usr/local/include/OpenMVS/Common/Types.h:2706:0,
>                  from /usr/local/include/OpenMVS/Common/Common.h:176,
>                  from /home/radek/ClionProjects/mvs/main.cpp:3:
> /usr/local/include/OpenMVS/Common/Types.inl:663:33: error: ‘Eigen’ does not name a type
>  FORCEINLINE bool ISFINITE(const Eigen::Matrix<TYPE,R,C>& m)

please help me solve it.

**Comment by cdcseacave** [comment]
not sure if this helps, but for using OpenMVS as a library you have to include only one file, and that file is <OpenMVS/MVS.h>

You also might want to include it as the first file in the project.

**Comment by raderic** [comment]
> and that file is 
is....?

> not sure if this helps, but for using OpenMVS as a library

So what is another possibility?

**Comment by cdcseacave** [comment]
sry, it was cut by the markdown language

```
#include <OpenMVS/MVS.h>
```
as the first include

**Comment by raderic** [comment]
Thanks, It solved compilation errors.
But now I've got linker error:

> /usr/local/include/OpenMVS/Common/Types.inl:265: undefined reference to `SEACAVE::ColorType<float>::ONE'

**Comment by cdcseacave** [comment]
you have to link against the openmvs libs, it is not a header only library

**Comment by raderic** [comment]
Yes, I know it but when I put to my CMakeLists.txt:

> find_package(OpenMVS REQUIRED)

it says me:
>Error:By not providing "FindOpenMVS.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "OpenMVS", but CMake did not find one.

**Comment by cdcseacave** [comment]
please read the CMake wiki!
you need to either create a findopenmvs CMake file or you point your project to the OpenMVS file created when installing OpenMVS: 
```
cmake .  src -DOpenMVS_DIR="path"
```

**Comment by raderic** [comment]
ok, thanks :) 
Now, I have a problem with something like that:

> ./InterfaceOpenMVG sfmData.json 

> 23:35:02 [App     ] Build date: Feb 24 2016, 12:27:58
> 23:35:02 [App     ] CPU: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
> 23:35:02 [App     ] RAM: 8.00GB Physical Memory 128.00TB Virtual Memory
> 23:35:02 [App     ] OS: Windows 8.1 x64
> 23:35:02 [App     ] SSE & AVX compatible CPU & OS detected
> 23:35:02 [App     ] Command line: sfmData.json
> 23:35:03 [App     ] Imported data: 8 cameras, 8 poses, 8 images, 3958 vertices
> Processed images 8 (100%, 1ms)
> 23:35:03 [App     ] error: no image using camera 0 of platform 0
> 23:35:03 [App     ] error: no image using camera 0 of platform 1
> 23:35:03 [App     ] error: no image using camera 0 of platform 2
> 23:35:03 [App     ] error: no image using camera 0 of platform 3
> 23:35:03 [App     ] error: no image using camera 0 of platform 4
> 23:35:03 [App     ] error: no image using camera 0 of platform 5
> 23:35:03 [App     ] error: no image using camera 0 of platform 6
> 23:35:03 [App     ] error: no image using camera 0 of platform 7
> 23:35:03 [App     ] Scene saved (5ms):
>         8 images (0 calibrated)


1. I don't know how to deal with that. The sfmData.json was generated by openMVG. 
2. Do you know how to use sfmData structure in runtime and pass it to Scene struct ( I don't like convert and save it on a disk while I have it in memory.)

**Comment by pyp22** [comment]
You need now to run openMVS. See usage here: https://github.com/cdcseacave/openMVS/wiki/Usage

**Comment by cdcseacave** [comment]
You have to use exactly the same path you used to sfmData.json when you used OpenMVG. This is a problem in OpenMVG file format, and I think @pmoulon is already working on it, cause I signaled it to him before.

**Comment by cdcseacave** [comment]
I moved the OpenMVG to OpenMVS exporter in OpenMVG, so please use that one from now on.

**Comment by pmoulon** [comment]
@raderic => You can use it from the OpenMVG develop branch: https://github.com/openMVG/openMVG/blob/develop/docs/sphinx/rst/software/MVS/OpenMVS.rst
