### ISSUE TITLE
Terminates at refine mesh step

### ISSUE THREAD

**Issue by Hiltona99** [cdcseacave/openMVS#611]
I am attempting to simulate running OpenMVS on a background subtracted image. In other words, I took the SceauxCastle dataset and removed most of the image, leaving only a small section as shown in this example. And I did this with 5 of the images.

![100_7100](https://user-images.githubusercontent.com/55594341/91999621-98f6fa00-ed0a-11ea-85b7-2184b8139048.png)

The issue is that when I reach the refine mesh step, the program ends as shown here: 

# 12. Refine the mesh
Cmd: /Users/andrewhlton/fresh_Open/openMVS_build/bin/Release/RefineMesh scene_dense_mesh.mvs --scales 2 -w /Users/andrewhlton/3d_reconstruction/python_background_sub/example_building/test_out_small_1080p/mvs
10:44:22 [App     ] Build date: Aug 26 2020, 15:51:44
10:44:22 [App     ] CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 cores)
10:44:22 [App     ] RAM: 16.00GB Physical Memory 16.00GB Virtual Memory
10:44:22 [App     ] OS: Darwin 19.6.0 (x86_64)
10:44:22 [App     ] SSE & AVX compatible CPU & OS detected
10:44:22 [App     ] Command line: scene_dense_mesh.mvs --scales 2 -w /Users/andrewhlton/3d_reconstruction/python_background_sub/example_building/test_out_small_1080p/mvs
10:44:22 [App     ] Scene loaded (9ms):
	5 images (5 calibrated) with a total of 9.89 MPixels (1.98 MPixels/image)
	0 points, 6656 vertices, 13269 faces

I am not sure why this is happening as the other steps provide a decent model as you can see: 

scene_dense
<img width="477" alt="Screen Shot 2020-09-02 at 11 01 32 AM" src="https://user-images.githubusercontent.com/55594341/92000684-c7290980-ed0b-11ea-939c-40e81e467bd4.png">

scene_dense_mesh
<img width="231" alt="Screen Shot 2020-09-02 at 11 01 40 AM" src="https://user-images.githubusercontent.com/55594341/92000702-cd1eea80-ed0b-11ea-80bd-b7a0394fa6f9.png">

Any insight into why this is happening or how to fix it is much appreciated.

**Comment by cdcseacave** [comment]
Try with more RAM, or in Debug mode to see some more info about the crash.
