### ISSUE TITLE
Add points to mesh.mvs

### ISSUE THREAD

**Issue by tangeroo** [cdcseacave/openMVS#613]
Hi,
  I want to add some other points to the mesh result before the TextureMesh step. Could you give any suggestions for I finishing this?
Thank you in advance.

**Comment by cdcseacave** [comment]
edit the mesh in any tool you want, and add `--mesh-file <edited-mesh.ply>` to the normal `TextureMesh` command line

**Comment by tangeroo** [comment]
Sorry to bother again here, but i found meshlab doesn't support ply or mvs format. Any other tool recommanded. 
thank you!

**Comment by cdcseacave** [comment]
it does support ply
