### ISSUE TITLE
ZNCC calculation

### ISSUE THREAD

**Issue by w080707** [cdcseacave/openMVS#617]
normSqZeroMean() is subtracting the mean from each pixel

_Originally posted by @cdcseacave in https://github.com/cdcseacave/openMVS/issues/227#issuecomment-310049759_
*****************************
In the repo, I only found two definitions of normSqZeroMean() in libs/Common/Types.inl, and this function has never been called. Could you help to check that?

In the flle libs/MVS/DepthMap.cpp, I noticed that in DepthEstimator::FillPixelPatch(), you calculate the mean value of the patch of image0 (line 386) to calculate normSq0, however, when calculating normSq1(line 443), it seems that there is no operation to substract the mean values of patch pixels.

**Comment by cdcseacave** [comment]
the implementation in the DepthMap is an optimized version of WZNCC
