### ISSUE TITLE
Can't find OpenMVS binaries on Ubuntu

### ISSUE THREAD

**Issue by Kolt912** [cdcseacave/openMVS#618]
Hello!
I'm trying to start work with OpenMVS and on step10 I have error.
First of all script ask me an OpenMVS binary folder. I'm writing "./apps" in root of OpenMVS.
Then script working and crashed on step 10 - using DensifyPointCloud

`Cmd: ./apps/DensifyPointCloud scene.mvs --dense-config-file Densify.ini --resolution-level 1 -w /home/dev/openMVS/output/mvs
Traceback (most recent call last):
  File "./scr2", line 354, in <module>
    pStep = subprocess.Popen(cmdline)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './apps/DensifyPointCloud'
`

Containes of apps/DensifyPointCloud: DensifyPointCloud.cpp, CMakeLists.txt
Installing and compiling was successfully ended without errors.
Whats wrong?
Thanks.

**Comment by gladguy** [comment]
Have you built it successfully ?

**Comment by cdcseacave** [comment]
no permission

**Comment by Kolt912** [comment]
> Have you built it successfully ?

No.
I'm used docker openmvsmvg image from dockerhub
