### ISSUE TITLE
A bug in Sift::create_octaves?

### ISSUE THREAD

**Issue by stanleylijilin** [cdcseacave/openMVS#619]
It seems the comment is right, but the code is not.The third parameter of add_octave is not updated.
    /*
     * Create new octave from 'img', then subsample octave image where
     * sigma is doubled to get a new base image for the next octave.
     */
    float img_sigma = this->options.inherent_blur_sigma;
    for (int i = std::max(0, this->options.min_octave);
        i <= this->options.max_octave; ++i)
    {
        //std::cout << "Creating octave " << i << "..." << std::endl;
        this->add_octave(img, img_sigma, this->options.base_blur_sigma);
        img = mve::image::rescale_half_size_gaussian<float>(img);
        img_sigma = this->options.base_blur_sigma;
    }

**Comment by cdcseacave** [comment]
not related to OpenMVS

**Comment by stanleylijilin** [comment]
> not related to OpenMVS

sorry, I commit in wrong place
