### ISSUE TITLE
Segmentation fault with InterfaceOpenMVG application on Ubuntu 14.04

### ISSUE THREAD

**Issue by vfdev-5** [cdcseacave/openMVS#62]
I've built the project (master branch) following the [wiki page](https://github.com/cdcseacave/openMVS/wiki/Building) with OpenMVG library. Launching the InterfaceOpenMVG application on the Sceaux Castle example sfm_data.json file as explained in the [example](https://github.com/cdcseacave/openMVS/wiki/Usage)  and application crashes with the following info in the terminal :
```
14:20:24 [App     ] Build date: Mar 20 2016, 13:25:56
14:20:24 [App     ] CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
14:20:24 [App     ] RAM: 15.58GB Physical Memory 202.00MB Virtual Memory
14:20:24 [App     ] OS: Linux 3.19.0-39-generic (x86_64)
14:20:24 [App     ] SSE & AVX compatible CPU & OS detected
14:20:24 [App     ] Command line: -i SfM_Test_Data/ImageDataset_SceauxCastle_openmvg/reconstruction_global/sfm_data.json -l SfM_Test_Data/ImageDataset_SceauxCastle/ -o SfM_Test_Data/ImageDataset_SceauxCastle_openmvg/scene.mvs --verbosity 2
14:20:24 [App     ] Imported data: 1 cameras, 10 poses, 11 images, 2874 vertices
Segmentation fault (core dumped)
```

Debugging the application, the crash happens on the line 618
```
File::access(srcImage)
```

Further testing shows also that a simple application crashes similarly : Signal name : SIGSEGV | Signal meaning : Segmentation fault

```
#include <iostream>
#include "../../libs/MVS/Common.h"
int main()
{
    bool b(false);
    String filename("/home/user/Documents/OpenMVS_source/apps/InterfaceOpenMVG/CMakeLists.txt");
    b = File::access(filename);
    std::cout << "File access : " << b << std::endl;
    return 0;
}
```

Could you please provide some hints to deal with this problem.
Thanks,
Cheers.

PS. Probably, in the documentation the example line 
``` 
InterfaceOpenMVG2 -i sfm_data.json -o scene.mvs
```
should be changed to 
```
InterfaceOpenMVG -i sfm_data.json -o scene.mvs
```

**Comment by cdcseacave** [comment]
please use the develop branch, it was fixed there

**Comment by vfdev-5** [comment]
Yes, application works in 'develop' branch. Thank you!
Why won't you merge two branches, at least such critical commits ?
