### ISSUE TITLE
Texture Mesh gets stuck at "Assigning the best view to each face completed:"

### ISSUE THREAD

**Issue by i-am-phenomenal** [cdcseacave/openMVS#620]
Hi, 
I am running a pipeline using OpenMVG + OpenMVS and while running the pipeline, the process TextureMesh gets stuck at 
"Assigning the best view to each face completed: 5145382 faces (18m21s449ms)". Its been like this since the last 6 hours. sometimes even 12 hours. I have tried to restart the process multiple times but i have received no luck. 

System Specifications :-
OS -> Windows 10 (64 bit)
RAM -> 16 Gb
Processor -> Intel Core i5-8265U CPU @ 1.60 GHz
Graphics Card -> No graphic card

This is the pipeline that I am using. 
Assume the following,
inputDir -> Input directory where all the images are stored
matchesDir -> matchesDir where sfm_data.json is located
reconstructionDir -> Directory where the SFM data is stored
focalLength -> focal length used for calculations (Calculating it by using the formula ( max(imageHeight , imageWidth) * 1.1)

These are the commands which i am calling through my python code using subprocess
1) openMVG_main_SfMInit_ImageListing -i inputDir -o matchesDir -f focalLength
2) openMVG_main_ComputeFeatures -i matchesDir+ /sfm_data.json, -o, matchesDir, -m, "SIFT", "-p", "NORMAL"
3) openMVG_main_ComputeMatches "-i", matchesDir +"/sfm_data.json", "-o", matchesDir
4) openMVG_main_IncrementalSfM "-i",  matchesDir+"/sfm_data.json", "-m", matchesDir, "-o", reconstructionDir
5) openMVG_main_openMVG2NVM "-i", reconstructionDir + "/sfm_data.bin", "-o", reconstructionDir
6) InterfaceVisualSFM  "-w",  reconstructionDir, "-i", reconstructionDir+"/scene.nvm", "-o",  reconstructionDir + "/interfacevsfm.mvs"
7) DensifyPointCloud "-w", reconstructionDir, "-i",  reconstructionDir+"/interfacevsfm.mvs", "-o", reconstructionDir + "/point_cloud_dense.mvs"
8) ReconstructMesh "-w", reconstructionDir, "-i", reconstructionDir+"/point_cloud_dense.mvs" "-o", reconstructionDir + "/mesh.obj"
9) TextureMesh "-w", reconstructionDir, "-i", reconstructionDir+"/mesh.mvs", "-o", reconstructionDir + "/textured.obj", "--empty-color",   "0", "--patch-packing-heuristic", "0", "-v", "2", "--max-threads", "0", "--process-priority", "1"

Please ignore the quotes and the commas, the code is taken from my python script. I hope you get an idea of the commands and the command line arguments which i am passing.
It takes about 3-4 hours to complete steps 1 to 8 but for textureMesh, its been stuck for more than 6 hours. restarting textureMesh doesnt help either. Also, it used to work normally for some previous datasets which i tried my pipeline with but when i am trying with this dataset, its taking way much time. Is it normal ? It has created a mesh.mvs and a mesh.obj file in the reconstructonDir and the mesh seems to be perfectly fine in terms of volume and shape but i am not able to see anything in the console for TextureMesh apart from these logs

C:\Code\OpenMVG>TextureMesh.exe -w D:/Colmap_workspace/Statue2/reconstruction -i D:/Colmap_workspace/Statue2/reconstruction/mesh.mvs -o D:/Colmap_workspace/Statue2/reconstruction/textured.obj --empty-color 0 --patch-packing-heuristic 0 -v 2 --max-threads 0 --process-priority 1
11:33:51 [App     ] Build date: Jul  2 2016, 14:57:30
11:33:51 [App     ] CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
11:33:51 [App     ] RAM: 15.88GB Physical Memory 128.00TB Virtual Memory
11:33:51 [App     ] OS: Windows 10+ x64
11:33:51 [App     ] SSE & AVX compatible CPU & OS detected
11:33:51 [App     ] Command line: -w D:/Colmap_workspace/Statue2/reconstruction -i D:/Colmap_workspace/Statue2/reconstruction/mesh.mvs -o D:/Colmap_workspace/Statue2/reconstruction/textured.obj --empty-color 0 --patch-packing-heuristic 0 -v 2 --max-threads 0 --process-priority 1
11:33:54 [App     ] Scene loaded (2s896ms):
        51 images (51 calibrated) with a total of 779.95 MPixels (15.29 MPixels/image)
        0 points, 2572935 vertices, 5145382 faces
Initialized views 51 (100%, 1m34s552ms)
11:52:16 [App     ] Assigning the best view to each face completed: 5145382 faces (18m21s449ms)

Am i missing something ? Any help would be appreciated a lot. Thanks in advance.

**Comment by cdcseacave** [comment]
you can try using the default params; and to speed it up you can limit the image resolution using `--resolution-level 2` or 3

**Comment by i-am-phenomenal** [comment]
Thank you. However i was able to resolve it.

**Comment by qpc001** [comment]
> 谢谢你。但是我能够解决它。

How to?

**Comment by balaclava9** [comment]
> Thank you. However i was able to resolve it.

How were you able to resolve it?

For me, going from `--resolution-level=2` to `--resolution-level=3` and decimating didn't improve the speed at all.

```
07:08:35 [App     ] Command line: TextureMesh floor-vase_dense_mesh.mvs --resolution-level=2
	43 images (43 calibrated) with a total of 972.12 MPixels (22.61 MPixels/image)
	0 points, 7313202 vertices, 14623909 faces      
15:10:17 [App     ] Assigning the best view to each face completed: 14623909 faces (8h1m34s632ms)
```
```
20:58:22 [App     ] Command line: TextureMesh floor-vase_dense_mesh_refine.mvs --decimate=0.6 --resolution-level=3
	43 images (43 calibrated) with a total of 15.18 MPixels (0.35 MPixels/image)
	0 points, 7313242 vertices, 14623987 faces        
07:00:06 [App     ] Assigning the best view to each face completed: 8774322 faces (9h59m29s4ms)
```

**Comment by cdcseacave** [comment]
you should decimate a bit the mesh, 14623987 faces for 43 images is waaaaaaaaaaaaay to much, use param like: `--decimate 0.1`

**Comment by balaclava9** [comment]
Thank you! it worked!


```
11:25:42 [App     ] Command line: TextureMesh floor-vase_dense_mesh_refine.mvs --decimate=0.1 --resolution-level=2   --verbosity=5
11:26:18 [App     ] Scene loaded (35s185ms):
	43 images (43 calibrated) with a total of 15.18 MPixels (0.35 MPixels/image)
	0 points, 7313242 vertices, 14623987 faces      
11:55:45 [App     ] Mesh decimated: 14623987 -> 1462399 faces
12:49:44 [App     ] Assigning the best view to each face completed: 1462343 faces (53m14s807ms)
12:53:08 [App     ] 	global seam leveling completed (3m21s580ms)
13:47:00 [App     ] 	local seam leveling completed (53m51s934ms)
14:35:55 [App     ] 	packing texture completed: 137963 patches, 8192 texture-size (45m33s318ms)
14:35:55 [App     ] Generating texture atlas and image completed: 137963 patches, 8192 image size (1h46m10s761ms)
14:35:56 [App     ] Mesh texturing completed: 732414 vertices, 1462343 faces (2h39m26s39ms)
14:37:50 [App     ] Scene saved (1m54s504ms):
	43 images (43 calibrated)
	0 points, 732414 vertices, 1462343 faces
```

I did have success earlier this week texturing a mesh of almost 9 million faces. Is the TextureMesh process speed is somewhat dependent on the nature or complexity of the mesh, not just the number of faces?

```
08:39:10 [App     ] Command line: TextureMesh st-jq-spa_dense_mesh_refine.mvs
08:39:11 [App     ] Scene loaded (1s743ms):
        43 images (43 calibrated) with a total of 984.19 MPixels (22.89 MPixels/image)
        0 points, 4432077 vertices, 8856567 faces
10:48:11 [App     ] Assigning the best view to each face completed: 8856567 faces (2h8m59s801ms)
11:22:24 [App     ] Generating texture atlas and image completed: 138802 patches, 16384 image size (34m12s353ms)
11:22:24 [App     ] Mesh texturing completed: 4432077 vertices, 8856567 faces (2h43m12s542ms)
11:22:53 [App     ] Scene saved (28s721ms):
        43 images (43 calibrated)
        0 points, 4432077 vertices, 8856567 faces
```

**Comment by cdcseacave** [comment]
yes, but to a very small extent, the big speed dependency is number of faces

**Comment by balaclava9** [comment]
here are some more results. it seems to me that between different datasets, completion success and running time don't match number of faces.

```
dataset st-jq: --decimate=1.00:  8,856,567 faces: completed 02h43m;

dataset wb-ii: --decimate=1.00: 10,173,695 faces: completed 15h11m; local seam leveling 1h50m

dataset fvase: --decimate=0.50:  7,311,930 faces: completed 01h55m; local seam leveling 0h14m

dataset stump: --decimate=0.05:  1,230,194 faces: completed 00h11m: local seam leveling 0h5m
dataset stump: --decimate=0.10:  2,460,590 faces: completed 2h30m: local seam leveling 1h22m
dataset stump: --decimate=0.15:  3,691,355 faces: incomplete after 4h: local seam leveling never finishes.
dataset stump: --decimate=0.30:  7,382,710 faces: incomplete after 18h: local seam leveling never finishes.
```

**Comment by balaclava9** [comment]
Just for a closer look at the logs from some of the quirky TextureMesh incomplete results. the vase dataset completes with --`decimate=0.91`, but fails with `0.93`

```
22:29:53 [App     ] OpenMVS x64 v2.2.0
22:29:53 [App     ] Build date: Oct 20 2023, 16:32:07
22:29:53 [App     ] CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 cores)
22:29:53 [App     ] RAM: 16.00GB Physical Memory 16.00GB Virtual Memory
22:29:53 [App     ] OS: Darwin 20.6.0 (x86_64)
22:29:53 [App     ] Disk: 
22:29:53 [App     ] SSE & AVX compatible CPU & OS detected
22:29:53 [App     ] Command line: TextureMesh floor-vase_dense_mesh_refine.mvs --verbosity=5 --decimate=0.93
22:29:58 [App     ] Scene loaded (4s440ms):
	43 images (43 calibrated) with a total of 15.18 MPixels (0.35 MPixels/image)
	0 points, 7313242 vertices, 14623987 faces
22:29:59 [App     ] Removed 0 zero-area faces
22:30:01 [App     ] Removed 0 duplicate faces
22:30:01 [App     ] Removed 0 unreferenced vertices
Decimated faces 1023679 (100%, 20s264ms)           
22:30:24 [App     ] Mesh decimated: 14623987 -> 13600308 faces
22:30:32 [App     ] Removed 0 zero-area faces
22:30:33 [App     ] Removed 43 duplicate faces
22:30:33 [App     ] Removed 10 unreferenced vertices
22:30:38 [App     ] Removed 42 non-manifold faces
22:30:39 [App     ] Removed 0 degenerate vertices
22:30:40 [App     ] Removed 0 duplicate vertices
22:30:48 [App     ] Split 1 non-manifold vertices
22:30:55 [App     ] Split 0 non-manifold vertices
22:31:07 [App     ] Closed 4 holes and added 1 new faces
22:31:07 [App     ] Cleaned mesh: 6801403 vertices, 13600223 faces (1m9s475ms)
22:31:08 [App     ] Removed 0 zero-area faces
22:31:10 [App     ] Removed 0 duplicate faces
22:31:10 [App     ] Removed 41 unreferenced vertices
22:31:15 [App     ] Removed 0 non-manifold faces
22:31:15 [App     ] Removed 0 degenerate vertices
22:31:16 [App     ] Removed 0 duplicate vertices
22:31:24 [App     ] Split 0 non-manifold vertices
22:31:29 [App     ] Cleaned mesh: 6801362 vertices, 13600223 faces (22s45ms)
22:31:32 [App     ] Mesh saved: 6801362 vertices, 13600223 faces (2s765ms)
Initialized views 43 (100%, 3m37s986ms)          
22:42:55 [App     ] 	 0. e: 1.71799e+10	d: 0	t: 3m42s384ms
22:42:55 [App     ] Inference converged in 1 iterations: 1.71799e+10 energy (3m47s947ms)
22:48:11 [App     ] Assigning the best view to each face completed: 13600223 faces (16m39s96ms)
22:50:07 [App     ] 	color channel 0: 109 iterations, 9.93044e-05 residual
22:50:50 [App     ] 	color channel 1: 107 iterations, 9.74656e-05 residual
22:51:32 [App     ] 	color channel 2: 105 iterations, 9.65743e-05 residual
22:52:02 [App     ] 	global seam leveling completed (3m43s484ms)
```





```
10:38:41 [App     ] OpenMVS x64 v2.2.0
10:38:41 [App     ] Build date: Oct 20 2023, 16:32:07
10:38:41 [App     ] CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 cores)
10:38:41 [App     ] RAM: 16.00GB Physical Memory 16.00GB Virtual Memory
10:38:41 [App     ] OS: Darwin 20.6.0 (x86_64)
10:38:41 [App     ] Disk: 
10:38:41 [App     ] SSE & AVX compatible CPU & OS detected
10:38:41 [App     ] Command line: TextureMesh floor-vase_dense_mesh_refine.mvs --verbosity=5 --decimate=0.91
10:38:45 [App     ] Scene loaded (4s525ms):
	43 images (43 calibrated) with a total of 15.18 MPixels (0.35 MPixels/image)
	0 points, 7313242 vertices, 14623987 faces
...
Decimated faces 1316157 (100%, 22s649ms)           
...
10:40:21 [App     ] Cleaned mesh: 6655119 vertices, 13307737 faces (22s104ms)
10:40:23 [App     ] Mesh saved: 6655119 vertices, 13307737 faces (2s722ms)
Initialized views 43 (100%, 3m43s20ms)           
10:51:49 [App     ] 	 0. e: 1.71799e+10	d: 4.64251e+07	t: 3m38s999ms
10:55:53 [App     ] 	 1. e: 1.71334e+10	d: 2.17562e+09	t: 4m3s387ms
...
16:56:49 [App     ] 	99. e: 3.15651e+09	d: 346880	t: 3m47s59ms
17:00:33 [App     ] 	100. e: 3.15616e+09	d: 411392	t: 3m43s721ms
17:00:33 [App     ] Inference aborted (energy increased): 101 iterations, 3.15575e+09 energy (6h12m28s96ms)
17:03:57 [App     ] Assigning the best view to each face completed: 13307737 faces (6h23m33s634ms)
17:05:11 [App     ] 	color channel 0: 114 iterations, 9.53194e-05 residual
17:05:29 [App     ] 	color channel 1: 114 iterations, 9.79007e-05 residual
17:05:47 [App     ] 	color channel 2: 119 iterations, 9.16191e-05 residual
17:06:04 [App     ] 	global seam leveling completed (2m1s974ms)
17:54:58 [App     ] 	local seam leveling completed (48m54s441ms)
18:05:22 [App     ] 	packing texture completed: 122632 patches, 32768 texture-size (9m55s712ms)
18:05:37 [App     ] Generating texture atlas and image completed: 122632 patches, 32768 image size (1h1m39s938ms)
18:05:39 [App     ] Mesh texturing completed: 6655119 vertices, 13307737 faces (7h25m15s556ms)
18:07:54 [App     ] Scene saved (2m14s710ms):
	43 images (43 calibrated)
	0 points, 6655119 vertices, 13307737 faces
18:09:16 [App     ] Mesh saved: 6655119 vertices, 13307737 faces (1m22s357ms)
```
