### ISSUE TITLE
How to reduce RAM usage of DensifyPointCloud step?

### ISSUE THREAD

**Issue by kevinsmia1939** [cdcseacave/openMVS#626]
I would like to know if I can reduce RAM usage during DensifyPointCloud.
I use 224 images (NeuvicqCastle).

`DensifyPointCloud scene.mvs --resolution-level 5000 --min-resolution 10 --max-resolution 100`

Thinking that --resolution-level 5000 would decrease my RAM usage, but it still use more that 24 GiB which it terminated. I also tried
`DensifyPointCloud scene.mvs --resolution-level 1`
which still fail and run out of memory.
Is there other way to reduce RAM usage? Or must it be done in previous steps?

**Comment by kevinsmia1939** [comment]
```
15:37:26 [App     ] Image loaded 219: DPP_1253.JPG
15:37:26 [App     ] Image loaded 220: DPP_1254.JPG
15:37:26 [App     ] Image loaded 221: DPP_1255.JPG
15:37:26 [App     ] Image loaded 222: DPP_1256.JPG
15:37:26 [App     ] Image loaded 223: DPP_1257.JPG
15:37:26 [App     ] Scene loaded from interface format (1s175ms):
        224 images (224 calibrated) with a total of 4491.70 MPixels (20.05 MPixels/image)
        681257 points, 0 vertices, 0 faces
15:37:36 [App     ] Preparing images for dense reconstruction completed: 224 images (9s865ms)
15:37:39 [App     ] Selecting images for dense reconstruction completed: 224 images (2s476ms)
Estimated depth-maps 224 (100%, 44s168ms)           
Filtered depth-maps 224 (100%, 3m57s614ms)          
Killed

```

**Comment by cdcseacave** [comment]
you have to delete the existing `depthXXXX.map` files if you change resolution

**Comment by kevinsmia1939** [comment]
> you have to delete the existing `depthXXXX.map` files if you change resolution

Thanks for the tip it worked.
How about RefineMesh? I tried 
`RefineMesh scene_dense_mesh.mvs --resolution-level 500--scales 1`
and also delete all depthXXX.map files, but it still use more than 24 GB.

**Comment by cdcseacave** [comment]
u r still using the params wrong; `--resolution-level` is an integer down scale factor, ex 1 means to half the image resolution on each axis, so resulting a quarter of the original pixels; max-resolution is max image size, etc

**Comment by kevinsmia1939** [comment]
> u r still using the params wrong; `--resolution-level` is an integer down scale factor, ex 1 means to half the image resolution on each axis, so resulting a quarter of the original pixels; max-resolution is max image size, etc

I figured out the DensifyPointCloud but the RefineMesh I have some issue.
So the higher the --resolution-level is the memory usage should be lower right, because the image resolution is reduce? 
I tried ridiculous number like
`RefineMesh scene_dense_mesh.mvs --resolution-level 100`
but it still use over 24 GB of RAM
I have a feeling that it does not register my new --resolution-level, do you think this is the case?
I learned that DensifyPointCloud will take new --resolution-level option once I delete depthXXXX.map files, but how about RefineMesh? 

Thanks.
