### ISSUE TITLE
Translation vector and PPM matrix after interfacing colmap output!

### ISSUE THREAD

**Issue by pathi** [cdcseacave/openMVS#628]
This might sound like a silly question, however, I would like to know why the translation vector of "_InterfaceCOLMAP_" is not used to form the PPM matrix in the "_DensifyPointCloud_" step (inside Scene.cpp).
I have been debugging the code for the past few days and noticed that "pose.C.{x,y,z}" outputs after the "_t = Eigen::Map<const EVec3d>(&pose.C.x)_;" line do not affect "_imageData.camera.P_".

I might be missing something, or maybe doing something incorrectly, but any guidance would be highly appreciated!

**Comment by cdcseacave** [comment]
P is updated after K R and C are changing
