### ISSUE TITLE
how to get depth.png without color

### ISSUE THREAD

**Issue by HuangTY96** [cdcseacave/openMVS#629]
Hi,

When I do this DensifyPointCloud, I will get depth.conf.png, depth.filtered.png, depth.png and depth.raw.png, but depth.conf.png looks like some kind of mask, and the rest have RGB, and could you please tell me how to get depth.png without color?

**Comment by cdcseacave** [comment]
the depth by definition is not a color, so in order to save it as an image some kind of color assigment needs to be done; to get the real depth values read the DMAP file

**Comment by HuangTY96** [comment]
thanks for your reply,

so maybe the question is how to read DMAP file, not using Viewer tool.

**Comment by cdcseacave** [comment]
HeaderDepthDataRaw in Interface.h is all u need
