### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by yuchengzhong** [cdcseacave/openMVS#63]
e..actually i dont know how this happen
there is a lot of error without rhyme or reason 

PLY.cpp
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1117): error C2059: 语法错误:“(”
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1117): error C2061: 语法错误: 标识符“elem_data”
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1117): error C2091: 函数返回函数
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1117): error C2059: 语法错误:“)”
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1120): error C2440: “=”: 无法从“int”转换为“char **(__cdecl *(void))(void)”
1>          没有转换为函数类型，但有转换为函数的引用或指针
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1128): error C2440: “=”: 无法从“char *”转换为“char **(__cdecl *(void))(void)”
1>          没有转换为函数类型，但有转换为函数的引用或指针
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1132): error C2143: 语法错误 : 缺少“)”(在“;”的前面)
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1132): error C2143: 语法错误 : 缺少“;”(在“)”的前面)
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1132): error C2065: “k”: 未声明的标识符
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1132): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1215): error C2059: 语法错误:“(”
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1215): error C2061: 语法错误: 标识符“elem_data”
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1215): error C2091: 函数返回函数
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1215): error C2059: 语法错误:“)”
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1218): error C2440: “=”: 无法从“int”转换为“char **(__cdecl *(void))(void)”
1>          没有转换为函数类型，但有转换为函数的引用或指针
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1224): error C2440: “=”: 无法从“char *”转换为“char **(__cdecl *(void))(void)”
1>          没有转换为函数类型，但有转换为函数的引用或指针
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1228): error C2143: 语法错误 : 缺少“)”(在“;”的前面)
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1228): error C2143: 语法错误 : 缺少“;”(在“)”的前面)
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1228): error C2065: “k”: 未声明的标识符
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1228): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
2>------ 已启动生成:  项目: MVS, 配置: Release x64 ------
2>cl : 命令行 warning D9025: 正在重写“/Zm170”(用“/Zm150”)
2>cl : 命令行 warning D9002: 忽略未知选项“/arch:SSE3”
2>  Camera.cpp
2>  DepthMap.cpp
2>d:\ue4\sourcecode\openmvs-master\mvs\libs\mvs\../Common/AutoEstimator.h(464): error C3861: “cvRANSACUpdateNumIters”:  找不到标识符
2>          D:\Ue4\SourceCode\openMVS-master\MVS\libs\MVS\DepthMap.cpp(566): 参见对正在编译的函数 模板 实例化“void SEACAVE::RANSAC<MVS::PlaneSolverAdaptor,Sampler>(Kernel &,Sampler &,std::vector<boost::ulong_long_type,std::allocator<_Ty>> &,MVS::PlaneSolverAdaptor::Model &,double,double,size_t)”的引用
2>          with
2>          [
2>              Sampler=SEACAVE::UniformSampler
2>  ,            Kernel=MVS::PlaneSolverAdaptor
2>  ,            _Ty=boost::ulong_long_type
2>          ]
2>          D:\Ue4\SourceCode\openMVS-master\MVS\libs\MVS\DepthMap.cpp(603): 参见对正在编译的函数 模板 实例化“unsigned int MVS::TEstimatePlane<SEACAVE::UniformSampler,false>(const SEACAVE::Point3Arr &,SEACAVE::Plane &,double &,bool [],size_t)”的引用
2>d:\ue4\sourcecode\openmvs-master\mvs\libs\mvs\../Common/AutoEstimator.h(335): error C3861: “cvRANSACUpdateNumIters”:  找不到标识符
2>          D:\Ue4\SourceCode\openMVS-master\MVS\libs\MVS\DepthMap.cpp(570): 参见对正在编译的函数 模板 实例化“std::pair<double,double> SEACAVE::ACRANSAC<MVS::PlaneSolverAdaptor,Sampler>(Kernel &,Sampler &,std::vector<boost::ulong_long_type,std::allocator<_Ty>> &,MVS::PlaneSolverAdaptor::Model &,double,double,size_t)”的引用
2>          with
2>          [
2>              Sampler=SEACAVE::UniformSampler
2>  ,            Kernel=MVS::PlaneSolverAdaptor
2>  ,            _Ty=boost::ulong_long_type
2>          ]
2>  Image.cpp
2>  Mesh.cpp
2>D:\Ue4\SourceCode\openMVS-master\MVS\libs\MVS\Mesh.cpp(44): fatal error C1083: 无法打开包括文件: “vcg/complex/complex.h”: No such file or directory
2>  Platform.cpp
2>  PointCloud.cpp
2>  RectsBinPack.cpp
2>  Scene.cpp
2>  SceneDensify.cpp
2>D:\Ue4\SourceCode\openMVS-master\MVS\libs\MVS\SceneDensify.cpp(473): error C2593: “operator /”不明确
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\HalfFloat.h(88): 可能是“SEACAVE::hfloat SEACAVE::operator /(const SEACAVE::hfloat &,const SEACAVE::hfloat &)”
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2320): 或       “cv::MatExpr cv::operator /(const cv::Mat &,const cv::Mat &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2321): 或       “cv::MatExpr cv::operator /(const cv::Mat &,double)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2322): 或       “cv::MatExpr cv::operator /(double,const cv::Mat &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2323): 或       “cv::MatExpr cv::operator /(const cv::MatExpr &,const cv::Mat &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2324): 或       “cv::MatExpr cv::operator /(const cv::Mat &,const cv::MatExpr &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2325): 或       “cv::MatExpr cv::operator /(const cv::MatExpr &,double)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2326): 或       “cv::MatExpr cv::operator /(double,const cv::MatExpr &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2327): 或       “cv::MatExpr cv::operator /(const cv::MatExpr &,const cv::MatExpr &)”[使用参数相关的查找找到]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1268): 或       “SEACAVE::TPoint3<double> SEACAVE::operator /<float>(const SEACAVE::TPoint3<double> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=float
2>          ]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1263): 或       “SEACAVE::TPoint3<float> SEACAVE::operator /<float>(const SEACAVE::TPoint3<float> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=float
2>          ]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1174): 或       “SEACAVE::TPoint2<double> SEACAVE::operator /<float>(const SEACAVE::TPoint2<double> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=float
2>          ]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1169): 或       “SEACAVE::TPoint2<float> SEACAVE::operator /<float>(const SEACAVE::TPoint2<float> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=float
2>          ]
2>          尝试匹配参数列表“(cv::Point_<double>, float)”时
2>D:\Ue4\SourceCode\openMVS-master\MVS\libs\MVS\SceneDensify.cpp(935): error C2593: “operator /”不明确
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\HalfFloat.h(88): 可能是“SEACAVE::hfloat SEACAVE::operator /(const SEACAVE::hfloat &,const SEACAVE::hfloat &)”
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2320): 或       “cv::MatExpr cv::operator /(const cv::Mat &,const cv::Mat &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2321): 或       “cv::MatExpr cv::operator /(const cv::Mat &,double)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2322): 或       “cv::MatExpr cv::operator /(double,const cv::Mat &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2323): 或       “cv::MatExpr cv::operator /(const cv::MatExpr &,const cv::Mat &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2324): 或       “cv::MatExpr cv::operator /(const cv::Mat &,const cv::MatExpr &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2325): 或       “cv::MatExpr cv::operator /(const cv::MatExpr &,double)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2326): 或       “cv::MatExpr cv::operator /(double,const cv::MatExpr &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2327): 或       “cv::MatExpr cv::operator /(const cv::MatExpr &,const cv::MatExpr &)”[使用参数相关的查找找到]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1268): 或       “SEACAVE::TPoint3<double> SEACAVE::operator /<float>(const SEACAVE::TPoint3<double> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=float
2>          ]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1263): 或       “SEACAVE::TPoint3<float> SEACAVE::operator /<float>(const SEACAVE::TPoint3<float> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=float
2>          ]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1174): 或       “SEACAVE::TPoint2<double> SEACAVE::operator /<float>(const SEACAVE::TPoint2<double> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=float
2>          ]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1169): 或       “SEACAVE::TPoint2<float> SEACAVE::operator /<float>(const SEACAVE::TPoint2<float> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=float
2>          ]
2>          尝试匹配参数列表“(cv::Point_<float>, float)”时
2>D:\Ue4\SourceCode\openMVS-master\MVS\libs\MVS\SceneDensify.cpp(1001): error C2593: “operator /”不明确
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\HalfFloat.h(88): 可能是“SEACAVE::hfloat SEACAVE::operator /(const SEACAVE::hfloat &,const SEACAVE::hfloat &)”
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2320): 或       “cv::MatExpr cv::operator /(const cv::Mat &,const cv::Mat &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2321): 或       “cv::MatExpr cv::operator /(const cv::Mat &,double)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2322): 或       “cv::MatExpr cv::operator /(double,const cv::Mat &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2323): 或       “cv::MatExpr cv::operator /(const cv::MatExpr &,const cv::Mat &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2324): 或       “cv::MatExpr cv::operator /(const cv::Mat &,const cv::MatExpr &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2325): 或       “cv::MatExpr cv::operator /(const cv::MatExpr &,double)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2326): 或       “cv::MatExpr cv::operator /(double,const cv::MatExpr &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2327): 或       “cv::MatExpr cv::operator /(const cv::MatExpr &,const cv::MatExpr &)”[使用参数相关的查找找到]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1268): 或       “SEACAVE::TPoint3<double> SEACAVE::operator /<float>(const SEACAVE::TPoint3<double> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=float
2>          ]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1263): 或       “SEACAVE::TPoint3<float> SEACAVE::operator /<float>(const SEACAVE::TPoint3<float> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=float
2>          ]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1174): 或       “SEACAVE::TPoint2<double> SEACAVE::operator /<float>(const SEACAVE::TPoint2<double> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=float
2>          ]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1169): 或       “SEACAVE::TPoint2<float> SEACAVE::operator /<float>(const SEACAVE::TPoint2<float> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=float
2>          ]
2>          尝试匹配参数列表“(cv::Point_<float>, float)”时
2>  SceneReconstruct.cpp
2>C:\Program Files\CGAL\include\CGAL/gmp.h(30): fatal error C1083: 无法打开包括文件: “gmp.h”: No such file or directory
2>  SceneRefine.cpp
2>d:\ue4\sourcecode\openmvs-master\mvs\libs\mvs\Mesh.h(222): error C2593: “operator /”不明确
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\HalfFloat.h(88): 可能是“SEACAVE::hfloat SEACAVE::operator /(const SEACAVE::hfloat &,const SEACAVE::hfloat &)”
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2320): 或       “cv::MatExpr cv::operator /(const cv::Mat &,const cv::Mat &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2321): 或       “cv::MatExpr cv::operator /(const cv::Mat &,double)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2322): 或       “cv::MatExpr cv::operator /(double,const cv::Mat &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2323): 或       “cv::MatExpr cv::operator /(const cv::MatExpr &,const cv::Mat &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2324): 或       “cv::MatExpr cv::operator /(const cv::Mat &,const cv::MatExpr &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2325): 或       “cv::MatExpr cv::operator /(const cv::MatExpr &,double)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2326): 或       “cv::MatExpr cv::operator /(double,const cv::MatExpr &)”[使用参数相关的查找找到]
2>          D:\Opencv\Opencv3.0\opencv\sources\modules\core\include\opencv2/core/mat.hpp(2327): 或       “cv::MatExpr cv::operator /(const cv::MatExpr &,const cv::MatExpr &)”[使用参数相关的查找找到]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1268): 或       “SEACAVE::TPoint3<double> SEACAVE::operator /<int>(const SEACAVE::TPoint3<double> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=int
2>          ]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1263): 或       “SEACAVE::TPoint3<float> SEACAVE::operator /<int>(const SEACAVE::TPoint3<float> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=int
2>          ]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1174): 或       “SEACAVE::TPoint2<double> SEACAVE::operator /<int>(const SEACAVE::TPoint2<double> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=int
2>          ]
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\common\Types.inl(1169): 或       “SEACAVE::TPoint2<float> SEACAVE::operator /<int>(const SEACAVE::TPoint2<float> &,TYPEM)”
2>          with
2>          [
2>              TYPEM=int
2>          ]
2>          尝试匹配参数列表“(cv::Point3_<double>, int)”时
2>          d:\ue4\sourcecode\openmvs-master\mvs\libs\mvs\Mesh.h(211): 编译类 模板 成员函数“void MVS::TRasterMesh<MeshRefine::RasterMesh>::Project(const MVS::Mesh::Face &)”时
2>          D:\Ue4\SourceCode\openMVS-master\MVS\libs\MVS\SceneRefine.cpp(760): 参见对正在编译的函数 模板 实例化“void MVS::TRasterMesh<MeshRefine::RasterMesh>::Project(const MVS::Mesh::Face &)”的引用
2>          D:\Ue4\SourceCode\openMVS-master\MVS\libs\MVS\SceneRefine.cpp(99): 参见对正在编译的类 模板 实例化“MVS::TRasterMesh<MeshRefine::RasterMesh>”的引用
2>  SceneRefineCUDA.cpp
2>  SceneTexture.cpp
2>D:\Ue4\SourceCode\openMVS-master\MVS\libs\MVS\SceneTexture.cpp(797): fatal error C1001: 编译器中发生内部错误。

**Comment by cdcseacave** [comment]
sorry, I don't speak any of the Asian languages
Are you trying to use OpenMVS with Unreal Engine 4?
I am interested in what is the use you plan for it. Can you detail a bit about your intentions?

**Comment by yuchengzhong** [comment]
Hi,Im trying to use English but my compiler'`s language is set to Chinese.Anyway,forget those Chinese Character XD.
I m trying to complie OpenMVS in vs 2013,and wanna put it into UE4,I thought it would be cool.But after I 
 make sure everything's ready,there were many compiler errors....It reported many wrong grammars which were correct formerly

But my OpenMVG can be use properly.How can I solve this problem?
The error are:
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1117): error C2059: 
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1117): error C2061: 
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1117): error C2091: 
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1117): error C2059: 
1>D:\Ue4\SourceCode\openMVS-master\MVS\libs\IO\PLY.cpp(1120): error C2440: “int” castto“char *(__cdecl *(void))(void)”

**Comment by cdcseacave** [comment]
I can not see any error message, but it seems there is something terrible wrong. I develop OpenMVS on windows, so windows is the native OS, it should work. I am using VC2015, but should work on VC2013 as well.

**Comment by yuchengzhong** [comment]
Because of my complier 's language.....I could only show you the error code..in "MVS\libs\IO\PLY.cpp"this file ,there is something terrible wrong.....
Do you have an complied programme?or dll?

**Comment by cdcseacave** [comment]
https://github.com/cdcseacave/openMVS_sample

**Comment by riyueshi** [comment]
if you use vc2013 the error within PLY.cpp  can be solved by change line 1118 to "char **store_array = ((char**)(elem_data + prop->offset));" and line 1216 to "char **store_array = ((char**)(elem_data + prop->offset));". I don't know why it doesn't work by using the constructor initialization

**Comment by cdcseacave** [comment]
thx @riyueshi 
I have updated the code

**Comment by cdcseacave** [comment]
apparently VC2013 has problems with this code, pls use VC2015
