### ISSUE TITLE
Divide the PointClouds to ReconstructMesh and RefineMesh

### ISSUE THREAD

**Issue by tftangming** [cdcseacave/openMVS#633]
I try to divide the pointclouds in the process of ReconstructMesh and I can get the tile meshes. Note that every .mvs files save the all images so it exists the condition that some images cannot seen the tile mesh.
When I send one scene_dense_mesh0.mvs file according one tile mesh 0 into the RefineMesh, I find some error occur in the ProjectMesh function. And I find the problem occur when the view seen no faces of the input mesh.
THe follow pictures are related debug information.
![bug询问](https://user-images.githubusercontent.com/39753580/101112407-2868bd80-3618-11eb-9eef-fd97bac0331a.png)
![bug询问2](https://user-images.githubusercontent.com/39753580/101112410-2b63ae00-3618-11eb-87a8-6c8f48fa66d3.png)

**Comment by cdcseacave** [comment]
disable CUDA

**Comment by tftangming** [comment]
Thanks!
