### ISSUE TITLE
holes in the mesh

### ISSUE THREAD

**Issue by tftangming** [cdcseacave/openMVS#634]
When I reconstruct the urban dataset for a realistic mesh, I find there are some large holes in the side of the building main because of the absence of point clouds. And I try to use the Possion Method, the problem are solved.So how can i get a better result.
![openMVS结果](https://user-images.githubusercontent.com/39753580/101300408-74ae3a80-3870-11eb-8651-3129de4debed.png)
openMVS result
![possion结果](https://user-images.githubusercontent.com/39753580/101300421-80016600-3870-11eb-820d-e4b40c5737a0.png)
possion result

**Comment by cdcseacave** [comment]
you can use the Poisson mesh; in OpenMVS use it with `--mesh-files <external-mesh>`
