### ISSUE TITLE
TextureMesh process completes with no output and no error

### ISSUE THREAD

**Issue by IDEA-V** [cdcseacave/openMVS#636]
I used the Swiss quarry dataset  from sensefly.
The log shows that the whole process has been completed with no error, but there's no textured mesh outputed by it.
It doesn't seems like a out of memory issue because the whole process takes only about 10% of my memory.
Is there any way to know exactly what the problem is?

TextureMesh .\scene_dense_mesh_refine.mvs
19:39:25 [App     ] Build date: Jul  2 2020, 10:09:18
19:39:25 [App     ] CPU: AMD Ryzen Threadripper 3970X 32-Core Processor  (64 cores)
19:39:25 [App     ] RAM: 255.90GB Physical Memory 128.00TB Virtual Memory
19:39:25 [App     ] OS: Windows 8 x64
19:39:25 [App     ] SSE & AVX compatible CPU & OS detected
19:39:25 [App     ] Command line: .\scene_dense_mesh_refine.mvs
19:39:26 [App     ] Scene loaded (1s132ms):
        127 images (125 calibrated) with a total of 1430.51 MPixels (11.44 MPixels/image)
        0 points, 1368319 vertices, 2649161 faces
Initialized views 127 (100%, 18s513ms)
19:41:10 [App     ] Assigning the best view to each face completed: 2649161 faces (1m36s73ms)

**Comment by IDEA-V** [comment]
Well, I looked into the source code and I find out that the process has been aborted, not completed. Run the program on ubuntu will show the following log:

terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted (core dumped)

I think this is a bug.

**Comment by cdcseacave** [comment]
is the input mesh manifold?

**Comment by IDEA-V** [comment]
> is the input mesh manifold?

I've seen some other issues and I did clean the non-manifold edges by removing faces in MeshLab

**Comment by IDEA-V** [comment]
Hello? Do you have any ideas? @cdcseacave

**Comment by cdcseacave** [comment]
no, and can't help without any debugging data
