### ISSUE TITLE
Ubuntu 18.04 snap installation failed to execute openmvs.DensifyPointCloud

### ISSUE THREAD

**Issue by laGataDelDiablo** [cdcseacave/openMVS#640]
I pulled an image from osboxes.org. Then i triggered Ubuntu/software graphical installation of openmvs. 
Upload from windows host to Ubuntu virtualbox VM. An export folder from regard3d program to ubuntu vm. (I successfully reconstructed those images in win 10 and openMVS)
win 10 alike I used a variable to reach image and workfolder, which are the same plus an outputfile.

It raised an error from libdc1394, so I google for this issue and found ln command should fix this; or ignore!?
The scene.mvs file is in the image folder as shown below
Snap/bin is in the path. 
To add -v 3 debug did not helped at all.

In Ubuntu terminal:

osboxes@osboxes:~$ sudo ln /dev/null /dev/raw1394
[sudo] password for osboxes: 

osboxes@osboxes:~$ work_dir="/home/osboxes/_3dtests/test-10/OpenMVSworkon"

osboxes@osboxes:~$ openmvs.DensifyPointCloud  -w $work_dir -i $work_dir -o $work_dir/scene_dense.mvs 
libdc1394 error: Failed to initialize libdc1394
15:39:19 [App     ] Build date: Mar 15 2017, 11:57:05
15:39:19 [App     ] CPU: Intel(R) Xeon(R) CPU E5-2680 0 @ 2.70GHz
15:39:19 [App     ] RAM: 62.81GB Physical Memory 8.38GB Virtual Memory
15:39:19 [App     ] OS: Linux 5.4.0-58-generic (x86_64)
15:39:19 [App     ] SSE & AVX compatible CPU & OS detected
15:39:19 [App     ] Command line: -w /home/osboxes/_3dtests/test-10/OpenMVSworkon -i /home/osboxes/_3dtests/test-10/OpenMVSworkon -o /home/osboxes/_3dtests/test-10/OpenMVSworkon/scene_dense.mvs
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted (core dumped)

osboxes@osboxes:~$ ls "/home/osboxes/_3dtests/test-10/OpenMVSworkon"
DensifyPointCloud-2012251526198B5000.log  image000001.jpg  image000003.jpg  image000005.jpg  image000007.jpg  image000009.jpg
image000000.jpg                           image000002.jpg  image000004.jpg  image000006.jpg  image000008.jpg  scene.mvs

osboxes@osboxes:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

To get an idia of what that should be used for is running this config in google colab.
Colab is using ubuntu 18.04 this time.

Thank you for your efford; and I like your style to handle this project.

**Comment by cdcseacave** [comment]
I did not create the snap package and I do not manage it either. In fact I didn't even knew it existed. Pls ask the author. Thx
