### ISSUE TITLE
with cuda some problems have occurred

### ISSUE THREAD

**Issue by HW-hideonbush** [cdcseacave/openMVS#641]
it seemed to be the reason for different versions. 
my cuda is 10.2 ， platform ：windows , ide：vs2019
the compiling is success . but , when i used the  library ，i saw the problem 
![image](https://user-images.githubusercontent.com/67229194/103496976-18443800-4e7b-11eb-9285-e2e8594f2aa2.png)
which was declared negative.
i know a litte about cuda , has this function been replaced?

**Comment by cdcseacave** [comment]
pls disable CUDA in CMAKE (there is a flag you need to set to OFF)

**Comment by HW-hideonbush** [comment]
> pls disable CUDA in CMAKE (there is a flag you need to set to OFF)

does this part of the code about cuda not support to update ?

**Comment by WilliamOChai** [comment]
Can you compile openmvs with cuda，I faild. Could you please help me.
