### ISSUE TITLE
cannot compile with a specific CGAL header

### ISSUE THREAD

**Issue by raphaelsulzer** [cdcseacave/openMVS#643]
I have openMVS linked to a project that heavily relies on CGAL. I have never had any issues before.
But now I wanted to include the CGAL header

> #include <CGAL/Surface_mesh_approximation/approximate_triangle_mesh.h>

which leads to a lot of errors starting here:

> /home/raphael/cpp/openMVS/libs/Common/Log.h:135: error: expected ‘}’ before ‘::’ token
#define GET_LOG()   SEACAVE::Log::GetInstance()

I tried to include this header directly in e.g. the densifyPointCloud app which leads to the same.

I am using CGAL 5.1
Any idea how to fix this?

**Comment by cdcseacave** [comment]
most probably there is a name conflict between some defines and function names, etc
detect which is the conflict and use the `pop` and 'push` functionality to isolate that header

**Comment by cdcseacave** [comment]
```
#pragma push_macro("VERBOSE")
#undef VERBOSE
#include <CGAL/Surface_mesh_approximation/approximate_triangle_mesh.h>
#pragma pop_macro("VERBOSE")
````
