### ISSUE TITLE
Viewer display white on texture

### ISSUE THREAD

**Issue by chn-lee-yumi** [cdcseacave/openMVS#645]
**Describe the bug**
I use 128 images with a total of 1464.84 MPixels (11.44 MPixels/image) to build the model. But the output file of TextureMesh is something wrong. I use Viewer to open the mvs and ply file, but what I see is the model is totally whiten. I used about 50 images to build a model before, all is well. So I wonder if TextureMesh has some bug when it processes a large amount of pixels?

**To Reproduce**
1. `openMVG_main_openMVG2openMVS -i sfm_data.bin -o scene.mvs`
2. `DensifyPointCloud scene.mvs`
3. `ReconstructMesh scene_dense.mvs`
4. `RefineMesh scene_dense_mesh.mvs`
5. `TextureMesh scene_dense_mesh_refine.mvs`

**Expected behavior**
It should show the texture as usual.

**Screenshots**
After TextureMesh: (`scene_dense_mesh_refine_texture.ply`, `scene_dense_mesh_refine_texture.mvs` is the same)
![image](https://user-images.githubusercontent.com/20398519/106360965-550a2e80-6356-11eb-8e99-d42b4d20fe15.png)
Before TextureMesh: (`scene_dense_mesh_refine.mvs `)
![image](https://user-images.githubusercontent.com/20398519/106360988-72d79380-6356-11eb-97cf-9aea2b3dae2b.png)

**Desktop (please complete the following information):**
 - OS: Debian 10.6 (server), macOS 10.15.7 (client running viewer)
 - Version: master branch (build on Jan 22 2021)

**Additional context**
These files are too big, it may be a reason:
```
-rw-r--r-- 1 root root 257M Jan 30 12:55 scene_dense_mesh.mvs
-rw-r--r-- 1 root root 489M Jan 30 12:55 scene_dense_mesh.ply
-rw-r--r-- 1 root root  32M Jan 30 14:23 scene_dense_mesh_refine.mvs
-rw-r--r-- 1 root root  59M Jan 30 14:23 scene_dense_mesh_refine.ply
-rw-r--r-- 1 root root 923M Jan 30 14:32 scene_dense_mesh_refine_texture.mvs
-rw-r--r-- 1 root root 136M Jan 30 14:34 scene_dense_mesh_refine_texture.ply
-rw-r--r-- 1 root root 345M Jan 30 14:34 scene_dense_mesh_refine_texture.png
-rw-r--r-- 1 root root 1.9G Jan 30 12:30 scene_dense.mvs
-rw-r--r-- 1 root root 1.2G Jan 30 12:31 scene_dense.ply
-rw-r--r-- 1 root root  12M Jan 30 11:54 scene.mvs
```
I tried to use `three.js` to load the file `scene_dense_mesh_refine_texture.ply` and `scene_dense_mesh_refine_texture.png`, but also failed.
![image](https://user-images.githubusercontent.com/20398519/106361319-402e9a80-6358-11eb-8a76-3265b74180c9.png)
By the way, I tried to use ffprobe to see `scene_dense_mesh_refine_texture.png` property, and it return an error:
```
ffprobe version 4.1.6-1~deb10u1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[IMGUTILS @ 0x7fff49b17e50] Picture size 32768x32768 is invalid
[png @ 0x5635d4964100] [IMGUTILS @ 0x7fff49b176a0] Picture size 32768x32768 is invalid
[png @ 0x5635d4964100] Invalid image size
[png_pipe @ 0x5635d4962000] Stream #0: not enough frames to estimate rate; consider increasing probesize
[png_pipe @ 0x5635d4962000] decoding for stream 0 failed
[png_pipe @ 0x5635d4962000] Could not find codec parameters for stream 0 (Video: png, none(pc)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, png_pipe, from 'scene_dense_mesh_refine_texture.png':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: png, none(pc), 25 tbr, 25 tbn, 25 tbc
```

**Comment by cdcseacave** [comment]
can u see the texture PNG file?

**Comment by chn-lee-yumi** [comment]
> can u see the texture PNG file?

Yes, I can.
<img width="920" alt="image" src="https://user-images.githubusercontent.com/20398519/106363922-78d57080-6366-11eb-9184-bbfeb5310553.png">

**Comment by chn-lee-yumi** [comment]
Update:

I tried to add `--resolution-level 2` to reduce the size of texture, then it can show normally.
```
TextureMesh --resolution-level 2 scene_dense_mesh_refine.mvs
```
<img width="585" alt="image" src="https://user-images.githubusercontent.com/20398519/106364949-4da24f80-636d-11eb-8592-ae3edec2bdeb.png">
The png size is 8192x8192. File sizes are below: (files end with `.bk` are not used `--resolution-level 2`)
```
-rwxr-xr-x 1 root root 176M Jan 30 18:30 scene_dense_mesh_refine_texture.mvs
-rwxr-xr-x 1 root root 923M Jan 30 14:32 scene_dense_mesh_refine_texture.mvs.bk
-rwxr-xr-x 1 root root 136M Jan 30 18:31 scene_dense_mesh_refine_texture.ply
-rwxr-xr-x 1 root root 136M Jan 30 14:34 scene_dense_mesh_refine_texture.ply.bk
-rwxr-xr-x 1 root root  57M Jan 30 18:31 scene_dense_mesh_refine_texture.png
-rwxr-xr-x 1 root root 345M Jan 30 14:34 scene_dense_mesh_refine_texture.png.bk
```

**Comment by cdcseacave** [comment]
most probably the GPU has not enough memory to load big textures
