### ISSUE TITLE
in SemiGlobalMatcher::ConsistencyCrossCheck functions, i think v = (c - ld, r)

### ISSUE THREAD

**Issue by Why384040146** [cdcseacave/openMVS#646]
when left2right xl - lr = ld. that is: Disparity& ld = l2r(r,c);
comes with right2left xr should be xr = xl - ld. that is : const ImageRef v(c - ld,r);   Is it right?

**Comment by cdcseacave** [comment]
to me the function looks ok;
what is not working on your side?

**Comment by Why384040146** [comment]
i check the code leftimage as right camera. so it is opposite.
