### ISSUE TITLE
Welcome to OpenMVS learning team!

### ISSUE THREAD

**Issue by electech6** [cdcseacave/openMVS#647]
OpenMVS is an excellent library for Multi-View Stereo reconstruction. Thanks for the authors!

However, green hands come across many problems when run or study the code, and the authors maybe too busy to reply the issues timely. So I create a learning team. Just contact me (wechat id: cvlife6) with comments "OpenMVS" and I will invite you.

**Comment by Yannnnnnnnnnnn** [comment]
it's not a good idea to post AD here.

**Comment by electech6** [comment]
> it's not a good idea to post AD here.

It's a good idea to offer the opportunity for people to connect and collaborate.
