### ISSUE TITLE
How can i  Improve accuracy in DensifyPointCloud using tSGM algorithm? 

### ISSUE THREAD

**Issue by Why384040146** [cdcseacave/openMVS#649]
Recently I use the OpenMVS tSGM alogrithm to Implement dense image matching, I test many paras in the algorithm (windows size, P1, P2), But has not a very good result(Single depth  or fused result) ablow. the pointcloud is always coarse. Can you give me some advises to have a relatived good result.

single_depth:
![single_depth](https://user-images.githubusercontent.com/17980581/108684163-7f9e7000-752d-11eb-9300-70dbdd3b6ffa.png)

fused_depth:
![fused_depth](https://user-images.githubusercontent.com/17980581/108684193-8af19b80-752d-11eb-85bf-b5fd3035fa19.png)

**Comment by cdcseacave** [comment]
Which are the command lines you use?
The algorithm can always have room for improvement, I tried to set the default params that work best in most cases. But usually the resolution at which the images are processed affects the most final accuracy. 
From what I can see above the results look good, what exactly do you want to improve?

**Comment by Why384040146** [comment]
I use the command para: FusionMode = -1 , nResolutionLevel = 0 and the image resultion is 1600*1200.  As above pointcloud, I found it is not smooth (rough).   and  I found rectify image pair blow,   the shape change a alittle which will affect image match ?

left rectify image:
![left_rectify](https://user-images.githubusercontent.com/17980581/108793827-7231c600-75bf-11eb-8f02-2bf6788a3eea.png)

right rectify image:
![right_rectify](https://user-images.githubusercontent.com/17980581/108793866-85449600-75bf-11eb-9d76-988b5c491519.png)

**Comment by cdcseacave** [comment]
what do you mean by `image pair blow, the shape change a alittle`, it is not obvious to me in the images above?
at first look they seem as they should
