### ISSUE TITLE
Sometimes certain subscenes cannot be reconstructed

### ISSUE THREAD

**Issue by pierotofy** [cdcseacave/openMVS#660]
**Describe the bug**

A scene is being split for point densification. Of the resulting sub scenes, some can be reconstructed, but some can't. This creates incomplete reconstructions in some cases.

![image](https://user-images.githubusercontent.com/1951843/110973642-80a40f80-832b-11eb-88b1-a7c8b6d0230b.png)

Instead of:

![image](https://user-images.githubusercontent.com/1951843/110973696-8ef22b80-832b-11eb-8fef-e3a3a7d10eb5.png)

**To Reproduce**

OpenMVS project files: https://testhub1.dronedb.app/r/pierotofy/0f5869ed232a487fb5dea9ddb8c9827c
Input images (raw): https://github.com/pierotofy/dataset_banana

Commands used:

```
DensifyPointCloud "/datasets/banana/opensfm/undistorted/openmvs/scene.mvs"  --resolution-level 1 --min-resolution 1504 --max-resolution 3008 --max-threads 4 --number-views-fuse 2 -w "/datasets/banana/opensfm/undistorted/openmvs/depthmaps" -v 0 --fusion-mode 1
```

This works perfectly to compute the depthmaps.

We split the scene via:

```
DensifyPointCloud "/datasets/banana/opensfm/undistorted/openmvs/scene.mvs" --sub-scene-area 330000 --max-threads 4 -w "/datasets/banana/opensfm/undistorted/openmvs/depthmaps" -v 0
```

This creates 9 sub scenes. I tweaked the sub-scene-area parameter to reproduce this bug, it probably creates too many scenes for this small dataset (but I was able to reproduce it with a larger parameter in the past and with fewer scenes).

For each scene, I run:

```
DensifyPointCloud "/datasets/banana/opensfm/undistorted/openmvs/scene_XXXX.mvs" --resolution-level 1 --min-resolution 1504 --max-resolution 3008 --dense-config-file "/datasets/banana/opensfm/undistorted/openmvs/config.ini" --number-views-fuse 2 --max-threads 4 -w "/datasets/banana/opensfm/undistorted/openmvs/depthmaps" -v 0
```

Some scenes reconstruct successfully, while others don't. Specifically this fails for:

```
scene_0006.mvs
scene_0003.mvs
scene_0008.mvs
scene_0007.mvs
scene_0005.mvs
scene_0009.mvs
scene_0002.mvs
```

The error are:

```
17:14:04 [App     ] Build date: Mar  1 2021, 16:04:19
17:14:04 [App     ] CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 cores)
17:14:04 [App     ] RAM: 23.35GB Physical Memory 0B Virtual Memory
17:14:04 [App     ] OS: Linux 5.11.2-arch1-1 (x86_64)
17:14:04 [App     ] SSE & AVX compatible CPU & OS detected
17:14:04 [App     ] Command line: /datasets/banana/opensfm/undistorted/openmvs/scene_0006.mvs --resolution-level 1 --min-resolution 1504 --max-resolution 3008 --dense-config-file /datasets/banana/opensfm/undistorted/openmvs/config.ini --number-views-fuse 2 --max-threads 4 -w /datasets/banana/opensfm/undistorted/openmvs/depthmaps -v 2
17:14:04 [App     ] Scene loaded (0ms):
	1 images (1 calibrated) with a total of 5.74 MPixels (5.74 MPixels/image)
	0 points, 0 vertices, 0 faces
17:14:04 [App     ] error: empty initial point-cloud
```

Or:

```
17:14:35 [App     ] Build date: Mar  1 2021, 16:04:19
17:14:35 [App     ] CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 cores)
17:14:35 [App     ] RAM: 23.35GB Physical Memory 0B Virtual Memory
17:14:35 [App     ] OS: Linux 5.11.2-arch1-1 (x86_64)
17:14:35 [App     ] SSE & AVX compatible CPU & OS detected
17:14:35 [App     ] Command line: /datasets/banana/opensfm/undistorted/openmvs/scene_0003.mvs --resolution-level 1 --min-resolution 1504 --max-resolution 3008 --dense-config-file /datasets/banana/opensfm/undistorted/openmvs/config.ini --number-views-fuse 2 --max-threads 4 -w /datasets/banana/opensfm/undistorted/openmvs/depthmaps -v 2
17:14:35 [App     ] Scene loaded (0ms):
	0 images (0 calibrated) with a total of 0.00 MPixels (-nan MPixels/image)
	0 points, 0 vertices, 0 faces
17:14:35 [App     ] error: empty initial point-cloud
```

On https://github.com/OpenDroneMap/ODM/pull/1236 YanNoun from OpenSfM suggested to tweak https://github.com/cdcseacave/openMVS/commit/7a88fefb0476fa4f6229e228a69641ff3febeb10#diff-66d736c1d38c1b27ace4b48ffbf5a91639659add7b752ea4fb7070b347b1a01cR866 and https://github.com/cdcseacave/openMVS/commit/7a88fefb0476fa4f6229e228a69641ff3febeb10#diff-66d736c1d38c1b27ace4b48ffbf5a91639659add7b752ea4fb7070b347b1a01cR752. I haven't tried to do that.

**Expected behavior**

Probably that just a set of valid scenes be computed.

**Screenshots**

See above.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (via docker)
 - Browser N/A
 - Version: `develop`

**Additional context**

N/A

**Comment by cdcseacave** [comment]
Thank you for this detailed test, I'll look into it as soon as I can.

**Comment by CanCanZeng** [comment]
Hi @pierotofy , can you look into the log of `DensifyPointCloud "/datasets/banana/opensfm/undistorted/openmvs/scene.mvs" --sub-scene-area 330000 --max-threads 4 -w "/datasets/banana/opensfm/undistorted/openmvs/depthmaps" -v 0`, I guess some scene has no point so the reconstruction will fail. If it is true, you may increase the `sub-scene-area` parameter to get less number of sub-scene but each one of them will have point, then you can successfully reconstruct each of them.

I guess before you split the large scene, you should have already reconstructed the whole scene, so you don't have to do DensifyPointCloud for every sub-scene, just run ReconstructMesh on every sub-scene is enough.

**Comment by cdcseacave** [comment]
The problem I suspect is that some sub-scenes can have any small number of camera, even just 1, as there is no explicit control on the number of cameras in a sub-scene. It should be easy to add that check, and deny the split in the first place.

**Comment by pierotofy** [comment]
I had also noticed during one of my tests (I don't remember how I reproduced it) that in one case one of the sub-scenes had 4 cameras in it (which should be sufficient), but probably due to https://github.com/cdcseacave/openMVS/blob/master/libs/MVS/SceneDensify.cpp#L282 it would end up selecting only 1, which led to an error.

**Comment by cdcseacave** [comment]
I've added in the latest develop functionality to merge too small (<5 images) sub-scenes into larger ones. The approach I took can have two issues:
- it is possible that the memory cap to be exceeded
- there can appear some overlap between sub-scenes because the bounding-boxes are merged without checking for compatibility (same dimensions on the common sizes)
Please let me know if any of these become a problem, and I will look into a different strategy to do the merge.

**Comment by pierotofy** [comment]
That's awesome @cdcseacave ! I'll test this sometimes in the upcoming weeks.
