### ISSUE TITLE
What's the meaning of area in scene split

### ISSUE THREAD

**Issue by CanCanZeng** [cdcseacave/openMVS#661]
Hi, thank you for adding scene split function recently, it's very useful for very large scene!

I use `DensifyPointCloud -i scene_dense.mvs --sub-scene-area 20000000` to split a large scene. But I don't know the meaning of scene-area, I looked into the code and find that `area = Footprint * areaScale`, in which `areaScale = 0.01` and `Footprint = focalLength / pointDepth`.  I'm not sure what the Footprint means, does it stands for the area of a surface that project to this pixel?

Can we just specify how many sub-scene we want? The sub-scene-area is not very intuitive, but most of time I know how many sub-scene I should get because I know how many images my computer can hanld at once. Besides, I think specify the number of sub-scene is more suitable for auto-reconstruction.

**Comment by Why384040146** [comment]
@cdcseacave     the cmd “DensifyPoint scene.mvs --sub-scene-area 660000 --max-threads 4 -w "sheffield_cross/opensfm/undistorted/openmvs/depthmaps" -v 0 “  you say that:   for example you can use the bellow value to limit memory usage to ~16GB.  

I wanna  know, how you calculate the most memory used 16GB ?

**Comment by cdcseacave** [comment]
I'm afraid there is no exact formula to compute it, pls use trial approach
