### ISSUE TITLE
How to build openMVS with eigen3.2？ if I have installed eigen3.3

### ISSUE THREAD

**Issue by fightmoney** [cdcseacave/openMVS#663]
I have installed Eigen3.3.9, but openMVS require Eigen3.2 ,so how to install openMVS? If I dont uninstall Eigen3.3.

**Comment by cdcseacave** [comment]
that is easy, just point cmake to the 3.2 version using `-DEIGEN_ROOT`
however I think they fixed the latest eigen version, and 3.3.9 works too
