### ISSUE TITLE
DensifyPointCloud  std::bad_alloc Aborted (core dumped)

### ISSUE THREAD

**Issue by Ryujinosorus** [cdcseacave/openMVS#665]
Hello,
I am only starting in the field of photogrammetry

Im using a sh script to render data 

```test $# = 0 && exit 1

openMVG_main_SfMInit_ImageListing -i $1 -o Features -f 4838.4

openMVG_main_ComputeFeatures -i Features/sfm_data.json -o Features 

openMVG_main_ComputeMatches -i Features/sfm_data.json -o Features 

openMVG_main_IncrementalSfM -i Features/sfm_data.json -m Features/ -o PointCloud 

openMVG_main_ComputeSfM_DataColor  -i PointCloud/sfm_data.bin -o PointCloud/colored.ply 

openMVG_main_ComputeStructureFromKnownPoses -i PointCloud/sfm_data.bin -m Features -o PointCloud/robust.bin -f Features/matches.f.bin

openMVG_main_openMVG2openMVS -i PointCloud/robust.bin -d . -o scene.mvs

openmvs.DensifyPointCloud scene.mvs 
```

but DensifyPointCloud run this error

`libdc1394 error: Failed to initialize libdc1394
16:48:49 [App     ] Build date: Mar 15 2017, 11:57:05
16:48:49 [App     ] CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
16:48:49 [App     ] RAM: 6.78GB Physical Memory 2.00GB Virtual Memory
16:48:49 [App     ] OS: Linux 5.8.0-48-generic (x86_64)
16:48:49 [App     ] SSE & AVX compatible CPU & OS detected
16:48:49 [App     ] Command line: scene.mvs
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)`

For info i install openmvs using `snap install openmvs`

Thank you in advance, 
Truthfully yours

**Comment by cdcseacave** [comment]
most probably out of memory

**Comment by Ryujinosorus** [comment]
Well, i just check my ram during process and she wasnt out

**Comment by Ryujinosorus** [comment]
Ok, got it !

If you have same problem.

Dont install openmvs as shared library use :
`cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT="$main_path/vcglib"`
instead of 
`cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT="$main_path/vcglib"  -DBUILD_SHARED_LIBS=ON`

and run DensifyPointCloud with
`your_path/openMVS_build/bin/DensifyPointCloud`
