### ISSUE TITLE
Building issue (linking) on Fedora systems

### ISSUE THREAD

**Issue by alkavan** [cdcseacave/openMVS#667]
So I've been trying to create an RPM package for OpenMVS on my Fedora (33) system and found some link related issue that does not happen on Debian it seems. I am using the most recent `develop` branch.

I've been digging into this for quite a while, and it turns out that for the build to work on Fedora I need to add the following argument when calling `cmake`:
```
-DCMAKE_CXX_FLAGS="-lboost_iostreams -lz -lboost_program_options -lgmp"
```
Otherwise, you will get an undefined symbol error for these specific libraries.

Here is a sample of the errors I got, there's a lot of them:
```
[100%] Linking CXX executable ../../bin/Viewer
/usr/bin/ld: ../../lib/libMVS.a(Scene.cpp.o): in function `boost::detail::sp_counted_impl_p<boost::iostreams::symmetric_filter<boost::iostreams::detail::zstd_compressor_impl<std::allocator<char> >, std::allocator<char> >::impl>::dispose()':
Scene.cpp:(.text._ZN5boost6detail17sp_counted_impl_pINS_9iostreams16symmetric_filterINS2_6detail20zstd_compressor_implISaIcEEES6_E4implEE7disposeEv[_ZN5boost6detail17sp_counted_impl_pINS_9iostreams16symmetric_filterINS2_6detail20zstd_compressor_implISaIcEEES6_E4implEE7disposeEv]+0x27): undefined reference to `boost::iostreams::detail::zstd_base::reset(bool, bool)'
/usr/bin/ld: Scene.cpp:(.text._ZN5boost6detail17sp_counted_impl_pINS_9iostreams16symmetric_filterINS2_6detail20zstd_compressor_implISaIcEEES6_E4implEE7disposeEv[_ZN5boost6detail17sp_counted_impl_pINS_9iostreams16symmetric_filterINS2_6detail20zstd_compressor_implISaIcEEES6_E4implEE7disposeEv]+0x2f): undefined reference to `boost::iostreams::detail::zstd_base::~zstd_base()'
/usr/bin/ld: ../../lib/libMVS.a(Scene.cpp.o): in function `boost::detail::sp_counted_impl_p<boost::iostreams::symmetric_filter<boost::iostreams::detail::zstd_decompressor_impl<std::allocator<char> >, std::allocator<char> >::impl>::dispose()':
```

I'm not sure what exactly neds to be adjusted but here are the locations of the related shared objects on my system, maybe that would help:

```
/usr/lib64/libboost_iostreams.so
/usr/lib64/libboost_iostreams.so.1.73.0
/usr/lib64/libboost_program_options.so
/usr/lib64/libboost_program_options.so.1.73.0
/usr/lib64/libgmp.so
/usr/lib64/libgmp.so.10
/usr/lib64/libgmp.so.10.4.0
```

I do suspect this might be related to the `/usr/lib64/` path that is different.

There is an issue with the format of the `-DCMAKE_CXX_FLAGS` flag and the rpm build parser that will not allow the argument to be passed correctly, the best solution would be that I won't actually need to provide them at all.

But when building manually and supplying the flag everything works!

**Comment by twshield** [comment]
A note on Fedora 35 issues.  First the the good news:

I did not need the CXX_FLAGS as above.

The following are all packages, so no separate sources are needed:
			opencv-devel
			ceres-solver-devel
			CGAL-qt5-devel
			vcglib-devel
			glfw-devel
			glew-devel

I had to add 
`-DVCG_ROOT=/usr/include/vcglib `
to the cmake line to get it to pick that up.  (Perhaps this should be a cmake default.)

But the bad news is that boost-iostreams-1.76.0-4.fc35.x86_64 package does not include zstd support.  This has been reported to Fedora through bugzilla.  

I got around this by building from the src rpm as follows:

```
dnf download --source boost-iostreams
dnf install openmpi-devel mpich-devel
rpmbuild -rp boost-1.76.0-4.fc35.src.rpm
cd ~/rpmbuild/BUILD/boost_1_76_0
./bootstrap.sh
cd libs/iostreams/
../../b2
```

and this will generate a new libboost_iostreams.so that you can put in /usr/lib64 that results in a successful compile (link actually).  The rpmbuild step was the slowest for me.  Building the one library was quick.

**Comment by alkavan** [comment]
Indeed building `boost` manually solved the issue. I wanted to avoid installing different boost on my system so here I build it with `./b2 --link=static` and that seems to work.

I have created a [3d-reconstruction-toolkit-fedora](https://github.com/alkavan/3d-reconstruction-toolkit-fedora) that contains RPM spec files for Fedora 34/35.
And additionally, scripts to manually build and install both [OpenMVG](https://github.com/openMVG/openMVG/) and [OpenMVS](https://github.com/cdcseacave/openMVS) into the `/opt/3dr/` prefix.
