### ISSUE TITLE
problem and tips with build

### ISSUE THREAD

**Issue by riyueshi** [cdcseacave/openMVS#67]
the code works fine with vs2015 but really not vs2013,(I just bulid successfully with vs2015 but failed many times with vs2013)
vs2013 case:
in the file SceneReconstruct.cpp there is some error in line 728 and line 958, after change delete line 729,730,731 and 733, fix the first error. by delete the "typename" in line 958 can fix the second error(I an not sure whether this step would cause other failed),  and eigen 3.2.8 would be better since the old vs2013 (update 1, you'd better install the update 5 for you vs2013 ) has bug with early version eigen. after taking those the project still failed  with an "fatal error C1001: INTERNAL COMPILER ERROR" (the solution I can find can not fix)
vs2015 case:
it seems that we have to manually add the "CGAL-vc140-mt-4.7.lib" to each app after cmake generate the project.
finally, thanks @cdcseacave for sharing such a great code.

Miller Zhang

**Comment by cdcseacave** [comment]
Thank you for the tips. If you made it compile with VC2013, please post a pull request.
