### ISSUE TITLE
Noisy Output From DensifyPointcloud

### ISSUE THREAD

**Issue by c0ffymachyne** [cdcseacave/openMVS#673]
**To Reproduce**
Created a pointcloud with OpenMVG. I did try multiple times with different setting including generating features with HIGH and ULTRA settings. Since there is no exif data in the footage, I tried using 1.2 and 0.904 for focal values without any visual differences.

**Epected Results**
I would expect surface to be smooth of close to smooth, I would expect some irregularities but there is clearly something not right with the reconstruction

Densify pointcould arguments: 
Command line: 
`--resolution-level 3 --min-resolution 1800 --max-resolution 4000 --number-views 2 --number-views-fuse 1 --fusion-mode 1 --filter-point-cloud 1 -w /photogrammetry/Mercedes/openmvs -i /photogrammetry/Mercedes/openmvs/model.mvs`

Reconstruct mesh arguments:
Command line: 
`--remove-spurious 50 -w /photogrammetry/Mercedes/openmvs --thickness-factor 0.001 --constant-weight true --max-threads 24 --remove-spikes true --close-holes 30 --smooth 1 --decimate 1.0 --quality-factor 1.0 --min-point-distance 2.5 /photogrammetry/Mercedes/openmvs/model_dense.mvs`

 - OS: Ubuntu 20.04
![Screenshot from 2021-05-23 17-27-17](https://user-images.githubusercontent.com/1432920/119281950-8dc36180-bbec-11eb-99e7-9005ef36f387.png)

**Comment by c0ffymachyne** [comment]
From looking at the point cloud it seems there are two layers of "door" surface.

**Comment by cdcseacave** [comment]
first of all you are modifying a lot of the default params and set them wrong; you can change them if you want, but only if you know what are they doing

second, whenever you get ghost artefacts that is usually a sign of bad image alignment, so I suspect something wrong happended in the SfM step in OpenMVSG; judging by the bad customization in OpenMVS, I recommend you better use default params for OpenMVG as well; what is 1.2 or 0.9? you probably want to un-normalize that by the image size and use the focal length in pixels

**Comment by c0ffymachyne** [comment]
Hi @cdcseacave,

Thank you for reply. 

This is what I mean by 1.2 or 0.904 `focal = 0.904 * max(width,height)`

I checked parameters of openMVG and they are pretty much default. After reverting those and those you see to default there is no significant difference in the output, the "ghosting" is pretty apparent. What can I do to improve the quality of image alignment other then using default parameters ?

**Comment by c0ffymachyne** [comment]
Hi, I figured what the issues is. Please close this ticket.

**Comment by rperrot** [comment]
Could you explain what was the issue please ? (In order to the other users to know how did you fixed it).

**Comment by c0ffymachyne** [comment]
The data sets have to be prepared in a certain way to make it for as expected. In the case for this ticket, the subject was in frame on all the pictures thus overlapping and issues matching. I started making photos of subjects in parts and this yields better results and overlapping is smaller although reconstruction is still resulting in noisy surfaces, the noise just less noticeable.
