### ISSUE TITLE
Segmentation Fault running trimesh_optional.cpp example

### ISSUE THREAD

**Issue by Cervidellus** [cdcseacave/openMVS#674]
Compiling with MinGW 64 bit with Qt Creator , Qt6, on windows 10. 

Crash occurs at line 92, where a tetrahedron is constructed: `tri::Tetrahedron(cmof);`

Digging in, it occurs in the file platonic.h line 68. The FaceIterator fi has no read access to _M_Current, hence the segfault. Interestingly, the vertex iterator in the previous lines works just fine.

**Comment by cdcseacave** [comment]
Do you refer at OpenMVS or some other project? There are no such file in OpenMVS

**Comment by Cervidellus** [comment]
My bad, posted issue in wrong place! Closing.
