### ISSUE TITLE
OpenMVG not present in OpenMVS Build description

### ISSUE THREAD

**Issue by cogitas3d** [cdcseacave/openMVS#68]
Dear friends,

I update my Ubuntu and tried to build the openMVS again, following the steps to activate openMVG.

But errors started to happen. I read line by line on build official seccion (
https://github.com/cdcseacave/openMVS/wiki/Building) and I saw that the part with openMVG support was took off -->

```
#OpenMVG (Optional)
sudo apt-get install libxxf86vm1 libxxf86vm-dev libxi-dev libxrandr-dev graphviz
git clone --recursive https://github.com/openMVG/openMVG.git openMVG
mkdir openMVG_build
cd openMVG_build
cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/ -DCMAKE_INSTALL_PREFIX=$main_path/openMVG_install
make
make install
cd ..
```

Why?

A big hug!

**Comment by mad-de** [comment]
can't tell you why it was removed, but he build.md instructions didn't work for Ubuntu anyway.

Best would be to stick with the wiki (https://github.com/cdcseacave/openMVS/wiki/Building) and report, which errors do occur.

best wishes

**Comment by cdcseacave** [comment]
OpenMVG dependency was removed, cause the exporter to OpenMVS is included now directly in OpenMVG. So all you have to do is update OpenMVG to the latest version (develop branch), build it and use OpenMVG2OpenMVS executable instead of the old InterfaceOpenMVG.
