### ISSUE TITLE
Linking error on DenseReconstruction();

### ISSUE THREAD

**Issue by radek13** [cdcseacave/openMVS#69]
Hi,
I got two linker errors when I call:
scene.DenseReconstruction();
When I comment this line the code is linked correctly. I don't know what is the problem. I attached my CMakeLists.txt ( I put only important fragments)

```
find_package(OpenMVG REQUIRED)
find_package(Boost 1.57 REQUIRED COMPONENTS filesystem system serialization iostreams wserialization  program_options)
find_package(OpenCV REQUIRED)
target_link_libraries(mvg ${Boost_LIBRARIES} ${OPENMVG_LIBRARIES} ${OpenCV_LIBRARIES}  /home/john/Pobrane/nowe/openMVS/openMVS_build/lib/libMVS.a /home/john/Pobrane/nowe/openMVS/openMVS_build/lib/libCommon.a   /home/john/Pobrane/nowe/openMVS/openMVS_build/lib/libMath.a  /home/john/Pobrane/nowe/openMVS/openMVS_build/lib/libIO.a)
```

> home/john/Pobrane/nowe/openMVS/openMVS_build/lib/libMVS.a(DepthMap.cpp.o): In function `boost::archive::detail::common_iarchive<boost::archive::text_iarchive>::vload(boost::archive::class_name_type&)':
> DepthMap.cpp:(.text._ZN5boost7archive6detail15common_iarchiveINS0_13text_iarchiveEE5vloadERNS0_15class_name_typeE[_ZN5boost7archive6detail15common_iarchiveINS0_13text_iarchiveEE5vloadERNS0_15class_name_typeE]+0x1): undefined reference to `boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::load_override(boost::archive::class_name_type&)'
> /home/john/Pobrane/nowe/openMVS/openMVS_build/lib/libMVS.a(DepthMap.cpp.o): In function `boost::archive::detail::common_iarchive<boost::archive::binary_iarchive>::vload(boost::archive::class_name_type&)':
> DepthMap.cpp:(.text._ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_15class_name_typeE[_ZN5boost7archive6detail15common_iarchiveINS0_15binary_iarchiveEE5vloadERNS0_15class_name_typeE]+0x1): undefined reference to `boost::archive::basic_binary_iarchive<boost::archive::binary_iarchive>::load_override(boost::archive::class_name_type&)'
> collect2: error: ld returned 1 exit status

P.S. It is intriguing for me because I was able to build OpenMVS from sources and especially apps/DensifyPointCloud

Please help.

**Comment by cdcseacave** [comment]
Please try the latest version.
Use:
find_package(OpenMVS REQUIRED)

**Comment by radek13** [comment]
> "Latest version"
Do you mean latest version of Boost?

> Use:
> find_package(OpenMVS REQUIRED)
I tried to do it, but I got error:

> Error:By not providing "FindOpenMVS.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "OpenMVS", but CMake did not find one.

I tried also to find FindOpenMVS.cmake but without a success.

**Comment by cdcseacave** [comment]
as the CMake error well says, you have to install OpenMVS and point the CMake to the OpenMVSConfig.cmake file... like for any other project out there configured with CMake
