### ISSUE TITLE
Seems `InterfaceCOLMAP` append `sparse/` as prefix forcibly.

### ISSUE THREAD

**Issue by FavorMylikes** [cdcseacave/openMVS#691]
https://github.com/cdcseacave/openMVS/blob/1de8e4bd83c37376914784d8bf47a17e80c95d7b/apps/InterfaceCOLMAP/InterfaceCOLMAP.cpp#L752-L754

But colmap default output is `sparse/0` with command below

```console
colmap mapper --output_path sparse
```

**Comment by cdcseacave** [comment]
it is sparse only after undistortion, pls see the documentation
