### ISSUE TITLE
Possible CUDA patch-match reconstruction artifact issues

### ISSUE THREAD

**Issue by pierotofy** [cdcseacave/openMVS#708]
**Describe the bug**

Running `DensifyPointCloud` on an aerial dataset using the CUDA accelerated patch-match yields some artifacts / reconstruction issues compared to the same dataset processed using the CPU code.

CPU:

![image](https://user-images.githubusercontent.com/1951843/138727330-4329be06-d456-422c-bfcf-aa98f0843d96.png)

CUDA:

![image](https://user-images.githubusercontent.com/1951843/138727413-dbf14beb-a57e-47cc-ab5b-fec58620362d.png)

Link to results and input OpenMVS files: https://testhub.dronedb.app/r/pierotofy/openmvs

**To Reproduce**

1. Download the input files from https://testhub.dronedb.app/r/pierotofy/openmvs
2. Run: `DensifyPointCloud "openmvs/scene.mvs"  --resolution-level 2 --max-threads 4 --number-views-fuse 2 -w "openmvs/depthmaps"` (GPU)
3. Compare the run with:  `DensifyPointCloud "openmvs/scene.mvs"  --cuda-device -1 --resolution-level 2 --max-threads 4 --number-views-fuse 2 -w "openmvs/depthmaps"` (CPU)

**Expected behavior**

Reconstruction quality should be comparable.

**Desktop (please complete the following information):**

Arch Linux / CUDA 11.2

```
(odmdev)[piero:/code] gpuomvs(+3/-2)* 130 ± nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```

Btw, I got a blast seeing the speed at which depthmaps were computed using CUDA. :boom: super-excited for this feature!

Let me know if you need additional information.

**Comment by pierotofy** [comment]
So a quick update on this, I might have a solution, although I want to double check on the approach, there might be better ways.

The root cause is that the images for this dataset have been undistorted to remove lens distortion, so there are black/empty areas at the edges of the photos:

![image](https://user-images.githubusercontent.com/1951843/141343583-eec7ee20-1f15-490b-ab6e-92b55a7e3330.png)

The both CPU and GPU implementations initialize the rough depthmap/normal estimates by interpolating from the sparse points if they are available, but whereas the CPU code is able to filter through the empty areas,  the GPU code does not (as I observed in https://user-images.githubusercontent.com/1951843/139292031-79a81d83-e491-43af-93fe-f995d5a5a173.png)

I found that by limiting the rough intialization to areas that have valid pixels (non-black) I get good results with the GPU (no seamlines):

![image](https://user-images.githubusercontent.com/1951843/141344176-80cd4d8f-b977-45b1-8ab2-5a641b995493.png)

This is the code change I made: https://github.com/OpenDroneMap/openMVS/commit/6564ce24ff98c32e1838af4ef36351fe69e76103

Thought I'd check if this is a reasonable approach before opening a PR.

As a side note, I think the bubble sort function has an off-by-one bug as the `sortedValues` is not initialized all the way. I can open a separate PR for that. https://github.com/OpenDroneMap/openMVS/commit/6f766dcc06d00bcfdf3f76e66eff08d8f88b5cf2

**Comment by cdcseacave** [comment]
Thank for looking into this. I am familiar with the black border issue cause by iamge undistortions, however I do not like much the approach of comparing to black color, as that could very well be a valid color. Additionally the change you suggest in initializing the coarse depth-map with 0, translates in initializing those values with random values (done when the score is first computed). I think this works only becuase those random estimates will later be filtered out by the fusion step.

The difference between CPU and GPU implementation is however in the additional filtering step that the CPU version has which removed all estimates with very bad confidence: https://github.com/cdcseacave/openMVS/blob/bbe7db543cdc09b0ef7a9afba5b201ff9d92dbed/libs/MVS/SceneDensify.cpp#L704

Crazy bug you found in the sort function, thank you for spotting it.

I will try to make some time tomorrow to commit a fix for both.

Thanks you again!

**Comment by cdcseacave** [comment]
Hey @pierotofy 
Can you pls try the new develop and confirm you do not get the black strips anymore?
The last commit contains two important changes:
1. the depth estimates with high NCC score are filtered out on GPU implementation as well
2. the corners of the coarse depth-map are not initialized anymore with values interpolated from the valid pixels; this will let empty (will be initialized randomly) the regions of the depth-map outside of the sparse point-cloud convex hull; in other words it should indirectly accomplish the same effect as your proposed change of comparing the color to Black.

**Comment by pierotofy** [comment]
Hey @cdcseacave :hand: thanks for looking into this. It does seem like a better solution.

Stripes are gone but the filtering seems a bit more aggressive than the CPU implementation:

![anim](https://user-images.githubusercontent.com/1951843/141815953-4888076e-56c7-4959-955f-3b22386104be.gif)

I think this is due to differences in the computation of the NCC score; one can tweak the `fNCCThresholdKeep` option to get more comparable results.

**Comment by cdcseacave** [comment]
You are right, I created a different threshold to be used with CUDA and now they should have similar output. Can you pls confirm on your dataset?

**Comment by pierotofy** [comment]
Thanks @cdcseacave , I'll test and report back :pray:

**Comment by pierotofy** [comment]
Works fantastic! :tada: 

Much appreciate your help in troubleshooting this issue :pray:
