### ISSUE TITLE
CUDA code for Scene Refinement

### ISSUE THREAD

**Issue by saedrna** [cdcseacave/openMVS#726]
**Is your feature request related to a problem? Please describe.**
Is there a readable version for `g_szMeshRefineModule` as below?
https://github.com/cdcseacave/openMVS/blob/35facc588c1f231330c8dcbaaacbd436a6e0dd67/libs/MVS/SceneRefineCUDA.cpp#L53-L74

**Describe the solution you'd like**
Probably refactor it into a common `.h` `.cpp` and `.cu` structure.

**Additional context**
I am again following the variational refinement part in the repo and the compiled CUDA module is hard to be understood.

**Comment by cdcseacave** [comment]
this question came up before; it is a very long time since I wrote that code, and I wrote it directly in assembly mode (believe it or not), so there is no cu version of the code; the algorithm is identical to the CPP version, so feel free to contribute with the port to CUDA in a cu format.

**Comment by saedrna** [comment]
WOW!!!
