### ISSUE TITLE
Cannot run the usage example

### ISSUE THREAD

**Issue by hlzz** [cdcseacave/openMVS#73]
It seems that the usage example is out-dated. I noticed that openMVS is now independent of openMVG, so InterfaceOpenMVG2 does not exist. I've tried first convert the sfm_data.json to sfm_data.baf and then run 
`InterfaceOpenMVG -i scene.baf -l images.txt -o scene.mvs`
but got a lot of errors like: 

> 14:54:27 [App     ] error: intrinsics-pose pair not existing
> 14:54:27 [App     ] observation: 0 3 2067.14 1223.18
> 14:54:27 [App     ] error: intrinsics-pose pair not existing
> 14:54:27 [App     ] observation: 0 4 2135.34 1171.59
> 14:54:27 [App     ] error: intrinsics-pose pair not existing
> 14:54:27 [App     ] observation: 0 1 2088.38 672.835
> 14:54:27 [App     ] error: intrinsics-pose pair not existing
> 14:54:27 [App     ] observation: 0 3 2192.94 669.534
> 14:54:27 [App     ] error: intrinsics-pose pair not existing
> 14:54:27 [App     ] observation: 0 0 2476.58 1277.34

Then I download openmvs_sample and tried to run the command using the scene.mvs in it, but got the following output:

> [tianwei@localhost bin]$ ./DensifyPointCloud -i scene.mvs -o scene_dense.mvs
> 14:55:13 [App     ] Build date: Apr  5 2016, 13:16:52
> 14:55:14 [App     ] CPU: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
> 14:55:14 [App     ] RAM: 31.20GB Physical Memory 15.70GB Virtual Memory
> 14:55:14 [App     ] OS: Linux 3.10.0-327.10.1.el7.x86_64 (x86_64)
> 14:55:14 [App     ] SSE & AVX compatible CPU & OS detected
> 14:55:14 [App     ] Command line: -i scene.mvs -o scene_dense.mvs
> DensifyPointCloud: /home/tianwei/Documents/Projects/brainstorm/src/openMVS/libs/MVS/Scene.cpp:67: bool MVS::Scene::LoadInterface(const SEACAVE::String&): Assertion `!obj.platforms.empty()' failed.
> Aborted (core dumped)

So can you update the usage example a bit?

**Comment by cdcseacave** [comment]
indeed, the wiki was outdated, please check the corrected version now... hope it works now

**Comment by hlzz** [comment]
Thanks! The openMVG converter works fine, but I still got the following errors when running the next steps: 
`./DensifyPointCloud ~/data/ImageDataset_SceauxCastle-master/out/reconstruction_sequential/sfm_data.mvs `

> [tianwei@localhost bin]$ ./DensifyPointCloud ~/data/ImageDataset_SceauxCastle-master/out/reconstruction_sequential/sfm_data.mvs 
> 15:39:15 [App     ] Build date: Apr  5 2016, 13:16:52
> 15:39:15 [App     ] CPU: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
> 15:39:15 [App     ] RAM: 31.20GB Physical Memory 15.70GB Virtual Memory
> 15:39:15 [App     ] OS: Linux 3.10.0-327.10.1.el7.x86_64 (x86_64)
> 15:39:15 [App     ] SSE & AVX compatible CPU & OS detected
> 15:39:15 [App     ] Command line: /home/tianwei/data/ImageDataset_SceauxCastle-master/out/reconstruction_sequential/sfm_data.mvs
> DensifyPointCloud: /home/tianwei/Documents/Projects/openMVS/libs/MVS/Scene.cpp:67: bool MVS::Scene::LoadInterface(const SEACAVE::String&): Assertion `!obj.platforms.empty()' failed.
> Aborted (core dumped)
> [tianwei@localhost bin]$ ./ReconstructMesh ~/data/ImageDataset_SceauxCastle-master/out/reconstruction_sequential/sfm_data.mvs 
> 15:39:55 [App     ] Build date: Apr  5 2016, 13:16:52
> 15:39:55 [App     ] CPU: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
> 15:39:55 [App     ] RAM: 31.20GB Physical Memory 15.70GB Virtual Memory
> 15:39:55 [App     ] OS: Linux 3.10.0-327.10.1.el7.x86_64 (x86_64)
> 15:39:55 [App     ] SSE & AVX compatible CPU & OS detected
> 15:39:55 [App     ] Command line: /home/tianwei/data/ImageDataset_SceauxCastle-master/out/reconstruction_sequential/sfm_data.mvs
> ReconstructMesh: /home/tianwei/Documents/Projects/openMVS/libs/MVS/Scene.cpp:67: bool MVS::Scene::LoadInterface(const SEACAVE::String&): Assertion `!obj.platforms.empty()' failed.
> Aborted (core dumped)

**Comment by cdcseacave** [comment]
are you using the latest OpenMVG and OpenMVS code?

**Comment by hlzz** [comment]
OpenMVS is the latest, but OpenMVG is not. Should I use the OpenMVG dev branch?

**Comment by cdcseacave** [comment]
yes

**Comment by hlzz** [comment]
Updated to the latest version of both MVS and MVG, still cannot run the second step 

> [tianwei@localhost bin]$ ./DensifyPointCloud ~/Data/ImageDataset_SceauxCastle-master/out1/reconstruction_sequential/scene.mvs 
> 16:50:07 [App     ] Build date: Apr  5 2016, 16:42:19
> 16:50:07 [App     ] CPU: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
> 16:50:07 [App     ] RAM: 31.20GB Physical Memory 15.70GB Virtual Memory
> 16:50:07 [App     ] OS: Linux 3.10.0-327.10.1.el7.x86_64 (x86_64)
> 16:50:07 [App     ] SSE & AVX compatible CPU & OS detected
> 16:50:07 [App     ] Command line: /home/tianwei/Data/ImageDataset_SceauxCastle-master/out1/reconstruction_sequential/scene.mvs
> 16:50:08 [App     ] Camera model loaded: platform 0; camera  0; f 1.056x1.056; poses 11
> Segmentation fault (core dumped)
> 

The cmake configuration of openMVG and openMVS are correspondingly:
openMVG:
[tianwei@localhost build_linux]$ cmake ../src/

> -- Optimizing for the host architecture using -march=native
> -- Checking for C++11 compiler
> -- Checking for C++11 compiler - available
> -- Did not find MOSEK header
> -- Did not find MOSEK library
> -- Could not find mosek library on this machine.
> -- Eigen 3.2.8 found (include: /home/tianwei/Documents/Projects/openMVG/src/third_party/eigen)
> -- Failed to find Ceres - Found Eigen dependency, but the version of Eigen found (3.2.8) does not exactly match the version of Eigen Ceres was compiled with (3.2.5). This can cause subtle bugs by triggering violations of the One Definition Rule. See the Wikipedia article http://en.wikipedia.org/wiki/One_Definition_Rule for more details
> -- Flann 1.8.4 found (include: /home/tianwei/Documents/Projects/openMVG/src/third_party/flann/src/cpp/flann)
> -- CoinUtils 2.9.3 found (include: /home/tianwei/Documents/Projects/openMVG/src/dependencies/osi_clp/CoinUtils/src)
> -- Clp 1.15.11 found (include: /home/tianwei/Documents/Projects/openMVG/src/dependencies/osi_clp/Clp/src)
> -- Osi 0.106.10 found (include: /home/tianwei/Documents/Projects/openMVG/src/dependencies/osi_clp/Osi/src/Osi)
> -- Lemon 1.3 found (include: /home/tianwei/Documents/Projects/openMVG/src/third_party/lemon/lemon)
> -- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
> -- Could NOT find ILOG (missing:  ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR) 
> -- Could NOT find COIN (missing:  COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
> -- Could NOT find SOPLEX (missing:  SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR) 
> -- Eigen 3.2.8 found (include: /home/tianwei/Documents/Projects/openMVG/src/third_party/eigen)
> -- Found Eigen version 3.2.8: /home/tianwei/Documents/Projects/openMVG/src/third_party/eigen
> 
>    ===============================================================
>    Disabling the use of Eigen as a sparse linear algebra library.
>    This does not affect the covariance estimation algorithm 
>    which can still use the EIGEN_SPARSE_QR algorithm.
>    ===============================================================
> 
> -- A library with BLAS API found.
> -- Found LAPACK library: /usr/lib64/liblapack.so;/usr/lib64/libblas.so
> -- Found BLAS library: /usr/lib64/libblas.so
> -- Building without SuiteSparse.
> -- Google Flags disabled; no tests or tools will be built!
> -- Compiling minimal glog substitute into Ceres.
> -- Using minimal glog substitute (include): internal/ceres/miniglog
> -- Building with OpenMP.
> -- Found unordered_map/set in std namespace.
> -- Found shared_ptr in std namespace using <memory> header.
> -- Building Ceres as a static library.
> -- Enabling CERES_NO_SUITESPARSE in Ceres config.h
> -- Enabling CERES_USE_OPENMP in Ceres config.h
> -- Enabling CERES_HAVE_PTHREAD in Ceres config.h
> -- Enabling CERES_HAVE_RWLOCK in Ceres config.h
> -- Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
> -- Do not build any example.
> -- 
> -- Configured Eigen 3.2.8
> -- 
> -- Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE) 
> Sphinx need to be installed to generate the sphinx documentation
> 
> 
> ** OpenMVG version: 0.9.0
> ** Build Shared libs: OFF
> ** Build OpenMVG tests: OFF
> ** Build OpenMVG documentation: ON
> ** Build OpenMVG samples applications: ON
> ** Build OpenMVG openGL examples: OFF
> ** Enable code coverage generation: OFF
> ** Enable OpenMP parallelization: ON
> ** Build OpenCV+OpenMVG samples programs: OFF
> ** Use OpenCV SIFT features: OFF
> 
> 
> -- EIGEN: 3.2.8 (internal)
> -- CERES: 1.10.0 (internal)
> -- FLANN: 1.8.4 (internal)
> -- LIBTIFF: 4.0.3 (external)
> -- LIBPNG: 1.5.13 (external)
> -- LIBJPEG (external)
> -- CLP: 1.15.11 (internal)
> -- COINUTILS: 2.9.3 (internal)
> -- OSI: 0.106.10 (internal)
> -- LEMON: 1.3 (internal)
> 
> 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/tianwei/Documents/Projects/openMVG/build_linux
> 

and openMVS:

> [tianwei@localhost build_linux]$ cmake ..
> -- cotire 1.7.8 loaded.
> -- Detected version of GNU GCC: 48 (408)
> CUDA_TOOLKIT_ROOT_DIR not found or specified
> -- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
> -- Can't find CUDA. Continuing without it.
> -- WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
> -- Can't find BreakPad. Continuing without it.
> -- Boost version: 1.53.0
> -- Found the following Boost libraries:
> --   iostreams
> --   program_options
> --   system
> --   serialization
> --   regex
> -- Eigen 3.2.5 found (include: /usr/include/eigen3)
> -- OpenCV 2.4.9 found (include: /usr/include/opencv;/usr/include)
> -- CXX target Common cotired without unity build.
> -- CXX target Math cotired without unity build.
> -- CXX target IO cotired without unity build.
> -- CGAL 4.4 found (include: /usr/include)
> -- VCG  found (include: /usr/local/include)
> -- Found required Ceres dependency: Eigen version 3.2.5 in /usr/include/eigen3
> -- Found required Ceres dependency: Glog in /usr/include
> -- Found Ceres version: 1.12.0 installed in: /usr/local
> -- CERES 1.12.0 found (include: /usr/local/include;/usr/include/eigen3;/usr/include;/usr/local/include)
> -- CXX target MVS cotired without unity build.
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/tianwei/Documents/Projects/openMVS/build_linux
>

**Comment by pmoulon** [comment]
Regarding the warning
```
-- Failed to find Ceres - Found Eigen dependency, but the version of Eigen found (3.2.8) does not exactly match the version of Eigen Ceres was compiled with (3.2.5). This can cause subtle bugs by triggering violations of the One Definition Rule. See the Wikipedia article http://en.wikipedia.org/wiki/One_Definition_Rule for more details
```
You can solve it by telling to OpenMVG to use the same Eigen version as the version used by your existing compiled ceres by setting EIGEN_INCLUDE_DIR_HINTS=/usr/include

Please note that now in the develop branch the output SFM file are saved in binary format.
So please use the sfm_data.bin file with the openMVG2OpenMVS binary.
