### ISSUE TITLE
calling a __host__ function("Eigen::MatrixBase< ::Eigen::Matrix<float, (int)3, (int)3, (int)0, (int)3, (int)3> > ::inverse() const") from a __device__ function("ComputeHomography") is not allowed

### ISSUE THREAD

**Issue by RenDavid** [cdcseacave/openMVS#733]
Severity	Code	Description	Project	File	Line	Suppression State
Error	calling a __host__ function("Eigen::MatrixBase< ::Eigen::Matrix<float, (int)3, (int)3, (int)0, (int)3, (int)3> > ::inverse() const") from a __device__ function("ComputeHomography") is not allowed	
.......\OpenMVS\src\libs\MVS\PatchMatchCUDA.cu	255	

**PatchMatchCUDA.cu **
// compose tho homography matrix that transforms a point from reference to source camera through the given plane
__device__ inline Matrix3 ComputeHomography(const PatchMatchCUDA::Camera& refCamera, const PatchMatchCUDA::Camera& trgCamera, const Point2& p, const Point4& plane)
{
	const Point3 X = BackProjectPointCamera(refCamera, p, plane.w());
	const Point3 normal = plane.topLeftCorner<3,1>();
	const Point3 t = (refCamera.C - trgCamera.C) / (normal.dot(X));
	const Matrix3 H = trgCamera.R * (refCamera.R.transpose() + t*normal.transpose());
	**return trgCamera.K * H * refCamera.K.inverse();**
}

** "......\vcpkg\installed\x64-windows\include\eigen3\Eigen\src\LU\InverseImpl.h"**
template<typename Derived>
inline const Inverse<Derived> MatrixBase<Derived>::inverse() const
{
  EIGEN_STATIC_ASSERT(!NumTraits<Scalar>::IsInteger,THIS_FUNCTION_IS_NOT_FOR_INTEGER_NUMERIC_TYPES)
  eigen_assert(rows() == cols());
  return Inverse<Derived>(derived());
}

**Visual Studio 2019
GPU: Nvidia RTX3090
CUDA: 11.5
Eigen:3.3.9**

**Comment by RenDavid** [comment]
Eigen 3.3.9

**Comment by longhuan2018** [comment]
This is the problem of eigen3 itself. Please upgrade to eigen3 version 3.4.0

**Comment by Jinunmeng** [comment]
Eigen version 3.4 or higher

**Comment by RenDavid** [comment]
template<typename Derived>
**EIGEN_DEVICE_FUNC**
inline const Inverse<Derived> MatrixBase<Derived>::inverse() const
{
  EIGEN_STATIC_ASSERT(!NumTraits<Scalar>::IsInteger,THIS_FUNCTION_IS_NOT_FOR_INTEGER_NUMERIC_TYPES)
  eigen_assert(rows() == cols());
  return Inverse<Derived>(derived());
}
