### ISSUE TITLE
New compilation error from PatchMatchCUDA 

### ISSUE THREAD

**Issue by whistlefancy** [cdcseacave/openMVS#737]
Thanks for the maintenance and update of this system, but I encountered a new compilation error. The error location is in PatchMatchCUDA. The following is the terminal error message.
I tried to compile on two computers (the system environment is ubantu16 and ubantu20, and the previous version was successfully compiled before), and this error occurred. I would like to know how to solve this compilation error. Any replies from you are greatly appreciated.

“1 error detected in the compilation of "/tmp/tmpxft_000058f0_00000000-6_PatchMatchCUDA.cpp1.ii".
libs/MVS/CMakeFiles/MVS.dir/build.make:446: recipe for target 'libs/MVS/CMakeFiles/MVS.dir/PatchMatchCUDA.cu.o' failed
make[2]: *** [libs/MVS/CMakeFiles/MVS.dir/PatchMatchCUDA.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:311: recipe for target 'libs/MVS/CMakeFiles/MVS.dir/all' failed
make[1]: *** [libs/MVS/CMakeFiles/MVS.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2”

**Comment by longchao343** [comment]
Same error and can not find a way to fix it :(

**Comment by Daisy-Dong** [comment]
I solved this problem by updating eigen to 3.4.

**Comment by whistlefancy** [comment]
> 
Thank you very much, upgrading the eigen version can solve this problem. In fact, the author has emphasized the eigen version in the building document.

**Comment by whistlefancy** [comment]
> 我通过将 eigen 更新到 3.4 解决了这个问题。

Thank you very much, upgrading the eigen version can solve this problem. In fact, the author has emphasized the eigen version in the building document.

**Comment by WilliamOChai** [comment]
You solve the problem? I failed in windows when I compile openmvs with cuda
