### ISSUE TITLE
Version 2.0 crashes during geometric consistent on CUDA

### ISSUE THREAD

**Issue by melhashash** [cdcseacave/openMVS#739]
**Configuration:**

21:51:17 [App     ] Build date: Dec 16 2021, 11:34:21
21:51:17 [App     ] CPU: Intel(R) Xeon(R) W-2275 CPU @ 3.30GHz (28 cores)
21:51:17 [App     ] RAM: 63.69GB Physical Memory 128.00TB Virtual Memory
21:51:17 [App     ] OS: Windows 8 x64
21:51:17 [App     ] SSE & AVX compatible CPU & OS detected
21:51:17 [App     ] Command line: -i PATH\scene.mvs -w PATH
21:51:17 [App     ] MapSMtoCores for SM 8.6 is undefined; default to use 64 cores/SM
21:51:17 [App     ] CUDA device 0 initialized: NVIDIA GeForce RTX 3080 (compute capability 8.6; memory 10.00GB)

**CMD output:**

Estimated depth-maps 1687 (100%, 2m47s227ms)
Geometric-consistent estimated depth-maps 108 (6.40%, 12s, ETA 2m)...

**Log file:**

19:53:57 [App     ] error: opening file 'PATH_HERE/depth0590.dmap' for reading depth-data
19:53:57 [App     ] Depth-map for image 240 estimated using  2 images: 1000x750 (58ms)
19:53:57 [App     ] Reference image 171 paired with 2 views
19:53:57 [App     ] CUDA error: an illegal memory access was encountered (code 700)

Also, while checking the log file, I noticed few errors like this one `19:53:57 [App     ] error: opening file 'PATH_HERE/depth0590.dmap' for reading depth-data`. Why did this issue occur?

**Comment by 3XH6R** [comment]
only noticing this after updating to windows 11.

**Comment by cdcseacave** [comment]
I need a minimum dataset that reproduces the problem to debug

**Comment by Daisy-Dong** [comment]
same error.

**Comment by cdcseacave** [comment]
pls try latest develop, I might have found the problem

**Comment by melhashash** [comment]
> pls try latest develop, I might have found the problem

Thanks, will let you know how it goes.

**Comment by melhashash** [comment]
@cdcseacave, please send windows binaries for develop if you have them. If not, I will build from scratch.

**Comment by melhashash** [comment]
@cdcseacave I tested the latest develop and can confirm it has been fixed. Thanks!

**Comment by WilliamOChai** [comment]
> @cdcseacave I tested the latest develop and can confirm it has been fixed. Thanks!



> same error.
Can you compile openmvs with cuda，I faild. Could you please help me.
