### ISSUE TITLE
InterfaceCOLMAP Error

### ISSUE THREAD

**Issue by cogitas3d** [cdcseacave/openMVS#744]
Hey there!

I'm trying to build openMVS on Mac, but I had an error on COLMAP:

`[ 72%] Linking CXX executable ../../bin/InterfaceCOLMAP`
...
`clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/InterfaceCOLMAP] Error 1
make[1]: *** [apps/InterfaceCOLMAP/CMakeFiles/InterfaceCOLMAP.dir/all] Error 2`

So I use this configuration:

`cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT="$main_path/vcglib" -DOpenMVS_USE_OPENMP=OFF`

But, unfortunatelly the error continue.

I try to follow this: 

https://github.com/cdcseacave/openMVS/issues/730

But the problem continue.

Is it a possible to build only command line without this error?

A big hug.

**Comment by awcchungster** [comment]
Same issue!

**Comment by awcchungster** [comment]
The discussion in #730 worked for me. I ran this command and then went back to the final make step.

```
brew install boost
sed -i.bak -r 's/NO_ZSTD=1/NO_ZSTD=0/' /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb
brew reinstall boost --build-from-source
```

**Comment by cogitas3d** [comment]
Hi @awcchungster !

I tryied it again the solution of #730  and I saw an error:

`sed: illegal option -- r`

So, I replace "-r" to "-E" and it works!
