### ISSUE TITLE
Hide camera in Viewer

### ISSUE THREAD

**Issue by robin-shaun** [cdcseacave/openMVS#746]
Thanks for the wonderful project. I wonder whether there is a way to hide camera in Viewer. 
![image](https://user-images.githubusercontent.com/20561850/149065365-9c8a23ae-0488-4b8a-8ec6-dc56349f597f.png)

**Comment by 3XH6R** [comment]
Keys:
        E: export scene
        R: reset scene
        B: render bounds
        C: render cameras
        C + Shift: render camera trajectory
        Left/Right: select next camera to view the scene
        T: render mesh texture
        W: render wire-frame mesh
        V: render view rays to the selected point
        V + Shift: render points seen by the current view
        Up/Down: adjust point size
        Up/Down + Shift: adjust minimum number of views accepted when displaying a point or line
        +/-: adjust camera thumbnail transparency
        +/- + Shift: adjust camera cones' length

**Comment by robin-shaun** [comment]
Thanks!
