### ISSUE TITLE
Running into an issue building with CUDA on Windows 10/11

### ISSUE THREAD

**Issue by 3XH6R** [cdcseacave/openMVS#748]
Using the Windows compilation build instructions.
Error building with CUDA log: https://pastebin.com/raw/FE2s3xkC
Builds fine without CUDA.

Windows 11 x64
Cuda Toolkit 11.5 Version 11
Visual Studio 2019 16.11.8 | MSVC v142 | Windows 11 SDK 10.0.22

**Comment by longhuan2018** [comment]
see #733
