### ISSUE TITLE
DensifyPointCloud | --sub-scene-area doesn't work for some scenes

### ISSUE THREAD

**Issue by 3XH6R** [cdcseacave/openMVS#753]
DensifyPointCloud is failing to fuse scenes or only completes a handful.

Dataset: [sheffield_cross](https://github.com/pierotofy/drone_dataset_sheffield_cross/tree/master)
![image](https://user-images.githubusercontent.com/32020441/149440788-960e9d95-e168-4858-8e85-4f1cd0fd30ad.png)

DensifyPointCloud log for snail sculpture dataset

     19:17:24 [App     ] Build date: Jan 12 2022, 19:48:26
     19:17:24 [App     ] CPU: AMD Ryzen 7 3700X 8-Core Processor              (16 cores)
     19:17:24 [App     ] RAM: 31.94GB Physical Memory 128.00TB Virtual Memory
     19:17:24 [App     ] OS: Windows 8 x64
     19:17:24 [App     ] Disk: 256.17GB (930.77GB) space
     19:17:24 [App     ] SSE & AVX compatible CPU & OS detected
     19:17:24 [App     ] Command line: DensifyPointCloud C:\Users\3XH6R\Downloads\datasets\Snails\mvs\scene_0132.mvs --dense-config-file Densify.ini --number-views-fuse 3 -w C:\Users\3XH6R\Downloads\datasets\Snails\mvs
     19:17:24 [App     ] CUDA device 0 initialized: NVIDIA GeForce RTX 2080 (compute capability 7.5; memory 8.00GB)
     19:17:24 [App     ] Scene loaded (8ms):
	     6 images (6 calibrated) with a total of 137.33 MPixels (22.89 MPixels/image)
	     20874 points, 0 vertices, 0 faces
     19:17:25 [App     ] Preparing images for dense reconstruction completed: 6 images (280ms)
     19:17:25 [App     ] Selecting images for dense reconstruction completed: 6 images (2ms)
     19:17:25 [App     ] Reference image   0 paired with 4 views
     19:17:25 [App     ] Reference image   1 paired with 3 views
     19:17:25 [App     ] Reference image   2 paired with 3 views
     19:17:25 [App     ] Reference image   3 paired with 4 views
     19:17:25 [App     ] Reference image   4 paired with 4 views
     19:17:25 [App     ] Reference image   5 paired with 2 views
     19:17:25 [App     ] Reference image   0 paired with 4 views
     19:17:25 [App     ] Reference image   1 paired with 3 views

doesn't produce any dense mvs or ply

![image](https://user-images.githubusercontent.com/32020441/149448795-1ebfa178-f327-49e2-8f0e-d33a3faa6072.png)
![image](https://user-images.githubusercontent.com/32020441/149449038-214c49ac-709b-498f-af7b-1dcbe71cfc68.png)

**Comment by 3XH6R** [comment]
Next day: deleted project and restarted. Fusing isn't working anymore. The only thing changed was reprocessing the dataset starting from OpenMVG.

**Comment by 3XH6R** [comment]
Windows 11 x64
Visual Studio 2019 v16.11.8 | MSVC v142 | Windows 11 SDK 10.0.22
3700X | RTX 2080 | 32GB
commit c658b72 build using Windows compilation instructions. Replaced vcpkg eigen3 with eigen3 3.4.0
CUDA 11.5 Version 11

**Comment by cdcseacave** [comment]
can you pls share the 2 scenes that do not work, plus the command line you used?

**Comment by 3XH6R** [comment]
uploaded

**Comment by 3XH6R** [comment]
Am I doing something wrong?

**Comment by cdcseacave** [comment]
sry, didn't have time to look at it
pls consider a donation if urgent
