### ISSUE TITLE
refinemesh error

### ISSUE THREAD

**Issue by PaulLiuYZ** [cdcseacave/openMVS#755]
I have downloaded the scene_mesh.mvs from the example page, then i want to refine the mesh directly, however, there are some problems:
1. it seems that the gpu is not used
2. there is an error：exception thrown: array size too short
the screenshot is below:
<img width="688" alt="1642410094(1)" src="https://user-images.githubusercontent.com/66100217/149739291-8be67dcc-2e22-491c-b14f-0c0677912703.png">
can you help me ? thanks a lot

**Comment by cdcseacave** [comment]
most probably the example is not up to date with the latest code
pls start from scene.mvs, hopefully that will work

**Comment by PaulLiuYZ** [comment]
i followed your instruction, however, there are some new problems:
<img width="660" alt="e8fa2aaca933dfa30c8728155bd02dd" src="https://user-images.githubusercontent.com/66100217/149963210-a86b27cd-bab4-4d8e-83ff-a9760ef4a8e6.png">
do you know the reasons?
thanks a lot

**Comment by PaulLiuYZ** [comment]
I have found the problem, and completed the pipeline sucessfully.
However, i still met a problem, i set the use cuda option in the cmakelist with on, but it seems that the gpu dosen't work.
![image](https://user-images.githubusercontent.com/66100217/150069562-5369d08e-cf30-44bc-9546-ae4f3145fb52.png)

**Comment by PaulLiuYZ** [comment]
maybe, in other words, how can i know whether the refinemesh is done with the cpu or the gpu?
