### ISSUE TITLE
Unknown Image Format .JPG

### ISSUE THREAD

**Issue by braden-dev** [cdcseacave/openMVS#757]
I know this isn't a bug and many people have asked questions about this but I can't seem to figure it out. When MvgMvsPipeline.py reaches the Densify Point Cloud step I get this error.
![image](https://user-images.githubusercontent.com/69637496/153917076-f12b45db-23b7-4b8e-8bc0-d0e9daeb555e.png)

I know that I need to compile OpenMVS with libjpeg but I cannot for the life of me figure out how to do that. I'm pretty sure I compiled OpenCV with libjpeg but when I use the cmake gui to compile OpenMVS libjpeg isn't there. Any help with this would be greatly appreciated!

**Comment by 1z2z** [comment]
I have encountered the same problem. How did you solve it? Thank you.
