### ISSUE TITLE
Error When Reconstructing the Mesh

### ISSUE THREAD

**Issue by braden-dev** [cdcseacave/openMVS#758]
When I run the MvgMvsPipeline.py file I get this error pop up when it gets to the "Reconstruct the mesh" step:
![image](https://user-images.githubusercontent.com/69637496/154210071-da4f7215-ed2e-407c-a5c8-5d4cf129ba20.png)
and this is all the terminal says:
![image](https://user-images.githubusercontent.com/69637496/154210257-6f33d513-dfec-4339-892a-bb66c64f321a.png)

Have you seen this error before? Also is there any other kind of log I can provide that might give some more information?

**Comment by braden-dev** [comment]
I ended up using the ReconstructMesh.exe from the pre-built binaries and it worked. Still not sure why it wasn't able to launch when I built it though.

**Comment by guan-lin** [comment]
I met the same question,  when i run the ReconstructMesh.exe, the terminal says: 
![image](https://github.com/cdcseacave/openMVS/assets/65641960/ea8e1eb0-5924-431c-a68b-4989af0aa566)
And i have tested the OpenMVS 1.1  1.0, BOTH have this question. Boost 1.70.0 OpenCV 3.4.10 CGAL 5.2 ?

Have you solved it? Thanks!
