### ISSUE TITLE
List of 3D Points from the Dense Point Cloud

### ISSUE THREAD

**Issue by braden-dev** [cdcseacave/openMVS#759]
I was wondering if there's any way to get a list of the 3D points that make up the dense point cloud. In the ReconstructMesh.cpp file I see the function Export3DProjections which seems to do just what I'm asking about but it requires an "image-points-file" which contains the list of points from an image to project on the mesh.

I'm not entirely sure how I would make/find that to be able to get a list of the 3D points. Any help would be really appreciated, thanks!

**Comment by cdcseacave** [comment]
I do not understand what you need, Dense Point Cloud exports a PLY file, which is just the list of all 3D points

**Comment by cdcseacave** [comment]
yes, again that is what the PLY file is, a list of all 3d point coordinates; by default it is saved in binary mode, but if you save it in ASCII format it will be in text mode

**Comment by braden-dev** [comment]
> yes, again that is what the PLY file is, a list of all 3d point coordinates; by default it is saved in binary mode, but if you save it in ASCII format it will be in text mode

Ah okay, I misunderstood you initially. Thanks for the response, I got what I needed!
