### ISSUE TITLE
Not correct matrixes K,C,R

### ISSUE THREAD

**Issue by AJohnAA** [cdcseacave/openMVS#76]
When I try to make densified point cloud ( denseReconstruction()) I got a lot debug outputs. Especiall I got:
```
22:05:52 [App     ] K1 = 
 7906230.8790     0.0000  4674813.0732 
    0.0000  7906230.8790  3137838.2903 
    0.0000     0.0000     1.0000 

22:05:52 [App     ] R1 = 
    0.4998     0.2414     0.5021 
   -0.0087    -0.3494     0.0319 
    0.4804     0.2218     0.5287 

22:05:52 [App     ] C1 = 
    0.0001 
   -0.1668 
    0.0016 
```

And It looks like it compute matrix K1, R1, and vector C1 on "OpenMVS own". I cannot undertand why he do it. After all, I gave this data in scene object. Moreover, please note that K matrix is not correct ineed. 

Please make clear my doubts.

**Comment by cdcseacave** [comment]
Please follow the example in the apps folder!
