### ISSUE TITLE
Maybe we should use logger which could close output by `--verbosity (-v)` flag

### ISSUE THREAD

**Issue by FavorMylikes** [cdcseacave/openMVS#760]
https://github.com/cdcseacave/openMVS/blob/c658b72298019544a5b0522d303fc158f226857e/libs/Common/Util.h#L807

**Comment by cdcseacave** [comment]
can u pls describe the problem/improvement you suggest, I do not get it

**Comment by FavorMylikes** [comment]
I mean, if we add -v 0 as the log level flag, it still print and update your process bar.

This process bar is not control by `--verbosity`

**Comment by cdcseacave** [comment]
verbosity can be turned off completely if you define `#define TD_VERBOSE TD_VERBOSE_OFF`
