### ISSUE TITLE
Usage of hidden option --split-max-area in ReconstructMesh module

### ISSUE THREAD

**Issue by 3XH6R** [cdcseacave/openMVS#764]
How do you use the hidden option `--split-max-area` in the ReconstructMesh module?

Trying `ReconstructMesh scene_dense.mvs -w .\ --split-max-area 660000`
It loads the scene then ends, nothing gets exported.

Version 2.0 commit 65b90bd

**Comment by cdcseacave** [comment]
pls check https://github.com/cdcseacave/openMVS/issues/438#issuecomment-800972596
