### ISSUE TITLE
I cannot convert openMVG(sfm_data.bin) file to .mvs file correctly!

### ISSUE THREAD

**Issue by nuli0355** [cdcseacave/openMVS#77]
### Specifications like the version of the project, operating system, and hardware
latest InterfaceOpenMVG.cpp;     win8.1
### Steps to reproduce the problem
My  optiopns:
InterfaceOpenMVG.exe
--input-file .../ImageDataset_SceauxCastle-master//sfm_data.bin
 --output-file .../scene.mvs"
 --output-image-folder .../test//"
problems:
13:49:43 [App     ] Imported data: 1 cameras, 11 poses, 11 images, 6295 vertices
13:49:51 [IO      ] error: unknown image format 'C://Users//xXx//Desktop//lena//100_7100.JPG'
13:49:51 [App     ] error: failed loading image header
13:49:51 [App     ] error: failed reloading image 'C://Users//xXx//Desktop//lena//100_7100.JPG'
13:49:51 [App     ] error: can not read image C://Users//xXx//Desktop//lena//100_7100.JPG
13:49:51 [IO      ] error: unknown image format 'C://Users//xXx//Desktop//lena//100_7101.JPG'
13:49:51 [App     ] error: failed loading image header
13:49:51 [App     ] error: failed reloading image 'C://Users//xXx//Desktop//lena//100_7101.JPG'
13:49:51 [App     ] error: can not read image C://Users//xXx//Desktop//lena//100_7101.JPG
13:49:51 [IO      ] error: unknown image format 'C://Users//xXx//Desktop//lena//100_7102.JPG'

scene.mvs can be generated，but cannot generate densepoint.ply
Thank you!

**Comment by cdcseacave** [comment]
could you share the dataset (images and bin file) to debug it?

**Comment by nuli0355** [comment]
![100_7100](https://cloud.githubusercontent.com/assets/15178973/14402140/853d5ef0-fe5d-11e5-9fb8-2c1cd3f186b2.JPG)
![100_7101](https://cloud.githubusercontent.com/assets/15178973/14402139/853cd1a6-fe5d-11e5-8ab6-004048d7f0ae.JPG)
![100_7102](https://cloud.githubusercontent.com/assets/15178973/14402141/854052b8-fe5d-11e5-8619-bf3d45fc95d2.JPG)
![100_7103](https://cloud.githubusercontent.com/assets/15178973/14402142/8542cc50-fe5d-11e5-9c25-614f553b598b.JPG)
![100_7104](https://cloud.githubusercontent.com/assets/15178973/14402143/8560eea6-fe5d-11e5-8f0d-765886ac5dfb.JPG)
![100_7105](https://cloud.githubusercontent.com/assets/15178973/14402144/85eb652c-fe5d-11e5-89df-31ffe75c25c9.JPG)
![100_7106](https://cloud.githubusercontent.com/assets/15178973/14402145/861ef93c-fe5d-11e5-9247-158221ca9147.JPG)
![100_7107](https://cloud.githubusercontent.com/assets/15178973/14402146/862975e2-fe5d-11e5-987a-100e6039f51d.JPG)
![100_7108](https://cloud.githubusercontent.com/assets/15178973/14402147/862cc490-fe5d-11e5-9db9-d1c7bd58ee18.JPG)
![100_7109](https://cloud.githubusercontent.com/assets/15178973/14402148/864bf8c4-fe5d-11e5-9e7e-02271ec06adc.JPG)
![100_7110](https://cloud.githubusercontent.com/assets/15178973/14402149/86b266ea-fe5d-11e5-9463-a1c7a79b220a.JPG)

**Comment by cdcseacave** [comment]
and bin?

**Comment by nuli0355** [comment]
[sfm_data.txt](https://github.com/cdcseacave/openMVS/files/211110/sfm_data.txt)
I cannot upload zip file,so please Change the file extension to " .bin"

**Comment by cdcseacave** [comment]
I can not debug the sfm_data.bin you sent me cause it stored full path to images and I can not reproduce it.

But I tried reconstructing the images with OpenMVG and then run OpenMVS on the sfm_data.bin I got and it works like a charm.

Make sure you follow well the steps described in the Wiki.

**Comment by nuli0355** [comment]
Oh,I stored full path to images,but I modify path in interfaceopenMVG.cpp when i run it,Could you send me your log file?

**Comment by cdcseacave** [comment]
why would you modify interfaceopenMVG.cpp for that? that sounds so crazy

I didn't even use interfaceopenMVG, I used the exporter inside OpenMVG

apparently you don't feel like reading the wiki, so we end this here
