### ISSUE TITLE
Building on Ubuntu 18.04 Error

### ISSUE THREAD

**Issue by YuhsiHu** [cdcseacave/openMVS#770]
**Describe the bug**
Some error about filesystem and InterfaceCOLMAP when building on ubuntu 18.04

**To Reproduce**
1. Use command in Building.md:
mkdir openMVS_build && cd openMVS_build
cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT="$main_path/vcglib"
2. Everything is good. But when I input make -j2 && sudo make install, somenthing went wrong.

[ 67%] Linking CUDA device code CMakeFiles/InterfaceMetashape.dir/cmake_device_link.o
[ 69%] Linking CXX executable ../../bin/InterfaceMetashape
../../lib/libCommon.a(Util.cpp.o)：在函数‘SEACAVE::Util::GetDiskInfo(SEACAVE::String const&)’中：
Util.cpp:(.text._ZN7SEACAVE4Util11GetDiskInfoERKNS_6StringE+0x72)：对‘std::filesystem::__cxx11::path::_M_split_cmpts()’未定义的引用
Util.cpp:(.text._ZN7SEACAVE4Util11GetDiskInfoERKNS_6StringE+0x7d)：对‘std::filesystem::space(std::filesystem::__cxx11::path const&)’未定义的引用
collect2: error: ld returned 1 exit status
apps/InterfaceMetashape/CMakeFiles/InterfaceMetashape.dir/build.make:231: recipe for target 'bin/InterfaceMetashape' failed
make[2]: *** [bin/InterfaceMetashape] Error 1
CMakeFiles/Makefile2:463: recipe for target 'apps/InterfaceMetashape/CMakeFiles/InterfaceMetashape.dir/all' failed
make[1]: *** [apps/InterfaceMetashape/CMakeFiles/InterfaceMetashape.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 70%] Linking CUDA device code CMakeFiles/InterfaceCOLMAP.dir/cmake_device_link.o
[ 71%] Linking CXX executable ../../bin/InterfaceCOLMAP
../../lib/libCommon.a(Util.cpp.o)：在函数‘SEACAVE::Util::GetDiskInfo(SEACAVE::String const&)’中：
Util.cpp:(.text._ZN7SEACAVE4Util11GetDiskInfoERKNS_6StringE+0x72)：对‘std::filesystem::__cxx11::path::_M_split_cmpts()’未定义的引用
Util.cpp:(.text._ZN7SEACAVE4Util11GetDiskInfoERKNS_6StringE+0x7d)：对‘std::filesystem::space(std::filesystem::__cxx11::path const&)’未定义的引用
collect2: error: ld returned 1 exit status
apps/InterfaceCOLMAP/CMakeFiles/InterfaceCOLMAP.dir/build.make:231: recipe for target 'bin/InterfaceCOLMAP' failed
make[2]: *** [bin/InterfaceCOLMAP] Error 1
CMakeFiles/Makefile2:405: recipe for target 'apps/InterfaceCOLMAP/CMakeFiles/InterfaceCOLMAP.dir/all' failed
make[1]: *** [apps/InterfaceCOLMAP/CMakeFiles/InterfaceCOLMAP.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - gcc-8 g++-8 

**Additional context**
I have tried method mentioned in issue #744 and #548 and also add link libraries in apps/CMakeLists.txt:
link_libraries("/usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.65.1")
link_libraries("/usr/lib/gcc/x86_64-linux-gnu/8/libstdc++fs.a")

But it did not work.

By the way, I have tried gcc 6 and 7 and they did not work. However, when I switched gcc to 9, it worked.

**Comment by dineshdhotrad** [comment]
Hello,
https://youtube.com/playlist?list=PLSsp6nX9eDuUdrCPVkucRNuzmFSiIrd2V
Look through this video tutorial you might be able to figure out some outcome.
Thank You.😊

**Comment by arsee11** [comment]
I got the same problem when use gcc-8.3, change to gcc-10.2 sloved it

**Comment by arsee11** [comment]
I got the same problem when use gcc-8.3, changed to gcc-10.2 sloved it

**Comment by YuhsiHu** [comment]
Thank you for your sharing.
It seems that contributors are not going to fix that. So upgrade GCC can solve it.

**Comment by flashlau** [comment]
Thank you! @arsee11
I install gcc10 and solve it. (https://askubuntu.com/questions/1192955/how-to-install-g-10-on-ubuntu-18-04)
