### ISSUE TITLE
CUDA only partially detected, CUDA 11.6 on Ubuntu

### ISSUE THREAD

**Issue by Rheinwalt** [cdcseacave/openMVS#772]
I'm trying to build openMVS on Ubuntu with CUDA 11.6. inside a conda environment. My CUDA is installed under /usr/local/cuda so I configure using cmake like the following:

`(openMVS) $ cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT=/path_to/vcglib -DCMAKE_INSTALL_PREFIX=/install_to_path/conda/OpenMVS -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda`

This seems to find CUDA, but then fails:
```
[...]
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found version "11.6")
CMake Error at /raid-everest/conda/miniconda3/envs/openMVS/share/cmake-3.22/Modules/CMakeDetermineCUDACompiler.cmake:226 (message):
  Couldn't find CUDA library root.
Call Stack (most recent call first):
  CMakeLists.txt:104 (ENABLE_LANGUAGE)


-- Configuring incomplete, errors occurred!
See also "/raid-everest/arheinwalt/src/openMVS_build/CMakeFiles/CMakeOutput.log".
See also "/raid-everest/arheinwalt/src/openMVS_build/CMakeFiles/CMakeError.log".
```

Somehow the cmake from conda gets confused?

**Comment by cdcseacave** [comment]
pls try the way I do it in the Docker file example, might work

**Comment by Rheinwalt** [comment]
No success, I tried this now:
cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT=../vcglib -DOpenMVS_USE_CUDA=ON -DCMAKE_LIBRARY_PATH=/usr/local/cuda-11.6/lib64/stubs/ -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-11.6/ -DCUDA_INCLUDE_DIRS=/usr/local/cuda-11.6/include/ -DCUDA_CUDART_LIBRARY=/usr/local/cuda-11.6/lib64/ -DCUDA_NVCC_EXECUTABLE=/usr/local/cuda-11.6/bin/

And it fails the same way:
[...]
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda-11.6/ (found version "11.6")
CMake Error at /raid-everest/conda/miniconda3/envs/openMVS/share/cmake-3.22/Modules/CMakeDetermineCUDACompiler.cmake:226 (message):
  Couldn't find CUDA library root.
Call Stack (most recent call first):
  CMakeLists.txt:104 (ENABLE_LANGUAGE)

I guess this weird mixture of conda cmake and system cuda might be the problem?

**Comment by Rheinwalt** [comment]
If I do the same outside of the conda environment it fails to find cuda_runtime.h in its nvcc test although I specified CUDA_INCLUDE_DIRS:

[...]
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda-11.6/ (found version "11.6")
-- The CUDA compiler identification is unknown
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/usr/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /raid-everest/arheinwalt/src/openMVS_build/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_06e71/fast"
    /usr/bin/make -f CMakeFiles/cmTC_06e71.dir/build.make CMakeFiles/cmTC_06e71.dir/build
    make[1]: Entering directory '/raid-everest/arheinwalt/src/openMVS_build/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_06e71.dir/main.cu.o
    /usr/bin/nvcc     -x cu -c /raid-everest/arheinwalt/src/openMVS_build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_06e71.dir/main.cu.o
    cc1plus: fatal error: cuda_runtime.h: No such file or directory
    compilation terminated.
[...]

**Comment by Rheinwalt** [comment]
> If I do the same outside of the conda environment it fails to find cuda_runtime.h in its nvcc test although I specified CUDA_INCLUDE_DIRS:
> 
> [...]
> 
> ```
> -- Found Threads: TRUE
> -- Found CUDA: /usr/local/cuda-11.6/ (found version "11.6")
> -- The CUDA compiler identification is unknown
> -- Check for working CUDA compiler: /usr/bin/nvcc
> -- Check for working CUDA compiler: /usr/bin/nvcc -- broken
> CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCUDACompiler.cmake:46 (message):
>   The CUDA compiler
> 
>     "/usr/bin/nvcc"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: /raid-everest/arheinwalt/src/openMVS_build/CMakeFiles/CMakeTmp
> 
>     Run Build Command:"/usr/bin/make" "cmTC_06e71/fast"
>     /usr/bin/make -f CMakeFiles/cmTC_06e71.dir/build.make CMakeFiles/cmTC_06e71.dir/build
>     make[1]: Entering directory '/raid-everest/arheinwalt/src/openMVS_build/CMakeFiles/CMakeTmp'
>     Building CUDA object CMakeFiles/cmTC_06e71.dir/main.cu.o
>     /usr/bin/nvcc     -x cu -c /raid-everest/arheinwalt/src/openMVS_build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_06e71.dir/main.cu.o
>     cc1plus: fatal error: cuda_runtime.h: No such file or directory
>     compilation terminated.
> ```
> 
> [...]

Ok, so this error was due to a symlink to nvcc in /usr/bin which nvcc **does not** like. When we removed that link we could install it outside conda with:

`cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT=/path_to/vcglib -DCMAKE_INSTALL_PREFIX=/install_to_path/conda/OpenMVS -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
`

All set now. Thanks for this excellent software!
