### ISSUE TITLE
Unable to Generate DepthMaps with Resolution Level 0 on GPU Machines

### ISSUE THREAD

**Issue by vivekmistry** [cdcseacave/openMVS#773]
In ODM, under OpenMVS stage, we tried to generate DepthMaps with Resolution Level 0 on CPU Machines. It works well but takes too much time to generate depth maps.
As an alternate solution tried to generate DepthMaps on the GPU machine but stop abruptly w/o any error. Please suggest, why there is different behavior for CPU and GPU machines?

**Comment by vivekmistry** [comment]
Please let me know if you need more information?

**Comment by pierotofy** [comment]
Why open so many threads? You've already opened a discussion on https://community.opendronemap.org/t/unable-to-generate-depths-for-resolution-level-0-with-gpu-docker/10865/3 :no_good:

**Comment by vivekmistry** [comment]
Had first raised issue here, but since there was no response had open discussion in ODM git and coummunity
