### ISSUE TITLE
Mesh.cpp:980:9: error on Mac OS

### ISSUE THREAD

**Issue by cogitas3d** [cdcseacave/openMVS#775]
Hi my friends!

I had problems again with Mac.

All works well with make until 52%, so, the error appear:

`[ 52%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/Mesh.cpp.o
/Users/ciceromoraes/Programs/openMVS/libs/MVS/Mesh.cpp:980:9: error: no template
      named 'BasicVertexPair'; did you mean 'vcg::tri::BasicVertexPair'?
typedef BasicVertexPair<Vertex> VertexPair;
        ^~~~~~~~~~~~~~~
        vcg::tri::BasicVertexPair
/Users/ciceromoraes/Programs/vcglib/vcg/complex/algorithms/edge_collapse.h:34:7: note: 
      'vcg::tri::BasicVertexPair' declared here
class BasicVertexPair {
      ^
/Users/ciceromoraes/Programs/openMVS/libs/MVS/Mesh.cpp:1042:6: error: no member
      named 'BoundaryWeight' in 'vcg::tri::TriEdgeCollapseQuadricParameter'
                pp.BoundaryWeight = 1; // the importance of the boundar...
                ~~ ^
2 errors generated.
make[2]: *** [libs/MVS/CMakeFiles/MVS.dir/Mesh.cpp.o] Error 1
make[1]: *** [libs/MVS/CMakeFiles/MVS.dir/all] Error 2
make: *** [all] Error 2`

Is it possible to solve this?

**Comment by cdcseacave** [comment]
are you using latest openmvs develop with latest https://github.com/cdcseacave/VCG?

**Comment by cogitas3d** [comment]
@cdcseacave 

O follow the default steps to build on Mac (https://github.com/cdcseacave/openMVS/wiki/Building).

**Comment by cdcseacave** [comment]
that is great, I am asking though if you are using latest code of both openmvs and vcg

**Comment by cogitas3d** [comment]
I think yes, because I follow the steps yesterday.

**Comment by cdcseacave** [comment]
I've just tested on my mac and it all works fine

**Comment by cogitas3d** [comment]
Finally i sove this!

1) I downloaded the 'develop' branch version;
2) I try to build and I had error, because the liboost lib, so I use the command: 
`brew install boost && sed -i.bak -E 's/NO_ZSTD=1/NO_ZSTD=0/' /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb && brew reinstall boost --build-from-source`
3) So, I build and it works!
