### ISSUE TITLE
In DensifyPointCloud Module, When scale input images, why you choose cv::INTER_AREA ?

### ISSUE THREAD

**Issue by Why384040146** [cdcseacave/openMVS#776]
When image assumed to be the coordinates and  with 0.5, I think scale algorithm choose cv::INTER_LINEAR better, for keep center invariant?

**Comment by cdcseacave** [comment]
not sure what you mean, pls read the description of various interpolation methods in OpenCV

**Comment by Why384040146** [comment]
ok thks
