### ISSUE TITLE
EXIF image rotation is ignored in COLMAP

### ISSUE THREAD

**Issue by tompollok** [cdcseacave/openMVS#777]
How does openMVS handle JPG EXIF rotation metadata? In COLMAP they completely ignore the image rotation tag, so that intrinsics can optimized from all images from the same camera, instead of estimatine separate intrinsics for rotated images.

The problem in my case is that the intrinsics and extrinsics do not match when the exif metadata is taken into account. I realized that in my own application.

Does OpenMVS rotate the image accodring to the EXIF tag? If so, would it make sense to add an ignore exif rotation parameter, so that there arent any issues with the camera poses and intrinsics from COLMAP?

I had some crashes when using openmvs in datasets with EXIF Metadata in combination with COLMAP sparse pose estimation - i havent checked yet, if that is due to the exif metadata.

**Comment by cdcseacave** [comment]
the steps you are using sound wrong; there is no EXIF info in the images that get to OpenMVS (and even if there was, it is completely useless, as I get all the data from the calibrated cameras); that suggests that you are not using the tools well; if using COLMAP for SfM (though I suggest to use OpenMVG which is more accurate), you need to generate the undistorted images and cameras, and you pass those to OpenMVS; you should NEVER use the cameras and images directly from the SfM step of COLMAP

OpenMVS contains a python script that can automatically call OpenMVG for SfM and OpenMVS for MVS, all you need to do is point it to the folder where the raw images are: 
```
python3 MvgMvsPipeline.py images output
```
Use it especially if you are a beginner

**Comment by tompollok** [comment]
I guess i forgot to undistort the images before passing them to openmvs. I thought openmvs handles this using the intrinsic calibration data. Thank you for the hint. In the past always had very good visual results. Anyways thank you for your quick reply.
