### ISSUE TITLE
Mesh.cpp error on Ubuntu 20.04

### ISSUE THREAD

**Issue by nianhuasong** [cdcseacave/openMVS#778]
**Describe the bug**
I had problems again with Ubuntu.
There are so many warnings and errors.
I follow the docs(https://github.com/cdcseacave/openMVS/wiki/Building) and use latest code of both openmvs and vcg.I try many times,but the result is always same.Can anybody help me?
**makelist**
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected version of GNU GCC: 94 (904)
Compiling with C++17
-- Performing Test HAVE_CXX_W
-- Performing Test HAVE_CXX_W - Success
-- Performing Test HAVE_C_W
-- Performing Test HAVE_C_W - Success
-- Performing Test HAVE_CXX_WALL
-- Performing Test HAVE_CXX_WALL - Success
-- Performing Test HAVE_C_WALL
-- Performing Test HAVE_C_WALL - Success
-- Performing Test HAVE_CXX_WERROR_ADDRESS
-- Performing Test HAVE_CXX_WERROR_ADDRESS - Success
-- Performing Test HAVE_C_WERROR_ADDRESS
-- Performing Test HAVE_C_WERROR_ADDRESS - Success
-- Performing Test HAVE_CXX_WERROR_SEQUENCE_POINT
-- Performing Test HAVE_CXX_WERROR_SEQUENCE_POINT - Success
-- Performing Test HAVE_C_WERROR_SEQUENCE_POINT
-- Performing Test HAVE_C_WERROR_SEQUENCE_POINT - Success
-- Performing Test HAVE_CXX_WFORMAT
-- Performing Test HAVE_CXX_WFORMAT - Success
-- Performing Test HAVE_C_WFORMAT
-- Performing Test HAVE_C_WFORMAT - Success
-- Performing Test HAVE_CXX_WERROR_FORMAT_SECURITY
-- Performing Test HAVE_CXX_WERROR_FORMAT_SECURITY - Success
-- Performing Test HAVE_C_WERROR_FORMAT_SECURITY
-- Performing Test HAVE_C_WERROR_FORMAT_SECURITY - Success
-- Performing Test HAVE_CXX_WSTRICT_PROTOTYPES
-- Performing Test HAVE_CXX_WSTRICT_PROTOTYPES - Failed
-- Performing Test HAVE_C_WSTRICT_PROTOTYPES
-- Performing Test HAVE_C_WSTRICT_PROTOTYPES - Success
-- Performing Test HAVE_CXX_WINIT_SELF
-- Performing Test HAVE_CXX_WINIT_SELF - Success
-- Performing Test HAVE_C_WINIT_SELF
-- Performing Test HAVE_C_WINIT_SELF - Success
-- Performing Test HAVE_CXX_WSIGN_PROMO
-- Performing Test HAVE_CXX_WSIGN_PROMO - Success
-- Performing Test HAVE_C_WSIGN_PROMO
-- Performing Test HAVE_C_WSIGN_PROMO - Failed
-- Performing Test HAVE_CXX_WREORDER
-- Performing Test HAVE_CXX_WREORDER - Success
-- Performing Test HAVE_C_WREORDER
-- Performing Test HAVE_C_WREORDER - Failed
-- Performing Test HAVE_CXX_WNO_UNDEF
-- Performing Test HAVE_CXX_WNO_UNDEF - Success
-- Performing Test HAVE_C_WNO_UNDEF
-- Performing Test HAVE_C_WNO_UNDEF - Success
-- Performing Test HAVE_CXX_WNO_SWITCH
-- Performing Test HAVE_CXX_WNO_SWITCH - Success
-- Performing Test HAVE_C_WNO_SWITCH
-- Performing Test HAVE_C_WNO_SWITCH - Success
-- Performing Test HAVE_CXX_WNO_SWITCH_ENUM
-- Performing Test HAVE_CXX_WNO_SWITCH_ENUM - Success
-- Performing Test HAVE_C_WNO_SWITCH_ENUM
-- Performing Test HAVE_C_WNO_SWITCH_ENUM - Success
-- Performing Test HAVE_CXX_WNO_SWITCH_DEFAULT
-- Performing Test HAVE_CXX_WNO_SWITCH_DEFAULT - Success
-- Performing Test HAVE_C_WNO_SWITCH_DEFAULT
-- Performing Test HAVE_C_WNO_SWITCH_DEFAULT - Success
-- Performing Test HAVE_CXX_WNO_IMPLICIT_FALLTHROUGH
-- Performing Test HAVE_CXX_WNO_IMPLICIT_FALLTHROUGH - Success
-- Performing Test HAVE_C_WNO_IMPLICIT_FALLTHROUGH
-- Performing Test HAVE_C_WNO_IMPLICIT_FALLTHROUGH - Success
-- Performing Test HAVE_CXX_WNO_COMMENT
-- Performing Test HAVE_CXX_WNO_COMMENT - Success
-- Performing Test HAVE_C_WNO_COMMENT
-- Performing Test HAVE_C_WNO_COMMENT - Success
-- Performing Test HAVE_CXX_WNO_NARROWING
-- Performing Test HAVE_CXX_WNO_NARROWING - Success
-- Performing Test HAVE_C_WNO_NARROWING
-- Performing Test HAVE_C_WNO_NARROWING - Success
-- Performing Test HAVE_CXX_WNO_ATTRIBUTES
-- Performing Test HAVE_CXX_WNO_ATTRIBUTES - Success
-- Performing Test HAVE_C_WNO_ATTRIBUTES
-- Performing Test HAVE_C_WNO_ATTRIBUTES - Success
-- Performing Test HAVE_CXX_WNO_IGNORED_ATTRIBUTES
-- Performing Test HAVE_CXX_WNO_IGNORED_ATTRIBUTES - Success
-- Performing Test HAVE_C_WNO_IGNORED_ATTRIBUTES
-- Performing Test HAVE_C_WNO_IGNORED_ATTRIBUTES - Success
-- Performing Test HAVE_CXX_WNO_MAYBE_UNINITIALIZED
-- Performing Test HAVE_CXX_WNO_MAYBE_UNINITIALIZED - Success
-- Performing Test HAVE_C_WNO_MAYBE_UNINITIALIZED
-- Performing Test HAVE_C_WNO_MAYBE_UNINITIALIZED - Success
-- Performing Test HAVE_CXX_WNO_ENUM_COMPARE
-- Performing Test HAVE_CXX_WNO_ENUM_COMPARE - Success
-- Performing Test HAVE_C_WNO_ENUM_COMPARE
-- Performing Test HAVE_C_WNO_ENUM_COMPARE - Success
-- Performing Test HAVE_CXX_WNO_MISLEADING_INDENTATION
-- Performing Test HAVE_CXX_WNO_MISLEADING_INDENTATION - Success
-- Performing Test HAVE_C_WNO_MISLEADING_INDENTATION
-- Performing Test HAVE_C_WNO_MISLEADING_INDENTATION - Success
-- Performing Test HAVE_CXX_WNO_MISSING_FIELD_INITIALIZERS
-- Performing Test HAVE_CXX_WNO_MISSING_FIELD_INITIALIZERS - Success
-- Performing Test HAVE_C_WNO_MISSING_FIELD_INITIALIZERS
-- Performing Test HAVE_C_WNO_MISSING_FIELD_INITIALIZERS - Success
-- Performing Test HAVE_CXX_WNO_UNUSED_RESULT
-- Performing Test HAVE_CXX_WNO_UNUSED_RESULT - Success
-- Performing Test HAVE_C_WNO_UNUSED_RESULT
-- Performing Test HAVE_C_WNO_UNUSED_RESULT - Success
-- Performing Test HAVE_CXX_WNO_UNUSED_FUNCTION
-- Performing Test HAVE_CXX_WNO_UNUSED_FUNCTION - Success
-- Performing Test HAVE_C_WNO_UNUSED_FUNCTION
-- Performing Test HAVE_C_WNO_UNUSED_FUNCTION - Success
-- Performing Test HAVE_CXX_WNO_UNUSED_PARAMETER
-- Performing Test HAVE_CXX_WNO_UNUSED_PARAMETER - Success
-- Performing Test HAVE_C_WNO_UNUSED_PARAMETER
-- Performing Test HAVE_C_WNO_UNUSED_PARAMETER - Success
-- Performing Test HAVE_CXX_WNO_DELETE_INCOMPLETE
-- Performing Test HAVE_CXX_WNO_DELETE_INCOMPLETE - Success
-- Performing Test HAVE_C_WNO_DELETE_INCOMPLETE
-- Performing Test HAVE_C_WNO_DELETE_INCOMPLETE - Failed
-- Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Performing Test HAVE_CXX_WNO_INT_IN_BOOL_CONTEXT
-- Performing Test HAVE_CXX_WNO_INT_IN_BOOL_CONTEXT - Success
-- Performing Test HAVE_C_WNO_INT_IN_BOOL_CONTEXT
-- Performing Test HAVE_C_WNO_INT_IN_BOOL_CONTEXT - Success
-- Performing Test HAVE_CXX_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HAVE_CXX_FDIAGNOSTICS_SHOW_OPTION - Success
-- Performing Test HAVE_C_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HAVE_C_FDIAGNOSTICS_SHOW_OPTION - Success
-- Performing Test HAVE_CXX_FTEMPLATE_BACKTRACE_LIMIT_0
-- Performing Test HAVE_CXX_FTEMPLATE_BACKTRACE_LIMIT_0 - Success
-- Performing Test HAVE_C_FTEMPLATE_BACKTRACE_LIMIT_0
-- Performing Test HAVE_C_FTEMPLATE_BACKTRACE_LIMIT_0 - Failed
-- Performing Test HAVE_CXX_WNO_LONG_LONG
-- Performing Test HAVE_CXX_WNO_LONG_LONG - Success
-- Performing Test HAVE_C_WNO_LONG_LONG
-- Performing Test HAVE_C_WNO_LONG_LONG - Success
-- Performing Test HAVE_CXX_PTHREAD
-- Performing Test HAVE_CXX_PTHREAD - Success
-- Performing Test HAVE_C_PTHREAD
-- Performing Test HAVE_C_PTHREAD - Success
-- Performing Test HAVE_CXX_FOMIT_FRAME_POINTER
-- Performing Test HAVE_CXX_FOMIT_FRAME_POINTER - Success
-- Performing Test HAVE_C_FOMIT_FRAME_POINTER
-- Performing Test HAVE_C_FOMIT_FRAME_POINTER - Success
-- Performing Test HAVE_CXX_FROUNDING_MATH
-- Performing Test HAVE_CXX_FROUNDING_MATH - Success
-- Performing Test HAVE_C_FROUNDING_MATH
-- Performing Test HAVE_C_FROUNDING_MATH - Success
-- Performing Test HAVE_CXX_MSSE
-- Performing Test HAVE_CXX_MSSE - Success
-- Performing Test HAVE_C_MSSE
-- Performing Test HAVE_C_MSSE - Success
-- Performing Test HAVE_CXX_MSSE2
-- Performing Test HAVE_CXX_MSSE2 - Success
-- Performing Test HAVE_C_MSSE2
-- Performing Test HAVE_C_MSSE2 - Success
-- Performing Test HAVE_CXX_MSSE3
-- Performing Test HAVE_CXX_MSSE3 - Success
-- Performing Test HAVE_C_MSSE3
-- Performing Test HAVE_C_MSSE3 - Success
-- Performing Test HAVE_CXX_MSSSE3
-- Performing Test HAVE_CXX_MSSSE3 - Success
-- Performing Test HAVE_C_MSSSE3
-- Performing Test HAVE_C_MSSSE3 - Success
-- Performing Test HAVE_CXX_MSSE4_1
-- Performing Test HAVE_CXX_MSSE4_1 - Success
-- Performing Test HAVE_C_MSSE4_1
-- Performing Test HAVE_C_MSSE4_1 - Success
-- Performing Test HAVE_CXX_MSSE4_2
-- Performing Test HAVE_CXX_MSSE4_2 - Success
-- Performing Test HAVE_C_MSSE4_2
-- Performing Test HAVE_C_MSSE4_2 - Success
-- Performing Test HAVE_CXX_FFUNCTION_SECTIONS
-- Performing Test HAVE_CXX_FFUNCTION_SECTIONS - Success
-- Performing Test HAVE_C_FFUNCTION_SECTIONS
-- Performing Test HAVE_C_FFUNCTION_SECTIONS - Success
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Can't find CUDA. Continuing without it.
-- WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: iostreams program_options system serialization 
-- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "2.91.0") 
-- Eigen 3.4.0 found (include: /usr/local/include/eigen3)
-- Found OpenCV: /usr/local (found version "3.4.16") 
-- OpenCV 3.4.16 found (include: /usr/local/include;/usr/local/include/opencv)
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so  
-- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so  
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")  
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
-- VCG  found (include: /home/zhang/include/VCG-master)
-- GLEW 2.1.0 found (include: /usr/include)
-- GLFW3 3.3.2 found (include: )
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zhang/include/openMVS_build

**cmake log**
  1%] Building CXX object libs/Common/CMakeFiles/Common.dir/cmake_pch.hxx.gch
[  2%] Building CXX object libs/Common/CMakeFiles/Common.dir/Common.cpp.o
[  4%] Building CXX object libs/Common/CMakeFiles/Common.dir/ConfigTable.cpp.o
[  5%] Building CXX object libs/Common/CMakeFiles/Common.dir/EventQueue.cpp.o
[  7%] Building CXX object libs/Common/CMakeFiles/Common.dir/Log.cpp.o
In file included from /usr/include/string.h:495,
                 from /home/zhang/include/openMVS/libs/Common/Types.h:28,
                 from /home/zhang/include/openMVS/libs/Common/Common.h:176,
                 from /home/zhang/include/openMVS_build/libs/Common/CMakeFiles/Common.dir/cmake_pch.hxx:5,
                 from <command-line>:
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘SEACAVE::Log::Idx SEACAVE::Log::RegisterType(LPCTSTR)’ at /home/zhang/include/openMVS/libs/Common/Log.cpp:67:10:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: warning: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/zhang/include/openMVS/libs/Common/Log.cpp: In member function ‘SEACAVE::Log::Idx SEACAVE::Log::RegisterType(LPCTSTR)’:
/home/zhang/include/openMVS/libs/Common/Log.cpp:66:26: note: length computed here
   66 |  Idx n = MINF((Idx)strlen(lt), (Idx)LOGTYPE_SIZE);
      |                    ~~~~~~^~~~
[  8%] Building CXX object libs/Common/CMakeFiles/Common.dir/SML.cpp.o
[ 10%] Building CXX object libs/Common/CMakeFiles/Common.dir/Timer.cpp.o
[ 11%] Building CXX object libs/Common/CMakeFiles/Common.dir/Types.cpp.o
[ 13%] Building CXX object libs/Common/CMakeFiles/Common.dir/Util.cpp.o
[ 14%] Building CXX object libs/Common/CMakeFiles/Common.dir/UtilCUDA.cpp.o
[ 16%] Linking CXX static library ../../lib/libCommon.a
[ 16%] Built target Common
Scanning dependencies of target Math
[ 17%] Building CXX object libs/Math/CMakeFiles/Math.dir/cmake_pch.hxx.gch
[ 19%] Building CXX object libs/Math/CMakeFiles/Math.dir/Common.cpp.o
[ 20%] Building CXX object libs/Math/CMakeFiles/Math.dir/IBFS/IBFS.cpp.o
[ 22%] Building CXX object libs/Math/CMakeFiles/Math.dir/LMFit/lmmin.cpp.o
[ 23%] Linking CXX static library ../../lib/libMath.a
[ 23%] Built target Math
Scanning dependencies of target IO
[ 25%] Building CXX object libs/IO/CMakeFiles/IO.dir/cmake_pch.hxx.gch
[ 26%] Building CXX object libs/IO/CMakeFiles/IO.dir/Common.cpp.o
[ 27%] Building CXX object libs/IO/CMakeFiles/IO.dir/Image.cpp.o
[ 29%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImageBMP.cpp.o
[ 30%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImageDDS.cpp.o
[ 32%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImageJPG.cpp.o
/home/zhang/include/openMVS/libs/IO/ImageJPG.cpp: In member function ‘virtual HRESULT SEACAVE::CImageJPG::ReadData(void*, SEACAVE::PIXELFORMAT, SEACAVE::CImage::Size, SEACAVE::CImage::Size)’:
/home/zhang/include/openMVS/libs/IO/ImageJPG.cpp:186:13: warning: variable ‘state’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
  186 |  JpegState* state = (JpegState*)m_state;
      |             ^~~~~
[ 33%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImagePNG.cpp.o
[ 35%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImageSCI.cpp.o
[ 36%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImageTGA.cpp.o
[ 38%] Building CXX object libs/IO/CMakeFiles/IO.dir/ImageTIFF.cpp.o
[ 39%] Building CXX object libs/IO/CMakeFiles/IO.dir/OBJ.cpp.o
[ 41%] Building CXX object libs/IO/CMakeFiles/IO.dir/PLY.cpp.o
[ 42%] Building CXX object libs/IO/CMakeFiles/IO.dir/TinyXML2.cpp.o
[ 44%] Linking CXX static library ../../lib/libIO.a
[ 44%] Built target IO
Scanning dependencies of target MVS
[ 45%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/cmake_pch.hxx.gch
[ 47%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/Camera.cpp.o
/home/zhang/include/openMVS/libs/MVS/Camera.cpp: In function ‘void MVS::DecomposeProjectionMatrix(const PMatrix&, SEACAVE::KMatrix&, SEACAVE::RMatrix&, SEACAVE::CMatrix&)’:
/home/zhang/include/openMVS/libs/MVS/Camera.cpp:138:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  138 |  C = (const CMatrix&)hC * INVERT(hC[3]);
      |                      ^~
/home/zhang/include/openMVS/libs/MVS/Camera.cpp:138:39: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  138 |  C = (const CMatrix&)hC * INVERT(hC[3]);
      |                                       ^
/home/zhang/include/openMVS/libs/MVS/Camera.cpp: In function ‘void MVS::DecomposeProjectionMatrix(const PMatrix&, SEACAVE::RMatrix&, SEACAVE::CMatrix&)’:
/home/zhang/include/openMVS/libs/MVS/Camera.cpp:165:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  165 |  C = (const CMatrix&)hC * INVERT(hC[3]);
      |                      ^~
/home/zhang/include/openMVS/libs/MVS/Camera.cpp:165:39: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  165 |  C = (const CMatrix&)hC * INVERT(hC[3]);
      |                                       ^
[ 48%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/Common.cpp.o
[ 50%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/DepthMap.cpp.o
/home/zhang/include/openMVS/libs/MVS/DepthMap.cpp: In member function ‘bool MVS::DepthEstimator::FillPixelPatch()’:
/home/zhang/include/openMVS/libs/MVS/DepthMap.cpp:446:28: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  446 |  reinterpret_cast<Point3&>(X0) = image0.camera.TransformPointI2C(Cast<REAL>(x0));
      |                            ^~
/home/zhang/include/openMVS/libs/MVS/DepthMap.cpp: In member function ‘void MVS::DepthEstimator::ProcessPixel(SEACAVE::IDX)’:
/home/zhang/include/openMVS/libs/MVS/DepthMap.cpp:733:67: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  733 |  const Normal viewDir(Cast<float>(reinterpret_cast<const Point3&>(X0)));
      |                                                                   ^~
/home/zhang/include/openMVS/libs/MVS/DepthMap.cpp: In function ‘std::pair<float, float> TriangulatePointsDelaunay(const MVS::DepthData::ViewData&, const MVS::PointCloud&, const IndexArr&, MVS::Mesh&, SEACAVE::Point2fArr&, bool)’:
/home/zhang/include/openMVS/libs/MVS/DepthMap.cpp:989:38: warning: typedef ‘VertexCirculator’ locally defined but not used [-Wunused-local-typedefs]
  989 |  typedef Delaunay::Vertex_circulator VertexCirculator;
      |                                      ^~~~~~~~~~~~~~~~
/home/zhang/include/openMVS/libs/MVS/DepthMap.cpp: In function ‘void MVS::EstimatePointNormals(const ImageArr&, MVS::PointCloud&, int)’:
/home/zhang/include/openMVS/libs/MVS/DepthMap.cpp:1365:30: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 1365 |   (Point3d&)(pointvectors[i].first) = pointcloud.points[i];
      |             ~~~~~~~~~~~~~~~~~^~~~~~
/home/zhang/include/openMVS/libs/MVS/DepthMap.cpp:1393:45: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 1393 |   normal = (const Point3d&)(pointvectors[i].second);
      |                            ~~~~~~~~~~~~~~~~~^~~~~~~
/home/zhang/include/openMVS/libs/MVS/DepthMap.cpp:1393:51: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 1393 |   normal = (const Point3d&)(pointvectors[i].second);
      |                                                   ^
[ 51%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/Image.cpp.o
[ 52%] Building CXX object libs/MVS/CMakeFiles/MVS.dir/Mesh.cpp.o
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:980:9: error: ‘BasicVertexPair’ does not name a type
  980 | typedef BasicVertexPair<Vertex> VertexPair;
      |         ^~~~~~~~~~~~~~~
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:982:71: error: ‘VertexPair’ was not declared in this scope; did you mean ‘Vertex’?
  982 | EdgeCollapse : public vcg::tri::TriEdgeCollapseQuadric<Mesh, VertexPair, TriEdgeCollapse, QHelper> {
      |                                                              ^~~~~~~~~~
      |                                                              Vertex
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:982:107: error: template argument 2 is invalid
  982 | dgeCollapseQuadric<Mesh, VertexPair, TriEdgeCollapse, QHelper> {
      |                                                              ^

/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:984:49: error: ‘VertexPair’ was not declared in this scope; did you mean ‘Vertex’?
  984 |  typedef vcg::tri::TriEdgeCollapseQuadric<Mesh, VertexPair, TriEdgeCollapse, QHelper> TECQ;
      |                                                 ^~~~~~~~~~
      |                                                 Vertex
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:984:85: error: template argument 2 is invalid
  984 | dgeCollapseQuadric<Mesh, VertexPair, TriEdgeCollapse, QHelper> TECQ;
      |                                                              ^

/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:985:31: error: ‘VertexPair’ does not name a type; did you mean ‘Vertex’?
  985 |  inline TriEdgeCollapse(const VertexPair &p, int i, vcg::BaseParameterClass *pp) :TECQ(p, i, pp) {}
      |                               ^~~~~~~~~~
      |                               Vertex
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp: In constructor ‘CLEAN::TriEdgeCollapse::TriEdgeCollapse(const int&, int, vcg::BaseParameterClass*)’:
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:985:83: error: ‘typedef int CLEAN::TriEdgeCollapse::TECQ’ is not a non-static data member of ‘CLEAN::TriEdgeCollapse’
  985 | pse(const VertexPair &p, int i, vcg::BaseParameterClass *pp) :TECQ(p, i, pp) {}
      |                                                               ^~~~

/home/zhang/include/openMVS/libs/MVS/Mesh.cpp: In member function ‘void MVS::Mesh::Clean(float, float, bool, unsigned int, unsigned int, bool)’:
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:1042:6: error: ‘class vcg::tri::TriEdgeCollapseQuadricParameter’ has no member named ‘BoundaryWeight’
 1042 |   pp.BoundaryWeight = 1; // the importance of the boundary during simplification: the value is in the range (0..+inf), default (1.0) means that the boundary has the same importance as the rest; values greater than 1.0 raise boundary importance and has the effect of removing less vertices on the border
      |      ^~~~~~~~~~~~~~
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp: In member function ‘bool MVS::Mesh::LoadPLY(const SEACAVE::String&)’:
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:1372:48: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class SEACAVE::TPoint3<unsigned int>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
 1372 |      memcpy(pFace, face.pFace, sizeof(VIndex)*3);
      |                                                ^
In file included from /home/zhang/include/openMVS/libs/Common/Common.h:176,
                 from /home/zhang/include/openMVS/libs/MVS/Common.h:42,
                 from /home/zhang/include/openMVS_build/libs/MVS/CMakeFiles/MVS.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/zhang/include/openMVS/libs/Common/Types.h:1338:7: note: ‘class SEACAVE::TPoint3<unsigned int>’ declared here
 1338 | class TPoint3 : public cv::Point3_<TYPE>
      |       ^~~~~~~
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:1387:63: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class SEACAVE::TPoint3<unsigned int>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
 1387 |      memcpy(faces.Begin()+f, face.face.pFace, sizeof(VIndex)*3);
      |                                                               ^
In file included from /home/zhang/include/openMVS/libs/Common/Common.h:176,
                 from /home/zhang/include/openMVS/libs/MVS/Common.h:42,
                 from /home/zhang/include/openMVS_build/libs/MVS/CMakeFiles/MVS.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/zhang/include/openMVS/libs/Common/Types.h:1338:7: note: ‘class SEACAVE::TPoint3<unsigned int>’ declared here
 1338 | class TPoint3 : public cv::Point3_<TYPE>
      |       ^~~~~~~
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:1393:73: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class SEACAVE::TPoint2<float>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
 1393 |      memcpy(faceTexcoords.Begin()+f*3, face.tex.pTex, sizeof(TexCoord)*3);
      |                                                                         ^
In file included from /home/zhang/include/openMVS/libs/Common/Common.h:176,
                 from /home/zhang/include/openMVS/libs/MVS/Common.h:42,
                 from /home/zhang/include/openMVS_build/libs/MVS/CMakeFiles/MVS.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/zhang/include/openMVS/libs/Common/Types.h:1245:7: note: ‘class SEACAVE::TPoint2<float>’ declared here
 1245 | class TPoint2 : public cv::Point_<TYPE>
      |       ^~~~~~~
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp: In member function ‘bool MVS::Mesh::ProjectOrtho(const MVS::Camera&, MVS::DepthMap&) const::RasterMesh::ProjectVertex(const Vertex&, int)’:
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:3901:113: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 3901 | amera.TransformPointC2I(reinterpret_cast<const Point2&>(ptc[v])));
      |                                                         ~~~~~^

/home/zhang/include/openMVS/libs/MVS/Mesh.cpp: In member function ‘bool MVS::Mesh::ProjectOrtho(const MVS::Camera&, MVS::DepthMap&, SEACAVE::Image8U3&) const::RasterMesh::ProjectVertex(const Vertex&, int)’:
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:3933:113: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 3933 | amera.TransformPointC2I(reinterpret_cast<const Point2&>(ptc[v])));
      |                                                         ~~~~~^

In file included from /home/zhang/include/openMVS/libs/MVS/Mesh.cpp:62:
/home/zhang/include/VCG-master/vcg/complex/algorithms/local_optimization.h: In instantiation of ‘void vcg::LocalOptimization<MeshType>::Init() [with LocalModificationType = CLEAN::TriEdgeCollapse; MeshType = CLEAN::Mesh]’:
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:1065:44:   required from here
/home/zhang/include/VCG-master/vcg/complex/algorithms/local_optimization.h:269:63: error: ‘HeapSimplexRatio’ is not a member of ‘CLEAN::TriEdgeCollapse’
  269 |     HeapSimplexRatio = LocalModificationType::HeapSimplexRatio(pp);
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/home/zhang/include/VCG-master/vcg/complex/algorithms/local_optimization.h:271:32: error: ‘Init’ is not a member of ‘CLEAN::TriEdgeCollapse’
  271 |     LocalModificationType::Init(m,h,pp);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/home/zhang/include/VCG-master/vcg/complex/algorithms/local_optimization.h: In instantiation of ‘void vcg::LocalOptimization<MeshType>::Finalize() [with LocalModificationType = CLEAN::TriEdgeCollapse; MeshType = CLEAN::Mesh]’:
/home/zhang/include/openMVS/libs/MVS/Mesh.cpp:1070:48:   required from here
/home/zhang/include/VCG-master/vcg/complex/algorithms/local_optimization.h:279:36: error: ‘Finalize’ is not a member of ‘CLEAN::TriEdgeCollapse’
  279 |     LocalModificationType::Finalize(m,h,pp);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
make[2]: *** [libs/MVS/CMakeFiles/MVS.dir/build.make:139：libs/MVS/CMakeFiles/MVS.dir/Mesh.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:472：libs/MVS/CMakeFiles/MVS.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2

**Comment by cdcseacave** [comment]
are you using the latest develop branch in OpenMVS?

**Comment by HuberyQ** [comment]
> 

I downloaded the latest version v2.0, but I encountered the same problem.

**Comment by HuberyQ** [comment]
> are you using the latest develop branch in OpenMVS?

Oh, sorry, I used 'master' before. Now I download 'develop' and try it. It succeed. Are there any differences between them？
