### ISSUE TITLE
SIGABRT (std::bad_alloc) for DensifyPointCloud

### ISSUE THREAD

**Issue by mad-de** [cdcseacave/openMVS#78]
### Specifications like the version of the project, operating system, and hardware
Ubuntu 15.10 64-bit
Memory 3,8 GiB
Processor Intel® Core™ i3-4160 CPU @ 3.60GHz × 4 
Graphics Intel® Haswell 
### Steps to reproduce the problem
Reconstruction Incremental folder:
https://mega.nz/#F!3IkmRSSS!8pSAsXnIyotTXf2Prg46Ug

gdb:

> gdb --args /home/martin-uwh/openMVS_build/bin/DensifyPointCloud -i /home/martin-uwh/meshes/os_coxae_2_out/MVS_out/scene.mvs -o /home/martin-uwh/meshes/os_coxae_2_out/MVS_out/scene_dense.mvs -w /home/martin-uwh/meshes/os_coxae_2_out/MVS_out/

gdb output:

> GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/martin-uwh/openMVS_build/bin/DensifyPointCloud...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/martin-uwh/openMVS_build/bin/DensifyPointCloud -i /home/martin-uwh/meshes/os_coxae_2_out/MVS_out/scene.mvs -o /home/martin-uwh/meshes/os_coxae_2_out/MVS_out/scene_dense.mvs -w /home/martin-uwh/meshes/os_coxae_2_out/MVS_out/
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffde97b700 (LWP 10553)]
12:53:56 [App     ] Build date: Apr  8 2016, 20:41:37
12:53:56 [App     ] CPU: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
12:53:56 [App     ] RAM: 3.77GB Physical Memory 3.91GB Virtual Memory
12:53:56 [App     ] OS: Linux 4.2.0-16-generic (x86_64)
12:53:56 [App     ] SSE & AVX compatible CPU & OS detected
12:53:56 [App     ] Command line: -i /home/martin-uwh/meshes/os_coxae_2_out/MVS_out/scene.mvs -o /home/martin-uwh/meshes/os_coxae_2_out/MVS_out/scene_dense.mvs -w /home/martin-uwh/meshes/os_coxae_2_out/MVS_out/
12:53:57 [App     ] Scene loaded (122ms):
	60 images (60 calibrated) with a total of 1025.16 MPixels (17.09 MPixels/image)
	132235 points, 0 vertices, 0 faces
[New Thread 0x7fffdddf1700 (LWP 10554)]
[New Thread 0x7fffdd5f0700 (LWP 10555)]
[New Thread 0x7fffdcdef700 (LWP 10556)]
[New Thread 0x7fffd4cbc700 (LWP 10557)]
[New Thread 0x7fffd48bb700 (LWP 10558)]
[New Thread 0x7fffd44ba700 (LWP 10559)]
12:54:00 [App     ] Preparing images for dense reconstruction completed: 60 images (3s188ms)
Completing graph construction... done
TRW_S algorithm
iter 10: lower bound = 238.644675, energy = 238.971917
iter 15: lower bound = 238.680097, energy = 238.971917
iter 20: lower bound = 238.713661, energy = 238.971917
iter 25: lower bound = 238.744976, energy = 238.971917
iter 30: lower bound = 238.773604, energy = 238.971917
iter 32: lower bound = 238.780431, energy = 238.971917
12:54:00 [App     ] Selecting images for dense reconstruction completed: 60 images (217ms)
[New Thread 0x7fffd598c700 (LWP 10560)]
[New Thread 0x7fffce65d700 (LWP 10561)]
Estimated depth-maps 59 (98.33%, 1m39s, ETA 1s)...[Thread 0x7fffd598c700 (LWP 10560) exited]
Estimated depth-maps 60 (100%, 1m39s932ms)          
[Thread 0x7fffce65d700 (LWP 10561) exited]
[New Thread 0x7fffce65d700 (LWP 10567)]
[New Thread 0x7fffd598c700 (LWP 10568)]
[New Thread 0x7fffcde5c700 (LWP 10569)]
[New Thread 0x7fffcd65b700 (LWP 10570)]
Filtered depth-maps 60 (100%, 3m41s408ms)         
[Thread 0x7fffcd65b700 (LWP 10570) exited]
[Thread 0x7fffcde5c700 (LWP 10569) exited]
[Thread 0x7fffd598c700 (LWP 10568) exited]
[Thread 0x7fffce65d700 (LWP 10567) exited]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

> Program received signal SIGABRT, Aborted.
0x00007ffff4fe7267 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt full
#0  0x00007ffff4fe7267 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 10549
        selftid = 10549
#1  0x00007ffff4fe8eca in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7ffff59d1422, 
            sa_sigaction = 0x7ffff59d1422}, sa_mask = {__val = {
              140737307441184, 140735072438608, 140737351974688, 
              140737307440704, 140737307440704, 1, 140737307440835, 14562016, 
              140737303990505, 10, 140737307440835, 140737353550376, 
              140737307440835, 1, 140737353552848, 140735072438480}}, 
          sa_flags = -180909728, sa_restorer = 0x7ffff7f70ac0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff592ab7d in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff59289c6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff5928a11 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#5  0x00007ffff5928c29 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff59291cc in operator new(unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#7  0x00007ffff5929229 in operator new[](unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#8  0x000000000064de55 in DepthMapsData::FuseDepthMaps(MVS::PointCloud&, bool)
    ()
No symbol table info available.
#9  0x000000000065a317 in MVS::Scene::DenseReconstruction() ()
No symbol table info available.
#10 0x00000000005820db in main ()
No symbol table info available.
(gdb) q

**Comment by cdcseacave** [comment]
the sfm-data.json is useless alone, without the images I can not debug

but I see in the gdb you posted that the reconstruction starts with the last depth map... why is that? I suggest to delete all the dmap files and start it from the begining

I also noticed you are not using the latest versions, neither of OpenMVS nor of OpenMVG. It would be a good idea to use the last version.

And just a note: the whole idea of the working directory command line "-w" is not to add the full path to all the files!!!!!!!!!!!

**Comment by mad-de** [comment]
The problem seems to have come from an exhaustive memory consumption from too many / too large images. Using "-- resolution-level" and setting it to a value above 2 fixed this issue.
