### ISSUE TITLE
Program was killed.

### ISSUE THREAD

**Issue by wujilingfeng** [cdcseacave/openMVS#781]
**Describe the bug**
I run the command `ReconstructMesh scene_dense.mvs`,then the last output text was "Killed" and there was no mesh file to generate.

**Screenshots**
![Screenshot from 2022-03-15 16-26-30](https://user-images.githubusercontent.com/35684738/158336536-fae3ba4e-835c-460b-8f34-bd49067e3e35.png)

**Desktop (please complete the following information):**
 - OS: ubuntu20.04

**Comment by cdcseacave** [comment]
most probably OOM, install more RAM

**Comment by zhangwei19980131** [comment]
Lower the image resolution or add a memory stick

**Comment by wujilingfeng** [comment]
Thank you !

**Comment by PaulLiuYZ** [comment]
how do you solve the problem in the end?

**Comment by PaulLiuYZ** [comment]
@wujilingfeng how do you solve the problem in the end? i met the problem as well, do you have any idea? thank you !

**Comment by PaulLiuYZ** [comment]
@zhangwei19980131 i tried the command "./ReconstructMesh --resolution-level xxx xxx.mvs", but it seems that this command does not exsit, and adding memory may be hard, what can i do ?

**Comment by cdcseacave** [comment]
you can use `-d ` param in ReconstructMesh  to lower the mesh resolution

**Comment by Anonyme415** [comment]
> 

Hello,What are the mesh resolution parameters? The default value is?

**Comment by cdcseacave** [comment]
simply run it with no params and all default and options are displayed
