### ISSUE TITLE
how to parse  content of scene_dense.mvs.

### ISSUE THREAD

**Issue by wujilingfeng** [cdcseacave/openMVS#782]
**Is your feature request related to a problem? Please describe.**
I want to create the mesh with my own program,so how to parse the content of scene_dense.mvs?
For example ,I want to get the point data and texture data.
Do you have any file format description？

Thank you very much!

**Comment by cdcseacave** [comment]
there is no file format for scene_dense.mvs, I use boost serialization to save to disk the memory objects as they are

**Comment by wujilingfeng** [comment]
> there is no file format for scene_dense.mvs, I use boost serialization to save to disk the memory objects as they are


Is there any way to complete my task？

**Comment by cdcseacave** [comment]
sure there is, just link to the OpenMVS library and read the file with it

**Comment by wujilingfeng** [comment]
> sure there is, just link to the OpenMVS library and read the file with it
Thanks! Keep in touch!
