### ISSUE TITLE
A method to get sub-textured-mesh for very large scene

### ISSUE THREAD

**Issue by CanCanZeng** [cdcseacave/openMVS#783]
Hi, I find a way to get sub-textured-meshs without overlap, but I do not know is it suggested?
My method is:
1. reconstruct scene with mesh as normal.
2. split the mesh via below command:
     `ReconstructMesh -i scene_mesh.mvs --split-max-area 50000`
3. texture mesh one by one
     `TextureMesh -i scene_mesh.mvs --mesh-file scene_mesh_chunk00.ply  -o scene_mesh_chunk00.mvs`

via this way, I can get sub-textured-mesh without any overlap. Is there any potential problems?

I need sub-mesh to do texture because I find that for very large scene, the time consumption of texturing becomes unacceptable, so does the memory consumption. But if I follw the guide of this example https://github.com/cdcseacave/openMVS/issues/438#issuecomment-800972596, there will be much overlap between sub-scenes, and there may be some conflicts in these overlap regions. So I find this way to figure out my problem.

**Comment by cdcseacave** [comment]
Your approach is very good, it is not official yet because it is missing a step that makes sure the sub-meshes have exactly the same border; in other words we need to zip the adjacent meshes such that the vertices at the border have exactly the same coordinates, so when you render them there will be no gap between them. If you have time to add this step feel free to help.

**Comment by CanCanZeng** [comment]
Do you mean the splited sub-meshes by `ReconstructMesh -i scene_mesh.mvs --split-max-area 50000` may have gaps? I do not understand, is this comes from spliting stage or saving stage? I see you called RemoveUnreferencedVertices and FixNonManifold functions in saving stage.

Besides,  there may be clean stage or decimate stage, which can also create gaps. I think this is hard to be handled indivadually.

**Comment by cdcseacave** [comment]
in fact you are right, the splitting stage itself in ReconstructMesh should not add gaps, that should happen only if you post process the mesh between ReconstructMesh and TextureMesh (like decimate it, etc)

**Comment by CanCanZeng** [comment]
OK, I get it. If we want to make sure there are no gaps even after post process, we need to revise the mesh process function to preserve the border, but this beyond my knowledge now, so I have no choice but  do post process on the mesh before split.

**Comment by PaulLiuYZ** [comment]
so how can you join all the sub-meshes together?

**Comment by CanCanZeng** [comment]
@PaulLiuYZ  I do not join them together.

**Comment by PaulLiuYZ** [comment]
@CanCanZeng so, do you mean that you do something to different parts separately?  in that way, how can you get the complete scene？

**Comment by CanCanZeng** [comment]
I load all of the sub-meshes in meshlab and just display it. I think you may use CloudCompare to merge all the sub-meshes, see here https://www.cloudcompare.org/doc/wiki/index.php?title=Merge . I did not try it, but maybe you can have a try.

**Comment by PaulLiuYZ** [comment]
Thank you so much!

**Comment by wutingfan** [comment]
I don't have enough memory for reconstruct scene with mesh for the whole large scene, Is there any solution to solve it ?

**Comment by cdcseacave** [comment]
you can try https://github.com/cdcseacave/openMVS/issues/438#issuecomment-800972596

**Comment by wutingfan** [comment]
> you can try [#438 (comment)](https://github.com/cdcseacave/openMVS/issues/438#issuecomment-800972596)

The ultimate goal is generate texture model of large secne.  All  pipelines split the model, but it seems that all of them don't merge the texture model(ply/obj/gltf with png). Is there any way to merge  sub-texture-models to get the texture model of  the whole large scene? And Is there any way to merge two or more mvs file?
Before openMVS2,  I use colmap split sparse model and generate dense point cloud  one by one, then meger the point cloud(ply file). I'll try get dense large point cloud by openMVS2 mention in #438. But, in any way,  I will get two or more texture model(ply/obj/gltf with png).

**Comment by wutingfan** [comment]
> you can try [#438 (comment)](https://github.com/cdcseacave/openMVS/issues/438#issuecomment-800972596)

Also, I have problems when I try #438. cmd line:
18:15:53 [App     ] error: opening file 'depth0074.dmap' for reading depth-data
18:15:53 [App     ] error: opening file 'depth0119.dmap' for reading depth-data
18:15:53 [App     ] error: opening file 'depth0120.dmap' for reading depth-data
18:15:53 [App     ] error: opening file 'depth0122.dmap' for reading depth-data
18:15:53 [App     ] Point-cloud saved: 8 points (0ms)
18:15:54 [App     ] Scene split (600000 max-area): 24 chunks (970ms)
18:15:54 [App     ] Scene saved (4ms):
        5 images (5 calibrated)
        2384 points, 0 vertices, 0 faces
18:15:54 [App     ] Scene saved (39ms):
        45 images (45 calibrated)
        17614 points, 0 vertices, 0 faces
munmap_chunk(): invalid pointer

depth0074.dmap...  don't exist because them cannot find enough views for depth estimate. And when finish depth estimate, the depth map filter still need  a lot of memory that's nothing different with "--fusiono-mode 0".

**Comment by cdcseacave** [comment]
you must have use the option wrong: first you need to compute the depth maps without fusion, next split the scene in smaller sub-scenes, and next do the fusion on each small scene (which need less memory)

**Comment by wutingfan** [comment]
> you must have use the option wrong: first you need to compute the depth maps without fusion, next split the scene in smaller sub-scenes, and next do the fusion on each small scene (which need less memory)

I did some tests, In file scene.cpp, funciton "unsigned Scene::Split(ImagesChunkArr& chunks, float maxArea, int depthMapStep) const",  after octree.SplitVolume(maxArea, areaEstimator, chunkInserter); the chunks.size() is always 1.

**Comment by wutingfan** [comment]
> you must have use the option wrong: first you need to compute the depth maps without fusion, next split the scene in smaller sub-scenes, and next do the fusion on each small scene (which need less memory)

I test the code line by line, the error may be happend because of "subset.platforms.emplace_back(std::move(subPlatform));".  The error happeend when try to release the platforms of the subset. So only the first chunk will be saved as mvs file successfully.

**Comment by yinbc** [comment]
> > you must have use the option wrong: first you need to compute the depth maps without fusion, next split the scene in smaller sub-scenes, and next do the fusion on each small scene (which need less memory)
> 
> I test the code line by line, the error may be happend because of "subset.platforms.emplace_back(std::move(subPlatform));". The error happeend when try to release the platforms of the subset. So only the first chunk will be saved as mvs file successfully.

HI! I also meet the same question.did you solve it?? Thanks!
