### ISSUE TITLE
Memory Leak Issue: Unable to Generate DepthMaps for Resolution Level 0 with GPU Docker

### ISSUE THREAD

**Issue by vivekmistry** [cdcseacave/openMVS#785]
**Describe the bug**
A clear and concise description of what the bug is. Use `Viewer` to verify/display the input/output.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by 3XH6R** [comment]
You can't comment at this time.

**Comment by 3XH6R** [comment]
Please add a detailed description.
How big are the images? How much memory did you allocate?

Possibly a duplicate of https://github.com/cdcseacave/openMVS/issues/743.

**Comment by vivekmistry** [comment]
Had issue in creating bug in github, creating new one

**Comment by vivekmistry** [comment]
.
