### ISSUE TITLE
[Question] Automatically Cropping/Removing Outliers from Sparse/Dense Point Cloud

### ISSUE THREAD

**Issue by braden-dev** [cdcseacave/openMVS#787]
I'm not sure if this is the right place to ask this question but I haven't found help elsewhere. Currently, I am using an MVG to MVS pipeline to create a 3D model from a set of 2D images. The images are taken around an object sitting on a table. Ideally, the end 3D model would consist of just the object sitting on the table, but that's unrealistic. I'm really just trying to remove as much background noise as possible. I'm sure there are some parameters in either the OpenMVG or OpenMVS functions that I'm missing that might help with this to an extent.

Here's an example of a scene that I got from the MVG/MVS pipeline where the piece in the back is far lower than the object I want outlined in blue:
![image](https://user-images.githubusercontent.com/69637496/158923923-2aa7762f-c749-4d52-9773-9fb28697286e.png)

Here is an example of the kind of result I'm looking for, where there is a lot less in the background: 
![image](https://user-images.githubusercontent.com/69637496/158924086-e401f5b7-43c8-467d-8c47-79cce4bf7cd7.png)

The thing is that I want to automate this either in the MVG/MVS pipeline or once the pipeline finishes. I apologize if this isn't really an issue that relates to this but I'm at a loss for where else to ask for help.

Let me know if there's any other information that I can provide that would give a better understanding of my problem.

**Comment by cdcseacave** [comment]
there are several ways to handle this:
- you can supply a mask for each image (should have the same name with the image, but with `.mask` added)
- you can supply a region of interest (oriented bounding box) using `--import-roi-file`
- OpenMVS can be augmented with a function to try to automatically estimate the ROI (didn't have time yet to do it though)

**Comment by braden-dev** [comment]
> there are several ways to handle this:
> 
> * you can supply a mask for each image (should have the same name with the image, but with `.mask` added)
> * you can supply a region of interest (oriented bounding box) using `--import-roi-file`
> * OpenMVS can be augmented with a function to try to automatically estimate the ROI (didn't have time yet to do it though)

Got it, but like you said there isn't a way to automatically try to estimate the ROI or something like that? That's the kind of thing that I would be needing for my application. I'm going to be taking several pictures around an object and I only want that object in the final reconstruction but I don't want there to be any manual pieces in between taking the pictures and creating the final mesh/point cloud.

I found a bit of hacked solution that works for my purposes but it definitely would be improved with an automatic ROI process or something similar.

**Comment by 3XH6R** [comment]
>there are several ways to handle this:
>
>* you can supply a mask for each image (should have the same name with the image, but with .mask added)
>* you can supply a region of interest (oriented bounding box) using --import-roi-file
>* OpenMVS can be augmented with a function to try to automatically estimate the ROI (didn't have time yet to do it though)

Would it be possible to move those methods before depth mapping?

**Comment by cdcseacave** [comment]
I can help you and implement the automatic ROI estimation, however pls consider donating in order to be able to make time

**Comment by txyxy** [comment]
@braden-dev Hi, could you give me some suggestions and ideas on how you estimated the ROI of the second picture you posted above?

**Comment by braden-dev** [comment]
> @braden-dev Hi, could you give me some suggestions and ideas on how you estimated the ROI of the second picture you posted above?

Hey txyxy, I can tell you what I did although it definitely isn't the best method by any means. Since the ROI in almost all of my 3D reconstructed models had the most amount of points, I created a density map of all the points in the model and just cropped out the furthest points away from that densest point. Like I said, this isn't perfect and it isn't smart by any means but it served the purpose I needed it to. Let me know if you have any other questions!

**Comment by txyxy** [comment]
> > @braden-dev Hi, could you give me some suggestions and ideas on how you estimated the ROI of the second picture you posted above?
> 
> Hey txyxy, I can tell you what I did although it definitely isn't the best method by any means. Since the ROI in almost all of my 3D reconstructed models had the most amount of points, I created a density map of all the points in the model and just cropped out the furthest points away from that densest point. Like I said, this isn't perfect and it isn't smart by any means but it served the purpose I needed it to. Let me know if you have any other questions!

Did you mean that you specify the coordinates of the point for cropping?  And you use the remaining points to reconstruct, is it?

**Comment by txyxy** [comment]
I mean that, if you estimated the range of coordinates in the ROI and removing the points outside those coordinates?

**Comment by braden-dev** [comment]
> > > @braden-dev Hi, could you give me some suggestions and ideas on how you estimated the ROI of the second picture you posted above?
> > 
> > 
> > Hey txyxy, I can tell you what I did although it definitely isn't the best method by any means. Since the ROI in almost all of my 3D reconstructed models had the most amount of points, I created a density map of all the points in the model and just cropped out the furthest points away from that densest point. Like I said, this isn't perfect and it isn't smart by any means but it served the purpose I needed it to. Let me know if you have any other questions!
> 
> Did you mean that you specify the coordinates of the point for cropping? And you use the remaining points to reconstruct, is it?

I figured out the coordinate of the densest point and then went into, I believe, the .ply file that is generated and manually removed the points that were far enough away from the densest point based on some condition. What I did was I removed half of the points each iteration and ran like 2 to 5 iterations depending on the 3D model I gave it.

**Comment by braden-dev** [comment]
No, I didn't estimate a range which is why this method isn't great because you can easily crop out part of your ROI.

**Comment by txyxy** [comment]
Got it. Thanks a lot for your reply!

**Comment by braden-dev** [comment]
> Got it. Thanks a lot for your reply!

Of course! Hope it helped!
