### ISSUE TITLE
Unable to Create DepthMaps for Resolution Level0 with GPU Docker.

### ISSUE THREAD

**Issue by vivekmistry** [cdcseacave/openMVS#788]
With latest OpenMVS Dev Branch, had successfully generated DepthMaps for Resolution Level1 with CPU & GPU Docker.
Now, for Reoslution Level0 the DepthMaps are generated with CPU Docker but fails with GPU Docker with following error:

Error Message:
terminate called after throwing an instance of ‘std::bad_alloc’
what(): std::bad_alloc

Below are our InfraStructure details:

Cloud: AWS
EC2 Instance Type: g4dn.12xlarge(48vCPus and 192GB RAM)
OS: Linux
OpenMVS Docker: Yes
GPU Type:  NVIDIA T4 GPUs (16GB GPU RAM)

**Comment by cdcseacave** [comment]
Reoslution Level0 can be anything, it just means the original image is not downscaled
so what is the original image resolution?

**Comment by vivekmistry** [comment]
The Original Image Resolution is 19470*9062.

**Comment by cdcseacave** [comment]
that explains it, the GPU run OOM
in order to process such high resolution a divide and conquer approach needs to be implemented; I can help you with that, but in order to be able to make some time for it pls consider a donantion

**Comment by cdcseacave** [comment]
yes
