### ISSUE TITLE
confilict with vcglib

### ISSUE THREAD

**Issue by SabraHashemi** [cdcseacave/openMVS#789]
/home/komatsu2ubuntu/openMVS/libs/MVS/Mesh.cpp:1065:44:   required from here
/home/komatsu2ubuntu/vcglib/vcg/complex/algorithms/local_optimization.h:269:63: error: ‘HeapSimplexRatio’ is not a member of ‘CLEAN::TriEdgeCollapse’
  269 |     HeapSimplexRatio = LocalModificationType::HeapSimplexRatio(pp);
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/home/komatsu2ubuntu/vcglib/vcg/complex/algorithms/local_optimization.h:271:32: error: ‘Init’ is not a member of ‘CLEAN::TriEdgeCollapse’
  271 |     LocalModificationType::Init(m,h,pp);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/home/komatsu2ubuntu/vcglib/vcg/complex/algorithms/local_optimization.h: In instantiation of ‘void vcg::LocalOptimization<MeshType>::Finalize() [with LocalModificationType = CLEAN::TriEdgeCollapse; MeshType = CLEAN::Mesh]’:
/home/komatsu2ubuntu/openMVS/libs/MVS/Mesh.cpp:1070:48:   required from here
/home/komatsu2ubuntu/vcglib/vcg/complex/algorithms/local_optimization.h:279:36: error: ‘Finalize’ is not a member of ‘CLEAN::TriEdgeCollapse’
  279 |     LocalModificationType::Finalize(m,h,pp);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
make[2]: *** [libs/MVS/CMakeFiles/MVS.dir/build.make:157: libs/MVS/CMakeFiles/MVS.dir/Mesh.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:433: libs/MVS/CMakeFiles/MVS.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by cdcseacave** [comment]
pls use develop branch for OpenMVS with master branch of VCG

**Comment by weihohoho** [comment]
@SabraHashemi Hi did you managed to work around the problem? I repalced the git clone links with develop branch/master branch and the problem seems to presist?

**Comment by weihohoho** [comment]
@cdcseacave sorry to bother, just want to check if I am doing it right

I deleted and replaced the VCG library by doing  
git clone https://github.com/cnr-isti-vclab/vcglib.git vcglib

and ran 
git clone https://github.com/cdcseacave/openMVS.git openMVS
mkdir openMVS_build && cd openMVS_build
cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_ROOT="$main_path/vcglib"

make -j2 && sudo make install

Seems I am still running into the same problem. Thank you！

**Comment by cliffcheng** [comment]
I have the same problem. How can I solve it? Thank you!
