### ISSUE TITLE
TextureMesh: "error: empty initial mesh" when running tutorial files w/o prior running DensifyPointCloud scene.mvs

### ISSUE THREAD

**Issue by mad-de** [cdcseacave/openMVS#79]
### Specifications like the version of the project, operating system, and hardware
latest openMVG from develop branch
latest openMVS

Ubuntu 15.10 64-bit
Memory 3,8 GiB
Processor Intel® Core™ i3-4160 CPU @ 3.60GHz × 4
Graphics Intel® Haswell 
### Steps to reproduce the problem

Run Tutorial FIles (Describer Preset: Normal, Global SfM. Running w/o prior running DensifyPointCloud results in "error: empty initial mesh". If running DensifyPointCLoud prior, it works alright. Same applies if trying to run Refine Mesh. Don't know if Wiki is outdated and this is intended behaviour, so I'm reporting anyway.

Files: https://mega.nz/#F!6IUiSSwT!xb4Ie7GCjPGWqidb1lem8A

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Scene saved to OpenMVS interface format:
	11 images (11 calibrated)
	2926 Landmarks
14:38:46 [App     ] Build date: Apr 14 2016, 09:38:27
14:38:47 [App     ] CPU: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
14:38:47 [App     ] RAM: 3.77GB Physical Memory 3.91GB Virtual Memory
14:38:47 [App     ] OS: Linux 4.2.0-16-generic (x86_64)
14:38:47 [App     ] SSE & AVX compatible CPU & OS detected
14:38:47 [App     ] Command line: /home/martin-uwh/openMVG_build/software/SfM/ImageDataset_SceauxCastle/images_out/MVS_out/scene.mvs
14:38:47 [App     ] Camera model loaded: platform 0; camera  0; f 1.054x1.054; poses 11
14:38:47 [App     ] Image loaded   0: 100_7100.JPG
14:38:47 [App     ] Image loaded   1: 100_7101.JPG
14:38:47 [App     ] Image loaded   2: 100_7102.JPG
14:38:47 [App     ] Image loaded   3: 100_7103.JPG
14:38:47 [App     ] Image loaded   4: 100_7104.JPG
14:38:47 [App     ] Image loaded   5: 100_7105.JPG
14:38:47 [App     ] Image loaded   6: 100_7106.JPG
14:38:47 [App     ] Image loaded   7: 100_7107.JPG
14:38:47 [App     ] Image loaded   8: 100_7108.JPG
14:38:47 [App     ] Image loaded   9: 100_7109.JPG
14:38:47 [App     ] Image loaded  10: 100_7110.JPG
14:38:47 [App     ] Scene loaded from interface format (402ms):
	11 images (11 calibrated) with a total of 63.22 MPixels (5.75 MPixels/image)
	2926 points, 0 vertices, 0 faces
14:38:47 [App     ] Delaunay tetrahedralization completed: 2926 points -> 2728 vertices, 16668 (+114) cells, 33393 (+171) faces (63ms)
14:38:47 [App     ] Delaunay tetrahedras weighting completed: 16782 cells, 33564 faces (113ms)
14:38:47 [App     ] Delaunay tetrahedras graph-cut completed (1722.6 flow): 798 vertices, 1570 faces (26ms)
14:38:47 [App     ] Mesh reconstruction completed: 801 vertices, 1570 faces (301ms)
14:38:47 [App     ] Cleaned mesh: 0 vertices, 0 faces (3ms)
14:38:48 [App     ] Scene saved (2ms):
	11 images (11 calibrated)
	0 points, 0 vertices, 0 faces
14:38:48 [App     ] MEMORYINFO: {
14:38:48 [App     ] 	VmPeak:	  889304 kB
14:38:48 [App     ] 	VmSize:	  691612 kB
14:38:48 [App     ] } ENDINFO

14:38:48 [App     ] Build date: Apr 14 2016, 09:38:27
14:38:48 [App     ] CPU: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
14:38:48 [App     ] RAM: 3.77GB Physical Memory 3.91GB Virtual Memory
14:38:48 [App     ] OS: Linux 4.2.0-16-generic (x86_64)
14:38:48 [App     ] SSE & AVX compatible CPU & OS detected
14:38:48 [App     ] Command line: /home/martin-uwh/openMVG_build/software/SfM/ImageDataset_SceauxCastle/images_out/MVS_out/scene_mesh.mvs
14:38:48 [App     ] Scene loaded (0ms):
	11 images (11 calibrated) with a total of 63.22 MPixels (5.75 MPixels/image)
	0 points, 0 vertices, 0 faces
14:38:48 [App     ] error: empty initial mesh

**Comment by pmoulon** [comment]
Did you run ReconstructMesh scene_dense.mvs ?
The binary say you have an empty mesh...

**Comment by mad-de** [comment]
I ran "ReconstructMesh scene.mvs" as https://github.com/cdcseacave/openMVS/wiki/Usage states DensifyPointCloud as "optional"

**Comment by pmoulon** [comment]
Did you look at own many vertices ReconstructMesh generated?

**Comment by pmoulon** [comment]
Seems that the cleaning removed all the faces:
14:38:47 [App ] Mesh reconstruction completed: 801 vertices, 1570 faces (301ms)
**14:38:47 [App ] Cleaned mesh: 0 vertices, 0 faces (3ms)**

**Comment by mad-de** [comment]
Running with an old version (March 2016) of openMVS: 
(please just close if this is intended behaviour in new versions)

./ReconstructMesh -i /home/martin-uwh/openMVG_build_copy/software/SfM/ImageDataset_SceauxCastle/images_out/MVS_out/scene.mvs
15:32:09 [App     ] Build date: Apr  8 2016, 20:41:37
15:32:09 [App     ] CPU: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
15:32:09 [App     ] RAM: 3.77GB Physical Memory 3.91GB Virtual Memory
15:32:09 [App     ] OS: Linux 4.2.0-16-generic (x86_64)
15:32:09 [App     ] SSE & AVX compatible CPU & OS detected
15:32:09 [App     ] Command line: -i /home/martin-uwh/openMVG_build_copy/software/SfM/ImageDataset_SceauxCastle/images_out/MVS_out/scene.mvs
15:32:09 [App     ] Scene loaded (1ms):
	11 images (11 calibrated) with a total of 63.22 MPixels (5.75 MPixels/image)
	2911 points, 0 vertices, 0 faces
15:32:09 [App     ] Delaunay tetrahedralization completed: 2911 points -> 2720 vertices, 16599 (+96) cells, 33246 (+144) faces (24ms)
15:32:09 [App     ] Delaunay tetrahedras weighting completed: 16695 cells, 33390 faces (36ms)
15:32:10 [App     ] Delaunay tetrahedras graph-cut completed (9587.34 flow): 2690 vertices, 5364 faces (12ms)
**15:32:10 [App     ] Mesh reconstruction completed: 2692 vertices, 5360 faces (185ms)
15:32:10 [App     ] Cleaned mesh: 2691 vertices, 5372 faces (11ms)
15:32:10 [App     ] Cleaned mesh: 2691 vertices, 5378 faces (7ms)
15:32:10 [App     ] Cleaned mesh: 2691 vertices, 5378 faces (4ms)**
15:32:10 [App     ] Scene saved (8ms):
	11 images (11 calibrated)
	0 points, 2691 vertices, 5378 faces
15:32:10 [App     ] Mesh saved: 2691 vertices, 5378 faces (42ms)
15:32:10 [App     ] MEMORYINFO: {
15:32:10 [App     ] 	VmPeak:	  846172 kB
15:32:10 [App     ] 	VmSize:	  650364 kB
15:32:10 [App     ] } ENDINFO

**Comment by mad-de** [comment]
Current version:
14:38:47 [App ] Delaunay tetrahedralization completed: 2926 points -> 2728 vertices, 16668 (+114) cells, 33393 (+171) faces (63ms)
14:38:47 [App ] Delaunay tetrahedras weighting completed: 16782 cells, 33564 faces (113ms)
**14:38:47 [App ] Delaunay tetrahedras graph-cut completed (1722.6 flow): 798 vertices, 1570 faces (26ms)**

Old version:
15:32:09 [App ] Delaunay tetrahedralization completed: 2911 points -> 2720 vertices, 16599 (+96) cells, 33246 (+144) faces (24ms)
15:32:09 [App ] Delaunay tetrahedras weighting completed: 16695 cells, 33390 faces (36ms)
**15:32:10 [App ] Delaunay tetrahedras graph-cut completed (9587.34 flow): 2690 vertices, 5364 faces (12ms)**

**Comment by ORNis** [comment]
@cdcseacave disable the weak surface support by default in the last version

**Comment by mad-de** [comment]
@ORNis thanks for the info. I looked into https://github.com/cdcseacave/openMVS/commit/5ecf29e0f65b92f1bae06fde1efd6bfcdc662c11 and set free-space-support back to true as well as -f true when running ReconstructMesh. But this doesn't change anything.

**Comment by cdcseacave** [comment]
All the binaries in OpenMVS support some command line parameters, which are explained in detail if executed with no parameters or with "-h". ReconstructMesh has a cleaning stage incorporated, run automatically at the end of the reconstruction. Between the responsibilities of the cleaning stage, there is also the task of removing triangles with very long edges which always appear due to the way the mesh reconstruction works. There is a parameter defining what a "long edge" is. By default it is set to handle the case of dense reconstructed scenes with many densely sampled vertices and only few long edge triangles. If you want to run ReconstructMesh directly on the sparse point cloud, sometimes you need to tweak this parameter as well as all the other "cleaning" parameters.

**Comment by mad-de** [comment]
@cdcseacave Hi and thanks for your help. I have tried to change all parameters, that are listed for ReconstructMesh. Setting --reomove-spurious to 0-5 seems to prevent the mesh cleaning to remove the surfaces, but the real problem seems to be in the Delaunay tetrahedras graph-cut. And I haven't found out how to set it back to the way it was, yet.

I have tried to revert the latest changes to libs/MVS/SceneReconstruct.cpp but that didn't help.
As all of my models, I am using right now - not only the tutorial files - are affected: Is there a way to revert or set the Delaunay tetrahedras graph-cut to the way it was before?
Thanks for your help in advance.

**Comment by cdcseacave** [comment]
Of course it is. But first please tell me what is the problem with graph-cut. We better fix it instead of going back.

**Comment by pmoulon** [comment]
What about a git bisect to track what have changed.
You start from the state that was working, compile each time and iterate.

**Comment by mad-de** [comment]
@pmoulon I'll do that within the next days, but that might take me a while.

@cdcseacave For the same tutorial files: before updating graph-cut turned 16695 cells, 33390 faces into 2690 vertices and 5364 faces
the current version turns 16782 cells, 33564 faces  into 798 vertices, 1570 faces.

So graph cut now results in way to few vertices to get good models (at least for my files, which are already quite high-res)

**Comment by cdcseacave** [comment]
Are you sure you are running the pipeline correctly?
I just tested the "ImageDataset_SceauxCastle" scene with the latest binaries of OpenMVS and it works flawlessly (I didn't even have to tweak the clean parameters, the default ones are ok). Please find attached the log.
[ReconstructMesh-160415094342006675.txt](https://github.com/cdcseacave/openMVS/files/221384/ReconstructMesh-160415094342006675.txt)

**Comment by mad-de** [comment]
did you run DensifyPointCloud before or did you use the Describer Preset "Normal"? 
Because you seem to have a lot more points, than I do...

**Comment by cdcseacave** [comment]
I did not run DensifyPointCloud and I do not use OpenMVG, I have my own SFM pipeline. I'll try also with OpenMVG.

**Comment by mad-de** [comment]
@cdcseacave you can find my openMVG files here: https://mega.nz/#F!6IUiSSwT!xb4Ie7GCjPGWqidb1lem8A

**Comment by cdcseacave** [comment]
I just tested also with OpenMVG (the latest develop branch) and it works also with no parameter adjustment.
[ReconstructMesh-160415135434001299.txt](https://github.com/cdcseacave/openMVS/files/221766/ReconstructMesh-160415135434001299.txt)

**Comment by cdcseacave** [comment]
PS: as always, your reconstruction can not be used on other machine, as the bin folder stores full paths (well known problem of OpenMVG)

**Comment by pmoulon** [comment]
Not a problem. Just use openMVG_main_ConvertSfM_DataFormat to convert the .bin to .json and edit the root image path ;-)

**Comment by mad-de** [comment]
For some reason you are starting with way more points than I do after running openMVG:
Your output:
13:54:35 [App     ] Scene loaded from interface format (925ms):
	11 images (11 calibrated) with a total of 63.22 MPixels (5.75 MPixels/image)
	6468 points, 0 vertices, 0 faces

Mine:
11 images (11 calibrated) with a total of 63.22 MPixels (5.75 MPixels/image)
2926 points, 0 vertices, 0 faces

My amount of points is the same I had with old (working) versions of openMVS, so if you could point me to the changes in openMVS (so that I don't have to compare every git commit since february) I could write some sort of compatibility option to restore graph-cut to the way it was before. Maybe you'd like to accept that as a PR when its done...

**Comment by pmoulon** [comment]
@mad-de Git bisect use a dichotomy to allow you to find the point where you have an error.
So you will indicate the starting commit (where all the thing was running nice), and you will find the breaking point very fast. Then you checkout the repository at the fine stage in another directory and perform a diff. You will directly see the changes.

**Comment by mad-de** [comment]
@pmoulon thanks for the hint, I didn't knew about that functionality and will try to use it in the next days to sort out the issue.

**Comment by cdcseacave** [comment]
I'd like to help, but I do not recall any change in the graph-cut algorithm.

**Comment by mad-de** [comment]
thanks to @pmoulon for his advice with git bisect, which saved me a ton of work.

I figured out, that commit 0100c7f99ec7b59db2e36f86f4b164bf87523407 broke ReconstructMesh for me. Simply replacing SceneReconstruct.cpp with the file from archive before the commit (https://raw.githubusercontent.com/cdcseacave/openMVS/dea2b22c623d9903025bf7afdfc00c0951391c29/libs/MVS/SceneReconstruct.cpp) solves my issue. I'll look into it more specifically to test what line exactly triggered my error.

**Comment by mad-de** [comment]
Same openMVG input current SceneReconstruct:
![screenshot from 2016-04-17 00-14-39](https://cloud.githubusercontent.com/assets/7095883/14583936/be8d0168-0431-11e6-9a45-8680509223b7.png)
old Scene Reconstruct
![screenshot from 2016-04-17 00-16-06](https://cloud.githubusercontent.com/assets/7095883/14583939/c76e9c4c-0431-11e6-93bb-b4f222a51f0d.png)

**Comment by mad-de** [comment]
Figured it out: Problem is the squareroot function SQRT which was added with https://github.com/cdcseacave/openMVS/commit/0100c7f99ec7b59db2e36f86f4b164bf87523407

not working:
`const float sigma(SQRT(distsSq.GetMedian())*2);`
working:
`const float sigma(distsSq.GetMedian()*2);`
