### ISSUE TITLE
Strange results from DensifyPointCloud

### ISSUE THREAD

**Issue by bialasjaroslaw** [cdcseacave/openMVS#794]
First of all - **Thank you very much** for your work and all effort you have put in this project.

I decided to switch from older version at commit (b6ecabe) which took ~45 minutes to reconstruct a mesh  to more recent one (7346385) - CUDA sounds promising. It is couple times faster, however after the run I realized that mesh seems to be gone after `DensifyPointCloud`. I went back a little bit in git history and tried many different versions. 

It took me a while, but I was able to narrow it down to single commit - 0af0213. After reverting new way of computing scaled K (do not add 0.5 before scaling and skip subtraction as well) I've run whole pipeline once again and it was much better. I have attached screens from Viewer for visual comparison.

<details>
<summary>Input pointcloud generated by OpenMVG</summary>

![pointcloud](https://user-images.githubusercontent.com/22586035/159744813-0bbec7e7-117a-4fbc-ae3d-31915d084118.jpg)

</details>
<details>
<summary>After DensifyPointCloud (not working)</summary>

![densified_bad](https://user-images.githubusercontent.com/22586035/159744817-08f46608-302c-4119-bc58-2c58eec5fbc2.jpg)

</details>
<details>
<summary>After DensifyPointCloud (good)</summary>

![densified_good](https://user-images.githubusercontent.com/22586035/159744819-a8144f04-67e0-42d6-bd2f-b8ffc1e71847.jpg)

</details>

I don't know why camera scaling has been changed and if this has anything to do with new version of OpenMVG - I am using 1.6 (74deb33) which is quite old, but allows me to specify geometric model that works for my camera (4k 360). I just want to know if this is a bug (I doubt it as there would be a lot of complains since then), a missing parameter or anything else, that I am not aware.

I will be glad to provide more details and do some tests/changes/investigation etc. just let me know how can I be useful.

**Thank you** once again and have a great day.

**Comment by cdcseacave** [comment]
I doubt that change to the scaling is the issue, I think the other cahnge in the same commit is making problems for you. Recent OpenMVS prefers MVS scenes containing un-normalized cameras as opposite to the normalized one by image width. So OpenMVG chnaged too to output un-normalized cameras, so I think the old version of OpenMVG has a problem with the new OpenMVS. Pls try using latest openmvg and let me know.

**Comment by BrightWHU** [comment]
Sure! Only OpenMVG2.0 matches with the new OpenMVS. The old version of OpenMVG has a problem with the new OpenMVS. 

> I doubt that change to the scaling is the issue, I think the other cahnge in the same commit is making problems for you. Recent OpenMVS prefers MVS scenes containing un-normalized cameras as opposite to the normalized one by image width. So OpenMVG chnaged too to output un-normalized cameras, so I think the old version of OpenMVG has a problem with the new OpenMVS. Pls try using latest openmvg and let me know.

**Comment by cdcseacave** [comment]
seems solved
