### ISSUE TITLE
What algorithm is used to reconstruct the surface?

### ISSUE THREAD

**Issue by wujilingfeng** [cdcseacave/openMVS#796]
I wonder to konw what algorithm is used to reconstruct the surface?
Is it Power Crust algorithm?

Thank you very much!

**Comment by cdcseacave** [comment]
https://github.com/cdcseacave/openMVS/wiki/Modules

**Comment by wujilingfeng** [comment]
> https://github.com/cdcseacave/openMVS/wiki/Modules

Thank you very much !
