### ISSUE TITLE
 DensifyPointCloud aborted(core dumped)

### ISSUE THREAD

**Issue by PaulLiuYZ** [cdcseacave/openMVS#804]
the log is as foollowing:
./ReconstructMesh -i scene_dense.mvs --split-max-area 2650000
19:11:31 [App     ] Build date: Apr  5 2022, 10:51:38
19:11:31 [App     ] CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 cores)
19:11:31 [App     ] RAM: 31.21GB Physical Memory 2.00GB Virtual Memory
19:11:31 [App     ] OS: Linux 5.13.0-39-generic (x86_64)
19:11:31 [App     ] Disk: 14.10GB (97.44GB) space
19:11:31 [App     ] SSE & AVX compatible CPU & OS detected
19:11:32 [App     ] Command line: ReconstructMesh -i scene_dense.mvs --split-max-area 2650000
19:11:45 [App     ] Scene loaded (13s227ms):
	475 images (475 calibrated) with a total of 159.72 MPixels (0.34 MPixels/image)
	23626981 points, 0 vertices, 0 faces
Segmentation fault (core dumped)
do you know why? if it's because the ram is not enough or something else? 
what's more , if i use the devide and conquer method, how can i fuse the subpart together ?
Thank you!

**Comment by cdcseacave** [comment]
the command is probably not correct
use:
./ReconstructMesh scene_dense.mvs

**Comment by PaulLiuYZ** [comment]
i tried again using the new command, however , the process is killed.
./ReconstructMesh scene_dense.mvs 
14:01:57 [App     ] Build date: Apr  8 2022, 23:07:39
14:01:57 [App     ] CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 cores)
14:01:57 [App     ] RAM: 31.21GB Physical Memory 2.00GB Virtual Memory
14:01:57 [App     ] OS: Linux 5.13.0-39-generic (x86_64)
14:01:57 [App     ] Disk: 7.85GB (97.44GB) space
14:01:57 [App     ] SSE & AVX compatible CPU & OS detected
14:01:57 [App     ] Command line: ReconstructMesh scene_dense.mvs
14:01:57 [App     ] CUDA device 0 initialized: Quadro P4000 (compute capability 6.1; memory 7.93GB)
14:02:11 [App     ] Scene loaded (13s190ms):
	475 images (475 calibrated) with a total of 159.72 MPixels (0.34 MPixels/image)
	22749719 points, 0 vertices, 0 faces
Points inserted 22749719 (100%, 2m12s963ms)           
14:04:46 [App     ] Delaunay tetrahedralization completed: 22749719 points -> 17590783 vertices, 112880770 (+276) cells, 225761678 (+414) faces (2m25s698ms)
Points weighted 17590783 (100%, 2m23s289ms)           
14:08:13 [App     ] Delaunay tetrahedras weighting completed: 112881046 cells, 225762092 faces (3m24s404ms)
Killed

do you know why? if it's because the ram is not enough or something else?
what's more , if i use the devide and conquer method, how can i fuse the subpart together ?
Thank you again!

**Comment by cdcseacave** [comment]
yes, you do not have enough memory; try using https://github.com/cdcseacave/openMVS/issues/438#issuecomment-800972596

**Comment by PaulLiuYZ** [comment]
@cdcseacave Thank you so much! but i still have a question: how can i join the different parts together?
