### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/openMVG_main_PairGenerator': '/usr/local/bin/openMVG_main_PairGenerator'

### ISSUE THREAD

**Issue by antenna-fast** [cdcseacave/openMVS#806]
**Describe the bug**
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/openMVG_main_PairGenerator': '/usr/local/bin/openMVG_main_PairGenerator'

**To Reproduce**
Run the python script "MvgMvsPipeline.py", using the dataset: https://github.com/openMVG/ImageDataset_SceauxCastle

**Expected behavior**
I just want to run it without any ERROR

**Desktop (please complete the following information):**
 - OS: Ubuntu18.04
 - Browser  chrome

**Comment by antenna-fast** [comment]
btw, I can not find openMVG_main_PairGenerator in my openMVG's /build/Linux-x86_64-RELEASE

**Comment by cdcseacave** [comment]
you have to use the latest openmvg
