### ISSUE TITLE
DensifyPointCloud hidden options

### ISSUE THREAD

**Issue by mitjap** [cdcseacave/openMVS#81]
Can you please explain on how to use hidden options with DensifyPointCloud. We would really like to test various configurations.

**Comment by cdcseacave** [comment]
all options are commented in DepthMap.cpp, line 64
if you tell me what exactly you want to achieve, I can tell you what parameter you need to play with

**Comment by mitjap** [comment]
We would like to increase smoothing a bit, and somehow remove spurious points that are on the edge of the point cloud.

Do I have to create some .cfg file and then pass it to app with `--dense-config-file=my_config_file.cfg`? And withing that file I add options like this `flag_name_from_DepthMap_file=some_value`?

**Comment by cdcseacave** [comment]
first run with `--dense-config-file somefile.ini`, change the params, and rerun

**Comment by mitjap** [comment]
thank you..
