### ISSUE TITLE
error: reference image  28 has not enough images in view

### ISSUE THREAD

**Issue by yuanhn5206** [cdcseacave/openMVS#812]
23:54:53 [App     ] Build date: Apr 17 2022, 11:49:17
23:54:53 [App     ] CPU: AMD Ryzen 7 3700X 8-Core Processor              (16 cores)
23:54:53 [App     ] RAM: 47.93GB Physical Memory 128.00TB Virtual Memory
23:54:53 [App     ] OS: Windows 8 x64
23:54:53 [App     ] Disk: 562.73GB (931.50GB) space
23:54:53 [App     ] SSE & AVX compatible CPU & OS detected
23:54:53 [App     ] Command line: DensifyPointCloud .\hnu\scene.mvs
23:54:53 [App     ] CUDA device 0 initialized: NVIDIA GeForce GTX 1660 SUPER (compute capability 7.5; memory 6.00GB)
23:54:53 [App     ] Camera model loaded: platform 0; camera  0; f 0.645x0.645; poses 31
23:54:53 [App     ] Scene loaded from interface format (8ms):
        31 images (31 calibrated) with a total of 27.25 MPixels (0.88 MPixels/image)
        2112 points, 0 vertices, 0 faces
23:54:53 [App     ] Preparing images for dense reconstruction completed: 31 images (30ms)
23:54:53 [App     ] error: reference image  28 has not enough images in view
23:54:53 [App     ] error: reference image   0 has not enough images in view
23:54:53 [App     ] error: reference image   3 has not enough images in view
23:54:53 [App     ] error: reference image   8 has not enough images in view
23:54:53 [App     ] error: reference image   1 has not enough images in view
23:54:53 [App     ] error: reference image  23 has not enough images in view
23:54:53 [App     ] error: reference image  24 has not enough images in view
23:54:53 [App     ] error: reference image  14 has not enough images in view
23:54:53 [App     ] error: reference image  11 has not enough images in view
23:54:53 [App     ] error: reference image  19 has not enough images in view
23:54:53 [App     ] error: reference image   9 has not enough images in view
23:54:53 [App     ] error: reference image  12 has not enough images in view
23:54:53 [App     ] error: reference image  21 has not enough images in view
23:54:53 [App     ] error: reference image  16 has not enough images in view
23:54:53 [App     ] error: reference image  26 has not enough images in view
23:54:53 [App     ] error: reference image  20 has not enough images in view
23:54:53 [App     ] error: reference image  15 has not enough images in view
23:54:53 [App     ] error: reference image  29 has not enough images in view
23:54:53 [App     ] error: reference image   2 has not enough images in view
23:54:53 [App     ] error: reference image  17 has not enough images in view
23:54:53 [App     ] error: reference image  25 has not enough images in view
23:54:53 [App     ] error: reference image  10 has not enough images in view
23:54:53 [App     ] error: reference image  30 has not enough images in view
23:54:53 [App     ] error: reference image   6 has not enough images in view
23:54:53 [App     ] error: reference image   5 has not enough images in view
23:54:53 [App     ] error: reference image   4 has not enough images in view
23:54:53 [App     ] error: reference image  27 has not enough images in view
23:54:53 [App     ] error: reference image   7 has not enough images in view
23:54:53 [App     ] error: reference image  18 has not enough images in view
23:54:53 [App     ] error: reference image  22 has not enough images in view
23:54:53 [App     ] error: reference image  13 has not enough images in view

**Comment by yuanhn5206** [comment]
did anyone know how to solve the problem?

**Comment by 3XH6R** [comment]
Can you supply the dataset to better diagnose.

**Comment by yuanhn5206** [comment]
alright, after I test in another pc, it works well. may be something wrong with my PC.
