### ISSUE TITLE
export to .obj file format (--export-type obj) exports to current path ignoring -w

### ISSUE THREAD

**Issue by mad-de** [cdcseacave/openMVS#82]
### Specifications like the version of the project, operating system, and hardware
latest openMVG from develop branch
latest openMVS

Ubuntu 15.10 64-bit
Memory 3,8 GiB
Processor Intel® Core™ i3-4160 CPU @ 3.60GHz × 4
Graphics Intel® Haswell 

### Steps to reproduce the problem
Hope you are still accepting issues from me :)

I have trouble exporting to the .obj format, which doesn't work (tried it with ReconstructMesh, RefineMesh and TextureMesh). It generates no error,. but no .obj output file as well... 
Works fine with "--export-type ply" to export to .ply.

Refine Output files:
- scene_dense_mesh_refine_texture.mvs
- scene_dense_mesh_refine_texture.mlp

Any way I can debug this for you?

Output for the whole workflow (on standard tutorial files):

> 
 0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Scene saved to OpenMVS interface format:
	11 images (10 calibrated)
	2633 Landmarks
23:16:49 [App     ] Build date: Apr 17 2016, 11:20:49
23:16:49 [App     ] CPU: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
23:16:49 [App     ] RAM: 3.77GB Physical Memory 3.91GB Virtual Memory
23:16:49 [App     ] OS: Linux 4.2.0-35-generic (x86_64)
23:16:49 [App     ] SSE & AVX compatible CPU & OS detected
23:16:49 [App     ] Command line: /home/martin-uwh/meshes/scapula_8_out/castle/scene.mvs -w /home/martin-uwh/meshes/scapula_8_out/castle/ --resolution-level 3
23:16:49 [App     ] Camera model loaded: platform 0; camera  0; f 1.055x1.055; poses 10
23:16:49 [App     ] Image loaded   0: 100_7100.JPG
23:16:49 [App     ] Image loaded   1: 100_7101.JPG
23:16:49 [App     ] Image loaded   2: 100_7102.JPG
23:16:49 [App     ] Image loaded   3: 100_7103.JPG
23:16:49 [App     ] Image loaded   4: 100_7104.JPG
23:16:49 [App     ] Image loaded   5: 100_7105.JPG
23:16:50 [App     ] Image loaded   6: 100_7106.JPG
23:16:50 [App     ] Image loaded   7: 100_7107.JPG
23:16:50 [App     ] Image loaded   8: 100_7108.JPG
23:16:50 [App     ] Image loaded   9: 100_7109.JPG
23:16:50 [App     ] warning: uncalibrated image '/home/martin-uwh/meshes/scapula_8_out/castle/undistorted_images//100_7110.JPG'
23:16:50 [App     ] Scene loaded from interface format (371ms):
	11 images (10 calibrated) with a total of 57.47 MPixels (5.75 MPixels/image)
	2633 points, 0 vertices, 0 faces
23:16:50 [App     ] Preparing images for dense reconstruction completed: 11 images (264ms)
23:16:50 [App     ] Selecting images for dense reconstruction completed: 10 images (5ms)
Estimated depth-maps 1 (10.00%, 8s, ETA 1m)...
Estimated depth-maps 2 (20.00%, 16s, ETA 1m)...
Estimated depth-maps 3 (30.00%, 23s, ETA 55s)...
Estimated depth-maps 4 (40.00%, 30s, ETA 46s)...
Estimated depth-maps 5 (50.00%, 37s, ETA 37s)...
Estimated depth-maps 6 (60.00%, 44s, ETA 29s)...
Estimated depth-maps 7 (70.00%, 51s, ETA 22s)...
Estimated depth-maps 8 (80.00%, 58s, ETA 14s)...
Estimated depth-maps 9 (90.00%, 1m6s, ETA 7s)...
Estimated depth-maps 10 (100.00%, 1m13s, ETA 0ms)...
Estimated depth-maps 10 (100%, 1m13s19ms)           
Filtered depth-maps 1 (10.00%, 1s, ETA 13s)...
Filtered depth-maps 5 (50.00%, 1s, ETA 1s)... 
Filtered depth-maps 9 (90.00%, 1s, ETA 195ms)...
Filtered depth-maps 10 (100%, 1s763ms)          
Fused depth-maps 0 (0.00%, 136ms, ETA 0ms)...
Fused depth-maps 3 (30.00%, 271ms, ETA 634ms)...
Fused depth-maps 6 (60.00%, 390ms, ETA 260ms)...
Fused depth-maps 8 (80.00%, 499ms, ETA 124ms)...
Fused depth-maps 10 (100%, 554ms)               
23:18:06 [App     ] Depth-maps fused and filtered: 10 depth-maps, 2395002 depths, 356226 points (15%%) (1s209ms)
23:18:06 [App     ] Densifying point-cloud completed: 356226 points (1m16s433ms)
23:18:07 [App     ] Scene saved (618ms):
	11 images (10 calibrated)
	356226 points, 0 vertices, 0 faces
23:18:07 [App     ] Point-cloud saved: 356226 points (54ms)
23:18:07 [App     ] MEMORYINFO: {
23:18:07 [App     ] 	VmPeak:	 1325128 kB
23:18:07 [App     ] 	VmSize:	 1325128 kB
23:18:07 [App     ] } ENDINFO
23:18:07 [App     ] Build date: Apr 17 2016, 11:20:49
23:18:07 [App     ] CPU: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
23:18:07 [App     ] RAM: 3.77GB Physical Memory 3.91GB Virtual Memory
23:18:07 [App     ] OS: Linux 4.2.0-35-generic (x86_64)
23:18:07 [App     ] SSE & AVX compatible CPU & OS detected
23:18:07 [App     ] Command line: /home/martin-uwh/meshes/scapula_8_out/castle/scene_dense.mvs -w /home/martin-uwh/meshes/scapula_8_out/castle/ -v 3 --export-type obj
23:18:08 [App     ] Scene loaded (368ms):
	11 images (10 calibrated) with a total of 3.59 MPixels (0.36 MPixels/image)
	356226 points, 0 vertices, 0 faces
23:18:09 [App     ] Delaunay tetrahedralization completed: 356226 points -> 66260 vertices, 415631 (+178) cells, 831351 (+267) faces (1s562ms)
23:18:12 [App     ] 	weighting completed in 2s302ms
23:18:12 [App     ] Delaunay tetrahedras weighting completed: 415809 cells, 831618 faces (2s616ms)
23:18:13 [App     ] Delaunay tetrahedras graph-cut completed (121212 flow): 53671 vertices, 107315 faces (1s1ms)
23:18:13 [App     ] Fixed 0/1 non-manifold edges/vertices and 4 faces removed: 0 pyramid3 and 1 pyramid4 (217ms)
23:18:14 [App     ] Fixed 0/0 non-manifold edges/vertices and 0 faces removed: 0 pyramid3 and 0 pyramid4 (216ms)
23:18:14 [App     ] Mesh reconstruction completed: 53671 vertices, 107313 faces (5s817ms)
23:18:14 [App     ] Mesh saved: 53671 vertices, 107313 faces (118ms)
23:18:14 [App     ] Removed 0 zero-area faces
23:18:14 [App     ] Removed 0 duplicate faces
23:18:14 [App     ] Removed 0 non-manifold faces
23:18:14 [App     ] Removed 0 degenerate vertices
23:18:14 [App     ] Removed 0 unreferenced vertices
23:18:14 [App     ] Removed 0 duplicate vertices
23:18:14 [App     ] Split 0 non-manifold vertices
23:18:14 [App     ] Removed 39 faces with edges longer than 0.200730
23:18:14 [App     ] Removed 0 connected components out of 1
23:18:14 [App     ] Removed 1 spikes
23:18:15 [App     ] Closed 0 holes and added 0 new faces
23:18:15 [App     ] Smoothed 53668 vertices
23:18:15 [App     ] Cleaned mesh: 53668 vertices, 107273 faces (761ms)
23:18:15 [App     ] Removed 0 zero-area faces
23:18:15 [App     ] Removed 0 duplicate faces
23:18:15 [App     ] Removed 0 non-manifold faces
23:18:15 [App     ] Removed 0 degenerate vertices
23:18:15 [App     ] Removed 0 unreferenced vertices
23:18:15 [App     ] Removed 0 duplicate vertices
23:18:15 [App     ] Split 0 non-manifold vertices
23:18:15 [App     ] Removed 0 spikes
23:18:15 [App     ] Closed 0 holes and added 0 new faces
23:18:15 [App     ] Cleaned mesh: 53668 vertices, 107273 faces (544ms)
23:18:15 [App     ] Removed 0 zero-area faces
23:18:15 [App     ] Removed 0 duplicate faces
23:18:15 [App     ] Removed 0 non-manifold faces
23:18:15 [App     ] Removed 0 degenerate vertices
23:18:15 [App     ] Removed 0 unreferenced vertices
23:18:15 [App     ] Removed 0 duplicate vertices
23:18:16 [App     ] Split 0 non-manifold vertices
23:18:16 [App     ] Cleaned mesh: 53668 vertices, 107273 faces (437ms)
23:18:16 [App     ] Scene saved (120ms):
	11 images (10 calibrated)
	0 points, 53668 vertices, 107273 faces
23:18:16 [App     ] Mesh saved: 53668 vertices, 107273 faces (101ms)
23:18:16 [App     ] Build date: Apr 17 2016, 11:20:49
23:18:16 [App     ] CPU: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
23:18:16 [App     ] RAM: 3.77GB Physical Memory 3.91GB Virtual Memory
23:18:16 [App     ] OS: Linux 4.2.0-35-generic (x86_64)
23:18:16 [App     ] SSE & AVX compatible CPU & OS detected
23:18:16 [App     ] Command line: /home/martin-uwh/meshes/scapula_8_out/castle/scene_dense_mesh.mvs -w /home/martin-uwh/meshes/scapula_8_out/castle/ --scales 3 --resolution-level 2 -v 3 --close-holes 30 --export-type obj
23:18:16 [App     ] Scene loaded (136ms):
	11 images (10 calibrated) with a total of 3.59 MPixels (0.36 MPixels/image)
	0 points, 53668 vertices, 107273 faces
23:18:16 [App     ] Refine mesh at: 0.25 image scale
Decimated faces 16670 (17.27%, 199ms, ETA 954ms)...
Decimated faces 29344 (30.39%, 299ms, ETA 686ms)...
Decimated faces 40648 (42.10%, 399ms, ETA 549ms)...
Decimated faces 51016 (52.84%, 499ms, ETA 445ms)...
Decimated faces 60248 (62.40%, 599ms, ETA 361ms)...
Decimated faces 73010 (75.62%, 701ms, ETA 226ms)...
Decimated faces 88036 (91.19%, 801ms, ETA 77ms)... 
Decimated faces 96546 (100%, 865ms)               
23:18:18 [App     ] Mesh decimated: 107273 -> 10727 faces
23:18:18 [App     ] Removed 0 zero-area faces
23:18:18 [App     ] Removed 0 duplicate faces
23:18:18 [App     ] Removed 0 non-manifold faces
23:18:18 [App     ] Removed 0 degenerate vertices
23:18:18 [App     ] Removed 0 unreferenced vertices
23:18:18 [App     ] Removed 0 duplicate vertices
23:18:18 [App     ] Split 0 non-manifold vertices
23:18:18 [App     ] Closed 0 holes and added 0 new faces
23:18:18 [App     ] Cleaned mesh: 5394 vertices, 10726 faces (1s250ms)
23:18:18 [App     ] Removed 0 zero-area faces
23:18:18 [App     ] Removed 0 duplicate faces
23:18:18 [App     ] Removed 0 non-manifold faces
23:18:18 [App     ] Removed 0 degenerate vertices
23:18:19 [App     ] Removed 0 unreferenced vertices
23:18:19 [App     ] Removed 0 duplicate vertices
23:18:19 [App     ] Split 0 non-manifold vertices
23:18:19 [App     ] Closed 0 holes and added 0 new faces
23:18:19 [App     ] Removed 0 non-manifold faces
23:18:19 [App     ] Removed 0 non-manifold vertices
23:18:19 [App     ] Cleaned mesh: 5394 vertices, 10726 faces (367ms)
23:18:19 [App     ] Mesh imported: 5394 vertices, 10726 facets (60 border edges)
23:18:19 [App     ] Edge size in [0.00425827, 0.0721892] (requested in [0.00925125, 0.07401]): 1003 ops, 16 iters
23:18:19 [App     ] Mesh exported: 4476 vertices, 8862 facets (88 border edges)
23:18:19 [App     ] Removed 0 zero-area faces
23:18:19 [App     ] Removed 0 duplicate faces
23:18:19 [App     ] Removed 0 non-manifold faces
23:18:19 [App     ] Removed 0 degenerate vertices
23:18:19 [App     ] Removed 0 unreferenced vertices
23:18:19 [App     ] Removed 0 duplicate vertices
23:18:19 [App     ] Split 0 non-manifold vertices
23:18:19 [App     ] Closed 0 holes and added 0 new faces
23:18:19 [App     ] Removed 0 non-manifold faces
23:18:19 [App     ] Removed 0 non-manifold vertices
23:18:19 [App     ] Cleaned mesh: 4476 vertices, 8862 faces (341ms)
23:18:19 [App     ] Mesh subdivided: 5394/10726 -> 4476/8862 vertices/faces
23:18:20 [App     ] Mesh saved: 4476 vertices, 8862 faces (33ms)
Processed iterations 0 (0.00%, 158ms, ETA 0ms)...
Processed iterations 1 (2.22%, 316ms, ETA 13s)...
Processed iterations 2 (4.44%, 483ms, ETA 10s)...
Processed iterations 3 (6.67%, 642ms, ETA 8s)... 
Processed iterations 4 (8.89%, 800ms, ETA 8s)...
Processed iterations 5 (11.11%, 958ms, ETA 7s)...
Processed iterations 6 (13.33%, 1s, ETA 7s)...   
Processed iterations 7 (15.56%, 1s, ETA 6s)...
Processed iterations 8 (17.78%, 1s, ETA 6s)...
Processed iterations 9 (20.00%, 1s, ETA 6s)...
Processed iterations 10 (22.22%, 1s, ETA 6s)...
Processed iterations 11 (24.44%, 1s, ETA 5s)...
Processed iterations 12 (26.67%, 2s, ETA 5s)...
Processed iterations 13 (28.89%, 2s, ETA 5s)...
Processed iterations 14 (31.11%, 2s, ETA 5s)...
Processed iterations 15 (33.33%, 2s, ETA 5s)...
Processed iterations 16 (35.56%, 2s, ETA 5s)...
Processed iterations 17 (37.78%, 2s, ETA 4s)...
Processed iterations 18 (40.00%, 3s, ETA 4s)...
Processed iterations 19 (42.22%, 3s, ETA 4s)...
Processed iterations 20 (44.44%, 3s, ETA 4s)...
Processed iterations 21 (46.67%, 3s, ETA 4s)...
Processed iterations 22 (48.89%, 3s, ETA 3s)...
Processed iterations 23 (51.11%, 3s, ETA 3s)...
Processed iterations 24 (53.33%, 4s, ETA 3s)...
Processed iterations 25 (55.56%, 4s, ETA 3s)...
Processed iterations 26 (57.78%, 4s, ETA 3s)...
Processed iterations 27 (60.00%, 4s, ETA 3s)...
Processed iterations 28 (62.22%, 4s, ETA 2s)...
Processed iterations 29 (64.44%, 4s, ETA 2s)...
Processed iterations 30 (66.67%, 5s, ETA 2s)...
Processed iterations 31 (68.89%, 5s, ETA 2s)...
Processed iterations 32 (71.11%, 5s, ETA 2s)...
Processed iterations 33 (73.33%, 5s, ETA 2s)...
Processed iterations 34 (75.56%, 5s, ETA 1s)...
Processed iterations 35 (77.78%, 5s, ETA 1s)...
Processed iterations 36 (80.00%, 6s, ETA 1s)...
Processed iterations 37 (82.22%, 6s, ETA 1s)...
Processed iterations 38 (84.44%, 6s, ETA 1s)...
Processed iterations 39 (86.67%, 6s, ETA 1s)...
Processed iterations 40 (88.89%, 6s, ETA 846ms)...
Processed iterations 41 (91.11%, 6s, ETA 676ms)...
Processed iterations 42 (93.33%, 7s, ETA 506ms)...
Processed iterations 43 (95.56%, 7s, ETA 337ms)...
Processed iterations 44 (97.78%, 7s, ETA 168ms)...
Processed iterations 45 (100%, 7s405ms)           
23:18:27 [App     ] Mesh saved: 4476 vertices, 8862 faces (33ms)
23:18:27 [App     ] Refine mesh at: 0.50 image scale
23:18:27 [App     ] Mesh subdivided: 4476/8862 -> 4502/8913 vertices/faces
23:18:27 [App     ] Mesh saved: 4502 vertices, 8913 faces (30ms)
Processed iterations 0 (0.00%, 491ms, ETA 0ms)...
Processed iterations 1 (4.55%, 975ms, ETA 20s)...
Processed iterations 2 (9.09%, 1s, ETA 14s)...   
Processed iterations 3 (13.64%, 1s, ETA 12s)...
Processed iterations 4 (18.18%, 2s, ETA 11s)...
Processed iterations 5 (22.73%, 2s, ETA 10s)...
Processed iterations 6 (27.27%, 3s, ETA 9s)... 
Processed iterations 7 (31.82%, 3s, ETA 8s)...
Processed iterations 8 (36.36%, 4s, ETA 7s)...
Processed iterations 9 (40.91%, 4s, ETA 7s)...
Processed iterations 10 (45.45%, 5s, ETA 6s)...
Processed iterations 11 (50.00%, 5s, ETA 5s)...
Processed iterations 12 (54.55%, 6s, ETA 5s)...
Processed iterations 13 (59.09%, 6s, ETA 4s)...
Processed iterations 14 (63.64%, 7s, ETA 4s)...
Processed iterations 15 (68.18%, 7s, ETA 3s)...
Processed iterations 16 (72.73%, 8s, ETA 3s)...
Processed iterations 17 (77.27%, 8s, ETA 2s)...
Processed iterations 18 (81.82%, 9s, ETA 2s)...
Processed iterations 19 (86.36%, 9s, ETA 1s)...
Processed iterations 20 (90.91%, 10s, ETA 1s)...
Processed iterations 21 (95.45%, 10s, ETA 521ms)...
Processed iterations 22 (100%, 10s960ms)           
23:18:38 [App     ] Mesh saved: 4502 vertices, 8913 faces (25ms)
23:18:38 [App     ] Refine mesh at: 1.00 image scale
23:18:39 [App     ] Mesh subdivided: 4502/8913 -> 7427/14710 vertices/faces
23:18:39 [App     ] Mesh saved: 7427 vertices, 14710 faces (27ms)
Processed iterations 0 (0.00%, 1s, ETA 0ms)...
Processed iterations 1 (6.67%, 3s, ETA 51s)...
Processed iterations 2 (13.33%, 5s, ETA 36s)...
Processed iterations 3 (20.00%, 7s, ETA 29s)...
Processed iterations 4 (26.67%, 9s, ETA 25s)...
Processed iterations 5 (33.33%, 11s, ETA 22s)...
Processed iterations 6 (40.00%, 13s, ETA 19s)...
Processed iterations 7 (46.67%, 14s, ETA 17s)...
Processed iterations 8 (53.33%, 16s, ETA 14s)...
Processed iterations 9 (60.00%, 18s, ETA 12s)...
Processed iterations 10 (66.67%, 20s, ETA 10s)...
Processed iterations 11 (73.33%, 22s, ETA 8s)... 
Processed iterations 12 (80.00%, 24s, ETA 6s)...
Processed iterations 13 (86.67%, 26s, ETA 4s)...
Processed iterations 14 (93.33%, 27s, ETA 1s)...
Processed iterations 15 (100%, 27s978ms)        
23:19:07 [App     ] Mesh saved: 7427 vertices, 14710 faces (25ms)
23:19:07 [App     ] Mesh refinement completed: 7427 vertices, 14710 faces (50s411ms)
23:19:07 [App     ] Scene saved (9ms):
	11 images (10 calibrated)
	0 points, 7427 vertices, 14710 faces
23:19:07 [App     ] Mesh saved: 7427 vertices, 14710 faces (18ms)
23:19:07 [App     ] Build date: Apr 17 2016, 11:20:49
23:19:07 [App     ] CPU: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
23:19:07 [App     ] RAM: 3.77GB Physical Memory 3.91GB Virtual Memory
23:19:07 [App     ] OS: Linux 4.2.0-35-generic (x86_64)
23:19:07 [App     ] SSE & AVX compatible CPU & OS detected
23:19:07 [App     ] Command line: /home/martin-uwh/meshes/scapula_8_out/castle/scene_dense_mesh_refine.mvs -w /home/martin-uwh/meshes/scapula_8_out/castle/ --resolution-level 2 -v 3 --export-type obj
23:19:07 [App     ] Scene loaded (5ms):
	11 images (10 calibrated) with a total of 3.59 MPixels (0.36 MPixels/image)
	0 points, 7427 vertices, 14710 faces
23:19:08 [App     ] Initializing images completed: 11 images (206ms)
23:19:08 [App     ] 	 0. e: 2.34294e+07	d: 7.51149e+06	t: 17ms
23:19:08 [App     ] 	 1. e: 1.59179e+07	d: 2.80598e+06	t: 17ms
23:19:08 [App     ] 	 2. e: 1.3112e+07	d: 803627	t: 22ms
23:19:08 [App     ] 	 3. e: 1.23083e+07	d: 757747	t: 18ms
23:19:08 [App     ] 	 4. e: 1.15506e+07	d: 887901	t: 17ms
23:19:08 [App     ] 	 5. e: 1.06627e+07	d: 1.11918e+06	t: 24ms
23:19:08 [App     ] 	 6. e: 9.5435e+06	d: 1.04738e+06	t: 42ms
23:19:08 [App     ] 	 7. e: 8.49612e+06	d: 790954	t: 30ms
23:19:08 [App     ] 	 8. e: 7.70517e+06	d: 810462	t: 21ms
23:19:08 [App     ] 	 9. e: 6.8947e+06	d: 256294	t: 23ms
23:19:08 [App     ] 	10. e: 6.63841e+06	d: 331630	t: 19ms
23:19:09 [App     ] 	11. e: 6.30678e+06	d: 228567	t: 23ms
23:19:09 [App     ] 	12. e: 6.07821e+06	d: 456362	t: 37ms
23:19:09 [App     ] 	13. e: 5.62185e+06	d: 213301	t: 55ms
23:19:09 [App     ] 	14. e: 5.40855e+06	d: 384019	t: 35ms
23:19:09 [App     ] 	15. e: 5.02453e+06	d: 232504	t: 53ms
23:19:09 [App     ] 	16. e: 4.79203e+06	d: 367740	t: 33ms
23:19:09 [App     ] 	17. e: 4.42429e+06	d: 91523.5	t: 19ms
23:19:09 [App     ] 	18. e: 4.33276e+06	d: 131768	t: 20ms
23:19:09 [App     ] 	19. e: 4.201e+06	d: 19630.5	t: 17ms
23:19:09 [App     ] 	20. e: 4.18136e+06	d: 135488	t: 17ms
23:19:09 [App     ] 	21. e: 4.04588e+06	d: 129784	t: 17ms
23:19:09 [App     ] 	22. e: 3.91609e+06	d: 129784	t: 17ms
23:19:09 [App     ] 	23. e: 3.78631e+06	d: 13881.2	t: 17ms
23:19:09 [App     ] 	24. e: 3.77243e+06	d: 63957.8	t: 17ms
23:19:09 [App     ] 	25. e: 3.70847e+06	d: 149674	t: 17ms
23:19:09 [App     ] 	26. e: 3.5588e+06	d: 58019.2	t: 17ms
23:19:09 [App     ] 	27. e: 3.50078e+06	d: 75704.8	t: 17ms
23:19:09 [App     ] 	28. e: 3.42507e+06	d: -43933.5	t: 18ms
23:19:09 [App     ] 	29. e: 3.469e+06	d: 107962	t: 17ms
23:19:10 [App     ] 	30. e: 3.36104e+06	d: 74268.5	t: 17ms
23:19:10 [App     ] 	31. e: 3.28677e+06	d: 113880	t: 18ms
23:19:10 [App     ] 	32. e: 3.17289e+06	d: 55.75	t: 17ms
23:19:10 [App     ] 	33. e: 3.17284e+06	d: 46064.2	t: 17ms
23:19:10 [App     ] 	34. e: 3.12677e+06	d: 73593.5	t: 17ms
23:19:10 [App     ] 	35. e: 3.05318e+06	d: -17697.5	t: 18ms
23:19:10 [App     ] 	36. e: 3.07088e+06	d: 29886.2	t: 17ms
23:19:10 [App     ] 	37. e: 3.04099e+06	d: -40051.8	t: 17ms
23:19:10 [App     ] 	38. e: 3.08104e+06	d: 35689.5	t: 17ms
23:19:10 [App     ] 	39. e: 3.04535e+06	d: 60111	t: 17ms
23:19:10 [App     ] 	40. e: 2.98524e+06	d: 9656.25	t: 18ms
23:19:10 [App     ] 	41. e: 2.97559e+06	d: 9189.25	t: 21ms
23:19:10 [App     ] 	42. e: 2.9664e+06	d: -18198	t: 33ms
23:19:10 [App     ] 	43. e: 2.9846e+06	d: 40118.5	t: 39ms
23:19:10 [App     ] 	44. e: 2.94448e+06	d: 56054	t: 22ms
23:19:10 [App     ] 	45. e: 2.88842e+06	d: 19844	t: 21ms
23:19:10 [App     ] 	46. e: 2.86858e+06	d: 13730.8	t: 21ms
23:19:10 [App     ] 	47. e: 2.85485e+06	d: -21869	t: 18ms
23:19:10 [App     ] 	48. e: 2.87672e+06	d: 14052.2	t: 17ms
23:19:11 [App     ] 	49. e: 2.86266e+06	d: 15930	t: 24ms
23:19:11 [App     ] 	50. e: 2.84673e+06	d: 26066.5	t: 42ms
23:19:11 [App     ] 	51. e: 2.82067e+06	d: -19877	t: 56ms
23:19:11 [App     ] 	52. e: 2.84054e+06	d: -11781	t: 30ms
23:19:11 [App     ] 	53. e: 2.85233e+06	d: 49861	t: 19ms
23:19:11 [App     ] Inference aborted (energy increased): 54 iterations, 2.80246e+06 energy (2s959ms)
23:19:11 [App     ] Assigning the best view to each face completed: 14710 faces (3s273ms)
23:19:11 [App     ] 	global seam leveling completed (56ms)
23:19:11 [App     ] 	local seam leveling completed (462ms)
23:19:12 [App     ] 	packing texture completed: 71 patches, 1024 texture-size (0ms)
23:19:12 [App     ] Generating texture atlas and image completed: 71 patches, 1024 image size (610ms)
23:19:12 [App     ] Mesh texturing completed: 7427 vertices, 14710 faces (4s183ms)
23:19:12 [App     ] Scene saved (202ms):
	11 images (10 calibrated)
	0 points, 7427 vertices, 14710 faces
23:19:12 [App     ] Mesh saved: 7427 vertices, 14710 faces (50ms)`

**Comment by cdcseacave** [comment]
Hi @mad-de ! Glade to help, but I do not see the problem. The log is saying the mesh was saved.

**Comment by mad-de** [comment]
I am expecting a .obj file as output. Am I wrong?

On 24 April 2016 04:03:49 CEST, cDc <notifications@github.com> wrote:
>Hi @mad-de ! Glade to help, but I do not see the problem. The log is
>saying the mesh was saved.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cdcseacave/openMVS/issues/82#issuecomment-213866073

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cdcseacave** [comment]
no, you are right

**Comment by mad-de** [comment]
Hey - I think I fond part of the solution:
the .obj wasn't expoorted to the working folder but to the folder where I called the script from, which IO just found out by chance right now :)

**Comment by cdcseacave** [comment]
ok, now I understand the problem
please let me have a look

**Comment by cdcseacave** [comment]
solved, try the last commit

**Comment by mad-de** [comment]
I can confirm that this solved the issue. Thanks for your work!
