### ISSUE TITLE
Error: /lib/libMVS.so: undefined reference to `MeshRefineCUDA::HalfSize'

### ISSUE THREAD

**Issue by HKUSTmji** [cdcseacave/openMVS#83]
### Specifications like the version of the project, operating system, and hardware
ubuntu 14.04, GPU: Titan X
### Steps to reproduce the problem
I follow the guideline in https://github.com/cdcseacave/openMVS/wiki/Building
It works well until to 'make' the project. The error comes:

[ 21%] Built target Common
[ 28%] Built target Math
[ 58%] Built target IO
[ 89%] Built target MVS
Linking CXX executable ../../bin/InterfaceVisualSFM
../../lib/libMVS.so: undefined reference to 'MeshRefineCUDA::HalfSize'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/InterfaceVisualSFM] Error 1
make[1]: *** [apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/all] Error 2
make: *** [all] Error 2

Could anyone help me on this issue please~ Thanks in advance.

**Comment by mad-de** [comment]
can you update to 15.10? this one is tested, otherwise you could try to remove the CUDA line, as you probably won`t be using it anyway I assume...

**Comment by pmoulon** [comment]
I would suggest the same as @mad-de Try to compile first without CUDA support. Then test the software and in a second time add the CUDA back end.

**Comment by cdcseacave** [comment]
You can disable CUDA support while configuring the CMake project.

**Comment by HKUSTmji** [comment]
thanks all of you. It can pass the compile phase after turning down the CUDA support. I may test it again on Ubuntu 15.10 latter. Still hope this issue can be fixed for the Ubuntu 14.04.

**Comment by mbrix** [comment]
I'm using 15.10 and I have the same issue (using cuda-7.5 on x64), I've noticed that manually appending -lcuda to the end of the generated link.txts seems to resolve the issue for everything except RefineMesh which still throws this particular error.

**Comment by mbrix** [comment]
Also have the same issue on Ubuntu 16.04. I can compile normally, but I get this error on RefineMesh if Cuda is enabled.

**Comment by cdcseacave** [comment]
I do not have a Linux machine with CUDA to test it, but theoretically this commit should fix the problem. Please confirm!

**Comment by mbrix** [comment]
That certainly did it, thank you very much. I still have to manually link to cuda, the cmake files detect but aren't adding the -lcuda linker flag to the generated makefiles.
