### ISSUE TITLE
'DensifyPointCloud scene.mvs' Error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by HKUSTmji** [cdcseacave/openMVS#84]
### Specifications like the version of the project, operating system, and hardware
Ubuntu 14.04; GPU: TITAN X
### Steps to reproduce the problem
I followed the [tutorial](https://github.com/cdcseacave/openMVS/wiki/Usage) and got error after command: `DensifyPointCloud scene.mvs`

mji@EEE0625:~/libs/openMVS_build/bin$ ./DensifyPointCloud /home/mji/libs/ImageDataset_SceauxCastle-master/images/scene.mvs 
17:46:18 [App     ] Build date: Apr 27 2016, 15:56:35
17:46:18 [App     ] CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
17:46:18 [App     ] RAM: 31.36GB Physical Memory 31.88GB Virtual Memory
17:46:18 [App     ] OS: Linux 3.19.0-32-generic (x86_64)
17:46:18 [App     ] SSE & AVX compatible CPU & OS detected
17:46:18 [App     ] Command line: /home/mji/libs/ImageDataset_SceauxCastle-master/images/scene.mvs
17:46:18 [App     ] Camera model loaded: platform 0; camera  0; f 1.056x1.056; poses 10
Segmentation fault (core dumped)

Is that the correct way to call the densifypointcloud method? There are many files generated by the openMVG global method: `python SfM_GlobalPipeline.py [full path image directory] [resulting directory]`, which ones could be useful for openMVS pipeline? And where to put both the useful files and the images used for reconstruction?

Thank you very much~

**Comment by pmoulon** [comment]
here some doc: http://openmvg.readthedocs.org/en/latest/software/MVS/OpenMVS/
Have you used somethinf like this:
```
# Export the OpenMVG scene to the OpenMVS data format
$ openMVG_main_openMVG2openMVS -i PATH/sfm_data.(json/xml/bin) -d OUTPUT_PATH/scene.mvs -o OUTPUT_PATH/
```

**Comment by mad-de** [comment]
My standard for Densify mesh is:
"/home/martin-uwh/openMVS_build/bin/DensifyPointCloud -i /home/martin-uwh/meshes/os_coxae_2_out/MVS_out/scene.mvs -w /home/martin-uwh/meshes/os_coxae_2_out/MVS_out/

Best wishes

**Comment by HKUSTmji** [comment]
Thanks for your quick reply. @pmoulon @mad-de 

Dear @pmoulon ,
Yes, you are right. Previously I generate the scene.mvs use `openMVG_main_openMVG2openMVS -i sfm_data.bin -o scene.mvs` which doesn't specify the '-d OUTPUT_PATH'.
The `openMVG_main_openMVG2openMVS -i PATH/sfm_data.(json/xml/bin) -d OUTPUT_PATH -o OUTPUT_PATH/Scene.mvs` generates scene.mvs and all the images in the specified folder.
Latter on, `./DensifyPointCloud /home/mji/libs/ImageDataset_SceauxCastle-master/images/scene.mvs ` works fine with a larger .ply generated. :+1: 

Thanks again

**Comment by pmoulon** [comment]
Impatient to see your resulting reconstruction here or on G+
=> Your remark show that ``openMVG_main_openMVG2openMVS ``` must wait a none empty -d directory string path
