### ISSUE TITLE
Question regarding wrong NCC score

### ISSUE THREAD

**Issue by melhashash** [cdcseacave/openMVS#842]
Hello,

Thanks for open sourcing the project.

I noticed I am getting values larger than 2 for the NCC score.
https://github.com/cdcseacave/openMVS/blob/3b2bb8402c9c38c77b8be27461f95284c60b5d21/libs/MVS/DepthMap.cpp#L754

Could you please elaborate if you faced similar issue before, where should I look at?

**Comment by cdcseacave** [comment]
you should be more specific, like when using CPU or GPU version?
in both cases it is maxed out to 2, so it should not be `return MIN(2.f, score);` and `return max(0.f, min(2.f, ncc));`
you should be able to find out more about from where the problem comes in debug with a little tracking

**Comment by melhashash** [comment]
> you should be more specific, like when using CPU or GPU version? in both cases it is maxed out to 2, so it should not be `return MIN(2.f, score);` and `return max(0.f, min(2.f, ncc));` you should be able to find out more about from where the problem comes in debug with a little tracking

Thanks, it is the CPU version. I will check further and let you know if I find the reason.
