### ISSUE TITLE
the working directory is not used in InterfaceCOLMAP.cpp

### ISSUE THREAD

**Issue by CanCanZeng** [cdcseacave/openMVS#843]
Hi, I find that the `WORKING_FOLDER` variable from command line is not used, is this intended? Maybe change to 

```
if (WORKING_FOLDER.empty())
     WORKING_FOLDER = (File::isFolder(OPT::strInputFileName) ? OPT::strInputFileName : Util::getFilePath(OPT::strInputFileName));
```

will be better?

**Comment by cdcseacave** [comment]
are you sure it is not used?
it is used everywhere in OpenMVS, through the defines like `MAKE_PATH`

**Comment by CanCanZeng** [comment]
Yes, I double checked my suspicion. You over wiritted the variable before using it. There is no this line in other apps file except InterfaceCOLMAP.cpp https://github.com/cdcseacave/openMVS/blob/3b2bb8402c9c38c77b8be27461f95284c60b5d21/apps/InterfaceCOLMAP/InterfaceCOLMAP.cpp#L133 .

**Comment by CanCanZeng** [comment]
Yes, the program runs well if I delete that line https://github.com/cdcseacave/openMVS/blob/3b2bb8402c9c38c77b8be27461f95284c60b5d21/apps/InterfaceCOLMAP/InterfaceCOLMAP.cpp#L133 
(I check on ubuntu16.04, importing and exporting colmap scenes)

**Comment by cdcseacave** [comment]
I can do it, but feel free to make a PR so that you become a constributor

**Comment by CanCanZeng** [comment]
OK, I created a PR just now
