### ISSUE TITLE
query about the algorithm of the module: Dense Point-Cloud Reconstruction

### ISSUE THREAD

**Issue by HKUSTmji** [cdcseacave/openMVS#85]
It says that the module of Dense Point-Cloud Reconstruction follows the algorithm in the paper `PatchMatch: A Randomized Correspondence Algorithm for Structural Image Editing C. Barnes et al. 2009.`. However, in my first glance of this paper, it only states the algorithm for image editing with nothing about point cloud processing.

I really want to have look at the implementation of the module: Dense Point-Cloud Reconstruction. Which paper should I read? Any suggestions please ?

**Comment by ORNis** [comment]
it follows "Accurate Multiple View 3D Reconstruction Using Patch-Based Stereo for Large-Scale Scenes", S. Shen, 2013 for dense matching. The core idea of random initialization and right-left/top-down propagation follows the inpainting paper you cite.
