### ISSUE TITLE
Export the image ID and pose info of each point after densification  

### ISSUE THREAD

**Issue by hwang051785** [cdcseacave/openMVS#852]
Really appreciate the great work of OpenMVS. I have been using openMVG-openMVS pipeline for a while and understand most of the basics. Recently I am working on a project that requires extracting the projected image coordinates [u, v] of each point [X, Y, Z] in the densified point cloud (not just structures from openMVG which can be accessed from the sfm_data.json file) and picking up some features at [u, v] from the corresponding undistorted image, hence the pose info and image ID need to be linked to each point of the densified point cloud. I know the .MVS file is the data container that stores all the relevant information, but I cannot decode it or convert it into any data format that I can further process other than the ply file. 

It is possible to project the 3D coordinates of each point in the "scene_dense.ply" file onto each image coordinate system and determine if the point is inside or not using camera parameters from the "sfm_data.json" and undistorted images, however, I think this path must not be optimal and may "reinvent the wheel" for this purpose. Any more straightforward approaches/workflows are very much appreciated.

**Comment by cdcseacave** [comment]
this question was asked so many times, and the answer is the same: use `Interface.h` and see wiki
