### ISSUE TITLE
TextureMesh Command did not generate a new "_texture_mesh.ply" file

### ISSUE THREAD

**Issue by citystrawman** [cdcseacave/openMVS#858]
**Describe the bug**
I followed this [tutorial ](https://openmvg.readthedocs.io/en/latest/software/MVS/OpenMVS/) to learn how to generate a textured mesh. 
![image](https://user-images.githubusercontent.com/9004748/189078517-3ded2614-0f22-4700-81b9-c2d8db760e79.png)

Dense point-cloud reconstruction and Mesh reconstruction are both OK. But when I ran `TextureMesh scene_dense_mesh.mvs` I can only get scene_dense_mesh_texture_mesh.png and scene_dense_mesh_texture_mesh.mvs. I think the command should also generate a scene_dense_mesh_texture_mesh.ply file but it did not.

Then I guess I should run `ReconstructMesh scene_dense_mesh.mvs` because this command could generate a scene_dense_mesh_texture_mesh.ply file.

It did generate a scene_dense_mesh_texture_mesh.ply file, but when I opened it in meshlab, the texture seems not correct:
![image](https://user-images.githubusercontent.com/9004748/189079826-a9f6a4c2-caf4-4067-9f99-4cf10a4ec9dc.png)
As you can see. 

But the texture mapping png looks OK:
![image](https://user-images.githubusercontent.com/9004748/189080219-1a59c66b-39d7-462e-abb1-2e00509f2099.png)

**Comment by cdcseacave** [comment]
can you pls try something else, maybe Meshlab has an issue?

**Comment by citystrawman** [comment]
> can you pls try something else, maybe Meshlab has an issue?

I tried windows 3D viewer and blender, neither of them show texture image.  (I am not familiar with these software) Do you know any software supports .ply with texture image?

**Comment by citystrawman** [comment]
> can you pls try something else, maybe Meshlab has an issue?

after a quick search, I found a way to add texture in blender from [here](https://all3dp.com/2/blender-how-to-add-a-texture/). but the result was obviously not correct:

![image](https://user-images.githubusercontent.com/9004748/189156944-5187ff76-0558-4d82-96a9-5e7902be8805.png)

**Comment by cdcseacave** [comment]
can u pls share the mesh?

**Comment by cdcseacave** [comment]
it works for me; pls use the GLB, I do not know how you generated the PLY, but you did something wrong in the conversion
![image](https://user-images.githubusercontent.com/2802670/189165946-d6727f72-4653-4755-a50c-6277384fec4a.png)

**Comment by citystrawman** [comment]
> it works for me; pls use the GLB, I do not know how you generated the PLY, but you did something wrong in the conversion ![image](https://user-images.githubusercontent.com/2802670/189165946-d6727f72-4653-4755-a50c-6277384fec4a.png)

I did not find a tutorial for using glb. Could you give me a link?
