### ISSUE TITLE
DensifyPointCloud virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.

### ISSUE THREAD

**Issue by vip96300** [cdcseacave/openMVS#869]
using openmvs and openmvs as third party
i copy openmvg and openmvs pipleline to my project,but has problem in DensifyPointCloud.cpp
virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.

debug in DensifyPointCloud.cpp scene.DenseReconstruction(OPT::nFusionMode)
error in MVS/Common/File.h Line 484

Command Line Console:

16:12:22 [App     ] Build date: Aug 31 2022, 16:19:44
16:12:22 [App     ] CPU: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 cores)
16:12:22 [App     ] RAM: 31.32GB Physical Memory 2.00GB Virtual Memory
16:12:22 [App     ] OS: Linux 5.15.0-48-generic (x86_64)
16:12:22 [App     ] Disk: 241.81GB (293.73GB) space
16:12:22 [App     ] SSE & AVX compatible CPU & OS detected
16:12:22 [App     ] Command line: DensifyPointCloud -i /home/huanghongfei/workspace/reconstruction/reconstruction_sequential/scene.mvs -o /home/huanghongfei/workspace/reconstruction/reconstruction_sequential/scene_dense.mvs -w /home/huanghongfei/workspace/reconstruction/reconstruction_sequential
16:12:22 [App     ] Camera model loaded: platform 0; camera  0; f 1.294x1.294; poses 18
16:12:22 [App     ] Image loaded   0: DSC_0333.JPG
16:12:22 [App     ] Image loaded   1: DSC_0334.JPG
16:12:22 [App     ] Image loaded   2: DSC_0335.JPG
16:12:22 [App     ] Image loaded   3: DSC_0336.JPG
16:12:22 [App     ] Image loaded   4: DSC_0337.JPG
16:12:22 [App     ] Image loaded   5: DSC_0338.JPG
16:12:22 [App     ] Image loaded   6: DSC_0339.JPG
16:12:22 [App     ] Image loaded   7: DSC_0340.JPG
16:12:22 [App     ] Image loaded   8: DSC_0341.JPG
16:12:22 [App     ] Image loaded   9: DSC_0342.JPG
16:12:22 [App     ] Image loaded  10: DSC_0343.JPG
16:12:22 [App     ] Image loaded  11: DSC_0344.JPG
16:12:22 [App     ] Image loaded  12: DSC_0345.JPG
16:12:22 [App     ] Image loaded  13: DSC_0346.JPG
16:12:22 [App     ] Image loaded  14: DSC_0347.JPG
16:12:22 [App     ] Image loaded  15: DSC_0348.JPG
16:12:22 [App     ] Image loaded  16: DSC_0349.JPG
16:12:22 [App     ] Image loaded  17: DSC_0350.JPG
16:12:22 [App     ] Scene loaded from interface format (20ms):
        18 images (18 calibrated) with a total of 43.07 MPixels (2.39 MPixels/image)
        13129 points, 0 vertices, 0 faces
simulation: /usr/local/include/OpenMVS/Common/File.h:484: virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.
simulation: /usr/local/include/OpenMVS/Common/File.h:484: virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.
simulation: /usr/local/include/OpenMVS/Common/File.h:484: virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.
simulation: /usr/local/include/OpenMVS/Common/File.h:484: virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.
simulation: /usr/local/include/OpenMVS/Common/File.h:484: virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.
simulation: /usr/local/include/OpenMVS/Common/File.h:484: virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.
simulation: /usr/local/include/OpenMVS/Common/File.h:484: virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.
simulation: /usr/local/include/OpenMVS/Common/File.h:484: virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.
simulation: /usr/local/include/OpenMVS/Common/File.h:484: virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.
simulation: /usr/local/include/OpenMVS/Common/File.h:484: virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.
simulation: /usr/local/include/OpenMVS/Common/File.h:484: virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.
simulation: /usr/local/include/OpenMVS/Common/File.h:484: virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.
simulation: /usr/local/include/OpenMVS/Common/File.h:484: virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.
simulation: /usr/local/include/OpenMVS/Common/File.h:484: virtual size_t SEACAVE::File::read(void*, size_t): Assertion `"FILE::read() break" == __null' failed.

i confirmed the images is exists
why?

**Comment by cdcseacave** [comment]
I do not know, debug dataset?

**Comment by vip96300** [comment]
thank you reply,i try eidt path to openMVS source code
the are work,i can't understand

int main_DensifyPointCloud(int argc, LPCTSTR* argv);

int main(){
	int argc=7;
	LPCTSTR argv[argc]={
		"the program",
		"-i","/home/huanghongfei/workspace/reconstruction/reconstruction_sequential/scene.mvs",
		"-o","/home/huanghongfei/workspace/reconstruction/reconstruction_sequential/scene_dense.mvs",
		"-w","/home/huanghongfei/workspace/reconstruction/reconstruction_sequential"
		};
	return main_DensifyPointCloud(argc,argv);
}

int main_DensifyPointCloud(int argc, LPCTSTR* argv)

**Comment by cdcseacave** [comment]
if you set `-w` you can supply only the file name for the others:
```
DensifyPointCloud -i scene.mvs -o scene_dense.mvs -w /home/huanghongfei/workspace/reconstruction/reconstruction_sequential
```

**Comment by vip96300** [comment]
> if you set `-w` you can supply only the file name for the others:
> 
> ```
> DensifyPointCloud -i scene.mvs -o scene_dense.mvs -w /home/huanghongfei/workspace/reconstruction/reconstruction_sequential
> ```

if not set -w,the work folder in my project/build dictionary,the can't work
