### ISSUE TITLE
CERES CMake script suggested changes

### ISSUE THREAD

**Issue by KevinCain** [cdcseacave/openMVS#87]
For Ceres >= 1.8, OpenMVS should adapt FindCERES.cmake script, according to Alex in the Ceres Google Group (see:  https://groups.google.com/forum/#!topic/ceres-solver/VbiqrQK3FNo):

The following changes are in my fork of OpenMVS (https://github.com/KevinCain/openMVS/tree/master); I will issue a pull request if useful:

1) Remove build/Modules/FindCERES.cmake

https://github.com/cdcseacave/openMVS/blob/d062feb7e3cfb6eddd88cd0ef4a411c752259673/build/Modules/FindCERES.cmake

2) Replace lines 15-19 here:

https://github.com/cdcseacave/openMVS/blob/9d67937336a6ab6fe081fcba40b3dfc6d1eb9a7a/libs/MVS/CMakeLists.txt#L15-L19

with this:

find_package(Ceres)
if (Ceres_FOUND)
   include_directories( ${CERES_INCLUDE_DIRS} )
endif()

3) Replace line 40 here:

https://github.com/cdcseacave/openMVS/blob/9d67937336a6ab6fe081fcba40b3dfc6d1eb9a7a/libs/MVS/CMakeLists.txt#L40

with this:

target_link_libraries(MVS Common Math IO ${CERES_LIBRARIES} ${CGAL_LIBS} ${CUDA_LIBRARIES})

**Comment by cdcseacave** [comment]
Thank you for the pull request, but could you please tell me what is the purpose? The current version is not working?

**Comment by pmoulon** [comment]
I'm agree with @KevinCain It would be better to use the ceres installed cmake script.
Less cmake code in OpenMVS ;-) and it delegate the ceres cmake config.

**Comment by KevinCain** [comment]
While mostly benign, there are corner cases where the current OpenMVS CMake
code was actually interfering with the build, as noted.  The few changes in
my pull request mostly reflect suggestions from the CMake Google Group.

Thanks,

-Kevin

**Comment by ORNis** [comment]
I personally agree with this change too, if it my opinion matters.

**Comment by cdcseacave** [comment]
I'd agree with this changes too if they work... that reality is that they do not work, I tried this several weeks ago. Did any of you tried the suggested changes on Windows? The current CERES script should not affect in any way the linux system, but should simplify the process on Windows, where building CERES is difficult and often the default settings are not enough. This is my experience at least, so if you find a good way to build CERES on windows that works with the default script, I am more than happy to remove it.

**Comment by KevinCain** [comment]
Excellent point, I did not try this on Windows.

-Kevin

**Comment by pmoulon** [comment]
Using -DCeres_DIR that point to the "ceres_install_path/share/Ceres/" should work on all platform for local install

**Comment by cdcseacave** [comment]
@pmoulon that works, my point in the previous post was different though

**Comment by clercj** [comment]
Hello, 

I tested the changes proposed by @KevinCain , but for me (on MacOS), it doesn't seem to work. That's what I get after compiling: 

```
-- Eigen 3.2.9 found (include: /usr/local/include/eigen3)
-- OpenCV 2.4.13 found (include: /usr/local/include/opencv;/usr/local/include)
-- CGAL 4.7 found (include: /usr/local/Cellar/cgal/4.7/include)
-- VCG  found (include: /Users/jonasclerc/vcglib)
CMake Error at /usr/local/share/Ceres/CeresConfig.cmake:88 (message):
  Failed to find Ceres - Found Eigen dependency, but the version of Eigen
  found (3.2.9) does not exactly match the version of Eigen Ceres was
  compiled with (3.2.8).  This can cause subtle bugs by triggering violations
  of the One Definition Rule.  See the Wikipedia article
  http://en.wikipedia.org/wiki/One_Definition_Rule for more details
Call Stack (most recent call first):
  /usr/local/share/Ceres/CeresConfig.cmake:204 (ceres_report_not_found)
  libs/MVS/CMakeLists.txt:15 (find_package)


CMake Warning at libs/MVS/CMakeLists.txt:15 (find_package):
  Found package configuration file:

    /usr/local/share/Ceres/CeresConfig.cmake

  but it set Ceres_FOUND to FALSE so package "Ceres" is considered to be NOT
  FOUND.
```

Have someone an idea how to resolve it?

**Comment by Minipada** [comment]
@clercj I have the same issue on a different repo, did you manage to solve it? Thanks!
