### ISSUE TITLE
Possible texture bug in TRWS view selection?

### ISSUE THREAD

**Issue by humanbeingZ** [cdcseacave/openMVS#879]
**Describe the bug**
When using TRWS as TEXOPT_INFERNCE algorithm, `TextureMesh` crashes.

**To Reproduce**
1. change [this line](https://github.com/cdcseacave/openMVS/blob/master/libs/MVS/SceneTexture.cpp#L67) to `#define TEXOPT_INFERENCE TEXOPT_INFERENCE_TRWS`
2. recompile
3. run the program
4. the program crashes (Aborted)

**Expected behavior**
successful execution.

**Additional context**
After debugging, I found out that after view selection, some faces might be labeled with views not considered visible.
I dug more and found all views are given as labels in [this line](https://github.com/cdcseacave/openMVS/blob/master/libs/MVS/SceneTexture.cpp#L946).  
While invisible views' data cost are `MaxEnergy`, so are edge costs in Potts model ([this line](https://github.com/cdcseacave/openMVS/blob/master/libs/MVS/SceneTexture.cpp#L107)). 

If I'm not mistaken, for a simple case like the following graph  
(Two connected nodes, with `MaxEnergy=1`.  
Label 0 is invisible to A and label 1 invisible to B.)
```
               Node A    Node B
label 0 cost     0.1       1
label 1 cost      1       0.1
```
With energy term given above, I guess the algorithm would simply choose label 0 (or 1) for both nodes? I'm not sure about my understanding though, and thanks in advance for your help!

**Comment by humanbeingZ** [comment]
IMHO, invisible views should be given a much larger data costs (at least larger than 3 times the edge costs in Potts model, as 3 is the degree of each triangle face).

**Comment by cdcseacave** [comment]
Please propose a fix in a new pull request

**Comment by humanbeingZ** [comment]
Done! Thanks for your quick reply!
