### ISSUE TITLE
why there is not a lib released in win64,just apps in release?

### ISSUE THREAD

**Issue by Yes-Jumby** [cdcseacave/openMVS#882]
I want to use openmvs as a lib,but it is confued to get it built,so could there can be a prebuild lib in release?
[i want a prebuild libs ,but there is only apps in release]

**Comment by monschine** [comment]
For windows you can download them already compiled [here](https://github.com/cdcseacave/openMVS/releases/tag/v2.0.1)

**Comment by Yes-Jumby** [comment]
> For windows you can download them already compiled [here](https://github.com/cdcseacave/openMVS/releases/tag/v2.0.1)

i want a prebuild libs ,but there is only apps in release

**Comment by Yes-Jumby** [comment]
i have complied it from source anyway
