### ISSUE TITLE
Adding non-manifold repairing

### ISSUE THREAD

**Issue by xqyd** [cdcseacave/openMVS#885]
Thanks again for your wonderful work!
After generating the textured mesh, I've realized sometimes, the output is non manifold. I've seen your request at https://github.com/pmp-library/pmp-library/issues/9, so I was wondering if this feature has already been added to the latest OpenMVS. And if so, how to use it? Many thanks!!!

**Comment by cdcseacave** [comment]
mesh has a function `FixNonManifold()`, though I never saw a case when the input mesh to texturing is manifold and the output is not, can you provide such an example?

**Comment by xqyd** [comment]
Yeah, I was playing Open3d for using its cluster_connected_triangles funtion to remove small clusters(like the background scene). When the final output is in .obj format, it fails. However, if output file is in .ply file, it works just fine. So it is not a problem anymore at my side.
