### ISSUE TITLE
using COLMAP's dense point cloud visibility file

### ISSUE THREAD

**Issue by CanCanZeng** [cdcseacave/openMVS#887]
I find that openMVS import the point visibility info from fused.ply.vis file, it is very confusing that the meaning of the observation view id is not we thought, it is an index of image instead of ID. In most cases, the index of image is the same with image ID, but not always. If some image has no 3D point, then in undistortion stage this image will be ignored, then the index of images followed will not be equal to it's ID.

There is no easy way to check this, I find this just because I'm more familiar with the source code of COLMAP and I find some odd phenomenon when I trying to use the covisibilty info of the dense point cloud.

You can read this function https://github.com/colmap/colmap/blob/87b3aa325bd8e5fb913788e29e9ac1e085e28b67/src/mvs/model.cc#L56 , the MVS module of COLMAP defined a new `image` class, and this class has no ID, we need a mapping table to convert index to ID.

**Comment by cdcseacave** [comment]
as far as I remember that mapping is done during openMVS import; if you found a problem with that mapping pls propose a fix

**Comment by CanCanZeng** [comment]
It seems you have a very good memory! I gone through the importing code, you did a mapping from image ID to image index, so  there should not be problem. I will check my code again, thank you very much for your quick reply!
