### ISSUE TITLE
Compiling OpenMVS results in Eigen and VCG errors 

### ISSUE THREAD

**Issue by KevinCain** [cdcseacave/openMVS#89]
I have no trouble compiling OpenMVG, but OpenMVS is proving more difficult on my system.  Following the installation notes on the wiki (https://github.com/cdcseacave/openMVS/wiki/Building), I can successfully proceed through the CMake configuration and generation, but am seeing Eigen and VCG errors when launching make, as shown in the same errors below.

My system is running Ubuntu 16.04, GCC 503, Eigen 3.2.92, VCG SVN revision 5718 (current).

Any advice?

---

/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:811:30**: error: invalid use of incomplete type** ‘struct Eigen::internal::enable_if<false, SEACAVE::TPoint3<float> >’
In file included from /usr/include/eigen3/Eigen/Core:295:0,
                 from /home/kevin/openMVS/libs/MVS/../Common/Types.h:114,
                 from /home/kevin/openMVS/libs/MVS/../Common/Common.h:176,
                 from /home/kevin/openMVS/libs/MVS/Common.h:42,
                 from /home/kevin/openMVS_build/libs/MVS/cotire/MVS_CXX_prefix.cxx:4,
                 from /home/kevin/openMVS_build/libs/MVS/cotire/MVS_CXX_prefix.hxx:4:

usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:822:30: e**rror: invalid use of incomplete type** ‘struct Eigen::internal::enable_if<false, SEACAVE::TPoint3<float>*>’
In file included from /usr/include/eigen3/Eigen/Core:295:0,
                 from /home/kevin/openMVS/libs/MVS/../Common/Types.h:114,
                 from /home/kevin/openMVS/libs/MVS/../Common/Common.h:176,
                 from /home/kevin/openMVS/libs/MVS/Common.h:42,
                 from /home/kevin/openMVS_build/libs/MVS/cotire/MVS_CXX_prefix.cxx:4,
                 from /home/kevin/openMVS_build/libs/MVS/cotire/MVS_CXX_prefix.hxx:4:

/home/kevin/vcglib/vcg/math/base.h:199:51: **error: ‘isnan’ was not declared in this scope**, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
 template<class T> int IsNAN(T t) {    return isnan(t) || isinf(t); }

/home/kevin/vcglib/vcg/math/base.h:199:63: **error: ‘isinf’ was not declared in this scope**, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
 template<class T> int IsNAN(T t) {    return isnan(t) || isinf(t); }

**Comment by cdcseacave** [comment]
please use stable Eigen release... as far as I know, the last stable release is 3.2.8

**Comment by KevinCain** [comment]
Good point, I'll revert to Eigen 3.2.8.  Do you feel the VCG errors are connected or separate?

**Comment by KevinCain** [comment]
As @cdcseacave suggested, I reverted to Eigen 3.2.8 in order to compile OpenMVS.  (I was previously using Eigen 3.2.9, which is shipped with Ubuntu 16.04.).  I then compiled a sample program using Eigen headers, to check that gcc can see the 'new' Eigen.

I then rebuilt Ceres with Eigen 3.2.8, which went fine.

OpenMVS still won't compile for me, as Cotire libs were calling for Eigen header files that I don't have in Eigen 3.2.8, as highlighted below:

> make[2]: *** No rule to make target '/usr/include/eigen3/Eigen/src/Core/**AssignEvaluator.h**', needed by 'libs/Common/cotire/Common_CXX_prefix.hxx.gch'.  Stop.
> CMakeFiles/Makefile2:147: recipe for target 'libs/Common/CMakeFiles/Common.dir/all' failed
> make[1]: *** [libs/Common/CMakeFiles/Common.dir/all] Error 2
> Makefile:116: recipe for target 'all' failed

Following advice from @pmoulon, I deleted the ‘CMakeCache.txt’ CMake configuration file for OpenMVS, launched the CMake GUI, configured and generated a new ‘CMakeCache.txt’ file.

Still no luck.  Any advice?

**Comment by cdcseacave** [comment]
I have just tested, openMVS compiles fine with eigen 3.2.8 on ubuntu 16.04 with no customizations

**Comment by KevinCain** [comment]
@cdcseacave reported success with compiling OpenMVS on Ubuntu 16.04.  I attempted to duplicate, using these lines from the [wiki:](https://github.com/cdcseacave/openMVS/wiki/Building) verbatim, excerpted below:

```
git clone https://github.com/cdcseacave/openMVS.git openMVS
mkdir openMVS_build && cd openMVS_build
cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="$main_path/vcglib"
```

The above halts when CMake mistakenly concludes that Eigen was compiled with Eigen 3.2.2, not Eigen 3.2.8, which Ceres both found and logged during compilation.  The error:

> CMake Error at /usr/local/share/Ceres/CeresConfig.cmake:88 (message):
>   Failed to find Ceres - Found Eigen dependency, but the version of Eigen
>   found (3.2.8) does not exactly match the version of Eigen Ceres was
>   compiled with (3.2.2).  This can cause subtle bugs by triggering violations
>   of the One Definition Rule.

The Ceres Google group diagnosed the cause in [this thread](https://groups.google.com/forum/#!topic/ceres-solver/VbiqrQK3FNo).

I compiled from scratch from my fork of OpenMVS, with the minor changes suggested in the above thread:

```
git clone https://github.com/KevinCain/openMVS.git
mkdir openMVS_build && cd openMVS_build
cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="$main_path/vcglib"
```

This clears CMake, resolving the phantom version conflict with the OpenMVS Ceres install code.  CMake also correctly finds the Eigen 3.2.8 dependency for Ceres.

However, the make step still halts with the errors I opened this thread with, e.g.:

> /home/kevin/vcglib/vcg/math/base.h:199:51: **error: ‘isnan’ was not declared in this scope**, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
>  template<class T> int IsNAN(T t) {    return isnan(t) || isinf(t); }

                                                   ^

**Comment by KevinCain** [comment]
Below are a list of the problems (and solutions) I found when building OpenMVS using the wiki instructions:  https://github.com/cdcseacave/openMVS/wiki/Building.

The notes below assume Ubuntu 16.04, GCC 503 with CUDA 7.5.  See also my OpenMVS bug report:  https://github.com/cdcseacave/openMVS/issues/87.

**Problem A:  VCG not found**
Make Error at build/Utils.cmake:214 (message):
VCG required, but not found: Please specify VCG directory using VCG_ROOT

_Solution:  pass ‘~/vcglib’ to OpenMVS_ as per:  https://github.com/cdcseacave/openMVS/issues/46

E.g.: when invoking CMake in the OpenMVS build directory, use:
cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="~/vcglib"
...rather than the suggested invocation from the OpenMVS wiki:
cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="$main_path/vcglib"

**Problem B:  Ceres’ Eigen dependency**

Found Eigen dependency, but the version of Eigen found (3.2.5) does not exactly match the version of Eigen Ceres was compiled with (3.2.2).  This can cause subtle bugs by triggering violations of the One Definition Rule.

_Solution:  I forked MVS (https://github.com/KevinCain/openMVS.git), making the edits suggested here_:
https://groups.google.com/forum/#!topic/ceres-solver/VbiqrQK3FNo

Note:  compile Ceres against Eigen 3.2.5, from scratch, as per:
http://ceres-solver.org/building.html

Perhaps another option is to set EIGEN_INCLUDE_DIR_HINTS=/usr/include as per Pierre Moulon’s suggestion here:  https://github.com/cdcseacave/openMVS/issues/73

To downgrade Eigen version:  “you just need to download and extract Eigen's source code (see the wiki for download instructions). In fact, the header files in the Eigen subdirectory are the only files required to compile programs using Eigen. The header files are the same for all platforms. It is not necessary to use CMake or install anything.  On Linux or Mac OS X, another option is to symlink or copy the Eigen folder into /usr/local/include/:”

**Problem C:  Failed to find CGAL**

_Solution:  to clear the CGAL CMake installation, I found I needed to also install ‘libcgal-qt5-dev’ _(as per: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804539)

I didn’t see CUDA as a dependency, but got ‘CUDA_TOOLKIT_ROOT_DIR not found or specified’ so I installed nvidia-cuda-dev and, for good measure nvidia-cuda-dev as per.

**Problem D:  CUDA related errors**

_Solution:  in the CMake GUI, I flagged the OpenMVS_USE_CUDA to OFF _as per cdseacave:  https://github.com/cdcseacave/openMVS/issues/86

**Problem E:  VCG errors
**
error: ‘isinf’ was not declared in this scope
error: ‘isnan’ was not declared in this scope

_Solution: In ‘/vcglib/vcg/math/base.h’ [199], I made trivial changes_ from:
template<class T> int IsNAN(T t) {    return isnan(t) || isinf(t); }
to:
template<class T> int IsNAN(T t) {    return std::isnan(t) || std::isinf(t); }

Following advice from Pierre Moulon, I deleted the ‘CMakeCache.txt’ CMake configuration file, launched the CMake GUI, configured and generated a new ‘CMakeCache.txt’ file.

To downgrade Eigen version:  “you just need to download and extract Eigen's source code (see the wiki for download instructions). In fact, the header files in the Eigen subdirectory are the only files required to compile programs using Eigen. The header files are the same for all platforms. It is not necessary to use CMake or install anything.  On Linux or Mac OS X, another option is to symlink or copy the Eigen folder into /usr/local/include/" (https://eigen.tuxfamily.org/dox/GettingStarted.html)

**Comment by jpwhitney** [comment]
Thanks @KevinCain.  Using your instructions found here I was able to successfully compile and install openMVS.
@cdcseacave perhaps you could consider adding these instructions to the build directions.
