### ISSUE TITLE
Is roi trimming good to go?

### ISSUE THREAD

**Issue by xqyd** [cdcseacave/openMVS#893]
Thanks for the great job!
I was running DensifyPointCloud with the code from https://github.com/cdcseacave/openMVS/tree/develop. And it looks like the EstimateROI is working. But after that, the program failed to pass ASSERT(viewRef.image.size() == depthData.depthMap.size()); The size of these two are not the same. So I was wondering, is roi trimming already good to go?

**Comment by xqyd** [comment]
It turns out this problem only happens under debug mode.

**Comment by nnop** [comment]
Met the same problem. Have you solved it?
