### ISSUE TITLE
Windows compile error with CUDA, eigen cannot match function definition with existing declaration

### ISSUE THREAD

**Issue by zmf2022** [cdcseacave/openMVS#895]
Os：Windows10
complie: vs2019
Cuda Version：11.1

**Comment by zmf2022** [comment]
![捕获](https://user-images.githubusercontent.com/35084983/197163144-dc8e93bc-bc43-4ca7-932c-f4aa9ad638ba.PNG)

**Comment by cdcseacave** [comment]
what Eigen version?

**Comment by zmf2022** [comment]
> what Eigen version?

3.4.0

**Comment by zmf2022** [comment]
I update the CUDA version to 11.6, and the problem disappears.

**Comment by sgtimea** [comment]
> 
我也遇到一样的报错，请问下是更新cuda后vs重新生成就行了，还是整个都要重新安装？

**Comment by zmf2022** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，已收到您的邮件，将尽快给您回复！

**Comment by sgtimea** [comment]
> I update the CUDA version to 11.6, and the problem disappears.

it does work,thanks
