### ISSUE TITLE
memleak in Octree.inl:233   	   m_root.m_child = new CELL_TYPE[CELL_TYPE::numChildren];        # openMVS-2.0.1

### ISSUE THREAD

**Issue by BrentHuang** [cdcseacave/openMVS#896]
**Describe the bug**
A clear and concise description of what the bug is. Use `Viewer` to verify/display the input/output.

==4368== 200 bytes in 1 blocks are definitely lost in loss record 27 of 40
==4368==    at 0x4C34A2F: operator new[](unsigned long) (vg_replace_malloc.c:640)
==4368==    by 0x270A97: Insert<MVS::Mesh::FacesInserter::CreateOctree(MVS::Mesh::Octree&, const MVS::Mesh&)::<lambda(SEACAVE::TOctree<SEACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::IDX_TYPE, SEACAVE::TOctree<S
EACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::Type)> > (Octree.inl:233)
==4368==    by 0x270A97: Insert<MVS::Mesh::FacesInserter::CreateOctree(MVS::Mesh::Octree&, const MVS::Mesh&)::<lambda(SEACAVE::TOctree<SEACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::IDX_TYPE, SEACAVE::TOctree<S
EACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::Type)> > (Octree.inl:251)
==4368==    by 0x270A97: CreateOctree (Mesh.h:101)
==4368==    by 0x270A97: MeshRefine::ListCameraFaces() (SceneRefine.cpp:417)
==4368==    by 0x272E74: MeshRefine::SubdivideMesh(unsigned int, float, unsigned int, unsigned int) (SceneRefine.cpp:506)
==4368==    by 0x27370E: MVS::Scene::RefineMesh(unsigned int, unsigned int, unsigned int, float, unsigned int, unsigned int, unsigned int, unsigned int, float, unsigned int, unsigned int, float, float, float, float) (SceneRefine.cpp:1305)
==4368==    by 0x159103: main (RefineMesh.cpp:251)

==4368== 600 bytes in 3 blocks are definitely lost in loss record 34 of 40
==4368==    at 0x4C34A2F: operator new[](unsigned long) (vg_replace_malloc.c:640)
==4368==    by 0x270A97: Insert<MVS::Mesh::FacesInserter::CreateOctree(MVS::Mesh::Octree&, const MVS::Mesh&)::<lambda(SEACAVE::TOctree<SEACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::IDX_TYPE, SEACAVE::TOctree<S
EACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::Type)> > (Octree.inl:233)
==4368==    by 0x270A97: Insert<MVS::Mesh::FacesInserter::CreateOctree(MVS::Mesh::Octree&, const MVS::Mesh&)::<lambda(SEACAVE::TOctree<SEACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::IDX_TYPE, SEACAVE::TOctree<S
EACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::Type)> > (Octree.inl:251)
==4368==    by 0x270A97: CreateOctree (Mesh.h:101)
==4368==    by 0x270A97: MeshRefine::ListCameraFaces() (SceneRefine.cpp:417)
==4368==    by 0x272834: MeshRefine::SubdivideMesh(unsigned int, float, unsigned int, unsigned int) (SceneRefine.cpp:539)
==4368==    by 0x27370E: MVS::Scene::RefineMesh(unsigned int, unsigned int, unsigned int, float, unsigned int, unsigned int, unsigned int, unsigned int, float, unsigned int, unsigned int, float, float, float, float) (SceneRefine.cpp:1305)
==4368==    by 0x159103: main (RefineMesh.cpp:251)

==4368== 16,400 bytes in 82 blocks are definitely lost in loss record 40 of 40
==4368==    at 0x4C34A2F: operator new[](unsigned long) (vg_replace_malloc.c:640)
==4368==    by 0x270A97: Insert<MVS::Mesh::FacesInserter::CreateOctree(MVS::Mesh::Octree&, const MVS::Mesh&)::<lambda(SEACAVE::TOctree<SEACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::IDX_TYPE, SEACAVE::TOctree<S
EACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::Type)> > (Octree.inl:233)
==4368==    by 0x270A97: Insert<MVS::Mesh::FacesInserter::CreateOctree(MVS::Mesh::Octree&, const MVS::Mesh&)::<lambda(SEACAVE::TOctree<SEACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::IDX_TYPE, SEACAVE::TOctree<S
EACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::Type)> > (Octree.inl:251)
==4368==    by 0x270A97: CreateOctree (Mesh.h:101)
==4368==    by 0x270A97: MeshRefine::ListCameraFaces() (SceneRefine.cpp:417)
==4368==    by 0x271198: MeshRefine::ScoreMesh(double*) (SceneRefine.cpp:578)
==4368==    by 0x2740F5: MVS::Scene::RefineMesh(unsigned int, unsigned int, unsigned int, float, unsigned int, unsigned int, unsigned int, unsigned int, float, unsigned int, unsigned int, float, float, float, float) (SceneRefine.cpp:1375)
==4368==    by 0x159103: main (RefineMesh.cpp:251)

==24734== 200 bytes in 1 blocks are definitely lost in loss record 30 of 46
==24734==    at 0x4C34A2F: operator new[](unsigned long) (vg_replace_malloc.c:640)
==24734==    by 0x281FDF: Insert<MVS::Mesh::FacesInserter::CreateOctree(MVS::Mesh::Octree&, const MVS::Mesh&)::<lambda(SEACAVE::TOctree<SEACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::IDX_TYPE, SEACAVE::TOctree<
SEACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::Type)> > (Octree.inl:233)
==24734==    by 0x281FDF: Insert<MVS::Mesh::FacesInserter::CreateOctree(MVS::Mesh::Octree&, const MVS::Mesh&)::<lambda(SEACAVE::TOctree<SEACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::IDX_TYPE, SEACAVE::TOctree<
SEACAVE::cList<SEACAVE::TPoint3<float>, const SEACAVE::TPoint3<float>&, 0, 8192, unsigned int>, float, 3>::Type)> > (Octree.inl:251)
==24734==    by 0x281FDF: CreateOctree (Mesh.h:101)
==24734==    by 0x281FDF: MeshTexture::ListCameraFaces(SEACAVE::cList<SEACAVE::cList<MeshTexture::FaceData, MeshTexture::FaceData const&, 0, 8, unsigned int>, SEACAVE::cList<MeshTexture::FaceData, MeshTexture::FaceData const&, 0, 8, unsigned int> const&, 2, 1024, unsign
ed int>&, float, SEACAVE::cList<unsigned int, unsigned int, 0, 16, unsigned int> const&) (SceneTexture.cpp:478)
==24734==    by 0x2828FD: MeshTexture::FaceViewSelection(float, float, SEACAVE::cList<unsigned int, unsigned int, 0, 16, unsigned int> const&) (SceneTexture.cpp:817)
==24734==    by 0x2846D8: MVS::Scene::TextureMesh(unsigned int, unsigned int, float, float, bool, bool, unsigned int, unsigned int, SEACAVE::TPixel<unsigned char>, SEACAVE::cList<unsigned int, unsigned int, 0, 16, unsigned int> const&) (SceneTexture.cpp:1926)
==24734==    by 0x14BE2F: main (TextureMesh.cpp:304)

 - OS: 
 photo@photo-virtual-machine:~/new_disk/workspace/photoscan/MVG_MVS_tutorial_demo/tutorialUserData$ cat /etc/issue
Ubuntu 18.04.6 LTS \n \l

photo@photo-virtual-machine:~/new_disk/workspace/photoscan/MVG_MVS_tutorial_demo/tutorialUserData$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

photo@photo-virtual-machine:~/new_disk/workspace/photoscan/MVG_MVS_tutorial_demo/tutorialUserData$ g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 - Version:
 openMVS-2.0.1

**Comment by cdcseacave** [comment]
Can you pls propose a fix in a PR? Thank you!

**Comment by BrentHuang** [comment]
ok
