### ISSUE TITLE
Unsigned integer overflow when using one picture to texture scene

### ISSUE THREAD

**Issue by Tang2333** [cdcseacave/openMVS#900]
When using one picture to test texture a scene, I found a problem out of bounds. Then  I located that the root cause of the problem was unsigned integer overflow.
Here is the line:
https://github.com/cdcseacave/openMVS/blob/1d3df169e565dd3f751ccb94b2a20d42f566f813/libs/MVS/SceneTexture.cpp#L1819

If you think this is a problem, please assign the bug to me. I'm a newcomer of github, I need a issue to practise submitting a PR. Thanks.

**Comment by cdcseacave** [comment]
I agree, this is not nice code, and can be a problem if you have a mesh that is divided in just one patch (which should never happen for normal scans); I'll add a check at some point

BTW, how do you test with one image? You need at least 2 images to be able to recover depth
