### ISSUE TITLE
SFM report about the views and pose

### ISSUE THREAD

**Issue by Dratlan** [cdcseacave/openMVS#901]
![1667914119256](https://user-images.githubusercontent.com/35300160/200577260-1ff846b9-0518-4522-bfe9-330aa476edcd.jpg)
As is shown in the picture, I used 10 image to bulid a 3D face model(maybe too little?), the view indicates the number of the images. I wonder to know when(or where) the poses are estimated? Are there some options to change it? By the way I got a bug, when I run it on different PC(both windows), the pose number is different. Can you give me some suggeestions?

**Comment by cdcseacave** [comment]
this is OpenMVG related, pls report it there
as a fist advice, pls use not only more pictures, but better quality photos: good lighting, high resolution, sharp, etc
you got very few point per image, which is clearly a problem with the input photos

**Comment by Dratlan** [comment]
Thanks for your suggestions. I do got very few point per image, but the result on my parterner's PC is different from mine. He got better point per image than I do, I'm wondering this is why? Thanks for your reply again, I'll report my question there.
