### ISSUE TITLE
Coordinate system of the output scene of DensifyPointCloud

### ISSUE THREAD

**Issue by tormentliang** [cdcseacave/openMVS#902]
**Is your feature request related to a problem? Please describe.**
I have a sparse scene reconstructed by COLMAP, with corresponding points and camera poses exported. I am trying to densely reconstruct the scene by OpenMVS, and further fine-tune the reconstructed mesh and material by differentiable rendering.

The problem I caught is after DensifyPointCloud, the coordinate system of the scene  (exported as a .ply) seems to have changed. It means that I cannot use the camera poses exported by COLMAP as the camera pose for differentiable rendering. I had to do something like ICP or convex hull fitting to fit the transform between the imported COLMAP sparse scene and the DensifyPointCloud output.

**Describe the solution you'd like**
A command line option that exports the transformation matrix between the COLMAP sparse scene and the DensifyPointCloud output.

**Describe alternatives you've considered**
Or... Something like exporting the equivalent camera poses in the DensifyPointCloud output.

**Additional context**
None.

**Comment by cdcseacave** [comment]
whatever cameras and poses you provide initially, they will remain constant for the entire OpenMVS pipeline; you must be doing something wrong importing COLMAP scene; you need to import the undistoreted scene (the same scene that is used by COLMAP to compute dense point cloud)
