### ISSUE TITLE
Why doesn't TextureMesh generate mesh texture.ply？

### ISSUE THREAD

**Issue by WeiqiangXie** [cdcseacave/openMVS#905]
Texturemes.exe generated the mesh_textex.ply file in openMVS_sample, but Texturemes.exe itself compiled on Windows did not generate the mesh_textex.ply file.

**Comment by cdcseacave** [comment]
by default it generates glb file
use command parameters to change

**Comment by WeiqiangXie** [comment]
> 

Thanks for your reply!When I changed the default parameter to ply in texturemes.cpp, the result was worse.

**Comment by WeiqiangXie** [comment]
![1](https://user-images.githubusercontent.com/87118799/203345772-1b3ed25e-bf23-4914-9128-63dd399f2b20.png)
![2](https://user-images.githubusercontent.com/87118799/203345830-a429f0e5-3176-46b8-bde8-8233d9e3acf1.png)
