### ISSUE TITLE
Lack of --cuda-device option in pre-compile binary of 2.1.0 release

### ISSUE THREAD

**Issue by nguyengiang41** [cdcseacave/openMVS#907]
**Describe the bug**
It's not really a bug, but I does not see the --cuda-device option to enable the GPU processing in DensifyPointCloud pre-compiled binary v2.1.0. This option does exist in pre compile binary of  v2.0.1 and v2.0 release. 

**To Reproduce**
1. Download openMVS v2.1.0 pre-compile binary release on github
2. Launch DensifyPointCloud.exe ( Windows )
3. Observe all proposed option on terminal

**Expected behavior**
--cuda-device option presented

**Screenshots**
![image](https://user-images.githubusercontent.com/18443054/204262538-a0382a99-e6d3-4975-84a8-217569ccf64c.png)
**Desktop (please complete the following information):**
 - OS: [Windows 8 x64]

I take a tour on CmakeList.txt of openMVS and saw that CUDA compilation option is ON by default. So, are the pre-compiled version intentionally remove --cuda-device option ?

**Comment by cdcseacave** [comment]
because CI does not support CUDA, I've replace the release with CUDA support compiled on my PC

**Comment by nguyengiang41** [comment]
Understand. The release is done by the CI. I'll test it. Thank you.
