### ISSUE TITLE
DensifyPointCloud "Assertion ISINSIDE failed"

### ISSUE THREAD

**Issue by FlachyJoe** [cdcseacave/openMVS#91]
Hi,
I'm testing OpenMVG+OpenMVS(master branch commit 7ecd86d) and get an error with DensifyPointCloud : Estimating and Filtering work great but after that it stops with this message : 

> Fused depth-maps 0 (0.00%, 1s, ETA 0ms)...DensifyPointCloud: /home/florian/Desktop/Photogrammetrie/Sources/openMVS/libs/MVS/SceneDensify.cpp:1358: void DepthMapsData::FuseDepthMaps(MVS::PointCloud&, bool): Assertion `ISINSIDE(depth, depthData.dMin, depthData.dMax)' failed.

The 28 Depth*.png are 1072x712px.
Filtered.ply have 115.000 to 750.000 vertices and seem good by previewing them in meshlab.

I comment the assertion line then recompile and it works. What is this warning for ?

Thanks !

**Comment by cdcseacave** [comment]
Please run the pipeline in release mode, it is possible that that assert to be too strict so it is safe to ignore it.

**Comment by FlachyJoe** [comment]
it runs fine, thank !
