### ISSUE TITLE
Texture map offset

### ISSUE THREAD

**Issue by YanHuaHuaHua** [cdcseacave/openMVS#914]
I used TextureMesh to complete the texture map,but textures are always offset.I only have a mesh 3d model , model pose matrix and  view.I used the model pose matrix as the camera extrinsics,I think there might be a problem here.If yes, how to convert the model pose matrix to camera pose matrix.

It would be appreciated if you could give me some suggestions, Thanks a lot.

![texture](https://user-images.githubusercontent.com/56535633/205794299-b100dfef-bee3-4401-a4ad-589cfadb17fe.png)
![textureModel](https://user-images.githubusercontent.com/56535633/205794309-ddb7adb9-daad-40e3-8cf9-1182c18ec6f9.png)

**Comment by cdcseacave** [comment]
I do not understand. How did you obtain the mesh?

**Comment by YanHuaHuaHua** [comment]
> 我不明白。你是如何获得网格的？

Fusion by scanning.
I configure "Platform" and "images" with data from the input folder.
`void mvs_TextureMesh()
{
	int number_of_thread = 1;
	Scene scene(number_of_thread);
	double k1, k2, k3, k4;
	k1 = 4.8186199030921453e+03;
	k2 = 4.8186199030921453e+03;
	k3 = 1.3832799110412598e+03;
	k4 = 5.7771776199340820e+02;

	Eigen::Matrix<double, 3, 3, Eigen::RowMajor> _k = Matrix3x3d::ZERO;
	_k(0, 0) = k1 / 1440.;
	_k(1, 1) = k2 / 1440.;
	_k(0, 2) = k3 / 1440.;
	_k(1, 2) = k4 / 1440.;
	_k(2, 2) = 1;

	{ 
		Platform& plat = scene.platforms.AddEmpty();
		plat.name = std::string("platform");

		CameraIntern& cam = plat.cameras.AddEmpty();
		cam.R = RMatrix::IDENTITY;
		cam.C = Point3(0, 0, 0);
		cam.K = _k;

		std::string matrix_path = "./input/Pos/";
		for (int k = 0; k <=10; ++k)
		{
			std::string _path = matrix_path + std::to_string(k) + ".txt";
			Eigen::Matrix<double,4,4, Eigen::RowMajor> temp;
			FILE* fp;
			fp = fopen(_path.data(),"r");
			for (size_t i = 0; i < 4; i++)
			{
				fscanf(fp, "%lf%lf%lf%lf",&temp(i,0) , &temp(i, 1), &temp(i, 2), &temp(i, 3));
			}
			fclose(fp);

			Platform::Pose& pose = plat.poses.AddEmpty();
			//c=-R.transpose()*T
			pose.C = -temp.block<3, 3>(0, 0).transpose()*temp.block<3, 1>(0, 3);
			pose.R = temp.block<3, 3>(0, 0);
			
		}
	}

	{
		std::string imag_path = "./input/Image/";
		for (int i = 0; i <=10; ++i) {
			std::string t_img = imag_path + std::to_string(i) + ".jpg";
			String _imgP(t_img);
			Image& _img = scene.images.AddEmpty();
			_img.ID = i;
			_img.platformID = 0;
			_img.cameraID = 0;
			_img.poseID = i;
			_img.LoadImage(_imgP);
			scene.images.push_back(_img);
		}
	}

	bool ree=scene.mesh.Load(std::string("./input/model/Mesh.ply"));
	unsigned nResolutionLevel = 0;
	unsigned nMinResolution = 1080;
	float fOutlierThreshold = 0.f;
	float fRatioDataSmoothness = 0.0f;
	bool bGlobalSeamLeveling = true;
	bool bLocalSeamLeveling = true;
	unsigned nTextureSizeMultiple = 0;
	unsigned nRectPackingHeuristic = 0;
	
	bool res = scene.TextureMesh(nResolutionLevel, nMinResolution, fOutlierThreshold,
		fRatioDataSmoothness, bGlobalSeamLeveling, bLocalSeamLeveling,
		nTextureSizeMultiple, nRectPackingHeuristic);
	scene.mesh.Save(std::string("./output/TEXTURE_Mesh.ply"));
}`
[input.zip](https://github.com/cdcseacave/openMVS/files/10172040/input.zip)

**Comment by YanHuaHuaHua** [comment]
> I do not understand. How did you obtain the mesh?

Sorry, I think I know why. The initial position of the model was changed by me, and it was normal after recovery.
I'm having two issues：
1，The orange triangle on the model is a bit much, is there a suitable way to clear it?
2，When there are many texture images, the run time is too long.
Hope to get your opinion.
[TEXTURE_Mesh.zip](https://github.com/cdcseacave/openMVS/files/10175959/TEXTURE_Mesh.zip)
