### ISSUE TITLE
Creating mesh from Point Cloud

### ISSUE THREAD

**Issue by satyajitghana** [cdcseacave/openMVS#916]
Hi,

I want to know what changes to the code would i have to make so i can run only the mesh reconstruction pipeline?

I have a point cloud and want to run the Delaunay triangulation meshing on it. The code with OpenMVS needs the cameras which i do not have, I've tried to change the code which needs the camera, by commenting those out.

What i get now is a graph-cut with some 5x10^6 flow, but the vertices and faces are 0, because `                if (ciType == graph.IsNodeOnSrcSide(cjID)) continue;` this does continue for all triangles in delaunay.

```
Point-cloud loaded: 820038 points (69ms)
loaded point cloud, points: 820038
indices length: 820038
Points inserted 820038 (100%, 3s279ms)           
init cells weights
Delaunay tetrahedralization completed: 820038 points -> 820038 vertices, 5099662 (+244) cells, 10199446 (+366) faces (3s543ms)L910
delaunay number of cells: 5099906
maxflow: 5.09991e+06
nEstimatedNumVerts: 820038
Delaunay tetrahedras graph-cut completed (5.09991e+06 flow): 0 vertices, 0 faces (2s338ms)
Fixed 0/0 non-manifold edges/vertices and 0 faces removed: 0 pyramid3 and 0 pyramid4 (0ms)
```

**Comment by cdcseacave** [comment]
it is easy, you can not use mesh reconstruction from OpenMVS without the cameras, pls use some other library, like poisson reconstruction
