### ISSUE TITLE
DensifyPointCloud.exe output file is empty

### ISSUE THREAD

**Issue by Isacc84** [cdcseacave/openMVS#917]
**DensifyPointCloud.exe output is empty**

1. When using openMVG_main_openMVG2openMVS.exe, put mvs files and pictures in two directories
↓
openMVG_main_openMVG2openMVS.exe -i C:\Users\13540\Desktop\rchat\reconstruction_sequential\sfm_data.bin -o C:\Users\13540\Desktop\test_openMVS\reconstruction_sequential\sfm_data.mvs -d C:\Users\13540\Desktop\test_openMVS\reconstruction_sequential\open_MVS

2. Use DensifyPointCloud to process sfm_data.mvs. Because the integrated graphics card is used, --cuda-device -2 is set
↓
DensifyPointCloud.exe  --cuda-device -2 -i C:\Users\13540\Desktop\test_openMVS\reconstruction_sequential\sfm_data.mvs -o C:\Users\13540\Desktop\test_openMVS\reconstruction_sequential\sfm_dat.mvs

log
11:31:23 [App     ] Build date: Nov 28 2022, 13:08:56
11:31:23 [App     ] CPU: AMD Ryzen 7 5800H with Radeon Graphics          (16 cores)
11:31:23 [App     ] RAM: 13.87GB Physical Memory 128.00TB Virtual Memory
11:31:23 [App     ] OS: Windows 8 x64
11:31:23 [App     ] Disk: 3.59GB (275.69GB) space
11:31:23 [App     ] SSE & AVX compatible CPU & OS detected
11:31:23 [App     ] Command line: DensifyPointCloud --cuda-device -2 -i C:\Users\13540\Desktop\caobi\reconstruction_sequential\sfm_data.mvs
11:31:23 [App     ] Camera model loaded: platform 0; camera  0; f 0.752x0.752; poses 31
11:31:23 [App     ] warning: uncalibrated image 'C:\Users\13540\Desktop\caobi\reconstruction_sequential/open_MVS/IMG_20221222_094039.jpg'
11:31:23 [App     ] warning: uncalibrated image 'C:\Users\13540\Desktop\caobi\reconstruction_sequential/open_MVS/IMG_20221222_094042.jpg'
11:31:23 [App     ] Scene loaded from interface format (14ms):
        33 images (31 calibrated) with a total of 470.81 MPixels (15.19 MPixels/image)
        2038 points, 0 vertices, 0 faces
11:31:23 [App     ] The camera directions mean is unbalanced; the scene will be considered unbounded (no ROI)
11:31:23 [App     ] Point-cloud composed of 2038 points with:
 - visibility info (6092 views - 2.99 views/point):
                0 points with 1- views (0.00)
             1237 points with 2  views (60.70)
              373 points with 3  views (18.30)
              428 points with 4+ views (21.00)
        2 min / 2.98921 mean (1.86225 std) / 18 max
11:31:25 [App     ] Preparing images for dense reconstruction completed: 33 images (1s473ms)
11:31:25 [App     ] error: reference image  26 has not enough images in view
11:31:25 [App     ] error: reference image  12 has not enough images in view
11:31:25 [App     ] error: reference image  30 has not enough images in view
11:31:25 [App     ] Selecting images for dense reconstruction completed: 28 images (5ms)
Geometric-consistent estimated depth-maps 28 (100%, 24s425ms)
Geometric-consistent estimated depth-maps 28 (100%, 16s196ms)
Filtered depth-maps 28 (100%, 2s384ms)
Fused depth-maps 6 (100%, 459ms)
11:32:09 [App     ] Depth-maps fused and filtered: 6 depth-maps, 773018 depths, 0 points (0%) (772ms)
11:32:09 [App     ] Densifying point-cloud completed: 0 points (45s357ms)
11:32:09 [App     ] Scene saved (4ms):
        33 images (31 calibrated)
        0 points, 0 vertices, 0 faces
11:32:09 [App     ] MEMORYINFO: {
11:32:09 [App     ]     PageFaultCount 3770333
11:32:09 [App     ]     PeakWorkingSetSize 1.25GB
11:32:09 [App     ]     WorkingSetSize 140.36MB
11:32:09 [App     ]     QuotaPeakPagedPoolUsage 217.77KB
11:32:09 [App     ]     QuotaPagedPoolUsage 210.09KB
11:32:09 [App     ]     QuotaPeakNonPagedPoolUsage 30.95KB
11:32:09 [App     ]     QuotaNonPagedPoolUsage 25.89KB
11:32:09 [App     ]     PagefileUsage 564.38MB
11:32:09 [App     ]     PeakPagefileUsage 1.44GB
11:32:09 [App     ] } ENDINFO

**Expected behavior**
Expected to get Dense Point-Cloud in sfm_data dense.mvs file, but there is no point after the outpit file is opened

![imag](https://user-images.githubusercontent.com/83857549/209049275-de5c23b1-9c79-4eac-ad62-23c3163e3fc3.png)

**Comment by cdcseacave** [comment]
OpenMVS works fine with goos input. In your case most probably the SfM is not good, and from the look of how the images are distributed and the sparsity of the point cloud I am sure there is an issue with how you acquired the images. Check the internet on how to take images for photogrammetry, there are many great tutorials, even on youtube

**Comment by Sanheiii** [comment]
I get the same error and was sure it would not be caused in the old version of OpenMVS, so I pulled both versions of the code while debugging to compare the values of the variables.
I found that imageData.camera.K was getting the wrong value in the new version, causing an error in SelectNeighborViews().
After I replaced GetK() and GetInvK() in Camera.h with the old version, OpenMVS worked fine.
```cpp
//// returns full K and the inverse of K (assuming standard K format)
//template<typename TYPE>
//inline TMatrix<TYPE,3,3> GetK(uint32_t width, uint32_t height) const {
//	ASSERT(width>0 && height>0);
//	const float scale(GetNormalizationScale(width, height));
//	if (K(0,2) != 0 || K(1,2) != 0)
//		return GetScaledK(scale);
//	ASSERT(ISZERO(K(0,1)));
//	return ComposeK(
//		TYPE(K(0,0)*scale), TYPE(K(1,1)*scale),
//		width, height );
//}
// returns full K and the inverse of K (assuming standard K format)
template<typename TYPE>
inline TMatrix<TYPE, 3, 3> GetK(uint32_t width, uint32_t height) const {
	ASSERT(width > 0 && height > 0);
	const float fScale(GetNormalizationScale(width, height));
	if (K(0, 2) == 0 && K(1, 2) == 0)
		return ComposeK(
			TYPE(K(0, 0) * fScale), TYPE(K(1, 1) * fScale),
			width, height);
	TMatrix<TYPE, 3, 3> fullK(TMatrix<TYPE, 3, 3>::IDENTITY);
	fullK(0, 0) = K(0, 0) * fScale;
	fullK(1, 1) = K(1, 1) * fScale;
	fullK(0, 2) = K(0, 2) * fScale;
	fullK(1, 2) = K(1, 2) * fScale;
	return fullK;
}
//template<typename TYPE>
//inline TMatrix<TYPE,3,3> GetInvK(uint32_t width, uint32_t height) const {
//	ASSERT(width>0 && height>0);
//	const float scale(GetNormalizationScale(width, height));
//	if (K(0,2) != 0 || K(1,2) != 0)
//		return InvK(GetScaledK(scale));
//	ASSERT(ISZERO(K(0,1)));
//	return ComposeInvK(
//		TYPE(K(0,0)*scale), TYPE(K(1,1)*scale),
//		width, height );
//}
template<typename TYPE>
inline TMatrix<TYPE, 3, 3> GetInvK(uint32_t width, uint32_t height) const {
	ASSERT(width > 0 && height > 0);
	const float fScale(GetNormalizationScale(width, height));
	if (K(0, 2) == 0 && K(1, 2) == 0)
		return ComposeInvK(
			TYPE(K(0, 0) * fScale), TYPE(K(1, 1) * fScale),
			width, height);
	TMatrix<TYPE, 3, 3> fullInvK(TMatrix<TYPE, 3, 3>::IDENTITY);
	fullInvK(0, 0) = TYPE(1) / (K(0, 0) * fScale);
	fullInvK(1, 1) = TYPE(1) / (K(1, 1) * fScale);
	fullInvK(0, 2) = -K(0, 2) * fScale * fullInvK(0, 0);
	fullInvK(1, 2) = -K(1, 2) * fScale * fullInvK(1, 1);
	return fullInvK;
}
```

**Comment by cdcseacave** [comment]
pls make sure you correctly create the MVS file

**Comment by Sanheiii** [comment]
Thanks for your reply, I updated openMVG2openMVS and it works fine
