### ISSUE TITLE
Relative path

### ISSUE THREAD

**Issue by FlachyJoe** [cdcseacave/openMVS#92]
Hi,
it seems .mvs files store relative paths to pictures instead of absolutes.
So it's not possible to use the file from a different folder than the one that has been used for creation.
As some error handlers are missing, processes can terminate on segfault due to this.

e.g.
`$ ReconstructMesh mvs/scene_dense.mvs`
`...`
`$ cd mvs`
`$ RefineMesh scene_dense_mesh.mvs`
`SegFault !`

Thks !

**Comment by cdcseacave** [comment]
I am not sure I understand! Exactly because OpenMVS uses relative path you ARE able to use other images later in the pipeline. Simply set the working directory to the new images folder!

**Comment by FlachyJoe** [comment]
The problem is not using the same file with another image set but the same file, the same image set but launch from a different path.
if I launch 
```
cd \home\flachy\mvs1\
ReconstructMesh scene_dense.mvs
```
or
```
cd \home\flachy\
ReconstructMesh mvs1\scene_dense.mvs
```
the pictures are not searched in the same directory, it disturbs me.

I don't find the documentation about the --working-folder option, is the --input relative to it ? Are the log and dmap store in it or in the current one ? All my test with this parameter result on silent exit without result or segfault...

**Comment by deusclovis** [comment]
hello, I am trying to run use your python script to run the openMVG openMVS pipeline, but it somehow stops when it tries to do the mesh reconstruction. I can get the dense reconstruction, but when it reaches the mesh reconstruction, i get a seg fault. I am wondering if my issue is similar to this one? 

This is my output when I run ./ReconstructMesh /root/pineapple_out/mvs/scene_dense.mvs manually:-

15:01:52 [App     ] Build date: Oct  8 2016, 11:06:01
15:01:52 [App     ] CPU: Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
15:01:52 [App     ] RAM: 7.80GB Physical Memory 2.00GB Virtual Memory
15:01:52 [App     ] OS: Linux 4.4.0-38-generic (x86_64)
15:01:52 [App     ] SSE & AVX compatible CPU & OS detected
15:01:52 [App     ] Command line: /root/pineapple_out/mvs/scene_dense.mvs
15:02:01 [App     ] Scene loaded (8s777ms):
	17 images (17 calibrated) with a total of 49.42 MPixels (2.91 MPixels/image)
	4295064 points, 0 vertices, 0 faces
Segmentation fault (core dumped)

Might you know why?

**Comment by FlachyJoe** [comment]
Hi,

My [script](https://github.com/cdcseacave/openMVS_sample/blob/master/MvgMvs_Pipeline.py) workarounds the relative path pseudo-issue so if a segfault occurs you have to look at another way.

Can you please share your datas or follow cDc recommendations "compile in debug mode and try to GDB the issue." ?
