### ISSUE TITLE
TextureMesh speed

### ISSUE THREAD

**Issue by YanHuaHuaHua** [cdcseacave/openMVS#920]
Hello, I used the TextureMesh function for texture mapping. I used 11 images and it took 62 seconds.No matter how many images I used, the run time was about the same.
1，Is there any way or modify the parameters to shorten the running time？
2，Can TextureMesh use CUDA?I have never used CUDA.
Here are the TextureMesh parameters I use.
`unsigned nResolutionLevel = 0;
	unsigned nMinResolution = minSize;
	unsigned minCommonCameras = 3;
	float fOutlierThreshold = 0.f;
	float fRatioDataSmoothness = 0.3f;
	bool bGlobalSeamLeveling = true;
	bool bLocalSeamLeveling = true;
	unsigned nTextureSizeMultiple = 0U;
	unsigned nRectPackingHeuristic = 3U;
	Pixel8U colEmpty = Pixel8U(255, 127, 39);
	float fSharpnessWeight = 0.5f;
scene.TextureMesh(nResolutionLevel, nMinResolution, minCommonCameras, 
		fOutlierThreshold, fRatioDataSmoothness, bGlobalSeamLeveling, bLocalSeamLeveling,
		nTextureSizeMultiple, nRectPackingHeuristic, colEmpty, fSharpnessWeight);` 

It would be appreciated if you could give me some suggestions, Thanks a lot.
![TEXTURE](https://user-images.githubusercontent.com/56535633/209740518-039837de-475d-4a66-8eb0-00c69dff5871.png)

**Comment by cdcseacave** [comment]
yes, there are several ways to influence the runtime, the simplest is decimating the mesh to have fewer triangles
yes, GPU can be used for speeding this process to some extent

**Comment by YanHuaHuaHua** [comment]
> yes, there are several ways to influence the runtime, the simplest is decimating the mesh to have fewer triangles yes, GPU can be used for speeding this process to some extent

Thanks for your answer.
I'm having another problem.Why is the model darkened after texture mapping?Even if I increase the brightness, the texture and picture are still not quite the same.
![0](https://user-images.githubusercontent.com/56535633/212540423-bbc06b35-fb10-4bcc-a186-b6bca2a1f7af.png)

**Comment by calmelo** [comment]
> GPU can be used for speeding this process to some extent

How can I use GPU to speed the texturemesh? I can't find 'cuda' about the texturemesh in the codes. It would be appreciated if you could give me some suggestions, Thanks a lot.

**Comment by cdcseacave** [comment]
there is no support currently, but it can be easily done by using OpenGL to project the mesh into each image
