### ISSUE TITLE
How to reconstruct mesh from depth map estimated by MVSNet.Focus on how to write a dmap file

### ISSUE THREAD

**Issue by Bill-WangJiLong** [cdcseacave/openMVS#923]
* What I want to do
** I want to get the point cloud model from the depth map estimated by MVSNet, and perform mesh reconstruction and texture mapping.
* What I have done
** I got the. mvs scene file containing pictures and camera parameters according to InterfaceMVSNet.cpp. At the same time, I also got the depth map and confidence map through mvsnet. However, the normal map and views map that make up the dmap file are missing.
![image](https://user-images.githubusercontent.com/62866119/210241743-ae97edac-0604-472a-96db-6a2f981af889.png)
* What I should do?
** I know that I should use Interface. h to get the Dmap file and then run DensifyPointCloud.cpp. But I am not clear about how to build the Dmap file. At the same time, I do not have normal map and views map. Will this affect my running DensifyPointCloud.cpp and subsequent mesh reconstruction?
Please give me some advice on the preparation of Dmap file and my workflow. Thank you very much

**Comment by cdcseacave** [comment]
depth-map fusion should work even if you do not have the normal and view map
as for how to create the DMAP file, not sure I understand what you do not understand; DMAP is nothing more than a bunch of matrices one for storing the depth for each pixel, other for storing the nnormal, and so on... you write whatever data you have, but at least the depths

**Comment by Bill-WangJiLong** [comment]
> depth-map fusion should work even if you do not have the normal and view map as for how to create the DMAP file, not sure I understand what you do not understand; DMAP is nothing more than a bunch of matrices one for storing the depth for each pixel, other for storing the nnormal, and so on... you write whatever data you have, but at least the depths

Thank you for your timely reply and guidance, which is very helpful to me！
For the preparation of the dmap file, can I pass the required parameters into MVS:: ExportDepthDataRaw(), so that I can get the dmap file directly?

**Comment by cdcseacave** [comment]
that is one way, or using `Interface.h` directly

**Comment by Bill-WangJiLong** [comment]
thx for your guidance.I will try it.

**Comment by Bill-WangJiLong** [comment]
I want to ask what the IDs in the dmap file mean. I don't have this data. Is it necessary to build the dmap file? If so, how can I get the ID of the reference view and neighbor view required by the dmap file from the camera parameters and other data?

**Comment by Bill-WangJiLong** [comment]
> that is one way, or using `Interface.h` directly

I want to ask what the IDs in the dmap file mean. I don't have this data. Is it necessary to build the dmap file? If so, how can I get the ID of the reference view and neighbor view required by the dmap file from the camera parameters and other data?

**Comment by Bill-WangJiLong** [comment]
I have solved the problem, and I have to praise your excellent work. It is really very easy to use！

**Comment by jiahaoji** [comment]
Hello！I meet the same problem. I want to use the .pfm depth maps obtained from a MVS network for further work with OpenMVS. Could you share how you solved this issue?

**Comment by cdcseacave** [comment]
using Interface.h or use the python scripts

See wiki
