### ISSUE TITLE
Photosynth Compatibility

### ISSUE THREAD

**Issue by jpwhitney** [cdcseacave/openMVS#93]
### Steps to reproduce the problem
Hi, looks like a great project.

I'm having some problems with openMVG, so what I'm wondering is this: is it possible to use openMVS with downloaded Photosynth files?

**Comment by pmoulon** [comment]
I think that you got your answer here https://github.com/openMVG/openMVG/issues/559

**Comment by cdcseacave** [comment]
I never used Photosynth. What is the file format and what it contains?

**Comment by jpwhitney** [comment]
I'm not sure.  I've decided to use openMVG pipeline for generating the camera poses and sparse pointcloud that openMVS can use to further process the scene.
