### ISSUE TITLE
Is there a way to further filter the point cloud without negatively impacting areas with low views?

### ISSUE THREAD

**Issue by 4CJ7T** [cdcseacave/openMVS#933]
Processed with low resolution depth maps and --number-views-fuse 5.
![noise](https://user-images.githubusercontent.com/108303308/213947067-a5087d47-257b-4026-abc0-4f31fea7ab26.jpg)
![VLAD](https://user-images.githubusercontent.com/108303308/213946895-44c59dc0-415f-490e-9af6-fb340e833ea8.jpg)

**Comment by cdcseacave** [comment]
The mesh reconstruction method implemented in OpenMVS can be seen as a way to filter out the outliers. Can you try to reconstruct the mesh and show only the vertices?

**Comment by cdcseacave** [comment]
You can also try visibility based filtering of the point cloud using `--filter-point-cloud`, ex:
```
DensifyPointCloud scene_dense.mvs --filter-point-cloud -1
```
