### ISSUE TITLE
An error in generating OpenMVS lib file

### ISSUE THREAD

**Issue by 1511607288** [cdcseacave/openMVS#938]
When I try this command "sudo make -j2 && sudo make instal" to generate OpenMVS lib file in Ubuntu18.04，it turns an error like this:

/home/jm/MVS/openMVS/libs/MVS/SceneReconstruct.cpp:1103:38: error: ‘(3.40282347e+38f * 9.99999975e-5f)’ is not a constant expression
   constexpr edge_cap_t maxCap(FLT_MAX*0.0001f);

and i don't know how to fix it....
Please help me, thank you!

**Comment by cdcseacave** [comment]
it seems the compiler you use does not fully support C++17
either upgrade the compiler or remove `constexpr`

**Comment by 1511607288** [comment]
Thank you so much , i changed two "constexpr" to "const", and it just worked.

**Comment by 1511607288** [comment]
> it seems the compiler you use does not fully support C++17 either upgrade the compiler or remove `constexpr`

Thank you so much , i changed two "constexpr" to "const", and it just worked.

**Comment by abhimanyuchadha96** [comment]
@1511607288 Which two did you change?

**Comment by 1511607288** [comment]
Sorry to reply your email late


I changed&nbsp;"constexpr" to "const" in the&nbsp;SceneReconstruct.cpp:1103:38 where the error happened.


It may be the problem that our&nbsp;compilers do not fully support C++17.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cdcseacave/openMVS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月3日(星期五) 上午7:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cdcseacave/openMVS] An error in generating OpenMVS lib file (Issue #938)





 
@1511607288 Which two did you change?

**Comment by Rurouni-z** [comment]
in [here](https://gcc.gnu.org/projects/cxx-status.html), you can see 

> C++17 mode is the default since GCC 11
so check your gcc vesion

> gcc --version  && g++ --version

and find how to upgrade your gcc and g++ in your system, for example: [how to install gcc11 in ubuntu18](https://blog.csdn.net/tytyvyibijk/article/details/123074333)

but it will get a waring,

> created by a different GCC executable

maybe you should restart(remove) the whole make progress, and for me, i just let it be
