### ISSUE TITLE
FR | Merging dense sub-scenes and alternative sub-scene split

### ISSUE THREAD

**Issue by 4CJ7T** [cdcseacave/openMVS#941]
https://github.com/cdcseacave/openMVS/issues/941#issuecomment-1445273863

**Comment by 4CJ7T** [comment]
Now that I'm remembering, a hidden option called `--sub-scene-file || --sub-scene-cluster-file` would be a QOL feature because of recurring IDs if converted externally. Image name would be the easiest to convert over.

**Comment by 4CJ7T** [comment]
```python
from argparse import ArgumentParser
from json import load
from os import makedirs, path
from sys import exit

parser = ArgumentParser()
parser.add_argument('--sfm_data', type=str, required=True, help='path to the SfM_Data scene')
parser.add_argument('--filtered_pairs', type=str, required=True, help='path to the filtered pairs')
parser.add_argument('--num_neighbors', type=int, default=8, help='number of neighbors per image')
parser.add_argument('--output', type=str, help='path to the output pair file')
args = parser.parse_args()

if path.splitext(args.sfm_data)[1] in ('.json', '.JSON'):
  with open(args.sfm_data) as file:
    data = load(file)
else:
  print('ERROR: SfM_Data scene is not a JSON file')
  exit()

idView, idPose = [], []
for i in range(len(data['views'])):
  idView.append(data['views'][i]['value']['ptr_wrapper']['data']['id_view'])
  idPose.append(data['views'][i]['value']['ptr_wrapper']['data']['id_pose'])

validViewIDs = []
for i in range(len(data['extrinsics'])):
  index = idPose.index(data['extrinsics'][i]['key'])
  validViewIDs.append(str(idView[index]))

ViewNeighbors = {}
with open(args.filtered_pairs) as file:
  while (line := file.readline().split()):
    if line[0] in validViewIDs:
      try:
        viewID = str(validViewIDs.index(line[0]))
        neighborID = str(validViewIDs.index(line[1]))
        if viewID in ViewNeighbors:
          ViewNeighbors[viewID] += [neighborID]
        else:
          ViewNeighbors.update({viewID:[neighborID]})
      except Exception:
        pass
  file.seek(0)
  while (line := file.readline().split()):
    if line[1] in validViewIDs:
      try:
        viewID = str(validViewIDs.index(line[1]))
        neighborID = str(validViewIDs.index(line[0]))
        if viewID in ViewNeighbors:
          ViewNeighbors[viewID] += [neighborID]
        else:
          ViewNeighbors.update({viewID:[neighborID]})
      except Exception:
        pass

if args.output != None:
  outputDir = args.output
else:
  outputDir = path.join(path.dirname(args.sfm_data),'cluster_pairs.txt')

with open(outputDir, 'w') as file:
  for x in ViewNeighbors:
    file.write(x + ' ' + ' '.join(ViewNeighbors[x][:args.num_neighbors]) + '\n')
```

**Comment by 4CJ7T** [comment]
`--fusion-mode` does not have an option to only fuse existing depth maps.
Will try going around it by using `--view-neighbors-file`.

**Comment by 4CJ7T** [comment]
Running tests
```python
from argparse import ArgumentParser
from json import load
from os import makedirs, path, remove, rename
import shutil
import subprocess

parser = ArgumentParser()
parser.add_argument('--sub_scene_file', type=str, required=True, help='path to the cluster pair file')
parser.add_argument('--depth_maps', type=str, required=True, help='path to the depth maps directory')
parser.add_argument('--mvs_dir', type=str, required=True, help='path to the MVS directory')
args = parser.parse_args()

with open(args.sub_scene_file) as file1:
  while (line := file1.readline().split()):
    for i in line:
      shutil.copy(path.join(args.depth_maps,'depth%04d.dmap' % int(i)),args.mvs_dir)
    with open(path.join(args.mvs_dir,'viewPairs.txt'), 'w') as file2:
      file2.write(' '.join(line) + '\n')
      for x in line[1:]:
        file2.write(x + ' ' + line[0] + '\n')
    command = str('DensifyPointCloud -i scene.mvs --view-neighbors-file viewPairs.txt --resolution-level 0 --max-resolution 2560 --number-views-fuse 5 --geometric-iters 0 --estimate-colors 0 --postprocess-dmaps 0 --estimate-roi 0 -w ' + args.mvs_dir)
    p1 = subprocess.Popen(command, shell=True)
    p1.wait()
    for x in line:
      if path.isfile(path.join(args.mvs_dir,'depth%04d.dmap' % int(x))):
        remove(path.join(args.mvs_dir,'depth%04d.dmap' % int(x)))
    try:
      rename(path.join(args.mvs_dir,'scene_dense.ply'),path.join(args.mvs_dir,'scene_%04d_dense.ply' % int(line[0])))
    except:
      pass
```

**Comment by 4CJ7T** [comment]
My GPU coils are making a noise I've never heard. As if it's covered in water making bubbly noises.

**Comment by 4CJ7T** [comment]
Snail Statue 227 Images
### Test01 - Neighbors: 8 | Resolution: 2560 | Fuse: 5
- Time: 66minutes Ran from 1:39AM to 2:45AM
- Memory: 4.6GB per cluster
- Coverage: Better than current sub scene split

**Comment by 4CJ7T** [comment]
Current sub-scene split using 660000
### Images
![snapshot00](https://user-images.githubusercontent.com/108303308/220734690-742a9a11-67c3-4601-8df1-2d7bcb4478ff.jpg)

**Comment by 4CJ7T** [comment]
### Test02 - Neighbors: 12 | Resolution: 2560 | Fuse: 5
- Time: 82 minutes
- Memory: 5.3GB per cluster
### Images
![snapshot00](https://user-images.githubusercontent.com/108303308/220761742-b25c2c17-6361-4943-80c4-8760ad48b01d.jpg)

**Comment by 4CJ7T** [comment]
### Test03 - Neighbors: 30 | Resolution: 2560 | Fuse: 5
- Time: 101 minutes
- Memory: 7GB per cluster
### Images
![snapshot00](https://user-images.githubusercontent.com/108303308/220808099-bcd3f29a-2633-4de1-9bab-b26c65e45647.jpg)

**Comment by 4CJ7T** [comment]
### Test04 - Neighbors: 3 | Resolution: 2560 | Fuse: 3 | Iters: 50
### Images
![snapshot04](https://user-images.githubusercontent.com/108303308/221043647-6c0e218b-a9e6-4fe9-81cd-84112cb02390.jpg)

**Comment by 4CJ7T** [comment]
script to merge scene_####_dense.ply
```python
from argparse import ArgumentParser
from glob import glob
import open3d as o3d
import os

parser = ArgumentParser()
parser.add_argument('--sub_scene_dir', type=str, required=True, help='path to the dense sub-scene directory')
parser.add_argument('--output', type=str, help='path to the output merged point cloud')
args = parser.parse_args()

filelist = glob(os.path.join(args.sub_scene_dir,'scene_*_dense.ply'))
pcd = o3d.io.read_point_cloud(filelist[0])
for f in filelist[1:]:
  pcd2 = o3d.io.read_point_cloud(f)
  pcd += pcd2

if args.output != None:
  outputDir = args.output
else:
  outputDir = os.path.join(args.sub_scene_dir,'scene_merged.ply')

o3d.io.write_point_cloud(outputDir, pcd)
```

**Comment by 4CJ7T** [comment]
### Test05 - Neighbors: all | Resolution: 2560 | Fuse: 5 | Iters: 4
### Images
![snapshot05](https://user-images.githubusercontent.com/108303308/221112895-21f6a818-d931-4d2a-a021-cf2cf67ecbf3.jpg)

**Comment by 4CJ7T** [comment]
### Test06 - Neighbors: 8 | Resolution: 2560 | Fuse: 5 | Iters: 40
### Images
![snapshot06](https://user-images.githubusercontent.com/108303308/221218381-e8fd131c-45c8-4095-8b44-1acc13c0d75e.jpg)

**Comment by 4CJ7T** [comment]
### Test07 - Neighbors: 12 | Resolution: 2560 | Fuse: 5 | Iters: 40
### Images
![snapshot07](https://user-images.githubusercontent.com/108303308/221249225-36ef93a8-5b4e-4da1-bfbf-6504c7fdbfc7.jpg)

**Comment by 4CJ7T** [comment]
### Test08 - Neighbors: 12 | Resolution: 2560 | Fuse: 5 | Iters: 50
### Images
![snapshot08](https://user-images.githubusercontent.com/108303308/221274561-3daf4702-2974-4394-b747-255b2ccbe048.jpg)

**Comment by 4CJ7T** [comment]
### Current | Resolution: 2560 | Fuse: 5 | Iters: 50
### Images
![snapshot09](https://user-images.githubusercontent.com/108303308/221309758-556d3862-90ba-4bba-9f01-e32fd347a969.jpg)

**Comment by 4CJ7T** [comment]
### Test10 - Neighbors: 30 | Resolution: 2560 | Fuse: 5 | Iters: 50
### Images
![snapshot10](https://user-images.githubusercontent.com/108303308/221331060-a8de3763-7574-4da0-9b23-c947236b3f84.jpg)

**Comment by 4CJ7T** [comment]
Pairs weren't sorted, I could use VLAD similarity scores but the scope would be incomplete. I'll try creating a multi-threaded pair generator using structure view maps.

**Comment by 4CJ7T** [comment]
Not multi-threaded but better than the last one.
```python
from argparse import ArgumentParser
from collections import Counter
from itertools import product
from json import load
from os import path
from sys import exit

parser = ArgumentParser()
parser.add_argument('--sfm_data', type=str, required=True, help='path to the SfM_Data scene')
parser.add_argument('--num_neighbors', type=int, default=12, help='number of neighbors per image')
parser.add_argument('--output', type=str, help='path to the output pair file')
args = parser.parse_args()

if path.splitext(args.sfm_data)[1] in ('.json', '.JSON'):
  with open(args.sfm_data) as file:
    data = load(file)
else:
  print('ERROR: SfM_Data scene is not a JSON file')
  exit()

idView, idPose = [], []
for i in range(len(data['views'])):
  idView.append(data['views'][i]['value']['ptr_wrapper']['data']['id_view'])
  idPose.append(data['views'][i]['value']['ptr_wrapper']['data']['id_pose'])

validViewIDs = []
for i in range(len(data['extrinsics'])):
  index = idPose.index(data['extrinsics'][i]['key'])
  validViewIDs.append(idView[index])

pairs = []
for x in data['structure']:
  observations = []
  for o in x['value']['observations']:
    observations.append(o['key'])
  pairs.append(list(product(observations, repeat=2)))

ViewNeighbors = {}
for x in pairs:
  for p in x:
    if p[0] in validViewIDs:
      try:
        viewID = validViewIDs.index(p[0])
        neighborID = str(validViewIDs.index(p[1]))
        if viewID in ViewNeighbors:
          ViewNeighbors[viewID] += [neighborID]
        else:
          ViewNeighbors.update({viewID:[neighborID]})
      except Exception:
        pass

for x in ViewNeighbors:
  ViewNeighbors[x] = list(j[0] for j in Counter(ViewNeighbors[x]).most_common()[1:])

ViewNeighbors = dict(sorted(ViewNeighbors.items()))

if args.output != None:
  outputDir = args.output
else:
  outputDir = path.join(path.dirname(args.sfm_data),'cluster_pairs.txt')

with open(outputDir, 'w') as file:
  for x in ViewNeighbors:
    file.write(str(x) + ' ' + ' '.join(ViewNeighbors[x][:args.num_neighbors]) + '\n')
```

**Comment by cdcseacave** [comment]
@4CJ7T you are doing a great work here!
Can you tell me what is exactly your end goal here? Like what is the end product your want to have, and for what you plan to use it?
I could help perhaps if I know more and I could guide you in your quest or in ways to improve OpenMVS.

**Comment by 4CJ7T** [comment]
I was running into an issue a while back with sub-scene scenes being incomplete, missing chunks, or bounding boxes overlapping. The tests at this point were to verify the completeness and I gotta say, great work on sub-scenes! It splits up nicely into memory friendly chunks and has great coverage... as long as you don't crop to ROI. I was thinking if we could get a scene merge feature and something for splitting it later on for meshing. If only scene merging were to be implemented, we could use the --import-roi-file option in the DensifyPointCloud module to update the ROI and create a makeshift splitter for the time being.
### Images
![snapshot00](https://user-images.githubusercontent.com/108303308/221392662-7aa1e135-f277-48d3-8695-8fb07b3cd986.jpg)
![snapshot00](https://user-images.githubusercontent.com/108303308/221392837-177d126e-c253-4146-8b29-b911704f45a5.png)

**Comment by cdcseacave** [comment]
Not sure I understand the issue with the ROIs. Anyway, great to hear that you tested this extensively and it works, nobody did so many tests, including me.

I like the sub-scene box drawing in the Viewer. Can you make a PR for that?

**Comment by 4CJ7T** [comment]
I still have to test different memory estimations and other datasets to make sure. The overlapping bounding boxes make it difficult to mesh. I was using Meshlab to view the bounding boxes and normals, I'll put the 2010 shaders below in case you're interested.

### Now that we have sub-scenes, what are your thoughts on fusing on the GPU?
    With memory roughly doubling as it fuses we should be able to load:
    24000MB / 2 = 12000MB / 549MB(6000x4000) = ~21 Images per cluster
    12000MB / 2 =  6000MB / 549MB(6000x4000) = ~10 Images per cluster
     8000MB / 2 =  4000MB / 549MB(6000x4000) =  ~7 Images per cluster
     6000MB / 2 =  3000MB / 549MB(6000x4000) =  ~5 Images per cluster
     4000MB / 2 =  2000MB / 549MB(6000x4000) =  ~3 Images per cluster
Depending on what the user wants, it may be enough especially with higher iterations as seen above. Quite exciting for setups with multiple GPUs!
- normalmap.frag
https://pastebin.com/e3uYr6Lc
- normalmap.gdp
https://pastebin.com/WZcBrdLg
- normalmap.vert
https://pastebin.com/xgwhaD5E

**Comment by cdcseacave** [comment]
What do you mean exactly by `fusion`? Pls describe exactly what is the input and desired output.

**Comment by 4CJ7T** [comment]
The input is a sub-scene, split by a new option to better constrain to set memory limits and fusing the depth maps.
The option would create one sub-scene per image using closely matched neighbors while knowing their file size.
(0 - disabled, >0 - max memory in MB, <0 - number of neighbors)

**Comment by 4CJ7T** [comment]
Never mind it was a silly idea.

**Comment by 4CJ7T** [comment]
Though, a fixed view neighbor count option for sub-scene split would be best but would require preset pairs for a singular view, for the correct outcome, to be either in the archive or exported along side the sub-scene.
###
    0 1 2 53 55    8 9 66 67 10
    1 0            9 8
    2 0            66 8
    53 0           67 8
    55 0           10 8
If the existing view selection isn't preferable, a pair file option for sub-scene could be used.
One sub-scene per line with preset pairs either in the archive or exported along side the sub-scene.
###
    0 1 2 53 55
    1 0 2 53 55
    2 1 0 3 53
    ...
    224 220 137 136 138
    225 138 221 139 224
    226 3 2 4 1

**Comment by 4CJ7T** [comment]
Merging the point clouds would have exceeded memory. It would have needed to load and cut for each ROI generated to not exceed memory.
