### ISSUE TITLE
--fusion-mode is missing the option to fuse existing depth maps only

### ISSUE THREAD

**Issue by 4CJ7T** [cdcseacave/openMVS#943]
I was trying some things in OpenMVS and found I couldn't stop depth map estimation. In one of the attempts using a low amount of structure points I succeeded in not generating more depth maps but given the opportunity to fuse, it did not.

**Comment by cdcseacave** [comment]
fusing existing depth-map happens automatically without any option, when the required depth-map files already exist where expected
