### ISSUE TITLE
Densify Step Doesn't run with  --archive-type -1

### ISSUE THREAD

**Issue by EliDavis3D** [cdcseacave/openMVS#956]
**Describe the bug**

When running **DensifyPointcloud**, things load in fine, and then it immediately completes, with the resulting point cloud PLY file being uncolored (all white), and each point is just the vertex found in the original mvs scene. 

Remove the --archive-type -1 allows the process to run, and the .ply is as you'd expect.

**To Reproduce**

1. DensifyPointCloud scene.mvs --archive-type -1
2. Observe undense pointcloud

**Expected behavior**
A densified pointcloud.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Latest stable release (Nov28 2022)

**Comment by 4CJ7T** [comment]
What made you choose -1?

**Comment by 4CJ7T** [comment]
This is user error. Available project archive types are 0-text, 1-binary, and 2-compressed binary.

**Comment by EliDavis3D** [comment]
This here
https://github.com/cdcseacave/openMVS/blob/f62b38d5d02266452bb16dbcf153963001c09f93/libs/Common/Types.inl#L3802

**Comment by 4CJ7T** [comment]
It seems -1 was for a different use case, a bit weird than to not run the module at all.
https://github.com/cdcseacave/openMVS/blob/6702bf463b5f867179968cdd56176f25667713da/apps/DensifyPointCloud/DensifyPointCloud.cpp#L372

**Comment by 4CJ7T** [comment]
It seems -1 was for a different use case. This option is useful for switching between dense and sparse without needing to change the inputs and outputs of other modules.
https://github.com/cdcseacave/openMVS/blob/6702bf463b5f867179968cdd56176f25667713da/apps/DensifyPointCloud/DensifyPointCloud.cpp#L372

**Comment by 4CJ7T** [comment]
Was added in https://github.com/cdcseacave/openMVS/commit/4f91c8f2158841ffe675edda25426c4be497da0e and has another use in `libs/MVS/Scene.cpp` under the `Scene::Save` function.

**Comment by cdcseacave** [comment]
if you have a different use-case in mind that can not be achieved with current functionality pls open a new issue
