### ISSUE TITLE
Delete small texture patches

### ISSUE THREAD

**Issue by Habsburgg** [cdcseacave/openMVS#963]
There are about 180,000 small texture blocks in the texture image. Is there a way to limit the number of small texture patches created, as this greatly affects speed.(I use the source code for texture mapping).
It would be appreciated if you could give me some suggestions, Thanks a lot.

**Comment by YanHuaHuaHua** [comment]
![Texture](https://user-images.githubusercontent.com/56535633/228535395-ff52cf58-6bbe-401c-aeef-ccd64ad6a8f7.png)

**Comment by cdcseacave** [comment]
yes, the simplest way is to decimate/pre-process the mesh to have fewer triangles and use that mesh instead of the one you get from mesh reconstruction; or just add the `--decimate 0.1` param and it will decimate the mesh automatically before texturing

**Comment by Habsburgg** [comment]
> yes, the simplest way is to decimate/pre-process the mesh to have fewer triangles and use that mesh instead of the one you get from mesh reconstruction; or just add the `--decimate 0.1` param and it will decimate the mesh automatically before texturing

Reducing the number of triangles may reduce the accuracy of the model. Can I combine small texture patches into large texture patches in the code?I'm not sure in which function to make the modification.

**Comment by Habsburgg** [comment]
I'm not sure if there's a way to modify the faces that correspond to those small texture patches here.
![20230329205834](https://user-images.githubusercontent.com/56535633/228543386-f8166b63-6abc-4e3c-a3c1-366f919c7948.png)

**Comment by Habsburgg** [comment]
After choosing the label for each triangle using LBP algorithm,get those triangles that are labeled differently from the surroundings,change the triangle's label makes them same.Always report an error.
is there any simpler way to solve the problem?
`if (labels[idxFace]!=NO_ID)
					{
						int num = 0;
						Label label(0);
						const Mesh::FaceFaces& afaces = faceFaces[idxFace];
						for (int v = 0; v < 3; ++v) 
						{
							const FIndex idxFaceAdj = afaces[v];
							if (idxFaceAdj == NO_ID)
								num++;
							else if (labels[idxFace]!= labels[idxFaceAdj])
							{
								num++;
								label = labels[idxFaceAdj];
							}
						}
						if (num>=3)
						{
							labels[idxFace] = label;
                                                 }`
![1](https://user-images.githubusercontent.com/56535633/229086113-cc3ff8be-f8a9-4364-84a2-ea362bb482ba.png)

**Comment by Habsburgg** [comment]
> you can set a label only to valid label, that is if that image is seeing that face

I tried it and only 1/10 of the triangles can be changed to the label of the surrounding faces.Is my method wrong?
if right,can I directly replace the data of the remaining triangles with the surrounding faces?
![1](https://user-images.githubusercontent.com/56535633/229466734-2458117e-b281-48e0-93ff-b3d535e1e5dd.png)

**Comment by Habsburgg** [comment]
Replacing the texture coordinates with those of the adjacent face seems to solve the problem for now.
Thanks for your guidance.
