### ISSUE TITLE
How to use ignore-mask-label

### ISSUE THREAD

**Issue by mcgilltaosun** [cdcseacave/openMVS#979]
**[Describe the question]**
Thanks for such a great code base! However, I'm confused about the usage of **--ignore-mask-label**. 

Please refer to the [command line and log] below, in my case, there seems to be no difference between using **--ignore-mask-label** and not using it (The number of generated points is almost the same). I suspect that I used this option incorrectly or my masks are not in the correct format. **so I would like to know the exact formatting requirements of the masks, and ask if there is a tutorial to generate correct masks for images.**

Attached are my the [sample of images and masks] for reference.

Looking forward to anyone's responses to this question, thanks!

**[Command line and Log]**
**Not using ignore-mask-label** :
_-Command line:_ 
[./DensifyPointCloud -i ./scene.mvs](url)
_-Log:_
 21:40:00 [App     ] Build date: Apr 25 2023, 18:13:09
21:40:00 [App     ] CPU: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 cores)
21:40:01 [App     ] RAM: 15.46GB Physical Memory 976.00MB Virtual Memory
21:40:01 [App     ] OS: Linux 4.15.0-142-generic (x86_64)
21:40:01 [App     ] SSE & AVX compatible CPU & OS detected
21:40:01 [App     ] Command line: -i ./scene.mvs
21:40:01 [App     ] Camera model loaded: platform 0; camera  0; f 0.621x0.621; poses 7
21:40:01 [App     ] Image loaded   0: 025.png
21:40:01 [App     ] Image loaded   1: 026.png
21:40:01 [App     ] Image loaded   2: 027.png
21:40:01 [App     ] Image loaded   3: 028.png
21:40:01 [App     ] Image loaded   4: 029.png
21:40:01 [App     ] Image loaded   5: 030.png
21:40:01 [App     ] Image loaded   6: 031.png
21:40:01 [App     ] Scene loaded from interface format (282ms):
	7 images (7 calibrated) with a total of 13.95 MPixels (1.99 MPixels/image)
	6316 points, 0 vertices, 0 faces
21:40:01 [App     ] Preparing images for dense reconstruction completed: 7 images (172ms)
21:40:01 [App     ] Selecting images for dense reconstruction completed: 7 images (5ms)
Estimated depth-maps 7 (100%, 1s703ms)              
Filtered depth-maps 7 (100%, 847ms)             
Fused depth-maps 7 (100%, 564ms)             
21:40:04 [App     ] Depth-maps fused and filtered: 7 depth-maps, 2728978 depths, 593592 points (22%%) (591ms)
21:40:05 [App     ] Densifying point-cloud completed: 593592 points (4s24ms)
21:40:07 [App     ] Scene saved (1s562ms):
	7 images (7 calibrated)
	593592 points, 0 vertices, 0 faces
21:40:07 [App     ] Point-cloud saved: 593592 points (136ms)
21:40:08 [App     ] MEMORYINFO: {
21:40:08 [App     ] 	VmPeak:	 1140292 kB
21:40:08 [App     ] 	VmSize:	 1123900 kB
21:40:08 [App     ] } ENDINFO

**Using ignore-mask-label** :
_-Command line:_
[./DensifyPointCloud -i ./scene.mvs --ignore-mask-label 255 --mask-path ./mask_binary](url)
_-Log:_
21:42:55 [App     ] Build date: Apr 25 2023, 18:13:09
21:42:55 [App     ] CPU: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 cores)
21:42:55 [App     ] RAM: 15.46GB Physical Memory 976.00MB Virtual Memory
21:42:55 [App     ] OS: Linux 4.15.0-142-generic (x86_64)
21:42:55 [App     ] SSE & AVX compatible CPU & OS detected
21:42:55 [App     ] Command line: -i ./scene.mvs --ignore-mask-label 255 --mask-path ./mask_binary
21:42:55 [App     ] Camera model loaded: platform 0; camera  0; f 0.621x0.621; poses 7
21:42:55 [App     ] Image loaded   0: 025.png
21:42:55 [App     ] Image loaded   1: 026.png
21:42:55 [App     ] Image loaded   2: 027.png
21:42:55 [App     ] Image loaded   3: 028.png
21:42:55 [App     ] Image loaded   4: 029.png
21:42:55 [App     ] Image loaded   5: 030.png
21:42:55 [App     ] Image loaded   6: 031.png
21:42:55 [App     ] Scene loaded from interface format (282ms):
	7 images (7 calibrated) with a total of 13.95 MPixels (1.99 MPixels/image)
	6316 points, 0 vertices, 0 faces
21:42:56 [App     ] Preparing images for dense reconstruction completed: 7 images (147ms)
21:42:56 [App     ] Selecting images for dense reconstruction completed: 7 images (2ms)
Estimated depth-maps 7 (100%, 1s546ms)              
Filtered depth-maps 7 (100%, 808ms)             
Fused depth-maps 7 (100%, 563ms)             
21:42:59 [App     ] Depth-maps fused and filtered: 7 depth-maps, 2728818 depths, 593665 points (22%%) (590ms)
21:42:59 [App     ] Densifying point-cloud completed: 593665 points (3s821ms)
21:43:01 [App     ] Scene saved (1s500ms):
	7 images (7 calibrated)
	593665 points, 0 vertices, 0 faces
21:43:01 [App     ] Point-cloud saved: 593665 points (130ms)
21:43:02 [App     ] MEMORYINFO: {
21:43:02 [App     ] 	VmPeak:	 1138768 kB
21:43:02 [App     ] 	VmSize:	 1122400 kB
21:43:02 [App     ] } ENDINFO

[Sample of images and masks]
_image(000.png):_ 
![Screenshot from 2023-04-25 22-20-44](https://user-images.githubusercontent.com/73679440/234190988-a0fdeb46-decf-4b30-9ff9-ad0bbcfa01d4.png)

_mask(000.mask.png):_ 
![Screenshot from 2023-04-25 22-18-57](https://user-images.githubusercontent.com/73679440/234190822-0ccd4343-6768-4861-8f06-dee5a3fab5f8.png)

**Comment by 4CJ7T** [comment]
0 - white; 1 - black
I have had issues with --mask-path. Another issue, when renaming the output folder, masks cannot be found.

**Comment by mcgilltaosun** [comment]
> 0 - white; 1 - black I have had issues with --mask-path.

Thank you for your response!
Do you mean I need to set --ignore-mask-label to 0 (to ignore black) or 1 (to ignore white)? I've tried that but it doesn't seem to work.

I am using the mask branch of OpenMVS and added _--mask-path_ according to  #940. It seems to be able to read the masks correctly with _--mask-path_, but as I mentioned before,  the masks didn't do the trick.

**Comment by mcgilltaosun** [comment]
> > 0 - white; 1 - black I have had issues with --mask-path.
> 
> Thank you for your response! Do you mean I need to set --ignore-mask-label to 0 (to ignore black) or 1 (to ignore white)? I've tried that but it doesn't seem to work.
> 
> I am using the mask branch of OpenMVS and added _--mask-path_ according to #940. It seems to be able to read the masks correctly with _--mask-path_, but as I mentioned before, the masks didn't do the trick.

Setting --ignore-mask-label to 0 (to ignore black) or 1 (to ignore white) is the right way.
