### ISSUE TITLE
--mask-path does not override maskName path in MVS scene.

### ISSUE THREAD

**Issue by 4CJ7T** [cdcseacave/openMVS#980]
--mask-path C:\...\mask_test\mvs\masks
```
error: Image C:/.../mask_test/mvs/images/DSC01161.JPG has non-empty maskName C:/.../mask_test/mvs/images/DSC01161.mask.png
```

**Comment by 4CJ7T** [comment]
@kenshi84 <3

**Comment by abhimanyuchadha96** [comment]
@cdcseacave  Any solution for this?

**Comment by cdcseacave** [comment]
it should be working, if not pls provide a small dataset that reproduces the problem on the latest develop code

**Comment by abhimanyuchadha96** [comment]
@cdcseacave I can't share the dataset but can share the directory structure and some examples.
<img width="211" alt="Screenshot 2024-08-12 at 10 27 24 PM" src="https://github.com/user-attachments/assets/2cb83df7-16b0-45cc-a8de-4a19a57c532c">

These are in the same folder and when passed to `openMVG` followed by `openMVS`

Some example results are here:-

<img width="1006" alt="Screenshot 2024-08-12 at 10 38 31 PM" src="https://github.com/user-attachments/assets/38b47a3c-d07b-4c56-9bbb-4a9c14b97ab4">
<img width="1006" alt="Screenshot 2024-08-12 at 10 38 37 PM" src="https://github.com/user-attachments/assets/824e27ae-e854-46e3-be32-413f1a42ce6a">
<img width="1006" alt="Screenshot 2024-08-12 at 10 39 48 PM" src="https://github.com/user-attachments/assets/3e6731c7-fd9b-4ef4-83e9-9ea8126cbc5a">

As you can see it is still picking up points outside the mask.
