### ISSUE TITLE
How to convert OBJ format to MVS file

### ISSUE THREAD

**Issue by Bryant666** [cdcseacave/openMVS#984]
Hello author, I obtained a mesh model (OBJ format) through other ways, I want to use the texture map module in the openMVS framework, what do I need to do (or what data), do I need to convert the OBJ format to MVS file?

**Comment by cdcseacave** [comment]
a mesh is not enough, you need to have the poses for all the images seeing that mesh

**Comment by Bryant666** [comment]
Bother you again.
Do I need to convert OBJ format to MVS files? If yes, how to convert a file in OBJ format to  MVS file. looking forward to your reply.
















在 2023-05-05 15:47:43，"cDc" ***@***.***> 写道：

a mesh is not enough, you need to have the poses for all the images seeing that mesh

**Comment by cdcseacave** [comment]
it seems that we do not understand eachother
