### ISSUE TITLE
Texture

### ISSUE THREAD

**Issue by Habsburgg** [cdcseacave/openMVS#986]
I experiment Texture a lot using OpenMVS code, the result is pretty good except a small problem, There are always a lot of triangles without texture, I make sure these triangles are visible in some pictures, how to assign proper texture to these triangles.
![test](https://github.com/cdcseacave/openMVS/assets/56535633/ad74a543-6025-4746-a4b9-d09ad7991b8c)

**Comment by Habsburgg** [comment]
Is there a suitable method without simplifying the model, looking forward to your answer.

**Comment by cdcseacave** [comment]
there is a simple solution: match the resolution of the mesh with the resolution of the images!
in short the mesh faces are smaller than one pixel area in the images
we could add an automatic way to compute the mesh decimation factor to match the image resolution, but for now just add a hardcoded factor ex to `TextureMesh`: `--decimate 0.3`

**Comment by Habsburgg** [comment]
Is it to use the clean function, but this will simplify the model.
![test](https://github.com/cdcseacave/openMVS/assets/56535633/224f97fc-12f3-471c-8d57-3966a85948d1)

**Comment by zxxsam** [comment]
I am also troubled by this problem.

**Comment by zxxsam** [comment]
How to fix it?

**Comment by cdcseacave** [comment]
> Is it to use the clean function, but this will simplify the model. ![test](https://user-images.githubusercontent.com/56535633/237548582-224f97fc-12f3-471c-8d57-3966a85948d1.png)

that is exactly what I am suggesting and what you should do

**Comment by zxxsam** [comment]
![image](https://github.com/cdcseacave/openMVS/assets/91625277/ce238955-d53f-4f14-9de8-785bbb0fd845)

**Comment by zxxsam** [comment]
There are many shaded places that are yellow, I just want to be able to interpolate to modify it, what position do I need to modify, can you give me some advice, thank you very much！ @cdcseacave

**Comment by zxxsam** [comment]
![image](https://github.com/cdcseacave/openMVS/assets/91625277/0cd2ace5-ba32-4120-9528-faf08a033bd8)

**Comment by Habsburgg** [comment]
@zxxsam You can refer to this answer #693  to remove the small orange triangle.

**Comment by Habsburgg** [comment]
> > Is it to use the clean function, but this will simplify the model. ![test](https://user-images.githubusercontent.com/56535633/237548582-224f97fc-12f3-471c-8d57-3966a85948d1.png)
> 
> that is exactly what I am suggesting and what you should do

thank you for your reply
