### ISSUE TITLE
[Question] DensifyPointCloud does not generate depth map (correct way to treat multiple cameras with different intrinsics)

### ISSUE THREAD

**Issue by park-sungjoon** [cdcseacave/openMVS#989]
**Problem**
I am trying to reconstruct dense point cloud using images taken from 8 synchronized cameras. To maximize the accuracy, I found the intrinsic parameters for each of the cameras. However, I am not sure what is the correct way to use these intrinsic parameters in the openMVG and openMVS pipeline.

**Details on what I have tried**
I am basically using `SfM_SequentialPipeline.py` in openMVG repository to generate sparse point cloud, which is then exported for use in openMVS with **openMVG_main_openMVG2openMVS**. I then use **DensifyPointCloud** to generate dense point cloud.

I have no problem generating dense point cloud when using the same camera intrinsics for all of the images (I called **openMVG_main_ConvertList** with option "-k f;0;ox;0,f;oy;0;0;1"). Of course I could just ignore slight differences in the camera intrinsic parameters. But if I were using cameras with largely different intrinsics, this would not work, and I was wondering what is the correct way to approach this problem.

What I have tried is as follows: 
In the documentation for image listing [(SfMInit_ImageListing),](https://openmvg.readthedocs.io/en/latest/software/SfM/SfMInit_ImageListing/) it is noted that for old version of openMVG, one can use **openMVG_main_ConvertList** to generate sfm_data.json, which is nice because I can insert the intrinsic parameters corresponding to each of the images.  Although I am using the latest branch for both openMVG, I noticed that this function is still available, so I tweaked the `SfM_SequentialPipeline.py` by using **openMVG_main_ConvertList** instead of **openMVG_main_SfMInit_ImageListing**. This seems to work without problem (sparse point cloud generated by openMVG looks good) until I call **DensifyPointCloud**, which generates errors like 
"error: opening file '/dataset/000000/scene_undistorted_images/depth0000.dmap' for reading depth-data"
Generated sfm_data.json: [sfm_data.zip](https://github.com/cdcseacave/openMVS/files/11475728/sfm_data.zip)
Full log for DensifyPointCloud: [DensifyPointCloud.log](https://github.com/cdcseacave/openMVS/files/11475598/DensifyPointCloud.log)

Any suggestions?

**Comment by cdcseacave** [comment]
I am not an expert of OpenMVG, but for sure there is a way to enter a custom list of images containing the instrinsics for each image. In the worst case you can generate the sfm_data.json image list yourself, it has a very simple format.

Once that is done, you do not have to do anything special in OpenMVS, it will simply use the calibrated list of cameras from the received MVS file.

All these is working, as for example I used ~100 synchronized cameras to capture this scene processed in OpenMVS: https://skfb.ly/ozPrp

**Comment by park-sungjoon** [comment]
@cdcseacave thanks for the reply. I have also tried to generate sfm_data.json manually but obtained similar error during DensifyPointCloud (sparse point cloud is correctly recovered when using openMVG so I thought this was an issue with openMVS). On the other hand, DensifyPointCloud works just fine when I use openMVG_main_SfMInit_ImageListing. Should I close this issue and ask the question in the openMVG community?
