### ISSUE TITLE
problem with DensifyPointCloud and ReconstructMesh

### ISSUE THREAD

**Issue by riyueshi** [cdcseacave/openMVS#99]
Hi,
  The software ReconstructMesh.exe works well in most case, but I got an bug while I use the absolute oriented coordinate (it works fine for some data), ReconstructMesh.exe returned 3 and exit without any information. I find that the one of  point's coordinate generated by DensifyPointCloud.exe is NAN(not a number) (the dense reconstruction process works fine). Is it necessary to confirm that all the points in the scene has an reasonable coordinate in the later version. And one more case while the coordinate of points is a very huge (to be specific x around 534000.0 and y around 3378500.0, which is the coordinate applied in China) the points generated by DensifyPointCloud.exe decrease to a line (solved by transfer the points to coordinate center), I think this would be a problem of coordinate output, hope can be solved in later version. 
  And now I got a problem didn't solved: I am working on how to make it possible to use openMVS run a large scale data set, since I use the absolute world coordinate I divide the large scene into small one by coordinate and crop the image according to the divide blocks. I want to do the process of divide after dense reconstruction (otherwise it will be lot of repeat work). but I find that the dense reconstruction require lot of memory too, so I use the param --resolution-level 3 (image resolution 8176*6132) to generate dense points, but it turned out failed. the points generated by DensifyPointCloud.exe is too much coarse (using 303 images, and the SFM Scene RMSE is 0.517 by openMVG ) which lead to a too much coarse initial mesh (generated by ReconstructMesh.exe) the result of ReconstructMesh.exe cannot provide an good initial mesh to be refined in the later process (part of the mesh is refined but remains lot of coarse mesh). My problem is whether it is possible to use the original image resolution to generate a points cloud which is not so dense but more accurate than the points generated by lower resolution (since we have refine process a very dense cloud seems not necessary, and a sparse point cloud can not meet the rmany building initial mesh in many case) (and I tried to skip the dense reconstruction process use openMVG to generate a denser sparse points by using params -p HIGH or ULTRA while compute features but it is such a time consume work). if there is any solution, in which part should I modify the code.
Miller Zhang

**Comment by cdcseacave** [comment]
Hi Miller,

What you are trying to do is a very complex problem and OpenMVS was not designed and/or tries to fill it. If interested in having this functionality, please use the full version of the pipeline: [3Dnovator](http://3dnovator.com) which supports all this plus much more.

As for the first issue with numerical errors, that is to be expected if you use absolute coordinates. Many parts of OpenMVS make use of single precision floating points and such big numbers are a huge problem. Ideally all input data to OpenMVS should be normalized. While normalization could be done on the fly inside OpenMVS, most of the processing, starting with the structure-from-motion stage, is sensitive to this, so it make more sense to normalize it once, not every step. Thus, you should Geo-refference the scene after dense reconstruction, not before, or normalize the coordinates before OpenMVS and restore them after.

**Comment by riyueshi** [comment]
Thanks for the quick reply and the illustrations. But I cannot find any link to download the software 3Dnovator on the website you linked to. how can I get the 3Dnovator?

**Comment by cdcseacave** [comment]
3Dnovator is not a standard 3D reconstruction pipeline you find on the market, it is designed to be used as a middleware, deeply integrated in a bigger project using this functionality. If interested, please write a intention message on the site describing a bit what you want and we start from there.
