### ISSUE TITLE
cmake build error (Ubuntu 20/04)

### ISSUE THREAD

**Issue by DimitrisKatsatos** [cdcseacave/openMVS#994]
I followed building instructions step-by-step but ran into some unexpected errors. I used the following commands:

- cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DVCG_DIR="$PATH/VCG" -DOpenCV_CAN_BREAK_BINARY_COMPATIBILITY=OFF 
- cmake --build . -j4
The first command was executed without errors, I used the forked version of @cdcseacave VSG lib (https://github.com/cdcseacave/VCG) and I also disabled CUDA in CMakeList. However, during building process I get these errors:

[ 72%] Linking CXX executable ../../bin/InterfaceMVSNet
/usr/bin/ld: cannot find -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [apps/InterfaceMVSNet/CMakeFiles/InterfaceMVSNet.dir/build.make:146: bin/InterfaceMVSNet] Error 1
make[1]: *** [CMakeFiles/Makefile2:625: apps/InterfaceMVSNet/CMakeFiles/InterfaceMVSNet.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
2 warnings generated.
[ 73%] Linking CXX executable ../../bin/DensifyPointCloud
/usr/bin/ld: cannot find -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [apps/DensifyPointCloud/CMakeFiles/DensifyPointCloud.dir/build.make:146: bin/DensifyPointCloud] Error 1
make[1]: *** [CMakeFiles/Makefile2:655: apps/DensifyPointCloud/CMakeFiles/DensifyPointCloud.dir/all] Error 2
2 warnings generated.
[ 74%] Linking CXX executable ../../bin/InterfaceMetashape
/usr/bin/ld: cannot find -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [apps/InterfaceMetashape/CMakeFiles/InterfaceMetashape.dir/build.make:146: bin/InterfaceMetashape] Error 1
make[1]: *** [CMakeFiles/Makefile2:595: apps/InterfaceMetashape/CMakeFiles/InterfaceMetashape.dir/all] Error 2
2 warnings generated.
[ 76%] Linking CXX executable ../../bin/InterfaceCOLMAP
/usr/bin/ld: cannot find -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [apps/InterfaceCOLMAP/CMakeFiles/InterfaceCOLMAP.dir/build.make:146: bin/InterfaceCOLMAP] Error 1
make[1]: *** [CMakeFiles/Makefile2:565: apps/InterfaceCOLMAP/CMakeFiles/InterfaceCOLMAP.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

 - OS: Ubuntu 20.04.5 LTS

**Comment by cdcseacave** [comment]
I've just built on ubuntu 20.04 using the instruction in BUILD.md and all works fine

**Comment by DimitrisKatsatos** [comment]
> I've just built on ubuntu 20.04 using the instruction in BUILD.md and all works fine

Ok, so it seems to be my problem. Do you have any suggestions as to what might be causing these errors?

**Comment by DimitrisKatsatos** [comment]
*Update* 
Problem solved using these commands:

1) cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DVCG_DIR="$PATH/vcglib" \
-DOpenCV_CAN_BREAK_BINARY_COMPATIBILITY=OFF \
-DCMAKE_TOOLCHAIN_FILE=$PATH/vcpkg/scripts/buildsystems/vcpkg.cmake
2)cmake --build
