### ISSUE TITLE
Mesh scale ratio

### ISSUE THREAD

**Issue by DimitrisKatsatos** [cdcseacave/openMVS#996]
I'm using COLMAP with OpenMVS to generate a textured mesh, and I obtain very accurate results. However, the final mesh seems to be scaled up by an unknown factor (i.e. the length of the surface was 1+ meters, and the one of the mesh surface was 10+ meters). Is there somewhere a scale ratio to adjust? I'm not sure if this is an issue of openMVS or COLMAP.

**Comment by cdcseacave** [comment]
it is easy to check, measure the scale of the COLMAP output (sparse point cloud)

**Comment by DimitrisKatsatos** [comment]
> it is easy to check, measure the scale of the COLMAP output (sparse point cloud)

It turns out that COLMAP was the source of the wrong scaling results. I tested out OpenMVG-OpenMVS and I can confirm that there is no scaling issue using this pipeline.
